# Generated by Django 5.1.6 on 2026-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_flag_aff_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='group',
            field=models.CharField(choices=[('priority', 'Priority'), ('nouns', 'Nouns'), ('adjectives', 'Adjectives'), ('reflexive_verbs', 'Reflexive verbs'), ('advanced', 'Advanced flags')], default='priority', max_length=16),
        ),
    ]
