import re
import os
from pathlib import Path

# Cross product generator: FG x Ob => GK
# Description:
# - Left block `FG`: FG
# - Right block `Ob`: Object markers
# - Output flag `GK`: Cross-product prefixes for FG x Ob

REPO_ROOT = Path(__file__).resolve().parents[1]
AFF_FILE = REPO_ROOT / "Luganda.aff"

# If set to a flag name (e.g. "HB"), the generated cross-product block will be inserted
# immediately before the first "PFX <flag>" line when the output flag block doesn't
# already exist in the .aff.
INSERT_BEFORE_FLAG = "".strip() or None

rule_left_raw = """
PFX FG Y 3380
PFX FG 0 wennaba .
PFX FG 0 wennagu .
PFX FG 0 wennagi .
PFX FG 0 wennazi .
PFX FG 0 wennaki .
PFX FG 0 wennabi .
PFX FG 0 wennali .
PFX FG 0 wennaga .
PFX FG 0 wennaka .
PFX FG 0 wennabu .
PFX FG 0 wennalu .
PFX FG 0 wennaku .
PFX FG 0 wennatu .
PFX FG 0 wennamu .
PFX FG 0 wewan [^lmnb]
PFX FG l wewand l.[^mn]
PFX FG l wewann l.[mn]
PFX FG w wewamp [w]
PFX FG 0 wewamu .
PFX FG 0 wewaba .
PFX FG 0 wewagu .
PFX FG 0 wewagi .
PFX FG 0 wewazi .
PFX FG 0 wewaki .
PFX FG 0 wewabi .
PFX FG 0 wewali .
PFX FG 0 wewaga .
PFX FG 0 wewaka .
PFX FG 0 wewabu .
PFX FG 0 wewalu .
PFX FG 0 wewaku .
PFX FG 0 wewatu .
PFX FG 0 weyan [^lmnb]
PFX FG l weyand l.[^mn]
PFX FG l weyann l.[mn]
PFX FG w weyamp [w]
PFX FG 0 weyamu .
PFX FG 0 weyaba .
PFX FG 0 weyagu .
PFX FG 0 weyagi .
PFX FG 0 weyazi .
PFX FG 0 weyaki .
PFX FG 0 weyabi .
PFX FG 0 weyali .
PFX FG 0 weyaga .
PFX FG 0 weyaka .
PFX FG 0 weyabu .
PFX FG 0 weyalu .
PFX FG 0 weyaku .
PFX FG 0 weyatu .
PFX FG 0 wetwan [^lmnb]
PFX FG l wetwand l.[^mn]
PFX FG l wetwann l.[mn]
PFX FG w wetwamp [w]
PFX FG 0 wetwamu .
PFX FG 0 wetwaba .
PFX FG 0 wetwagu .
PFX FG 0 wetwagi .
PFX FG 0 wetwazi .
PFX FG 0 wetwaki .
PFX FG 0 wetwabi .
PFX FG 0 wetwali .
PFX FG 0 wetwaga .
PFX FG 0 wetwaka .
PFX FG 0 wetwabu .
PFX FG 0 wetwalu .
PFX FG 0 wetwaku .
PFX FG 0 wetwatu .
PFX FG 0 wemwan [^lmnb]
PFX FG l wemwand l.[^mn]
PFX FG l wemwann l.[mn]
PFX FG w wemwamp [w]
PFX FG 0 wemwamu .
PFX FG 0 wemwaba .
PFX FG 0 wemwagu .
PFX FG 0 wemwagi .
PFX FG 0 wemwazi .
PFX FG 0 wemwaki .
PFX FG 0 wemwabi .
PFX FG 0 wemwali .
PFX FG 0 wemwaga .
PFX FG 0 wemwaka .
PFX FG 0 wemwabu .
PFX FG 0 wemwalu .
PFX FG 0 wemwaku .
PFX FG 0 wemwatu .
PFX FG 0 webaan [^lmnb]
PFX FG l webaand l.[^mn]
PFX FG l webaann l.[mn]
PFX FG w webaamp [w]
PFX FG 0 webaamu .
PFX FG 0 webaaba .
PFX FG 0 webaagu .
PFX FG 0 webaagi .
PFX FG 0 webaazi .
PFX FG 0 webaaki .
PFX FG 0 webaabi .
PFX FG 0 webaali .
PFX FG 0 webaaga .
PFX FG 0 webaaka .
PFX FG 0 webaabu .
PFX FG 0 webaalu .
PFX FG 0 webaaku .
PFX FG 0 webaatu .
PFX FG 0 wegwan [^lmnb]
PFX FG l wegwand l.[^mn]
PFX FG l wegwann l.[mn]
PFX FG w wegwamp [w]
PFX FG 0 wegwamu .
PFX FG 0 wegwaba .
PFX FG 0 wegwagu .
PFX FG 0 wegwagi .
PFX FG 0 wegwazi .
PFX FG 0 wegwaki .
PFX FG 0 wegwabi .
PFX FG 0 wegwali .
PFX FG 0 wegwaga .
PFX FG 0 wegwaka .
PFX FG 0 wegwabu .
PFX FG 0 wegwalu .
PFX FG 0 wegwaku .
PFX FG 0 wegwatu .
PFX FG 0 wegyan [^lmnb]
PFX FG l wegyand l.[^mn]
PFX FG l wegyann l.[mn]
PFX FG w wegyamp [w]
PFX FG 0 wegyamu .
PFX FG 0 wegyaba .
PFX FG 0 wegyagu .
PFX FG 0 wegyagi .
PFX FG 0 wegyazi .
PFX FG 0 wegyaki .
PFX FG 0 wegyabi .
PFX FG 0 wegyali .
PFX FG 0 wegyaga .
PFX FG 0 wegyaka .
PFX FG 0 wegyabu .
PFX FG 0 wegyalu .
PFX FG 0 wegyaku .
PFX FG 0 wegyatu .
PFX FG 0 wezaan [^lmnb]
PFX FG l wezaand l.[^mn]
PFX FG l wezaann l.[mn]
PFX FG w wezaamp [w]
PFX FG 0 wezaamu .
PFX FG 0 wezaaba .
PFX FG 0 wezaagu .
PFX FG 0 wezaagi .
PFX FG 0 wezaazi .
PFX FG 0 wezaaki .
PFX FG 0 wezaabi .
PFX FG 0 wezaali .
PFX FG 0 wezaaga .
PFX FG 0 wezaaka .
PFX FG 0 wezaabu .
PFX FG 0 wezaalu .
PFX FG 0 wezaaku .
PFX FG 0 wezaatu .
PFX FG 0 wekyaan [^lmnb]
PFX FG l wekyaand l.[^mn]
PFX FG l wekyaann l.[mn]
PFX FG w wekyaamp [w]
PFX FG 0 wekyaamu .
PFX FG 0 wekyaaba .
PFX FG 0 wekyaagu .
PFX FG 0 wekyaagi .
PFX FG 0 wekyaazi .
PFX FG 0 wekyaaki .
PFX FG 0 wekyaabi .
PFX FG 0 wekyaali .
PFX FG 0 wekyaaga .
PFX FG 0 wekyaaka .
PFX FG 0 wekyaabu .
PFX FG 0 wekyaalu .
PFX FG 0 wekyaaku .
PFX FG 0 wekyaatu .
PFX FG 0 webyaan [^lmnb]
PFX FG l webyaand l.[^mn]
PFX FG l webyaann l.[mn]
PFX FG w webyaamp [w]
PFX FG 0 webyaamu .
PFX FG 0 webyaaba .
PFX FG 0 webyaagu .
PFX FG 0 webyaagi .
PFX FG 0 webyaazi .
PFX FG 0 webyaaki .
PFX FG 0 webyaabi .
PFX FG 0 webyaali .
PFX FG 0 webyaaga .
PFX FG 0 webyaaka .
PFX FG 0 webyaabu .
PFX FG 0 webyaalu .
PFX FG 0 webyaaku .
PFX FG 0 webyaatu .
PFX FG 0 welyaan [^lmnb]
PFX FG l welyaand l.[^mn]
PFX FG l welyaann l.[mn]
PFX FG w welyaamp [w]
PFX FG 0 welyaamu .
PFX FG 0 welyaaba .
PFX FG 0 welyaagu .
PFX FG 0 welyaagi .
PFX FG 0 welyaazi .
PFX FG 0 welyaaki .
PFX FG 0 welyaabi .
PFX FG 0 welyaali .
PFX FG 0 welyaaga .
PFX FG 0 welyaaka .
PFX FG 0 welyaabu .
PFX FG 0 welyaalu .
PFX FG 0 welyaaku .
PFX FG 0 welyaatu .
PFX FG 0 wegaan [^lmnb]
PFX FG l wegaand l.[^mn]
PFX FG l wegaann l.[mn]
PFX FG w wegaamp [w]
PFX FG 0 wegaamu .
PFX FG 0 wegaaba .
PFX FG 0 wegaagu .
PFX FG 0 wegaagi .
PFX FG 0 wegaazi .
PFX FG 0 wegaaki .
PFX FG 0 wegaabi .
PFX FG 0 wegaali .
PFX FG 0 wegaaga .
PFX FG 0 wegaaka .
PFX FG 0 wegaabu .
PFX FG 0 wegaalu .
PFX FG 0 wegaaku .
PFX FG 0 wegaatu .
PFX FG 0 wekaan [^lmnb]
PFX FG l wekaand l.[^mn]
PFX FG l wekaann l.[mn]
PFX FG w wekaamp [w]
PFX FG 0 wekaamu .
PFX FG 0 wekaaba .
PFX FG 0 wekaagu .
PFX FG 0 wekaagi .
PFX FG 0 wekaazi .
PFX FG 0 wekaaki .
PFX FG 0 wekaabi .
PFX FG 0 wekaali .
PFX FG 0 wekaaga .
PFX FG 0 wekaaka .
PFX FG 0 wekaabu .
PFX FG 0 wekaalu .
PFX FG 0 wekaaku .
PFX FG 0 wekaatu .
PFX FG 0 webwan [^lmnb]
PFX FG l webwand l.[^mn]
PFX FG l webwann l.[mn]
PFX FG w webwamp [w]
PFX FG 0 webwamu .
PFX FG 0 webwaba .
PFX FG 0 webwagu .
PFX FG 0 webwagi .
PFX FG 0 webwazi .
PFX FG 0 webwaki .
PFX FG 0 webwabi .
PFX FG 0 webwali .
PFX FG 0 webwaga .
PFX FG 0 webwaka .
PFX FG 0 webwabu .
PFX FG 0 webwalu .
PFX FG 0 webwaku .
PFX FG 0 webwatu .
PFX FG 0 welwan [^lmnb]
PFX FG l welwand l.[^mn]
PFX FG l welwann l.[mn]
PFX FG w welwamp [w]
PFX FG 0 welwamu .
PFX FG 0 welwaba .
PFX FG 0 welwagu .
PFX FG 0 welwagi .
PFX FG 0 welwazi .
PFX FG 0 welwaki .
PFX FG 0 welwabi .
PFX FG 0 welwali .
PFX FG 0 welwaga .
PFX FG 0 welwaka .
PFX FG 0 welwabu .
PFX FG 0 welwalu .
PFX FG 0 welwaku .
PFX FG 0 welwatu .
PFX FG 0 wekwan [^lmnb]
PFX FG l wekwand l.[^mn]
PFX FG l wekwann l.[mn]
PFX FG w wekwamp [w]
PFX FG 0 wekwamu .
PFX FG 0 wekwaba .
PFX FG 0 wekwagu .
PFX FG 0 wekwagi .
PFX FG 0 wekwazi .
PFX FG 0 wekwaki .
PFX FG 0 wekwabi .
PFX FG 0 wekwali .
PFX FG 0 wekwaga .
PFX FG 0 wekwaka .
PFX FG 0 wekwabu .
PFX FG 0 wekwalu .
PFX FG 0 wekwaku .
PFX FG 0 wekwatu .
PFX FG 0 wegaan [^lmnb]
PFX FG l wegaand l.[^mn]
PFX FG l wegaann l.[mn]
PFX FG w wegaamp [w]
PFX FG 0 wegaamu .
PFX FG 0 wegaaba .
PFX FG 0 wegaagu .
PFX FG 0 wegaagi .
PFX FG 0 wegaazi .
PFX FG 0 wegaaki .
PFX FG 0 wegaabi .
PFX FG 0 wegaali .
PFX FG 0 wegaaga .
PFX FG 0 wegaaka .
PFX FG 0 wegaabu .
PFX FG 0 wegaalu .
PFX FG 0 wegaaku .
PFX FG 0 wegaatu .
PFX FG 0 wetwan [^lmnb]
PFX FG l wetwand l.[^mn]
PFX FG l wetwann l.[mn]
PFX FG w wetwamp [w]
PFX FG 0 wetwamu .
PFX FG 0 wetwaba .
PFX FG 0 wetwagu .
PFX FG 0 wetwagi .
PFX FG 0 wetwazi .
PFX FG 0 wetwaki .
PFX FG 0 wetwabi .
PFX FG 0 wetwali .
PFX FG 0 wetwaga .
PFX FG 0 wetwaka .
PFX FG 0 wetwabu .
PFX FG 0 wetwalu .
PFX FG 0 wetwaku .
PFX FG 0 wetwatu .
PFX FG 0 bwennaba .
PFX FG 0 bwennagu .
PFX FG 0 bwennagi .
PFX FG 0 bwennazi .
PFX FG 0 bwennaki .
PFX FG 0 bwennabi .
PFX FG 0 bwennali .
PFX FG 0 bwennaga .
PFX FG 0 bwennaka .
PFX FG 0 bwennabu .
PFX FG 0 bwennalu .
PFX FG 0 bwennaku .
PFX FG 0 bwennatu .
PFX FG 0 bwennamu .
PFX FG 0 bwewan [^lmnb]
PFX FG l bwewand l.[^mn]
PFX FG l bwewann l.[mn]
PFX FG w bwewamp [w]
PFX FG 0 bwewamu .
PFX FG 0 bwewaba .
PFX FG 0 bwewagu .
PFX FG 0 bwewagi .
PFX FG 0 bwewazi .
PFX FG 0 bwewaki .
PFX FG 0 bwewabi .
PFX FG 0 bwewali .
PFX FG 0 bwewaga .
PFX FG 0 bwewaka .
PFX FG 0 bwewabu .
PFX FG 0 bwewalu .
PFX FG 0 bwewaku .
PFX FG 0 bwewatu .
PFX FG 0 bweyan [^lmnb]
PFX FG l bweyand l.[^mn]
PFX FG l bweyann l.[mn]
PFX FG w bweyamp [w]
PFX FG 0 bweyamu .
PFX FG 0 bweyaba .
PFX FG 0 bweyagu .
PFX FG 0 bweyagi .
PFX FG 0 bweyazi .
PFX FG 0 bweyaki .
PFX FG 0 bweyabi .
PFX FG 0 bweyali .
PFX FG 0 bweyaga .
PFX FG 0 bweyaka .
PFX FG 0 bweyabu .
PFX FG 0 bweyalu .
PFX FG 0 bweyaku .
PFX FG 0 bweyatu .
PFX FG 0 bwetwan [^lmnb]
PFX FG l bwetwand l.[^mn]
PFX FG l bwetwann l.[mn]
PFX FG w bwetwamp [w]
PFX FG 0 bwetwamu .
PFX FG 0 bwetwaba .
PFX FG 0 bwetwagu .
PFX FG 0 bwetwagi .
PFX FG 0 bwetwazi .
PFX FG 0 bwetwaki .
PFX FG 0 bwetwabi .
PFX FG 0 bwetwali .
PFX FG 0 bwetwaga .
PFX FG 0 bwetwaka .
PFX FG 0 bwetwabu .
PFX FG 0 bwetwalu .
PFX FG 0 bwetwaku .
PFX FG 0 bwetwatu .
PFX FG 0 bwemwan [^lmnb]
PFX FG l bwemwand l.[^mn]
PFX FG l bwemwann l.[mn]
PFX FG w bwemwamp [w]
PFX FG 0 bwemwamu .
PFX FG 0 bwemwaba .
PFX FG 0 bwemwagu .
PFX FG 0 bwemwagi .
PFX FG 0 bwemwazi .
PFX FG 0 bwemwaki .
PFX FG 0 bwemwabi .
PFX FG 0 bwemwali .
PFX FG 0 bwemwaga .
PFX FG 0 bwemwaka .
PFX FG 0 bwemwabu .
PFX FG 0 bwemwalu .
PFX FG 0 bwemwaku .
PFX FG 0 bwemwatu .
PFX FG 0 bwebaan [^lmnb]
PFX FG l bwebaand l.[^mn]
PFX FG l bwebaann l.[mn]
PFX FG w bwebaamp [w]
PFX FG 0 bwebaamu .
PFX FG 0 bwebaaba .
PFX FG 0 bwebaagu .
PFX FG 0 bwebaagi .
PFX FG 0 bwebaazi .
PFX FG 0 bwebaaki .
PFX FG 0 bwebaabi .
PFX FG 0 bwebaali .
PFX FG 0 bwebaaga .
PFX FG 0 bwebaaka .
PFX FG 0 bwebaabu .
PFX FG 0 bwebaalu .
PFX FG 0 bwebaaku .
PFX FG 0 bwebaatu .
PFX FG 0 bwegwan [^lmnb]
PFX FG l bwegwand l.[^mn]
PFX FG l bwegwann l.[mn]
PFX FG w bwegwamp [w]
PFX FG 0 bwegwamu .
PFX FG 0 bwegwaba .
PFX FG 0 bwegwagu .
PFX FG 0 bwegwagi .
PFX FG 0 bwegwazi .
PFX FG 0 bwegwaki .
PFX FG 0 bwegwabi .
PFX FG 0 bwegwali .
PFX FG 0 bwegwaga .
PFX FG 0 bwegwaka .
PFX FG 0 bwegwabu .
PFX FG 0 bwegwalu .
PFX FG 0 bwegwaku .
PFX FG 0 bwegwatu .
PFX FG 0 bwegyan [^lmnb]
PFX FG l bwegyand l.[^mn]
PFX FG l bwegyann l.[mn]
PFX FG w bwegyamp [w]
PFX FG 0 bwegyamu .
PFX FG 0 bwegyaba .
PFX FG 0 bwegyagu .
PFX FG 0 bwegyagi .
PFX FG 0 bwegyazi .
PFX FG 0 bwegyaki .
PFX FG 0 bwegyabi .
PFX FG 0 bwegyali .
PFX FG 0 bwegyaga .
PFX FG 0 bwegyaka .
PFX FG 0 bwegyabu .
PFX FG 0 bwegyalu .
PFX FG 0 bwegyaku .
PFX FG 0 bwegyatu .
PFX FG 0 bwezaan [^lmnb]
PFX FG l bwezaand l.[^mn]
PFX FG l bwezaann l.[mn]
PFX FG w bwezaamp [w]
PFX FG 0 bwezaamu .
PFX FG 0 bwezaaba .
PFX FG 0 bwezaagu .
PFX FG 0 bwezaagi .
PFX FG 0 bwezaazi .
PFX FG 0 bwezaaki .
PFX FG 0 bwezaabi .
PFX FG 0 bwezaali .
PFX FG 0 bwezaaga .
PFX FG 0 bwezaaka .
PFX FG 0 bwezaabu .
PFX FG 0 bwezaalu .
PFX FG 0 bwezaaku .
PFX FG 0 bwezaatu .
PFX FG 0 bwekyaan [^lmnb]
PFX FG l bwekyaand l.[^mn]
PFX FG l bwekyaann l.[mn]
PFX FG w bwekyaamp [w]
PFX FG 0 bwekyaamu .
PFX FG 0 bwekyaaba .
PFX FG 0 bwekyaagu .
PFX FG 0 bwekyaagi .
PFX FG 0 bwekyaazi .
PFX FG 0 bwekyaaki .
PFX FG 0 bwekyaabi .
PFX FG 0 bwekyaali .
PFX FG 0 bwekyaaga .
PFX FG 0 bwekyaaka .
PFX FG 0 bwekyaabu .
PFX FG 0 bwekyaalu .
PFX FG 0 bwekyaaku .
PFX FG 0 bwekyaatu .
PFX FG 0 bwebyaan [^lmnb]
PFX FG l bwebyaand l.[^mn]
PFX FG l bwebyaann l.[mn]
PFX FG w bwebyaamp [w]
PFX FG 0 bwebyaamu .
PFX FG 0 bwebyaaba .
PFX FG 0 bwebyaagu .
PFX FG 0 bwebyaagi .
PFX FG 0 bwebyaazi .
PFX FG 0 bwebyaaki .
PFX FG 0 bwebyaabi .
PFX FG 0 bwebyaali .
PFX FG 0 bwebyaaga .
PFX FG 0 bwebyaaka .
PFX FG 0 bwebyaabu .
PFX FG 0 bwebyaalu .
PFX FG 0 bwebyaaku .
PFX FG 0 bwebyaatu .
PFX FG 0 bwelyaan [^lmnb]
PFX FG l bwelyaand l.[^mn]
PFX FG l bwelyaann l.[mn]
PFX FG w bwelyaamp [w]
PFX FG 0 bwelyaamu .
PFX FG 0 bwelyaaba .
PFX FG 0 bwelyaagu .
PFX FG 0 bwelyaagi .
PFX FG 0 bwelyaazi .
PFX FG 0 bwelyaaki .
PFX FG 0 bwelyaabi .
PFX FG 0 bwelyaali .
PFX FG 0 bwelyaaga .
PFX FG 0 bwelyaaka .
PFX FG 0 bwelyaabu .
PFX FG 0 bwelyaalu .
PFX FG 0 bwelyaaku .
PFX FG 0 bwelyaatu .
PFX FG 0 bwegaan [^lmnb]
PFX FG l bwegaand l.[^mn]
PFX FG l bwegaann l.[mn]
PFX FG w bwegaamp [w]
PFX FG 0 bwegaamu .
PFX FG 0 bwegaaba .
PFX FG 0 bwegaagu .
PFX FG 0 bwegaagi .
PFX FG 0 bwegaazi .
PFX FG 0 bwegaaki .
PFX FG 0 bwegaabi .
PFX FG 0 bwegaali .
PFX FG 0 bwegaaga .
PFX FG 0 bwegaaka .
PFX FG 0 bwegaabu .
PFX FG 0 bwegaalu .
PFX FG 0 bwegaaku .
PFX FG 0 bwegaatu .
PFX FG 0 bwekaan [^lmnb]
PFX FG l bwekaand l.[^mn]
PFX FG l bwekaann l.[mn]
PFX FG w bwekaamp [w]
PFX FG 0 bwekaamu .
PFX FG 0 bwekaaba .
PFX FG 0 bwekaagu .
PFX FG 0 bwekaagi .
PFX FG 0 bwekaazi .
PFX FG 0 bwekaaki .
PFX FG 0 bwekaabi .
PFX FG 0 bwekaali .
PFX FG 0 bwekaaga .
PFX FG 0 bwekaaka .
PFX FG 0 bwekaabu .
PFX FG 0 bwekaalu .
PFX FG 0 bwekaaku .
PFX FG 0 bwekaatu .
PFX FG 0 bwebwan [^lmnb]
PFX FG l bwebwand l.[^mn]
PFX FG l bwebwann l.[mn]
PFX FG w bwebwamp [w]
PFX FG 0 bwebwamu .
PFX FG 0 bwebwaba .
PFX FG 0 bwebwagu .
PFX FG 0 bwebwagi .
PFX FG 0 bwebwazi .
PFX FG 0 bwebwaki .
PFX FG 0 bwebwabi .
PFX FG 0 bwebwali .
PFX FG 0 bwebwaga .
PFX FG 0 bwebwaka .
PFX FG 0 bwebwabu .
PFX FG 0 bwebwalu .
PFX FG 0 bwebwaku .
PFX FG 0 bwebwatu .
PFX FG 0 bwelwan [^lmnb]
PFX FG l bwelwand l.[^mn]
PFX FG l bwelwann l.[mn]
PFX FG w bwelwamp [w]
PFX FG 0 bwelwamu .
PFX FG 0 bwelwaba .
PFX FG 0 bwelwagu .
PFX FG 0 bwelwagi .
PFX FG 0 bwelwazi .
PFX FG 0 bwelwaki .
PFX FG 0 bwelwabi .
PFX FG 0 bwelwali .
PFX FG 0 bwelwaga .
PFX FG 0 bwelwaka .
PFX FG 0 bwelwabu .
PFX FG 0 bwelwalu .
PFX FG 0 bwelwaku .
PFX FG 0 bwelwatu .
PFX FG 0 bwekwan [^lmnb]
PFX FG l bwekwand l.[^mn]
PFX FG l bwekwann l.[mn]
PFX FG w bwekwamp [w]
PFX FG 0 bwekwamu .
PFX FG 0 bwekwaba .
PFX FG 0 bwekwagu .
PFX FG 0 bwekwagi .
PFX FG 0 bwekwazi .
PFX FG 0 bwekwaki .
PFX FG 0 bwekwabi .
PFX FG 0 bwekwali .
PFX FG 0 bwekwaga .
PFX FG 0 bwekwaka .
PFX FG 0 bwekwabu .
PFX FG 0 bwekwalu .
PFX FG 0 bwekwaku .
PFX FG 0 bwekwatu .
PFX FG 0 bwegaan [^lmnb]
PFX FG l bwegaand l.[^mn]
PFX FG l bwegaann l.[mn]
PFX FG w bwegaamp [w]
PFX FG 0 bwegaamu .
PFX FG 0 bwegaaba .
PFX FG 0 bwegaagu .
PFX FG 0 bwegaagi .
PFX FG 0 bwegaazi .
PFX FG 0 bwegaaki .
PFX FG 0 bwegaabi .
PFX FG 0 bwegaali .
PFX FG 0 bwegaaga .
PFX FG 0 bwegaaka .
PFX FG 0 bwegaabu .
PFX FG 0 bwegaalu .
PFX FG 0 bwegaaku .
PFX FG 0 bwegaatu .
PFX FG 0 bwetwan [^lmnb]
PFX FG l bwetwand l.[^mn]
PFX FG l bwetwann l.[mn]
PFX FG w bwetwamp [w]
PFX FG 0 bwetwamu .
PFX FG 0 bwetwaba .
PFX FG 0 bwetwagu .
PFX FG 0 bwetwagi .
PFX FG 0 bwetwazi .
PFX FG 0 bwetwaki .
PFX FG 0 bwetwabi .
PFX FG 0 bwetwali .
PFX FG 0 bwetwaga .
PFX FG 0 bwetwaka .
PFX FG 0 bwetwabu .
PFX FG 0 bwetwalu .
PFX FG 0 bwetwaku .
PFX FG 0 bwetwatu .
PFX FG 0 lwennaba .
PFX FG 0 lwennagu .
PFX FG 0 lwennagi .
PFX FG 0 lwennazi .
PFX FG 0 lwennaki .
PFX FG 0 lwennabi .
PFX FG 0 lwennali .
PFX FG 0 lwennaga .
PFX FG 0 lwennaka .
PFX FG 0 lwennabu .
PFX FG 0 lwennalu .
PFX FG 0 lwennaku .
PFX FG 0 lwennatu .
PFX FG 0 lwennamu .
PFX FG 0 lwewan [^lmnb]
PFX FG l lwewand l.[^mn]
PFX FG l lwewann l.[mn]
PFX FG w lwewamp [w]
PFX FG 0 lwewamu .
PFX FG 0 lwewaba .
PFX FG 0 lwewagu .
PFX FG 0 lwewagi .
PFX FG 0 lwewazi .
PFX FG 0 lwewaki .
PFX FG 0 lwewabi .
PFX FG 0 lwewali .
PFX FG 0 lwewaga .
PFX FG 0 lwewaka .
PFX FG 0 lwewabu .
PFX FG 0 lwewalu .
PFX FG 0 lwewaku .
PFX FG 0 lwewatu .
PFX FG 0 lweyan [^lmnb]
PFX FG l lweyand l.[^mn]
PFX FG l lweyann l.[mn]
PFX FG w lweyamp [w]
PFX FG 0 lweyamu .
PFX FG 0 lweyaba .
PFX FG 0 lweyagu .
PFX FG 0 lweyagi .
PFX FG 0 lweyazi .
PFX FG 0 lweyaki .
PFX FG 0 lweyabi .
PFX FG 0 lweyali .
PFX FG 0 lweyaga .
PFX FG 0 lweyaka .
PFX FG 0 lweyabu .
PFX FG 0 lweyalu .
PFX FG 0 lweyaku .
PFX FG 0 lweyatu .
PFX FG 0 lwetwan [^lmnb]
PFX FG l lwetwand l.[^mn]
PFX FG l lwetwann l.[mn]
PFX FG w lwetwamp [w]
PFX FG 0 lwetwamu .
PFX FG 0 lwetwaba .
PFX FG 0 lwetwagu .
PFX FG 0 lwetwagi .
PFX FG 0 lwetwazi .
PFX FG 0 lwetwaki .
PFX FG 0 lwetwabi .
PFX FG 0 lwetwali .
PFX FG 0 lwetwaga .
PFX FG 0 lwetwaka .
PFX FG 0 lwetwabu .
PFX FG 0 lwetwalu .
PFX FG 0 lwetwaku .
PFX FG 0 lwetwatu .
PFX FG 0 lwemwan [^lmnb]
PFX FG l lwemwand l.[^mn]
PFX FG l lwemwann l.[mn]
PFX FG w lwemwamp [w]
PFX FG 0 lwemwamu .
PFX FG 0 lwemwaba .
PFX FG 0 lwemwagu .
PFX FG 0 lwemwagi .
PFX FG 0 lwemwazi .
PFX FG 0 lwemwaki .
PFX FG 0 lwemwabi .
PFX FG 0 lwemwali .
PFX FG 0 lwemwaga .
PFX FG 0 lwemwaka .
PFX FG 0 lwemwabu .
PFX FG 0 lwemwalu .
PFX FG 0 lwemwaku .
PFX FG 0 lwemwatu .
PFX FG 0 lwebaan [^lmnb]
PFX FG l lwebaand l.[^mn]
PFX FG l lwebaann l.[mn]
PFX FG w lwebaamp [w]
PFX FG 0 lwebaamu .
PFX FG 0 lwebaaba .
PFX FG 0 lwebaagu .
PFX FG 0 lwebaagi .
PFX FG 0 lwebaazi .
PFX FG 0 lwebaaki .
PFX FG 0 lwebaabi .
PFX FG 0 lwebaali .
PFX FG 0 lwebaaga .
PFX FG 0 lwebaaka .
PFX FG 0 lwebaabu .
PFX FG 0 lwebaalu .
PFX FG 0 lwebaaku .
PFX FG 0 lwebaatu .
PFX FG 0 lwegwan [^lmnb]
PFX FG l lwegwand l.[^mn]
PFX FG l lwegwann l.[mn]
PFX FG w lwegwamp [w]
PFX FG 0 lwegwamu .
PFX FG 0 lwegwaba .
PFX FG 0 lwegwagu .
PFX FG 0 lwegwagi .
PFX FG 0 lwegwazi .
PFX FG 0 lwegwaki .
PFX FG 0 lwegwabi .
PFX FG 0 lwegwali .
PFX FG 0 lwegwaga .
PFX FG 0 lwegwaka .
PFX FG 0 lwegwabu .
PFX FG 0 lwegwalu .
PFX FG 0 lwegwaku .
PFX FG 0 lwegwatu .
PFX FG 0 lwegyan [^lmnb]
PFX FG l lwegyand l.[^mn]
PFX FG l lwegyann l.[mn]
PFX FG w lwegyamp [w]
PFX FG 0 lwegyamu .
PFX FG 0 lwegyaba .
PFX FG 0 lwegyagu .
PFX FG 0 lwegyagi .
PFX FG 0 lwegyazi .
PFX FG 0 lwegyaki .
PFX FG 0 lwegyabi .
PFX FG 0 lwegyali .
PFX FG 0 lwegyaga .
PFX FG 0 lwegyaka .
PFX FG 0 lwegyabu .
PFX FG 0 lwegyalu .
PFX FG 0 lwegyaku .
PFX FG 0 lwegyatu .
PFX FG 0 lwezaan [^lmnb]
PFX FG l lwezaand l.[^mn]
PFX FG l lwezaann l.[mn]
PFX FG w lwezaamp [w]
PFX FG 0 lwezaamu .
PFX FG 0 lwezaaba .
PFX FG 0 lwezaagu .
PFX FG 0 lwezaagi .
PFX FG 0 lwezaazi .
PFX FG 0 lwezaaki .
PFX FG 0 lwezaabi .
PFX FG 0 lwezaali .
PFX FG 0 lwezaaga .
PFX FG 0 lwezaaka .
PFX FG 0 lwezaabu .
PFX FG 0 lwezaalu .
PFX FG 0 lwezaaku .
PFX FG 0 lwezaatu .
PFX FG 0 lwekyaan [^lmnb]
PFX FG l lwekyaand l.[^mn]
PFX FG l lwekyaann l.[mn]
PFX FG w lwekyaamp [w]
PFX FG 0 lwekyaamu .
PFX FG 0 lwekyaaba .
PFX FG 0 lwekyaagu .
PFX FG 0 lwekyaagi .
PFX FG 0 lwekyaazi .
PFX FG 0 lwekyaaki .
PFX FG 0 lwekyaabi .
PFX FG 0 lwekyaali .
PFX FG 0 lwekyaaga .
PFX FG 0 lwekyaaka .
PFX FG 0 lwekyaabu .
PFX FG 0 lwekyaalu .
PFX FG 0 lwekyaaku .
PFX FG 0 lwekyaatu .
PFX FG 0 lwebyaan [^lmnb]
PFX FG l lwebyaand l.[^mn]
PFX FG l lwebyaann l.[mn]
PFX FG w lwebyaamp [w]
PFX FG 0 lwebyaamu .
PFX FG 0 lwebyaaba .
PFX FG 0 lwebyaagu .
PFX FG 0 lwebyaagi .
PFX FG 0 lwebyaazi .
PFX FG 0 lwebyaaki .
PFX FG 0 lwebyaabi .
PFX FG 0 lwebyaali .
PFX FG 0 lwebyaaga .
PFX FG 0 lwebyaaka .
PFX FG 0 lwebyaabu .
PFX FG 0 lwebyaalu .
PFX FG 0 lwebyaaku .
PFX FG 0 lwebyaatu .
PFX FG 0 lwelyaan [^lmnb]
PFX FG l lwelyaand l.[^mn]
PFX FG l lwelyaann l.[mn]
PFX FG w lwelyaamp [w]
PFX FG 0 lwelyaamu .
PFX FG 0 lwelyaaba .
PFX FG 0 lwelyaagu .
PFX FG 0 lwelyaagi .
PFX FG 0 lwelyaazi .
PFX FG 0 lwelyaaki .
PFX FG 0 lwelyaabi .
PFX FG 0 lwelyaali .
PFX FG 0 lwelyaaga .
PFX FG 0 lwelyaaka .
PFX FG 0 lwelyaabu .
PFX FG 0 lwelyaalu .
PFX FG 0 lwelyaaku .
PFX FG 0 lwelyaatu .
PFX FG 0 lwegaan [^lmnb]
PFX FG l lwegaand l.[^mn]
PFX FG l lwegaann l.[mn]
PFX FG w lwegaamp [w]
PFX FG 0 lwegaamu .
PFX FG 0 lwegaaba .
PFX FG 0 lwegaagu .
PFX FG 0 lwegaagi .
PFX FG 0 lwegaazi .
PFX FG 0 lwegaaki .
PFX FG 0 lwegaabi .
PFX FG 0 lwegaali .
PFX FG 0 lwegaaga .
PFX FG 0 lwegaaka .
PFX FG 0 lwegaabu .
PFX FG 0 lwegaalu .
PFX FG 0 lwegaaku .
PFX FG 0 lwegaatu .
PFX FG 0 lwekaan [^lmnb]
PFX FG l lwekaand l.[^mn]
PFX FG l lwekaann l.[mn]
PFX FG w lwekaamp [w]
PFX FG 0 lwekaamu .
PFX FG 0 lwekaaba .
PFX FG 0 lwekaagu .
PFX FG 0 lwekaagi .
PFX FG 0 lwekaazi .
PFX FG 0 lwekaaki .
PFX FG 0 lwekaabi .
PFX FG 0 lwekaali .
PFX FG 0 lwekaaga .
PFX FG 0 lwekaaka .
PFX FG 0 lwekaabu .
PFX FG 0 lwekaalu .
PFX FG 0 lwekaaku .
PFX FG 0 lwekaatu .
PFX FG 0 lwebwan [^lmnb]
PFX FG l lwebwand l.[^mn]
PFX FG l lwebwann l.[mn]
PFX FG w lwebwamp [w]
PFX FG 0 lwebwamu .
PFX FG 0 lwebwaba .
PFX FG 0 lwebwagu .
PFX FG 0 lwebwagi .
PFX FG 0 lwebwazi .
PFX FG 0 lwebwaki .
PFX FG 0 lwebwabi .
PFX FG 0 lwebwali .
PFX FG 0 lwebwaga .
PFX FG 0 lwebwaka .
PFX FG 0 lwebwabu .
PFX FG 0 lwebwalu .
PFX FG 0 lwebwaku .
PFX FG 0 lwebwatu .
PFX FG 0 lwelwan [^lmnb]
PFX FG l lwelwand l.[^mn]
PFX FG l lwelwann l.[mn]
PFX FG w lwelwamp [w]
PFX FG 0 lwelwamu .
PFX FG 0 lwelwaba .
PFX FG 0 lwelwagu .
PFX FG 0 lwelwagi .
PFX FG 0 lwelwazi .
PFX FG 0 lwelwaki .
PFX FG 0 lwelwabi .
PFX FG 0 lwelwali .
PFX FG 0 lwelwaga .
PFX FG 0 lwelwaka .
PFX FG 0 lwelwabu .
PFX FG 0 lwelwalu .
PFX FG 0 lwelwaku .
PFX FG 0 lwelwatu .
PFX FG 0 lwekwan [^lmnb]
PFX FG l lwekwand l.[^mn]
PFX FG l lwekwann l.[mn]
PFX FG w lwekwamp [w]
PFX FG 0 lwekwamu .
PFX FG 0 lwekwaba .
PFX FG 0 lwekwagu .
PFX FG 0 lwekwagi .
PFX FG 0 lwekwazi .
PFX FG 0 lwekwaki .
PFX FG 0 lwekwabi .
PFX FG 0 lwekwali .
PFX FG 0 lwekwaga .
PFX FG 0 lwekwaka .
PFX FG 0 lwekwabu .
PFX FG 0 lwekwalu .
PFX FG 0 lwekwaku .
PFX FG 0 lwekwatu .
PFX FG 0 lwegaan [^lmnb]
PFX FG l lwegaand l.[^mn]
PFX FG l lwegaann l.[mn]
PFX FG w lwegaamp [w]
PFX FG 0 lwegaamu .
PFX FG 0 lwegaaba .
PFX FG 0 lwegaagu .
PFX FG 0 lwegaagi .
PFX FG 0 lwegaazi .
PFX FG 0 lwegaaki .
PFX FG 0 lwegaabi .
PFX FG 0 lwegaali .
PFX FG 0 lwegaaga .
PFX FG 0 lwegaaka .
PFX FG 0 lwegaabu .
PFX FG 0 lwegaalu .
PFX FG 0 lwegaaku .
PFX FG 0 lwegaatu .
PFX FG 0 lwetwan [^lmnb]
PFX FG l lwetwand l.[^mn]
PFX FG l lwetwann l.[mn]
PFX FG w lwetwamp [w]
PFX FG 0 lwetwamu .
PFX FG 0 lwetwaba .
PFX FG 0 lwetwagu .
PFX FG 0 lwetwagi .
PFX FG 0 lwetwazi .
PFX FG 0 lwetwaki .
PFX FG 0 lwetwabi .
PFX FG 0 lwetwali .
PFX FG 0 lwetwaga .
PFX FG 0 lwetwaka .
PFX FG 0 lwetwabu .
PFX FG 0 lwetwalu .
PFX FG 0 lwetwaku .
PFX FG 0 lwetwatu .
PFX FG 0 zennaba .
PFX FG 0 zennagu .
PFX FG 0 zennagi .
PFX FG 0 zennazi .
PFX FG 0 zennaki .
PFX FG 0 zennabi .
PFX FG 0 zennali .
PFX FG 0 zennaga .
PFX FG 0 zennaka .
PFX FG 0 zennabu .
PFX FG 0 zennalu .
PFX FG 0 zennaku .
PFX FG 0 zennatu .
PFX FG 0 zennamu .
PFX FG 0 zewan [^lmnb]
PFX FG l zewand l.[^mn]
PFX FG l zewann l.[mn]
PFX FG w zewamp [w]
PFX FG 0 zewamu .
PFX FG 0 zewaba .
PFX FG 0 zewagu .
PFX FG 0 zewagi .
PFX FG 0 zewazi .
PFX FG 0 zewaki .
PFX FG 0 zewabi .
PFX FG 0 zewali .
PFX FG 0 zewaga .
PFX FG 0 zewaka .
PFX FG 0 zewabu .
PFX FG 0 zewalu .
PFX FG 0 zewaku .
PFX FG 0 zewatu .
PFX FG 0 zeyan [^lmnb]
PFX FG l zeyand l.[^mn]
PFX FG l zeyann l.[mn]
PFX FG w zeyamp [w]
PFX FG 0 zeyamu .
PFX FG 0 zeyaba .
PFX FG 0 zeyagu .
PFX FG 0 zeyagi .
PFX FG 0 zeyazi .
PFX FG 0 zeyaki .
PFX FG 0 zeyabi .
PFX FG 0 zeyali .
PFX FG 0 zeyaga .
PFX FG 0 zeyaka .
PFX FG 0 zeyabu .
PFX FG 0 zeyalu .
PFX FG 0 zeyaku .
PFX FG 0 zeyatu .
PFX FG 0 zetwan [^lmnb]
PFX FG l zetwand l.[^mn]
PFX FG l zetwann l.[mn]
PFX FG w zetwamp [w]
PFX FG 0 zetwamu .
PFX FG 0 zetwaba .
PFX FG 0 zetwagu .
PFX FG 0 zetwagi .
PFX FG 0 zetwazi .
PFX FG 0 zetwaki .
PFX FG 0 zetwabi .
PFX FG 0 zetwali .
PFX FG 0 zetwaga .
PFX FG 0 zetwaka .
PFX FG 0 zetwabu .
PFX FG 0 zetwalu .
PFX FG 0 zetwaku .
PFX FG 0 zetwatu .
PFX FG 0 zemwan [^lmnb]
PFX FG l zemwand l.[^mn]
PFX FG l zemwann l.[mn]
PFX FG w zemwamp [w]
PFX FG 0 zemwamu .
PFX FG 0 zemwaba .
PFX FG 0 zemwagu .
PFX FG 0 zemwagi .
PFX FG 0 zemwazi .
PFX FG 0 zemwaki .
PFX FG 0 zemwabi .
PFX FG 0 zemwali .
PFX FG 0 zemwaga .
PFX FG 0 zemwaka .
PFX FG 0 zemwabu .
PFX FG 0 zemwalu .
PFX FG 0 zemwaku .
PFX FG 0 zemwatu .
PFX FG 0 zebaan [^lmnb]
PFX FG l zebaand l.[^mn]
PFX FG l zebaann l.[mn]
PFX FG w zebaamp [w]
PFX FG 0 zebaamu .
PFX FG 0 zebaaba .
PFX FG 0 zebaagu .
PFX FG 0 zebaagi .
PFX FG 0 zebaazi .
PFX FG 0 zebaaki .
PFX FG 0 zebaabi .
PFX FG 0 zebaali .
PFX FG 0 zebaaga .
PFX FG 0 zebaaka .
PFX FG 0 zebaabu .
PFX FG 0 zebaalu .
PFX FG 0 zebaaku .
PFX FG 0 zebaatu .
PFX FG 0 zegwan [^lmnb]
PFX FG l zegwand l.[^mn]
PFX FG l zegwann l.[mn]
PFX FG w zegwamp [w]
PFX FG 0 zegwamu .
PFX FG 0 zegwaba .
PFX FG 0 zegwagu .
PFX FG 0 zegwagi .
PFX FG 0 zegwazi .
PFX FG 0 zegwaki .
PFX FG 0 zegwabi .
PFX FG 0 zegwali .
PFX FG 0 zegwaga .
PFX FG 0 zegwaka .
PFX FG 0 zegwabu .
PFX FG 0 zegwalu .
PFX FG 0 zegwaku .
PFX FG 0 zegwatu .
PFX FG 0 zegyan [^lmnb]
PFX FG l zegyand l.[^mn]
PFX FG l zegyann l.[mn]
PFX FG w zegyamp [w]
PFX FG 0 zegyamu .
PFX FG 0 zegyaba .
PFX FG 0 zegyagu .
PFX FG 0 zegyagi .
PFX FG 0 zegyazi .
PFX FG 0 zegyaki .
PFX FG 0 zegyabi .
PFX FG 0 zegyali .
PFX FG 0 zegyaga .
PFX FG 0 zegyaka .
PFX FG 0 zegyabu .
PFX FG 0 zegyalu .
PFX FG 0 zegyaku .
PFX FG 0 zegyatu .
PFX FG 0 zezaan [^lmnb]
PFX FG l zezaand l.[^mn]
PFX FG l zezaann l.[mn]
PFX FG w zezaamp [w]
PFX FG 0 zezaamu .
PFX FG 0 zezaaba .
PFX FG 0 zezaagu .
PFX FG 0 zezaagi .
PFX FG 0 zezaazi .
PFX FG 0 zezaaki .
PFX FG 0 zezaabi .
PFX FG 0 zezaali .
PFX FG 0 zezaaga .
PFX FG 0 zezaaka .
PFX FG 0 zezaabu .
PFX FG 0 zezaalu .
PFX FG 0 zezaaku .
PFX FG 0 zezaatu .
PFX FG 0 zekyaan [^lmnb]
PFX FG l zekyaand l.[^mn]
PFX FG l zekyaann l.[mn]
PFX FG w zekyaamp [w]
PFX FG 0 zekyaamu .
PFX FG 0 zekyaaba .
PFX FG 0 zekyaagu .
PFX FG 0 zekyaagi .
PFX FG 0 zekyaazi .
PFX FG 0 zekyaaki .
PFX FG 0 zekyaabi .
PFX FG 0 zekyaali .
PFX FG 0 zekyaaga .
PFX FG 0 zekyaaka .
PFX FG 0 zekyaabu .
PFX FG 0 zekyaalu .
PFX FG 0 zekyaaku .
PFX FG 0 zekyaatu .
PFX FG 0 zebyaan [^lmnb]
PFX FG l zebyaand l.[^mn]
PFX FG l zebyaann l.[mn]
PFX FG w zebyaamp [w]
PFX FG 0 zebyaamu .
PFX FG 0 zebyaaba .
PFX FG 0 zebyaagu .
PFX FG 0 zebyaagi .
PFX FG 0 zebyaazi .
PFX FG 0 zebyaaki .
PFX FG 0 zebyaabi .
PFX FG 0 zebyaali .
PFX FG 0 zebyaaga .
PFX FG 0 zebyaaka .
PFX FG 0 zebyaabu .
PFX FG 0 zebyaalu .
PFX FG 0 zebyaaku .
PFX FG 0 zebyaatu .
PFX FG 0 zelyaan [^lmnb]
PFX FG l zelyaand l.[^mn]
PFX FG l zelyaann l.[mn]
PFX FG w zelyaamp [w]
PFX FG 0 zelyaamu .
PFX FG 0 zelyaaba .
PFX FG 0 zelyaagu .
PFX FG 0 zelyaagi .
PFX FG 0 zelyaazi .
PFX FG 0 zelyaaki .
PFX FG 0 zelyaabi .
PFX FG 0 zelyaali .
PFX FG 0 zelyaaga .
PFX FG 0 zelyaaka .
PFX FG 0 zelyaabu .
PFX FG 0 zelyaalu .
PFX FG 0 zelyaaku .
PFX FG 0 zelyaatu .
PFX FG 0 zegaan [^lmnb]
PFX FG l zegaand l.[^mn]
PFX FG l zegaann l.[mn]
PFX FG w zegaamp [w]
PFX FG 0 zegaamu .
PFX FG 0 zegaaba .
PFX FG 0 zegaagu .
PFX FG 0 zegaagi .
PFX FG 0 zegaazi .
PFX FG 0 zegaaki .
PFX FG 0 zegaabi .
PFX FG 0 zegaali .
PFX FG 0 zegaaga .
PFX FG 0 zegaaka .
PFX FG 0 zegaabu .
PFX FG 0 zegaalu .
PFX FG 0 zegaaku .
PFX FG 0 zegaatu .
PFX FG 0 zekaan [^lmnb]
PFX FG l zekaand l.[^mn]
PFX FG l zekaann l.[mn]
PFX FG w zekaamp [w]
PFX FG 0 zekaamu .
PFX FG 0 zekaaba .
PFX FG 0 zekaagu .
PFX FG 0 zekaagi .
PFX FG 0 zekaazi .
PFX FG 0 zekaaki .
PFX FG 0 zekaabi .
PFX FG 0 zekaali .
PFX FG 0 zekaaga .
PFX FG 0 zekaaka .
PFX FG 0 zekaabu .
PFX FG 0 zekaalu .
PFX FG 0 zekaaku .
PFX FG 0 zekaatu .
PFX FG 0 zebwan [^lmnb]
PFX FG l zebwand l.[^mn]
PFX FG l zebwann l.[mn]
PFX FG w zebwamp [w]
PFX FG 0 zebwamu .
PFX FG 0 zebwaba .
PFX FG 0 zebwagu .
PFX FG 0 zebwagi .
PFX FG 0 zebwazi .
PFX FG 0 zebwaki .
PFX FG 0 zebwabi .
PFX FG 0 zebwali .
PFX FG 0 zebwaga .
PFX FG 0 zebwaka .
PFX FG 0 zebwabu .
PFX FG 0 zebwalu .
PFX FG 0 zebwaku .
PFX FG 0 zebwatu .
PFX FG 0 zelwan [^lmnb]
PFX FG l zelwand l.[^mn]
PFX FG l zelwann l.[mn]
PFX FG w zelwamp [w]
PFX FG 0 zelwamu .
PFX FG 0 zelwaba .
PFX FG 0 zelwagu .
PFX FG 0 zelwagi .
PFX FG 0 zelwazi .
PFX FG 0 zelwaki .
PFX FG 0 zelwabi .
PFX FG 0 zelwali .
PFX FG 0 zelwaga .
PFX FG 0 zelwaka .
PFX FG 0 zelwabu .
PFX FG 0 zelwalu .
PFX FG 0 zelwaku .
PFX FG 0 zelwatu .
PFX FG 0 zekwan [^lmnb]
PFX FG l zekwand l.[^mn]
PFX FG l zekwann l.[mn]
PFX FG w zekwamp [w]
PFX FG 0 zekwamu .
PFX FG 0 zekwaba .
PFX FG 0 zekwagu .
PFX FG 0 zekwagi .
PFX FG 0 zekwazi .
PFX FG 0 zekwaki .
PFX FG 0 zekwabi .
PFX FG 0 zekwali .
PFX FG 0 zekwaga .
PFX FG 0 zekwaka .
PFX FG 0 zekwabu .
PFX FG 0 zekwalu .
PFX FG 0 zekwaku .
PFX FG 0 zekwatu .
PFX FG 0 zegaan [^lmnb]
PFX FG l zegaand l.[^mn]
PFX FG l zegaann l.[mn]
PFX FG w zegaamp [w]
PFX FG 0 zegaamu .
PFX FG 0 zegaaba .
PFX FG 0 zegaagu .
PFX FG 0 zegaagi .
PFX FG 0 zegaazi .
PFX FG 0 zegaaki .
PFX FG 0 zegaabi .
PFX FG 0 zegaali .
PFX FG 0 zegaaga .
PFX FG 0 zegaaka .
PFX FG 0 zegaabu .
PFX FG 0 zegaalu .
PFX FG 0 zegaaku .
PFX FG 0 zegaatu .
PFX FG 0 zetwan [^lmnb]
PFX FG l zetwand l.[^mn]
PFX FG l zetwann l.[mn]
PFX FG w zetwamp [w]
PFX FG 0 zetwamu .
PFX FG 0 zetwaba .
PFX FG 0 zetwagu .
PFX FG 0 zetwagi .
PFX FG 0 zetwazi .
PFX FG 0 zetwaki .
PFX FG 0 zetwabi .
PFX FG 0 zetwali .
PFX FG 0 zetwaga .
PFX FG 0 zetwaka .
PFX FG 0 zetwabu .
PFX FG 0 zetwalu .
PFX FG 0 zetwaku .
PFX FG 0 zetwatu .
PFX FG 0 gwennaba .
PFX FG 0 gwennagu .
PFX FG 0 gwennagi .
PFX FG 0 gwennazi .
PFX FG 0 gwennaki .
PFX FG 0 gwennabi .
PFX FG 0 gwennali .
PFX FG 0 gwennaga .
PFX FG 0 gwennaka .
PFX FG 0 gwennabu .
PFX FG 0 gwennalu .
PFX FG 0 gwennaku .
PFX FG 0 gwennatu .
PFX FG 0 gwennamu .
PFX FG 0 gwewan [^lmnb]
PFX FG l gwewand l.[^mn]
PFX FG l gwewann l.[mn]
PFX FG w gwewamp [w]
PFX FG 0 gwewamu .
PFX FG 0 gwewaba .
PFX FG 0 gwewagu .
PFX FG 0 gwewagi .
PFX FG 0 gwewazi .
PFX FG 0 gwewaki .
PFX FG 0 gwewabi .
PFX FG 0 gwewali .
PFX FG 0 gwewaga .
PFX FG 0 gwewaka .
PFX FG 0 gwewabu .
PFX FG 0 gwewalu .
PFX FG 0 gwewaku .
PFX FG 0 gwewatu .
PFX FG 0 gweyan [^lmnb]
PFX FG l gweyand l.[^mn]
PFX FG l gweyann l.[mn]
PFX FG w gweyamp [w]
PFX FG 0 gweyamu .
PFX FG 0 gweyaba .
PFX FG 0 gweyagu .
PFX FG 0 gweyagi .
PFX FG 0 gweyazi .
PFX FG 0 gweyaki .
PFX FG 0 gweyabi .
PFX FG 0 gweyali .
PFX FG 0 gweyaga .
PFX FG 0 gweyaka .
PFX FG 0 gweyabu .
PFX FG 0 gweyalu .
PFX FG 0 gweyaku .
PFX FG 0 gweyatu .
PFX FG 0 gwetwan [^lmnb]
PFX FG l gwetwand l.[^mn]
PFX FG l gwetwann l.[mn]
PFX FG w gwetwamp [w]
PFX FG 0 gwetwamu .
PFX FG 0 gwetwaba .
PFX FG 0 gwetwagu .
PFX FG 0 gwetwagi .
PFX FG 0 gwetwazi .
PFX FG 0 gwetwaki .
PFX FG 0 gwetwabi .
PFX FG 0 gwetwali .
PFX FG 0 gwetwaga .
PFX FG 0 gwetwaka .
PFX FG 0 gwetwabu .
PFX FG 0 gwetwalu .
PFX FG 0 gwetwaku .
PFX FG 0 gwetwatu .
PFX FG 0 gwemwan [^lmnb]
PFX FG l gwemwand l.[^mn]
PFX FG l gwemwann l.[mn]
PFX FG w gwemwamp [w]
PFX FG 0 gwemwamu .
PFX FG 0 gwemwaba .
PFX FG 0 gwemwagu .
PFX FG 0 gwemwagi .
PFX FG 0 gwemwazi .
PFX FG 0 gwemwaki .
PFX FG 0 gwemwabi .
PFX FG 0 gwemwali .
PFX FG 0 gwemwaga .
PFX FG 0 gwemwaka .
PFX FG 0 gwemwabu .
PFX FG 0 gwemwalu .
PFX FG 0 gwemwaku .
PFX FG 0 gwemwatu .
PFX FG 0 gwebaan [^lmnb]
PFX FG l gwebaand l.[^mn]
PFX FG l gwebaann l.[mn]
PFX FG w gwebaamp [w]
PFX FG 0 gwebaamu .
PFX FG 0 gwebaaba .
PFX FG 0 gwebaagu .
PFX FG 0 gwebaagi .
PFX FG 0 gwebaazi .
PFX FG 0 gwebaaki .
PFX FG 0 gwebaabi .
PFX FG 0 gwebaali .
PFX FG 0 gwebaaga .
PFX FG 0 gwebaaka .
PFX FG 0 gwebaabu .
PFX FG 0 gwebaalu .
PFX FG 0 gwebaaku .
PFX FG 0 gwebaatu .
PFX FG 0 gwegwan [^lmnb]
PFX FG l gwegwand l.[^mn]
PFX FG l gwegwann l.[mn]
PFX FG w gwegwamp [w]
PFX FG 0 gwegwamu .
PFX FG 0 gwegwaba .
PFX FG 0 gwegwagu .
PFX FG 0 gwegwagi .
PFX FG 0 gwegwazi .
PFX FG 0 gwegwaki .
PFX FG 0 gwegwabi .
PFX FG 0 gwegwali .
PFX FG 0 gwegwaga .
PFX FG 0 gwegwaka .
PFX FG 0 gwegwabu .
PFX FG 0 gwegwalu .
PFX FG 0 gwegwaku .
PFX FG 0 gwegwatu .
PFX FG 0 gwegyan [^lmnb]
PFX FG l gwegyand l.[^mn]
PFX FG l gwegyann l.[mn]
PFX FG w gwegyamp [w]
PFX FG 0 gwegyamu .
PFX FG 0 gwegyaba .
PFX FG 0 gwegyagu .
PFX FG 0 gwegyagi .
PFX FG 0 gwegyazi .
PFX FG 0 gwegyaki .
PFX FG 0 gwegyabi .
PFX FG 0 gwegyali .
PFX FG 0 gwegyaga .
PFX FG 0 gwegyaka .
PFX FG 0 gwegyabu .
PFX FG 0 gwegyalu .
PFX FG 0 gwegyaku .
PFX FG 0 gwegyatu .
PFX FG 0 gwezaan [^lmnb]
PFX FG l gwezaand l.[^mn]
PFX FG l gwezaann l.[mn]
PFX FG w gwezaamp [w]
PFX FG 0 gwezaamu .
PFX FG 0 gwezaaba .
PFX FG 0 gwezaagu .
PFX FG 0 gwezaagi .
PFX FG 0 gwezaazi .
PFX FG 0 gwezaaki .
PFX FG 0 gwezaabi .
PFX FG 0 gwezaali .
PFX FG 0 gwezaaga .
PFX FG 0 gwezaaka .
PFX FG 0 gwezaabu .
PFX FG 0 gwezaalu .
PFX FG 0 gwezaaku .
PFX FG 0 gwezaatu .
PFX FG 0 gwekyaan [^lmnb]
PFX FG l gwekyaand l.[^mn]
PFX FG l gwekyaann l.[mn]
PFX FG w gwekyaamp [w]
PFX FG 0 gwekyaamu .
PFX FG 0 gwekyaaba .
PFX FG 0 gwekyaagu .
PFX FG 0 gwekyaagi .
PFX FG 0 gwekyaazi .
PFX FG 0 gwekyaaki .
PFX FG 0 gwekyaabi .
PFX FG 0 gwekyaali .
PFX FG 0 gwekyaaga .
PFX FG 0 gwekyaaka .
PFX FG 0 gwekyaabu .
PFX FG 0 gwekyaalu .
PFX FG 0 gwekyaaku .
PFX FG 0 gwekyaatu .
PFX FG 0 gwebyaan [^lmnb]
PFX FG l gwebyaand l.[^mn]
PFX FG l gwebyaann l.[mn]
PFX FG w gwebyaamp [w]
PFX FG 0 gwebyaamu .
PFX FG 0 gwebyaaba .
PFX FG 0 gwebyaagu .
PFX FG 0 gwebyaagi .
PFX FG 0 gwebyaazi .
PFX FG 0 gwebyaaki .
PFX FG 0 gwebyaabi .
PFX FG 0 gwebyaali .
PFX FG 0 gwebyaaga .
PFX FG 0 gwebyaaka .
PFX FG 0 gwebyaabu .
PFX FG 0 gwebyaalu .
PFX FG 0 gwebyaaku .
PFX FG 0 gwebyaatu .
PFX FG 0 gwelyaan [^lmnb]
PFX FG l gwelyaand l.[^mn]
PFX FG l gwelyaann l.[mn]
PFX FG w gwelyaamp [w]
PFX FG 0 gwelyaamu .
PFX FG 0 gwelyaaba .
PFX FG 0 gwelyaagu .
PFX FG 0 gwelyaagi .
PFX FG 0 gwelyaazi .
PFX FG 0 gwelyaaki .
PFX FG 0 gwelyaabi .
PFX FG 0 gwelyaali .
PFX FG 0 gwelyaaga .
PFX FG 0 gwelyaaka .
PFX FG 0 gwelyaabu .
PFX FG 0 gwelyaalu .
PFX FG 0 gwelyaaku .
PFX FG 0 gwelyaatu .
PFX FG 0 gwegaan [^lmnb]
PFX FG l gwegaand l.[^mn]
PFX FG l gwegaann l.[mn]
PFX FG w gwegaamp [w]
PFX FG 0 gwegaamu .
PFX FG 0 gwegaaba .
PFX FG 0 gwegaagu .
PFX FG 0 gwegaagi .
PFX FG 0 gwegaazi .
PFX FG 0 gwegaaki .
PFX FG 0 gwegaabi .
PFX FG 0 gwegaali .
PFX FG 0 gwegaaga .
PFX FG 0 gwegaaka .
PFX FG 0 gwegaabu .
PFX FG 0 gwegaalu .
PFX FG 0 gwegaaku .
PFX FG 0 gwegaatu .
PFX FG 0 gwekaan [^lmnb]
PFX FG l gwekaand l.[^mn]
PFX FG l gwekaann l.[mn]
PFX FG w gwekaamp [w]
PFX FG 0 gwekaamu .
PFX FG 0 gwekaaba .
PFX FG 0 gwekaagu .
PFX FG 0 gwekaagi .
PFX FG 0 gwekaazi .
PFX FG 0 gwekaaki .
PFX FG 0 gwekaabi .
PFX FG 0 gwekaali .
PFX FG 0 gwekaaga .
PFX FG 0 gwekaaka .
PFX FG 0 gwekaabu .
PFX FG 0 gwekaalu .
PFX FG 0 gwekaaku .
PFX FG 0 gwekaatu .
PFX FG 0 gwebwan [^lmnb]
PFX FG l gwebwand l.[^mn]
PFX FG l gwebwann l.[mn]
PFX FG w gwebwamp [w]
PFX FG 0 gwebwamu .
PFX FG 0 gwebwaba .
PFX FG 0 gwebwagu .
PFX FG 0 gwebwagi .
PFX FG 0 gwebwazi .
PFX FG 0 gwebwaki .
PFX FG 0 gwebwabi .
PFX FG 0 gwebwali .
PFX FG 0 gwebwaga .
PFX FG 0 gwebwaka .
PFX FG 0 gwebwabu .
PFX FG 0 gwebwalu .
PFX FG 0 gwebwaku .
PFX FG 0 gwebwatu .
PFX FG 0 gwelwan [^lmnb]
PFX FG l gwelwand l.[^mn]
PFX FG l gwelwann l.[mn]
PFX FG w gwelwamp [w]
PFX FG 0 gwelwamu .
PFX FG 0 gwelwaba .
PFX FG 0 gwelwagu .
PFX FG 0 gwelwagi .
PFX FG 0 gwelwazi .
PFX FG 0 gwelwaki .
PFX FG 0 gwelwabi .
PFX FG 0 gwelwali .
PFX FG 0 gwelwaga .
PFX FG 0 gwelwaka .
PFX FG 0 gwelwabu .
PFX FG 0 gwelwalu .
PFX FG 0 gwelwaku .
PFX FG 0 gwelwatu .
PFX FG 0 gwekwan [^lmnb]
PFX FG l gwekwand l.[^mn]
PFX FG l gwekwann l.[mn]
PFX FG w gwekwamp [w]
PFX FG 0 gwekwamu .
PFX FG 0 gwekwaba .
PFX FG 0 gwekwagu .
PFX FG 0 gwekwagi .
PFX FG 0 gwekwazi .
PFX FG 0 gwekwaki .
PFX FG 0 gwekwabi .
PFX FG 0 gwekwali .
PFX FG 0 gwekwaga .
PFX FG 0 gwekwaka .
PFX FG 0 gwekwabu .
PFX FG 0 gwekwalu .
PFX FG 0 gwekwaku .
PFX FG 0 gwekwatu .
PFX FG 0 gwegaan [^lmnb]
PFX FG l gwegaand l.[^mn]
PFX FG l gwegaann l.[mn]
PFX FG w gwegaamp [w]
PFX FG 0 gwegaamu .
PFX FG 0 gwegaaba .
PFX FG 0 gwegaagu .
PFX FG 0 gwegaagi .
PFX FG 0 gwegaazi .
PFX FG 0 gwegaaki .
PFX FG 0 gwegaabi .
PFX FG 0 gwegaali .
PFX FG 0 gwegaaga .
PFX FG 0 gwegaaka .
PFX FG 0 gwegaabu .
PFX FG 0 gwegaalu .
PFX FG 0 gwegaaku .
PFX FG 0 gwegaatu .
PFX FG 0 gwetwan [^lmnb]
PFX FG l gwetwand l.[^mn]
PFX FG l gwetwann l.[mn]
PFX FG w gwetwamp [w]
PFX FG 0 gwetwamu .
PFX FG 0 gwetwaba .
PFX FG 0 gwetwagu .
PFX FG 0 gwetwagi .
PFX FG 0 gwetwazi .
PFX FG 0 gwetwaki .
PFX FG 0 gwetwabi .
PFX FG 0 gwetwali .
PFX FG 0 gwetwaga .
PFX FG 0 gwetwaka .
PFX FG 0 gwetwabu .
PFX FG 0 gwetwalu .
PFX FG 0 gwetwaku .
PFX FG 0 gwetwatu .
PFX FG 0 gyennaba .
PFX FG 0 gyennagu .
PFX FG 0 gyennagi .
PFX FG 0 gyennazi .
PFX FG 0 gyennaki .
PFX FG 0 gyennabi .
PFX FG 0 gyennali .
PFX FG 0 gyennaga .
PFX FG 0 gyennaka .
PFX FG 0 gyennabu .
PFX FG 0 gyennalu .
PFX FG 0 gyennaku .
PFX FG 0 gyennatu .
PFX FG 0 gyennamu .
PFX FG 0 gyewan [^lmnb]
PFX FG l gyewand l.[^mn]
PFX FG l gyewann l.[mn]
PFX FG w gyewamp [w]
PFX FG 0 gyewamu .
PFX FG 0 gyewaba .
PFX FG 0 gyewagu .
PFX FG 0 gyewagi .
PFX FG 0 gyewazi .
PFX FG 0 gyewaki .
PFX FG 0 gyewabi .
PFX FG 0 gyewali .
PFX FG 0 gyewaga .
PFX FG 0 gyewaka .
PFX FG 0 gyewabu .
PFX FG 0 gyewalu .
PFX FG 0 gyewaku .
PFX FG 0 gyewatu .
PFX FG 0 gyeyan [^lmnb]
PFX FG l gyeyand l.[^mn]
PFX FG l gyeyann l.[mn]
PFX FG w gyeyamp [w]
PFX FG 0 gyeyamu .
PFX FG 0 gyeyaba .
PFX FG 0 gyeyagu .
PFX FG 0 gyeyagi .
PFX FG 0 gyeyazi .
PFX FG 0 gyeyaki .
PFX FG 0 gyeyabi .
PFX FG 0 gyeyali .
PFX FG 0 gyeyaga .
PFX FG 0 gyeyaka .
PFX FG 0 gyeyabu .
PFX FG 0 gyeyalu .
PFX FG 0 gyeyaku .
PFX FG 0 gyeyatu .
PFX FG 0 gyetwan [^lmnb]
PFX FG l gyetwand l.[^mn]
PFX FG l gyetwann l.[mn]
PFX FG w gyetwamp [w]
PFX FG 0 gyetwamu .
PFX FG 0 gyetwaba .
PFX FG 0 gyetwagu .
PFX FG 0 gyetwagi .
PFX FG 0 gyetwazi .
PFX FG 0 gyetwaki .
PFX FG 0 gyetwabi .
PFX FG 0 gyetwali .
PFX FG 0 gyetwaga .
PFX FG 0 gyetwaka .
PFX FG 0 gyetwabu .
PFX FG 0 gyetwalu .
PFX FG 0 gyetwaku .
PFX FG 0 gyetwatu .
PFX FG 0 gyemwan [^lmnb]
PFX FG l gyemwand l.[^mn]
PFX FG l gyemwann l.[mn]
PFX FG w gyemwamp [w]
PFX FG 0 gyemwamu .
PFX FG 0 gyemwaba .
PFX FG 0 gyemwagu .
PFX FG 0 gyemwagi .
PFX FG 0 gyemwazi .
PFX FG 0 gyemwaki .
PFX FG 0 gyemwabi .
PFX FG 0 gyemwali .
PFX FG 0 gyemwaga .
PFX FG 0 gyemwaka .
PFX FG 0 gyemwabu .
PFX FG 0 gyemwalu .
PFX FG 0 gyemwaku .
PFX FG 0 gyemwatu .
PFX FG 0 gyebaan [^lmnb]
PFX FG l gyebaand l.[^mn]
PFX FG l gyebaann l.[mn]
PFX FG w gyebaamp [w]
PFX FG 0 gyebaamu .
PFX FG 0 gyebaaba .
PFX FG 0 gyebaagu .
PFX FG 0 gyebaagi .
PFX FG 0 gyebaazi .
PFX FG 0 gyebaaki .
PFX FG 0 gyebaabi .
PFX FG 0 gyebaali .
PFX FG 0 gyebaaga .
PFX FG 0 gyebaaka .
PFX FG 0 gyebaabu .
PFX FG 0 gyebaalu .
PFX FG 0 gyebaaku .
PFX FG 0 gyebaatu .
PFX FG 0 gyegwan [^lmnb]
PFX FG l gyegwand l.[^mn]
PFX FG l gyegwann l.[mn]
PFX FG w gyegwamp [w]
PFX FG 0 gyegwamu .
PFX FG 0 gyegwaba .
PFX FG 0 gyegwagu .
PFX FG 0 gyegwagi .
PFX FG 0 gyegwazi .
PFX FG 0 gyegwaki .
PFX FG 0 gyegwabi .
PFX FG 0 gyegwali .
PFX FG 0 gyegwaga .
PFX FG 0 gyegwaka .
PFX FG 0 gyegwabu .
PFX FG 0 gyegwalu .
PFX FG 0 gyegwaku .
PFX FG 0 gyegwatu .
PFX FG 0 gyegyan [^lmnb]
PFX FG l gyegyand l.[^mn]
PFX FG l gyegyann l.[mn]
PFX FG w gyegyamp [w]
PFX FG 0 gyegyamu .
PFX FG 0 gyegyaba .
PFX FG 0 gyegyagu .
PFX FG 0 gyegyagi .
PFX FG 0 gyegyazi .
PFX FG 0 gyegyaki .
PFX FG 0 gyegyabi .
PFX FG 0 gyegyali .
PFX FG 0 gyegyaga .
PFX FG 0 gyegyaka .
PFX FG 0 gyegyabu .
PFX FG 0 gyegyalu .
PFX FG 0 gyegyaku .
PFX FG 0 gyegyatu .
PFX FG 0 gyezaan [^lmnb]
PFX FG l gyezaand l.[^mn]
PFX FG l gyezaann l.[mn]
PFX FG w gyezaamp [w]
PFX FG 0 gyezaamu .
PFX FG 0 gyezaaba .
PFX FG 0 gyezaagu .
PFX FG 0 gyezaagi .
PFX FG 0 gyezaazi .
PFX FG 0 gyezaaki .
PFX FG 0 gyezaabi .
PFX FG 0 gyezaali .
PFX FG 0 gyezaaga .
PFX FG 0 gyezaaka .
PFX FG 0 gyezaabu .
PFX FG 0 gyezaalu .
PFX FG 0 gyezaaku .
PFX FG 0 gyezaatu .
PFX FG 0 gyekyaan [^lmnb]
PFX FG l gyekyaand l.[^mn]
PFX FG l gyekyaann l.[mn]
PFX FG w gyekyaamp [w]
PFX FG 0 gyekyaamu .
PFX FG 0 gyekyaaba .
PFX FG 0 gyekyaagu .
PFX FG 0 gyekyaagi .
PFX FG 0 gyekyaazi .
PFX FG 0 gyekyaaki .
PFX FG 0 gyekyaabi .
PFX FG 0 gyekyaali .
PFX FG 0 gyekyaaga .
PFX FG 0 gyekyaaka .
PFX FG 0 gyekyaabu .
PFX FG 0 gyekyaalu .
PFX FG 0 gyekyaaku .
PFX FG 0 gyekyaatu .
PFX FG 0 gyebyaan [^lmnb]
PFX FG l gyebyaand l.[^mn]
PFX FG l gyebyaann l.[mn]
PFX FG w gyebyaamp [w]
PFX FG 0 gyebyaamu .
PFX FG 0 gyebyaaba .
PFX FG 0 gyebyaagu .
PFX FG 0 gyebyaagi .
PFX FG 0 gyebyaazi .
PFX FG 0 gyebyaaki .
PFX FG 0 gyebyaabi .
PFX FG 0 gyebyaali .
PFX FG 0 gyebyaaga .
PFX FG 0 gyebyaaka .
PFX FG 0 gyebyaabu .
PFX FG 0 gyebyaalu .
PFX FG 0 gyebyaaku .
PFX FG 0 gyebyaatu .
PFX FG 0 gyelyaan [^lmnb]
PFX FG l gyelyaand l.[^mn]
PFX FG l gyelyaann l.[mn]
PFX FG w gyelyaamp [w]
PFX FG 0 gyelyaamu .
PFX FG 0 gyelyaaba .
PFX FG 0 gyelyaagu .
PFX FG 0 gyelyaagi .
PFX FG 0 gyelyaazi .
PFX FG 0 gyelyaaki .
PFX FG 0 gyelyaabi .
PFX FG 0 gyelyaali .
PFX FG 0 gyelyaaga .
PFX FG 0 gyelyaaka .
PFX FG 0 gyelyaabu .
PFX FG 0 gyelyaalu .
PFX FG 0 gyelyaaku .
PFX FG 0 gyelyaatu .
PFX FG 0 gyegaan [^lmnb]
PFX FG l gyegaand l.[^mn]
PFX FG l gyegaann l.[mn]
PFX FG w gyegaamp [w]
PFX FG 0 gyegaamu .
PFX FG 0 gyegaaba .
PFX FG 0 gyegaagu .
PFX FG 0 gyegaagi .
PFX FG 0 gyegaazi .
PFX FG 0 gyegaaki .
PFX FG 0 gyegaabi .
PFX FG 0 gyegaali .
PFX FG 0 gyegaaga .
PFX FG 0 gyegaaka .
PFX FG 0 gyegaabu .
PFX FG 0 gyegaalu .
PFX FG 0 gyegaaku .
PFX FG 0 gyegaatu .
PFX FG 0 gyekaan [^lmnb]
PFX FG l gyekaand l.[^mn]
PFX FG l gyekaann l.[mn]
PFX FG w gyekaamp [w]
PFX FG 0 gyekaamu .
PFX FG 0 gyekaaba .
PFX FG 0 gyekaagu .
PFX FG 0 gyekaagi .
PFX FG 0 gyekaazi .
PFX FG 0 gyekaaki .
PFX FG 0 gyekaabi .
PFX FG 0 gyekaali .
PFX FG 0 gyekaaga .
PFX FG 0 gyekaaka .
PFX FG 0 gyekaabu .
PFX FG 0 gyekaalu .
PFX FG 0 gyekaaku .
PFX FG 0 gyekaatu .
PFX FG 0 gyebwan [^lmnb]
PFX FG l gyebwand l.[^mn]
PFX FG l gyebwann l.[mn]
PFX FG w gyebwamp [w]
PFX FG 0 gyebwamu .
PFX FG 0 gyebwaba .
PFX FG 0 gyebwagu .
PFX FG 0 gyebwagi .
PFX FG 0 gyebwazi .
PFX FG 0 gyebwaki .
PFX FG 0 gyebwabi .
PFX FG 0 gyebwali .
PFX FG 0 gyebwaga .
PFX FG 0 gyebwaka .
PFX FG 0 gyebwabu .
PFX FG 0 gyebwalu .
PFX FG 0 gyebwaku .
PFX FG 0 gyebwatu .
PFX FG 0 gyelwan [^lmnb]
PFX FG l gyelwand l.[^mn]
PFX FG l gyelwann l.[mn]
PFX FG w gyelwamp [w]
PFX FG 0 gyelwamu .
PFX FG 0 gyelwaba .
PFX FG 0 gyelwagu .
PFX FG 0 gyelwagi .
PFX FG 0 gyelwazi .
PFX FG 0 gyelwaki .
PFX FG 0 gyelwabi .
PFX FG 0 gyelwali .
PFX FG 0 gyelwaga .
PFX FG 0 gyelwaka .
PFX FG 0 gyelwabu .
PFX FG 0 gyelwalu .
PFX FG 0 gyelwaku .
PFX FG 0 gyelwatu .
PFX FG 0 gyekwan [^lmnb]
PFX FG l gyekwand l.[^mn]
PFX FG l gyekwann l.[mn]
PFX FG w gyekwamp [w]
PFX FG 0 gyekwamu .
PFX FG 0 gyekwaba .
PFX FG 0 gyekwagu .
PFX FG 0 gyekwagi .
PFX FG 0 gyekwazi .
PFX FG 0 gyekwaki .
PFX FG 0 gyekwabi .
PFX FG 0 gyekwali .
PFX FG 0 gyekwaga .
PFX FG 0 gyekwaka .
PFX FG 0 gyekwabu .
PFX FG 0 gyekwalu .
PFX FG 0 gyekwaku .
PFX FG 0 gyekwatu .
PFX FG 0 gyegaan [^lmnb]
PFX FG l gyegaand l.[^mn]
PFX FG l gyegaann l.[mn]
PFX FG w gyegaamp [w]
PFX FG 0 gyegaamu .
PFX FG 0 gyegaaba .
PFX FG 0 gyegaagu .
PFX FG 0 gyegaagi .
PFX FG 0 gyegaazi .
PFX FG 0 gyegaaki .
PFX FG 0 gyegaabi .
PFX FG 0 gyegaali .
PFX FG 0 gyegaaga .
PFX FG 0 gyegaaka .
PFX FG 0 gyegaabu .
PFX FG 0 gyegaalu .
PFX FG 0 gyegaaku .
PFX FG 0 gyegaatu .
PFX FG 0 gyetwan [^lmnb]
PFX FG l gyetwand l.[^mn]
PFX FG l gyetwann l.[mn]
PFX FG w gyetwamp [w]
PFX FG 0 gyetwamu .
PFX FG 0 gyetwaba .
PFX FG 0 gyetwagu .
PFX FG 0 gyetwagi .
PFX FG 0 gyetwazi .
PFX FG 0 gyetwaki .
PFX FG 0 gyetwabi .
PFX FG 0 gyetwali .
PFX FG 0 gyetwaga .
PFX FG 0 gyetwaka .
PFX FG 0 gyetwabu .
PFX FG 0 gyetwalu .
PFX FG 0 gyetwaku .
PFX FG 0 gyetwatu .
PFX FG 0 kyennaba .
PFX FG 0 kyennagu .
PFX FG 0 kyennagi .
PFX FG 0 kyennazi .
PFX FG 0 kyennaki .
PFX FG 0 kyennabi .
PFX FG 0 kyennali .
PFX FG 0 kyennaga .
PFX FG 0 kyennaka .
PFX FG 0 kyennabu .
PFX FG 0 kyennalu .
PFX FG 0 kyennaku .
PFX FG 0 kyennatu .
PFX FG 0 kyennamu .
PFX FG 0 kyewan [^lmnb]
PFX FG l kyewand l.[^mn]
PFX FG l kyewann l.[mn]
PFX FG w kyewamp [w]
PFX FG 0 kyewamu .
PFX FG 0 kyewaba .
PFX FG 0 kyewagu .
PFX FG 0 kyewagi .
PFX FG 0 kyewazi .
PFX FG 0 kyewaki .
PFX FG 0 kyewabi .
PFX FG 0 kyewali .
PFX FG 0 kyewaga .
PFX FG 0 kyewaka .
PFX FG 0 kyewabu .
PFX FG 0 kyewalu .
PFX FG 0 kyewaku .
PFX FG 0 kyewatu .
PFX FG 0 kyeyan [^lmnb]
PFX FG l kyeyand l.[^mn]
PFX FG l kyeyann l.[mn]
PFX FG w kyeyamp [w]
PFX FG 0 kyeyamu .
PFX FG 0 kyeyaba .
PFX FG 0 kyeyagu .
PFX FG 0 kyeyagi .
PFX FG 0 kyeyazi .
PFX FG 0 kyeyaki .
PFX FG 0 kyeyabi .
PFX FG 0 kyeyali .
PFX FG 0 kyeyaga .
PFX FG 0 kyeyaka .
PFX FG 0 kyeyabu .
PFX FG 0 kyeyalu .
PFX FG 0 kyeyaku .
PFX FG 0 kyeyatu .
PFX FG 0 kyetwan [^lmnb]
PFX FG l kyetwand l.[^mn]
PFX FG l kyetwann l.[mn]
PFX FG w kyetwamp [w]
PFX FG 0 kyetwamu .
PFX FG 0 kyetwaba .
PFX FG 0 kyetwagu .
PFX FG 0 kyetwagi .
PFX FG 0 kyetwazi .
PFX FG 0 kyetwaki .
PFX FG 0 kyetwabi .
PFX FG 0 kyetwali .
PFX FG 0 kyetwaga .
PFX FG 0 kyetwaka .
PFX FG 0 kyetwabu .
PFX FG 0 kyetwalu .
PFX FG 0 kyetwaku .
PFX FG 0 kyetwatu .
PFX FG 0 kyemwan [^lmnb]
PFX FG l kyemwand l.[^mn]
PFX FG l kyemwann l.[mn]
PFX FG w kyemwamp [w]
PFX FG 0 kyemwamu .
PFX FG 0 kyemwaba .
PFX FG 0 kyemwagu .
PFX FG 0 kyemwagi .
PFX FG 0 kyemwazi .
PFX FG 0 kyemwaki .
PFX FG 0 kyemwabi .
PFX FG 0 kyemwali .
PFX FG 0 kyemwaga .
PFX FG 0 kyemwaka .
PFX FG 0 kyemwabu .
PFX FG 0 kyemwalu .
PFX FG 0 kyemwaku .
PFX FG 0 kyemwatu .
PFX FG 0 kyebaan [^lmnb]
PFX FG l kyebaand l.[^mn]
PFX FG l kyebaann l.[mn]
PFX FG w kyebaamp [w]
PFX FG 0 kyebaamu .
PFX FG 0 kyebaaba .
PFX FG 0 kyebaagu .
PFX FG 0 kyebaagi .
PFX FG 0 kyebaazi .
PFX FG 0 kyebaaki .
PFX FG 0 kyebaabi .
PFX FG 0 kyebaali .
PFX FG 0 kyebaaga .
PFX FG 0 kyebaaka .
PFX FG 0 kyebaabu .
PFX FG 0 kyebaalu .
PFX FG 0 kyebaaku .
PFX FG 0 kyebaatu .
PFX FG 0 kyegwan [^lmnb]
PFX FG l kyegwand l.[^mn]
PFX FG l kyegwann l.[mn]
PFX FG w kyegwamp [w]
PFX FG 0 kyegwamu .
PFX FG 0 kyegwaba .
PFX FG 0 kyegwagu .
PFX FG 0 kyegwagi .
PFX FG 0 kyegwazi .
PFX FG 0 kyegwaki .
PFX FG 0 kyegwabi .
PFX FG 0 kyegwali .
PFX FG 0 kyegwaga .
PFX FG 0 kyegwaka .
PFX FG 0 kyegwabu .
PFX FG 0 kyegwalu .
PFX FG 0 kyegwaku .
PFX FG 0 kyegwatu .
PFX FG 0 kyegyan [^lmnb]
PFX FG l kyegyand l.[^mn]
PFX FG l kyegyann l.[mn]
PFX FG w kyegyamp [w]
PFX FG 0 kyegyamu .
PFX FG 0 kyegyaba .
PFX FG 0 kyegyagu .
PFX FG 0 kyegyagi .
PFX FG 0 kyegyazi .
PFX FG 0 kyegyaki .
PFX FG 0 kyegyabi .
PFX FG 0 kyegyali .
PFX FG 0 kyegyaga .
PFX FG 0 kyegyaka .
PFX FG 0 kyegyabu .
PFX FG 0 kyegyalu .
PFX FG 0 kyegyaku .
PFX FG 0 kyegyatu .
PFX FG 0 kyezaan [^lmnb]
PFX FG l kyezaand l.[^mn]
PFX FG l kyezaann l.[mn]
PFX FG w kyezaamp [w]
PFX FG 0 kyezaamu .
PFX FG 0 kyezaaba .
PFX FG 0 kyezaagu .
PFX FG 0 kyezaagi .
PFX FG 0 kyezaazi .
PFX FG 0 kyezaaki .
PFX FG 0 kyezaabi .
PFX FG 0 kyezaali .
PFX FG 0 kyezaaga .
PFX FG 0 kyezaaka .
PFX FG 0 kyezaabu .
PFX FG 0 kyezaalu .
PFX FG 0 kyezaaku .
PFX FG 0 kyezaatu .
PFX FG 0 kyekyaan [^lmnb]
PFX FG l kyekyaand l.[^mn]
PFX FG l kyekyaann l.[mn]
PFX FG w kyekyaamp [w]
PFX FG 0 kyekyaamu .
PFX FG 0 kyekyaaba .
PFX FG 0 kyekyaagu .
PFX FG 0 kyekyaagi .
PFX FG 0 kyekyaazi .
PFX FG 0 kyekyaaki .
PFX FG 0 kyekyaabi .
PFX FG 0 kyekyaali .
PFX FG 0 kyekyaaga .
PFX FG 0 kyekyaaka .
PFX FG 0 kyekyaabu .
PFX FG 0 kyekyaalu .
PFX FG 0 kyekyaaku .
PFX FG 0 kyekyaatu .
PFX FG 0 kyebyaan [^lmnb]
PFX FG l kyebyaand l.[^mn]
PFX FG l kyebyaann l.[mn]
PFX FG w kyebyaamp [w]
PFX FG 0 kyebyaamu .
PFX FG 0 kyebyaaba .
PFX FG 0 kyebyaagu .
PFX FG 0 kyebyaagi .
PFX FG 0 kyebyaazi .
PFX FG 0 kyebyaaki .
PFX FG 0 kyebyaabi .
PFX FG 0 kyebyaali .
PFX FG 0 kyebyaaga .
PFX FG 0 kyebyaaka .
PFX FG 0 kyebyaabu .
PFX FG 0 kyebyaalu .
PFX FG 0 kyebyaaku .
PFX FG 0 kyebyaatu .
PFX FG 0 kyelyaan [^lmnb]
PFX FG l kyelyaand l.[^mn]
PFX FG l kyelyaann l.[mn]
PFX FG w kyelyaamp [w]
PFX FG 0 kyelyaamu .
PFX FG 0 kyelyaaba .
PFX FG 0 kyelyaagu .
PFX FG 0 kyelyaagi .
PFX FG 0 kyelyaazi .
PFX FG 0 kyelyaaki .
PFX FG 0 kyelyaabi .
PFX FG 0 kyelyaali .
PFX FG 0 kyelyaaga .
PFX FG 0 kyelyaaka .
PFX FG 0 kyelyaabu .
PFX FG 0 kyelyaalu .
PFX FG 0 kyelyaaku .
PFX FG 0 kyelyaatu .
PFX FG 0 kyegaan [^lmnb]
PFX FG l kyegaand l.[^mn]
PFX FG l kyegaann l.[mn]
PFX FG w kyegaamp [w]
PFX FG 0 kyegaamu .
PFX FG 0 kyegaaba .
PFX FG 0 kyegaagu .
PFX FG 0 kyegaagi .
PFX FG 0 kyegaazi .
PFX FG 0 kyegaaki .
PFX FG 0 kyegaabi .
PFX FG 0 kyegaali .
PFX FG 0 kyegaaga .
PFX FG 0 kyegaaka .
PFX FG 0 kyegaabu .
PFX FG 0 kyegaalu .
PFX FG 0 kyegaaku .
PFX FG 0 kyegaatu .
PFX FG 0 kyekaan [^lmnb]
PFX FG l kyekaand l.[^mn]
PFX FG l kyekaann l.[mn]
PFX FG w kyekaamp [w]
PFX FG 0 kyekaamu .
PFX FG 0 kyekaaba .
PFX FG 0 kyekaagu .
PFX FG 0 kyekaagi .
PFX FG 0 kyekaazi .
PFX FG 0 kyekaaki .
PFX FG 0 kyekaabi .
PFX FG 0 kyekaali .
PFX FG 0 kyekaaga .
PFX FG 0 kyekaaka .
PFX FG 0 kyekaabu .
PFX FG 0 kyekaalu .
PFX FG 0 kyekaaku .
PFX FG 0 kyekaatu .
PFX FG 0 kyebwan [^lmnb]
PFX FG l kyebwand l.[^mn]
PFX FG l kyebwann l.[mn]
PFX FG w kyebwamp [w]
PFX FG 0 kyebwamu .
PFX FG 0 kyebwaba .
PFX FG 0 kyebwagu .
PFX FG 0 kyebwagi .
PFX FG 0 kyebwazi .
PFX FG 0 kyebwaki .
PFX FG 0 kyebwabi .
PFX FG 0 kyebwali .
PFX FG 0 kyebwaga .
PFX FG 0 kyebwaka .
PFX FG 0 kyebwabu .
PFX FG 0 kyebwalu .
PFX FG 0 kyebwaku .
PFX FG 0 kyebwatu .
PFX FG 0 kyelwan [^lmnb]
PFX FG l kyelwand l.[^mn]
PFX FG l kyelwann l.[mn]
PFX FG w kyelwamp [w]
PFX FG 0 kyelwamu .
PFX FG 0 kyelwaba .
PFX FG 0 kyelwagu .
PFX FG 0 kyelwagi .
PFX FG 0 kyelwazi .
PFX FG 0 kyelwaki .
PFX FG 0 kyelwabi .
PFX FG 0 kyelwali .
PFX FG 0 kyelwaga .
PFX FG 0 kyelwaka .
PFX FG 0 kyelwabu .
PFX FG 0 kyelwalu .
PFX FG 0 kyelwaku .
PFX FG 0 kyelwatu .
PFX FG 0 kyekwan [^lmnb]
PFX FG l kyekwand l.[^mn]
PFX FG l kyekwann l.[mn]
PFX FG w kyekwamp [w]
PFX FG 0 kyekwamu .
PFX FG 0 kyekwaba .
PFX FG 0 kyekwagu .
PFX FG 0 kyekwagi .
PFX FG 0 kyekwazi .
PFX FG 0 kyekwaki .
PFX FG 0 kyekwabi .
PFX FG 0 kyekwali .
PFX FG 0 kyekwaga .
PFX FG 0 kyekwaka .
PFX FG 0 kyekwabu .
PFX FG 0 kyekwalu .
PFX FG 0 kyekwaku .
PFX FG 0 kyekwatu .
PFX FG 0 kyegaan [^lmnb]
PFX FG l kyegaand l.[^mn]
PFX FG l kyegaann l.[mn]
PFX FG w kyegaamp [w]
PFX FG 0 kyegaamu .
PFX FG 0 kyegaaba .
PFX FG 0 kyegaagu .
PFX FG 0 kyegaagi .
PFX FG 0 kyegaazi .
PFX FG 0 kyegaaki .
PFX FG 0 kyegaabi .
PFX FG 0 kyegaali .
PFX FG 0 kyegaaga .
PFX FG 0 kyegaaka .
PFX FG 0 kyegaabu .
PFX FG 0 kyegaalu .
PFX FG 0 kyegaaku .
PFX FG 0 kyegaatu .
PFX FG 0 kyetwan [^lmnb]
PFX FG l kyetwand l.[^mn]
PFX FG l kyetwann l.[mn]
PFX FG w kyetwamp [w]
PFX FG 0 kyetwamu .
PFX FG 0 kyetwaba .
PFX FG 0 kyetwagu .
PFX FG 0 kyetwagi .
PFX FG 0 kyetwazi .
PFX FG 0 kyetwaki .
PFX FG 0 kyetwabi .
PFX FG 0 kyetwali .
PFX FG 0 kyetwaga .
PFX FG 0 kyetwaka .
PFX FG 0 kyetwabu .
PFX FG 0 kyetwalu .
PFX FG 0 kyetwaku .
PFX FG 0 kyetwatu .
PFX FG 0 byennaba .
PFX FG 0 byennagu .
PFX FG 0 byennagi .
PFX FG 0 byennazi .
PFX FG 0 byennaki .
PFX FG 0 byennabi .
PFX FG 0 byennali .
PFX FG 0 byennaga .
PFX FG 0 byennaka .
PFX FG 0 byennabu .
PFX FG 0 byennalu .
PFX FG 0 byennaku .
PFX FG 0 byennatu .
PFX FG 0 byennamu .
PFX FG 0 byewan [^lmnb]
PFX FG l byewand l.[^mn]
PFX FG l byewann l.[mn]
PFX FG w byewamp [w]
PFX FG 0 byewamu .
PFX FG 0 byewaba .
PFX FG 0 byewagu .
PFX FG 0 byewagi .
PFX FG 0 byewazi .
PFX FG 0 byewaki .
PFX FG 0 byewabi .
PFX FG 0 byewali .
PFX FG 0 byewaga .
PFX FG 0 byewaka .
PFX FG 0 byewabu .
PFX FG 0 byewalu .
PFX FG 0 byewaku .
PFX FG 0 byewatu .
PFX FG 0 byeyan [^lmnb]
PFX FG l byeyand l.[^mn]
PFX FG l byeyann l.[mn]
PFX FG w byeyamp [w]
PFX FG 0 byeyamu .
PFX FG 0 byeyaba .
PFX FG 0 byeyagu .
PFX FG 0 byeyagi .
PFX FG 0 byeyazi .
PFX FG 0 byeyaki .
PFX FG 0 byeyabi .
PFX FG 0 byeyali .
PFX FG 0 byeyaga .
PFX FG 0 byeyaka .
PFX FG 0 byeyabu .
PFX FG 0 byeyalu .
PFX FG 0 byeyaku .
PFX FG 0 byeyatu .
PFX FG 0 byetwan [^lmnb]
PFX FG l byetwand l.[^mn]
PFX FG l byetwann l.[mn]
PFX FG w byetwamp [w]
PFX FG 0 byetwamu .
PFX FG 0 byetwaba .
PFX FG 0 byetwagu .
PFX FG 0 byetwagi .
PFX FG 0 byetwazi .
PFX FG 0 byetwaki .
PFX FG 0 byetwabi .
PFX FG 0 byetwali .
PFX FG 0 byetwaga .
PFX FG 0 byetwaka .
PFX FG 0 byetwabu .
PFX FG 0 byetwalu .
PFX FG 0 byetwaku .
PFX FG 0 byetwatu .
PFX FG 0 byemwan [^lmnb]
PFX FG l byemwand l.[^mn]
PFX FG l byemwann l.[mn]
PFX FG w byemwamp [w]
PFX FG 0 byemwamu .
PFX FG 0 byemwaba .
PFX FG 0 byemwagu .
PFX FG 0 byemwagi .
PFX FG 0 byemwazi .
PFX FG 0 byemwaki .
PFX FG 0 byemwabi .
PFX FG 0 byemwali .
PFX FG 0 byemwaga .
PFX FG 0 byemwaka .
PFX FG 0 byemwabu .
PFX FG 0 byemwalu .
PFX FG 0 byemwaku .
PFX FG 0 byemwatu .
PFX FG 0 byebaan [^lmnb]
PFX FG l byebaand l.[^mn]
PFX FG l byebaann l.[mn]
PFX FG w byebaamp [w]
PFX FG 0 byebaamu .
PFX FG 0 byebaaba .
PFX FG 0 byebaagu .
PFX FG 0 byebaagi .
PFX FG 0 byebaazi .
PFX FG 0 byebaaki .
PFX FG 0 byebaabi .
PFX FG 0 byebaali .
PFX FG 0 byebaaga .
PFX FG 0 byebaaka .
PFX FG 0 byebaabu .
PFX FG 0 byebaalu .
PFX FG 0 byebaaku .
PFX FG 0 byebaatu .
PFX FG 0 byegwan [^lmnb]
PFX FG l byegwand l.[^mn]
PFX FG l byegwann l.[mn]
PFX FG w byegwamp [w]
PFX FG 0 byegwamu .
PFX FG 0 byegwaba .
PFX FG 0 byegwagu .
PFX FG 0 byegwagi .
PFX FG 0 byegwazi .
PFX FG 0 byegwaki .
PFX FG 0 byegwabi .
PFX FG 0 byegwali .
PFX FG 0 byegwaga .
PFX FG 0 byegwaka .
PFX FG 0 byegwabu .
PFX FG 0 byegwalu .
PFX FG 0 byegwaku .
PFX FG 0 byegwatu .
PFX FG 0 byegyan [^lmnb]
PFX FG l byegyand l.[^mn]
PFX FG l byegyann l.[mn]
PFX FG w byegyamp [w]
PFX FG 0 byegyamu .
PFX FG 0 byegyaba .
PFX FG 0 byegyagu .
PFX FG 0 byegyagi .
PFX FG 0 byegyazi .
PFX FG 0 byegyaki .
PFX FG 0 byegyabi .
PFX FG 0 byegyali .
PFX FG 0 byegyaga .
PFX FG 0 byegyaka .
PFX FG 0 byegyabu .
PFX FG 0 byegyalu .
PFX FG 0 byegyaku .
PFX FG 0 byegyatu .
PFX FG 0 byezaan [^lmnb]
PFX FG l byezaand l.[^mn]
PFX FG l byezaann l.[mn]
PFX FG w byezaamp [w]
PFX FG 0 byezaamu .
PFX FG 0 byezaaba .
PFX FG 0 byezaagu .
PFX FG 0 byezaagi .
PFX FG 0 byezaazi .
PFX FG 0 byezaaki .
PFX FG 0 byezaabi .
PFX FG 0 byezaali .
PFX FG 0 byezaaga .
PFX FG 0 byezaaka .
PFX FG 0 byezaabu .
PFX FG 0 byezaalu .
PFX FG 0 byezaaku .
PFX FG 0 byezaatu .
PFX FG 0 byekyaan [^lmnb]
PFX FG l byekyaand l.[^mn]
PFX FG l byekyaann l.[mn]
PFX FG w byekyaamp [w]
PFX FG 0 byekyaamu .
PFX FG 0 byekyaaba .
PFX FG 0 byekyaagu .
PFX FG 0 byekyaagi .
PFX FG 0 byekyaazi .
PFX FG 0 byekyaaki .
PFX FG 0 byekyaabi .
PFX FG 0 byekyaali .
PFX FG 0 byekyaaga .
PFX FG 0 byekyaaka .
PFX FG 0 byekyaabu .
PFX FG 0 byekyaalu .
PFX FG 0 byekyaaku .
PFX FG 0 byekyaatu .
PFX FG 0 byebyaan [^lmnb]
PFX FG l byebyaand l.[^mn]
PFX FG l byebyaann l.[mn]
PFX FG w byebyaamp [w]
PFX FG 0 byebyaamu .
PFX FG 0 byebyaaba .
PFX FG 0 byebyaagu .
PFX FG 0 byebyaagi .
PFX FG 0 byebyaazi .
PFX FG 0 byebyaaki .
PFX FG 0 byebyaabi .
PFX FG 0 byebyaali .
PFX FG 0 byebyaaga .
PFX FG 0 byebyaaka .
PFX FG 0 byebyaabu .
PFX FG 0 byebyaalu .
PFX FG 0 byebyaaku .
PFX FG 0 byebyaatu .
PFX FG 0 byelyaan [^lmnb]
PFX FG l byelyaand l.[^mn]
PFX FG l byelyaann l.[mn]
PFX FG w byelyaamp [w]
PFX FG 0 byelyaamu .
PFX FG 0 byelyaaba .
PFX FG 0 byelyaagu .
PFX FG 0 byelyaagi .
PFX FG 0 byelyaazi .
PFX FG 0 byelyaaki .
PFX FG 0 byelyaabi .
PFX FG 0 byelyaali .
PFX FG 0 byelyaaga .
PFX FG 0 byelyaaka .
PFX FG 0 byelyaabu .
PFX FG 0 byelyaalu .
PFX FG 0 byelyaaku .
PFX FG 0 byelyaatu .
PFX FG 0 byegaan [^lmnb]
PFX FG l byegaand l.[^mn]
PFX FG l byegaann l.[mn]
PFX FG w byegaamp [w]
PFX FG 0 byegaamu .
PFX FG 0 byegaaba .
PFX FG 0 byegaagu .
PFX FG 0 byegaagi .
PFX FG 0 byegaazi .
PFX FG 0 byegaaki .
PFX FG 0 byegaabi .
PFX FG 0 byegaali .
PFX FG 0 byegaaga .
PFX FG 0 byegaaka .
PFX FG 0 byegaabu .
PFX FG 0 byegaalu .
PFX FG 0 byegaaku .
PFX FG 0 byegaatu .
PFX FG 0 byekaan [^lmnb]
PFX FG l byekaand l.[^mn]
PFX FG l byekaann l.[mn]
PFX FG w byekaamp [w]
PFX FG 0 byekaamu .
PFX FG 0 byekaaba .
PFX FG 0 byekaagu .
PFX FG 0 byekaagi .
PFX FG 0 byekaazi .
PFX FG 0 byekaaki .
PFX FG 0 byekaabi .
PFX FG 0 byekaali .
PFX FG 0 byekaaga .
PFX FG 0 byekaaka .
PFX FG 0 byekaabu .
PFX FG 0 byekaalu .
PFX FG 0 byekaaku .
PFX FG 0 byekaatu .
PFX FG 0 byebwan [^lmnb]
PFX FG l byebwand l.[^mn]
PFX FG l byebwann l.[mn]
PFX FG w byebwamp [w]
PFX FG 0 byebwamu .
PFX FG 0 byebwaba .
PFX FG 0 byebwagu .
PFX FG 0 byebwagi .
PFX FG 0 byebwazi .
PFX FG 0 byebwaki .
PFX FG 0 byebwabi .
PFX FG 0 byebwali .
PFX FG 0 byebwaga .
PFX FG 0 byebwaka .
PFX FG 0 byebwabu .
PFX FG 0 byebwalu .
PFX FG 0 byebwaku .
PFX FG 0 byebwatu .
PFX FG 0 byelwan [^lmnb]
PFX FG l byelwand l.[^mn]
PFX FG l byelwann l.[mn]
PFX FG w byelwamp [w]
PFX FG 0 byelwamu .
PFX FG 0 byelwaba .
PFX FG 0 byelwagu .
PFX FG 0 byelwagi .
PFX FG 0 byelwazi .
PFX FG 0 byelwaki .
PFX FG 0 byelwabi .
PFX FG 0 byelwali .
PFX FG 0 byelwaga .
PFX FG 0 byelwaka .
PFX FG 0 byelwabu .
PFX FG 0 byelwalu .
PFX FG 0 byelwaku .
PFX FG 0 byelwatu .
PFX FG 0 byekwan [^lmnb]
PFX FG l byekwand l.[^mn]
PFX FG l byekwann l.[mn]
PFX FG w byekwamp [w]
PFX FG 0 byekwamu .
PFX FG 0 byekwaba .
PFX FG 0 byekwagu .
PFX FG 0 byekwagi .
PFX FG 0 byekwazi .
PFX FG 0 byekwaki .
PFX FG 0 byekwabi .
PFX FG 0 byekwali .
PFX FG 0 byekwaga .
PFX FG 0 byekwaka .
PFX FG 0 byekwabu .
PFX FG 0 byekwalu .
PFX FG 0 byekwaku .
PFX FG 0 byekwatu .
PFX FG 0 byegaan [^lmnb]
PFX FG l byegaand l.[^mn]
PFX FG l byegaann l.[mn]
PFX FG w byegaamp [w]
PFX FG 0 byegaamu .
PFX FG 0 byegaaba .
PFX FG 0 byegaagu .
PFX FG 0 byegaagi .
PFX FG 0 byegaazi .
PFX FG 0 byegaaki .
PFX FG 0 byegaabi .
PFX FG 0 byegaali .
PFX FG 0 byegaaga .
PFX FG 0 byegaaka .
PFX FG 0 byegaabu .
PFX FG 0 byegaalu .
PFX FG 0 byegaaku .
PFX FG 0 byegaatu .
PFX FG 0 byetwan [^lmnb]
PFX FG l byetwand l.[^mn]
PFX FG l byetwann l.[mn]
PFX FG w byetwamp [w]
PFX FG 0 byetwamu .
PFX FG 0 byetwaba .
PFX FG 0 byetwagu .
PFX FG 0 byetwagi .
PFX FG 0 byetwazi .
PFX FG 0 byetwaki .
PFX FG 0 byetwabi .
PFX FG 0 byetwali .
PFX FG 0 byetwaga .
PFX FG 0 byetwaka .
PFX FG 0 byetwabu .
PFX FG 0 byetwalu .
PFX FG 0 byetwaku .
PFX FG 0 byetwatu .
PFX FG 0 lyennaba .
PFX FG 0 lyennagu .
PFX FG 0 lyennagi .
PFX FG 0 lyennazi .
PFX FG 0 lyennaki .
PFX FG 0 lyennabi .
PFX FG 0 lyennali .
PFX FG 0 lyennaga .
PFX FG 0 lyennaka .
PFX FG 0 lyennabu .
PFX FG 0 lyennalu .
PFX FG 0 lyennaku .
PFX FG 0 lyennatu .
PFX FG 0 lyennamu .
PFX FG 0 lyewan [^lmnb]
PFX FG l lyewand l.[^mn]
PFX FG l lyewann l.[mn]
PFX FG w lyewamp [w]
PFX FG 0 lyewamu .
PFX FG 0 lyewaba .
PFX FG 0 lyewagu .
PFX FG 0 lyewagi .
PFX FG 0 lyewazi .
PFX FG 0 lyewaki .
PFX FG 0 lyewabi .
PFX FG 0 lyewali .
PFX FG 0 lyewaga .
PFX FG 0 lyewaka .
PFX FG 0 lyewabu .
PFX FG 0 lyewalu .
PFX FG 0 lyewaku .
PFX FG 0 lyewatu .
PFX FG 0 lyeyan [^lmnb]
PFX FG l lyeyand l.[^mn]
PFX FG l lyeyann l.[mn]
PFX FG w lyeyamp [w]
PFX FG 0 lyeyamu .
PFX FG 0 lyeyaba .
PFX FG 0 lyeyagu .
PFX FG 0 lyeyagi .
PFX FG 0 lyeyazi .
PFX FG 0 lyeyaki .
PFX FG 0 lyeyabi .
PFX FG 0 lyeyali .
PFX FG 0 lyeyaga .
PFX FG 0 lyeyaka .
PFX FG 0 lyeyabu .
PFX FG 0 lyeyalu .
PFX FG 0 lyeyaku .
PFX FG 0 lyeyatu .
PFX FG 0 lyetwan [^lmnb]
PFX FG l lyetwand l.[^mn]
PFX FG l lyetwann l.[mn]
PFX FG w lyetwamp [w]
PFX FG 0 lyetwamu .
PFX FG 0 lyetwaba .
PFX FG 0 lyetwagu .
PFX FG 0 lyetwagi .
PFX FG 0 lyetwazi .
PFX FG 0 lyetwaki .
PFX FG 0 lyetwabi .
PFX FG 0 lyetwali .
PFX FG 0 lyetwaga .
PFX FG 0 lyetwaka .
PFX FG 0 lyetwabu .
PFX FG 0 lyetwalu .
PFX FG 0 lyetwaku .
PFX FG 0 lyetwatu .
PFX FG 0 lyemwan [^lmnb]
PFX FG l lyemwand l.[^mn]
PFX FG l lyemwann l.[mn]
PFX FG w lyemwamp [w]
PFX FG 0 lyemwamu .
PFX FG 0 lyemwaba .
PFX FG 0 lyemwagu .
PFX FG 0 lyemwagi .
PFX FG 0 lyemwazi .
PFX FG 0 lyemwaki .
PFX FG 0 lyemwabi .
PFX FG 0 lyemwali .
PFX FG 0 lyemwaga .
PFX FG 0 lyemwaka .
PFX FG 0 lyemwabu .
PFX FG 0 lyemwalu .
PFX FG 0 lyemwaku .
PFX FG 0 lyemwatu .
PFX FG 0 lyebaan [^lmnb]
PFX FG l lyebaand l.[^mn]
PFX FG l lyebaann l.[mn]
PFX FG w lyebaamp [w]
PFX FG 0 lyebaamu .
PFX FG 0 lyebaaba .
PFX FG 0 lyebaagu .
PFX FG 0 lyebaagi .
PFX FG 0 lyebaazi .
PFX FG 0 lyebaaki .
PFX FG 0 lyebaabi .
PFX FG 0 lyebaali .
PFX FG 0 lyebaaga .
PFX FG 0 lyebaaka .
PFX FG 0 lyebaabu .
PFX FG 0 lyebaalu .
PFX FG 0 lyebaaku .
PFX FG 0 lyebaatu .
PFX FG 0 lyegwan [^lmnb]
PFX FG l lyegwand l.[^mn]
PFX FG l lyegwann l.[mn]
PFX FG w lyegwamp [w]
PFX FG 0 lyegwamu .
PFX FG 0 lyegwaba .
PFX FG 0 lyegwagu .
PFX FG 0 lyegwagi .
PFX FG 0 lyegwazi .
PFX FG 0 lyegwaki .
PFX FG 0 lyegwabi .
PFX FG 0 lyegwali .
PFX FG 0 lyegwaga .
PFX FG 0 lyegwaka .
PFX FG 0 lyegwabu .
PFX FG 0 lyegwalu .
PFX FG 0 lyegwaku .
PFX FG 0 lyegwatu .
PFX FG 0 lyegyan [^lmnb]
PFX FG l lyegyand l.[^mn]
PFX FG l lyegyann l.[mn]
PFX FG w lyegyamp [w]
PFX FG 0 lyegyamu .
PFX FG 0 lyegyaba .
PFX FG 0 lyegyagu .
PFX FG 0 lyegyagi .
PFX FG 0 lyegyazi .
PFX FG 0 lyegyaki .
PFX FG 0 lyegyabi .
PFX FG 0 lyegyali .
PFX FG 0 lyegyaga .
PFX FG 0 lyegyaka .
PFX FG 0 lyegyabu .
PFX FG 0 lyegyalu .
PFX FG 0 lyegyaku .
PFX FG 0 lyegyatu .
PFX FG 0 lyezaan [^lmnb]
PFX FG l lyezaand l.[^mn]
PFX FG l lyezaann l.[mn]
PFX FG w lyezaamp [w]
PFX FG 0 lyezaamu .
PFX FG 0 lyezaaba .
PFX FG 0 lyezaagu .
PFX FG 0 lyezaagi .
PFX FG 0 lyezaazi .
PFX FG 0 lyezaaki .
PFX FG 0 lyezaabi .
PFX FG 0 lyezaali .
PFX FG 0 lyezaaga .
PFX FG 0 lyezaaka .
PFX FG 0 lyezaabu .
PFX FG 0 lyezaalu .
PFX FG 0 lyezaaku .
PFX FG 0 lyezaatu .
PFX FG 0 lyekyaan [^lmnb]
PFX FG l lyekyaand l.[^mn]
PFX FG l lyekyaann l.[mn]
PFX FG w lyekyaamp [w]
PFX FG 0 lyekyaamu .
PFX FG 0 lyekyaaba .
PFX FG 0 lyekyaagu .
PFX FG 0 lyekyaagi .
PFX FG 0 lyekyaazi .
PFX FG 0 lyekyaaki .
PFX FG 0 lyekyaabi .
PFX FG 0 lyekyaali .
PFX FG 0 lyekyaaga .
PFX FG 0 lyekyaaka .
PFX FG 0 lyekyaabu .
PFX FG 0 lyekyaalu .
PFX FG 0 lyekyaaku .
PFX FG 0 lyekyaatu .
PFX FG 0 lyebyaan [^lmnb]
PFX FG l lyebyaand l.[^mn]
PFX FG l lyebyaann l.[mn]
PFX FG w lyebyaamp [w]
PFX FG 0 lyebyaamu .
PFX FG 0 lyebyaaba .
PFX FG 0 lyebyaagu .
PFX FG 0 lyebyaagi .
PFX FG 0 lyebyaazi .
PFX FG 0 lyebyaaki .
PFX FG 0 lyebyaabi .
PFX FG 0 lyebyaali .
PFX FG 0 lyebyaaga .
PFX FG 0 lyebyaaka .
PFX FG 0 lyebyaabu .
PFX FG 0 lyebyaalu .
PFX FG 0 lyebyaaku .
PFX FG 0 lyebyaatu .
PFX FG 0 lyelyaan [^lmnb]
PFX FG l lyelyaand l.[^mn]
PFX FG l lyelyaann l.[mn]
PFX FG w lyelyaamp [w]
PFX FG 0 lyelyaamu .
PFX FG 0 lyelyaaba .
PFX FG 0 lyelyaagu .
PFX FG 0 lyelyaagi .
PFX FG 0 lyelyaazi .
PFX FG 0 lyelyaaki .
PFX FG 0 lyelyaabi .
PFX FG 0 lyelyaali .
PFX FG 0 lyelyaaga .
PFX FG 0 lyelyaaka .
PFX FG 0 lyelyaabu .
PFX FG 0 lyelyaalu .
PFX FG 0 lyelyaaku .
PFX FG 0 lyelyaatu .
PFX FG 0 lyegaan [^lmnb]
PFX FG l lyegaand l.[^mn]
PFX FG l lyegaann l.[mn]
PFX FG w lyegaamp [w]
PFX FG 0 lyegaamu .
PFX FG 0 lyegaaba .
PFX FG 0 lyegaagu .
PFX FG 0 lyegaagi .
PFX FG 0 lyegaazi .
PFX FG 0 lyegaaki .
PFX FG 0 lyegaabi .
PFX FG 0 lyegaali .
PFX FG 0 lyegaaga .
PFX FG 0 lyegaaka .
PFX FG 0 lyegaabu .
PFX FG 0 lyegaalu .
PFX FG 0 lyegaaku .
PFX FG 0 lyegaatu .
PFX FG 0 lyekaan [^lmnb]
PFX FG l lyekaand l.[^mn]
PFX FG l lyekaann l.[mn]
PFX FG w lyekaamp [w]
PFX FG 0 lyekaamu .
PFX FG 0 lyekaaba .
PFX FG 0 lyekaagu .
PFX FG 0 lyekaagi .
PFX FG 0 lyekaazi .
PFX FG 0 lyekaaki .
PFX FG 0 lyekaabi .
PFX FG 0 lyekaali .
PFX FG 0 lyekaaga .
PFX FG 0 lyekaaka .
PFX FG 0 lyekaabu .
PFX FG 0 lyekaalu .
PFX FG 0 lyekaaku .
PFX FG 0 lyekaatu .
PFX FG 0 lyebwan [^lmnb]
PFX FG l lyebwand l.[^mn]
PFX FG l lyebwann l.[mn]
PFX FG w lyebwamp [w]
PFX FG 0 lyebwamu .
PFX FG 0 lyebwaba .
PFX FG 0 lyebwagu .
PFX FG 0 lyebwagi .
PFX FG 0 lyebwazi .
PFX FG 0 lyebwaki .
PFX FG 0 lyebwabi .
PFX FG 0 lyebwali .
PFX FG 0 lyebwaga .
PFX FG 0 lyebwaka .
PFX FG 0 lyebwabu .
PFX FG 0 lyebwalu .
PFX FG 0 lyebwaku .
PFX FG 0 lyebwatu .
PFX FG 0 lyelwan [^lmnb]
PFX FG l lyelwand l.[^mn]
PFX FG l lyelwann l.[mn]
PFX FG w lyelwamp [w]
PFX FG 0 lyelwamu .
PFX FG 0 lyelwaba .
PFX FG 0 lyelwagu .
PFX FG 0 lyelwagi .
PFX FG 0 lyelwazi .
PFX FG 0 lyelwaki .
PFX FG 0 lyelwabi .
PFX FG 0 lyelwali .
PFX FG 0 lyelwaga .
PFX FG 0 lyelwaka .
PFX FG 0 lyelwabu .
PFX FG 0 lyelwalu .
PFX FG 0 lyelwaku .
PFX FG 0 lyelwatu .
PFX FG 0 lyekwan [^lmnb]
PFX FG l lyekwand l.[^mn]
PFX FG l lyekwann l.[mn]
PFX FG w lyekwamp [w]
PFX FG 0 lyekwamu .
PFX FG 0 lyekwaba .
PFX FG 0 lyekwagu .
PFX FG 0 lyekwagi .
PFX FG 0 lyekwazi .
PFX FG 0 lyekwaki .
PFX FG 0 lyekwabi .
PFX FG 0 lyekwali .
PFX FG 0 lyekwaga .
PFX FG 0 lyekwaka .
PFX FG 0 lyekwabu .
PFX FG 0 lyekwalu .
PFX FG 0 lyekwaku .
PFX FG 0 lyekwatu .
PFX FG 0 lyegaan [^lmnb]
PFX FG l lyegaand l.[^mn]
PFX FG l lyegaann l.[mn]
PFX FG w lyegaamp [w]
PFX FG 0 lyegaamu .
PFX FG 0 lyegaaba .
PFX FG 0 lyegaagu .
PFX FG 0 lyegaagi .
PFX FG 0 lyegaazi .
PFX FG 0 lyegaaki .
PFX FG 0 lyegaabi .
PFX FG 0 lyegaali .
PFX FG 0 lyegaaga .
PFX FG 0 lyegaaka .
PFX FG 0 lyegaabu .
PFX FG 0 lyegaalu .
PFX FG 0 lyegaaku .
PFX FG 0 lyegaatu .
PFX FG 0 lyetwan [^lmnb]
PFX FG l lyetwand l.[^mn]
PFX FG l lyetwann l.[mn]
PFX FG w lyetwamp [w]
PFX FG 0 lyetwamu .
PFX FG 0 lyetwaba .
PFX FG 0 lyetwagu .
PFX FG 0 lyetwagi .
PFX FG 0 lyetwazi .
PFX FG 0 lyetwaki .
PFX FG 0 lyetwabi .
PFX FG 0 lyetwali .
PFX FG 0 lyetwaga .
PFX FG 0 lyetwaka .
PFX FG 0 lyetwabu .
PFX FG 0 lyetwalu .
PFX FG 0 lyetwaku .
PFX FG 0 lyetwatu .
PFX FG 0 kennaba .
PFX FG 0 kennagu .
PFX FG 0 kennagi .
PFX FG 0 kennazi .
PFX FG 0 kennaki .
PFX FG 0 kennabi .
PFX FG 0 kennali .
PFX FG 0 kennaga .
PFX FG 0 kennaka .
PFX FG 0 kennabu .
PFX FG 0 kennalu .
PFX FG 0 kennaku .
PFX FG 0 kennatu .
PFX FG 0 kennamu .
PFX FG 0 kewan [^lmnb]
PFX FG l kewand l.[^mn]
PFX FG l kewann l.[mn]
PFX FG w kewamp [w]
PFX FG 0 kewamu .
PFX FG 0 kewaba .
PFX FG 0 kewagu .
PFX FG 0 kewagi .
PFX FG 0 kewazi .
PFX FG 0 kewaki .
PFX FG 0 kewabi .
PFX FG 0 kewali .
PFX FG 0 kewaga .
PFX FG 0 kewaka .
PFX FG 0 kewabu .
PFX FG 0 kewalu .
PFX FG 0 kewaku .
PFX FG 0 kewatu .
PFX FG 0 keyan [^lmnb]
PFX FG l keyand l.[^mn]
PFX FG l keyann l.[mn]
PFX FG w keyamp [w]
PFX FG 0 keyamu .
PFX FG 0 keyaba .
PFX FG 0 keyagu .
PFX FG 0 keyagi .
PFX FG 0 keyazi .
PFX FG 0 keyaki .
PFX FG 0 keyabi .
PFX FG 0 keyali .
PFX FG 0 keyaga .
PFX FG 0 keyaka .
PFX FG 0 keyabu .
PFX FG 0 keyalu .
PFX FG 0 keyaku .
PFX FG 0 keyatu .
PFX FG 0 ketwan [^lmnb]
PFX FG l ketwand l.[^mn]
PFX FG l ketwann l.[mn]
PFX FG w ketwamp [w]
PFX FG 0 ketwamu .
PFX FG 0 ketwaba .
PFX FG 0 ketwagu .
PFX FG 0 ketwagi .
PFX FG 0 ketwazi .
PFX FG 0 ketwaki .
PFX FG 0 ketwabi .
PFX FG 0 ketwali .
PFX FG 0 ketwaga .
PFX FG 0 ketwaka .
PFX FG 0 ketwabu .
PFX FG 0 ketwalu .
PFX FG 0 ketwaku .
PFX FG 0 ketwatu .
PFX FG 0 kemwan [^lmnb]
PFX FG l kemwand l.[^mn]
PFX FG l kemwann l.[mn]
PFX FG w kemwamp [w]
PFX FG 0 kemwamu .
PFX FG 0 kemwaba .
PFX FG 0 kemwagu .
PFX FG 0 kemwagi .
PFX FG 0 kemwazi .
PFX FG 0 kemwaki .
PFX FG 0 kemwabi .
PFX FG 0 kemwali .
PFX FG 0 kemwaga .
PFX FG 0 kemwaka .
PFX FG 0 kemwabu .
PFX FG 0 kemwalu .
PFX FG 0 kemwaku .
PFX FG 0 kemwatu .
PFX FG 0 kebaan [^lmnb]
PFX FG l kebaand l.[^mn]
PFX FG l kebaann l.[mn]
PFX FG w kebaamp [w]
PFX FG 0 kebaamu .
PFX FG 0 kebaaba .
PFX FG 0 kebaagu .
PFX FG 0 kebaagi .
PFX FG 0 kebaazi .
PFX FG 0 kebaaki .
PFX FG 0 kebaabi .
PFX FG 0 kebaali .
PFX FG 0 kebaaga .
PFX FG 0 kebaaka .
PFX FG 0 kebaabu .
PFX FG 0 kebaalu .
PFX FG 0 kebaaku .
PFX FG 0 kebaatu .
PFX FG 0 kegwan [^lmnb]
PFX FG l kegwand l.[^mn]
PFX FG l kegwann l.[mn]
PFX FG w kegwamp [w]
PFX FG 0 kegwamu .
PFX FG 0 kegwaba .
PFX FG 0 kegwagu .
PFX FG 0 kegwagi .
PFX FG 0 kegwazi .
PFX FG 0 kegwaki .
PFX FG 0 kegwabi .
PFX FG 0 kegwali .
PFX FG 0 kegwaga .
PFX FG 0 kegwaka .
PFX FG 0 kegwabu .
PFX FG 0 kegwalu .
PFX FG 0 kegwaku .
PFX FG 0 kegwatu .
PFX FG 0 kegyan [^lmnb]
PFX FG l kegyand l.[^mn]
PFX FG l kegyann l.[mn]
PFX FG w kegyamp [w]
PFX FG 0 kegyamu .
PFX FG 0 kegyaba .
PFX FG 0 kegyagu .
PFX FG 0 kegyagi .
PFX FG 0 kegyazi .
PFX FG 0 kegyaki .
PFX FG 0 kegyabi .
PFX FG 0 kegyali .
PFX FG 0 kegyaga .
PFX FG 0 kegyaka .
PFX FG 0 kegyabu .
PFX FG 0 kegyalu .
PFX FG 0 kegyaku .
PFX FG 0 kegyatu .
PFX FG 0 kezaan [^lmnb]
PFX FG l kezaand l.[^mn]
PFX FG l kezaann l.[mn]
PFX FG w kezaamp [w]
PFX FG 0 kezaamu .
PFX FG 0 kezaaba .
PFX FG 0 kezaagu .
PFX FG 0 kezaagi .
PFX FG 0 kezaazi .
PFX FG 0 kezaaki .
PFX FG 0 kezaabi .
PFX FG 0 kezaali .
PFX FG 0 kezaaga .
PFX FG 0 kezaaka .
PFX FG 0 kezaabu .
PFX FG 0 kezaalu .
PFX FG 0 kezaaku .
PFX FG 0 kezaatu .
PFX FG 0 kekyaan [^lmnb]
PFX FG l kekyaand l.[^mn]
PFX FG l kekyaann l.[mn]
PFX FG w kekyaamp [w]
PFX FG 0 kekyaamu .
PFX FG 0 kekyaaba .
PFX FG 0 kekyaagu .
PFX FG 0 kekyaagi .
PFX FG 0 kekyaazi .
PFX FG 0 kekyaaki .
PFX FG 0 kekyaabi .
PFX FG 0 kekyaali .
PFX FG 0 kekyaaga .
PFX FG 0 kekyaaka .
PFX FG 0 kekyaabu .
PFX FG 0 kekyaalu .
PFX FG 0 kekyaaku .
PFX FG 0 kekyaatu .
PFX FG 0 kebyaan [^lmnb]
PFX FG l kebyaand l.[^mn]
PFX FG l kebyaann l.[mn]
PFX FG w kebyaamp [w]
PFX FG 0 kebyaamu .
PFX FG 0 kebyaaba .
PFX FG 0 kebyaagu .
PFX FG 0 kebyaagi .
PFX FG 0 kebyaazi .
PFX FG 0 kebyaaki .
PFX FG 0 kebyaabi .
PFX FG 0 kebyaali .
PFX FG 0 kebyaaga .
PFX FG 0 kebyaaka .
PFX FG 0 kebyaabu .
PFX FG 0 kebyaalu .
PFX FG 0 kebyaaku .
PFX FG 0 kebyaatu .
PFX FG 0 kelyaan [^lmnb]
PFX FG l kelyaand l.[^mn]
PFX FG l kelyaann l.[mn]
PFX FG w kelyaamp [w]
PFX FG 0 kelyaamu .
PFX FG 0 kelyaaba .
PFX FG 0 kelyaagu .
PFX FG 0 kelyaagi .
PFX FG 0 kelyaazi .
PFX FG 0 kelyaaki .
PFX FG 0 kelyaabi .
PFX FG 0 kelyaali .
PFX FG 0 kelyaaga .
PFX FG 0 kelyaaka .
PFX FG 0 kelyaabu .
PFX FG 0 kelyaalu .
PFX FG 0 kelyaaku .
PFX FG 0 kelyaatu .
PFX FG 0 kegaan [^lmnb]
PFX FG l kegaand l.[^mn]
PFX FG l kegaann l.[mn]
PFX FG w kegaamp [w]
PFX FG 0 kegaamu .
PFX FG 0 kegaaba .
PFX FG 0 kegaagu .
PFX FG 0 kegaagi .
PFX FG 0 kegaazi .
PFX FG 0 kegaaki .
PFX FG 0 kegaabi .
PFX FG 0 kegaali .
PFX FG 0 kegaaga .
PFX FG 0 kegaaka .
PFX FG 0 kegaabu .
PFX FG 0 kegaalu .
PFX FG 0 kegaaku .
PFX FG 0 kegaatu .
PFX FG 0 kekaan [^lmnb]
PFX FG l kekaand l.[^mn]
PFX FG l kekaann l.[mn]
PFX FG w kekaamp [w]
PFX FG 0 kekaamu .
PFX FG 0 kekaaba .
PFX FG 0 kekaagu .
PFX FG 0 kekaagi .
PFX FG 0 kekaazi .
PFX FG 0 kekaaki .
PFX FG 0 kekaabi .
PFX FG 0 kekaali .
PFX FG 0 kekaaga .
PFX FG 0 kekaaka .
PFX FG 0 kekaabu .
PFX FG 0 kekaalu .
PFX FG 0 kekaaku .
PFX FG 0 kekaatu .
PFX FG 0 kebwan [^lmnb]
PFX FG l kebwand l.[^mn]
PFX FG l kebwann l.[mn]
PFX FG w kebwamp [w]
PFX FG 0 kebwamu .
PFX FG 0 kebwaba .
PFX FG 0 kebwagu .
PFX FG 0 kebwagi .
PFX FG 0 kebwazi .
PFX FG 0 kebwaki .
PFX FG 0 kebwabi .
PFX FG 0 kebwali .
PFX FG 0 kebwaga .
PFX FG 0 kebwaka .
PFX FG 0 kebwabu .
PFX FG 0 kebwalu .
PFX FG 0 kebwaku .
PFX FG 0 kebwatu .
PFX FG 0 kelwan [^lmnb]
PFX FG l kelwand l.[^mn]
PFX FG l kelwann l.[mn]
PFX FG w kelwamp [w]
PFX FG 0 kelwamu .
PFX FG 0 kelwaba .
PFX FG 0 kelwagu .
PFX FG 0 kelwagi .
PFX FG 0 kelwazi .
PFX FG 0 kelwaki .
PFX FG 0 kelwabi .
PFX FG 0 kelwali .
PFX FG 0 kelwaga .
PFX FG 0 kelwaka .
PFX FG 0 kelwabu .
PFX FG 0 kelwalu .
PFX FG 0 kelwaku .
PFX FG 0 kelwatu .
PFX FG 0 kekwan [^lmnb]
PFX FG l kekwand l.[^mn]
PFX FG l kekwann l.[mn]
PFX FG w kekwamp [w]
PFX FG 0 kekwamu .
PFX FG 0 kekwaba .
PFX FG 0 kekwagu .
PFX FG 0 kekwagi .
PFX FG 0 kekwazi .
PFX FG 0 kekwaki .
PFX FG 0 kekwabi .
PFX FG 0 kekwali .
PFX FG 0 kekwaga .
PFX FG 0 kekwaka .
PFX FG 0 kekwabu .
PFX FG 0 kekwalu .
PFX FG 0 kekwaku .
PFX FG 0 kekwatu .
PFX FG 0 kegaan [^lmnb]
PFX FG l kegaand l.[^mn]
PFX FG l kegaann l.[mn]
PFX FG w kegaamp [w]
PFX FG 0 kegaamu .
PFX FG 0 kegaaba .
PFX FG 0 kegaagu .
PFX FG 0 kegaagi .
PFX FG 0 kegaazi .
PFX FG 0 kegaaki .
PFX FG 0 kegaabi .
PFX FG 0 kegaali .
PFX FG 0 kegaaga .
PFX FG 0 kegaaka .
PFX FG 0 kegaabu .
PFX FG 0 kegaalu .
PFX FG 0 kegaaku .
PFX FG 0 kegaatu .
PFX FG 0 ketwan [^lmnb]
PFX FG l ketwand l.[^mn]
PFX FG l ketwann l.[mn]
PFX FG w ketwamp [w]
PFX FG 0 ketwamu .
PFX FG 0 ketwaba .
PFX FG 0 ketwagu .
PFX FG 0 ketwagi .
PFX FG 0 ketwazi .
PFX FG 0 ketwaki .
PFX FG 0 ketwabi .
PFX FG 0 ketwali .
PFX FG 0 ketwaga .
PFX FG 0 ketwaka .
PFX FG 0 ketwabu .
PFX FG 0 ketwalu .
PFX FG 0 ketwaku .
PFX FG 0 ketwatu ."""

rule_right_raw = """
PFX Ob Y 18
PFX Ob 0 n [^lmnb]
PFX Ob l nd l.[^mn][^u]
PFX Ob l nn l.[mn]
PFX Ob w mp [w]
PFX Ob 0 mu .
PFX Ob 0 ba .
PFX Ob 0 gu .
PFX Ob 0 gi .
PFX Ob 0 zi .
PFX Ob 0 ki .
PFX Ob 0 bi .
PFX Ob 0 li .
PFX Ob 0 ga .
PFX Ob 0 ka .
PFX Ob 0 bu .
PFX Ob 0 lu .
PFX Ob 0 ku .
PFX Ob 0 tu ."""

FLAG_DESCRIPTIONS = {
    "FG": "FG",
    "Ob": "Object markers",
}

def parse_rules(raw_text):
    rules = []
    for line in raw_text.strip().split('\n'):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        s = s.split('#', 1)[0].strip()
        parts = s.split()
        if len(parts) < 4:
            continue
        if parts[2] == 'Y':
            continue
        cond = parts[4] if len(parts) > 4 else '.'
        rules.append({'strip': parts[2], 'add': parts[3], 'cond': cond})
    return rules

def generate_block():
    lefts = parse_rules(rule_left_raw)
    rights = parse_rules(rule_right_raw)
    new_rules = []

    for left in lefts:
        for right in rights:
            if left['strip'] != '0':
                if not right['add'].startswith(left['strip']):
                    continue
                combined = left['add'] + right['add'][len(left['strip']):]
            else:
                combined = left['add'] + right['add']

            if left['cond'] != '.':
                if not re.match(left['cond'], right['add']):
                    continue

            new_rules.append({'strip': right['strip'], 'add': combined, 'cond': right['cond']})

    out_flag = "GK"
    left_desc = FLAG_DESCRIPTIONS.get("FG", "FG")
    right_desc = FLAG_DESCRIPTIONS.get("Ob", "Ob")
    comment_line = "# Cross product of {} ({}) and {} ({}) to {}".format(
        "FG", left_desc, "Ob", right_desc, out_flag
    )

    output = ["PFX {} Y {}".format(out_flag, len(new_rules))]
    for r in new_rules:
        output.append("PFX {} {} {} {}".format(out_flag, r['strip'], r['add'], r['cond']))

    return (out_flag, "\n".join([comment_line] + output) + "\n")

def main():
    if not os.path.exists(AFF_FILE):
        print("Error: {} not found.".format(AFF_FILE))
        return

    out_flag, block = generate_block()

    with open(AFF_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    first_flag_idx = None
    last_flag_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("PFX {} ".format(out_flag)):
            if first_flag_idx is None:
                first_flag_idx = i
            last_flag_idx = i

    if first_flag_idx is not None and first_flag_idx > 0:
        prev_line = lines[first_flag_idx - 1].strip()
        if prev_line.startswith("# Cross product"):
            start_idx = first_flag_idx - 1
        else:
            start_idx = first_flag_idx
    elif first_flag_idx is not None:
        start_idx = first_flag_idx
    else:
        start_idx = None

    if start_idx is not None and last_flag_idx is not None:
        # Replace existing block in-place.
        new_lines = lines[:start_idx] + [block] + lines[last_flag_idx + 1:]
    else:
        # Insert before an anchor flag if requested; otherwise append.
        insert_idx = None
        if INSERT_BEFORE_FLAG:
            anchor_prefix = "PFX {} ".format(INSERT_BEFORE_FLAG)
            for i, line in enumerate(lines):
                if line.strip().startswith(anchor_prefix):
                    insert_idx = i
                    # If the anchor PFX block is preceded by one or more cross-product
                    # comment lines, insert before those comments to keep them attached
                    # to the anchor block.
                    while insert_idx > 0 and lines[insert_idx - 1].strip().startswith("# Cross product"):
                        insert_idx -= 1
                    break

        if insert_idx is not None:
            new_lines = lines[:insert_idx] + [block] + lines[insert_idx:]
        else:
            new_lines = lines
            if new_lines and not new_lines[-1].endswith(chr(10)):
                new_lines[-1] += chr(10)
            new_lines.append(block)

    with open(AFF_FILE, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    print("{}: updated in place.".format(out_flag))

if __name__ == '__main__':
    main()
