import re
import os
from pathlib import Path

# Cross product generator: FE x OR => GT
# Description:
# - Left block `FE`: FE
# - Right block `OR`: Special reflexive object markers
# - Output flag `GT`: Cross-product prefixes for FE x OR

REPO_ROOT = Path(__file__).resolve().parents[1]
AFF_FILE = REPO_ROOT / "Luganda.aff"

# If set to a flag name (e.g. "HB"), the generated cross-product block will be inserted
# immediately before the first "PFX <flag>" line when the output flag block doesn't
# already exist in the .aff.
INSERT_BEFORE_FLAG = "".strip() or None

rule_left_raw = """
PFX FE Y 2894
PFX FE 0 wessiba .
PFX FE 0 wessigu .
PFX FE 0 wessigi .
PFX FE 0 wessizi .
PFX FE 0 wessiki .
PFX FE 0 wessibi .
PFX FE 0 wessili .
PFX FE 0 wessiga .
PFX FE 0 wessika .
PFX FE 0 wessibu .
PFX FE 0 wessilu .
PFX FE 0 wessiku .
PFX FE 0 wessitu .
PFX FE 0 wessimu .
PFX FE 0 wetutan [^lmnb]
PFX FE l wetutand l.[^mn]
PFX FE l wetutann l.[mn]
PFX FE w wetutamp [w]
PFX FE 0 wetutamu .
PFX FE 0 wetutaba .
PFX FE 0 wetutagu .
PFX FE 0 wetutagi .
PFX FE 0 wetutazi .
PFX FE 0 wetutaki .
PFX FE 0 wetutabi .
PFX FE 0 wetutali .
PFX FE 0 wetutaga .
PFX FE 0 wetutaka .
PFX FE 0 wetutabu .
PFX FE 0 wetutalu .
PFX FE 0 wetutaku .
PFX FE 0 wetutatu .
PFX FE 0 wemutan [^lmnb]
PFX FE l wemutand l.[^mn]
PFX FE l wemutann l.[mn]
PFX FE w wemutamp [w]
PFX FE 0 wemutamu .
PFX FE 0 wemutaba .
PFX FE 0 wemutagu .
PFX FE 0 wemutagi .
PFX FE 0 wemutazi .
PFX FE 0 wemutaki .
PFX FE 0 wemutabi .
PFX FE 0 wemutali .
PFX FE 0 wemutaga .
PFX FE 0 wemutaka .
PFX FE 0 wemutabu .
PFX FE 0 wemutalu .
PFX FE 0 wemutaku .
PFX FE 0 wemutatu .
PFX FE 0 webatan [^lmnb]
PFX FE l webatand l.[^mn]
PFX FE l webatann l.[mn]
PFX FE w webatamp [w]
PFX FE 0 webatamu .
PFX FE 0 webataba .
PFX FE 0 webatagu .
PFX FE 0 webatagi .
PFX FE 0 webatazi .
PFX FE 0 webataki .
PFX FE 0 webatabi .
PFX FE 0 webatali .
PFX FE 0 webataga .
PFX FE 0 webataka .
PFX FE 0 webatabu .
PFX FE 0 webatalu .
PFX FE 0 webataku .
PFX FE 0 webatatu .
PFX FE 0 wegutan [^lmnb]
PFX FE l wegutand l.[^mn]
PFX FE l wegutann l.[mn]
PFX FE w wegutamp [w]
PFX FE 0 wegutamu .
PFX FE 0 wegutaba .
PFX FE 0 wegutagu .
PFX FE 0 wegutagi .
PFX FE 0 wegutazi .
PFX FE 0 wegutaki .
PFX FE 0 wegutabi .
PFX FE 0 wegutali .
PFX FE 0 wegutaga .
PFX FE 0 wegutaka .
PFX FE 0 wegutabu .
PFX FE 0 wegutalu .
PFX FE 0 wegutaku .
PFX FE 0 wegutatu .
PFX FE 0 wegitan [^lmnb]
PFX FE l wegitand l.[^mn]
PFX FE l wegitann l.[mn]
PFX FE w wegitamp [w]
PFX FE 0 wegitamu .
PFX FE 0 wegitaba .
PFX FE 0 wegitagu .
PFX FE 0 wegitagi .
PFX FE 0 wegitazi .
PFX FE 0 wegitaki .
PFX FE 0 wegitabi .
PFX FE 0 wegitali .
PFX FE 0 wegitaga .
PFX FE 0 wegitaka .
PFX FE 0 wegitabu .
PFX FE 0 wegitalu .
PFX FE 0 wegitaku .
PFX FE 0 wegitatu .
PFX FE 0 wezitan [^lmnb]
PFX FE l wezitand l.[^mn]
PFX FE l wezitann l.[mn]
PFX FE w wezitamp [w]
PFX FE 0 wezitamu .
PFX FE 0 wezitaba .
PFX FE 0 wezitagu .
PFX FE 0 wezitagi .
PFX FE 0 wezitazi .
PFX FE 0 wezitaki .
PFX FE 0 wezitabi .
PFX FE 0 wezitali .
PFX FE 0 wezitaga .
PFX FE 0 wezitaka .
PFX FE 0 wezitabu .
PFX FE 0 wezitalu .
PFX FE 0 wezitaku .
PFX FE 0 wezitatu .
PFX FE 0 wekitan [^lmnb]
PFX FE l wekitand l.[^mn]
PFX FE l wekitann l.[mn]
PFX FE w wekitamp [w]
PFX FE 0 wekitamu .
PFX FE 0 wekitaba .
PFX FE 0 wekitagu .
PFX FE 0 wekitagi .
PFX FE 0 wekitazi .
PFX FE 0 wekitaki .
PFX FE 0 wekitabi .
PFX FE 0 wekitali .
PFX FE 0 wekitaga .
PFX FE 0 wekitaka .
PFX FE 0 wekitabu .
PFX FE 0 wekitalu .
PFX FE 0 wekitaku .
PFX FE 0 wekitatu .
PFX FE 0 webitan [^lmnb]
PFX FE l webitand l.[^mn]
PFX FE l webitann l.[mn]
PFX FE w webitamp [w]
PFX FE 0 webitamu .
PFX FE 0 webitaba .
PFX FE 0 webitagu .
PFX FE 0 webitagi .
PFX FE 0 webitazi .
PFX FE 0 webitaki .
PFX FE 0 webitabi .
PFX FE 0 webitali .
PFX FE 0 webitaga .
PFX FE 0 webitaka .
PFX FE 0 webitabu .
PFX FE 0 webitalu .
PFX FE 0 webitaku .
PFX FE 0 webitatu .
PFX FE 0 welitan [^lmnb]
PFX FE l welitand l.[^mn]
PFX FE l welitann l.[mn]
PFX FE w welitamp [w]
PFX FE 0 welitamu .
PFX FE 0 welitaba .
PFX FE 0 welitagu .
PFX FE 0 welitagi .
PFX FE 0 welitazi .
PFX FE 0 welitaki .
PFX FE 0 welitabi .
PFX FE 0 welitali .
PFX FE 0 welitaga .
PFX FE 0 welitaka .
PFX FE 0 welitabu .
PFX FE 0 welitalu .
PFX FE 0 welitaku .
PFX FE 0 welitatu .
PFX FE 0 wegatan [^lmnb]
PFX FE l wegatand l.[^mn]
PFX FE l wegatann l.[mn]
PFX FE w wegatamp [w]
PFX FE 0 wegatamu .
PFX FE 0 wegataba .
PFX FE 0 wegatagu .
PFX FE 0 wegatagi .
PFX FE 0 wegatazi .
PFX FE 0 wegataki .
PFX FE 0 wegatabi .
PFX FE 0 wegatali .
PFX FE 0 wegataga .
PFX FE 0 wegataka .
PFX FE 0 wegatabu .
PFX FE 0 wegatalu .
PFX FE 0 wegataku .
PFX FE 0 wegatatu .
PFX FE 0 wekatan [^lmnb]
PFX FE l wekatand l.[^mn]
PFX FE l wekatann l.[mn]
PFX FE w wekatamp [w]
PFX FE 0 wekatamu .
PFX FE 0 wekataba .
PFX FE 0 wekatagu .
PFX FE 0 wekatagi .
PFX FE 0 wekatazi .
PFX FE 0 wekataki .
PFX FE 0 wekatabi .
PFX FE 0 wekatali .
PFX FE 0 wekataga .
PFX FE 0 wekataka .
PFX FE 0 wekatabu .
PFX FE 0 wekatalu .
PFX FE 0 wekataku .
PFX FE 0 wekatatu .
PFX FE 0 webutan [^lmnb]
PFX FE l webutand l.[^mn]
PFX FE l webutann l.[mn]
PFX FE w webutamp [w]
PFX FE 0 webutamu .
PFX FE 0 webutaba .
PFX FE 0 webutagu .
PFX FE 0 webutagi .
PFX FE 0 webutazi .
PFX FE 0 webutaki .
PFX FE 0 webutabi .
PFX FE 0 webutali .
PFX FE 0 webutaga .
PFX FE 0 webutaka .
PFX FE 0 webutabu .
PFX FE 0 webutalu .
PFX FE 0 webutaku .
PFX FE 0 webutatu .
PFX FE 0 welutan [^lmnb]
PFX FE l welutand l.[^mn]
PFX FE l welutann l.[mn]
PFX FE w welutamp [w]
PFX FE 0 welutamu .
PFX FE 0 welutaba .
PFX FE 0 welutagu .
PFX FE 0 welutagi .
PFX FE 0 welutazi .
PFX FE 0 welutaki .
PFX FE 0 welutabi .
PFX FE 0 welutali .
PFX FE 0 welutaga .
PFX FE 0 welutaka .
PFX FE 0 welutabu .
PFX FE 0 welutalu .
PFX FE 0 welutaku .
PFX FE 0 welutatu .
PFX FE 0 wekutan [^lmnb]
PFX FE l wekutand l.[^mn]
PFX FE l wekutann l.[mn]
PFX FE w wekutamp [w]
PFX FE 0 wekutamu .
PFX FE 0 wekutaba .
PFX FE 0 wekutagu .
PFX FE 0 wekutagi .
PFX FE 0 wekutazi .
PFX FE 0 wekutaki .
PFX FE 0 wekutabi .
PFX FE 0 wekutali .
PFX FE 0 wekutaga .
PFX FE 0 wekutaka .
PFX FE 0 wekutabu .
PFX FE 0 wekutalu .
PFX FE 0 wekutaku .
PFX FE 0 wekutatu .
PFX FE 0 wetutan [^lmnb]
PFX FE l wetutand l.[^mn]
PFX FE l wetutann l.[mn]
PFX FE w wetutamp [w]
PFX FE 0 wetutamu .
PFX FE 0 wetutaba .
PFX FE 0 wetutagu .
PFX FE 0 wetutagi .
PFX FE 0 wetutazi .
PFX FE 0 wetutaki .
PFX FE 0 wetutabi .
PFX FE 0 wetutali .
PFX FE 0 wetutaga .
PFX FE 0 wetutaka .
PFX FE 0 wetutabu .
PFX FE 0 wetutalu .
PFX FE 0 wetutaku .
PFX FE 0 wetutatu .
PFX FE 0 bwessiba .
PFX FE 0 bwessigu .
PFX FE 0 bwessigi .
PFX FE 0 bwessizi .
PFX FE 0 bwessiki .
PFX FE 0 bwessibi .
PFX FE 0 bwessili .
PFX FE 0 bwessiga .
PFX FE 0 bwessika .
PFX FE 0 bwessibu .
PFX FE 0 bwessilu .
PFX FE 0 bwessiku .
PFX FE 0 bwessitu .
PFX FE 0 bwessimu .
PFX FE 0 bwetutan [^lmnb]
PFX FE l bwetutand l.[^mn]
PFX FE l bwetutann l.[mn]
PFX FE w bwetutamp [w]
PFX FE 0 bwetutamu .
PFX FE 0 bwetutaba .
PFX FE 0 bwetutagu .
PFX FE 0 bwetutagi .
PFX FE 0 bwetutazi .
PFX FE 0 bwetutaki .
PFX FE 0 bwetutabi .
PFX FE 0 bwetutali .
PFX FE 0 bwetutaga .
PFX FE 0 bwetutaka .
PFX FE 0 bwetutabu .
PFX FE 0 bwetutalu .
PFX FE 0 bwetutaku .
PFX FE 0 bwetutatu .
PFX FE 0 bwemutan [^lmnb]
PFX FE l bwemutand l.[^mn]
PFX FE l bwemutann l.[mn]
PFX FE w bwemutamp [w]
PFX FE 0 bwemutamu .
PFX FE 0 bwemutaba .
PFX FE 0 bwemutagu .
PFX FE 0 bwemutagi .
PFX FE 0 bwemutazi .
PFX FE 0 bwemutaki .
PFX FE 0 bwemutabi .
PFX FE 0 bwemutali .
PFX FE 0 bwemutaga .
PFX FE 0 bwemutaka .
PFX FE 0 bwemutabu .
PFX FE 0 bwemutalu .
PFX FE 0 bwemutaku .
PFX FE 0 bwemutatu .
PFX FE 0 bwebatan [^lmnb]
PFX FE l bwebatand l.[^mn]
PFX FE l bwebatann l.[mn]
PFX FE w bwebatamp [w]
PFX FE 0 bwebatamu .
PFX FE 0 bwebataba .
PFX FE 0 bwebatagu .
PFX FE 0 bwebatagi .
PFX FE 0 bwebatazi .
PFX FE 0 bwebataki .
PFX FE 0 bwebatabi .
PFX FE 0 bwebatali .
PFX FE 0 bwebataga .
PFX FE 0 bwebataka .
PFX FE 0 bwebatabu .
PFX FE 0 bwebatalu .
PFX FE 0 bwebataku .
PFX FE 0 bwebatatu .
PFX FE 0 bwegutan [^lmnb]
PFX FE l bwegutand l.[^mn]
PFX FE l bwegutann l.[mn]
PFX FE w bwegutamp [w]
PFX FE 0 bwegutamu .
PFX FE 0 bwegutaba .
PFX FE 0 bwegutagu .
PFX FE 0 bwegutagi .
PFX FE 0 bwegutazi .
PFX FE 0 bwegutaki .
PFX FE 0 bwegutabi .
PFX FE 0 bwegutali .
PFX FE 0 bwegutaga .
PFX FE 0 bwegutaka .
PFX FE 0 bwegutabu .
PFX FE 0 bwegutalu .
PFX FE 0 bwegutaku .
PFX FE 0 bwegutatu .
PFX FE 0 bwegitan [^lmnb]
PFX FE l bwegitand l.[^mn]
PFX FE l bwegitann l.[mn]
PFX FE w bwegitamp [w]
PFX FE 0 bwegitamu .
PFX FE 0 bwegitaba .
PFX FE 0 bwegitagu .
PFX FE 0 bwegitagi .
PFX FE 0 bwegitazi .
PFX FE 0 bwegitaki .
PFX FE 0 bwegitabi .
PFX FE 0 bwegitali .
PFX FE 0 bwegitaga .
PFX FE 0 bwegitaka .
PFX FE 0 bwegitabu .
PFX FE 0 bwegitalu .
PFX FE 0 bwegitaku .
PFX FE 0 bwegitatu .
PFX FE 0 bwezitan [^lmnb]
PFX FE l bwezitand l.[^mn]
PFX FE l bwezitann l.[mn]
PFX FE w bwezitamp [w]
PFX FE 0 bwezitamu .
PFX FE 0 bwezitaba .
PFX FE 0 bwezitagu .
PFX FE 0 bwezitagi .
PFX FE 0 bwezitazi .
PFX FE 0 bwezitaki .
PFX FE 0 bwezitabi .
PFX FE 0 bwezitali .
PFX FE 0 bwezitaga .
PFX FE 0 bwezitaka .
PFX FE 0 bwezitabu .
PFX FE 0 bwezitalu .
PFX FE 0 bwezitaku .
PFX FE 0 bwezitatu .
PFX FE 0 bwekitan [^lmnb]
PFX FE l bwekitand l.[^mn]
PFX FE l bwekitann l.[mn]
PFX FE w bwekitamp [w]
PFX FE 0 bwekitamu .
PFX FE 0 bwekitaba .
PFX FE 0 bwekitagu .
PFX FE 0 bwekitagi .
PFX FE 0 bwekitazi .
PFX FE 0 bwekitaki .
PFX FE 0 bwekitabi .
PFX FE 0 bwekitali .
PFX FE 0 bwekitaga .
PFX FE 0 bwekitaka .
PFX FE 0 bwekitabu .
PFX FE 0 bwekitalu .
PFX FE 0 bwekitaku .
PFX FE 0 bwekitatu .
PFX FE 0 bwebitan [^lmnb]
PFX FE l bwebitand l.[^mn]
PFX FE l bwebitann l.[mn]
PFX FE w bwebitamp [w]
PFX FE 0 bwebitamu .
PFX FE 0 bwebitaba .
PFX FE 0 bwebitagu .
PFX FE 0 bwebitagi .
PFX FE 0 bwebitazi .
PFX FE 0 bwebitaki .
PFX FE 0 bwebitabi .
PFX FE 0 bwebitali .
PFX FE 0 bwebitaga .
PFX FE 0 bwebitaka .
PFX FE 0 bwebitabu .
PFX FE 0 bwebitalu .
PFX FE 0 bwebitaku .
PFX FE 0 bwebitatu .
PFX FE 0 bwelitan [^lmnb]
PFX FE l bwelitand l.[^mn]
PFX FE l bwelitann l.[mn]
PFX FE w bwelitamp [w]
PFX FE 0 bwelitamu .
PFX FE 0 bwelitaba .
PFX FE 0 bwelitagu .
PFX FE 0 bwelitagi .
PFX FE 0 bwelitazi .
PFX FE 0 bwelitaki .
PFX FE 0 bwelitabi .
PFX FE 0 bwelitali .
PFX FE 0 bwelitaga .
PFX FE 0 bwelitaka .
PFX FE 0 bwelitabu .
PFX FE 0 bwelitalu .
PFX FE 0 bwelitaku .
PFX FE 0 bwelitatu .
PFX FE 0 bwegatan [^lmnb]
PFX FE l bwegatand l.[^mn]
PFX FE l bwegatann l.[mn]
PFX FE w bwegatamp [w]
PFX FE 0 bwegatamu .
PFX FE 0 bwegataba .
PFX FE 0 bwegatagu .
PFX FE 0 bwegatagi .
PFX FE 0 bwegatazi .
PFX FE 0 bwegataki .
PFX FE 0 bwegatabi .
PFX FE 0 bwegatali .
PFX FE 0 bwegataga .
PFX FE 0 bwegataka .
PFX FE 0 bwegatabu .
PFX FE 0 bwegatalu .
PFX FE 0 bwegataku .
PFX FE 0 bwegatatu .
PFX FE 0 bwekatan [^lmnb]
PFX FE l bwekatand l.[^mn]
PFX FE l bwekatann l.[mn]
PFX FE w bwekatamp [w]
PFX FE 0 bwekatamu .
PFX FE 0 bwekataba .
PFX FE 0 bwekatagu .
PFX FE 0 bwekatagi .
PFX FE 0 bwekatazi .
PFX FE 0 bwekataki .
PFX FE 0 bwekatabi .
PFX FE 0 bwekatali .
PFX FE 0 bwekataga .
PFX FE 0 bwekataka .
PFX FE 0 bwekatabu .
PFX FE 0 bwekatalu .
PFX FE 0 bwekataku .
PFX FE 0 bwekatatu .
PFX FE 0 bwebutan [^lmnb]
PFX FE l bwebutand l.[^mn]
PFX FE l bwebutann l.[mn]
PFX FE w bwebutamp [w]
PFX FE 0 bwebutamu .
PFX FE 0 bwebutaba .
PFX FE 0 bwebutagu .
PFX FE 0 bwebutagi .
PFX FE 0 bwebutazi .
PFX FE 0 bwebutaki .
PFX FE 0 bwebutabi .
PFX FE 0 bwebutali .
PFX FE 0 bwebutaga .
PFX FE 0 bwebutaka .
PFX FE 0 bwebutabu .
PFX FE 0 bwebutalu .
PFX FE 0 bwebutaku .
PFX FE 0 bwebutatu .
PFX FE 0 bwelutan [^lmnb]
PFX FE l bwelutand l.[^mn]
PFX FE l bwelutann l.[mn]
PFX FE w bwelutamp [w]
PFX FE 0 bwelutamu .
PFX FE 0 bwelutaba .
PFX FE 0 bwelutagu .
PFX FE 0 bwelutagi .
PFX FE 0 bwelutazi .
PFX FE 0 bwelutaki .
PFX FE 0 bwelutabi .
PFX FE 0 bwelutali .
PFX FE 0 bwelutaga .
PFX FE 0 bwelutaka .
PFX FE 0 bwelutabu .
PFX FE 0 bwelutalu .
PFX FE 0 bwelutaku .
PFX FE 0 bwelutatu .
PFX FE 0 bwekutan [^lmnb]
PFX FE l bwekutand l.[^mn]
PFX FE l bwekutann l.[mn]
PFX FE w bwekutamp [w]
PFX FE 0 bwekutamu .
PFX FE 0 bwekutaba .
PFX FE 0 bwekutagu .
PFX FE 0 bwekutagi .
PFX FE 0 bwekutazi .
PFX FE 0 bwekutaki .
PFX FE 0 bwekutabi .
PFX FE 0 bwekutali .
PFX FE 0 bwekutaga .
PFX FE 0 bwekutaka .
PFX FE 0 bwekutabu .
PFX FE 0 bwekutalu .
PFX FE 0 bwekutaku .
PFX FE 0 bwekutatu .
PFX FE 0 bwetutan [^lmnb]
PFX FE l bwetutand l.[^mn]
PFX FE l bwetutann l.[mn]
PFX FE w bwetutamp [w]
PFX FE 0 bwetutamu .
PFX FE 0 bwetutaba .
PFX FE 0 bwetutagu .
PFX FE 0 bwetutagi .
PFX FE 0 bwetutazi .
PFX FE 0 bwetutaki .
PFX FE 0 bwetutabi .
PFX FE 0 bwetutali .
PFX FE 0 bwetutaga .
PFX FE 0 bwetutaka .
PFX FE 0 bwetutabu .
PFX FE 0 bwetutalu .
PFX FE 0 bwetutaku .
PFX FE 0 bwetutatu .
PFX FE 0 lwessiba .
PFX FE 0 lwessigu .
PFX FE 0 lwessigi .
PFX FE 0 lwessizi .
PFX FE 0 lwessiki .
PFX FE 0 lwessibi .
PFX FE 0 lwessili .
PFX FE 0 lwessiga .
PFX FE 0 lwessika .
PFX FE 0 lwessibu .
PFX FE 0 lwessilu .
PFX FE 0 lwessiku .
PFX FE 0 lwessitu .
PFX FE 0 lwessimu .
PFX FE 0 lwetutan [^lmnb]
PFX FE l lwetutand l.[^mn]
PFX FE l lwetutann l.[mn]
PFX FE w lwetutamp [w]
PFX FE 0 lwetutamu .
PFX FE 0 lwetutaba .
PFX FE 0 lwetutagu .
PFX FE 0 lwetutagi .
PFX FE 0 lwetutazi .
PFX FE 0 lwetutaki .
PFX FE 0 lwetutabi .
PFX FE 0 lwetutali .
PFX FE 0 lwetutaga .
PFX FE 0 lwetutaka .
PFX FE 0 lwetutabu .
PFX FE 0 lwetutalu .
PFX FE 0 lwetutaku .
PFX FE 0 lwetutatu .
PFX FE 0 lwemutan [^lmnb]
PFX FE l lwemutand l.[^mn]
PFX FE l lwemutann l.[mn]
PFX FE w lwemutamp [w]
PFX FE 0 lwemutamu .
PFX FE 0 lwemutaba .
PFX FE 0 lwemutagu .
PFX FE 0 lwemutagi .
PFX FE 0 lwemutazi .
PFX FE 0 lwemutaki .
PFX FE 0 lwemutabi .
PFX FE 0 lwemutali .
PFX FE 0 lwemutaga .
PFX FE 0 lwemutaka .
PFX FE 0 lwemutabu .
PFX FE 0 lwemutalu .
PFX FE 0 lwemutaku .
PFX FE 0 lwemutatu .
PFX FE 0 lwebatan [^lmnb]
PFX FE l lwebatand l.[^mn]
PFX FE l lwebatann l.[mn]
PFX FE w lwebatamp [w]
PFX FE 0 lwebatamu .
PFX FE 0 lwebataba .
PFX FE 0 lwebatagu .
PFX FE 0 lwebatagi .
PFX FE 0 lwebatazi .
PFX FE 0 lwebataki .
PFX FE 0 lwebatabi .
PFX FE 0 lwebatali .
PFX FE 0 lwebataga .
PFX FE 0 lwebataka .
PFX FE 0 lwebatabu .
PFX FE 0 lwebatalu .
PFX FE 0 lwebataku .
PFX FE 0 lwebatatu .
PFX FE 0 lwegutan [^lmnb]
PFX FE l lwegutand l.[^mn]
PFX FE l lwegutann l.[mn]
PFX FE w lwegutamp [w]
PFX FE 0 lwegutamu .
PFX FE 0 lwegutaba .
PFX FE 0 lwegutagu .
PFX FE 0 lwegutagi .
PFX FE 0 lwegutazi .
PFX FE 0 lwegutaki .
PFX FE 0 lwegutabi .
PFX FE 0 lwegutali .
PFX FE 0 lwegutaga .
PFX FE 0 lwegutaka .
PFX FE 0 lwegutabu .
PFX FE 0 lwegutalu .
PFX FE 0 lwegutaku .
PFX FE 0 lwegutatu .
PFX FE 0 lwegitan [^lmnb]
PFX FE l lwegitand l.[^mn]
PFX FE l lwegitann l.[mn]
PFX FE w lwegitamp [w]
PFX FE 0 lwegitamu .
PFX FE 0 lwegitaba .
PFX FE 0 lwegitagu .
PFX FE 0 lwegitagi .
PFX FE 0 lwegitazi .
PFX FE 0 lwegitaki .
PFX FE 0 lwegitabi .
PFX FE 0 lwegitali .
PFX FE 0 lwegitaga .
PFX FE 0 lwegitaka .
PFX FE 0 lwegitabu .
PFX FE 0 lwegitalu .
PFX FE 0 lwegitaku .
PFX FE 0 lwegitatu .
PFX FE 0 lwezitan [^lmnb]
PFX FE l lwezitand l.[^mn]
PFX FE l lwezitann l.[mn]
PFX FE w lwezitamp [w]
PFX FE 0 lwezitamu .
PFX FE 0 lwezitaba .
PFX FE 0 lwezitagu .
PFX FE 0 lwezitagi .
PFX FE 0 lwezitazi .
PFX FE 0 lwezitaki .
PFX FE 0 lwezitabi .
PFX FE 0 lwezitali .
PFX FE 0 lwezitaga .
PFX FE 0 lwezitaka .
PFX FE 0 lwezitabu .
PFX FE 0 lwezitalu .
PFX FE 0 lwezitaku .
PFX FE 0 lwezitatu .
PFX FE 0 lwekitan [^lmnb]
PFX FE l lwekitand l.[^mn]
PFX FE l lwekitann l.[mn]
PFX FE w lwekitamp [w]
PFX FE 0 lwekitamu .
PFX FE 0 lwekitaba .
PFX FE 0 lwekitagu .
PFX FE 0 lwekitagi .
PFX FE 0 lwekitazi .
PFX FE 0 lwekitaki .
PFX FE 0 lwekitabi .
PFX FE 0 lwekitali .
PFX FE 0 lwekitaga .
PFX FE 0 lwekitaka .
PFX FE 0 lwekitabu .
PFX FE 0 lwekitalu .
PFX FE 0 lwekitaku .
PFX FE 0 lwekitatu .
PFX FE 0 lwebitan [^lmnb]
PFX FE l lwebitand l.[^mn]
PFX FE l lwebitann l.[mn]
PFX FE w lwebitamp [w]
PFX FE 0 lwebitamu .
PFX FE 0 lwebitaba .
PFX FE 0 lwebitagu .
PFX FE 0 lwebitagi .
PFX FE 0 lwebitazi .
PFX FE 0 lwebitaki .
PFX FE 0 lwebitabi .
PFX FE 0 lwebitali .
PFX FE 0 lwebitaga .
PFX FE 0 lwebitaka .
PFX FE 0 lwebitabu .
PFX FE 0 lwebitalu .
PFX FE 0 lwebitaku .
PFX FE 0 lwebitatu .
PFX FE 0 lwelitan [^lmnb]
PFX FE l lwelitand l.[^mn]
PFX FE l lwelitann l.[mn]
PFX FE w lwelitamp [w]
PFX FE 0 lwelitamu .
PFX FE 0 lwelitaba .
PFX FE 0 lwelitagu .
PFX FE 0 lwelitagi .
PFX FE 0 lwelitazi .
PFX FE 0 lwelitaki .
PFX FE 0 lwelitabi .
PFX FE 0 lwelitali .
PFX FE 0 lwelitaga .
PFX FE 0 lwelitaka .
PFX FE 0 lwelitabu .
PFX FE 0 lwelitalu .
PFX FE 0 lwelitaku .
PFX FE 0 lwelitatu .
PFX FE 0 lwegatan [^lmnb]
PFX FE l lwegatand l.[^mn]
PFX FE l lwegatann l.[mn]
PFX FE w lwegatamp [w]
PFX FE 0 lwegatamu .
PFX FE 0 lwegataba .
PFX FE 0 lwegatagu .
PFX FE 0 lwegatagi .
PFX FE 0 lwegatazi .
PFX FE 0 lwegataki .
PFX FE 0 lwegatabi .
PFX FE 0 lwegatali .
PFX FE 0 lwegataga .
PFX FE 0 lwegataka .
PFX FE 0 lwegatabu .
PFX FE 0 lwegatalu .
PFX FE 0 lwegataku .
PFX FE 0 lwegatatu .
PFX FE 0 lwekatan [^lmnb]
PFX FE l lwekatand l.[^mn]
PFX FE l lwekatann l.[mn]
PFX FE w lwekatamp [w]
PFX FE 0 lwekatamu .
PFX FE 0 lwekataba .
PFX FE 0 lwekatagu .
PFX FE 0 lwekatagi .
PFX FE 0 lwekatazi .
PFX FE 0 lwekataki .
PFX FE 0 lwekatabi .
PFX FE 0 lwekatali .
PFX FE 0 lwekataga .
PFX FE 0 lwekataka .
PFX FE 0 lwekatabu .
PFX FE 0 lwekatalu .
PFX FE 0 lwekataku .
PFX FE 0 lwekatatu .
PFX FE 0 lwebutan [^lmnb]
PFX FE l lwebutand l.[^mn]
PFX FE l lwebutann l.[mn]
PFX FE w lwebutamp [w]
PFX FE 0 lwebutamu .
PFX FE 0 lwebutaba .
PFX FE 0 lwebutagu .
PFX FE 0 lwebutagi .
PFX FE 0 lwebutazi .
PFX FE 0 lwebutaki .
PFX FE 0 lwebutabi .
PFX FE 0 lwebutali .
PFX FE 0 lwebutaga .
PFX FE 0 lwebutaka .
PFX FE 0 lwebutabu .
PFX FE 0 lwebutalu .
PFX FE 0 lwebutaku .
PFX FE 0 lwebutatu .
PFX FE 0 lwelutan [^lmnb]
PFX FE l lwelutand l.[^mn]
PFX FE l lwelutann l.[mn]
PFX FE w lwelutamp [w]
PFX FE 0 lwelutamu .
PFX FE 0 lwelutaba .
PFX FE 0 lwelutagu .
PFX FE 0 lwelutagi .
PFX FE 0 lwelutazi .
PFX FE 0 lwelutaki .
PFX FE 0 lwelutabi .
PFX FE 0 lwelutali .
PFX FE 0 lwelutaga .
PFX FE 0 lwelutaka .
PFX FE 0 lwelutabu .
PFX FE 0 lwelutalu .
PFX FE 0 lwelutaku .
PFX FE 0 lwelutatu .
PFX FE 0 lwekutan [^lmnb]
PFX FE l lwekutand l.[^mn]
PFX FE l lwekutann l.[mn]
PFX FE w lwekutamp [w]
PFX FE 0 lwekutamu .
PFX FE 0 lwekutaba .
PFX FE 0 lwekutagu .
PFX FE 0 lwekutagi .
PFX FE 0 lwekutazi .
PFX FE 0 lwekutaki .
PFX FE 0 lwekutabi .
PFX FE 0 lwekutali .
PFX FE 0 lwekutaga .
PFX FE 0 lwekutaka .
PFX FE 0 lwekutabu .
PFX FE 0 lwekutalu .
PFX FE 0 lwekutaku .
PFX FE 0 lwekutatu .
PFX FE 0 lwetutan [^lmnb]
PFX FE l lwetutand l.[^mn]
PFX FE l lwetutann l.[mn]
PFX FE w lwetutamp [w]
PFX FE 0 lwetutamu .
PFX FE 0 lwetutaba .
PFX FE 0 lwetutagu .
PFX FE 0 lwetutagi .
PFX FE 0 lwetutazi .
PFX FE 0 lwetutaki .
PFX FE 0 lwetutabi .
PFX FE 0 lwetutali .
PFX FE 0 lwetutaga .
PFX FE 0 lwetutaka .
PFX FE 0 lwetutabu .
PFX FE 0 lwetutalu .
PFX FE 0 lwetutaku .
PFX FE 0 lwetutatu .
PFX FE 0 zessiba .
PFX FE 0 zessigu .
PFX FE 0 zessigi .
PFX FE 0 zessizi .
PFX FE 0 zessiki .
PFX FE 0 zessibi .
PFX FE 0 zessili .
PFX FE 0 zessiga .
PFX FE 0 zessika .
PFX FE 0 zessibu .
PFX FE 0 zessilu .
PFX FE 0 zessiku .
PFX FE 0 zessitu .
PFX FE 0 zessimu .
PFX FE 0 zetutan [^lmnb]
PFX FE l zetutand l.[^mn]
PFX FE l zetutann l.[mn]
PFX FE w zetutamp [w]
PFX FE 0 zetutamu .
PFX FE 0 zetutaba .
PFX FE 0 zetutagu .
PFX FE 0 zetutagi .
PFX FE 0 zetutazi .
PFX FE 0 zetutaki .
PFX FE 0 zetutabi .
PFX FE 0 zetutali .
PFX FE 0 zetutaga .
PFX FE 0 zetutaka .
PFX FE 0 zetutabu .
PFX FE 0 zetutalu .
PFX FE 0 zetutaku .
PFX FE 0 zetutatu .
PFX FE 0 zemutan [^lmnb]
PFX FE l zemutand l.[^mn]
PFX FE l zemutann l.[mn]
PFX FE w zemutamp [w]
PFX FE 0 zemutamu .
PFX FE 0 zemutaba .
PFX FE 0 zemutagu .
PFX FE 0 zemutagi .
PFX FE 0 zemutazi .
PFX FE 0 zemutaki .
PFX FE 0 zemutabi .
PFX FE 0 zemutali .
PFX FE 0 zemutaga .
PFX FE 0 zemutaka .
PFX FE 0 zemutabu .
PFX FE 0 zemutalu .
PFX FE 0 zemutaku .
PFX FE 0 zemutatu .
PFX FE 0 zebatan [^lmnb]
PFX FE l zebatand l.[^mn]
PFX FE l zebatann l.[mn]
PFX FE w zebatamp [w]
PFX FE 0 zebatamu .
PFX FE 0 zebataba .
PFX FE 0 zebatagu .
PFX FE 0 zebatagi .
PFX FE 0 zebatazi .
PFX FE 0 zebataki .
PFX FE 0 zebatabi .
PFX FE 0 zebatali .
PFX FE 0 zebataga .
PFX FE 0 zebataka .
PFX FE 0 zebatabu .
PFX FE 0 zebatalu .
PFX FE 0 zebataku .
PFX FE 0 zebatatu .
PFX FE 0 zegutan [^lmnb]
PFX FE l zegutand l.[^mn]
PFX FE l zegutann l.[mn]
PFX FE w zegutamp [w]
PFX FE 0 zegutamu .
PFX FE 0 zegutaba .
PFX FE 0 zegutagu .
PFX FE 0 zegutagi .
PFX FE 0 zegutazi .
PFX FE 0 zegutaki .
PFX FE 0 zegutabi .
PFX FE 0 zegutali .
PFX FE 0 zegutaga .
PFX FE 0 zegutaka .
PFX FE 0 zegutabu .
PFX FE 0 zegutalu .
PFX FE 0 zegutaku .
PFX FE 0 zegutatu .
PFX FE 0 zegitan [^lmnb]
PFX FE l zegitand l.[^mn]
PFX FE l zegitann l.[mn]
PFX FE w zegitamp [w]
PFX FE 0 zegitamu .
PFX FE 0 zegitaba .
PFX FE 0 zegitagu .
PFX FE 0 zegitagi .
PFX FE 0 zegitazi .
PFX FE 0 zegitaki .
PFX FE 0 zegitabi .
PFX FE 0 zegitali .
PFX FE 0 zegitaga .
PFX FE 0 zegitaka .
PFX FE 0 zegitabu .
PFX FE 0 zegitalu .
PFX FE 0 zegitaku .
PFX FE 0 zegitatu .
PFX FE 0 zezitan [^lmnb]
PFX FE l zezitand l.[^mn]
PFX FE l zezitann l.[mn]
PFX FE w zezitamp [w]
PFX FE 0 zezitamu .
PFX FE 0 zezitaba .
PFX FE 0 zezitagu .
PFX FE 0 zezitagi .
PFX FE 0 zezitazi .
PFX FE 0 zezitaki .
PFX FE 0 zezitabi .
PFX FE 0 zezitali .
PFX FE 0 zezitaga .
PFX FE 0 zezitaka .
PFX FE 0 zezitabu .
PFX FE 0 zezitalu .
PFX FE 0 zezitaku .
PFX FE 0 zezitatu .
PFX FE 0 zekitan [^lmnb]
PFX FE l zekitand l.[^mn]
PFX FE l zekitann l.[mn]
PFX FE w zekitamp [w]
PFX FE 0 zekitamu .
PFX FE 0 zekitaba .
PFX FE 0 zekitagu .
PFX FE 0 zekitagi .
PFX FE 0 zekitazi .
PFX FE 0 zekitaki .
PFX FE 0 zekitabi .
PFX FE 0 zekitali .
PFX FE 0 zekitaga .
PFX FE 0 zekitaka .
PFX FE 0 zekitabu .
PFX FE 0 zekitalu .
PFX FE 0 zekitaku .
PFX FE 0 zekitatu .
PFX FE 0 zebitan [^lmnb]
PFX FE l zebitand l.[^mn]
PFX FE l zebitann l.[mn]
PFX FE w zebitamp [w]
PFX FE 0 zebitamu .
PFX FE 0 zebitaba .
PFX FE 0 zebitagu .
PFX FE 0 zebitagi .
PFX FE 0 zebitazi .
PFX FE 0 zebitaki .
PFX FE 0 zebitabi .
PFX FE 0 zebitali .
PFX FE 0 zebitaga .
PFX FE 0 zebitaka .
PFX FE 0 zebitabu .
PFX FE 0 zebitalu .
PFX FE 0 zebitaku .
PFX FE 0 zebitatu .
PFX FE 0 zelitan [^lmnb]
PFX FE l zelitand l.[^mn]
PFX FE l zelitann l.[mn]
PFX FE w zelitamp [w]
PFX FE 0 zelitamu .
PFX FE 0 zelitaba .
PFX FE 0 zelitagu .
PFX FE 0 zelitagi .
PFX FE 0 zelitazi .
PFX FE 0 zelitaki .
PFX FE 0 zelitabi .
PFX FE 0 zelitali .
PFX FE 0 zelitaga .
PFX FE 0 zelitaka .
PFX FE 0 zelitabu .
PFX FE 0 zelitalu .
PFX FE 0 zelitaku .
PFX FE 0 zelitatu .
PFX FE 0 zegatan [^lmnb]
PFX FE l zegatand l.[^mn]
PFX FE l zegatann l.[mn]
PFX FE w zegatamp [w]
PFX FE 0 zegatamu .
PFX FE 0 zegataba .
PFX FE 0 zegatagu .
PFX FE 0 zegatagi .
PFX FE 0 zegatazi .
PFX FE 0 zegataki .
PFX FE 0 zegatabi .
PFX FE 0 zegatali .
PFX FE 0 zegataga .
PFX FE 0 zegataka .
PFX FE 0 zegatabu .
PFX FE 0 zegatalu .
PFX FE 0 zegataku .
PFX FE 0 zegatatu .
PFX FE 0 zekatan [^lmnb]
PFX FE l zekatand l.[^mn]
PFX FE l zekatann l.[mn]
PFX FE w zekatamp [w]
PFX FE 0 zekatamu .
PFX FE 0 zekataba .
PFX FE 0 zekatagu .
PFX FE 0 zekatagi .
PFX FE 0 zekatazi .
PFX FE 0 zekataki .
PFX FE 0 zekatabi .
PFX FE 0 zekatali .
PFX FE 0 zekataga .
PFX FE 0 zekataka .
PFX FE 0 zekatabu .
PFX FE 0 zekatalu .
PFX FE 0 zekataku .
PFX FE 0 zekatatu .
PFX FE 0 zebutan [^lmnb]
PFX FE l zebutand l.[^mn]
PFX FE l zebutann l.[mn]
PFX FE w zebutamp [w]
PFX FE 0 zebutamu .
PFX FE 0 zebutaba .
PFX FE 0 zebutagu .
PFX FE 0 zebutagi .
PFX FE 0 zebutazi .
PFX FE 0 zebutaki .
PFX FE 0 zebutabi .
PFX FE 0 zebutali .
PFX FE 0 zebutaga .
PFX FE 0 zebutaka .
PFX FE 0 zebutabu .
PFX FE 0 zebutalu .
PFX FE 0 zebutaku .
PFX FE 0 zebutatu .
PFX FE 0 zelutan [^lmnb]
PFX FE l zelutand l.[^mn]
PFX FE l zelutann l.[mn]
PFX FE w zelutamp [w]
PFX FE 0 zelutamu .
PFX FE 0 zelutaba .
PFX FE 0 zelutagu .
PFX FE 0 zelutagi .
PFX FE 0 zelutazi .
PFX FE 0 zelutaki .
PFX FE 0 zelutabi .
PFX FE 0 zelutali .
PFX FE 0 zelutaga .
PFX FE 0 zelutaka .
PFX FE 0 zelutabu .
PFX FE 0 zelutalu .
PFX FE 0 zelutaku .
PFX FE 0 zelutatu .
PFX FE 0 zekutan [^lmnb]
PFX FE l zekutand l.[^mn]
PFX FE l zekutann l.[mn]
PFX FE w zekutamp [w]
PFX FE 0 zekutamu .
PFX FE 0 zekutaba .
PFX FE 0 zekutagu .
PFX FE 0 zekutagi .
PFX FE 0 zekutazi .
PFX FE 0 zekutaki .
PFX FE 0 zekutabi .
PFX FE 0 zekutali .
PFX FE 0 zekutaga .
PFX FE 0 zekutaka .
PFX FE 0 zekutabu .
PFX FE 0 zekutalu .
PFX FE 0 zekutaku .
PFX FE 0 zekutatu .
PFX FE 0 zetutan [^lmnb]
PFX FE l zetutand l.[^mn]
PFX FE l zetutann l.[mn]
PFX FE w zetutamp [w]
PFX FE 0 zetutamu .
PFX FE 0 zetutaba .
PFX FE 0 zetutagu .
PFX FE 0 zetutagi .
PFX FE 0 zetutazi .
PFX FE 0 zetutaki .
PFX FE 0 zetutabi .
PFX FE 0 zetutali .
PFX FE 0 zetutaga .
PFX FE 0 zetutaka .
PFX FE 0 zetutabu .
PFX FE 0 zetutalu .
PFX FE 0 zetutaku .
PFX FE 0 zetutatu .
PFX FE 0 gwessiba .
PFX FE 0 gwessigu .
PFX FE 0 gwessigi .
PFX FE 0 gwessizi .
PFX FE 0 gwessiki .
PFX FE 0 gwessibi .
PFX FE 0 gwessili .
PFX FE 0 gwessiga .
PFX FE 0 gwessika .
PFX FE 0 gwessibu .
PFX FE 0 gwessilu .
PFX FE 0 gwessiku .
PFX FE 0 gwessitu .
PFX FE 0 gwessimu .
PFX FE 0 gwetutan [^lmnb]
PFX FE l gwetutand l.[^mn]
PFX FE l gwetutann l.[mn]
PFX FE w gwetutamp [w]
PFX FE 0 gwetutamu .
PFX FE 0 gwetutaba .
PFX FE 0 gwetutagu .
PFX FE 0 gwetutagi .
PFX FE 0 gwetutazi .
PFX FE 0 gwetutaki .
PFX FE 0 gwetutabi .
PFX FE 0 gwetutali .
PFX FE 0 gwetutaga .
PFX FE 0 gwetutaka .
PFX FE 0 gwetutabu .
PFX FE 0 gwetutalu .
PFX FE 0 gwetutaku .
PFX FE 0 gwetutatu .
PFX FE 0 gwemutan [^lmnb]
PFX FE l gwemutand l.[^mn]
PFX FE l gwemutann l.[mn]
PFX FE w gwemutamp [w]
PFX FE 0 gwemutamu .
PFX FE 0 gwemutaba .
PFX FE 0 gwemutagu .
PFX FE 0 gwemutagi .
PFX FE 0 gwemutazi .
PFX FE 0 gwemutaki .
PFX FE 0 gwemutabi .
PFX FE 0 gwemutali .
PFX FE 0 gwemutaga .
PFX FE 0 gwemutaka .
PFX FE 0 gwemutabu .
PFX FE 0 gwemutalu .
PFX FE 0 gwemutaku .
PFX FE 0 gwemutatu .
PFX FE 0 gwebatan [^lmnb]
PFX FE l gwebatand l.[^mn]
PFX FE l gwebatann l.[mn]
PFX FE w gwebatamp [w]
PFX FE 0 gwebatamu .
PFX FE 0 gwebataba .
PFX FE 0 gwebatagu .
PFX FE 0 gwebatagi .
PFX FE 0 gwebatazi .
PFX FE 0 gwebataki .
PFX FE 0 gwebatabi .
PFX FE 0 gwebatali .
PFX FE 0 gwebataga .
PFX FE 0 gwebataka .
PFX FE 0 gwebatabu .
PFX FE 0 gwebatalu .
PFX FE 0 gwebataku .
PFX FE 0 gwebatatu .
PFX FE 0 gwegutan [^lmnb]
PFX FE l gwegutand l.[^mn]
PFX FE l gwegutann l.[mn]
PFX FE w gwegutamp [w]
PFX FE 0 gwegutamu .
PFX FE 0 gwegutaba .
PFX FE 0 gwegutagu .
PFX FE 0 gwegutagi .
PFX FE 0 gwegutazi .
PFX FE 0 gwegutaki .
PFX FE 0 gwegutabi .
PFX FE 0 gwegutali .
PFX FE 0 gwegutaga .
PFX FE 0 gwegutaka .
PFX FE 0 gwegutabu .
PFX FE 0 gwegutalu .
PFX FE 0 gwegutaku .
PFX FE 0 gwegutatu .
PFX FE 0 gwegitan [^lmnb]
PFX FE l gwegitand l.[^mn]
PFX FE l gwegitann l.[mn]
PFX FE w gwegitamp [w]
PFX FE 0 gwegitamu .
PFX FE 0 gwegitaba .
PFX FE 0 gwegitagu .
PFX FE 0 gwegitagi .
PFX FE 0 gwegitazi .
PFX FE 0 gwegitaki .
PFX FE 0 gwegitabi .
PFX FE 0 gwegitali .
PFX FE 0 gwegitaga .
PFX FE 0 gwegitaka .
PFX FE 0 gwegitabu .
PFX FE 0 gwegitalu .
PFX FE 0 gwegitaku .
PFX FE 0 gwegitatu .
PFX FE 0 gwezitan [^lmnb]
PFX FE l gwezitand l.[^mn]
PFX FE l gwezitann l.[mn]
PFX FE w gwezitamp [w]
PFX FE 0 gwezitamu .
PFX FE 0 gwezitaba .
PFX FE 0 gwezitagu .
PFX FE 0 gwezitagi .
PFX FE 0 gwezitazi .
PFX FE 0 gwezitaki .
PFX FE 0 gwezitabi .
PFX FE 0 gwezitali .
PFX FE 0 gwezitaga .
PFX FE 0 gwezitaka .
PFX FE 0 gwezitabu .
PFX FE 0 gwezitalu .
PFX FE 0 gwezitaku .
PFX FE 0 gwezitatu .
PFX FE 0 gwekitan [^lmnb]
PFX FE l gwekitand l.[^mn]
PFX FE l gwekitann l.[mn]
PFX FE w gwekitamp [w]
PFX FE 0 gwekitamu .
PFX FE 0 gwekitaba .
PFX FE 0 gwekitagu .
PFX FE 0 gwekitagi .
PFX FE 0 gwekitazi .
PFX FE 0 gwekitaki .
PFX FE 0 gwekitabi .
PFX FE 0 gwekitali .
PFX FE 0 gwekitaga .
PFX FE 0 gwekitaka .
PFX FE 0 gwekitabu .
PFX FE 0 gwekitalu .
PFX FE 0 gwekitaku .
PFX FE 0 gwekitatu .
PFX FE 0 gwebitan [^lmnb]
PFX FE l gwebitand l.[^mn]
PFX FE l gwebitann l.[mn]
PFX FE w gwebitamp [w]
PFX FE 0 gwebitamu .
PFX FE 0 gwebitaba .
PFX FE 0 gwebitagu .
PFX FE 0 gwebitagi .
PFX FE 0 gwebitazi .
PFX FE 0 gwebitaki .
PFX FE 0 gwebitabi .
PFX FE 0 gwebitali .
PFX FE 0 gwebitaga .
PFX FE 0 gwebitaka .
PFX FE 0 gwebitabu .
PFX FE 0 gwebitalu .
PFX FE 0 gwebitaku .
PFX FE 0 gwebitatu .
PFX FE 0 gwelitan [^lmnb]
PFX FE l gwelitand l.[^mn]
PFX FE l gwelitann l.[mn]
PFX FE w gwelitamp [w]
PFX FE 0 gwelitamu .
PFX FE 0 gwelitaba .
PFX FE 0 gwelitagu .
PFX FE 0 gwelitagi .
PFX FE 0 gwelitazi .
PFX FE 0 gwelitaki .
PFX FE 0 gwelitabi .
PFX FE 0 gwelitali .
PFX FE 0 gwelitaga .
PFX FE 0 gwelitaka .
PFX FE 0 gwelitabu .
PFX FE 0 gwelitalu .
PFX FE 0 gwelitaku .
PFX FE 0 gwelitatu .
PFX FE 0 gwegatan [^lmnb]
PFX FE l gwegatand l.[^mn]
PFX FE l gwegatann l.[mn]
PFX FE w gwegatamp [w]
PFX FE 0 gwegatamu .
PFX FE 0 gwegataba .
PFX FE 0 gwegatagu .
PFX FE 0 gwegatagi .
PFX FE 0 gwegatazi .
PFX FE 0 gwegataki .
PFX FE 0 gwegatabi .
PFX FE 0 gwegatali .
PFX FE 0 gwegataga .
PFX FE 0 gwegataka .
PFX FE 0 gwegatabu .
PFX FE 0 gwegatalu .
PFX FE 0 gwegataku .
PFX FE 0 gwegatatu .
PFX FE 0 gwekatan [^lmnb]
PFX FE l gwekatand l.[^mn]
PFX FE l gwekatann l.[mn]
PFX FE w gwekatamp [w]
PFX FE 0 gwekatamu .
PFX FE 0 gwekataba .
PFX FE 0 gwekatagu .
PFX FE 0 gwekatagi .
PFX FE 0 gwekatazi .
PFX FE 0 gwekataki .
PFX FE 0 gwekatabi .
PFX FE 0 gwekatali .
PFX FE 0 gwekataga .
PFX FE 0 gwekataka .
PFX FE 0 gwekatabu .
PFX FE 0 gwekatalu .
PFX FE 0 gwekataku .
PFX FE 0 gwekatatu .
PFX FE 0 gwebutan [^lmnb]
PFX FE l gwebutand l.[^mn]
PFX FE l gwebutann l.[mn]
PFX FE w gwebutamp [w]
PFX FE 0 gwebutamu .
PFX FE 0 gwebutaba .
PFX FE 0 gwebutagu .
PFX FE 0 gwebutagi .
PFX FE 0 gwebutazi .
PFX FE 0 gwebutaki .
PFX FE 0 gwebutabi .
PFX FE 0 gwebutali .
PFX FE 0 gwebutaga .
PFX FE 0 gwebutaka .
PFX FE 0 gwebutabu .
PFX FE 0 gwebutalu .
PFX FE 0 gwebutaku .
PFX FE 0 gwebutatu .
PFX FE 0 gwelutan [^lmnb]
PFX FE l gwelutand l.[^mn]
PFX FE l gwelutann l.[mn]
PFX FE w gwelutamp [w]
PFX FE 0 gwelutamu .
PFX FE 0 gwelutaba .
PFX FE 0 gwelutagu .
PFX FE 0 gwelutagi .
PFX FE 0 gwelutazi .
PFX FE 0 gwelutaki .
PFX FE 0 gwelutabi .
PFX FE 0 gwelutali .
PFX FE 0 gwelutaga .
PFX FE 0 gwelutaka .
PFX FE 0 gwelutabu .
PFX FE 0 gwelutalu .
PFX FE 0 gwelutaku .
PFX FE 0 gwelutatu .
PFX FE 0 gwekutan [^lmnb]
PFX FE l gwekutand l.[^mn]
PFX FE l gwekutann l.[mn]
PFX FE w gwekutamp [w]
PFX FE 0 gwekutamu .
PFX FE 0 gwekutaba .
PFX FE 0 gwekutagu .
PFX FE 0 gwekutagi .
PFX FE 0 gwekutazi .
PFX FE 0 gwekutaki .
PFX FE 0 gwekutabi .
PFX FE 0 gwekutali .
PFX FE 0 gwekutaga .
PFX FE 0 gwekutaka .
PFX FE 0 gwekutabu .
PFX FE 0 gwekutalu .
PFX FE 0 gwekutaku .
PFX FE 0 gwekutatu .
PFX FE 0 gwetutan [^lmnb]
PFX FE l gwetutand l.[^mn]
PFX FE l gwetutann l.[mn]
PFX FE w gwetutamp [w]
PFX FE 0 gwetutamu .
PFX FE 0 gwetutaba .
PFX FE 0 gwetutagu .
PFX FE 0 gwetutagi .
PFX FE 0 gwetutazi .
PFX FE 0 gwetutaki .
PFX FE 0 gwetutabi .
PFX FE 0 gwetutali .
PFX FE 0 gwetutaga .
PFX FE 0 gwetutaka .
PFX FE 0 gwetutabu .
PFX FE 0 gwetutalu .
PFX FE 0 gwetutaku .
PFX FE 0 gwetutatu .
PFX FE 0 gyessiba .
PFX FE 0 gyessigu .
PFX FE 0 gyessigi .
PFX FE 0 gyessizi .
PFX FE 0 gyessiki .
PFX FE 0 gyessibi .
PFX FE 0 gyessili .
PFX FE 0 gyessiga .
PFX FE 0 gyessika .
PFX FE 0 gyessibu .
PFX FE 0 gyessilu .
PFX FE 0 gyessiku .
PFX FE 0 gyessitu .
PFX FE 0 gyessimu .
PFX FE 0 gyetutan [^lmnb]
PFX FE l gyetutand l.[^mn]
PFX FE l gyetutann l.[mn]
PFX FE w gyetutamp [w]
PFX FE 0 gyetutamu .
PFX FE 0 gyetutaba .
PFX FE 0 gyetutagu .
PFX FE 0 gyetutagi .
PFX FE 0 gyetutazi .
PFX FE 0 gyetutaki .
PFX FE 0 gyetutabi .
PFX FE 0 gyetutali .
PFX FE 0 gyetutaga .
PFX FE 0 gyetutaka .
PFX FE 0 gyetutabu .
PFX FE 0 gyetutalu .
PFX FE 0 gyetutaku .
PFX FE 0 gyetutatu .
PFX FE 0 gyemutan [^lmnb]
PFX FE l gyemutand l.[^mn]
PFX FE l gyemutann l.[mn]
PFX FE w gyemutamp [w]
PFX FE 0 gyemutamu .
PFX FE 0 gyemutaba .
PFX FE 0 gyemutagu .
PFX FE 0 gyemutagi .
PFX FE 0 gyemutazi .
PFX FE 0 gyemutaki .
PFX FE 0 gyemutabi .
PFX FE 0 gyemutali .
PFX FE 0 gyemutaga .
PFX FE 0 gyemutaka .
PFX FE 0 gyemutabu .
PFX FE 0 gyemutalu .
PFX FE 0 gyemutaku .
PFX FE 0 gyemutatu .
PFX FE 0 gyebatan [^lmnb]
PFX FE l gyebatand l.[^mn]
PFX FE l gyebatann l.[mn]
PFX FE w gyebatamp [w]
PFX FE 0 gyebatamu .
PFX FE 0 gyebataba .
PFX FE 0 gyebatagu .
PFX FE 0 gyebatagi .
PFX FE 0 gyebatazi .
PFX FE 0 gyebataki .
PFX FE 0 gyebatabi .
PFX FE 0 gyebatali .
PFX FE 0 gyebataga .
PFX FE 0 gyebataka .
PFX FE 0 gyebatabu .
PFX FE 0 gyebatalu .
PFX FE 0 gyebataku .
PFX FE 0 gyebatatu .
PFX FE 0 gyegutan [^lmnb]
PFX FE l gyegutand l.[^mn]
PFX FE l gyegutann l.[mn]
PFX FE w gyegutamp [w]
PFX FE 0 gyegutamu .
PFX FE 0 gyegutaba .
PFX FE 0 gyegutagu .
PFX FE 0 gyegutagi .
PFX FE 0 gyegutazi .
PFX FE 0 gyegutaki .
PFX FE 0 gyegutabi .
PFX FE 0 gyegutali .
PFX FE 0 gyegutaga .
PFX FE 0 gyegutaka .
PFX FE 0 gyegutabu .
PFX FE 0 gyegutalu .
PFX FE 0 gyegutaku .
PFX FE 0 gyegutatu .
PFX FE 0 gyegitan [^lmnb]
PFX FE l gyegitand l.[^mn]
PFX FE l gyegitann l.[mn]
PFX FE w gyegitamp [w]
PFX FE 0 gyegitamu .
PFX FE 0 gyegitaba .
PFX FE 0 gyegitagu .
PFX FE 0 gyegitagi .
PFX FE 0 gyegitazi .
PFX FE 0 gyegitaki .
PFX FE 0 gyegitabi .
PFX FE 0 gyegitali .
PFX FE 0 gyegitaga .
PFX FE 0 gyegitaka .
PFX FE 0 gyegitabu .
PFX FE 0 gyegitalu .
PFX FE 0 gyegitaku .
PFX FE 0 gyegitatu .
PFX FE 0 gyezitan [^lmnb]
PFX FE l gyezitand l.[^mn]
PFX FE l gyezitann l.[mn]
PFX FE w gyezitamp [w]
PFX FE 0 gyezitamu .
PFX FE 0 gyezitaba .
PFX FE 0 gyezitagu .
PFX FE 0 gyezitagi .
PFX FE 0 gyezitazi .
PFX FE 0 gyezitaki .
PFX FE 0 gyezitabi .
PFX FE 0 gyezitali .
PFX FE 0 gyezitaga .
PFX FE 0 gyezitaka .
PFX FE 0 gyezitabu .
PFX FE 0 gyezitalu .
PFX FE 0 gyezitaku .
PFX FE 0 gyezitatu .
PFX FE 0 gyekitan [^lmnb]
PFX FE l gyekitand l.[^mn]
PFX FE l gyekitann l.[mn]
PFX FE w gyekitamp [w]
PFX FE 0 gyekitamu .
PFX FE 0 gyekitaba .
PFX FE 0 gyekitagu .
PFX FE 0 gyekitagi .
PFX FE 0 gyekitazi .
PFX FE 0 gyekitaki .
PFX FE 0 gyekitabi .
PFX FE 0 gyekitali .
PFX FE 0 gyekitaga .
PFX FE 0 gyekitaka .
PFX FE 0 gyekitabu .
PFX FE 0 gyekitalu .
PFX FE 0 gyekitaku .
PFX FE 0 gyekitatu .
PFX FE 0 gyebitan [^lmnb]
PFX FE l gyebitand l.[^mn]
PFX FE l gyebitann l.[mn]
PFX FE w gyebitamp [w]
PFX FE 0 gyebitamu .
PFX FE 0 gyebitaba .
PFX FE 0 gyebitagu .
PFX FE 0 gyebitagi .
PFX FE 0 gyebitazi .
PFX FE 0 gyebitaki .
PFX FE 0 gyebitabi .
PFX FE 0 gyebitali .
PFX FE 0 gyebitaga .
PFX FE 0 gyebitaka .
PFX FE 0 gyebitabu .
PFX FE 0 gyebitalu .
PFX FE 0 gyebitaku .
PFX FE 0 gyebitatu .
PFX FE 0 gyelitan [^lmnb]
PFX FE l gyelitand l.[^mn]
PFX FE l gyelitann l.[mn]
PFX FE w gyelitamp [w]
PFX FE 0 gyelitamu .
PFX FE 0 gyelitaba .
PFX FE 0 gyelitagu .
PFX FE 0 gyelitagi .
PFX FE 0 gyelitazi .
PFX FE 0 gyelitaki .
PFX FE 0 gyelitabi .
PFX FE 0 gyelitali .
PFX FE 0 gyelitaga .
PFX FE 0 gyelitaka .
PFX FE 0 gyelitabu .
PFX FE 0 gyelitalu .
PFX FE 0 gyelitaku .
PFX FE 0 gyelitatu .
PFX FE 0 gyegatan [^lmnb]
PFX FE l gyegatand l.[^mn]
PFX FE l gyegatann l.[mn]
PFX FE w gyegatamp [w]
PFX FE 0 gyegatamu .
PFX FE 0 gyegataba .
PFX FE 0 gyegatagu .
PFX FE 0 gyegatagi .
PFX FE 0 gyegatazi .
PFX FE 0 gyegataki .
PFX FE 0 gyegatabi .
PFX FE 0 gyegatali .
PFX FE 0 gyegataga .
PFX FE 0 gyegataka .
PFX FE 0 gyegatabu .
PFX FE 0 gyegatalu .
PFX FE 0 gyegataku .
PFX FE 0 gyegatatu .
PFX FE 0 gyekatan [^lmnb]
PFX FE l gyekatand l.[^mn]
PFX FE l gyekatann l.[mn]
PFX FE w gyekatamp [w]
PFX FE 0 gyekatamu .
PFX FE 0 gyekataba .
PFX FE 0 gyekatagu .
PFX FE 0 gyekatagi .
PFX FE 0 gyekatazi .
PFX FE 0 gyekataki .
PFX FE 0 gyekatabi .
PFX FE 0 gyekatali .
PFX FE 0 gyekataga .
PFX FE 0 gyekataka .
PFX FE 0 gyekatabu .
PFX FE 0 gyekatalu .
PFX FE 0 gyekataku .
PFX FE 0 gyekatatu .
PFX FE 0 gyebutan [^lmnb]
PFX FE l gyebutand l.[^mn]
PFX FE l gyebutann l.[mn]
PFX FE w gyebutamp [w]
PFX FE 0 gyebutamu .
PFX FE 0 gyebutaba .
PFX FE 0 gyebutagu .
PFX FE 0 gyebutagi .
PFX FE 0 gyebutazi .
PFX FE 0 gyebutaki .
PFX FE 0 gyebutabi .
PFX FE 0 gyebutali .
PFX FE 0 gyebutaga .
PFX FE 0 gyebutaka .
PFX FE 0 gyebutabu .
PFX FE 0 gyebutalu .
PFX FE 0 gyebutaku .
PFX FE 0 gyebutatu .
PFX FE 0 gyelutan [^lmnb]
PFX FE l gyelutand l.[^mn]
PFX FE l gyelutann l.[mn]
PFX FE w gyelutamp [w]
PFX FE 0 gyelutamu .
PFX FE 0 gyelutaba .
PFX FE 0 gyelutagu .
PFX FE 0 gyelutagi .
PFX FE 0 gyelutazi .
PFX FE 0 gyelutaki .
PFX FE 0 gyelutabi .
PFX FE 0 gyelutali .
PFX FE 0 gyelutaga .
PFX FE 0 gyelutaka .
PFX FE 0 gyelutabu .
PFX FE 0 gyelutalu .
PFX FE 0 gyelutaku .
PFX FE 0 gyelutatu .
PFX FE 0 gyekutan [^lmnb]
PFX FE l gyekutand l.[^mn]
PFX FE l gyekutann l.[mn]
PFX FE w gyekutamp [w]
PFX FE 0 gyekutamu .
PFX FE 0 gyekutaba .
PFX FE 0 gyekutagu .
PFX FE 0 gyekutagi .
PFX FE 0 gyekutazi .
PFX FE 0 gyekutaki .
PFX FE 0 gyekutabi .
PFX FE 0 gyekutali .
PFX FE 0 gyekutaga .
PFX FE 0 gyekutaka .
PFX FE 0 gyekutabu .
PFX FE 0 gyekutalu .
PFX FE 0 gyekutaku .
PFX FE 0 gyekutatu .
PFX FE 0 gyetutan [^lmnb]
PFX FE l gyetutand l.[^mn]
PFX FE l gyetutann l.[mn]
PFX FE w gyetutamp [w]
PFX FE 0 gyetutamu .
PFX FE 0 gyetutaba .
PFX FE 0 gyetutagu .
PFX FE 0 gyetutagi .
PFX FE 0 gyetutazi .
PFX FE 0 gyetutaki .
PFX FE 0 gyetutabi .
PFX FE 0 gyetutali .
PFX FE 0 gyetutaga .
PFX FE 0 gyetutaka .
PFX FE 0 gyetutabu .
PFX FE 0 gyetutalu .
PFX FE 0 gyetutaku .
PFX FE 0 gyetutatu .
PFX FE 0 kyessiba .
PFX FE 0 kyessigu .
PFX FE 0 kyessigi .
PFX FE 0 kyessizi .
PFX FE 0 kyessiki .
PFX FE 0 kyessibi .
PFX FE 0 kyessili .
PFX FE 0 kyessiga .
PFX FE 0 kyessika .
PFX FE 0 kyessibu .
PFX FE 0 kyessilu .
PFX FE 0 kyessiku .
PFX FE 0 kyessitu .
PFX FE 0 kyessimu .
PFX FE 0 kyetutan [^lmnb]
PFX FE l kyetutand l.[^mn]
PFX FE l kyetutann l.[mn]
PFX FE w kyetutamp [w]
PFX FE 0 kyetutamu .
PFX FE 0 kyetutaba .
PFX FE 0 kyetutagu .
PFX FE 0 kyetutagi .
PFX FE 0 kyetutazi .
PFX FE 0 kyetutaki .
PFX FE 0 kyetutabi .
PFX FE 0 kyetutali .
PFX FE 0 kyetutaga .
PFX FE 0 kyetutaka .
PFX FE 0 kyetutabu .
PFX FE 0 kyetutalu .
PFX FE 0 kyetutaku .
PFX FE 0 kyetutatu .
PFX FE 0 kyemutan [^lmnb]
PFX FE l kyemutand l.[^mn]
PFX FE l kyemutann l.[mn]
PFX FE w kyemutamp [w]
PFX FE 0 kyemutamu .
PFX FE 0 kyemutaba .
PFX FE 0 kyemutagu .
PFX FE 0 kyemutagi .
PFX FE 0 kyemutazi .
PFX FE 0 kyemutaki .
PFX FE 0 kyemutabi .
PFX FE 0 kyemutali .
PFX FE 0 kyemutaga .
PFX FE 0 kyemutaka .
PFX FE 0 kyemutabu .
PFX FE 0 kyemutalu .
PFX FE 0 kyemutaku .
PFX FE 0 kyemutatu .
PFX FE 0 kyebatan [^lmnb]
PFX FE l kyebatand l.[^mn]
PFX FE l kyebatann l.[mn]
PFX FE w kyebatamp [w]
PFX FE 0 kyebatamu .
PFX FE 0 kyebataba .
PFX FE 0 kyebatagu .
PFX FE 0 kyebatagi .
PFX FE 0 kyebatazi .
PFX FE 0 kyebataki .
PFX FE 0 kyebatabi .
PFX FE 0 kyebatali .
PFX FE 0 kyebataga .
PFX FE 0 kyebataka .
PFX FE 0 kyebatabu .
PFX FE 0 kyebatalu .
PFX FE 0 kyebataku .
PFX FE 0 kyebatatu .
PFX FE 0 kyegutan [^lmnb]
PFX FE l kyegutand l.[^mn]
PFX FE l kyegutann l.[mn]
PFX FE w kyegutamp [w]
PFX FE 0 kyegutamu .
PFX FE 0 kyegutaba .
PFX FE 0 kyegutagu .
PFX FE 0 kyegutagi .
PFX FE 0 kyegutazi .
PFX FE 0 kyegutaki .
PFX FE 0 kyegutabi .
PFX FE 0 kyegutali .
PFX FE 0 kyegutaga .
PFX FE 0 kyegutaka .
PFX FE 0 kyegutabu .
PFX FE 0 kyegutalu .
PFX FE 0 kyegutaku .
PFX FE 0 kyegutatu .
PFX FE 0 kyegitan [^lmnb]
PFX FE l kyegitand l.[^mn]
PFX FE l kyegitann l.[mn]
PFX FE w kyegitamp [w]
PFX FE 0 kyegitamu .
PFX FE 0 kyegitaba .
PFX FE 0 kyegitagu .
PFX FE 0 kyegitagi .
PFX FE 0 kyegitazi .
PFX FE 0 kyegitaki .
PFX FE 0 kyegitabi .
PFX FE 0 kyegitali .
PFX FE 0 kyegitaga .
PFX FE 0 kyegitaka .
PFX FE 0 kyegitabu .
PFX FE 0 kyegitalu .
PFX FE 0 kyegitaku .
PFX FE 0 kyegitatu .
PFX FE 0 kyezitan [^lmnb]
PFX FE l kyezitand l.[^mn]
PFX FE l kyezitann l.[mn]
PFX FE w kyezitamp [w]
PFX FE 0 kyezitamu .
PFX FE 0 kyezitaba .
PFX FE 0 kyezitagu .
PFX FE 0 kyezitagi .
PFX FE 0 kyezitazi .
PFX FE 0 kyezitaki .
PFX FE 0 kyezitabi .
PFX FE 0 kyezitali .
PFX FE 0 kyezitaga .
PFX FE 0 kyezitaka .
PFX FE 0 kyezitabu .
PFX FE 0 kyezitalu .
PFX FE 0 kyezitaku .
PFX FE 0 kyezitatu .
PFX FE 0 kyekitan [^lmnb]
PFX FE l kyekitand l.[^mn]
PFX FE l kyekitann l.[mn]
PFX FE w kyekitamp [w]
PFX FE 0 kyekitamu .
PFX FE 0 kyekitaba .
PFX FE 0 kyekitagu .
PFX FE 0 kyekitagi .
PFX FE 0 kyekitazi .
PFX FE 0 kyekitaki .
PFX FE 0 kyekitabi .
PFX FE 0 kyekitali .
PFX FE 0 kyekitaga .
PFX FE 0 kyekitaka .
PFX FE 0 kyekitabu .
PFX FE 0 kyekitalu .
PFX FE 0 kyekitaku .
PFX FE 0 kyekitatu .
PFX FE 0 kyebitan [^lmnb]
PFX FE l kyebitand l.[^mn]
PFX FE l kyebitann l.[mn]
PFX FE w kyebitamp [w]
PFX FE 0 kyebitamu .
PFX FE 0 kyebitaba .
PFX FE 0 kyebitagu .
PFX FE 0 kyebitagi .
PFX FE 0 kyebitazi .
PFX FE 0 kyebitaki .
PFX FE 0 kyebitabi .
PFX FE 0 kyebitali .
PFX FE 0 kyebitaga .
PFX FE 0 kyebitaka .
PFX FE 0 kyebitabu .
PFX FE 0 kyebitalu .
PFX FE 0 kyebitaku .
PFX FE 0 kyebitatu .
PFX FE 0 kyelitan [^lmnb]
PFX FE l kyelitand l.[^mn]
PFX FE l kyelitann l.[mn]
PFX FE w kyelitamp [w]
PFX FE 0 kyelitamu .
PFX FE 0 kyelitaba .
PFX FE 0 kyelitagu .
PFX FE 0 kyelitagi .
PFX FE 0 kyelitazi .
PFX FE 0 kyelitaki .
PFX FE 0 kyelitabi .
PFX FE 0 kyelitali .
PFX FE 0 kyelitaga .
PFX FE 0 kyelitaka .
PFX FE 0 kyelitabu .
PFX FE 0 kyelitalu .
PFX FE 0 kyelitaku .
PFX FE 0 kyelitatu .
PFX FE 0 kyegatan [^lmnb]
PFX FE l kyegatand l.[^mn]
PFX FE l kyegatann l.[mn]
PFX FE w kyegatamp [w]
PFX FE 0 kyegatamu .
PFX FE 0 kyegataba .
PFX FE 0 kyegatagu .
PFX FE 0 kyegatagi .
PFX FE 0 kyegatazi .
PFX FE 0 kyegataki .
PFX FE 0 kyegatabi .
PFX FE 0 kyegatali .
PFX FE 0 kyegataga .
PFX FE 0 kyegataka .
PFX FE 0 kyegatabu .
PFX FE 0 kyegatalu .
PFX FE 0 kyegataku .
PFX FE 0 kyegatatu .
PFX FE 0 kyekatan [^lmnb]
PFX FE l kyekatand l.[^mn]
PFX FE l kyekatann l.[mn]
PFX FE w kyekatamp [w]
PFX FE 0 kyekatamu .
PFX FE 0 kyekataba .
PFX FE 0 kyekatagu .
PFX FE 0 kyekatagi .
PFX FE 0 kyekatazi .
PFX FE 0 kyekataki .
PFX FE 0 kyekatabi .
PFX FE 0 kyekatali .
PFX FE 0 kyekataga .
PFX FE 0 kyekataka .
PFX FE 0 kyekatabu .
PFX FE 0 kyekatalu .
PFX FE 0 kyekataku .
PFX FE 0 kyekatatu .
PFX FE 0 kyebutan [^lmnb]
PFX FE l kyebutand l.[^mn]
PFX FE l kyebutann l.[mn]
PFX FE w kyebutamp [w]
PFX FE 0 kyebutamu .
PFX FE 0 kyebutaba .
PFX FE 0 kyebutagu .
PFX FE 0 kyebutagi .
PFX FE 0 kyebutazi .
PFX FE 0 kyebutaki .
PFX FE 0 kyebutabi .
PFX FE 0 kyebutali .
PFX FE 0 kyebutaga .
PFX FE 0 kyebutaka .
PFX FE 0 kyebutabu .
PFX FE 0 kyebutalu .
PFX FE 0 kyebutaku .
PFX FE 0 kyebutatu .
PFX FE 0 kyelutan [^lmnb]
PFX FE l kyelutand l.[^mn]
PFX FE l kyelutann l.[mn]
PFX FE w kyelutamp [w]
PFX FE 0 kyelutamu .
PFX FE 0 kyelutaba .
PFX FE 0 kyelutagu .
PFX FE 0 kyelutagi .
PFX FE 0 kyelutazi .
PFX FE 0 kyelutaki .
PFX FE 0 kyelutabi .
PFX FE 0 kyelutali .
PFX FE 0 kyelutaga .
PFX FE 0 kyelutaka .
PFX FE 0 kyelutabu .
PFX FE 0 kyelutalu .
PFX FE 0 kyelutaku .
PFX FE 0 kyelutatu .
PFX FE 0 kyekutan [^lmnb]
PFX FE l kyekutand l.[^mn]
PFX FE l kyekutann l.[mn]
PFX FE w kyekutamp [w]
PFX FE 0 kyekutamu .
PFX FE 0 kyekutaba .
PFX FE 0 kyekutagu .
PFX FE 0 kyekutagi .
PFX FE 0 kyekutazi .
PFX FE 0 kyekutaki .
PFX FE 0 kyekutabi .
PFX FE 0 kyekutali .
PFX FE 0 kyekutaga .
PFX FE 0 kyekutaka .
PFX FE 0 kyekutabu .
PFX FE 0 kyekutalu .
PFX FE 0 kyekutaku .
PFX FE 0 kyekutatu .
PFX FE 0 kyetutan [^lmnb]
PFX FE l kyetutand l.[^mn]
PFX FE l kyetutann l.[mn]
PFX FE w kyetutamp [w]
PFX FE 0 kyetutamu .
PFX FE 0 kyetutaba .
PFX FE 0 kyetutagu .
PFX FE 0 kyetutagi .
PFX FE 0 kyetutazi .
PFX FE 0 kyetutaki .
PFX FE 0 kyetutabi .
PFX FE 0 kyetutali .
PFX FE 0 kyetutaga .
PFX FE 0 kyetutaka .
PFX FE 0 kyetutabu .
PFX FE 0 kyetutalu .
PFX FE 0 kyetutaku .
PFX FE 0 kyetutatu .
PFX FE 0 byessiba .
PFX FE 0 byessigu .
PFX FE 0 byessigi .
PFX FE 0 byessizi .
PFX FE 0 byessiki .
PFX FE 0 byessibi .
PFX FE 0 byessili .
PFX FE 0 byessiga .
PFX FE 0 byessika .
PFX FE 0 byessibu .
PFX FE 0 byessilu .
PFX FE 0 byessiku .
PFX FE 0 byessitu .
PFX FE 0 byessimu .
PFX FE 0 byetutan [^lmnb]
PFX FE l byetutand l.[^mn]
PFX FE l byetutann l.[mn]
PFX FE w byetutamp [w]
PFX FE 0 byetutamu .
PFX FE 0 byetutaba .
PFX FE 0 byetutagu .
PFX FE 0 byetutagi .
PFX FE 0 byetutazi .
PFX FE 0 byetutaki .
PFX FE 0 byetutabi .
PFX FE 0 byetutali .
PFX FE 0 byetutaga .
PFX FE 0 byetutaka .
PFX FE 0 byetutabu .
PFX FE 0 byetutalu .
PFX FE 0 byetutaku .
PFX FE 0 byetutatu .
PFX FE 0 byemutan [^lmnb]
PFX FE l byemutand l.[^mn]
PFX FE l byemutann l.[mn]
PFX FE w byemutamp [w]
PFX FE 0 byemutamu .
PFX FE 0 byemutaba .
PFX FE 0 byemutagu .
PFX FE 0 byemutagi .
PFX FE 0 byemutazi .
PFX FE 0 byemutaki .
PFX FE 0 byemutabi .
PFX FE 0 byemutali .
PFX FE 0 byemutaga .
PFX FE 0 byemutaka .
PFX FE 0 byemutabu .
PFX FE 0 byemutalu .
PFX FE 0 byemutaku .
PFX FE 0 byemutatu .
PFX FE 0 byebatan [^lmnb]
PFX FE l byebatand l.[^mn]
PFX FE l byebatann l.[mn]
PFX FE w byebatamp [w]
PFX FE 0 byebatamu .
PFX FE 0 byebataba .
PFX FE 0 byebatagu .
PFX FE 0 byebatagi .
PFX FE 0 byebatazi .
PFX FE 0 byebataki .
PFX FE 0 byebatabi .
PFX FE 0 byebatali .
PFX FE 0 byebataga .
PFX FE 0 byebataka .
PFX FE 0 byebatabu .
PFX FE 0 byebatalu .
PFX FE 0 byebataku .
PFX FE 0 byebatatu .
PFX FE 0 byegutan [^lmnb]
PFX FE l byegutand l.[^mn]
PFX FE l byegutann l.[mn]
PFX FE w byegutamp [w]
PFX FE 0 byegutamu .
PFX FE 0 byegutaba .
PFX FE 0 byegutagu .
PFX FE 0 byegutagi .
PFX FE 0 byegutazi .
PFX FE 0 byegutaki .
PFX FE 0 byegutabi .
PFX FE 0 byegutali .
PFX FE 0 byegutaga .
PFX FE 0 byegutaka .
PFX FE 0 byegutabu .
PFX FE 0 byegutalu .
PFX FE 0 byegutaku .
PFX FE 0 byegutatu .
PFX FE 0 byegitan [^lmnb]
PFX FE l byegitand l.[^mn]
PFX FE l byegitann l.[mn]
PFX FE w byegitamp [w]
PFX FE 0 byegitamu .
PFX FE 0 byegitaba .
PFX FE 0 byegitagu .
PFX FE 0 byegitagi .
PFX FE 0 byegitazi .
PFX FE 0 byegitaki .
PFX FE 0 byegitabi .
PFX FE 0 byegitali .
PFX FE 0 byegitaga .
PFX FE 0 byegitaka .
PFX FE 0 byegitabu .
PFX FE 0 byegitalu .
PFX FE 0 byegitaku .
PFX FE 0 byegitatu .
PFX FE 0 byezitan [^lmnb]
PFX FE l byezitand l.[^mn]
PFX FE l byezitann l.[mn]
PFX FE w byezitamp [w]
PFX FE 0 byezitamu .
PFX FE 0 byezitaba .
PFX FE 0 byezitagu .
PFX FE 0 byezitagi .
PFX FE 0 byezitazi .
PFX FE 0 byezitaki .
PFX FE 0 byezitabi .
PFX FE 0 byezitali .
PFX FE 0 byezitaga .
PFX FE 0 byezitaka .
PFX FE 0 byezitabu .
PFX FE 0 byezitalu .
PFX FE 0 byezitaku .
PFX FE 0 byezitatu .
PFX FE 0 byekitan [^lmnb]
PFX FE l byekitand l.[^mn]
PFX FE l byekitann l.[mn]
PFX FE w byekitamp [w]
PFX FE 0 byekitamu .
PFX FE 0 byekitaba .
PFX FE 0 byekitagu .
PFX FE 0 byekitagi .
PFX FE 0 byekitazi .
PFX FE 0 byekitaki .
PFX FE 0 byekitabi .
PFX FE 0 byekitali .
PFX FE 0 byekitaga .
PFX FE 0 byekitaka .
PFX FE 0 byekitabu .
PFX FE 0 byekitalu .
PFX FE 0 byekitaku .
PFX FE 0 byekitatu .
PFX FE 0 byebitan [^lmnb]
PFX FE l byebitand l.[^mn]
PFX FE l byebitann l.[mn]
PFX FE w byebitamp [w]
PFX FE 0 byebitamu .
PFX FE 0 byebitaba .
PFX FE 0 byebitagu .
PFX FE 0 byebitagi .
PFX FE 0 byebitazi .
PFX FE 0 byebitaki .
PFX FE 0 byebitabi .
PFX FE 0 byebitali .
PFX FE 0 byebitaga .
PFX FE 0 byebitaka .
PFX FE 0 byebitabu .
PFX FE 0 byebitalu .
PFX FE 0 byebitaku .
PFX FE 0 byebitatu .
PFX FE 0 byelitan [^lmnb]
PFX FE l byelitand l.[^mn]
PFX FE l byelitann l.[mn]
PFX FE w byelitamp [w]
PFX FE 0 byelitamu .
PFX FE 0 byelitaba .
PFX FE 0 byelitagu .
PFX FE 0 byelitagi .
PFX FE 0 byelitazi .
PFX FE 0 byelitaki .
PFX FE 0 byelitabi .
PFX FE 0 byelitali .
PFX FE 0 byelitaga .
PFX FE 0 byelitaka .
PFX FE 0 byelitabu .
PFX FE 0 byelitalu .
PFX FE 0 byelitaku .
PFX FE 0 byelitatu .
PFX FE 0 byegatan [^lmnb]
PFX FE l byegatand l.[^mn]
PFX FE l byegatann l.[mn]
PFX FE w byegatamp [w]
PFX FE 0 byegatamu .
PFX FE 0 byegataba .
PFX FE 0 byegatagu .
PFX FE 0 byegatagi .
PFX FE 0 byegatazi .
PFX FE 0 byegataki .
PFX FE 0 byegatabi .
PFX FE 0 byegatali .
PFX FE 0 byegataga .
PFX FE 0 byegataka .
PFX FE 0 byegatabu .
PFX FE 0 byegatalu .
PFX FE 0 byegataku .
PFX FE 0 byegatatu .
PFX FE 0 byekatan [^lmnb]
PFX FE l byekatand l.[^mn]
PFX FE l byekatann l.[mn]
PFX FE w byekatamp [w]
PFX FE 0 byekatamu .
PFX FE 0 byekataba .
PFX FE 0 byekatagu .
PFX FE 0 byekatagi .
PFX FE 0 byekatazi .
PFX FE 0 byekataki .
PFX FE 0 byekatabi .
PFX FE 0 byekatali .
PFX FE 0 byekataga .
PFX FE 0 byekataka .
PFX FE 0 byekatabu .
PFX FE 0 byekatalu .
PFX FE 0 byekataku .
PFX FE 0 byekatatu .
PFX FE 0 byebutan [^lmnb]
PFX FE l byebutand l.[^mn]
PFX FE l byebutann l.[mn]
PFX FE w byebutamp [w]
PFX FE 0 byebutamu .
PFX FE 0 byebutaba .
PFX FE 0 byebutagu .
PFX FE 0 byebutagi .
PFX FE 0 byebutazi .
PFX FE 0 byebutaki .
PFX FE 0 byebutabi .
PFX FE 0 byebutali .
PFX FE 0 byebutaga .
PFX FE 0 byebutaka .
PFX FE 0 byebutabu .
PFX FE 0 byebutalu .
PFX FE 0 byebutaku .
PFX FE 0 byebutatu .
PFX FE 0 byelutan [^lmnb]
PFX FE l byelutand l.[^mn]
PFX FE l byelutann l.[mn]
PFX FE w byelutamp [w]
PFX FE 0 byelutamu .
PFX FE 0 byelutaba .
PFX FE 0 byelutagu .
PFX FE 0 byelutagi .
PFX FE 0 byelutazi .
PFX FE 0 byelutaki .
PFX FE 0 byelutabi .
PFX FE 0 byelutali .
PFX FE 0 byelutaga .
PFX FE 0 byelutaka .
PFX FE 0 byelutabu .
PFX FE 0 byelutalu .
PFX FE 0 byelutaku .
PFX FE 0 byelutatu .
PFX FE 0 byekutan [^lmnb]
PFX FE l byekutand l.[^mn]
PFX FE l byekutann l.[mn]
PFX FE w byekutamp [w]
PFX FE 0 byekutamu .
PFX FE 0 byekutaba .
PFX FE 0 byekutagu .
PFX FE 0 byekutagi .
PFX FE 0 byekutazi .
PFX FE 0 byekutaki .
PFX FE 0 byekutabi .
PFX FE 0 byekutali .
PFX FE 0 byekutaga .
PFX FE 0 byekutaka .
PFX FE 0 byekutabu .
PFX FE 0 byekutalu .
PFX FE 0 byekutaku .
PFX FE 0 byekutatu .
PFX FE 0 byetutan [^lmnb]
PFX FE l byetutand l.[^mn]
PFX FE l byetutann l.[mn]
PFX FE w byetutamp [w]
PFX FE 0 byetutamu .
PFX FE 0 byetutaba .
PFX FE 0 byetutagu .
PFX FE 0 byetutagi .
PFX FE 0 byetutazi .
PFX FE 0 byetutaki .
PFX FE 0 byetutabi .
PFX FE 0 byetutali .
PFX FE 0 byetutaga .
PFX FE 0 byetutaka .
PFX FE 0 byetutabu .
PFX FE 0 byetutalu .
PFX FE 0 byetutaku .
PFX FE 0 byetutatu .
PFX FE 0 lyessiba .
PFX FE 0 lyessigu .
PFX FE 0 lyessigi .
PFX FE 0 lyessizi .
PFX FE 0 lyessiki .
PFX FE 0 lyessibi .
PFX FE 0 lyessili .
PFX FE 0 lyessiga .
PFX FE 0 lyessika .
PFX FE 0 lyessibu .
PFX FE 0 lyessilu .
PFX FE 0 lyessiku .
PFX FE 0 lyessitu .
PFX FE 0 lyessimu .
PFX FE 0 lyetutan [^lmnb]
PFX FE l lyetutand l.[^mn]
PFX FE l lyetutann l.[mn]
PFX FE w lyetutamp [w]
PFX FE 0 lyetutamu .
PFX FE 0 lyetutaba .
PFX FE 0 lyetutagu .
PFX FE 0 lyetutagi .
PFX FE 0 lyetutazi .
PFX FE 0 lyetutaki .
PFX FE 0 lyetutabi .
PFX FE 0 lyetutali .
PFX FE 0 lyetutaga .
PFX FE 0 lyetutaka .
PFX FE 0 lyetutabu .
PFX FE 0 lyetutalu .
PFX FE 0 lyetutaku .
PFX FE 0 lyetutatu .
PFX FE 0 lyemutan [^lmnb]
PFX FE l lyemutand l.[^mn]
PFX FE l lyemutann l.[mn]
PFX FE w lyemutamp [w]
PFX FE 0 lyemutamu .
PFX FE 0 lyemutaba .
PFX FE 0 lyemutagu .
PFX FE 0 lyemutagi .
PFX FE 0 lyemutazi .
PFX FE 0 lyemutaki .
PFX FE 0 lyemutabi .
PFX FE 0 lyemutali .
PFX FE 0 lyemutaga .
PFX FE 0 lyemutaka .
PFX FE 0 lyemutabu .
PFX FE 0 lyemutalu .
PFX FE 0 lyemutaku .
PFX FE 0 lyemutatu .
PFX FE 0 lyebatan [^lmnb]
PFX FE l lyebatand l.[^mn]
PFX FE l lyebatann l.[mn]
PFX FE w lyebatamp [w]
PFX FE 0 lyebatamu .
PFX FE 0 lyebataba .
PFX FE 0 lyebatagu .
PFX FE 0 lyebatagi .
PFX FE 0 lyebatazi .
PFX FE 0 lyebataki .
PFX FE 0 lyebatabi .
PFX FE 0 lyebatali .
PFX FE 0 lyebataga .
PFX FE 0 lyebataka .
PFX FE 0 lyebatabu .
PFX FE 0 lyebatalu .
PFX FE 0 lyebataku .
PFX FE 0 lyebatatu .
PFX FE 0 lyegutan [^lmnb]
PFX FE l lyegutand l.[^mn]
PFX FE l lyegutann l.[mn]
PFX FE w lyegutamp [w]
PFX FE 0 lyegutamu .
PFX FE 0 lyegutaba .
PFX FE 0 lyegutagu .
PFX FE 0 lyegutagi .
PFX FE 0 lyegutazi .
PFX FE 0 lyegutaki .
PFX FE 0 lyegutabi .
PFX FE 0 lyegutali .
PFX FE 0 lyegutaga .
PFX FE 0 lyegutaka .
PFX FE 0 lyegutabu .
PFX FE 0 lyegutalu .
PFX FE 0 lyegutaku .
PFX FE 0 lyegutatu .
PFX FE 0 lyegitan [^lmnb]
PFX FE l lyegitand l.[^mn]
PFX FE l lyegitann l.[mn]
PFX FE w lyegitamp [w]
PFX FE 0 lyegitamu .
PFX FE 0 lyegitaba .
PFX FE 0 lyegitagu .
PFX FE 0 lyegitagi .
PFX FE 0 lyegitazi .
PFX FE 0 lyegitaki .
PFX FE 0 lyegitabi .
PFX FE 0 lyegitali .
PFX FE 0 lyegitaga .
PFX FE 0 lyegitaka .
PFX FE 0 lyegitabu .
PFX FE 0 lyegitalu .
PFX FE 0 lyegitaku .
PFX FE 0 lyegitatu .
PFX FE 0 lyezitan [^lmnb]
PFX FE l lyezitand l.[^mn]
PFX FE l lyezitann l.[mn]
PFX FE w lyezitamp [w]
PFX FE 0 lyezitamu .
PFX FE 0 lyezitaba .
PFX FE 0 lyezitagu .
PFX FE 0 lyezitagi .
PFX FE 0 lyezitazi .
PFX FE 0 lyezitaki .
PFX FE 0 lyezitabi .
PFX FE 0 lyezitali .
PFX FE 0 lyezitaga .
PFX FE 0 lyezitaka .
PFX FE 0 lyezitabu .
PFX FE 0 lyezitalu .
PFX FE 0 lyezitaku .
PFX FE 0 lyezitatu .
PFX FE 0 lyekitan [^lmnb]
PFX FE l lyekitand l.[^mn]
PFX FE l lyekitann l.[mn]
PFX FE w lyekitamp [w]
PFX FE 0 lyekitamu .
PFX FE 0 lyekitaba .
PFX FE 0 lyekitagu .
PFX FE 0 lyekitagi .
PFX FE 0 lyekitazi .
PFX FE 0 lyekitaki .
PFX FE 0 lyekitabi .
PFX FE 0 lyekitali .
PFX FE 0 lyekitaga .
PFX FE 0 lyekitaka .
PFX FE 0 lyekitabu .
PFX FE 0 lyekitalu .
PFX FE 0 lyekitaku .
PFX FE 0 lyekitatu .
PFX FE 0 lyebitan [^lmnb]
PFX FE l lyebitand l.[^mn]
PFX FE l lyebitann l.[mn]
PFX FE w lyebitamp [w]
PFX FE 0 lyebitamu .
PFX FE 0 lyebitaba .
PFX FE 0 lyebitagu .
PFX FE 0 lyebitagi .
PFX FE 0 lyebitazi .
PFX FE 0 lyebitaki .
PFX FE 0 lyebitabi .
PFX FE 0 lyebitali .
PFX FE 0 lyebitaga .
PFX FE 0 lyebitaka .
PFX FE 0 lyebitabu .
PFX FE 0 lyebitalu .
PFX FE 0 lyebitaku .
PFX FE 0 lyebitatu .
PFX FE 0 lyelitan [^lmnb]
PFX FE l lyelitand l.[^mn]
PFX FE l lyelitann l.[mn]
PFX FE w lyelitamp [w]
PFX FE 0 lyelitamu .
PFX FE 0 lyelitaba .
PFX FE 0 lyelitagu .
PFX FE 0 lyelitagi .
PFX FE 0 lyelitazi .
PFX FE 0 lyelitaki .
PFX FE 0 lyelitabi .
PFX FE 0 lyelitali .
PFX FE 0 lyelitaga .
PFX FE 0 lyelitaka .
PFX FE 0 lyelitabu .
PFX FE 0 lyelitalu .
PFX FE 0 lyelitaku .
PFX FE 0 lyelitatu .
PFX FE 0 lyegatan [^lmnb]
PFX FE l lyegatand l.[^mn]
PFX FE l lyegatann l.[mn]
PFX FE w lyegatamp [w]
PFX FE 0 lyegatamu .
PFX FE 0 lyegataba .
PFX FE 0 lyegatagu .
PFX FE 0 lyegatagi .
PFX FE 0 lyegatazi .
PFX FE 0 lyegataki .
PFX FE 0 lyegatabi .
PFX FE 0 lyegatali .
PFX FE 0 lyegataga .
PFX FE 0 lyegataka .
PFX FE 0 lyegatabu .
PFX FE 0 lyegatalu .
PFX FE 0 lyegataku .
PFX FE 0 lyegatatu .
PFX FE 0 lyekatan [^lmnb]
PFX FE l lyekatand l.[^mn]
PFX FE l lyekatann l.[mn]
PFX FE w lyekatamp [w]
PFX FE 0 lyekatamu .
PFX FE 0 lyekataba .
PFX FE 0 lyekatagu .
PFX FE 0 lyekatagi .
PFX FE 0 lyekatazi .
PFX FE 0 lyekataki .
PFX FE 0 lyekatabi .
PFX FE 0 lyekatali .
PFX FE 0 lyekataga .
PFX FE 0 lyekataka .
PFX FE 0 lyekatabu .
PFX FE 0 lyekatalu .
PFX FE 0 lyekataku .
PFX FE 0 lyekatatu .
PFX FE 0 lyebutan [^lmnb]
PFX FE l lyebutand l.[^mn]
PFX FE l lyebutann l.[mn]
PFX FE w lyebutamp [w]
PFX FE 0 lyebutamu .
PFX FE 0 lyebutaba .
PFX FE 0 lyebutagu .
PFX FE 0 lyebutagi .
PFX FE 0 lyebutazi .
PFX FE 0 lyebutaki .
PFX FE 0 lyebutabi .
PFX FE 0 lyebutali .
PFX FE 0 lyebutaga .
PFX FE 0 lyebutaka .
PFX FE 0 lyebutabu .
PFX FE 0 lyebutalu .
PFX FE 0 lyebutaku .
PFX FE 0 lyebutatu .
PFX FE 0 lyelutan [^lmnb]
PFX FE l lyelutand l.[^mn]
PFX FE l lyelutann l.[mn]
PFX FE w lyelutamp [w]
PFX FE 0 lyelutamu .
PFX FE 0 lyelutaba .
PFX FE 0 lyelutagu .
PFX FE 0 lyelutagi .
PFX FE 0 lyelutazi .
PFX FE 0 lyelutaki .
PFX FE 0 lyelutabi .
PFX FE 0 lyelutali .
PFX FE 0 lyelutaga .
PFX FE 0 lyelutaka .
PFX FE 0 lyelutabu .
PFX FE 0 lyelutalu .
PFX FE 0 lyelutaku .
PFX FE 0 lyelutatu .
PFX FE 0 lyekutan [^lmnb]
PFX FE l lyekutand l.[^mn]
PFX FE l lyekutann l.[mn]
PFX FE w lyekutamp [w]
PFX FE 0 lyekutamu .
PFX FE 0 lyekutaba .
PFX FE 0 lyekutagu .
PFX FE 0 lyekutagi .
PFX FE 0 lyekutazi .
PFX FE 0 lyekutaki .
PFX FE 0 lyekutabi .
PFX FE 0 lyekutali .
PFX FE 0 lyekutaga .
PFX FE 0 lyekutaka .
PFX FE 0 lyekutabu .
PFX FE 0 lyekutalu .
PFX FE 0 lyekutaku .
PFX FE 0 lyekutatu .
PFX FE 0 lyetutan [^lmnb]
PFX FE l lyetutand l.[^mn]
PFX FE l lyetutann l.[mn]
PFX FE w lyetutamp [w]
PFX FE 0 lyetutamu .
PFX FE 0 lyetutaba .
PFX FE 0 lyetutagu .
PFX FE 0 lyetutagi .
PFX FE 0 lyetutazi .
PFX FE 0 lyetutaki .
PFX FE 0 lyetutabi .
PFX FE 0 lyetutali .
PFX FE 0 lyetutaga .
PFX FE 0 lyetutaka .
PFX FE 0 lyetutabu .
PFX FE 0 lyetutalu .
PFX FE 0 lyetutaku .
PFX FE 0 lyetutatu .
PFX FE 0 kessiba .
PFX FE 0 kessigu .
PFX FE 0 kessigi .
PFX FE 0 kessizi .
PFX FE 0 kessiki .
PFX FE 0 kessibi .
PFX FE 0 kessili .
PFX FE 0 kessiga .
PFX FE 0 kessika .
PFX FE 0 kessibu .
PFX FE 0 kessilu .
PFX FE 0 kessiku .
PFX FE 0 kessitu .
PFX FE 0 kessimu .
PFX FE 0 ketutan [^lmnb]
PFX FE l ketutand l.[^mn]
PFX FE l ketutann l.[mn]
PFX FE w ketutamp [w]
PFX FE 0 ketutamu .
PFX FE 0 ketutaba .
PFX FE 0 ketutagu .
PFX FE 0 ketutagi .
PFX FE 0 ketutazi .
PFX FE 0 ketutaki .
PFX FE 0 ketutabi .
PFX FE 0 ketutali .
PFX FE 0 ketutaga .
PFX FE 0 ketutaka .
PFX FE 0 ketutabu .
PFX FE 0 ketutalu .
PFX FE 0 ketutaku .
PFX FE 0 ketutatu .
PFX FE 0 kemutan [^lmnb]
PFX FE l kemutand l.[^mn]
PFX FE l kemutann l.[mn]
PFX FE w kemutamp [w]
PFX FE 0 kemutamu .
PFX FE 0 kemutaba .
PFX FE 0 kemutagu .
PFX FE 0 kemutagi .
PFX FE 0 kemutazi .
PFX FE 0 kemutaki .
PFX FE 0 kemutabi .
PFX FE 0 kemutali .
PFX FE 0 kemutaga .
PFX FE 0 kemutaka .
PFX FE 0 kemutabu .
PFX FE 0 kemutalu .
PFX FE 0 kemutaku .
PFX FE 0 kemutatu .
PFX FE 0 kebatan [^lmnb]
PFX FE l kebatand l.[^mn]
PFX FE l kebatann l.[mn]
PFX FE w kebatamp [w]
PFX FE 0 kebatamu .
PFX FE 0 kebataba .
PFX FE 0 kebatagu .
PFX FE 0 kebatagi .
PFX FE 0 kebatazi .
PFX FE 0 kebataki .
PFX FE 0 kebatabi .
PFX FE 0 kebatali .
PFX FE 0 kebataga .
PFX FE 0 kebataka .
PFX FE 0 kebatabu .
PFX FE 0 kebatalu .
PFX FE 0 kebataku .
PFX FE 0 kebatatu .
PFX FE 0 kegutan [^lmnb]
PFX FE l kegutand l.[^mn]
PFX FE l kegutann l.[mn]
PFX FE w kegutamp [w]
PFX FE 0 kegutamu .
PFX FE 0 kegutaba .
PFX FE 0 kegutagu .
PFX FE 0 kegutagi .
PFX FE 0 kegutazi .
PFX FE 0 kegutaki .
PFX FE 0 kegutabi .
PFX FE 0 kegutali .
PFX FE 0 kegutaga .
PFX FE 0 kegutaka .
PFX FE 0 kegutabu .
PFX FE 0 kegutalu .
PFX FE 0 kegutaku .
PFX FE 0 kegutatu .
PFX FE 0 kegitan [^lmnb]
PFX FE l kegitand l.[^mn]
PFX FE l kegitann l.[mn]
PFX FE w kegitamp [w]
PFX FE 0 kegitamu .
PFX FE 0 kegitaba .
PFX FE 0 kegitagu .
PFX FE 0 kegitagi .
PFX FE 0 kegitazi .
PFX FE 0 kegitaki .
PFX FE 0 kegitabi .
PFX FE 0 kegitali .
PFX FE 0 kegitaga .
PFX FE 0 kegitaka .
PFX FE 0 kegitabu .
PFX FE 0 kegitalu .
PFX FE 0 kegitaku .
PFX FE 0 kegitatu .
PFX FE 0 kezitan [^lmnb]
PFX FE l kezitand l.[^mn]
PFX FE l kezitann l.[mn]
PFX FE w kezitamp [w]
PFX FE 0 kezitamu .
PFX FE 0 kezitaba .
PFX FE 0 kezitagu .
PFX FE 0 kezitagi .
PFX FE 0 kezitazi .
PFX FE 0 kezitaki .
PFX FE 0 kezitabi .
PFX FE 0 kezitali .
PFX FE 0 kezitaga .
PFX FE 0 kezitaka .
PFX FE 0 kezitabu .
PFX FE 0 kezitalu .
PFX FE 0 kezitaku .
PFX FE 0 kezitatu .
PFX FE 0 kekitan [^lmnb]
PFX FE l kekitand l.[^mn]
PFX FE l kekitann l.[mn]
PFX FE w kekitamp [w]
PFX FE 0 kekitamu .
PFX FE 0 kekitaba .
PFX FE 0 kekitagu .
PFX FE 0 kekitagi .
PFX FE 0 kekitazi .
PFX FE 0 kekitaki .
PFX FE 0 kekitabi .
PFX FE 0 kekitali .
PFX FE 0 kekitaga .
PFX FE 0 kekitaka .
PFX FE 0 kekitabu .
PFX FE 0 kekitalu .
PFX FE 0 kekitaku .
PFX FE 0 kekitatu .
PFX FE 0 kebitan [^lmnb]
PFX FE l kebitand l.[^mn]
PFX FE l kebitann l.[mn]
PFX FE w kebitamp [w]
PFX FE 0 kebitamu .
PFX FE 0 kebitaba .
PFX FE 0 kebitagu .
PFX FE 0 kebitagi .
PFX FE 0 kebitazi .
PFX FE 0 kebitaki .
PFX FE 0 kebitabi .
PFX FE 0 kebitali .
PFX FE 0 kebitaga .
PFX FE 0 kebitaka .
PFX FE 0 kebitabu .
PFX FE 0 kebitalu .
PFX FE 0 kebitaku .
PFX FE 0 kebitatu .
PFX FE 0 kelitan [^lmnb]
PFX FE l kelitand l.[^mn]
PFX FE l kelitann l.[mn]
PFX FE w kelitamp [w]
PFX FE 0 kelitamu .
PFX FE 0 kelitaba .
PFX FE 0 kelitagu .
PFX FE 0 kelitagi .
PFX FE 0 kelitazi .
PFX FE 0 kelitaki .
PFX FE 0 kelitabi .
PFX FE 0 kelitali .
PFX FE 0 kelitaga .
PFX FE 0 kelitaka .
PFX FE 0 kelitabu .
PFX FE 0 kelitalu .
PFX FE 0 kelitaku .
PFX FE 0 kelitatu .
PFX FE 0 kegatan [^lmnb]
PFX FE l kegatand l.[^mn]
PFX FE l kegatann l.[mn]
PFX FE w kegatamp [w]
PFX FE 0 kegatamu .
PFX FE 0 kegataba .
PFX FE 0 kegatagu .
PFX FE 0 kegatagi .
PFX FE 0 kegatazi .
PFX FE 0 kegataki .
PFX FE 0 kegatabi .
PFX FE 0 kegatali .
PFX FE 0 kegataga .
PFX FE 0 kegataka .
PFX FE 0 kegatabu .
PFX FE 0 kegatalu .
PFX FE 0 kegataku .
PFX FE 0 kegatatu .
PFX FE 0 kekatan [^lmnb]
PFX FE l kekatand l.[^mn]
PFX FE l kekatann l.[mn]
PFX FE w kekatamp [w]
PFX FE 0 kekatamu .
PFX FE 0 kekataba .
PFX FE 0 kekatagu .
PFX FE 0 kekatagi .
PFX FE 0 kekatazi .
PFX FE 0 kekataki .
PFX FE 0 kekatabi .
PFX FE 0 kekatali .
PFX FE 0 kekataga .
PFX FE 0 kekataka .
PFX FE 0 kekatabu .
PFX FE 0 kekatalu .
PFX FE 0 kekataku .
PFX FE 0 kekatatu .
PFX FE 0 kebutan [^lmnb]
PFX FE l kebutand l.[^mn]
PFX FE l kebutann l.[mn]
PFX FE w kebutamp [w]
PFX FE 0 kebutamu .
PFX FE 0 kebutaba .
PFX FE 0 kebutagu .
PFX FE 0 kebutagi .
PFX FE 0 kebutazi .
PFX FE 0 kebutaki .
PFX FE 0 kebutabi .
PFX FE 0 kebutali .
PFX FE 0 kebutaga .
PFX FE 0 kebutaka .
PFX FE 0 kebutabu .
PFX FE 0 kebutalu .
PFX FE 0 kebutaku .
PFX FE 0 kebutatu .
PFX FE 0 kelutan [^lmnb]
PFX FE l kelutand l.[^mn]
PFX FE l kelutann l.[mn]
PFX FE w kelutamp [w]
PFX FE 0 kelutamu .
PFX FE 0 kelutaba .
PFX FE 0 kelutagu .
PFX FE 0 kelutagi .
PFX FE 0 kelutazi .
PFX FE 0 kelutaki .
PFX FE 0 kelutabi .
PFX FE 0 kelutali .
PFX FE 0 kelutaga .
PFX FE 0 kelutaka .
PFX FE 0 kelutabu .
PFX FE 0 kelutalu .
PFX FE 0 kelutaku .
PFX FE 0 kelutatu .
PFX FE 0 kekutan [^lmnb]
PFX FE l kekutand l.[^mn]
PFX FE l kekutann l.[mn]
PFX FE w kekutamp [w]
PFX FE 0 kekutamu .
PFX FE 0 kekutaba .
PFX FE 0 kekutagu .
PFX FE 0 kekutagi .
PFX FE 0 kekutazi .
PFX FE 0 kekutaki .
PFX FE 0 kekutabi .
PFX FE 0 kekutali .
PFX FE 0 kekutaga .
PFX FE 0 kekutaka .
PFX FE 0 kekutabu .
PFX FE 0 kekutalu .
PFX FE 0 kekutaku .
PFX FE 0 kekutatu .
PFX FE 0 ketutan [^lmnb]
PFX FE l ketutand l.[^mn]
PFX FE l ketutann l.[mn]
PFX FE w ketutamp [w]
PFX FE 0 ketutamu .
PFX FE 0 ketutaba .
PFX FE 0 ketutagu .
PFX FE 0 ketutagi .
PFX FE 0 ketutazi .
PFX FE 0 ketutaki .
PFX FE 0 ketutabi .
PFX FE 0 ketutali .
PFX FE 0 ketutaga .
PFX FE 0 ketutaka .
PFX FE 0 ketutabu .
PFX FE 0 ketutalu .
PFX FE 0 ketutaku .
PFX FE 0 ketutatu .
PFX FE 0 oton [^lmnb]
PFX FE l otond l.[^mn]
PFX FE l otonn l.[mn]
PFX FE w otomp [w]
PFX FE 0 otomu .
PFX FE 0 otoba .
PFX FE 0 otogu .
PFX FE 0 otogi .
PFX FE 0 otozi .
PFX FE 0 otoki .
PFX FE 0 otobi .
PFX FE 0 otoli .
PFX FE 0 otoga .
PFX FE 0 otoka .
PFX FE 0 otobu .
PFX FE 0 otolu .
PFX FE 0 otoku .
PFX FE 0 ototu .
PFX FE 0 atan [^lmnb]
PFX FE l atand l.[^mn]
PFX FE l atann l.[mn]
PFX FE w atamp [w]
PFX FE 0 atamu .
PFX FE 0 ataba .
PFX FE 0 atagu .
PFX FE 0 atagi .
PFX FE 0 atazi .
PFX FE 0 ataki .
PFX FE 0 atabi .
PFX FE 0 atali .
PFX FE 0 ataga .
PFX FE 0 ataka .
PFX FE 0 atabu .
PFX FE 0 atalu .
PFX FE 0 ataku .
PFX FE 0 atatu .
PFX FE 0 eten [^lmnb]
PFX FE l etend l.[^mn]
PFX FE l etenn l.[mn]
PFX FE w etemp [w]
PFX FE 0 etemu .
PFX FE 0 eteba .
PFX FE 0 etegu .
PFX FE 0 etegi .
PFX FE 0 etezi .
PFX FE 0 eteki .
PFX FE 0 etebi .
PFX FE 0 eteli .
PFX FE 0 etega .
PFX FE 0 eteka .
PFX FE 0 etebu .
PFX FE 0 etelu .
PFX FE 0 eteku .
PFX FE 0 etetu ."""

rule_right_raw = """
PFX OR Y 16
PFX OR 0 mwe .
PFX OR 0 bee .
PFX OR 0 gwe .
PFX OR 0 gye .
PFX OR 0 zee .
PFX OR 0 kye .
PFX OR 0 bye .
PFX OR 0 lye .
PFX OR 0 gee .
PFX OR 0 kee .
PFX OR 0 bwe .
PFX OR 0 lwe .
PFX OR 0 zee .
PFX OR 0 kwe .
PFX OR 0 gee .
PFX OR 0 twe ."""

FLAG_DESCRIPTIONS = {
    "FE": "FE",
    "OR": "Special reflexive object markers",
}

def parse_rules(raw_text):
    rules = []
    for line in raw_text.strip().split('\n'):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        s = s.split('#', 1)[0].strip()
        parts = s.split()
        if len(parts) < 4:
            continue
        if parts[2] == 'Y':
            continue
        cond = parts[4] if len(parts) > 4 else '.'
        rules.append({'strip': parts[2], 'add': parts[3], 'cond': cond})
    return rules

def generate_block():
    lefts = parse_rules(rule_left_raw)
    rights = parse_rules(rule_right_raw)
    new_rules = []

    for left in lefts:
        for right in rights:
            if left['strip'] != '0':
                if not right['add'].startswith(left['strip']):
                    continue
                combined = left['add'] + right['add'][len(left['strip']):]
            else:
                combined = left['add'] + right['add']

            if left['cond'] != '.':
                if not re.match(left['cond'], right['add']):
                    continue

            new_rules.append({'strip': right['strip'], 'add': combined, 'cond': right['cond']})

    out_flag = "GT"
    left_desc = FLAG_DESCRIPTIONS.get("FE", "FE")
    right_desc = FLAG_DESCRIPTIONS.get("OR", "OR")
    comment_line = "# Cross product of {} ({}) and {} ({}) to {}".format(
        "FE", left_desc, "OR", right_desc, out_flag
    )

    output = ["PFX {} Y {}".format(out_flag, len(new_rules))]
    for r in new_rules:
        output.append("PFX {} {} {} {}".format(out_flag, r['strip'], r['add'], r['cond']))

    return (out_flag, "\n".join([comment_line] + output) + "\n")

def main():
    if not os.path.exists(AFF_FILE):
        print("Error: {} not found.".format(AFF_FILE))
        return

    out_flag, block = generate_block()

    with open(AFF_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    first_flag_idx = None
    last_flag_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("PFX {} ".format(out_flag)):
            if first_flag_idx is None:
                first_flag_idx = i
            last_flag_idx = i

    if first_flag_idx is not None and first_flag_idx > 0:
        prev_line = lines[first_flag_idx - 1].strip()
        if prev_line.startswith("# Cross product"):
            start_idx = first_flag_idx - 1
        else:
            start_idx = first_flag_idx
    elif first_flag_idx is not None:
        start_idx = first_flag_idx
    else:
        start_idx = None

    if start_idx is not None and last_flag_idx is not None:
        # Replace existing block in-place.
        new_lines = lines[:start_idx] + [block] + lines[last_flag_idx + 1:]
    else:
        # Insert before an anchor flag if requested; otherwise append.
        insert_idx = None
        if INSERT_BEFORE_FLAG:
            anchor_prefix = "PFX {} ".format(INSERT_BEFORE_FLAG)
            for i, line in enumerate(lines):
                if line.strip().startswith(anchor_prefix):
                    insert_idx = i
                    # If the anchor PFX block is preceded by one or more cross-product
                    # comment lines, insert before those comments to keep them attached
                    # to the anchor block.
                    while insert_idx > 0 and lines[insert_idx - 1].strip().startswith("# Cross product"):
                        insert_idx -= 1
                    break

        if insert_idx is not None:
            new_lines = lines[:insert_idx] + [block] + lines[insert_idx:]
        else:
            new_lines = lines
            if new_lines and not new_lines[-1].endswith(chr(10)):
                new_lines[-1] += chr(10)
            new_lines.append(block)

    with open(AFF_FILE, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    print("{}: updated in place.".format(out_flag))

if __name__ == '__main__':
    main()
