import re
import os
from pathlib import Path

# Cross product generator: FH x OR => GH
# Description:
# - Left block `FH`: FH
# - Right block `OR`: Special reflexive object markers
# - Output flag `GH`: Cross-product prefixes for FH x OR

REPO_ROOT = Path(__file__).resolve().parents[1]
AFF_FILE = REPO_ROOT / "Luganda.aff"

# If set to a flag name (e.g. "HB"), the generated cross-product block will be inserted
# immediately before the first "PFX <flag>" line when the output flag block doesn't
# already exist in the .aff.
INSERT_BEFORE_FLAG = "".strip() or None

rule_left_raw = """
PFX FH Y 3408
PFX FH 0 w'otaan [^lmnb]
PFX FH l w'otaand l.[^mn][^u]
PFX FH l w'otaann l.[mn]
PFX FH w w'otaamp [w]
PFX FH 0 w'otaamu .
PFX FH 0 w'otaaba .
PFX FH 0 w'otaagu .
PFX FH 0 w'otaagi .
PFX FH 0 w'otaazi .
PFX FH 0 w'otaaki .
PFX FH 0 w'otaabi .
PFX FH 0 w'otaali .
PFX FH 0 w'otaaga .
PFX FH 0 w'otaaka .
PFX FH 0 w'otaabu .
PFX FH 0 w'otaalu .
PFX FH 0 w'otaaku .
PFX FH 0 w'otaatu .
PFX FH 0 w'ataan [^lmnb]
PFX FH l w'ataand l.[^mn][^u]
PFX FH l w'ataann l.[mn]
PFX FH w w'ataamp [w]
PFX FH 0 w'ataamu .
PFX FH 0 w'ataaba .
PFX FH 0 w'ataagu .
PFX FH 0 w'ataagi .
PFX FH 0 w'ataazi .
PFX FH 0 w'ataaki .
PFX FH 0 w'ataabi .
PFX FH 0 w'ataali .
PFX FH 0 w'ataaga .
PFX FH 0 w'ataaka .
PFX FH 0 w'ataabu .
PFX FH 0 w'ataalu .
PFX FH 0 w'ataaku .
PFX FH 0 w'ataatu .
PFX FH 0 w'etaan [^lmnb]
PFX FH l w'etaand l.[^mn][^u]
PFX FH l w'etaann l.[mn]
PFX FH w w'etaamp [w]
PFX FH 0 w'etaamu .
PFX FH 0 w'etaaba .
PFX FH 0 w'etaagu .
PFX FH 0 w'etaagi .
PFX FH 0 w'etaazi .
PFX FH 0 w'etaaki .
PFX FH 0 w'etaabi .
PFX FH 0 w'etaali .
PFX FH 0 w'etaaga .
PFX FH 0 w'etaaka .
PFX FH 0 w'etaabu .
PFX FH 0 w'etaalu .
PFX FH 0 w'etaaku .
PFX FH 0 w'etaatu .
PFX FH 0 wessaaba .
PFX FH 0 wessaagu .
PFX FH 0 wessaagi .
PFX FH 0 wessaazi .
PFX FH 0 wessaaki .
PFX FH 0 wessaabi .
PFX FH 0 wessaali .
PFX FH 0 wessaaga .
PFX FH 0 wessaaka .
PFX FH 0 wessaabu .
PFX FH 0 wessaalu .
PFX FH 0 wessaaku .
PFX FH 0 wessaatu .
PFX FH 0 wessaamu .
PFX FH 0 wetutaan [^lmnb]
PFX FH l wetutaand l.[^mn][^u]
PFX FH l wetutaann l.[mn]
PFX FH w wetutaamp [w]
PFX FH 0 wetutaamu .
PFX FH 0 wetutaaba .
PFX FH 0 wetutaagu .
PFX FH 0 wetutaagi .
PFX FH 0 wetutaazi .
PFX FH 0 wetutaaki .
PFX FH 0 wetutaabi .
PFX FH 0 wetutaali .
PFX FH 0 wetutaaga .
PFX FH 0 wetutaaka .
PFX FH 0 wetutaabu .
PFX FH 0 wetutaalu .
PFX FH 0 wetutaaku .
PFX FH 0 wetutaatu .
PFX FH 0 wemutaan [^lmnb]
PFX FH l wemutaand l.[^mn][^u]
PFX FH l wemutaann l.[mn]
PFX FH w wemutaamp [w]
PFX FH 0 wemutaamu .
PFX FH 0 wemutaaba .
PFX FH 0 wemutaagu .
PFX FH 0 wemutaagi .
PFX FH 0 wemutaazi .
PFX FH 0 wemutaaki .
PFX FH 0 wemutaabi .
PFX FH 0 wemutaali .
PFX FH 0 wemutaaga .
PFX FH 0 wemutaaka .
PFX FH 0 wemutaabu .
PFX FH 0 wemutaalu .
PFX FH 0 wemutaaku .
PFX FH 0 wemutaatu .
PFX FH 0 webataan [^lmnb]
PFX FH l webataand l.[^mn][^u]
PFX FH l webataann l.[mn]
PFX FH w webataamp [w]
PFX FH 0 webataamu .
PFX FH 0 webataaba .
PFX FH 0 webataagu .
PFX FH 0 webataagi .
PFX FH 0 webataazi .
PFX FH 0 webataaki .
PFX FH 0 webataabi .
PFX FH 0 webataali .
PFX FH 0 webataaga .
PFX FH 0 webataaka .
PFX FH 0 webataabu .
PFX FH 0 webataalu .
PFX FH 0 webataaku .
PFX FH 0 webataatu .
PFX FH 0 wegutaan [^lmnb]
PFX FH l wegutaand l.[^mn][^u]
PFX FH l wegutaann l.[mn]
PFX FH w wegutaamp [w]
PFX FH 0 wegutaamu .
PFX FH 0 wegutaaba .
PFX FH 0 wegutaagu .
PFX FH 0 wegutaagi .
PFX FH 0 wegutaazi .
PFX FH 0 wegutaaki .
PFX FH 0 wegutaabi .
PFX FH 0 wegutaali .
PFX FH 0 wegutaaga .
PFX FH 0 wegutaaka .
PFX FH 0 wegutaabu .
PFX FH 0 wegutaalu .
PFX FH 0 wegutaaku .
PFX FH 0 wegutaatu .
PFX FH 0 wegitaan [^lmnb]
PFX FH l wegitaand l.[^mn][^u]
PFX FH l wegitaann l.[mn]
PFX FH w wegitaamp [w]
PFX FH 0 wegitaamu .
PFX FH 0 wegitaaba .
PFX FH 0 wegitaagu .
PFX FH 0 wegitaagi .
PFX FH 0 wegitaazi .
PFX FH 0 wegitaaki .
PFX FH 0 wegitaabi .
PFX FH 0 wegitaali .
PFX FH 0 wegitaaga .
PFX FH 0 wegitaaka .
PFX FH 0 wegitaabu .
PFX FH 0 wegitaalu .
PFX FH 0 wegitaaku .
PFX FH 0 wegitaatu .
PFX FH 0 wezitaan [^lmnb]
PFX FH l wezitaand l.[^mn][^u]
PFX FH l wezitaann l.[mn]
PFX FH w wezitaamp [w]
PFX FH 0 wezitaamu .
PFX FH 0 wezitaaba .
PFX FH 0 wezitaagu .
PFX FH 0 wezitaagi .
PFX FH 0 wezitaazi .
PFX FH 0 wezitaaki .
PFX FH 0 wezitaabi .
PFX FH 0 wezitaali .
PFX FH 0 wezitaaga .
PFX FH 0 wezitaaka .
PFX FH 0 wezitaabu .
PFX FH 0 wezitaalu .
PFX FH 0 wezitaaku .
PFX FH 0 wezitaatu .
PFX FH 0 wekitaan [^lmnb]
PFX FH l wekitaand l.[^mn][^u]
PFX FH l wekitaann l.[mn]
PFX FH w wekitaamp [w]
PFX FH 0 wekitaamu .
PFX FH 0 wekitaaba .
PFX FH 0 wekitaagu .
PFX FH 0 wekitaagi .
PFX FH 0 wekitaazi .
PFX FH 0 wekitaaki .
PFX FH 0 wekitaabi .
PFX FH 0 wekitaali .
PFX FH 0 wekitaaga .
PFX FH 0 wekitaaka .
PFX FH 0 wekitaabu .
PFX FH 0 wekitaalu .
PFX FH 0 wekitaaku .
PFX FH 0 wekitaatu .
PFX FH 0 webitaan [^lmnb]
PFX FH l webitaand l.[^mn][^u]
PFX FH l webitaann l.[mn]
PFX FH w webitaamp [w]
PFX FH 0 webitaamu .
PFX FH 0 webitaaba .
PFX FH 0 webitaagu .
PFX FH 0 webitaagi .
PFX FH 0 webitaazi .
PFX FH 0 webitaaki .
PFX FH 0 webitaabi .
PFX FH 0 webitaali .
PFX FH 0 webitaaga .
PFX FH 0 webitaaka .
PFX FH 0 webitaabu .
PFX FH 0 webitaalu .
PFX FH 0 webitaaku .
PFX FH 0 webitaatu .
PFX FH 0 welitaan [^lmnb]
PFX FH l welitaand l.[^mn][^u]
PFX FH l welitaann l.[mn]
PFX FH w welitaamp [w]
PFX FH 0 welitaamu .
PFX FH 0 welitaaba .
PFX FH 0 welitaagu .
PFX FH 0 welitaagi .
PFX FH 0 welitaazi .
PFX FH 0 welitaaki .
PFX FH 0 welitaabi .
PFX FH 0 welitaali .
PFX FH 0 welitaaga .
PFX FH 0 welitaaka .
PFX FH 0 welitaabu .
PFX FH 0 welitaalu .
PFX FH 0 welitaaku .
PFX FH 0 welitaatu .
PFX FH 0 wegataan [^lmnb]
PFX FH l wegataand l.[^mn][^u]
PFX FH l wegataann l.[mn]
PFX FH w wegataamp [w]
PFX FH 0 wegataamu .
PFX FH 0 wegataaba .
PFX FH 0 wegataagu .
PFX FH 0 wegataagi .
PFX FH 0 wegataazi .
PFX FH 0 wegataaki .
PFX FH 0 wegataabi .
PFX FH 0 wegataali .
PFX FH 0 wegataaga .
PFX FH 0 wegataaka .
PFX FH 0 wegataabu .
PFX FH 0 wegataalu .
PFX FH 0 wegataaku .
PFX FH 0 wegataatu .
PFX FH 0 wekataan [^lmnb]
PFX FH l wekataand l.[^mn][^u]
PFX FH l wekataann l.[mn]
PFX FH w wekataamp [w]
PFX FH 0 wekataamu .
PFX FH 0 wekataaba .
PFX FH 0 wekataagu .
PFX FH 0 wekataagi .
PFX FH 0 wekataazi .
PFX FH 0 wekataaki .
PFX FH 0 wekataabi .
PFX FH 0 wekataali .
PFX FH 0 wekataaga .
PFX FH 0 wekataaka .
PFX FH 0 wekataabu .
PFX FH 0 wekataalu .
PFX FH 0 wekataaku .
PFX FH 0 wekataatu .
PFX FH 0 webutaan [^lmnb]
PFX FH l webutaand l.[^mn][^u]
PFX FH l webutaann l.[mn]
PFX FH w webutaamp [w]
PFX FH 0 webutaamu .
PFX FH 0 webutaaba .
PFX FH 0 webutaagu .
PFX FH 0 webutaagi .
PFX FH 0 webutaazi .
PFX FH 0 webutaaki .
PFX FH 0 webutaabi .
PFX FH 0 webutaali .
PFX FH 0 webutaaga .
PFX FH 0 webutaaka .
PFX FH 0 webutaabu .
PFX FH 0 webutaalu .
PFX FH 0 webutaaku .
PFX FH 0 webutaatu .
PFX FH 0 welutaan [^lmnb]
PFX FH l welutaand l.[^mn][^u]
PFX FH l welutaann l.[mn]
PFX FH w welutaamp [w]
PFX FH 0 welutaamu .
PFX FH 0 welutaaba .
PFX FH 0 welutaagu .
PFX FH 0 welutaagi .
PFX FH 0 welutaazi .
PFX FH 0 welutaaki .
PFX FH 0 welutaabi .
PFX FH 0 welutaali .
PFX FH 0 welutaaga .
PFX FH 0 welutaaka .
PFX FH 0 welutaabu .
PFX FH 0 welutaalu .
PFX FH 0 welutaaku .
PFX FH 0 welutaatu .
PFX FH 0 wekutaan [^lmnb]
PFX FH l wekutaand l.[^mn][^u]
PFX FH l wekutaann l.[mn]
PFX FH w wekutaamp [w]
PFX FH 0 wekutaamu .
PFX FH 0 wekutaaba .
PFX FH 0 wekutaagu .
PFX FH 0 wekutaagi .
PFX FH 0 wekutaazi .
PFX FH 0 wekutaaki .
PFX FH 0 wekutaabi .
PFX FH 0 wekutaali .
PFX FH 0 wekutaaga .
PFX FH 0 wekutaaka .
PFX FH 0 wekutaabu .
PFX FH 0 wekutaalu .
PFX FH 0 wekutaaku .
PFX FH 0 wekutaatu .
PFX FH 0 wetutaan [^lmnb]
PFX FH l wetutaand l.[^mn][^u]
PFX FH l wetutaann l.[mn]
PFX FH w wetutaamp [w]
PFX FH 0 wetutaamu .
PFX FH 0 wetutaaba .
PFX FH 0 wetutaagu .
PFX FH 0 wetutaagi .
PFX FH 0 wetutaazi .
PFX FH 0 wetutaaki .
PFX FH 0 wetutaabi .
PFX FH 0 wetutaali .
PFX FH 0 wetutaaga .
PFX FH 0 wetutaaka .
PFX FH 0 wetutaabu .
PFX FH 0 wetutaalu .
PFX FH 0 wetutaaku .
PFX FH 0 wetutaatu .
PFX FH 0 bw'otaan [^lmnb]
PFX FH l bw'otaand l.[^mn][^u]
PFX FH l bw'otaann l.[mn]
PFX FH w bw'otaamp [w]
PFX FH 0 bw'otaamu .
PFX FH 0 bw'otaaba .
PFX FH 0 bw'otaagu .
PFX FH 0 bw'otaagi .
PFX FH 0 bw'otaazi .
PFX FH 0 bw'otaaki .
PFX FH 0 bw'otaabi .
PFX FH 0 bw'otaali .
PFX FH 0 bw'otaaga .
PFX FH 0 bw'otaaka .
PFX FH 0 bw'otaabu .
PFX FH 0 bw'otaalu .
PFX FH 0 bw'otaaku .
PFX FH 0 bw'otaatu .
PFX FH 0 bw'ataan [^lmnb]
PFX FH l bw'ataand l.[^mn][^u]
PFX FH l bw'ataann l.[mn]
PFX FH w bw'ataamp [w]
PFX FH 0 bw'ataamu .
PFX FH 0 bw'ataaba .
PFX FH 0 bw'ataagu .
PFX FH 0 bw'ataagi .
PFX FH 0 bw'ataazi .
PFX FH 0 bw'ataaki .
PFX FH 0 bw'ataabi .
PFX FH 0 bw'ataali .
PFX FH 0 bw'ataaga .
PFX FH 0 bw'ataaka .
PFX FH 0 bw'ataabu .
PFX FH 0 bw'ataalu .
PFX FH 0 bw'ataaku .
PFX FH 0 bw'ataatu .
PFX FH 0 bw'etaan [^lmnb]
PFX FH l bw'etaand l.[^mn][^u]
PFX FH l bw'etaann l.[mn]
PFX FH w bw'etaamp [w]
PFX FH 0 bw'etaamu .
PFX FH 0 bw'etaaba .
PFX FH 0 bw'etaagu .
PFX FH 0 bw'etaagi .
PFX FH 0 bw'etaazi .
PFX FH 0 bw'etaaki .
PFX FH 0 bw'etaabi .
PFX FH 0 bw'etaali .
PFX FH 0 bw'etaaga .
PFX FH 0 bw'etaaka .
PFX FH 0 bw'etaabu .
PFX FH 0 bw'etaalu .
PFX FH 0 bw'etaaku .
PFX FH 0 bw'etaatu .
PFX FH 0 bwessaaba .
PFX FH 0 bwessaagu .
PFX FH 0 bwessaagi .
PFX FH 0 bwessaazi .
PFX FH 0 bwessaaki .
PFX FH 0 bwessaabi .
PFX FH 0 bwessaali .
PFX FH 0 bwessaaga .
PFX FH 0 bwessaaka .
PFX FH 0 bwessaabu .
PFX FH 0 bwessaalu .
PFX FH 0 bwessaaku .
PFX FH 0 bwessaatu .
PFX FH 0 bwessaamu .
PFX FH 0 bwetutaan [^lmnb]
PFX FH l bwetutaand l.[^mn][^u]
PFX FH l bwetutaann l.[mn]
PFX FH w bwetutaamp [w]
PFX FH 0 bwetutaamu .
PFX FH 0 bwetutaaba .
PFX FH 0 bwetutaagu .
PFX FH 0 bwetutaagi .
PFX FH 0 bwetutaazi .
PFX FH 0 bwetutaaki .
PFX FH 0 bwetutaabi .
PFX FH 0 bwetutaali .
PFX FH 0 bwetutaaga .
PFX FH 0 bwetutaaka .
PFX FH 0 bwetutaabu .
PFX FH 0 bwetutaalu .
PFX FH 0 bwetutaaku .
PFX FH 0 bwetutaatu .
PFX FH 0 bwemutaan [^lmnb]
PFX FH l bwemutaand l.[^mn][^u]
PFX FH l bwemutaann l.[mn]
PFX FH w bwemutaamp [w]
PFX FH 0 bwemutaamu .
PFX FH 0 bwemutaaba .
PFX FH 0 bwemutaagu .
PFX FH 0 bwemutaagi .
PFX FH 0 bwemutaazi .
PFX FH 0 bwemutaaki .
PFX FH 0 bwemutaabi .
PFX FH 0 bwemutaali .
PFX FH 0 bwemutaaga .
PFX FH 0 bwemutaaka .
PFX FH 0 bwemutaabu .
PFX FH 0 bwemutaalu .
PFX FH 0 bwemutaaku .
PFX FH 0 bwemutaatu .
PFX FH 0 bwebataan [^lmnb]
PFX FH l bwebataand l.[^mn][^u]
PFX FH l bwebataann l.[mn]
PFX FH w bwebataamp [w]
PFX FH 0 bwebataamu .
PFX FH 0 bwebataaba .
PFX FH 0 bwebataagu .
PFX FH 0 bwebataagi .
PFX FH 0 bwebataazi .
PFX FH 0 bwebataaki .
PFX FH 0 bwebataabi .
PFX FH 0 bwebataali .
PFX FH 0 bwebataaga .
PFX FH 0 bwebataaka .
PFX FH 0 bwebataabu .
PFX FH 0 bwebataalu .
PFX FH 0 bwebataaku .
PFX FH 0 bwebataatu .
PFX FH 0 bwegutaan [^lmnb]
PFX FH l bwegutaand l.[^mn][^u]
PFX FH l bwegutaann l.[mn]
PFX FH w bwegutaamp [w]
PFX FH 0 bwegutaamu .
PFX FH 0 bwegutaaba .
PFX FH 0 bwegutaagu .
PFX FH 0 bwegutaagi .
PFX FH 0 bwegutaazi .
PFX FH 0 bwegutaaki .
PFX FH 0 bwegutaabi .
PFX FH 0 bwegutaali .
PFX FH 0 bwegutaaga .
PFX FH 0 bwegutaaka .
PFX FH 0 bwegutaabu .
PFX FH 0 bwegutaalu .
PFX FH 0 bwegutaaku .
PFX FH 0 bwegutaatu .
PFX FH 0 bwegitaan [^lmnb]
PFX FH l bwegitaand l.[^mn][^u]
PFX FH l bwegitaann l.[mn]
PFX FH w bwegitaamp [w]
PFX FH 0 bwegitaamu .
PFX FH 0 bwegitaaba .
PFX FH 0 bwegitaagu .
PFX FH 0 bwegitaagi .
PFX FH 0 bwegitaazi .
PFX FH 0 bwegitaaki .
PFX FH 0 bwegitaabi .
PFX FH 0 bwegitaali .
PFX FH 0 bwegitaaga .
PFX FH 0 bwegitaaka .
PFX FH 0 bwegitaabu .
PFX FH 0 bwegitaalu .
PFX FH 0 bwegitaaku .
PFX FH 0 bwegitaatu .
PFX FH 0 bwezitaan [^lmnb]
PFX FH l bwezitaand l.[^mn][^u]
PFX FH l bwezitaann l.[mn]
PFX FH w bwezitaamp [w]
PFX FH 0 bwezitaamu .
PFX FH 0 bwezitaaba .
PFX FH 0 bwezitaagu .
PFX FH 0 bwezitaagi .
PFX FH 0 bwezitaazi .
PFX FH 0 bwezitaaki .
PFX FH 0 bwezitaabi .
PFX FH 0 bwezitaali .
PFX FH 0 bwezitaaga .
PFX FH 0 bwezitaaka .
PFX FH 0 bwezitaabu .
PFX FH 0 bwezitaalu .
PFX FH 0 bwezitaaku .
PFX FH 0 bwezitaatu .
PFX FH 0 bwekitaan [^lmnb]
PFX FH l bwekitaand l.[^mn][^u]
PFX FH l bwekitaann l.[mn]
PFX FH w bwekitaamp [w]
PFX FH 0 bwekitaamu .
PFX FH 0 bwekitaaba .
PFX FH 0 bwekitaagu .
PFX FH 0 bwekitaagi .
PFX FH 0 bwekitaazi .
PFX FH 0 bwekitaaki .
PFX FH 0 bwekitaabi .
PFX FH 0 bwekitaali .
PFX FH 0 bwekitaaga .
PFX FH 0 bwekitaaka .
PFX FH 0 bwekitaabu .
PFX FH 0 bwekitaalu .
PFX FH 0 bwekitaaku .
PFX FH 0 bwekitaatu .
PFX FH 0 bwebitaan [^lmnb]
PFX FH l bwebitaand l.[^mn][^u]
PFX FH l bwebitaann l.[mn]
PFX FH w bwebitaamp [w]
PFX FH 0 bwebitaamu .
PFX FH 0 bwebitaaba .
PFX FH 0 bwebitaagu .
PFX FH 0 bwebitaagi .
PFX FH 0 bwebitaazi .
PFX FH 0 bwebitaaki .
PFX FH 0 bwebitaabi .
PFX FH 0 bwebitaali .
PFX FH 0 bwebitaaga .
PFX FH 0 bwebitaaka .
PFX FH 0 bwebitaabu .
PFX FH 0 bwebitaalu .
PFX FH 0 bwebitaaku .
PFX FH 0 bwebitaatu .
PFX FH 0 bwelitaan [^lmnb]
PFX FH l bwelitaand l.[^mn][^u]
PFX FH l bwelitaann l.[mn]
PFX FH w bwelitaamp [w]
PFX FH 0 bwelitaamu .
PFX FH 0 bwelitaaba .
PFX FH 0 bwelitaagu .
PFX FH 0 bwelitaagi .
PFX FH 0 bwelitaazi .
PFX FH 0 bwelitaaki .
PFX FH 0 bwelitaabi .
PFX FH 0 bwelitaali .
PFX FH 0 bwelitaaga .
PFX FH 0 bwelitaaka .
PFX FH 0 bwelitaabu .
PFX FH 0 bwelitaalu .
PFX FH 0 bwelitaaku .
PFX FH 0 bwelitaatu .
PFX FH 0 bwegataan [^lmnb]
PFX FH l bwegataand l.[^mn][^u]
PFX FH l bwegataann l.[mn]
PFX FH w bwegataamp [w]
PFX FH 0 bwegataamu .
PFX FH 0 bwegataaba .
PFX FH 0 bwegataagu .
PFX FH 0 bwegataagi .
PFX FH 0 bwegataazi .
PFX FH 0 bwegataaki .
PFX FH 0 bwegataabi .
PFX FH 0 bwegataali .
PFX FH 0 bwegataaga .
PFX FH 0 bwegataaka .
PFX FH 0 bwegataabu .
PFX FH 0 bwegataalu .
PFX FH 0 bwegataaku .
PFX FH 0 bwegataatu .
PFX FH 0 bwekataan [^lmnb]
PFX FH l bwekataand l.[^mn][^u]
PFX FH l bwekataann l.[mn]
PFX FH w bwekataamp [w]
PFX FH 0 bwekataamu .
PFX FH 0 bwekataaba .
PFX FH 0 bwekataagu .
PFX FH 0 bwekataagi .
PFX FH 0 bwekataazi .
PFX FH 0 bwekataaki .
PFX FH 0 bwekataabi .
PFX FH 0 bwekataali .
PFX FH 0 bwekataaga .
PFX FH 0 bwekataaka .
PFX FH 0 bwekataabu .
PFX FH 0 bwekataalu .
PFX FH 0 bwekataaku .
PFX FH 0 bwekataatu .
PFX FH 0 bwebutaan [^lmnb]
PFX FH l bwebutaand l.[^mn][^u]
PFX FH l bwebutaann l.[mn]
PFX FH w bwebutaamp [w]
PFX FH 0 bwebutaamu .
PFX FH 0 bwebutaaba .
PFX FH 0 bwebutaagu .
PFX FH 0 bwebutaagi .
PFX FH 0 bwebutaazi .
PFX FH 0 bwebutaaki .
PFX FH 0 bwebutaabi .
PFX FH 0 bwebutaali .
PFX FH 0 bwebutaaga .
PFX FH 0 bwebutaaka .
PFX FH 0 bwebutaabu .
PFX FH 0 bwebutaalu .
PFX FH 0 bwebutaaku .
PFX FH 0 bwebutaatu .
PFX FH 0 bwelutaan [^lmnb]
PFX FH l bwelutaand l.[^mn][^u]
PFX FH l bwelutaann l.[mn]
PFX FH w bwelutaamp [w]
PFX FH 0 bwelutaamu .
PFX FH 0 bwelutaaba .
PFX FH 0 bwelutaagu .
PFX FH 0 bwelutaagi .
PFX FH 0 bwelutaazi .
PFX FH 0 bwelutaaki .
PFX FH 0 bwelutaabi .
PFX FH 0 bwelutaali .
PFX FH 0 bwelutaaga .
PFX FH 0 bwelutaaka .
PFX FH 0 bwelutaabu .
PFX FH 0 bwelutaalu .
PFX FH 0 bwelutaaku .
PFX FH 0 bwelutaatu .
PFX FH 0 bwekutaan [^lmnb]
PFX FH l bwekutaand l.[^mn][^u]
PFX FH l bwekutaann l.[mn]
PFX FH w bwekutaamp [w]
PFX FH 0 bwekutaamu .
PFX FH 0 bwekutaaba .
PFX FH 0 bwekutaagu .
PFX FH 0 bwekutaagi .
PFX FH 0 bwekutaazi .
PFX FH 0 bwekutaaki .
PFX FH 0 bwekutaabi .
PFX FH 0 bwekutaali .
PFX FH 0 bwekutaaga .
PFX FH 0 bwekutaaka .
PFX FH 0 bwekutaabu .
PFX FH 0 bwekutaalu .
PFX FH 0 bwekutaaku .
PFX FH 0 bwekutaatu .
PFX FH 0 bwetutaan [^lmnb]
PFX FH l bwetutaand l.[^mn][^u]
PFX FH l bwetutaann l.[mn]
PFX FH w bwetutaamp [w]
PFX FH 0 bwetutaamu .
PFX FH 0 bwetutaaba .
PFX FH 0 bwetutaagu .
PFX FH 0 bwetutaagi .
PFX FH 0 bwetutaazi .
PFX FH 0 bwetutaaki .
PFX FH 0 bwetutaabi .
PFX FH 0 bwetutaali .
PFX FH 0 bwetutaaga .
PFX FH 0 bwetutaaka .
PFX FH 0 bwetutaabu .
PFX FH 0 bwetutaalu .
PFX FH 0 bwetutaaku .
PFX FH 0 bwetutaatu .
PFX FH 0 bwessaaba .
PFX FH 0 bwessaagu .
PFX FH 0 bwessaagi .
PFX FH 0 bwessaazi .
PFX FH 0 bwessaaki .
PFX FH 0 bwessaabi .
PFX FH 0 bwessaali .
PFX FH 0 bwessaaga .
PFX FH 0 bwessaaka .
PFX FH 0 bwessaabu .
PFX FH 0 bwessaalu .
PFX FH 0 bwessaaku .
PFX FH 0 bwessaatu .
PFX FH 0 bwessaamu .
PFX FH 0 lw'otaan [^lmnb]
PFX FH l lw'otaand l.[^mn][^u]
PFX FH l lw'otaann l.[mn]
PFX FH w lw'otaamp [w]
PFX FH 0 lw'otaamu .
PFX FH 0 lw'otaaba .
PFX FH 0 lw'otaagu .
PFX FH 0 lw'otaagi .
PFX FH 0 lw'otaazi .
PFX FH 0 lw'otaaki .
PFX FH 0 lw'otaabi .
PFX FH 0 lw'otaali .
PFX FH 0 lw'otaaga .
PFX FH 0 lw'otaaka .
PFX FH 0 lw'otaabu .
PFX FH 0 lw'otaalu .
PFX FH 0 lw'otaaku .
PFX FH 0 lw'otaatu .
PFX FH 0 lw'ataan [^lmnb]
PFX FH l lw'ataand l.[^mn][^u]
PFX FH l lw'ataann l.[mn]
PFX FH w lw'ataamp [w]
PFX FH 0 lw'ataamu .
PFX FH 0 lw'ataaba .
PFX FH 0 lw'ataagu .
PFX FH 0 lw'ataagi .
PFX FH 0 lw'ataazi .
PFX FH 0 lw'ataaki .
PFX FH 0 lw'ataabi .
PFX FH 0 lw'ataali .
PFX FH 0 lw'ataaga .
PFX FH 0 lw'ataaka .
PFX FH 0 lw'ataabu .
PFX FH 0 lw'ataalu .
PFX FH 0 lw'ataaku .
PFX FH 0 lw'ataatu .
PFX FH 0 lw'etaan [^lmnb]
PFX FH l lw'etaand l.[^mn][^u]
PFX FH l lw'etaann l.[mn]
PFX FH w lw'etaamp [w]
PFX FH 0 lw'etaamu .
PFX FH 0 lw'etaaba .
PFX FH 0 lw'etaagu .
PFX FH 0 lw'etaagi .
PFX FH 0 lw'etaazi .
PFX FH 0 lw'etaaki .
PFX FH 0 lw'etaabi .
PFX FH 0 lw'etaali .
PFX FH 0 lw'etaaga .
PFX FH 0 lw'etaaka .
PFX FH 0 lw'etaabu .
PFX FH 0 lw'etaalu .
PFX FH 0 lw'etaaku .
PFX FH 0 lw'etaatu .
PFX FH 0 lwessaaba .
PFX FH 0 lwessaagu .
PFX FH 0 lwessaagi .
PFX FH 0 lwessaazi .
PFX FH 0 lwessaaki .
PFX FH 0 lwessaabi .
PFX FH 0 lwessaali .
PFX FH 0 lwessaaga .
PFX FH 0 lwessaaka .
PFX FH 0 lwessaabu .
PFX FH 0 lwessaalu .
PFX FH 0 lwessaaku .
PFX FH 0 lwessaatu .
PFX FH 0 lwessaamu .
PFX FH 0 lwetutaan [^lmnb]
PFX FH l lwetutaand l.[^mn][^u]
PFX FH l lwetutaann l.[mn]
PFX FH w lwetutaamp [w]
PFX FH 0 lwetutaamu .
PFX FH 0 lwetutaaba .
PFX FH 0 lwetutaagu .
PFX FH 0 lwetutaagi .
PFX FH 0 lwetutaazi .
PFX FH 0 lwetutaaki .
PFX FH 0 lwetutaabi .
PFX FH 0 lwetutaali .
PFX FH 0 lwetutaaga .
PFX FH 0 lwetutaaka .
PFX FH 0 lwetutaabu .
PFX FH 0 lwetutaalu .
PFX FH 0 lwetutaaku .
PFX FH 0 lwetutaatu .
PFX FH 0 lwemutaan [^lmnb]
PFX FH l lwemutaand l.[^mn][^u]
PFX FH l lwemutaann l.[mn]
PFX FH w lwemutaamp [w]
PFX FH 0 lwemutaamu .
PFX FH 0 lwemutaaba .
PFX FH 0 lwemutaagu .
PFX FH 0 lwemutaagi .
PFX FH 0 lwemutaazi .
PFX FH 0 lwemutaaki .
PFX FH 0 lwemutaabi .
PFX FH 0 lwemutaali .
PFX FH 0 lwemutaaga .
PFX FH 0 lwemutaaka .
PFX FH 0 lwemutaabu .
PFX FH 0 lwemutaalu .
PFX FH 0 lwemutaaku .
PFX FH 0 lwemutaatu .
PFX FH 0 lwebataan [^lmnb]
PFX FH l lwebataand l.[^mn][^u]
PFX FH l lwebataann l.[mn]
PFX FH w lwebataamp [w]
PFX FH 0 lwebataamu .
PFX FH 0 lwebataaba .
PFX FH 0 lwebataagu .
PFX FH 0 lwebataagi .
PFX FH 0 lwebataazi .
PFX FH 0 lwebataaki .
PFX FH 0 lwebataabi .
PFX FH 0 lwebataali .
PFX FH 0 lwebataaga .
PFX FH 0 lwebataaka .
PFX FH 0 lwebataabu .
PFX FH 0 lwebataalu .
PFX FH 0 lwebataaku .
PFX FH 0 lwebataatu .
PFX FH 0 lwegutaan [^lmnb]
PFX FH l lwegutaand l.[^mn][^u]
PFX FH l lwegutaann l.[mn]
PFX FH w lwegutaamp [w]
PFX FH 0 lwegutaamu .
PFX FH 0 lwegutaaba .
PFX FH 0 lwegutaagu .
PFX FH 0 lwegutaagi .
PFX FH 0 lwegutaazi .
PFX FH 0 lwegutaaki .
PFX FH 0 lwegutaabi .
PFX FH 0 lwegutaali .
PFX FH 0 lwegutaaga .
PFX FH 0 lwegutaaka .
PFX FH 0 lwegutaabu .
PFX FH 0 lwegutaalu .
PFX FH 0 lwegutaaku .
PFX FH 0 lwegutaatu .
PFX FH 0 lwegitaan [^lmnb]
PFX FH l lwegitaand l.[^mn][^u]
PFX FH l lwegitaann l.[mn]
PFX FH w lwegitaamp [w]
PFX FH 0 lwegitaamu .
PFX FH 0 lwegitaaba .
PFX FH 0 lwegitaagu .
PFX FH 0 lwegitaagi .
PFX FH 0 lwegitaazi .
PFX FH 0 lwegitaaki .
PFX FH 0 lwegitaabi .
PFX FH 0 lwegitaali .
PFX FH 0 lwegitaaga .
PFX FH 0 lwegitaaka .
PFX FH 0 lwegitaabu .
PFX FH 0 lwegitaalu .
PFX FH 0 lwegitaaku .
PFX FH 0 lwegitaatu .
PFX FH 0 lwezitaan [^lmnb]
PFX FH l lwezitaand l.[^mn][^u]
PFX FH l lwezitaann l.[mn]
PFX FH w lwezitaamp [w]
PFX FH 0 lwezitaamu .
PFX FH 0 lwezitaaba .
PFX FH 0 lwezitaagu .
PFX FH 0 lwezitaagi .
PFX FH 0 lwezitaazi .
PFX FH 0 lwezitaaki .
PFX FH 0 lwezitaabi .
PFX FH 0 lwezitaali .
PFX FH 0 lwezitaaga .
PFX FH 0 lwezitaaka .
PFX FH 0 lwezitaabu .
PFX FH 0 lwezitaalu .
PFX FH 0 lwezitaaku .
PFX FH 0 lwezitaatu .
PFX FH 0 lwekitaan [^lmnb]
PFX FH l lwekitaand l.[^mn][^u]
PFX FH l lwekitaann l.[mn]
PFX FH w lwekitaamp [w]
PFX FH 0 lwekitaamu .
PFX FH 0 lwekitaaba .
PFX FH 0 lwekitaagu .
PFX FH 0 lwekitaagi .
PFX FH 0 lwekitaazi .
PFX FH 0 lwekitaaki .
PFX FH 0 lwekitaabi .
PFX FH 0 lwekitaali .
PFX FH 0 lwekitaaga .
PFX FH 0 lwekitaaka .
PFX FH 0 lwekitaabu .
PFX FH 0 lwekitaalu .
PFX FH 0 lwekitaaku .
PFX FH 0 lwekitaatu .
PFX FH 0 lwebitaan [^lmnb]
PFX FH l lwebitaand l.[^mn][^u]
PFX FH l lwebitaann l.[mn]
PFX FH w lwebitaamp [w]
PFX FH 0 lwebitaamu .
PFX FH 0 lwebitaaba .
PFX FH 0 lwebitaagu .
PFX FH 0 lwebitaagi .
PFX FH 0 lwebitaazi .
PFX FH 0 lwebitaaki .
PFX FH 0 lwebitaabi .
PFX FH 0 lwebitaali .
PFX FH 0 lwebitaaga .
PFX FH 0 lwebitaaka .
PFX FH 0 lwebitaabu .
PFX FH 0 lwebitaalu .
PFX FH 0 lwebitaaku .
PFX FH 0 lwebitaatu .
PFX FH 0 lwelitaan [^lmnb]
PFX FH l lwelitaand l.[^mn][^u]
PFX FH l lwelitaann l.[mn]
PFX FH w lwelitaamp [w]
PFX FH 0 lwelitaamu .
PFX FH 0 lwelitaaba .
PFX FH 0 lwelitaagu .
PFX FH 0 lwelitaagi .
PFX FH 0 lwelitaazi .
PFX FH 0 lwelitaaki .
PFX FH 0 lwelitaabi .
PFX FH 0 lwelitaali .
PFX FH 0 lwelitaaga .
PFX FH 0 lwelitaaka .
PFX FH 0 lwelitaabu .
PFX FH 0 lwelitaalu .
PFX FH 0 lwelitaaku .
PFX FH 0 lwelitaatu .
PFX FH 0 lwegataan [^lmnb]
PFX FH l lwegataand l.[^mn][^u]
PFX FH l lwegataann l.[mn]
PFX FH w lwegataamp [w]
PFX FH 0 lwegataamu .
PFX FH 0 lwegataaba .
PFX FH 0 lwegataagu .
PFX FH 0 lwegataagi .
PFX FH 0 lwegataazi .
PFX FH 0 lwegataaki .
PFX FH 0 lwegataabi .
PFX FH 0 lwegataali .
PFX FH 0 lwegataaga .
PFX FH 0 lwegataaka .
PFX FH 0 lwegataabu .
PFX FH 0 lwegataalu .
PFX FH 0 lwegataaku .
PFX FH 0 lwegataatu .
PFX FH 0 lwekataan [^lmnb]
PFX FH l lwekataand l.[^mn][^u]
PFX FH l lwekataann l.[mn]
PFX FH w lwekataamp [w]
PFX FH 0 lwekataamu .
PFX FH 0 lwekataaba .
PFX FH 0 lwekataagu .
PFX FH 0 lwekataagi .
PFX FH 0 lwekataazi .
PFX FH 0 lwekataaki .
PFX FH 0 lwekataabi .
PFX FH 0 lwekataali .
PFX FH 0 lwekataaga .
PFX FH 0 lwekataaka .
PFX FH 0 lwekataabu .
PFX FH 0 lwekataalu .
PFX FH 0 lwekataaku .
PFX FH 0 lwekataatu .
PFX FH 0 lwebutaan [^lmnb]
PFX FH l lwebutaand l.[^mn][^u]
PFX FH l lwebutaann l.[mn]
PFX FH w lwebutaamp [w]
PFX FH 0 lwebutaamu .
PFX FH 0 lwebutaaba .
PFX FH 0 lwebutaagu .
PFX FH 0 lwebutaagi .
PFX FH 0 lwebutaazi .
PFX FH 0 lwebutaaki .
PFX FH 0 lwebutaabi .
PFX FH 0 lwebutaali .
PFX FH 0 lwebutaaga .
PFX FH 0 lwebutaaka .
PFX FH 0 lwebutaabu .
PFX FH 0 lwebutaalu .
PFX FH 0 lwebutaaku .
PFX FH 0 lwebutaatu .
PFX FH 0 lwelutaan [^lmnb]
PFX FH l lwelutaand l.[^mn][^u]
PFX FH l lwelutaann l.[mn]
PFX FH w lwelutaamp [w]
PFX FH 0 lwelutaamu .
PFX FH 0 lwelutaaba .
PFX FH 0 lwelutaagu .
PFX FH 0 lwelutaagi .
PFX FH 0 lwelutaazi .
PFX FH 0 lwelutaaki .
PFX FH 0 lwelutaabi .
PFX FH 0 lwelutaali .
PFX FH 0 lwelutaaga .
PFX FH 0 lwelutaaka .
PFX FH 0 lwelutaabu .
PFX FH 0 lwelutaalu .
PFX FH 0 lwelutaaku .
PFX FH 0 lwelutaatu .
PFX FH 0 lwekutaan [^lmnb]
PFX FH l lwekutaand l.[^mn][^u]
PFX FH l lwekutaann l.[mn]
PFX FH w lwekutaamp [w]
PFX FH 0 lwekutaamu .
PFX FH 0 lwekutaaba .
PFX FH 0 lwekutaagu .
PFX FH 0 lwekutaagi .
PFX FH 0 lwekutaazi .
PFX FH 0 lwekutaaki .
PFX FH 0 lwekutaabi .
PFX FH 0 lwekutaali .
PFX FH 0 lwekutaaga .
PFX FH 0 lwekutaaka .
PFX FH 0 lwekutaabu .
PFX FH 0 lwekutaalu .
PFX FH 0 lwekutaaku .
PFX FH 0 lwekutaatu .
PFX FH 0 lwetutaan [^lmnb]
PFX FH l lwetutaand l.[^mn][^u]
PFX FH l lwetutaann l.[mn]
PFX FH w lwetutaamp [w]
PFX FH 0 lwetutaamu .
PFX FH 0 lwetutaaba .
PFX FH 0 lwetutaagu .
PFX FH 0 lwetutaagi .
PFX FH 0 lwetutaazi .
PFX FH 0 lwetutaaki .
PFX FH 0 lwetutaabi .
PFX FH 0 lwetutaali .
PFX FH 0 lwetutaaga .
PFX FH 0 lwetutaaka .
PFX FH 0 lwetutaabu .
PFX FH 0 lwetutaalu .
PFX FH 0 lwetutaaku .
PFX FH 0 lwetutaatu .
PFX FH 0 lwessaaba .
PFX FH 0 lwessaagu .
PFX FH 0 lwessaagi .
PFX FH 0 lwessaazi .
PFX FH 0 lwessaaki .
PFX FH 0 lwessaabi .
PFX FH 0 lwessaali .
PFX FH 0 lwessaaga .
PFX FH 0 lwessaaka .
PFX FH 0 lwessaabu .
PFX FH 0 lwessaalu .
PFX FH 0 lwessaaku .
PFX FH 0 lwessaatu .
PFX FH 0 lwessaamu .
PFX FH 0 z'otaan [^lmnb]
PFX FH l z'otaand l.[^mn][^u]
PFX FH l z'otaann l.[mn]
PFX FH w z'otaamp [w]
PFX FH 0 z'otaamu .
PFX FH 0 z'otaaba .
PFX FH 0 z'otaagu .
PFX FH 0 z'otaagi .
PFX FH 0 z'otaazi .
PFX FH 0 z'otaaki .
PFX FH 0 z'otaabi .
PFX FH 0 z'otaali .
PFX FH 0 z'otaaga .
PFX FH 0 z'otaaka .
PFX FH 0 z'otaabu .
PFX FH 0 z'otaalu .
PFX FH 0 z'otaaku .
PFX FH 0 z'otaatu .
PFX FH 0 z'ataan [^lmnb]
PFX FH l z'ataand l.[^mn][^u]
PFX FH l z'ataann l.[mn]
PFX FH w z'ataamp [w]
PFX FH 0 z'ataamu .
PFX FH 0 z'ataaba .
PFX FH 0 z'ataagu .
PFX FH 0 z'ataagi .
PFX FH 0 z'ataazi .
PFX FH 0 z'ataaki .
PFX FH 0 z'ataabi .
PFX FH 0 z'ataali .
PFX FH 0 z'ataaga .
PFX FH 0 z'ataaka .
PFX FH 0 z'ataabu .
PFX FH 0 z'ataalu .
PFX FH 0 z'ataaku .
PFX FH 0 z'ataatu .
PFX FH 0 z'etaan [^lmnb]
PFX FH l z'etaand l.[^mn][^u]
PFX FH l z'etaann l.[mn]
PFX FH w z'etaamp [w]
PFX FH 0 z'etaamu .
PFX FH 0 z'etaaba .
PFX FH 0 z'etaagu .
PFX FH 0 z'etaagi .
PFX FH 0 z'etaazi .
PFX FH 0 z'etaaki .
PFX FH 0 z'etaabi .
PFX FH 0 z'etaali .
PFX FH 0 z'etaaga .
PFX FH 0 z'etaaka .
PFX FH 0 z'etaabu .
PFX FH 0 z'etaalu .
PFX FH 0 z'etaaku .
PFX FH 0 z'etaatu .
PFX FH 0 zessaaba .
PFX FH 0 zessaagu .
PFX FH 0 zessaagi .
PFX FH 0 zessaazi .
PFX FH 0 zessaaki .
PFX FH 0 zessaabi .
PFX FH 0 zessaali .
PFX FH 0 zessaaga .
PFX FH 0 zessaaka .
PFX FH 0 zessaabu .
PFX FH 0 zessaalu .
PFX FH 0 zessaaku .
PFX FH 0 zessaatu .
PFX FH 0 zessaamu .
PFX FH 0 zetutaan [^lmnb]
PFX FH l zetutaand l.[^mn][^u]
PFX FH l zetutaann l.[mn]
PFX FH w zetutaamp [w]
PFX FH 0 zetutaamu .
PFX FH 0 zetutaaba .
PFX FH 0 zetutaagu .
PFX FH 0 zetutaagi .
PFX FH 0 zetutaazi .
PFX FH 0 zetutaaki .
PFX FH 0 zetutaabi .
PFX FH 0 zetutaali .
PFX FH 0 zetutaaga .
PFX FH 0 zetutaaka .
PFX FH 0 zetutaabu .
PFX FH 0 zetutaalu .
PFX FH 0 zetutaaku .
PFX FH 0 zetutaatu .
PFX FH 0 zemutaan [^lmnb]
PFX FH l zemutaand l.[^mn][^u]
PFX FH l zemutaann l.[mn]
PFX FH w zemutaamp [w]
PFX FH 0 zemutaamu .
PFX FH 0 zemutaaba .
PFX FH 0 zemutaagu .
PFX FH 0 zemutaagi .
PFX FH 0 zemutaazi .
PFX FH 0 zemutaaki .
PFX FH 0 zemutaabi .
PFX FH 0 zemutaali .
PFX FH 0 zemutaaga .
PFX FH 0 zemutaaka .
PFX FH 0 zemutaabu .
PFX FH 0 zemutaalu .
PFX FH 0 zemutaaku .
PFX FH 0 zemutaatu .
PFX FH 0 zebataan [^lmnb]
PFX FH l zebataand l.[^mn][^u]
PFX FH l zebataann l.[mn]
PFX FH w zebataamp [w]
PFX FH 0 zebataamu .
PFX FH 0 zebataaba .
PFX FH 0 zebataagu .
PFX FH 0 zebataagi .
PFX FH 0 zebataazi .
PFX FH 0 zebataaki .
PFX FH 0 zebataabi .
PFX FH 0 zebataali .
PFX FH 0 zebataaga .
PFX FH 0 zebataaka .
PFX FH 0 zebataabu .
PFX FH 0 zebataalu .
PFX FH 0 zebataaku .
PFX FH 0 zebataatu .
PFX FH 0 zegutaan [^lmnb]
PFX FH l zegutaand l.[^mn][^u]
PFX FH l zegutaann l.[mn]
PFX FH w zegutaamp [w]
PFX FH 0 zegutaamu .
PFX FH 0 zegutaaba .
PFX FH 0 zegutaagu .
PFX FH 0 zegutaagi .
PFX FH 0 zegutaazi .
PFX FH 0 zegutaaki .
PFX FH 0 zegutaabi .
PFX FH 0 zegutaali .
PFX FH 0 zegutaaga .
PFX FH 0 zegutaaka .
PFX FH 0 zegutaabu .
PFX FH 0 zegutaalu .
PFX FH 0 zegutaaku .
PFX FH 0 zegutaatu .
PFX FH 0 zegitaan [^lmnb]
PFX FH l zegitaand l.[^mn][^u]
PFX FH l zegitaann l.[mn]
PFX FH w zegitaamp [w]
PFX FH 0 zegitaamu .
PFX FH 0 zegitaaba .
PFX FH 0 zegitaagu .
PFX FH 0 zegitaagi .
PFX FH 0 zegitaazi .
PFX FH 0 zegitaaki .
PFX FH 0 zegitaabi .
PFX FH 0 zegitaali .
PFX FH 0 zegitaaga .
PFX FH 0 zegitaaka .
PFX FH 0 zegitaabu .
PFX FH 0 zegitaalu .
PFX FH 0 zegitaaku .
PFX FH 0 zegitaatu .
PFX FH 0 zezitaan [^lmnb]
PFX FH l zezitaand l.[^mn][^u]
PFX FH l zezitaann l.[mn]
PFX FH w zezitaamp [w]
PFX FH 0 zezitaamu .
PFX FH 0 zezitaaba .
PFX FH 0 zezitaagu .
PFX FH 0 zezitaagi .
PFX FH 0 zezitaazi .
PFX FH 0 zezitaaki .
PFX FH 0 zezitaabi .
PFX FH 0 zezitaali .
PFX FH 0 zezitaaga .
PFX FH 0 zezitaaka .
PFX FH 0 zezitaabu .
PFX FH 0 zezitaalu .
PFX FH 0 zezitaaku .
PFX FH 0 zezitaatu .
PFX FH 0 zekitaan [^lmnb]
PFX FH l zekitaand l.[^mn][^u]
PFX FH l zekitaann l.[mn]
PFX FH w zekitaamp [w]
PFX FH 0 zekitaamu .
PFX FH 0 zekitaaba .
PFX FH 0 zekitaagu .
PFX FH 0 zekitaagi .
PFX FH 0 zekitaazi .
PFX FH 0 zekitaaki .
PFX FH 0 zekitaabi .
PFX FH 0 zekitaali .
PFX FH 0 zekitaaga .
PFX FH 0 zekitaaka .
PFX FH 0 zekitaabu .
PFX FH 0 zekitaalu .
PFX FH 0 zekitaaku .
PFX FH 0 zekitaatu .
PFX FH 0 zebitaan [^lmnb]
PFX FH l zebitaand l.[^mn][^u]
PFX FH l zebitaann l.[mn]
PFX FH w zebitaamp [w]
PFX FH 0 zebitaamu .
PFX FH 0 zebitaaba .
PFX FH 0 zebitaagu .
PFX FH 0 zebitaagi .
PFX FH 0 zebitaazi .
PFX FH 0 zebitaaki .
PFX FH 0 zebitaabi .
PFX FH 0 zebitaali .
PFX FH 0 zebitaaga .
PFX FH 0 zebitaaka .
PFX FH 0 zebitaabu .
PFX FH 0 zebitaalu .
PFX FH 0 zebitaaku .
PFX FH 0 zebitaatu .
PFX FH 0 zelitaan [^lmnb]
PFX FH l zelitaand l.[^mn][^u]
PFX FH l zelitaann l.[mn]
PFX FH w zelitaamp [w]
PFX FH 0 zelitaamu .
PFX FH 0 zelitaaba .
PFX FH 0 zelitaagu .
PFX FH 0 zelitaagi .
PFX FH 0 zelitaazi .
PFX FH 0 zelitaaki .
PFX FH 0 zelitaabi .
PFX FH 0 zelitaali .
PFX FH 0 zelitaaga .
PFX FH 0 zelitaaka .
PFX FH 0 zelitaabu .
PFX FH 0 zelitaalu .
PFX FH 0 zelitaaku .
PFX FH 0 zelitaatu .
PFX FH 0 zegataan [^lmnb]
PFX FH l zegataand l.[^mn][^u]
PFX FH l zegataann l.[mn]
PFX FH w zegataamp [w]
PFX FH 0 zegataamu .
PFX FH 0 zegataaba .
PFX FH 0 zegataagu .
PFX FH 0 zegataagi .
PFX FH 0 zegataazi .
PFX FH 0 zegataaki .
PFX FH 0 zegataabi .
PFX FH 0 zegataali .
PFX FH 0 zegataaga .
PFX FH 0 zegataaka .
PFX FH 0 zegataabu .
PFX FH 0 zegataalu .
PFX FH 0 zegataaku .
PFX FH 0 zegataatu .
PFX FH 0 zekataan [^lmnb]
PFX FH l zekataand l.[^mn][^u]
PFX FH l zekataann l.[mn]
PFX FH w zekataamp [w]
PFX FH 0 zekataamu .
PFX FH 0 zekataaba .
PFX FH 0 zekataagu .
PFX FH 0 zekataagi .
PFX FH 0 zekataazi .
PFX FH 0 zekataaki .
PFX FH 0 zekataabi .
PFX FH 0 zekataali .
PFX FH 0 zekataaga .
PFX FH 0 zekataaka .
PFX FH 0 zekataabu .
PFX FH 0 zekataalu .
PFX FH 0 zekataaku .
PFX FH 0 zekataatu .
PFX FH 0 zebutaan [^lmnb]
PFX FH l zebutaand l.[^mn][^u]
PFX FH l zebutaann l.[mn]
PFX FH w zebutaamp [w]
PFX FH 0 zebutaamu .
PFX FH 0 zebutaaba .
PFX FH 0 zebutaagu .
PFX FH 0 zebutaagi .
PFX FH 0 zebutaazi .
PFX FH 0 zebutaaki .
PFX FH 0 zebutaabi .
PFX FH 0 zebutaali .
PFX FH 0 zebutaaga .
PFX FH 0 zebutaaka .
PFX FH 0 zebutaabu .
PFX FH 0 zebutaalu .
PFX FH 0 zebutaaku .
PFX FH 0 zebutaatu .
PFX FH 0 zelutaan [^lmnb]
PFX FH l zelutaand l.[^mn][^u]
PFX FH l zelutaann l.[mn]
PFX FH w zelutaamp [w]
PFX FH 0 zelutaamu .
PFX FH 0 zelutaaba .
PFX FH 0 zelutaagu .
PFX FH 0 zelutaagi .
PFX FH 0 zelutaazi .
PFX FH 0 zelutaaki .
PFX FH 0 zelutaabi .
PFX FH 0 zelutaali .
PFX FH 0 zelutaaga .
PFX FH 0 zelutaaka .
PFX FH 0 zelutaabu .
PFX FH 0 zelutaalu .
PFX FH 0 zelutaaku .
PFX FH 0 zelutaatu .
PFX FH 0 zekutaan [^lmnb]
PFX FH l zekutaand l.[^mn][^u]
PFX FH l zekutaann l.[mn]
PFX FH w zekutaamp [w]
PFX FH 0 zekutaamu .
PFX FH 0 zekutaaba .
PFX FH 0 zekutaagu .
PFX FH 0 zekutaagi .
PFX FH 0 zekutaazi .
PFX FH 0 zekutaaki .
PFX FH 0 zekutaabi .
PFX FH 0 zekutaali .
PFX FH 0 zekutaaga .
PFX FH 0 zekutaaka .
PFX FH 0 zekutaabu .
PFX FH 0 zekutaalu .
PFX FH 0 zekutaaku .
PFX FH 0 zekutaatu .
PFX FH 0 zetutaan [^lmnb]
PFX FH l zetutaand l.[^mn][^u]
PFX FH l zetutaann l.[mn]
PFX FH w zetutaamp [w]
PFX FH 0 zetutaamu .
PFX FH 0 zetutaaba .
PFX FH 0 zetutaagu .
PFX FH 0 zetutaagi .
PFX FH 0 zetutaazi .
PFX FH 0 zetutaaki .
PFX FH 0 zetutaabi .
PFX FH 0 zetutaali .
PFX FH 0 zetutaaga .
PFX FH 0 zetutaaka .
PFX FH 0 zetutaabu .
PFX FH 0 zetutaalu .
PFX FH 0 zetutaaku .
PFX FH 0 zetutaatu .
PFX FH 0 gw'otaan [^lmnb]
PFX FH l gw'otaand l.[^mn][^u]
PFX FH l gw'otaann l.[mn]
PFX FH w gw'otaamp [w]
PFX FH 0 gw'otaamu .
PFX FH 0 gw'otaaba .
PFX FH 0 gw'otaagu .
PFX FH 0 gw'otaagi .
PFX FH 0 gw'otaazi .
PFX FH 0 gw'otaaki .
PFX FH 0 gw'otaabi .
PFX FH 0 gw'otaali .
PFX FH 0 gw'otaaga .
PFX FH 0 gw'otaaka .
PFX FH 0 gw'otaabu .
PFX FH 0 gw'otaalu .
PFX FH 0 gw'otaaku .
PFX FH 0 gw'otaatu .
PFX FH 0 gw'ataan [^lmnb]
PFX FH l gw'ataand l.[^mn][^u]
PFX FH l gw'ataann l.[mn]
PFX FH w gw'ataamp [w]
PFX FH 0 gw'ataamu .
PFX FH 0 gw'ataaba .
PFX FH 0 gw'ataagu .
PFX FH 0 gw'ataagi .
PFX FH 0 gw'ataazi .
PFX FH 0 gw'ataaki .
PFX FH 0 gw'ataabi .
PFX FH 0 gw'ataali .
PFX FH 0 gw'ataaga .
PFX FH 0 gw'ataaka .
PFX FH 0 gw'ataabu .
PFX FH 0 gw'ataalu .
PFX FH 0 gw'ataaku .
PFX FH 0 gw'ataatu .
PFX FH 0 gw'etaan [^lmnb]
PFX FH l gw'etaand l.[^mn][^u]
PFX FH l gw'etaann l.[mn]
PFX FH w gw'etaamp [w]
PFX FH 0 gw'etaamu .
PFX FH 0 gw'etaaba .
PFX FH 0 gw'etaagu .
PFX FH 0 gw'etaagi .
PFX FH 0 gw'etaazi .
PFX FH 0 gw'etaaki .
PFX FH 0 gw'etaabi .
PFX FH 0 gw'etaali .
PFX FH 0 gw'etaaga .
PFX FH 0 gw'etaaka .
PFX FH 0 gw'etaabu .
PFX FH 0 gw'etaalu .
PFX FH 0 gw'etaaku .
PFX FH 0 gw'etaatu .
PFX FH 0 gwessaaba .
PFX FH 0 gwessaagu .
PFX FH 0 gwessaagi .
PFX FH 0 gwessaazi .
PFX FH 0 gwessaaki .
PFX FH 0 gwessaabi .
PFX FH 0 gwessaali .
PFX FH 0 gwessaaga .
PFX FH 0 gwessaaka .
PFX FH 0 gwessaabu .
PFX FH 0 gwessaalu .
PFX FH 0 gwessaaku .
PFX FH 0 gwessaatu .
PFX FH 0 gwessaamu .
PFX FH 0 gwetutaan [^lmnb]
PFX FH l gwetutaand l.[^mn][^u]
PFX FH l gwetutaann l.[mn]
PFX FH w gwetutaamp [w]
PFX FH 0 gwetutaamu .
PFX FH 0 gwetutaaba .
PFX FH 0 gwetutaagu .
PFX FH 0 gwetutaagi .
PFX FH 0 gwetutaazi .
PFX FH 0 gwetutaaki .
PFX FH 0 gwetutaabi .
PFX FH 0 gwetutaali .
PFX FH 0 gwetutaaga .
PFX FH 0 gwetutaaka .
PFX FH 0 gwetutaabu .
PFX FH 0 gwetutaalu .
PFX FH 0 gwetutaaku .
PFX FH 0 gwetutaatu .
PFX FH 0 gwemutaan [^lmnb]
PFX FH l gwemutaand l.[^mn][^u]
PFX FH l gwemutaann l.[mn]
PFX FH w gwemutaamp [w]
PFX FH 0 gwemutaamu .
PFX FH 0 gwemutaaba .
PFX FH 0 gwemutaagu .
PFX FH 0 gwemutaagi .
PFX FH 0 gwemutaazi .
PFX FH 0 gwemutaaki .
PFX FH 0 gwemutaabi .
PFX FH 0 gwemutaali .
PFX FH 0 gwemutaaga .
PFX FH 0 gwemutaaka .
PFX FH 0 gwemutaabu .
PFX FH 0 gwemutaalu .
PFX FH 0 gwemutaaku .
PFX FH 0 gwemutaatu .
PFX FH 0 gwebataan [^lmnb]
PFX FH l gwebataand l.[^mn][^u]
PFX FH l gwebataann l.[mn]
PFX FH w gwebataamp [w]
PFX FH 0 gwebataamu .
PFX FH 0 gwebataaba .
PFX FH 0 gwebataagu .
PFX FH 0 gwebataagi .
PFX FH 0 gwebataazi .
PFX FH 0 gwebataaki .
PFX FH 0 gwebataabi .
PFX FH 0 gwebataali .
PFX FH 0 gwebataaga .
PFX FH 0 gwebataaka .
PFX FH 0 gwebataabu .
PFX FH 0 gwebataalu .
PFX FH 0 gwebataaku .
PFX FH 0 gwebataatu .
PFX FH 0 gwegutaan [^lmnb]
PFX FH l gwegutaand l.[^mn][^u]
PFX FH l gwegutaann l.[mn]
PFX FH w gwegutaamp [w]
PFX FH 0 gwegutaamu .
PFX FH 0 gwegutaaba .
PFX FH 0 gwegutaagu .
PFX FH 0 gwegutaagi .
PFX FH 0 gwegutaazi .
PFX FH 0 gwegutaaki .
PFX FH 0 gwegutaabi .
PFX FH 0 gwegutaali .
PFX FH 0 gwegutaaga .
PFX FH 0 gwegutaaka .
PFX FH 0 gwegutaabu .
PFX FH 0 gwegutaalu .
PFX FH 0 gwegutaaku .
PFX FH 0 gwegutaatu .
PFX FH 0 gwegitaan [^lmnb]
PFX FH l gwegitaand l.[^mn][^u]
PFX FH l gwegitaann l.[mn]
PFX FH w gwegitaamp [w]
PFX FH 0 gwegitaamu .
PFX FH 0 gwegitaaba .
PFX FH 0 gwegitaagu .
PFX FH 0 gwegitaagi .
PFX FH 0 gwegitaazi .
PFX FH 0 gwegitaaki .
PFX FH 0 gwegitaabi .
PFX FH 0 gwegitaali .
PFX FH 0 gwegitaaga .
PFX FH 0 gwegitaaka .
PFX FH 0 gwegitaabu .
PFX FH 0 gwegitaalu .
PFX FH 0 gwegitaaku .
PFX FH 0 gwegitaatu .
PFX FH 0 gwezitaan [^lmnb]
PFX FH l gwezitaand l.[^mn][^u]
PFX FH l gwezitaann l.[mn]
PFX FH w gwezitaamp [w]
PFX FH 0 gwezitaamu .
PFX FH 0 gwezitaaba .
PFX FH 0 gwezitaagu .
PFX FH 0 gwezitaagi .
PFX FH 0 gwezitaazi .
PFX FH 0 gwezitaaki .
PFX FH 0 gwezitaabi .
PFX FH 0 gwezitaali .
PFX FH 0 gwezitaaga .
PFX FH 0 gwezitaaka .
PFX FH 0 gwezitaabu .
PFX FH 0 gwezitaalu .
PFX FH 0 gwezitaaku .
PFX FH 0 gwezitaatu .
PFX FH 0 gwekitaan [^lmnb]
PFX FH l gwekitaand l.[^mn][^u]
PFX FH l gwekitaann l.[mn]
PFX FH w gwekitaamp [w]
PFX FH 0 gwekitaamu .
PFX FH 0 gwekitaaba .
PFX FH 0 gwekitaagu .
PFX FH 0 gwekitaagi .
PFX FH 0 gwekitaazi .
PFX FH 0 gwekitaaki .
PFX FH 0 gwekitaabi .
PFX FH 0 gwekitaali .
PFX FH 0 gwekitaaga .
PFX FH 0 gwekitaaka .
PFX FH 0 gwekitaabu .
PFX FH 0 gwekitaalu .
PFX FH 0 gwekitaaku .
PFX FH 0 gwekitaatu .
PFX FH 0 gwebitaan [^lmnb]
PFX FH l gwebitaand l.[^mn][^u]
PFX FH l gwebitaann l.[mn]
PFX FH w gwebitaamp [w]
PFX FH 0 gwebitaamu .
PFX FH 0 gwebitaaba .
PFX FH 0 gwebitaagu .
PFX FH 0 gwebitaagi .
PFX FH 0 gwebitaazi .
PFX FH 0 gwebitaaki .
PFX FH 0 gwebitaabi .
PFX FH 0 gwebitaali .
PFX FH 0 gwebitaaga .
PFX FH 0 gwebitaaka .
PFX FH 0 gwebitaabu .
PFX FH 0 gwebitaalu .
PFX FH 0 gwebitaaku .
PFX FH 0 gwebitaatu .
PFX FH 0 gwelitaan [^lmnb]
PFX FH l gwelitaand l.[^mn][^u]
PFX FH l gwelitaann l.[mn]
PFX FH w gwelitaamp [w]
PFX FH 0 gwelitaamu .
PFX FH 0 gwelitaaba .
PFX FH 0 gwelitaagu .
PFX FH 0 gwelitaagi .
PFX FH 0 gwelitaazi .
PFX FH 0 gwelitaaki .
PFX FH 0 gwelitaabi .
PFX FH 0 gwelitaali .
PFX FH 0 gwelitaaga .
PFX FH 0 gwelitaaka .
PFX FH 0 gwelitaabu .
PFX FH 0 gwelitaalu .
PFX FH 0 gwelitaaku .
PFX FH 0 gwelitaatu .
PFX FH 0 gwegataan [^lmnb]
PFX FH l gwegataand l.[^mn][^u]
PFX FH l gwegataann l.[mn]
PFX FH w gwegataamp [w]
PFX FH 0 gwegataamu .
PFX FH 0 gwegataaba .
PFX FH 0 gwegataagu .
PFX FH 0 gwegataagi .
PFX FH 0 gwegataazi .
PFX FH 0 gwegataaki .
PFX FH 0 gwegataabi .
PFX FH 0 gwegataali .
PFX FH 0 gwegataaga .
PFX FH 0 gwegataaka .
PFX FH 0 gwegataabu .
PFX FH 0 gwegataalu .
PFX FH 0 gwegataaku .
PFX FH 0 gwegataatu .
PFX FH 0 gwekataan [^lmnb]
PFX FH l gwekataand l.[^mn][^u]
PFX FH l gwekataann l.[mn]
PFX FH w gwekataamp [w]
PFX FH 0 gwekataamu .
PFX FH 0 gwekataaba .
PFX FH 0 gwekataagu .
PFX FH 0 gwekataagi .
PFX FH 0 gwekataazi .
PFX FH 0 gwekataaki .
PFX FH 0 gwekataabi .
PFX FH 0 gwekataali .
PFX FH 0 gwekataaga .
PFX FH 0 gwekataaka .
PFX FH 0 gwekataabu .
PFX FH 0 gwekataalu .
PFX FH 0 gwekataaku .
PFX FH 0 gwekataatu .
PFX FH 0 gwebutaan [^lmnb]
PFX FH l gwebutaand l.[^mn][^u]
PFX FH l gwebutaann l.[mn]
PFX FH w gwebutaamp [w]
PFX FH 0 gwebutaamu .
PFX FH 0 gwebutaaba .
PFX FH 0 gwebutaagu .
PFX FH 0 gwebutaagi .
PFX FH 0 gwebutaazi .
PFX FH 0 gwebutaaki .
PFX FH 0 gwebutaabi .
PFX FH 0 gwebutaali .
PFX FH 0 gwebutaaga .
PFX FH 0 gwebutaaka .
PFX FH 0 gwebutaabu .
PFX FH 0 gwebutaalu .
PFX FH 0 gwebutaaku .
PFX FH 0 gwebutaatu .
PFX FH 0 gwelutaan [^lmnb]
PFX FH l gwelutaand l.[^mn][^u]
PFX FH l gwelutaann l.[mn]
PFX FH w gwelutaamp [w]
PFX FH 0 gwelutaamu .
PFX FH 0 gwelutaaba .
PFX FH 0 gwelutaagu .
PFX FH 0 gwelutaagi .
PFX FH 0 gwelutaazi .
PFX FH 0 gwelutaaki .
PFX FH 0 gwelutaabi .
PFX FH 0 gwelutaali .
PFX FH 0 gwelutaaga .
PFX FH 0 gwelutaaka .
PFX FH 0 gwelutaabu .
PFX FH 0 gwelutaalu .
PFX FH 0 gwelutaaku .
PFX FH 0 gwelutaatu .
PFX FH 0 gwekutaan [^lmnb]
PFX FH l gwekutaand l.[^mn][^u]
PFX FH l gwekutaann l.[mn]
PFX FH w gwekutaamp [w]
PFX FH 0 gwekutaamu .
PFX FH 0 gwekutaaba .
PFX FH 0 gwekutaagu .
PFX FH 0 gwekutaagi .
PFX FH 0 gwekutaazi .
PFX FH 0 gwekutaaki .
PFX FH 0 gwekutaabi .
PFX FH 0 gwekutaali .
PFX FH 0 gwekutaaga .
PFX FH 0 gwekutaaka .
PFX FH 0 gwekutaabu .
PFX FH 0 gwekutaalu .
PFX FH 0 gwekutaaku .
PFX FH 0 gwekutaatu .
PFX FH 0 gwetutaan [^lmnb]
PFX FH l gwetutaand l.[^mn][^u]
PFX FH l gwetutaann l.[mn]
PFX FH w gwetutaamp [w]
PFX FH 0 gwetutaamu .
PFX FH 0 gwetutaaba .
PFX FH 0 gwetutaagu .
PFX FH 0 gwetutaagi .
PFX FH 0 gwetutaazi .
PFX FH 0 gwetutaaki .
PFX FH 0 gwetutaabi .
PFX FH 0 gwetutaali .
PFX FH 0 gwetutaaga .
PFX FH 0 gwetutaaka .
PFX FH 0 gwetutaabu .
PFX FH 0 gwetutaalu .
PFX FH 0 gwetutaaku .
PFX FH 0 gwetutaatu .
PFX FH 0 gy'otaan [^lmnb]
PFX FH l gy'otaand l.[^mn][^u]
PFX FH l gy'otaann l.[mn]
PFX FH w gy'otaamp [w]
PFX FH 0 gy'otaamu .
PFX FH 0 gy'otaaba .
PFX FH 0 gy'otaagu .
PFX FH 0 gy'otaagi .
PFX FH 0 gy'otaazi .
PFX FH 0 gy'otaaki .
PFX FH 0 gy'otaabi .
PFX FH 0 gy'otaali .
PFX FH 0 gy'otaaga .
PFX FH 0 gy'otaaka .
PFX FH 0 gy'otaabu .
PFX FH 0 gy'otaalu .
PFX FH 0 gy'otaaku .
PFX FH 0 gy'otaatu .
PFX FH 0 gy'ataan [^lmnb]
PFX FH l gy'ataand l.[^mn][^u]
PFX FH l gy'ataann l.[mn]
PFX FH w gy'ataamp [w]
PFX FH 0 gy'ataamu .
PFX FH 0 gy'ataaba .
PFX FH 0 gy'ataagu .
PFX FH 0 gy'ataagi .
PFX FH 0 gy'ataazi .
PFX FH 0 gy'ataaki .
PFX FH 0 gy'ataabi .
PFX FH 0 gy'ataali .
PFX FH 0 gy'ataaga .
PFX FH 0 gy'ataaka .
PFX FH 0 gy'ataabu .
PFX FH 0 gy'ataalu .
PFX FH 0 gy'ataaku .
PFX FH 0 gy'ataatu .
PFX FH 0 gy'etaan [^lmnb]
PFX FH l gy'etaand l.[^mn][^u]
PFX FH l gy'etaann l.[mn]
PFX FH w gy'etaamp [w]
PFX FH 0 gy'etaamu .
PFX FH 0 gy'etaaba .
PFX FH 0 gy'etaagu .
PFX FH 0 gy'etaagi .
PFX FH 0 gy'etaazi .
PFX FH 0 gy'etaaki .
PFX FH 0 gy'etaabi .
PFX FH 0 gy'etaali .
PFX FH 0 gy'etaaga .
PFX FH 0 gy'etaaka .
PFX FH 0 gy'etaabu .
PFX FH 0 gy'etaalu .
PFX FH 0 gy'etaaku .
PFX FH 0 gy'etaatu .
PFX FH 0 gyessaaba .
PFX FH 0 gyessaagu .
PFX FH 0 gyessaagi .
PFX FH 0 gyessaazi .
PFX FH 0 gyessaaki .
PFX FH 0 gyessaabi .
PFX FH 0 gyessaali .
PFX FH 0 gyessaaga .
PFX FH 0 gyessaaka .
PFX FH 0 gyessaabu .
PFX FH 0 gyessaalu .
PFX FH 0 gyessaaku .
PFX FH 0 gyessaatu .
PFX FH 0 gyessaamu .
PFX FH 0 gyetutaan [^lmnb]
PFX FH l gyetutaand l.[^mn][^u]
PFX FH l gyetutaann l.[mn]
PFX FH w gyetutaamp [w]
PFX FH 0 gyetutaamu .
PFX FH 0 gyetutaaba .
PFX FH 0 gyetutaagu .
PFX FH 0 gyetutaagi .
PFX FH 0 gyetutaazi .
PFX FH 0 gyetutaaki .
PFX FH 0 gyetutaabi .
PFX FH 0 gyetutaali .
PFX FH 0 gyetutaaga .
PFX FH 0 gyetutaaka .
PFX FH 0 gyetutaabu .
PFX FH 0 gyetutaalu .
PFX FH 0 gyetutaaku .
PFX FH 0 gyetutaatu .
PFX FH 0 gyemutaan [^lmnb]
PFX FH l gyemutaand l.[^mn][^u]
PFX FH l gyemutaann l.[mn]
PFX FH w gyemutaamp [w]
PFX FH 0 gyemutaamu .
PFX FH 0 gyemutaaba .
PFX FH 0 gyemutaagu .
PFX FH 0 gyemutaagi .
PFX FH 0 gyemutaazi .
PFX FH 0 gyemutaaki .
PFX FH 0 gyemutaabi .
PFX FH 0 gyemutaali .
PFX FH 0 gyemutaaga .
PFX FH 0 gyemutaaka .
PFX FH 0 gyemutaabu .
PFX FH 0 gyemutaalu .
PFX FH 0 gyemutaaku .
PFX FH 0 gyemutaatu .
PFX FH 0 gyebataan [^lmnb]
PFX FH l gyebataand l.[^mn][^u]
PFX FH l gyebataann l.[mn]
PFX FH w gyebataamp [w]
PFX FH 0 gyebataamu .
PFX FH 0 gyebataaba .
PFX FH 0 gyebataagu .
PFX FH 0 gyebataagi .
PFX FH 0 gyebataazi .
PFX FH 0 gyebataaki .
PFX FH 0 gyebataabi .
PFX FH 0 gyebataali .
PFX FH 0 gyebataaga .
PFX FH 0 gyebataaka .
PFX FH 0 gyebataabu .
PFX FH 0 gyebataalu .
PFX FH 0 gyebataaku .
PFX FH 0 gyebataatu .
PFX FH 0 gyegutaan [^lmnb]
PFX FH l gyegutaand l.[^mn][^u]
PFX FH l gyegutaann l.[mn]
PFX FH w gyegutaamp [w]
PFX FH 0 gyegutaamu .
PFX FH 0 gyegutaaba .
PFX FH 0 gyegutaagu .
PFX FH 0 gyegutaagi .
PFX FH 0 gyegutaazi .
PFX FH 0 gyegutaaki .
PFX FH 0 gyegutaabi .
PFX FH 0 gyegutaali .
PFX FH 0 gyegutaaga .
PFX FH 0 gyegutaaka .
PFX FH 0 gyegutaabu .
PFX FH 0 gyegutaalu .
PFX FH 0 gyegutaaku .
PFX FH 0 gyegutaatu .
PFX FH 0 gyegitaan [^lmnb]
PFX FH l gyegitaand l.[^mn][^u]
PFX FH l gyegitaann l.[mn]
PFX FH w gyegitaamp [w]
PFX FH 0 gyegitaamu .
PFX FH 0 gyegitaaba .
PFX FH 0 gyegitaagu .
PFX FH 0 gyegitaagi .
PFX FH 0 gyegitaazi .
PFX FH 0 gyegitaaki .
PFX FH 0 gyegitaabi .
PFX FH 0 gyegitaali .
PFX FH 0 gyegitaaga .
PFX FH 0 gyegitaaka .
PFX FH 0 gyegitaabu .
PFX FH 0 gyegitaalu .
PFX FH 0 gyegitaaku .
PFX FH 0 gyegitaatu .
PFX FH 0 gyezitaan [^lmnb]
PFX FH l gyezitaand l.[^mn][^u]
PFX FH l gyezitaann l.[mn]
PFX FH w gyezitaamp [w]
PFX FH 0 gyezitaamu .
PFX FH 0 gyezitaaba .
PFX FH 0 gyezitaagu .
PFX FH 0 gyezitaagi .
PFX FH 0 gyezitaazi .
PFX FH 0 gyezitaaki .
PFX FH 0 gyezitaabi .
PFX FH 0 gyezitaali .
PFX FH 0 gyezitaaga .
PFX FH 0 gyezitaaka .
PFX FH 0 gyezitaabu .
PFX FH 0 gyezitaalu .
PFX FH 0 gyezitaaku .
PFX FH 0 gyezitaatu .
PFX FH 0 gyekitaan [^lmnb]
PFX FH l gyekitaand l.[^mn][^u]
PFX FH l gyekitaann l.[mn]
PFX FH w gyekitaamp [w]
PFX FH 0 gyekitaamu .
PFX FH 0 gyekitaaba .
PFX FH 0 gyekitaagu .
PFX FH 0 gyekitaagi .
PFX FH 0 gyekitaazi .
PFX FH 0 gyekitaaki .
PFX FH 0 gyekitaabi .
PFX FH 0 gyekitaali .
PFX FH 0 gyekitaaga .
PFX FH 0 gyekitaaka .
PFX FH 0 gyekitaabu .
PFX FH 0 gyekitaalu .
PFX FH 0 gyekitaaku .
PFX FH 0 gyekitaatu .
PFX FH 0 gyebitaan [^lmnb]
PFX FH l gyebitaand l.[^mn][^u]
PFX FH l gyebitaann l.[mn]
PFX FH w gyebitaamp [w]
PFX FH 0 gyebitaamu .
PFX FH 0 gyebitaaba .
PFX FH 0 gyebitaagu .
PFX FH 0 gyebitaagi .
PFX FH 0 gyebitaazi .
PFX FH 0 gyebitaaki .
PFX FH 0 gyebitaabi .
PFX FH 0 gyebitaali .
PFX FH 0 gyebitaaga .
PFX FH 0 gyebitaaka .
PFX FH 0 gyebitaabu .
PFX FH 0 gyebitaalu .
PFX FH 0 gyebitaaku .
PFX FH 0 gyebitaatu .
PFX FH 0 gyelitaan [^lmnb]
PFX FH l gyelitaand l.[^mn][^u]
PFX FH l gyelitaann l.[mn]
PFX FH w gyelitaamp [w]
PFX FH 0 gyelitaamu .
PFX FH 0 gyelitaaba .
PFX FH 0 gyelitaagu .
PFX FH 0 gyelitaagi .
PFX FH 0 gyelitaazi .
PFX FH 0 gyelitaaki .
PFX FH 0 gyelitaabi .
PFX FH 0 gyelitaali .
PFX FH 0 gyelitaaga .
PFX FH 0 gyelitaaka .
PFX FH 0 gyelitaabu .
PFX FH 0 gyelitaalu .
PFX FH 0 gyelitaaku .
PFX FH 0 gyelitaatu .
PFX FH 0 gyegataan [^lmnb]
PFX FH l gyegataand l.[^mn][^u]
PFX FH l gyegataann l.[mn]
PFX FH w gyegataamp [w]
PFX FH 0 gyegataamu .
PFX FH 0 gyegataaba .
PFX FH 0 gyegataagu .
PFX FH 0 gyegataagi .
PFX FH 0 gyegataazi .
PFX FH 0 gyegataaki .
PFX FH 0 gyegataabi .
PFX FH 0 gyegataali .
PFX FH 0 gyegataaga .
PFX FH 0 gyegataaka .
PFX FH 0 gyegataabu .
PFX FH 0 gyegataalu .
PFX FH 0 gyegataaku .
PFX FH 0 gyegataatu .
PFX FH 0 gyekataan [^lmnb]
PFX FH l gyekataand l.[^mn][^u]
PFX FH l gyekataann l.[mn]
PFX FH w gyekataamp [w]
PFX FH 0 gyekataamu .
PFX FH 0 gyekataaba .
PFX FH 0 gyekataagu .
PFX FH 0 gyekataagi .
PFX FH 0 gyekataazi .
PFX FH 0 gyekataaki .
PFX FH 0 gyekataabi .
PFX FH 0 gyekataali .
PFX FH 0 gyekataaga .
PFX FH 0 gyekataaka .
PFX FH 0 gyekataabu .
PFX FH 0 gyekataalu .
PFX FH 0 gyekataaku .
PFX FH 0 gyekataatu .
PFX FH 0 gyebutaan [^lmnb]
PFX FH l gyebutaand l.[^mn][^u]
PFX FH l gyebutaann l.[mn]
PFX FH w gyebutaamp [w]
PFX FH 0 gyebutaamu .
PFX FH 0 gyebutaaba .
PFX FH 0 gyebutaagu .
PFX FH 0 gyebutaagi .
PFX FH 0 gyebutaazi .
PFX FH 0 gyebutaaki .
PFX FH 0 gyebutaabi .
PFX FH 0 gyebutaali .
PFX FH 0 gyebutaaga .
PFX FH 0 gyebutaaka .
PFX FH 0 gyebutaabu .
PFX FH 0 gyebutaalu .
PFX FH 0 gyebutaaku .
PFX FH 0 gyebutaatu .
PFX FH 0 gyelutaan [^lmnb]
PFX FH l gyelutaand l.[^mn][^u]
PFX FH l gyelutaann l.[mn]
PFX FH w gyelutaamp [w]
PFX FH 0 gyelutaamu .
PFX FH 0 gyelutaaba .
PFX FH 0 gyelutaagu .
PFX FH 0 gyelutaagi .
PFX FH 0 gyelutaazi .
PFX FH 0 gyelutaaki .
PFX FH 0 gyelutaabi .
PFX FH 0 gyelutaali .
PFX FH 0 gyelutaaga .
PFX FH 0 gyelutaaka .
PFX FH 0 gyelutaabu .
PFX FH 0 gyelutaalu .
PFX FH 0 gyelutaaku .
PFX FH 0 gyelutaatu .
PFX FH 0 gyekutaan [^lmnb]
PFX FH l gyekutaand l.[^mn][^u]
PFX FH l gyekutaann l.[mn]
PFX FH w gyekutaamp [w]
PFX FH 0 gyekutaamu .
PFX FH 0 gyekutaaba .
PFX FH 0 gyekutaagu .
PFX FH 0 gyekutaagi .
PFX FH 0 gyekutaazi .
PFX FH 0 gyekutaaki .
PFX FH 0 gyekutaabi .
PFX FH 0 gyekutaali .
PFX FH 0 gyekutaaga .
PFX FH 0 gyekutaaka .
PFX FH 0 gyekutaabu .
PFX FH 0 gyekutaalu .
PFX FH 0 gyekutaaku .
PFX FH 0 gyekutaatu .
PFX FH 0 gyetutaan [^lmnb]
PFX FH l gyetutaand l.[^mn][^u]
PFX FH l gyetutaann l.[mn]
PFX FH w gyetutaamp [w]
PFX FH 0 gyetutaamu .
PFX FH 0 gyetutaaba .
PFX FH 0 gyetutaagu .
PFX FH 0 gyetutaagi .
PFX FH 0 gyetutaazi .
PFX FH 0 gyetutaaki .
PFX FH 0 gyetutaabi .
PFX FH 0 gyetutaali .
PFX FH 0 gyetutaaga .
PFX FH 0 gyetutaaka .
PFX FH 0 gyetutaabu .
PFX FH 0 gyetutaalu .
PFX FH 0 gyetutaaku .
PFX FH 0 gyetutaatu .
PFX FH 0 ky'otaan [^lmnb]
PFX FH l ky'otaand l.[^mn][^u]
PFX FH l ky'otaann l.[mn]
PFX FH w ky'otaamp [w]
PFX FH 0 ky'otaamu .
PFX FH 0 ky'otaaba .
PFX FH 0 ky'otaagu .
PFX FH 0 ky'otaagi .
PFX FH 0 ky'otaazi .
PFX FH 0 ky'otaaki .
PFX FH 0 ky'otaabi .
PFX FH 0 ky'otaali .
PFX FH 0 ky'otaaga .
PFX FH 0 ky'otaaka .
PFX FH 0 ky'otaabu .
PFX FH 0 ky'otaalu .
PFX FH 0 ky'otaaku .
PFX FH 0 ky'otaatu .
PFX FH 0 ky'ataan [^lmnb]
PFX FH l ky'ataand l.[^mn][^u]
PFX FH l ky'ataann l.[mn]
PFX FH w ky'ataamp [w]
PFX FH 0 ky'ataamu .
PFX FH 0 ky'ataaba .
PFX FH 0 ky'ataagu .
PFX FH 0 ky'ataagi .
PFX FH 0 ky'ataazi .
PFX FH 0 ky'ataaki .
PFX FH 0 ky'ataabi .
PFX FH 0 ky'ataali .
PFX FH 0 ky'ataaga .
PFX FH 0 ky'ataaka .
PFX FH 0 ky'ataabu .
PFX FH 0 ky'ataalu .
PFX FH 0 ky'ataaku .
PFX FH 0 ky'ataatu .
PFX FH 0 ky'etaan [^lmnb]
PFX FH l ky'etaand l.[^mn][^u]
PFX FH l ky'etaann l.[mn]
PFX FH w ky'etaamp [w]
PFX FH 0 ky'etaamu .
PFX FH 0 ky'etaaba .
PFX FH 0 ky'etaagu .
PFX FH 0 ky'etaagi .
PFX FH 0 ky'etaazi .
PFX FH 0 ky'etaaki .
PFX FH 0 ky'etaabi .
PFX FH 0 ky'etaali .
PFX FH 0 ky'etaaga .
PFX FH 0 ky'etaaka .
PFX FH 0 ky'etaabu .
PFX FH 0 ky'etaalu .
PFX FH 0 ky'etaaku .
PFX FH 0 ky'etaatu .
PFX FH 0 kyessaaba .
PFX FH 0 kyessaagu .
PFX FH 0 kyessaagi .
PFX FH 0 kyessaazi .
PFX FH 0 kyessaaki .
PFX FH 0 kyessaabi .
PFX FH 0 kyessaali .
PFX FH 0 kyessaaga .
PFX FH 0 kyessaaka .
PFX FH 0 kyessaabu .
PFX FH 0 kyessaalu .
PFX FH 0 kyessaaku .
PFX FH 0 kyessaatu .
PFX FH 0 kyessaamu .
PFX FH 0 kyetutaan [^lmnb]
PFX FH l kyetutaand l.[^mn][^u]
PFX FH l kyetutaann l.[mn]
PFX FH w kyetutaamp [w]
PFX FH 0 kyetutaamu .
PFX FH 0 kyetutaaba .
PFX FH 0 kyetutaagu .
PFX FH 0 kyetutaagi .
PFX FH 0 kyetutaazi .
PFX FH 0 kyetutaaki .
PFX FH 0 kyetutaabi .
PFX FH 0 kyetutaali .
PFX FH 0 kyetutaaga .
PFX FH 0 kyetutaaka .
PFX FH 0 kyetutaabu .
PFX FH 0 kyetutaalu .
PFX FH 0 kyetutaaku .
PFX FH 0 kyetutaatu .
PFX FH 0 kyemutaan [^lmnb]
PFX FH l kyemutaand l.[^mn][^u]
PFX FH l kyemutaann l.[mn]
PFX FH w kyemutaamp [w]
PFX FH 0 kyemutaamu .
PFX FH 0 kyemutaaba .
PFX FH 0 kyemutaagu .
PFX FH 0 kyemutaagi .
PFX FH 0 kyemutaazi .
PFX FH 0 kyemutaaki .
PFX FH 0 kyemutaabi .
PFX FH 0 kyemutaali .
PFX FH 0 kyemutaaga .
PFX FH 0 kyemutaaka .
PFX FH 0 kyemutaabu .
PFX FH 0 kyemutaalu .
PFX FH 0 kyemutaaku .
PFX FH 0 kyemutaatu .
PFX FH 0 kyebataan [^lmnb]
PFX FH l kyebataand l.[^mn][^u]
PFX FH l kyebataann l.[mn]
PFX FH w kyebataamp [w]
PFX FH 0 kyebataamu .
PFX FH 0 kyebataaba .
PFX FH 0 kyebataagu .
PFX FH 0 kyebataagi .
PFX FH 0 kyebataazi .
PFX FH 0 kyebataaki .
PFX FH 0 kyebataabi .
PFX FH 0 kyebataali .
PFX FH 0 kyebataaga .
PFX FH 0 kyebataaka .
PFX FH 0 kyebataabu .
PFX FH 0 kyebataalu .
PFX FH 0 kyebataaku .
PFX FH 0 kyebataatu .
PFX FH 0 kyegutaan [^lmnb]
PFX FH l kyegutaand l.[^mn][^u]
PFX FH l kyegutaann l.[mn]
PFX FH w kyegutaamp [w]
PFX FH 0 kyegutaamu .
PFX FH 0 kyegutaaba .
PFX FH 0 kyegutaagu .
PFX FH 0 kyegutaagi .
PFX FH 0 kyegutaazi .
PFX FH 0 kyegutaaki .
PFX FH 0 kyegutaabi .
PFX FH 0 kyegutaali .
PFX FH 0 kyegutaaga .
PFX FH 0 kyegutaaka .
PFX FH 0 kyegutaabu .
PFX FH 0 kyegutaalu .
PFX FH 0 kyegutaaku .
PFX FH 0 kyegutaatu .
PFX FH 0 kyegitaan [^lmnb]
PFX FH l kyegitaand l.[^mn][^u]
PFX FH l kyegitaann l.[mn]
PFX FH w kyegitaamp [w]
PFX FH 0 kyegitaamu .
PFX FH 0 kyegitaaba .
PFX FH 0 kyegitaagu .
PFX FH 0 kyegitaagi .
PFX FH 0 kyegitaazi .
PFX FH 0 kyegitaaki .
PFX FH 0 kyegitaabi .
PFX FH 0 kyegitaali .
PFX FH 0 kyegitaaga .
PFX FH 0 kyegitaaka .
PFX FH 0 kyegitaabu .
PFX FH 0 kyegitaalu .
PFX FH 0 kyegitaaku .
PFX FH 0 kyegitaatu .
PFX FH 0 kyezitaan [^lmnb]
PFX FH l kyezitaand l.[^mn][^u]
PFX FH l kyezitaann l.[mn]
PFX FH w kyezitaamp [w]
PFX FH 0 kyezitaamu .
PFX FH 0 kyezitaaba .
PFX FH 0 kyezitaagu .
PFX FH 0 kyezitaagi .
PFX FH 0 kyezitaazi .
PFX FH 0 kyezitaaki .
PFX FH 0 kyezitaabi .
PFX FH 0 kyezitaali .
PFX FH 0 kyezitaaga .
PFX FH 0 kyezitaaka .
PFX FH 0 kyezitaabu .
PFX FH 0 kyezitaalu .
PFX FH 0 kyezitaaku .
PFX FH 0 kyezitaatu .
PFX FH 0 kyekitaan [^lmnb]
PFX FH l kyekitaand l.[^mn][^u]
PFX FH l kyekitaann l.[mn]
PFX FH w kyekitaamp [w]
PFX FH 0 kyekitaamu .
PFX FH 0 kyekitaaba .
PFX FH 0 kyekitaagu .
PFX FH 0 kyekitaagi .
PFX FH 0 kyekitaazi .
PFX FH 0 kyekitaaki .
PFX FH 0 kyekitaabi .
PFX FH 0 kyekitaali .
PFX FH 0 kyekitaaga .
PFX FH 0 kyekitaaka .
PFX FH 0 kyekitaabu .
PFX FH 0 kyekitaalu .
PFX FH 0 kyekitaaku .
PFX FH 0 kyekitaatu .
PFX FH 0 kyebitaan [^lmnb]
PFX FH l kyebitaand l.[^mn][^u]
PFX FH l kyebitaann l.[mn]
PFX FH w kyebitaamp [w]
PFX FH 0 kyebitaamu .
PFX FH 0 kyebitaaba .
PFX FH 0 kyebitaagu .
PFX FH 0 kyebitaagi .
PFX FH 0 kyebitaazi .
PFX FH 0 kyebitaaki .
PFX FH 0 kyebitaabi .
PFX FH 0 kyebitaali .
PFX FH 0 kyebitaaga .
PFX FH 0 kyebitaaka .
PFX FH 0 kyebitaabu .
PFX FH 0 kyebitaalu .
PFX FH 0 kyebitaaku .
PFX FH 0 kyebitaatu .
PFX FH 0 kyelitaan [^lmnb]
PFX FH l kyelitaand l.[^mn][^u]
PFX FH l kyelitaann l.[mn]
PFX FH w kyelitaamp [w]
PFX FH 0 kyelitaamu .
PFX FH 0 kyelitaaba .
PFX FH 0 kyelitaagu .
PFX FH 0 kyelitaagi .
PFX FH 0 kyelitaazi .
PFX FH 0 kyelitaaki .
PFX FH 0 kyelitaabi .
PFX FH 0 kyelitaali .
PFX FH 0 kyelitaaga .
PFX FH 0 kyelitaaka .
PFX FH 0 kyelitaabu .
PFX FH 0 kyelitaalu .
PFX FH 0 kyelitaaku .
PFX FH 0 kyelitaatu .
PFX FH 0 kyegataan [^lmnb]
PFX FH l kyegataand l.[^mn][^u]
PFX FH l kyegataann l.[mn]
PFX FH w kyegataamp [w]
PFX FH 0 kyegataamu .
PFX FH 0 kyegataaba .
PFX FH 0 kyegataagu .
PFX FH 0 kyegataagi .
PFX FH 0 kyegataazi .
PFX FH 0 kyegataaki .
PFX FH 0 kyegataabi .
PFX FH 0 kyegataali .
PFX FH 0 kyegataaga .
PFX FH 0 kyegataaka .
PFX FH 0 kyegataabu .
PFX FH 0 kyegataalu .
PFX FH 0 kyegataaku .
PFX FH 0 kyegataatu .
PFX FH 0 kyekataan [^lmnb]
PFX FH l kyekataand l.[^mn][^u]
PFX FH l kyekataann l.[mn]
PFX FH w kyekataamp [w]
PFX FH 0 kyekataamu .
PFX FH 0 kyekataaba .
PFX FH 0 kyekataagu .
PFX FH 0 kyekataagi .
PFX FH 0 kyekataazi .
PFX FH 0 kyekataaki .
PFX FH 0 kyekataabi .
PFX FH 0 kyekataali .
PFX FH 0 kyekataaga .
PFX FH 0 kyekataaka .
PFX FH 0 kyekataabu .
PFX FH 0 kyekataalu .
PFX FH 0 kyekataaku .
PFX FH 0 kyekataatu .
PFX FH 0 kyebutaan [^lmnb]
PFX FH l kyebutaand l.[^mn][^u]
PFX FH l kyebutaann l.[mn]
PFX FH w kyebutaamp [w]
PFX FH 0 kyebutaamu .
PFX FH 0 kyebutaaba .
PFX FH 0 kyebutaagu .
PFX FH 0 kyebutaagi .
PFX FH 0 kyebutaazi .
PFX FH 0 kyebutaaki .
PFX FH 0 kyebutaabi .
PFX FH 0 kyebutaali .
PFX FH 0 kyebutaaga .
PFX FH 0 kyebutaaka .
PFX FH 0 kyebutaabu .
PFX FH 0 kyebutaalu .
PFX FH 0 kyebutaaku .
PFX FH 0 kyebutaatu .
PFX FH 0 kyelutaan [^lmnb]
PFX FH l kyelutaand l.[^mn][^u]
PFX FH l kyelutaann l.[mn]
PFX FH w kyelutaamp [w]
PFX FH 0 kyelutaamu .
PFX FH 0 kyelutaaba .
PFX FH 0 kyelutaagu .
PFX FH 0 kyelutaagi .
PFX FH 0 kyelutaazi .
PFX FH 0 kyelutaaki .
PFX FH 0 kyelutaabi .
PFX FH 0 kyelutaali .
PFX FH 0 kyelutaaga .
PFX FH 0 kyelutaaka .
PFX FH 0 kyelutaabu .
PFX FH 0 kyelutaalu .
PFX FH 0 kyelutaaku .
PFX FH 0 kyelutaatu .
PFX FH 0 kyekutaan [^lmnb]
PFX FH l kyekutaand l.[^mn][^u]
PFX FH l kyekutaann l.[mn]
PFX FH w kyekutaamp [w]
PFX FH 0 kyekutaamu .
PFX FH 0 kyekutaaba .
PFX FH 0 kyekutaagu .
PFX FH 0 kyekutaagi .
PFX FH 0 kyekutaazi .
PFX FH 0 kyekutaaki .
PFX FH 0 kyekutaabi .
PFX FH 0 kyekutaali .
PFX FH 0 kyekutaaga .
PFX FH 0 kyekutaaka .
PFX FH 0 kyekutaabu .
PFX FH 0 kyekutaalu .
PFX FH 0 kyekutaaku .
PFX FH 0 kyekutaatu .
PFX FH 0 kyetutaan [^lmnb]
PFX FH l kyetutaand l.[^mn][^u]
PFX FH l kyetutaann l.[mn]
PFX FH w kyetutaamp [w]
PFX FH 0 kyetutaamu .
PFX FH 0 kyetutaaba .
PFX FH 0 kyetutaagu .
PFX FH 0 kyetutaagi .
PFX FH 0 kyetutaazi .
PFX FH 0 kyetutaaki .
PFX FH 0 kyetutaabi .
PFX FH 0 kyetutaali .
PFX FH 0 kyetutaaga .
PFX FH 0 kyetutaaka .
PFX FH 0 kyetutaabu .
PFX FH 0 kyetutaalu .
PFX FH 0 kyetutaaku .
PFX FH 0 kyetutaatu .
PFX FH 0 by'otaan [^lmnb]
PFX FH l by'otaand l.[^mn][^u]
PFX FH l by'otaann l.[mn]
PFX FH w by'otaamp [w]
PFX FH 0 by'otaamu .
PFX FH 0 by'otaaba .
PFX FH 0 by'otaagu .
PFX FH 0 by'otaagi .
PFX FH 0 by'otaazi .
PFX FH 0 by'otaaki .
PFX FH 0 by'otaabi .
PFX FH 0 by'otaali .
PFX FH 0 by'otaaga .
PFX FH 0 by'otaaka .
PFX FH 0 by'otaabu .
PFX FH 0 by'otaalu .
PFX FH 0 by'otaaku .
PFX FH 0 by'otaatu .
PFX FH 0 by'ataan [^lmnb]
PFX FH l by'ataand l.[^mn][^u]
PFX FH l by'ataann l.[mn]
PFX FH w by'ataamp [w]
PFX FH 0 by'ataamu .
PFX FH 0 by'ataaba .
PFX FH 0 by'ataagu .
PFX FH 0 by'ataagi .
PFX FH 0 by'ataazi .
PFX FH 0 by'ataaki .
PFX FH 0 by'ataabi .
PFX FH 0 by'ataali .
PFX FH 0 by'ataaga .
PFX FH 0 by'ataaka .
PFX FH 0 by'ataabu .
PFX FH 0 by'ataalu .
PFX FH 0 by'ataaku .
PFX FH 0 by'ataatu .
PFX FH 0 by'etaan [^lmnb]
PFX FH l by'etaand l.[^mn][^u]
PFX FH l by'etaann l.[mn]
PFX FH w by'etaamp [w]
PFX FH 0 by'etaamu .
PFX FH 0 by'etaaba .
PFX FH 0 by'etaagu .
PFX FH 0 by'etaagi .
PFX FH 0 by'etaazi .
PFX FH 0 by'etaaki .
PFX FH 0 by'etaabi .
PFX FH 0 by'etaali .
PFX FH 0 by'etaaga .
PFX FH 0 by'etaaka .
PFX FH 0 by'etaabu .
PFX FH 0 by'etaalu .
PFX FH 0 by'etaaku .
PFX FH 0 by'etaatu .
PFX FH 0 byessaaba .
PFX FH 0 byessaagu .
PFX FH 0 byessaagi .
PFX FH 0 byessaazi .
PFX FH 0 byessaaki .
PFX FH 0 byessaabi .
PFX FH 0 byessaali .
PFX FH 0 byessaaga .
PFX FH 0 byessaaka .
PFX FH 0 byessaabu .
PFX FH 0 byessaalu .
PFX FH 0 byessaaku .
PFX FH 0 byessaatu .
PFX FH 0 byessaamu .
PFX FH 0 byetutaan [^lmnb]
PFX FH l byetutaand l.[^mn][^u]
PFX FH l byetutaann l.[mn]
PFX FH w byetutaamp [w]
PFX FH 0 byetutaamu .
PFX FH 0 byetutaaba .
PFX FH 0 byetutaagu .
PFX FH 0 byetutaagi .
PFX FH 0 byetutaazi .
PFX FH 0 byetutaaki .
PFX FH 0 byetutaabi .
PFX FH 0 byetutaali .
PFX FH 0 byetutaaga .
PFX FH 0 byetutaaka .
PFX FH 0 byetutaabu .
PFX FH 0 byetutaalu .
PFX FH 0 byetutaaku .
PFX FH 0 byetutaatu .
PFX FH 0 byemutaan [^lmnb]
PFX FH l byemutaand l.[^mn][^u]
PFX FH l byemutaann l.[mn]
PFX FH w byemutaamp [w]
PFX FH 0 byemutaamu .
PFX FH 0 byemutaaba .
PFX FH 0 byemutaagu .
PFX FH 0 byemutaagi .
PFX FH 0 byemutaazi .
PFX FH 0 byemutaaki .
PFX FH 0 byemutaabi .
PFX FH 0 byemutaali .
PFX FH 0 byemutaaga .
PFX FH 0 byemutaaka .
PFX FH 0 byemutaabu .
PFX FH 0 byemutaalu .
PFX FH 0 byemutaaku .
PFX FH 0 byemutaatu .
PFX FH 0 byebataan [^lmnb]
PFX FH l byebataand l.[^mn][^u]
PFX FH l byebataann l.[mn]
PFX FH w byebataamp [w]
PFX FH 0 byebataamu .
PFX FH 0 byebataaba .
PFX FH 0 byebataagu .
PFX FH 0 byebataagi .
PFX FH 0 byebataazi .
PFX FH 0 byebataaki .
PFX FH 0 byebataabi .
PFX FH 0 byebataali .
PFX FH 0 byebataaga .
PFX FH 0 byebataaka .
PFX FH 0 byebataabu .
PFX FH 0 byebataalu .
PFX FH 0 byebataaku .
PFX FH 0 byebataatu .
PFX FH 0 byegutaan [^lmnb]
PFX FH l byegutaand l.[^mn][^u]
PFX FH l byegutaann l.[mn]
PFX FH w byegutaamp [w]
PFX FH 0 byegutaamu .
PFX FH 0 byegutaaba .
PFX FH 0 byegutaagu .
PFX FH 0 byegutaagi .
PFX FH 0 byegutaazi .
PFX FH 0 byegutaaki .
PFX FH 0 byegutaabi .
PFX FH 0 byegutaali .
PFX FH 0 byegutaaga .
PFX FH 0 byegutaaka .
PFX FH 0 byegutaabu .
PFX FH 0 byegutaalu .
PFX FH 0 byegutaaku .
PFX FH 0 byegutaatu .
PFX FH 0 byegitaan [^lmnb]
PFX FH l byegitaand l.[^mn][^u]
PFX FH l byegitaann l.[mn]
PFX FH w byegitaamp [w]
PFX FH 0 byegitaamu .
PFX FH 0 byegitaaba .
PFX FH 0 byegitaagu .
PFX FH 0 byegitaagi .
PFX FH 0 byegitaazi .
PFX FH 0 byegitaaki .
PFX FH 0 byegitaabi .
PFX FH 0 byegitaali .
PFX FH 0 byegitaaga .
PFX FH 0 byegitaaka .
PFX FH 0 byegitaabu .
PFX FH 0 byegitaalu .
PFX FH 0 byegitaaku .
PFX FH 0 byegitaatu .
PFX FH 0 byezitaan [^lmnb]
PFX FH l byezitaand l.[^mn][^u]
PFX FH l byezitaann l.[mn]
PFX FH w byezitaamp [w]
PFX FH 0 byezitaamu .
PFX FH 0 byezitaaba .
PFX FH 0 byezitaagu .
PFX FH 0 byezitaagi .
PFX FH 0 byezitaazi .
PFX FH 0 byezitaaki .
PFX FH 0 byezitaabi .
PFX FH 0 byezitaali .
PFX FH 0 byezitaaga .
PFX FH 0 byezitaaka .
PFX FH 0 byezitaabu .
PFX FH 0 byezitaalu .
PFX FH 0 byezitaaku .
PFX FH 0 byezitaatu .
PFX FH 0 byekitaan [^lmnb]
PFX FH l byekitaand l.[^mn][^u]
PFX FH l byekitaann l.[mn]
PFX FH w byekitaamp [w]
PFX FH 0 byekitaamu .
PFX FH 0 byekitaaba .
PFX FH 0 byekitaagu .
PFX FH 0 byekitaagi .
PFX FH 0 byekitaazi .
PFX FH 0 byekitaaki .
PFX FH 0 byekitaabi .
PFX FH 0 byekitaali .
PFX FH 0 byekitaaga .
PFX FH 0 byekitaaka .
PFX FH 0 byekitaabu .
PFX FH 0 byekitaalu .
PFX FH 0 byekitaaku .
PFX FH 0 byekitaatu .
PFX FH 0 byebitaan [^lmnb]
PFX FH l byebitaand l.[^mn][^u]
PFX FH l byebitaann l.[mn]
PFX FH w byebitaamp [w]
PFX FH 0 byebitaamu .
PFX FH 0 byebitaaba .
PFX FH 0 byebitaagu .
PFX FH 0 byebitaagi .
PFX FH 0 byebitaazi .
PFX FH 0 byebitaaki .
PFX FH 0 byebitaabi .
PFX FH 0 byebitaali .
PFX FH 0 byebitaaga .
PFX FH 0 byebitaaka .
PFX FH 0 byebitaabu .
PFX FH 0 byebitaalu .
PFX FH 0 byebitaaku .
PFX FH 0 byebitaatu .
PFX FH 0 byelitaan [^lmnb]
PFX FH l byelitaand l.[^mn][^u]
PFX FH l byelitaann l.[mn]
PFX FH w byelitaamp [w]
PFX FH 0 byelitaamu .
PFX FH 0 byelitaaba .
PFX FH 0 byelitaagu .
PFX FH 0 byelitaagi .
PFX FH 0 byelitaazi .
PFX FH 0 byelitaaki .
PFX FH 0 byelitaabi .
PFX FH 0 byelitaali .
PFX FH 0 byelitaaga .
PFX FH 0 byelitaaka .
PFX FH 0 byelitaabu .
PFX FH 0 byelitaalu .
PFX FH 0 byelitaaku .
PFX FH 0 byelitaatu .
PFX FH 0 byegataan [^lmnb]
PFX FH l byegataand l.[^mn][^u]
PFX FH l byegataann l.[mn]
PFX FH w byegataamp [w]
PFX FH 0 byegataamu .
PFX FH 0 byegataaba .
PFX FH 0 byegataagu .
PFX FH 0 byegataagi .
PFX FH 0 byegataazi .
PFX FH 0 byegataaki .
PFX FH 0 byegataabi .
PFX FH 0 byegataali .
PFX FH 0 byegataaga .
PFX FH 0 byegataaka .
PFX FH 0 byegataabu .
PFX FH 0 byegataalu .
PFX FH 0 byegataaku .
PFX FH 0 byegataatu .
PFX FH 0 byekataan [^lmnb]
PFX FH l byekataand l.[^mn][^u]
PFX FH l byekataann l.[mn]
PFX FH w byekataamp [w]
PFX FH 0 byekataamu .
PFX FH 0 byekataaba .
PFX FH 0 byekataagu .
PFX FH 0 byekataagi .
PFX FH 0 byekataazi .
PFX FH 0 byekataaki .
PFX FH 0 byekataabi .
PFX FH 0 byekataali .
PFX FH 0 byekataaga .
PFX FH 0 byekataaka .
PFX FH 0 byekataabu .
PFX FH 0 byekataalu .
PFX FH 0 byekataaku .
PFX FH 0 byekataatu .
PFX FH 0 byebutaan [^lmnb]
PFX FH l byebutaand l.[^mn][^u]
PFX FH l byebutaann l.[mn]
PFX FH w byebutaamp [w]
PFX FH 0 byebutaamu .
PFX FH 0 byebutaaba .
PFX FH 0 byebutaagu .
PFX FH 0 byebutaagi .
PFX FH 0 byebutaazi .
PFX FH 0 byebutaaki .
PFX FH 0 byebutaabi .
PFX FH 0 byebutaali .
PFX FH 0 byebutaaga .
PFX FH 0 byebutaaka .
PFX FH 0 byebutaabu .
PFX FH 0 byebutaalu .
PFX FH 0 byebutaaku .
PFX FH 0 byebutaatu .
PFX FH 0 byelutaan [^lmnb]
PFX FH l byelutaand l.[^mn][^u]
PFX FH l byelutaann l.[mn]
PFX FH w byelutaamp [w]
PFX FH 0 byelutaamu .
PFX FH 0 byelutaaba .
PFX FH 0 byelutaagu .
PFX FH 0 byelutaagi .
PFX FH 0 byelutaazi .
PFX FH 0 byelutaaki .
PFX FH 0 byelutaabi .
PFX FH 0 byelutaali .
PFX FH 0 byelutaaga .
PFX FH 0 byelutaaka .
PFX FH 0 byelutaabu .
PFX FH 0 byelutaalu .
PFX FH 0 byelutaaku .
PFX FH 0 byelutaatu .
PFX FH 0 byekutaan [^lmnb]
PFX FH l byekutaand l.[^mn][^u]
PFX FH l byekutaann l.[mn]
PFX FH w byekutaamp [w]
PFX FH 0 byekutaamu .
PFX FH 0 byekutaaba .
PFX FH 0 byekutaagu .
PFX FH 0 byekutaagi .
PFX FH 0 byekutaazi .
PFX FH 0 byekutaaki .
PFX FH 0 byekutaabi .
PFX FH 0 byekutaali .
PFX FH 0 byekutaaga .
PFX FH 0 byekutaaka .
PFX FH 0 byekutaabu .
PFX FH 0 byekutaalu .
PFX FH 0 byekutaaku .
PFX FH 0 byekutaatu .
PFX FH 0 byetutaan [^lmnb]
PFX FH l byetutaand l.[^mn][^u]
PFX FH l byetutaann l.[mn]
PFX FH w byetutaamp [w]
PFX FH 0 byetutaamu .
PFX FH 0 byetutaaba .
PFX FH 0 byetutaagu .
PFX FH 0 byetutaagi .
PFX FH 0 byetutaazi .
PFX FH 0 byetutaaki .
PFX FH 0 byetutaabi .
PFX FH 0 byetutaali .
PFX FH 0 byetutaaga .
PFX FH 0 byetutaaka .
PFX FH 0 byetutaabu .
PFX FH 0 byetutaalu .
PFX FH 0 byetutaaku .
PFX FH 0 byetutaatu .
PFX FH 0 ly'otaan [^lmnb]
PFX FH l ly'otaand l.[^mn][^u]
PFX FH l ly'otaann l.[mn]
PFX FH w ly'otaamp [w]
PFX FH 0 ly'otaamu .
PFX FH 0 ly'otaaba .
PFX FH 0 ly'otaagu .
PFX FH 0 ly'otaagi .
PFX FH 0 ly'otaazi .
PFX FH 0 ly'otaaki .
PFX FH 0 ly'otaabi .
PFX FH 0 ly'otaali .
PFX FH 0 ly'otaaga .
PFX FH 0 ly'otaaka .
PFX FH 0 ly'otaabu .
PFX FH 0 ly'otaalu .
PFX FH 0 ly'otaaku .
PFX FH 0 ly'otaatu .
PFX FH 0 ly'ataan [^lmnb]
PFX FH l ly'ataand l.[^mn][^u]
PFX FH l ly'ataann l.[mn]
PFX FH w ly'ataamp [w]
PFX FH 0 ly'ataamu .
PFX FH 0 ly'ataaba .
PFX FH 0 ly'ataagu .
PFX FH 0 ly'ataagi .
PFX FH 0 ly'ataazi .
PFX FH 0 ly'ataaki .
PFX FH 0 ly'ataabi .
PFX FH 0 ly'ataali .
PFX FH 0 ly'ataaga .
PFX FH 0 ly'ataaka .
PFX FH 0 ly'ataabu .
PFX FH 0 ly'ataalu .
PFX FH 0 ly'ataaku .
PFX FH 0 ly'ataatu .
PFX FH 0 ly'etaan [^lmnb]
PFX FH l ly'etaand l.[^mn][^u]
PFX FH l ly'etaann l.[mn]
PFX FH w ly'etaamp [w]
PFX FH 0 ly'etaamu .
PFX FH 0 ly'etaaba .
PFX FH 0 ly'etaagu .
PFX FH 0 ly'etaagi .
PFX FH 0 ly'etaazi .
PFX FH 0 ly'etaaki .
PFX FH 0 ly'etaabi .
PFX FH 0 ly'etaali .
PFX FH 0 ly'etaaga .
PFX FH 0 ly'etaaka .
PFX FH 0 ly'etaabu .
PFX FH 0 ly'etaalu .
PFX FH 0 ly'etaaku .
PFX FH 0 ly'etaatu .
PFX FH 0 lyessaaba .
PFX FH 0 lyessaagu .
PFX FH 0 lyessaagi .
PFX FH 0 lyessaazi .
PFX FH 0 lyessaaki .
PFX FH 0 lyessaabi .
PFX FH 0 lyessaali .
PFX FH 0 lyessaaga .
PFX FH 0 lyessaaka .
PFX FH 0 lyessaabu .
PFX FH 0 lyessaalu .
PFX FH 0 lyessaaku .
PFX FH 0 lyessaatu .
PFX FH 0 lyessaamu .
PFX FH 0 lyetutaan [^lmnb]
PFX FH l lyetutaand l.[^mn][^u]
PFX FH l lyetutaann l.[mn]
PFX FH w lyetutaamp [w]
PFX FH 0 lyetutaamu .
PFX FH 0 lyetutaaba .
PFX FH 0 lyetutaagu .
PFX FH 0 lyetutaagi .
PFX FH 0 lyetutaazi .
PFX FH 0 lyetutaaki .
PFX FH 0 lyetutaabi .
PFX FH 0 lyetutaali .
PFX FH 0 lyetutaaga .
PFX FH 0 lyetutaaka .
PFX FH 0 lyetutaabu .
PFX FH 0 lyetutaalu .
PFX FH 0 lyetutaaku .
PFX FH 0 lyetutaatu .
PFX FH 0 lyemutaan [^lmnb]
PFX FH l lyemutaand l.[^mn][^u]
PFX FH l lyemutaann l.[mn]
PFX FH w lyemutaamp [w]
PFX FH 0 lyemutaamu .
PFX FH 0 lyemutaaba .
PFX FH 0 lyemutaagu .
PFX FH 0 lyemutaagi .
PFX FH 0 lyemutaazi .
PFX FH 0 lyemutaaki .
PFX FH 0 lyemutaabi .
PFX FH 0 lyemutaali .
PFX FH 0 lyemutaaga .
PFX FH 0 lyemutaaka .
PFX FH 0 lyemutaabu .
PFX FH 0 lyemutaalu .
PFX FH 0 lyemutaaku .
PFX FH 0 lyemutaatu .
PFX FH 0 lyebataan [^lmnb]
PFX FH l lyebataand l.[^mn][^u]
PFX FH l lyebataann l.[mn]
PFX FH w lyebataamp [w]
PFX FH 0 lyebataamu .
PFX FH 0 lyebataaba .
PFX FH 0 lyebataagu .
PFX FH 0 lyebataagi .
PFX FH 0 lyebataazi .
PFX FH 0 lyebataaki .
PFX FH 0 lyebataabi .
PFX FH 0 lyebataali .
PFX FH 0 lyebataaga .
PFX FH 0 lyebataaka .
PFX FH 0 lyebataabu .
PFX FH 0 lyebataalu .
PFX FH 0 lyebataaku .
PFX FH 0 lyebataatu .
PFX FH 0 lyegutaan [^lmnb]
PFX FH l lyegutaand l.[^mn][^u]
PFX FH l lyegutaann l.[mn]
PFX FH w lyegutaamp [w]
PFX FH 0 lyegutaamu .
PFX FH 0 lyegutaaba .
PFX FH 0 lyegutaagu .
PFX FH 0 lyegutaagi .
PFX FH 0 lyegutaazi .
PFX FH 0 lyegutaaki .
PFX FH 0 lyegutaabi .
PFX FH 0 lyegutaali .
PFX FH 0 lyegutaaga .
PFX FH 0 lyegutaaka .
PFX FH 0 lyegutaabu .
PFX FH 0 lyegutaalu .
PFX FH 0 lyegutaaku .
PFX FH 0 lyegutaatu .
PFX FH 0 lyegitaan [^lmnb]
PFX FH l lyegitaand l.[^mn][^u]
PFX FH l lyegitaann l.[mn]
PFX FH w lyegitaamp [w]
PFX FH 0 lyegitaamu .
PFX FH 0 lyegitaaba .
PFX FH 0 lyegitaagu .
PFX FH 0 lyegitaagi .
PFX FH 0 lyegitaazi .
PFX FH 0 lyegitaaki .
PFX FH 0 lyegitaabi .
PFX FH 0 lyegitaali .
PFX FH 0 lyegitaaga .
PFX FH 0 lyegitaaka .
PFX FH 0 lyegitaabu .
PFX FH 0 lyegitaalu .
PFX FH 0 lyegitaaku .
PFX FH 0 lyegitaatu .
PFX FH 0 lyezitaan [^lmnb]
PFX FH l lyezitaand l.[^mn][^u]
PFX FH l lyezitaann l.[mn]
PFX FH w lyezitaamp [w]
PFX FH 0 lyezitaamu .
PFX FH 0 lyezitaaba .
PFX FH 0 lyezitaagu .
PFX FH 0 lyezitaagi .
PFX FH 0 lyezitaazi .
PFX FH 0 lyezitaaki .
PFX FH 0 lyezitaabi .
PFX FH 0 lyezitaali .
PFX FH 0 lyezitaaga .
PFX FH 0 lyezitaaka .
PFX FH 0 lyezitaabu .
PFX FH 0 lyezitaalu .
PFX FH 0 lyezitaaku .
PFX FH 0 lyezitaatu .
PFX FH 0 lyekitaan [^lmnb]
PFX FH l lyekitaand l.[^mn][^u]
PFX FH l lyekitaann l.[mn]
PFX FH w lyekitaamp [w]
PFX FH 0 lyekitaamu .
PFX FH 0 lyekitaaba .
PFX FH 0 lyekitaagu .
PFX FH 0 lyekitaagi .
PFX FH 0 lyekitaazi .
PFX FH 0 lyekitaaki .
PFX FH 0 lyekitaabi .
PFX FH 0 lyekitaali .
PFX FH 0 lyekitaaga .
PFX FH 0 lyekitaaka .
PFX FH 0 lyekitaabu .
PFX FH 0 lyekitaalu .
PFX FH 0 lyekitaaku .
PFX FH 0 lyekitaatu .
PFX FH 0 lyebitaan [^lmnb]
PFX FH l lyebitaand l.[^mn][^u]
PFX FH l lyebitaann l.[mn]
PFX FH w lyebitaamp [w]
PFX FH 0 lyebitaamu .
PFX FH 0 lyebitaaba .
PFX FH 0 lyebitaagu .
PFX FH 0 lyebitaagi .
PFX FH 0 lyebitaazi .
PFX FH 0 lyebitaaki .
PFX FH 0 lyebitaabi .
PFX FH 0 lyebitaali .
PFX FH 0 lyebitaaga .
PFX FH 0 lyebitaaka .
PFX FH 0 lyebitaabu .
PFX FH 0 lyebitaalu .
PFX FH 0 lyebitaaku .
PFX FH 0 lyebitaatu .
PFX FH 0 lyelitaan [^lmnb]
PFX FH l lyelitaand l.[^mn][^u]
PFX FH l lyelitaann l.[mn]
PFX FH w lyelitaamp [w]
PFX FH 0 lyelitaamu .
PFX FH 0 lyelitaaba .
PFX FH 0 lyelitaagu .
PFX FH 0 lyelitaagi .
PFX FH 0 lyelitaazi .
PFX FH 0 lyelitaaki .
PFX FH 0 lyelitaabi .
PFX FH 0 lyelitaali .
PFX FH 0 lyelitaaga .
PFX FH 0 lyelitaaka .
PFX FH 0 lyelitaabu .
PFX FH 0 lyelitaalu .
PFX FH 0 lyelitaaku .
PFX FH 0 lyelitaatu .
PFX FH 0 lyegataan [^lmnb]
PFX FH l lyegataand l.[^mn][^u]
PFX FH l lyegataann l.[mn]
PFX FH w lyegataamp [w]
PFX FH 0 lyegataamu .
PFX FH 0 lyegataaba .
PFX FH 0 lyegataagu .
PFX FH 0 lyegataagi .
PFX FH 0 lyegataazi .
PFX FH 0 lyegataaki .
PFX FH 0 lyegataabi .
PFX FH 0 lyegataali .
PFX FH 0 lyegataaga .
PFX FH 0 lyegataaka .
PFX FH 0 lyegataabu .
PFX FH 0 lyegataalu .
PFX FH 0 lyegataaku .
PFX FH 0 lyegataatu .
PFX FH 0 lyekataan [^lmnb]
PFX FH l lyekataand l.[^mn][^u]
PFX FH l lyekataann l.[mn]
PFX FH w lyekataamp [w]
PFX FH 0 lyekataamu .
PFX FH 0 lyekataaba .
PFX FH 0 lyekataagu .
PFX FH 0 lyekataagi .
PFX FH 0 lyekataazi .
PFX FH 0 lyekataaki .
PFX FH 0 lyekataabi .
PFX FH 0 lyekataali .
PFX FH 0 lyekataaga .
PFX FH 0 lyekataaka .
PFX FH 0 lyekataabu .
PFX FH 0 lyekataalu .
PFX FH 0 lyekataaku .
PFX FH 0 lyekataatu .
PFX FH 0 lyebutaan [^lmnb]
PFX FH l lyebutaand l.[^mn][^u]
PFX FH l lyebutaann l.[mn]
PFX FH w lyebutaamp [w]
PFX FH 0 lyebutaamu .
PFX FH 0 lyebutaaba .
PFX FH 0 lyebutaagu .
PFX FH 0 lyebutaagi .
PFX FH 0 lyebutaazi .
PFX FH 0 lyebutaaki .
PFX FH 0 lyebutaabi .
PFX FH 0 lyebutaali .
PFX FH 0 lyebutaaga .
PFX FH 0 lyebutaaka .
PFX FH 0 lyebutaabu .
PFX FH 0 lyebutaalu .
PFX FH 0 lyebutaaku .
PFX FH 0 lyebutaatu .
PFX FH 0 lyelutaan [^lmnb]
PFX FH l lyelutaand l.[^mn][^u]
PFX FH l lyelutaann l.[mn]
PFX FH w lyelutaamp [w]
PFX FH 0 lyelutaamu .
PFX FH 0 lyelutaaba .
PFX FH 0 lyelutaagu .
PFX FH 0 lyelutaagi .
PFX FH 0 lyelutaazi .
PFX FH 0 lyelutaaki .
PFX FH 0 lyelutaabi .
PFX FH 0 lyelutaali .
PFX FH 0 lyelutaaga .
PFX FH 0 lyelutaaka .
PFX FH 0 lyelutaabu .
PFX FH 0 lyelutaalu .
PFX FH 0 lyelutaaku .
PFX FH 0 lyelutaatu .
PFX FH 0 lyekutaan [^lmnb]
PFX FH l lyekutaand l.[^mn][^u]
PFX FH l lyekutaann l.[mn]
PFX FH w lyekutaamp [w]
PFX FH 0 lyekutaamu .
PFX FH 0 lyekutaaba .
PFX FH 0 lyekutaagu .
PFX FH 0 lyekutaagi .
PFX FH 0 lyekutaazi .
PFX FH 0 lyekutaaki .
PFX FH 0 lyekutaabi .
PFX FH 0 lyekutaali .
PFX FH 0 lyekutaaga .
PFX FH 0 lyekutaaka .
PFX FH 0 lyekutaabu .
PFX FH 0 lyekutaalu .
PFX FH 0 lyekutaaku .
PFX FH 0 lyekutaatu .
PFX FH 0 lyetutaan [^lmnb]
PFX FH l lyetutaand l.[^mn][^u]
PFX FH l lyetutaann l.[mn]
PFX FH w lyetutaamp [w]
PFX FH 0 lyetutaamu .
PFX FH 0 lyetutaaba .
PFX FH 0 lyetutaagu .
PFX FH 0 lyetutaagi .
PFX FH 0 lyetutaazi .
PFX FH 0 lyetutaaki .
PFX FH 0 lyetutaabi .
PFX FH 0 lyetutaali .
PFX FH 0 lyetutaaga .
PFX FH 0 lyetutaaka .
PFX FH 0 lyetutaabu .
PFX FH 0 lyetutaalu .
PFX FH 0 lyetutaaku .
PFX FH 0 lyetutaatu .
PFX FH 0 k'otaan [^lmnb]
PFX FH l k'otaand l.[^mn][^u]
PFX FH l k'otaann l.[mn]
PFX FH w k'otaamp [w]
PFX FH 0 k'otaamu .
PFX FH 0 k'otaaba .
PFX FH 0 k'otaagu .
PFX FH 0 k'otaagi .
PFX FH 0 k'otaazi .
PFX FH 0 k'otaaki .
PFX FH 0 k'otaabi .
PFX FH 0 k'otaali .
PFX FH 0 k'otaaga .
PFX FH 0 k'otaaka .
PFX FH 0 k'otaabu .
PFX FH 0 k'otaalu .
PFX FH 0 k'otaaku .
PFX FH 0 k'otaatu .
PFX FH 0 k'ataan [^lmnb]
PFX FH l k'ataand l.[^mn][^u]
PFX FH l k'ataann l.[mn]
PFX FH w k'ataamp [w]
PFX FH 0 k'ataamu .
PFX FH 0 k'ataaba .
PFX FH 0 k'ataagu .
PFX FH 0 k'ataagi .
PFX FH 0 k'ataazi .
PFX FH 0 k'ataaki .
PFX FH 0 k'ataabi .
PFX FH 0 k'ataali .
PFX FH 0 k'ataaga .
PFX FH 0 k'ataaka .
PFX FH 0 k'ataabu .
PFX FH 0 k'ataalu .
PFX FH 0 k'ataaku .
PFX FH 0 k'ataatu .
PFX FH 0 k'etaan [^lmnb]
PFX FH l k'etaand l.[^mn][^u]
PFX FH l k'etaann l.[mn]
PFX FH w k'etaamp [w]
PFX FH 0 k'etaamu .
PFX FH 0 k'etaaba .
PFX FH 0 k'etaagu .
PFX FH 0 k'etaagi .
PFX FH 0 k'etaazi .
PFX FH 0 k'etaaki .
PFX FH 0 k'etaabi .
PFX FH 0 k'etaali .
PFX FH 0 k'etaaga .
PFX FH 0 k'etaaka .
PFX FH 0 k'etaabu .
PFX FH 0 k'etaalu .
PFX FH 0 k'etaaku .
PFX FH 0 k'etaatu .
PFX FH 0 kessaaba .
PFX FH 0 kessaagu .
PFX FH 0 kessaagi .
PFX FH 0 kessaazi .
PFX FH 0 kessaaki .
PFX FH 0 kessaabi .
PFX FH 0 kessaali .
PFX FH 0 kessaaga .
PFX FH 0 kessaaka .
PFX FH 0 kessaabu .
PFX FH 0 kessaalu .
PFX FH 0 kessaaku .
PFX FH 0 kessaatu .
PFX FH 0 kessaamu .
PFX FH 0 ketutaan [^lmnb]
PFX FH l ketutaand l.[^mn][^u]
PFX FH l ketutaann l.[mn]
PFX FH w ketutaamp [w]
PFX FH 0 ketutaamu .
PFX FH 0 ketutaaba .
PFX FH 0 ketutaagu .
PFX FH 0 ketutaagi .
PFX FH 0 ketutaazi .
PFX FH 0 ketutaaki .
PFX FH 0 ketutaabi .
PFX FH 0 ketutaali .
PFX FH 0 ketutaaga .
PFX FH 0 ketutaaka .
PFX FH 0 ketutaabu .
PFX FH 0 ketutaalu .
PFX FH 0 ketutaaku .
PFX FH 0 ketutaatu .
PFX FH 0 kemutaan [^lmnb]
PFX FH l kemutaand l.[^mn][^u]
PFX FH l kemutaann l.[mn]
PFX FH w kemutaamp [w]
PFX FH 0 kemutaamu .
PFX FH 0 kemutaaba .
PFX FH 0 kemutaagu .
PFX FH 0 kemutaagi .
PFX FH 0 kemutaazi .
PFX FH 0 kemutaaki .
PFX FH 0 kemutaabi .
PFX FH 0 kemutaali .
PFX FH 0 kemutaaga .
PFX FH 0 kemutaaka .
PFX FH 0 kemutaabu .
PFX FH 0 kemutaalu .
PFX FH 0 kemutaaku .
PFX FH 0 kemutaatu .
PFX FH 0 kebataan [^lmnb]
PFX FH l kebataand l.[^mn][^u]
PFX FH l kebataann l.[mn]
PFX FH w kebataamp [w]
PFX FH 0 kebataamu .
PFX FH 0 kebataaba .
PFX FH 0 kebataagu .
PFX FH 0 kebataagi .
PFX FH 0 kebataazi .
PFX FH 0 kebataaki .
PFX FH 0 kebataabi .
PFX FH 0 kebataali .
PFX FH 0 kebataaga .
PFX FH 0 kebataaka .
PFX FH 0 kebataabu .
PFX FH 0 kebataalu .
PFX FH 0 kebataaku .
PFX FH 0 kebataatu .
PFX FH 0 kegutaan [^lmnb]
PFX FH l kegutaand l.[^mn][^u]
PFX FH l kegutaann l.[mn]
PFX FH w kegutaamp [w]
PFX FH 0 kegutaamu .
PFX FH 0 kegutaaba .
PFX FH 0 kegutaagu .
PFX FH 0 kegutaagi .
PFX FH 0 kegutaazi .
PFX FH 0 kegutaaki .
PFX FH 0 kegutaabi .
PFX FH 0 kegutaali .
PFX FH 0 kegutaaga .
PFX FH 0 kegutaaka .
PFX FH 0 kegutaabu .
PFX FH 0 kegutaalu .
PFX FH 0 kegutaaku .
PFX FH 0 kegutaatu .
PFX FH 0 kegitaan [^lmnb]
PFX FH l kegitaand l.[^mn][^u]
PFX FH l kegitaann l.[mn]
PFX FH w kegitaamp [w]
PFX FH 0 kegitaamu .
PFX FH 0 kegitaaba .
PFX FH 0 kegitaagu .
PFX FH 0 kegitaagi .
PFX FH 0 kegitaazi .
PFX FH 0 kegitaaki .
PFX FH 0 kegitaabi .
PFX FH 0 kegitaali .
PFX FH 0 kegitaaga .
PFX FH 0 kegitaaka .
PFX FH 0 kegitaabu .
PFX FH 0 kegitaalu .
PFX FH 0 kegitaaku .
PFX FH 0 kegitaatu .
PFX FH 0 kezitaan [^lmnb]
PFX FH l kezitaand l.[^mn][^u]
PFX FH l kezitaann l.[mn]
PFX FH w kezitaamp [w]
PFX FH 0 kezitaamu .
PFX FH 0 kezitaaba .
PFX FH 0 kezitaagu .
PFX FH 0 kezitaagi .
PFX FH 0 kezitaazi .
PFX FH 0 kezitaaki .
PFX FH 0 kezitaabi .
PFX FH 0 kezitaali .
PFX FH 0 kezitaaga .
PFX FH 0 kezitaaka .
PFX FH 0 kezitaabu .
PFX FH 0 kezitaalu .
PFX FH 0 kezitaaku .
PFX FH 0 kezitaatu .
PFX FH 0 kekitaan [^lmnb]
PFX FH l kekitaand l.[^mn][^u]
PFX FH l kekitaann l.[mn]
PFX FH w kekitaamp [w]
PFX FH 0 kekitaamu .
PFX FH 0 kekitaaba .
PFX FH 0 kekitaagu .
PFX FH 0 kekitaagi .
PFX FH 0 kekitaazi .
PFX FH 0 kekitaaki .
PFX FH 0 kekitaabi .
PFX FH 0 kekitaali .
PFX FH 0 kekitaaga .
PFX FH 0 kekitaaka .
PFX FH 0 kekitaabu .
PFX FH 0 kekitaalu .
PFX FH 0 kekitaaku .
PFX FH 0 kekitaatu .
PFX FH 0 kebitaan [^lmnb]
PFX FH l kebitaand l.[^mn][^u]
PFX FH l kebitaann l.[mn]
PFX FH w kebitaamp [w]
PFX FH 0 kebitaamu .
PFX FH 0 kebitaaba .
PFX FH 0 kebitaagu .
PFX FH 0 kebitaagi .
PFX FH 0 kebitaazi .
PFX FH 0 kebitaaki .
PFX FH 0 kebitaabi .
PFX FH 0 kebitaali .
PFX FH 0 kebitaaga .
PFX FH 0 kebitaaka .
PFX FH 0 kebitaabu .
PFX FH 0 kebitaalu .
PFX FH 0 kebitaaku .
PFX FH 0 kebitaatu .
PFX FH 0 kelitaan [^lmnb]
PFX FH l kelitaand l.[^mn][^u]
PFX FH l kelitaann l.[mn]
PFX FH w kelitaamp [w]
PFX FH 0 kelitaamu .
PFX FH 0 kelitaaba .
PFX FH 0 kelitaagu .
PFX FH 0 kelitaagi .
PFX FH 0 kelitaazi .
PFX FH 0 kelitaaki .
PFX FH 0 kelitaabi .
PFX FH 0 kelitaali .
PFX FH 0 kelitaaga .
PFX FH 0 kelitaaka .
PFX FH 0 kelitaabu .
PFX FH 0 kelitaalu .
PFX FH 0 kelitaaku .
PFX FH 0 kelitaatu .
PFX FH 0 kegataan [^lmnb]
PFX FH l kegataand l.[^mn][^u]
PFX FH l kegataann l.[mn]
PFX FH w kegataamp [w]
PFX FH 0 kegataamu .
PFX FH 0 kegataaba .
PFX FH 0 kegataagu .
PFX FH 0 kegataagi .
PFX FH 0 kegataazi .
PFX FH 0 kegataaki .
PFX FH 0 kegataabi .
PFX FH 0 kegataali .
PFX FH 0 kegataaga .
PFX FH 0 kegataaka .
PFX FH 0 kegataabu .
PFX FH 0 kegataalu .
PFX FH 0 kegataaku .
PFX FH 0 kegataatu .
PFX FH 0 kekataan [^lmnb]
PFX FH l kekataand l.[^mn][^u]
PFX FH l kekataann l.[mn]
PFX FH w kekataamp [w]
PFX FH 0 kekataamu .
PFX FH 0 kekataaba .
PFX FH 0 kekataagu .
PFX FH 0 kekataagi .
PFX FH 0 kekataazi .
PFX FH 0 kekataaki .
PFX FH 0 kekataabi .
PFX FH 0 kekataali .
PFX FH 0 kekataaga .
PFX FH 0 kekataaka .
PFX FH 0 kekataabu .
PFX FH 0 kekataalu .
PFX FH 0 kekataaku .
PFX FH 0 kekataatu .
PFX FH 0 kebutaan [^lmnb]
PFX FH l kebutaand l.[^mn][^u]
PFX FH l kebutaann l.[mn]
PFX FH w kebutaamp [w]
PFX FH 0 kebutaamu .
PFX FH 0 kebutaaba .
PFX FH 0 kebutaagu .
PFX FH 0 kebutaagi .
PFX FH 0 kebutaazi .
PFX FH 0 kebutaaki .
PFX FH 0 kebutaabi .
PFX FH 0 kebutaali .
PFX FH 0 kebutaaga .
PFX FH 0 kebutaaka .
PFX FH 0 kebutaabu .
PFX FH 0 kebutaalu .
PFX FH 0 kebutaaku .
PFX FH 0 kebutaatu .
PFX FH 0 kelutaan [^lmnb]
PFX FH l kelutaand l.[^mn][^u]
PFX FH l kelutaann l.[mn]
PFX FH w kelutaamp [w]
PFX FH 0 kelutaamu .
PFX FH 0 kelutaaba .
PFX FH 0 kelutaagu .
PFX FH 0 kelutaagi .
PFX FH 0 kelutaazi .
PFX FH 0 kelutaaki .
PFX FH 0 kelutaabi .
PFX FH 0 kelutaali .
PFX FH 0 kelutaaga .
PFX FH 0 kelutaaka .
PFX FH 0 kelutaabu .
PFX FH 0 kelutaalu .
PFX FH 0 kelutaaku .
PFX FH 0 kelutaatu .
PFX FH 0 kekutaan [^lmnb]
PFX FH l kekutaand l.[^mn][^u]
PFX FH l kekutaann l.[mn]
PFX FH w kekutaamp [w]
PFX FH 0 kekutaamu .
PFX FH 0 kekutaaba .
PFX FH 0 kekutaagu .
PFX FH 0 kekutaagi .
PFX FH 0 kekutaazi .
PFX FH 0 kekutaaki .
PFX FH 0 kekutaabi .
PFX FH 0 kekutaali .
PFX FH 0 kekutaaga .
PFX FH 0 kekutaaka .
PFX FH 0 kekutaabu .
PFX FH 0 kekutaalu .
PFX FH 0 kekutaaku .
PFX FH 0 kekutaatu .
PFX FH 0 ketutaan [^lmnb]
PFX FH l ketutaand l.[^mn][^u]
PFX FH l ketutaann l.[mn]
PFX FH w ketutaamp [w]
PFX FH 0 ketutaamu .
PFX FH 0 ketutaaba .
PFX FH 0 ketutaagu .
PFX FH 0 ketutaagi .
PFX FH 0 ketutaazi .
PFX FH 0 ketutaaki .
PFX FH 0 ketutaabi .
PFX FH 0 ketutaali .
PFX FH 0 ketutaaga .
PFX FH 0 ketutaaka .
PFX FH 0 ketutaabu .
PFX FH 0 ketutaalu .
PFX FH 0 ketutaaku .
PFX FH 0 ketutaatu ."""

rule_right_raw = """
PFX OR Y 16
PFX OR 0 mwe .
PFX OR 0 bee .
PFX OR 0 gwe .
PFX OR 0 gye .
PFX OR 0 zee .
PFX OR 0 kye .
PFX OR 0 bye .
PFX OR 0 lye .
PFX OR 0 gee .
PFX OR 0 kee .
PFX OR 0 bwe .
PFX OR 0 lwe .
PFX OR 0 zee .
PFX OR 0 kwe .
PFX OR 0 gee .
PFX OR 0 twe ."""

FLAG_DESCRIPTIONS = {
    "FH": "FH",
    "OR": "Special reflexive object markers",
}

def parse_rules(raw_text):
    rules = []
    for line in raw_text.strip().split('\n'):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        s = s.split('#', 1)[0].strip()
        parts = s.split()
        if len(parts) < 4:
            continue
        if parts[2] == 'Y':
            continue
        cond = parts[4] if len(parts) > 4 else '.'
        rules.append({'strip': parts[2], 'add': parts[3], 'cond': cond})
    return rules

def generate_block():
    lefts = parse_rules(rule_left_raw)
    rights = parse_rules(rule_right_raw)
    new_rules = []

    for left in lefts:
        for right in rights:
            if left['strip'] != '0':
                if not right['add'].startswith(left['strip']):
                    continue
                combined = left['add'] + right['add'][len(left['strip']):]
            else:
                combined = left['add'] + right['add']

            if left['cond'] != '.':
                if not re.match(left['cond'], right['add']):
                    continue

            new_rules.append({'strip': right['strip'], 'add': combined, 'cond': right['cond']})

    out_flag = "GH"
    left_desc = FLAG_DESCRIPTIONS.get("FH", "FH")
    right_desc = FLAG_DESCRIPTIONS.get("OR", "OR")
    comment_line = "# Cross product of {} ({}) and {} ({}) to {}".format(
        "FH", left_desc, "OR", right_desc, out_flag
    )

    output = ["PFX {} Y {}".format(out_flag, len(new_rules))]
    for r in new_rules:
        output.append("PFX {} {} {} {}".format(out_flag, r['strip'], r['add'], r['cond']))

    return (out_flag, "\n".join([comment_line] + output) + "\n")

def main():
    if not os.path.exists(AFF_FILE):
        print("Error: {} not found.".format(AFF_FILE))
        return

    out_flag, block = generate_block()

    with open(AFF_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    first_flag_idx = None
    last_flag_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("PFX {} ".format(out_flag)):
            if first_flag_idx is None:
                first_flag_idx = i
            last_flag_idx = i

    if first_flag_idx is not None and first_flag_idx > 0:
        prev_line = lines[first_flag_idx - 1].strip()
        if prev_line.startswith("# Cross product"):
            start_idx = first_flag_idx - 1
        else:
            start_idx = first_flag_idx
    elif first_flag_idx is not None:
        start_idx = first_flag_idx
    else:
        start_idx = None

    if start_idx is not None and last_flag_idx is not None:
        # Replace existing block in-place.
        new_lines = lines[:start_idx] + [block] + lines[last_flag_idx + 1:]
    else:
        # Insert before an anchor flag if requested; otherwise append.
        insert_idx = None
        if INSERT_BEFORE_FLAG:
            anchor_prefix = "PFX {} ".format(INSERT_BEFORE_FLAG)
            for i, line in enumerate(lines):
                if line.strip().startswith(anchor_prefix):
                    insert_idx = i
                    # If the anchor PFX block is preceded by one or more cross-product
                    # comment lines, insert before those comments to keep them attached
                    # to the anchor block.
                    while insert_idx > 0 and lines[insert_idx - 1].strip().startswith("# Cross product"):
                        insert_idx -= 1
                    break

        if insert_idx is not None:
            new_lines = lines[:insert_idx] + [block] + lines[insert_idx:]
        else:
            new_lines = lines
            if new_lines and not new_lines[-1].endswith(chr(10)):
                new_lines[-1] += chr(10)
            new_lines.append(block)

    with open(AFF_FILE, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    print("{}: updated in place.".format(out_flag))

if __name__ == '__main__':
    main()
