import re
import os
from pathlib import Path

# Cross product generator: FD x Ob => HA
# Description:
# - Left block `FD`: FD
# - Right block `Ob`: Object markers
# - Output flag `HA`: Cross-product prefixes for FD x Ob

REPO_ROOT = Path(__file__).resolve().parents[1]
AFF_FILE = REPO_ROOT / "Luganda.aff"

# If set to a flag name (e.g. "HB"), the generated cross-product block will be inserted
# immediately before the first "PFX <flag>" line when the output flag block doesn't
# already exist in the .aff.
INSERT_BEFORE_FLAG = "".strip() or None

rule_left_raw = """
PFX FD Y 2830
PFX FD 0 wengu .
PFX FD 0 wengi .
PFX FD 0 wenzi .
PFX FD 0 wenki .
PFX FD 0 wenga .
PFX FD 0 wenka .
PFX FD 0 wenku .
PFX FD 0 wentu .
PFX FD 0 wemba .
PFX FD 0 wembi .
PFX FD 0 wembu .
PFX FD 0 wendi .
PFX FD 0 wendu .
PFX FD 0 wetun [^lmnb]
PFX FD l wetund l.[^mn]
PFX FD l wetunn l.[mn]
PFX FD w wetump [w]
PFX FD 0 wetumu .
PFX FD 0 wetuba .
PFX FD 0 wetugu .
PFX FD 0 wetugi .
PFX FD 0 wetuzi .
PFX FD 0 wetuki .
PFX FD 0 wetubi .
PFX FD 0 wetuli .
PFX FD 0 wetuga .
PFX FD 0 wetuka .
PFX FD 0 wetubu .
PFX FD 0 wetulu .
PFX FD 0 wetuku .
PFX FD 0 wetutu .
PFX FD 0 wemun [^lmnb]
PFX FD l wemund l.[^mn]
PFX FD l wemunn l.[mn]
PFX FD w wemump [w]
PFX FD 0 wemumu .
PFX FD 0 wemuba .
PFX FD 0 wemugu .
PFX FD 0 wemugi .
PFX FD 0 wemuzi .
PFX FD 0 wemuki .
PFX FD 0 wemubi .
PFX FD 0 wemuli .
PFX FD 0 wemuga .
PFX FD 0 wemuka .
PFX FD 0 wemubu .
PFX FD 0 wemulu .
PFX FD 0 wemuku .
PFX FD 0 wemutu .
PFX FD 0 weban [^lmnb]
PFX FD l weband l.[^mn]
PFX FD l webann l.[mn]
PFX FD w webamp [w]
PFX FD 0 webamu .
PFX FD 0 webaba .
PFX FD 0 webagu .
PFX FD 0 webagi .
PFX FD 0 webazi .
PFX FD 0 webaki .
PFX FD 0 webabi .
PFX FD 0 webali .
PFX FD 0 webaga .
PFX FD 0 webaka .
PFX FD 0 webabu .
PFX FD 0 webalu .
PFX FD 0 webaku .
PFX FD 0 webatu .
PFX FD 0 wegun [^lmnb]
PFX FD l wegund l.[^mn]
PFX FD l wegunn l.[mn]
PFX FD w wegump [w]
PFX FD 0 wegumu .
PFX FD 0 weguba .
PFX FD 0 wegugu .
PFX FD 0 wegugi .
PFX FD 0 weguzi .
PFX FD 0 weguki .
PFX FD 0 wegubi .
PFX FD 0 weguli .
PFX FD 0 weguga .
PFX FD 0 weguka .
PFX FD 0 wegubu .
PFX FD 0 wegulu .
PFX FD 0 weguku .
PFX FD 0 wegutu .
PFX FD 0 wegin [^lmnb]
PFX FD l wegind l.[^mn]
PFX FD l weginn l.[mn]
PFX FD w wegimp [w]
PFX FD 0 wegimu .
PFX FD 0 wegiba .
PFX FD 0 wegigu .
PFX FD 0 wegigi .
PFX FD 0 wegizi .
PFX FD 0 wegiki .
PFX FD 0 wegibi .
PFX FD 0 wegili .
PFX FD 0 wegiga .
PFX FD 0 wegika .
PFX FD 0 wegibu .
PFX FD 0 wegilu .
PFX FD 0 wegiku .
PFX FD 0 wegitu .
PFX FD 0 wezin [^lmnb]
PFX FD l wezind l.[^mn]
PFX FD l wezinn l.[mn]
PFX FD w wezimp [w]
PFX FD 0 wezimu .
PFX FD 0 weziba .
PFX FD 0 wezigu .
PFX FD 0 wezigi .
PFX FD 0 wezizi .
PFX FD 0 weziki .
PFX FD 0 wezibi .
PFX FD 0 wezili .
PFX FD 0 weziga .
PFX FD 0 wezika .
PFX FD 0 wezibu .
PFX FD 0 wezilu .
PFX FD 0 weziku .
PFX FD 0 wezitu .
PFX FD 0 wekin [^lmnb]
PFX FD l wekind l.[^mn]
PFX FD l wekinn l.[mn]
PFX FD w wekimp [w]
PFX FD 0 wekimu .
PFX FD 0 wekiba .
PFX FD 0 wekigu .
PFX FD 0 wekigi .
PFX FD 0 wekizi .
PFX FD 0 wekiki .
PFX FD 0 wekibi .
PFX FD 0 wekili .
PFX FD 0 wekiga .
PFX FD 0 wekika .
PFX FD 0 wekibu .
PFX FD 0 wekilu .
PFX FD 0 wekiku .
PFX FD 0 wekitu .
PFX FD 0 webin [^lmnb]
PFX FD l webind l.[^mn]
PFX FD l webinn l.[mn]
PFX FD w webimp [w]
PFX FD 0 webimu .
PFX FD 0 webiba .
PFX FD 0 webigu .
PFX FD 0 webigi .
PFX FD 0 webizi .
PFX FD 0 webiki .
PFX FD 0 webibi .
PFX FD 0 webili .
PFX FD 0 webiga .
PFX FD 0 webika .
PFX FD 0 webibu .
PFX FD 0 webilu .
PFX FD 0 webiku .
PFX FD 0 webitu .
PFX FD 0 welin [^lmnb]
PFX FD l welind l.[^mn]
PFX FD l welinn l.[mn]
PFX FD w welimp [w]
PFX FD 0 welimu .
PFX FD 0 weliba .
PFX FD 0 weligu .
PFX FD 0 weligi .
PFX FD 0 welizi .
PFX FD 0 weliki .
PFX FD 0 welibi .
PFX FD 0 welili .
PFX FD 0 weliga .
PFX FD 0 welika .
PFX FD 0 welibu .
PFX FD 0 welilu .
PFX FD 0 weliku .
PFX FD 0 welitu .
PFX FD 0 wegan [^lmnb]
PFX FD l wegand l.[^mn]
PFX FD l wegann l.[mn]
PFX FD w wegamp [w]
PFX FD 0 wegamu .
PFX FD 0 wegaba .
PFX FD 0 wegagu .
PFX FD 0 wegagi .
PFX FD 0 wegazi .
PFX FD 0 wegaki .
PFX FD 0 wegabi .
PFX FD 0 wegali .
PFX FD 0 wegaga .
PFX FD 0 wegaka .
PFX FD 0 wegabu .
PFX FD 0 wegalu .
PFX FD 0 wegaku .
PFX FD 0 wegatu .
PFX FD 0 wekan [^lmnb]
PFX FD l wekand l.[^mn]
PFX FD l wekann l.[mn]
PFX FD w wekamp [w]
PFX FD 0 wekamu .
PFX FD 0 wekaba .
PFX FD 0 wekagu .
PFX FD 0 wekagi .
PFX FD 0 wekazi .
PFX FD 0 wekaki .
PFX FD 0 wekabi .
PFX FD 0 wekali .
PFX FD 0 wekaga .
PFX FD 0 wekaka .
PFX FD 0 wekabu .
PFX FD 0 wekalu .
PFX FD 0 wekaku .
PFX FD 0 wekatu .
PFX FD 0 webun [^lmnb]
PFX FD l webund l.[^mn]
PFX FD l webunn l.[mn]
PFX FD w webump [w]
PFX FD 0 webumu .
PFX FD 0 webuba .
PFX FD 0 webugu .
PFX FD 0 webugi .
PFX FD 0 webuzi .
PFX FD 0 webuki .
PFX FD 0 webubi .
PFX FD 0 webuli .
PFX FD 0 webuga .
PFX FD 0 webuka .
PFX FD 0 webubu .
PFX FD 0 webulu .
PFX FD 0 webuku .
PFX FD 0 webutu .
PFX FD 0 welun [^lmnb]
PFX FD l welund l.[^mn]
PFX FD l welunn l.[mn]
PFX FD w welump [w]
PFX FD 0 welumu .
PFX FD 0 weluba .
PFX FD 0 welugu .
PFX FD 0 welugi .
PFX FD 0 weluzi .
PFX FD 0 weluki .
PFX FD 0 welubi .
PFX FD 0 weluli .
PFX FD 0 weluga .
PFX FD 0 weluka .
PFX FD 0 welubu .
PFX FD 0 welulu .
PFX FD 0 weluku .
PFX FD 0 welutu .
PFX FD 0 wekun [^lmnb]
PFX FD l wekund l.[^mn]
PFX FD l wekunn l.[mn]
PFX FD w wekump [w]
PFX FD 0 wekumu .
PFX FD 0 wekuba .
PFX FD 0 wekugu .
PFX FD 0 wekugi .
PFX FD 0 wekuzi .
PFX FD 0 wekuki .
PFX FD 0 wekubi .
PFX FD 0 wekuli .
PFX FD 0 wekuga .
PFX FD 0 wekuka .
PFX FD 0 wekubu .
PFX FD 0 wekulu .
PFX FD 0 wekuku .
PFX FD 0 wekutu .
PFX FD 0 wetun [^lmnb]
PFX FD l wetund l.[^mn]
PFX FD l wetunn l.[mn]
PFX FD w wetump [w]
PFX FD 0 wetumu .
PFX FD 0 wetuba .
PFX FD 0 wetugu .
PFX FD 0 wetugi .
PFX FD 0 wetuzi .
PFX FD 0 wetuki .
PFX FD 0 wetubi .
PFX FD 0 wetuli .
PFX FD 0 wetuga .
PFX FD 0 wetuka .
PFX FD 0 wetubu .
PFX FD 0 wetulu .
PFX FD 0 wetuku .
PFX FD 0 wetutu .
PFX FD 0 bwengu .
PFX FD 0 bwengi .
PFX FD 0 bwenzi .
PFX FD 0 bwenki .
PFX FD 0 bwenga .
PFX FD 0 bwenka .
PFX FD 0 bwenku .
PFX FD 0 bwentu .
PFX FD 0 bwemba .
PFX FD 0 bwembi .
PFX FD 0 bwembu .
PFX FD 0 bwendi .
PFX FD 0 bwendu .
PFX FD 0 bwetun [^lmnb]
PFX FD l bwetund l.[^mn]
PFX FD l bwetunn l.[mn]
PFX FD w bwetump [w]
PFX FD 0 bwetumu .
PFX FD 0 bwetuba .
PFX FD 0 bwetugu .
PFX FD 0 bwetugi .
PFX FD 0 bwetuzi .
PFX FD 0 bwetuki .
PFX FD 0 bwetubi .
PFX FD 0 bwetuli .
PFX FD 0 bwetuga .
PFX FD 0 bwetuka .
PFX FD 0 bwetubu .
PFX FD 0 bwetulu .
PFX FD 0 bwetuku .
PFX FD 0 bwetutu .
PFX FD 0 bwemun [^lmnb]
PFX FD l bwemund l.[^mn]
PFX FD l bwemunn l.[mn]
PFX FD w bwemump [w]
PFX FD 0 bwemumu .
PFX FD 0 bwemuba .
PFX FD 0 bwemugu .
PFX FD 0 bwemugi .
PFX FD 0 bwemuzi .
PFX FD 0 bwemuki .
PFX FD 0 bwemubi .
PFX FD 0 bwemuli .
PFX FD 0 bwemuga .
PFX FD 0 bwemuka .
PFX FD 0 bwemubu .
PFX FD 0 bwemulu .
PFX FD 0 bwemuku .
PFX FD 0 bwemutu .
PFX FD 0 bweban [^lmnb]
PFX FD l bweband l.[^mn]
PFX FD l bwebann l.[mn]
PFX FD w bwebamp [w]
PFX FD 0 bwebamu .
PFX FD 0 bwebaba .
PFX FD 0 bwebagu .
PFX FD 0 bwebagi .
PFX FD 0 bwebazi .
PFX FD 0 bwebaki .
PFX FD 0 bwebabi .
PFX FD 0 bwebali .
PFX FD 0 bwebaga .
PFX FD 0 bwebaka .
PFX FD 0 bwebabu .
PFX FD 0 bwebalu .
PFX FD 0 bwebaku .
PFX FD 0 bwebatu .
PFX FD 0 bwegun [^lmnb]
PFX FD l bwegund l.[^mn]
PFX FD l bwegunn l.[mn]
PFX FD w bwegump [w]
PFX FD 0 bwegumu .
PFX FD 0 bweguba .
PFX FD 0 bwegugu .
PFX FD 0 bwegugi .
PFX FD 0 bweguzi .
PFX FD 0 bweguki .
PFX FD 0 bwegubi .
PFX FD 0 bweguli .
PFX FD 0 bweguga .
PFX FD 0 bweguka .
PFX FD 0 bwegubu .
PFX FD 0 bwegulu .
PFX FD 0 bweguku .
PFX FD 0 bwegutu .
PFX FD 0 bwegin [^lmnb]
PFX FD l bwegind l.[^mn]
PFX FD l bweginn l.[mn]
PFX FD w bwegimp [w]
PFX FD 0 bwegimu .
PFX FD 0 bwegiba .
PFX FD 0 bwegigu .
PFX FD 0 bwegigi .
PFX FD 0 bwegizi .
PFX FD 0 bwegiki .
PFX FD 0 bwegibi .
PFX FD 0 bwegili .
PFX FD 0 bwegiga .
PFX FD 0 bwegika .
PFX FD 0 bwegibu .
PFX FD 0 bwegilu .
PFX FD 0 bwegiku .
PFX FD 0 bwegitu .
PFX FD 0 bwezin [^lmnb]
PFX FD l bwezind l.[^mn]
PFX FD l bwezinn l.[mn]
PFX FD w bwezimp [w]
PFX FD 0 bwezimu .
PFX FD 0 bweziba .
PFX FD 0 bwezigu .
PFX FD 0 bwezigi .
PFX FD 0 bwezizi .
PFX FD 0 bweziki .
PFX FD 0 bwezibi .
PFX FD 0 bwezili .
PFX FD 0 bweziga .
PFX FD 0 bwezika .
PFX FD 0 bwezibu .
PFX FD 0 bwezilu .
PFX FD 0 bweziku .
PFX FD 0 bwezitu .
PFX FD 0 bwekin [^lmnb]
PFX FD l bwekind l.[^mn]
PFX FD l bwekinn l.[mn]
PFX FD w bwekimp [w]
PFX FD 0 bwekimu .
PFX FD 0 bwekiba .
PFX FD 0 bwekigu .
PFX FD 0 bwekigi .
PFX FD 0 bwekizi .
PFX FD 0 bwekiki .
PFX FD 0 bwekibi .
PFX FD 0 bwekili .
PFX FD 0 bwekiga .
PFX FD 0 bwekika .
PFX FD 0 bwekibu .
PFX FD 0 bwekilu .
PFX FD 0 bwekiku .
PFX FD 0 bwekitu .
PFX FD 0 bwebin [^lmnb]
PFX FD l bwebind l.[^mn]
PFX FD l bwebinn l.[mn]
PFX FD w bwebimp [w]
PFX FD 0 bwebimu .
PFX FD 0 bwebiba .
PFX FD 0 bwebigu .
PFX FD 0 bwebigi .
PFX FD 0 bwebizi .
PFX FD 0 bwebiki .
PFX FD 0 bwebibi .
PFX FD 0 bwebili .
PFX FD 0 bwebiga .
PFX FD 0 bwebika .
PFX FD 0 bwebibu .
PFX FD 0 bwebilu .
PFX FD 0 bwebiku .
PFX FD 0 bwebitu .
PFX FD 0 bwelin [^lmnb]
PFX FD l bwelind l.[^mn]
PFX FD l bwelinn l.[mn]
PFX FD w bwelimp [w]
PFX FD 0 bwelimu .
PFX FD 0 bweliba .
PFX FD 0 bweligu .
PFX FD 0 bweligi .
PFX FD 0 bwelizi .
PFX FD 0 bweliki .
PFX FD 0 bwelibi .
PFX FD 0 bwelili .
PFX FD 0 bweliga .
PFX FD 0 bwelika .
PFX FD 0 bwelibu .
PFX FD 0 bwelilu .
PFX FD 0 bweliku .
PFX FD 0 bwelitu .
PFX FD 0 bwegan [^lmnb]
PFX FD l bwegand l.[^mn]
PFX FD l bwegann l.[mn]
PFX FD w bwegamp [w]
PFX FD 0 bwegamu .
PFX FD 0 bwegaba .
PFX FD 0 bwegagu .
PFX FD 0 bwegagi .
PFX FD 0 bwegazi .
PFX FD 0 bwegaki .
PFX FD 0 bwegabi .
PFX FD 0 bwegali .
PFX FD 0 bwegaga .
PFX FD 0 bwegaka .
PFX FD 0 bwegabu .
PFX FD 0 bwegalu .
PFX FD 0 bwegaku .
PFX FD 0 bwegatu .
PFX FD 0 bwekan [^lmnb]
PFX FD l bwekand l.[^mn]
PFX FD l bwekann l.[mn]
PFX FD w bwekamp [w]
PFX FD 0 bwekamu .
PFX FD 0 bwekaba .
PFX FD 0 bwekagu .
PFX FD 0 bwekagi .
PFX FD 0 bwekazi .
PFX FD 0 bwekaki .
PFX FD 0 bwekabi .
PFX FD 0 bwekali .
PFX FD 0 bwekaga .
PFX FD 0 bwekaka .
PFX FD 0 bwekabu .
PFX FD 0 bwekalu .
PFX FD 0 bwekaku .
PFX FD 0 bwekatu .
PFX FD 0 bwebun [^lmnb]
PFX FD l bwebund l.[^mn]
PFX FD l bwebunn l.[mn]
PFX FD w bwebump [w]
PFX FD 0 bwebumu .
PFX FD 0 bwebuba .
PFX FD 0 bwebugu .
PFX FD 0 bwebugi .
PFX FD 0 bwebuzi .
PFX FD 0 bwebuki .
PFX FD 0 bwebubi .
PFX FD 0 bwebuli .
PFX FD 0 bwebuga .
PFX FD 0 bwebuka .
PFX FD 0 bwebubu .
PFX FD 0 bwebulu .
PFX FD 0 bwebuku .
PFX FD 0 bwebutu .
PFX FD 0 bwelun [^lmnb]
PFX FD l bwelund l.[^mn]
PFX FD l bwelunn l.[mn]
PFX FD w bwelump [w]
PFX FD 0 bwelumu .
PFX FD 0 bweluba .
PFX FD 0 bwelugu .
PFX FD 0 bwelugi .
PFX FD 0 bweluzi .
PFX FD 0 bweluki .
PFX FD 0 bwelubi .
PFX FD 0 bweluli .
PFX FD 0 bweluga .
PFX FD 0 bweluka .
PFX FD 0 bwelubu .
PFX FD 0 bwelulu .
PFX FD 0 bweluku .
PFX FD 0 bwelutu .
PFX FD 0 bwekun [^lmnb]
PFX FD l bwekund l.[^mn]
PFX FD l bwekunn l.[mn]
PFX FD w bwekump [w]
PFX FD 0 bwekumu .
PFX FD 0 bwekuba .
PFX FD 0 bwekugu .
PFX FD 0 bwekugi .
PFX FD 0 bwekuzi .
PFX FD 0 bwekuki .
PFX FD 0 bwekubi .
PFX FD 0 bwekuli .
PFX FD 0 bwekuga .
PFX FD 0 bwekuka .
PFX FD 0 bwekubu .
PFX FD 0 bwekulu .
PFX FD 0 bwekuku .
PFX FD 0 bwekutu .
PFX FD 0 bwetun [^lmnb]
PFX FD l bwetund l.[^mn]
PFX FD l bwetunn l.[mn]
PFX FD w bwetump [w]
PFX FD 0 bwetumu .
PFX FD 0 bwetuba .
PFX FD 0 bwetugu .
PFX FD 0 bwetugi .
PFX FD 0 bwetuzi .
PFX FD 0 bwetuki .
PFX FD 0 bwetubi .
PFX FD 0 bwetuli .
PFX FD 0 bwetuga .
PFX FD 0 bwetuka .
PFX FD 0 bwetubu .
PFX FD 0 bwetulu .
PFX FD 0 bwetuku .
PFX FD 0 bwetutu .
PFX FD 0 lwengu .
PFX FD 0 lwengi .
PFX FD 0 lwenzi .
PFX FD 0 lwenki .
PFX FD 0 lwenga .
PFX FD 0 lwenka .
PFX FD 0 lwenku .
PFX FD 0 lwentu .
PFX FD 0 lwemba .
PFX FD 0 lwembi .
PFX FD 0 lwembu .
PFX FD 0 lwendi .
PFX FD 0 lwendu .
PFX FD 0 lwetun [^lmnb]
PFX FD l lwetund l.[^mn]
PFX FD l lwetunn l.[mn]
PFX FD w lwetump [w]
PFX FD 0 lwetumu .
PFX FD 0 lwetuba .
PFX FD 0 lwetugu .
PFX FD 0 lwetugi .
PFX FD 0 lwetuzi .
PFX FD 0 lwetuki .
PFX FD 0 lwetubi .
PFX FD 0 lwetuli .
PFX FD 0 lwetuga .
PFX FD 0 lwetuka .
PFX FD 0 lwetubu .
PFX FD 0 lwetulu .
PFX FD 0 lwetuku .
PFX FD 0 lwetutu .
PFX FD 0 lwemun [^lmnb]
PFX FD l lwemund l.[^mn]
PFX FD l lwemunn l.[mn]
PFX FD w lwemump [w]
PFX FD 0 lwemumu .
PFX FD 0 lwemuba .
PFX FD 0 lwemugu .
PFX FD 0 lwemugi .
PFX FD 0 lwemuzi .
PFX FD 0 lwemuki .
PFX FD 0 lwemubi .
PFX FD 0 lwemuli .
PFX FD 0 lwemuga .
PFX FD 0 lwemuka .
PFX FD 0 lwemubu .
PFX FD 0 lwemulu .
PFX FD 0 lwemuku .
PFX FD 0 lwemutu .
PFX FD 0 lweban [^lmnb]
PFX FD l lweband l.[^mn]
PFX FD l lwebann l.[mn]
PFX FD w lwebamp [w]
PFX FD 0 lwebamu .
PFX FD 0 lwebaba .
PFX FD 0 lwebagu .
PFX FD 0 lwebagi .
PFX FD 0 lwebazi .
PFX FD 0 lwebaki .
PFX FD 0 lwebabi .
PFX FD 0 lwebali .
PFX FD 0 lwebaga .
PFX FD 0 lwebaka .
PFX FD 0 lwebabu .
PFX FD 0 lwebalu .
PFX FD 0 lwebaku .
PFX FD 0 lwebatu .
PFX FD 0 lwegun [^lmnb]
PFX FD l lwegund l.[^mn]
PFX FD l lwegunn l.[mn]
PFX FD w lwegump [w]
PFX FD 0 lwegumu .
PFX FD 0 lweguba .
PFX FD 0 lwegugu .
PFX FD 0 lwegugi .
PFX FD 0 lweguzi .
PFX FD 0 lweguki .
PFX FD 0 lwegubi .
PFX FD 0 lweguli .
PFX FD 0 lweguga .
PFX FD 0 lweguka .
PFX FD 0 lwegubu .
PFX FD 0 lwegulu .
PFX FD 0 lweguku .
PFX FD 0 lwegutu .
PFX FD 0 lwegin [^lmnb]
PFX FD l lwegind l.[^mn]
PFX FD l lweginn l.[mn]
PFX FD w lwegimp [w]
PFX FD 0 lwegimu .
PFX FD 0 lwegiba .
PFX FD 0 lwegigu .
PFX FD 0 lwegigi .
PFX FD 0 lwegizi .
PFX FD 0 lwegiki .
PFX FD 0 lwegibi .
PFX FD 0 lwegili .
PFX FD 0 lwegiga .
PFX FD 0 lwegika .
PFX FD 0 lwegibu .
PFX FD 0 lwegilu .
PFX FD 0 lwegiku .
PFX FD 0 lwegitu .
PFX FD 0 lwezin [^lmnb]
PFX FD l lwezind l.[^mn]
PFX FD l lwezinn l.[mn]
PFX FD w lwezimp [w]
PFX FD 0 lwezimu .
PFX FD 0 lweziba .
PFX FD 0 lwezigu .
PFX FD 0 lwezigi .
PFX FD 0 lwezizi .
PFX FD 0 lweziki .
PFX FD 0 lwezibi .
PFX FD 0 lwezili .
PFX FD 0 lweziga .
PFX FD 0 lwezika .
PFX FD 0 lwezibu .
PFX FD 0 lwezilu .
PFX FD 0 lweziku .
PFX FD 0 lwezitu .
PFX FD 0 lwekin [^lmnb]
PFX FD l lwekind l.[^mn]
PFX FD l lwekinn l.[mn]
PFX FD w lwekimp [w]
PFX FD 0 lwekimu .
PFX FD 0 lwekiba .
PFX FD 0 lwekigu .
PFX FD 0 lwekigi .
PFX FD 0 lwekizi .
PFX FD 0 lwekiki .
PFX FD 0 lwekibi .
PFX FD 0 lwekili .
PFX FD 0 lwekiga .
PFX FD 0 lwekika .
PFX FD 0 lwekibu .
PFX FD 0 lwekilu .
PFX FD 0 lwekiku .
PFX FD 0 lwekitu .
PFX FD 0 lwebin [^lmnb]
PFX FD l lwebind l.[^mn]
PFX FD l lwebinn l.[mn]
PFX FD w lwebimp [w]
PFX FD 0 lwebimu .
PFX FD 0 lwebiba .
PFX FD 0 lwebigu .
PFX FD 0 lwebigi .
PFX FD 0 lwebizi .
PFX FD 0 lwebiki .
PFX FD 0 lwebibi .
PFX FD 0 lwebili .
PFX FD 0 lwebiga .
PFX FD 0 lwebika .
PFX FD 0 lwebibu .
PFX FD 0 lwebilu .
PFX FD 0 lwebiku .
PFX FD 0 lwebitu .
PFX FD 0 lwelin [^lmnb]
PFX FD l lwelind l.[^mn]
PFX FD l lwelinn l.[mn]
PFX FD w lwelimp [w]
PFX FD 0 lwelimu .
PFX FD 0 lweliba .
PFX FD 0 lweligu .
PFX FD 0 lweligi .
PFX FD 0 lwelizi .
PFX FD 0 lweliki .
PFX FD 0 lwelibi .
PFX FD 0 lwelili .
PFX FD 0 lweliga .
PFX FD 0 lwelika .
PFX FD 0 lwelibu .
PFX FD 0 lwelilu .
PFX FD 0 lweliku .
PFX FD 0 lwelitu .
PFX FD 0 lwegan [^lmnb]
PFX FD l lwegand l.[^mn]
PFX FD l lwegann l.[mn]
PFX FD w lwegamp [w]
PFX FD 0 lwegamu .
PFX FD 0 lwegaba .
PFX FD 0 lwegagu .
PFX FD 0 lwegagi .
PFX FD 0 lwegazi .
PFX FD 0 lwegaki .
PFX FD 0 lwegabi .
PFX FD 0 lwegali .
PFX FD 0 lwegaga .
PFX FD 0 lwegaka .
PFX FD 0 lwegabu .
PFX FD 0 lwegalu .
PFX FD 0 lwegaku .
PFX FD 0 lwegatu .
PFX FD 0 lwekan [^lmnb]
PFX FD l lwekand l.[^mn]
PFX FD l lwekann l.[mn]
PFX FD w lwekamp [w]
PFX FD 0 lwekamu .
PFX FD 0 lwekaba .
PFX FD 0 lwekagu .
PFX FD 0 lwekagi .
PFX FD 0 lwekazi .
PFX FD 0 lwekaki .
PFX FD 0 lwekabi .
PFX FD 0 lwekali .
PFX FD 0 lwekaga .
PFX FD 0 lwekaka .
PFX FD 0 lwekabu .
PFX FD 0 lwekalu .
PFX FD 0 lwekaku .
PFX FD 0 lwekatu .
PFX FD 0 lwebun [^lmnb]
PFX FD l lwebund l.[^mn]
PFX FD l lwebunn l.[mn]
PFX FD w lwebump [w]
PFX FD 0 lwebumu .
PFX FD 0 lwebuba .
PFX FD 0 lwebugu .
PFX FD 0 lwebugi .
PFX FD 0 lwebuzi .
PFX FD 0 lwebuki .
PFX FD 0 lwebubi .
PFX FD 0 lwebuli .
PFX FD 0 lwebuga .
PFX FD 0 lwebuka .
PFX FD 0 lwebubu .
PFX FD 0 lwebulu .
PFX FD 0 lwebuku .
PFX FD 0 lwebutu .
PFX FD 0 lwelun [^lmnb]
PFX FD l lwelund l.[^mn]
PFX FD l lwelunn l.[mn]
PFX FD w lwelump [w]
PFX FD 0 lwelumu .
PFX FD 0 lweluba .
PFX FD 0 lwelugu .
PFX FD 0 lwelugi .
PFX FD 0 lweluzi .
PFX FD 0 lweluki .
PFX FD 0 lwelubi .
PFX FD 0 lweluli .
PFX FD 0 lweluga .
PFX FD 0 lweluka .
PFX FD 0 lwelubu .
PFX FD 0 lwelulu .
PFX FD 0 lweluku .
PFX FD 0 lwelutu .
PFX FD 0 lwekun [^lmnb]
PFX FD l lwekund l.[^mn]
PFX FD l lwekunn l.[mn]
PFX FD w lwekump [w]
PFX FD 0 lwekumu .
PFX FD 0 lwekuba .
PFX FD 0 lwekugu .
PFX FD 0 lwekugi .
PFX FD 0 lwekuzi .
PFX FD 0 lwekuki .
PFX FD 0 lwekubi .
PFX FD 0 lwekuli .
PFX FD 0 lwekuga .
PFX FD 0 lwekuka .
PFX FD 0 lwekubu .
PFX FD 0 lwekulu .
PFX FD 0 lwekuku .
PFX FD 0 lwekutu .
PFX FD 0 lwetun [^lmnb]
PFX FD l lwetund l.[^mn]
PFX FD l lwetunn l.[mn]
PFX FD w lwetump [w]
PFX FD 0 lwetumu .
PFX FD 0 lwetuba .
PFX FD 0 lwetugu .
PFX FD 0 lwetugi .
PFX FD 0 lwetuzi .
PFX FD 0 lwetuki .
PFX FD 0 lwetubi .
PFX FD 0 lwetuli .
PFX FD 0 lwetuga .
PFX FD 0 lwetuka .
PFX FD 0 lwetubu .
PFX FD 0 lwetulu .
PFX FD 0 lwetuku .
PFX FD 0 lwetutu .
PFX FD 0 zengu .
PFX FD 0 zengi .
PFX FD 0 zenzi .
PFX FD 0 zenki .
PFX FD 0 zenga .
PFX FD 0 zenka .
PFX FD 0 zenku .
PFX FD 0 zentu .
PFX FD 0 zemba .
PFX FD 0 zembi .
PFX FD 0 zembu .
PFX FD 0 zendi .
PFX FD 0 zendu .
PFX FD 0 zetun [^lmnb]
PFX FD l zetund l.[^mn]
PFX FD l zetunn l.[mn]
PFX FD w zetump [w]
PFX FD 0 zetumu .
PFX FD 0 zetuba .
PFX FD 0 zetugu .
PFX FD 0 zetugi .
PFX FD 0 zetuzi .
PFX FD 0 zetuki .
PFX FD 0 zetubi .
PFX FD 0 zetuli .
PFX FD 0 zetuga .
PFX FD 0 zetuka .
PFX FD 0 zetubu .
PFX FD 0 zetulu .
PFX FD 0 zetuku .
PFX FD 0 zetutu .
PFX FD 0 zemun [^lmnb]
PFX FD l zemund l.[^mn]
PFX FD l zemunn l.[mn]
PFX FD w zemump [w]
PFX FD 0 zemumu .
PFX FD 0 zemuba .
PFX FD 0 zemugu .
PFX FD 0 zemugi .
PFX FD 0 zemuzi .
PFX FD 0 zemuki .
PFX FD 0 zemubi .
PFX FD 0 zemuli .
PFX FD 0 zemuga .
PFX FD 0 zemuka .
PFX FD 0 zemubu .
PFX FD 0 zemulu .
PFX FD 0 zemuku .
PFX FD 0 zemutu .
PFX FD 0 zeban [^lmnb]
PFX FD l zeband l.[^mn]
PFX FD l zebann l.[mn]
PFX FD w zebamp [w]
PFX FD 0 zebamu .
PFX FD 0 zebaba .
PFX FD 0 zebagu .
PFX FD 0 zebagi .
PFX FD 0 zebazi .
PFX FD 0 zebaki .
PFX FD 0 zebabi .
PFX FD 0 zebali .
PFX FD 0 zebaga .
PFX FD 0 zebaka .
PFX FD 0 zebabu .
PFX FD 0 zebalu .
PFX FD 0 zebaku .
PFX FD 0 zebatu .
PFX FD 0 zegun [^lmnb]
PFX FD l zegund l.[^mn]
PFX FD l zegunn l.[mn]
PFX FD w zegump [w]
PFX FD 0 zegumu .
PFX FD 0 zeguba .
PFX FD 0 zegugu .
PFX FD 0 zegugi .
PFX FD 0 zeguzi .
PFX FD 0 zeguki .
PFX FD 0 zegubi .
PFX FD 0 zeguli .
PFX FD 0 zeguga .
PFX FD 0 zeguka .
PFX FD 0 zegubu .
PFX FD 0 zegulu .
PFX FD 0 zeguku .
PFX FD 0 zegutu .
PFX FD 0 zegin [^lmnb]
PFX FD l zegind l.[^mn]
PFX FD l zeginn l.[mn]
PFX FD w zegimp [w]
PFX FD 0 zegimu .
PFX FD 0 zegiba .
PFX FD 0 zegigu .
PFX FD 0 zegigi .
PFX FD 0 zegizi .
PFX FD 0 zegiki .
PFX FD 0 zegibi .
PFX FD 0 zegili .
PFX FD 0 zegiga .
PFX FD 0 zegika .
PFX FD 0 zegibu .
PFX FD 0 zegilu .
PFX FD 0 zegiku .
PFX FD 0 zegitu .
PFX FD 0 zezin [^lmnb]
PFX FD l zezind l.[^mn]
PFX FD l zezinn l.[mn]
PFX FD w zezimp [w]
PFX FD 0 zezimu .
PFX FD 0 zeziba .
PFX FD 0 zezigu .
PFX FD 0 zezigi .
PFX FD 0 zezizi .
PFX FD 0 zeziki .
PFX FD 0 zezibi .
PFX FD 0 zezili .
PFX FD 0 zeziga .
PFX FD 0 zezika .
PFX FD 0 zezibu .
PFX FD 0 zezilu .
PFX FD 0 zeziku .
PFX FD 0 zezitu .
PFX FD 0 zekin [^lmnb]
PFX FD l zekind l.[^mn]
PFX FD l zekinn l.[mn]
PFX FD w zekimp [w]
PFX FD 0 zekimu .
PFX FD 0 zekiba .
PFX FD 0 zekigu .
PFX FD 0 zekigi .
PFX FD 0 zekizi .
PFX FD 0 zekiki .
PFX FD 0 zekibi .
PFX FD 0 zekili .
PFX FD 0 zekiga .
PFX FD 0 zekika .
PFX FD 0 zekibu .
PFX FD 0 zekilu .
PFX FD 0 zekiku .
PFX FD 0 zekitu .
PFX FD 0 zebin [^lmnb]
PFX FD l zebind l.[^mn]
PFX FD l zebinn l.[mn]
PFX FD w zebimp [w]
PFX FD 0 zebimu .
PFX FD 0 zebiba .
PFX FD 0 zebigu .
PFX FD 0 zebigi .
PFX FD 0 zebizi .
PFX FD 0 zebiki .
PFX FD 0 zebibi .
PFX FD 0 zebili .
PFX FD 0 zebiga .
PFX FD 0 zebika .
PFX FD 0 zebibu .
PFX FD 0 zebilu .
PFX FD 0 zebiku .
PFX FD 0 zebitu .
PFX FD 0 zelin [^lmnb]
PFX FD l zelind l.[^mn]
PFX FD l zelinn l.[mn]
PFX FD w zelimp [w]
PFX FD 0 zelimu .
PFX FD 0 zeliba .
PFX FD 0 zeligu .
PFX FD 0 zeligi .
PFX FD 0 zelizi .
PFX FD 0 zeliki .
PFX FD 0 zelibi .
PFX FD 0 zelili .
PFX FD 0 zeliga .
PFX FD 0 zelika .
PFX FD 0 zelibu .
PFX FD 0 zelilu .
PFX FD 0 zeliku .
PFX FD 0 zelitu .
PFX FD 0 zegan [^lmnb]
PFX FD l zegand l.[^mn]
PFX FD l zegann l.[mn]
PFX FD w zegamp [w]
PFX FD 0 zegamu .
PFX FD 0 zegaba .
PFX FD 0 zegagu .
PFX FD 0 zegagi .
PFX FD 0 zegazi .
PFX FD 0 zegaki .
PFX FD 0 zegabi .
PFX FD 0 zegali .
PFX FD 0 zegaga .
PFX FD 0 zegaka .
PFX FD 0 zegabu .
PFX FD 0 zegalu .
PFX FD 0 zegaku .
PFX FD 0 zegatu .
PFX FD 0 zekan [^lmnb]
PFX FD l zekand l.[^mn]
PFX FD l zekann l.[mn]
PFX FD w zekamp [w]
PFX FD 0 zekamu .
PFX FD 0 zekaba .
PFX FD 0 zekagu .
PFX FD 0 zekagi .
PFX FD 0 zekazi .
PFX FD 0 zekaki .
PFX FD 0 zekabi .
PFX FD 0 zekali .
PFX FD 0 zekaga .
PFX FD 0 zekaka .
PFX FD 0 zekabu .
PFX FD 0 zekalu .
PFX FD 0 zekaku .
PFX FD 0 zekatu .
PFX FD 0 zebun [^lmnb]
PFX FD l zebund l.[^mn]
PFX FD l zebunn l.[mn]
PFX FD w zebump [w]
PFX FD 0 zebumu .
PFX FD 0 zebuba .
PFX FD 0 zebugu .
PFX FD 0 zebugi .
PFX FD 0 zebuzi .
PFX FD 0 zebuki .
PFX FD 0 zebubi .
PFX FD 0 zebuli .
PFX FD 0 zebuga .
PFX FD 0 zebuka .
PFX FD 0 zebubu .
PFX FD 0 zebulu .
PFX FD 0 zebuku .
PFX FD 0 zebutu .
PFX FD 0 zelun [^lmnb]
PFX FD l zelund l.[^mn]
PFX FD l zelunn l.[mn]
PFX FD w zelump [w]
PFX FD 0 zelumu .
PFX FD 0 zeluba .
PFX FD 0 zelugu .
PFX FD 0 zelugi .
PFX FD 0 zeluzi .
PFX FD 0 zeluki .
PFX FD 0 zelubi .
PFX FD 0 zeluli .
PFX FD 0 zeluga .
PFX FD 0 zeluka .
PFX FD 0 zelubu .
PFX FD 0 zelulu .
PFX FD 0 zeluku .
PFX FD 0 zelutu .
PFX FD 0 zekun [^lmnb]
PFX FD l zekund l.[^mn]
PFX FD l zekunn l.[mn]
PFX FD w zekump [w]
PFX FD 0 zekumu .
PFX FD 0 zekuba .
PFX FD 0 zekugu .
PFX FD 0 zekugi .
PFX FD 0 zekuzi .
PFX FD 0 zekuki .
PFX FD 0 zekubi .
PFX FD 0 zekuli .
PFX FD 0 zekuga .
PFX FD 0 zekuka .
PFX FD 0 zekubu .
PFX FD 0 zekulu .
PFX FD 0 zekuku .
PFX FD 0 zekutu .
PFX FD 0 zetun [^lmnb]
PFX FD l zetund l.[^mn]
PFX FD l zetunn l.[mn]
PFX FD w zetump [w]
PFX FD 0 zetumu .
PFX FD 0 zetuba .
PFX FD 0 zetugu .
PFX FD 0 zetugi .
PFX FD 0 zetuzi .
PFX FD 0 zetuki .
PFX FD 0 zetubi .
PFX FD 0 zetuli .
PFX FD 0 zetuga .
PFX FD 0 zetuka .
PFX FD 0 zetubu .
PFX FD 0 zetulu .
PFX FD 0 zetuku .
PFX FD 0 zetutu .
PFX FD 0 gwengu .
PFX FD 0 gwengi .
PFX FD 0 gwenzi .
PFX FD 0 gwenki .
PFX FD 0 gwenga .
PFX FD 0 gwenka .
PFX FD 0 gwenku .
PFX FD 0 gwentu .
PFX FD 0 gwemba .
PFX FD 0 gwembi .
PFX FD 0 gwembu .
PFX FD 0 gwendi .
PFX FD 0 gwendu .
PFX FD 0 gwetun [^lmnb]
PFX FD l gwetund l.[^mn]
PFX FD l gwetunn l.[mn]
PFX FD w gwetump [w]
PFX FD 0 gwetumu .
PFX FD 0 gwetuba .
PFX FD 0 gwetugu .
PFX FD 0 gwetugi .
PFX FD 0 gwetuzi .
PFX FD 0 gwetuki .
PFX FD 0 gwetubi .
PFX FD 0 gwetuli .
PFX FD 0 gwetuga .
PFX FD 0 gwetuka .
PFX FD 0 gwetubu .
PFX FD 0 gwetulu .
PFX FD 0 gwetuku .
PFX FD 0 gwetutu .
PFX FD 0 gwemun [^lmnb]
PFX FD l gwemund l.[^mn]
PFX FD l gwemunn l.[mn]
PFX FD w gwemump [w]
PFX FD 0 gwemumu .
PFX FD 0 gwemuba .
PFX FD 0 gwemugu .
PFX FD 0 gwemugi .
PFX FD 0 gwemuzi .
PFX FD 0 gwemuki .
PFX FD 0 gwemubi .
PFX FD 0 gwemuli .
PFX FD 0 gwemuga .
PFX FD 0 gwemuka .
PFX FD 0 gwemubu .
PFX FD 0 gwemulu .
PFX FD 0 gwemuku .
PFX FD 0 gwemutu .
PFX FD 0 gweban [^lmnb]
PFX FD l gweband l.[^mn]
PFX FD l gwebann l.[mn]
PFX FD w gwebamp [w]
PFX FD 0 gwebamu .
PFX FD 0 gwebaba .
PFX FD 0 gwebagu .
PFX FD 0 gwebagi .
PFX FD 0 gwebazi .
PFX FD 0 gwebaki .
PFX FD 0 gwebabi .
PFX FD 0 gwebali .
PFX FD 0 gwebaga .
PFX FD 0 gwebaka .
PFX FD 0 gwebabu .
PFX FD 0 gwebalu .
PFX FD 0 gwebaku .
PFX FD 0 gwebatu .
PFX FD 0 gwegun [^lmnb]
PFX FD l gwegund l.[^mn]
PFX FD l gwegunn l.[mn]
PFX FD w gwegump [w]
PFX FD 0 gwegumu .
PFX FD 0 gweguba .
PFX FD 0 gwegugu .
PFX FD 0 gwegugi .
PFX FD 0 gweguzi .
PFX FD 0 gweguki .
PFX FD 0 gwegubi .
PFX FD 0 gweguli .
PFX FD 0 gweguga .
PFX FD 0 gweguka .
PFX FD 0 gwegubu .
PFX FD 0 gwegulu .
PFX FD 0 gweguku .
PFX FD 0 gwegutu .
PFX FD 0 gwegin [^lmnb]
PFX FD l gwegind l.[^mn]
PFX FD l gweginn l.[mn]
PFX FD w gwegimp [w]
PFX FD 0 gwegimu .
PFX FD 0 gwegiba .
PFX FD 0 gwegigu .
PFX FD 0 gwegigi .
PFX FD 0 gwegizi .
PFX FD 0 gwegiki .
PFX FD 0 gwegibi .
PFX FD 0 gwegili .
PFX FD 0 gwegiga .
PFX FD 0 gwegika .
PFX FD 0 gwegibu .
PFX FD 0 gwegilu .
PFX FD 0 gwegiku .
PFX FD 0 gwegitu .
PFX FD 0 gwezin [^lmnb]
PFX FD l gwezind l.[^mn]
PFX FD l gwezinn l.[mn]
PFX FD w gwezimp [w]
PFX FD 0 gwezimu .
PFX FD 0 gweziba .
PFX FD 0 gwezigu .
PFX FD 0 gwezigi .
PFX FD 0 gwezizi .
PFX FD 0 gweziki .
PFX FD 0 gwezibi .
PFX FD 0 gwezili .
PFX FD 0 gweziga .
PFX FD 0 gwezika .
PFX FD 0 gwezibu .
PFX FD 0 gwezilu .
PFX FD 0 gweziku .
PFX FD 0 gwezitu .
PFX FD 0 gwekin [^lmnb]
PFX FD l gwekind l.[^mn]
PFX FD l gwekinn l.[mn]
PFX FD w gwekimp [w]
PFX FD 0 gwekimu .
PFX FD 0 gwekiba .
PFX FD 0 gwekigu .
PFX FD 0 gwekigi .
PFX FD 0 gwekizi .
PFX FD 0 gwekiki .
PFX FD 0 gwekibi .
PFX FD 0 gwekili .
PFX FD 0 gwekiga .
PFX FD 0 gwekika .
PFX FD 0 gwekibu .
PFX FD 0 gwekilu .
PFX FD 0 gwekiku .
PFX FD 0 gwekitu .
PFX FD 0 gwebin [^lmnb]
PFX FD l gwebind l.[^mn]
PFX FD l gwebinn l.[mn]
PFX FD w gwebimp [w]
PFX FD 0 gwebimu .
PFX FD 0 gwebiba .
PFX FD 0 gwebigu .
PFX FD 0 gwebigi .
PFX FD 0 gwebizi .
PFX FD 0 gwebiki .
PFX FD 0 gwebibi .
PFX FD 0 gwebili .
PFX FD 0 gwebiga .
PFX FD 0 gwebika .
PFX FD 0 gwebibu .
PFX FD 0 gwebilu .
PFX FD 0 gwebiku .
PFX FD 0 gwebitu .
PFX FD 0 gwelin [^lmnb]
PFX FD l gwelind l.[^mn]
PFX FD l gwelinn l.[mn]
PFX FD w gwelimp [w]
PFX FD 0 gwelimu .
PFX FD 0 gweliba .
PFX FD 0 gweligu .
PFX FD 0 gweligi .
PFX FD 0 gwelizi .
PFX FD 0 gweliki .
PFX FD 0 gwelibi .
PFX FD 0 gwelili .
PFX FD 0 gweliga .
PFX FD 0 gwelika .
PFX FD 0 gwelibu .
PFX FD 0 gwelilu .
PFX FD 0 gweliku .
PFX FD 0 gwelitu .
PFX FD 0 gwegan [^lmnb]
PFX FD l gwegand l.[^mn]
PFX FD l gwegann l.[mn]
PFX FD w gwegamp [w]
PFX FD 0 gwegamu .
PFX FD 0 gwegaba .
PFX FD 0 gwegagu .
PFX FD 0 gwegagi .
PFX FD 0 gwegazi .
PFX FD 0 gwegaki .
PFX FD 0 gwegabi .
PFX FD 0 gwegali .
PFX FD 0 gwegaga .
PFX FD 0 gwegaka .
PFX FD 0 gwegabu .
PFX FD 0 gwegalu .
PFX FD 0 gwegaku .
PFX FD 0 gwegatu .
PFX FD 0 gwekan [^lmnb]
PFX FD l gwekand l.[^mn]
PFX FD l gwekann l.[mn]
PFX FD w gwekamp [w]
PFX FD 0 gwekamu .
PFX FD 0 gwekaba .
PFX FD 0 gwekagu .
PFX FD 0 gwekagi .
PFX FD 0 gwekazi .
PFX FD 0 gwekaki .
PFX FD 0 gwekabi .
PFX FD 0 gwekali .
PFX FD 0 gwekaga .
PFX FD 0 gwekaka .
PFX FD 0 gwekabu .
PFX FD 0 gwekalu .
PFX FD 0 gwekaku .
PFX FD 0 gwekatu .
PFX FD 0 gwebun [^lmnb]
PFX FD l gwebund l.[^mn]
PFX FD l gwebunn l.[mn]
PFX FD w gwebump [w]
PFX FD 0 gwebumu .
PFX FD 0 gwebuba .
PFX FD 0 gwebugu .
PFX FD 0 gwebugi .
PFX FD 0 gwebuzi .
PFX FD 0 gwebuki .
PFX FD 0 gwebubi .
PFX FD 0 gwebuli .
PFX FD 0 gwebuga .
PFX FD 0 gwebuka .
PFX FD 0 gwebubu .
PFX FD 0 gwebulu .
PFX FD 0 gwebuku .
PFX FD 0 gwebutu .
PFX FD 0 gwelun [^lmnb]
PFX FD l gwelund l.[^mn]
PFX FD l gwelunn l.[mn]
PFX FD w gwelump [w]
PFX FD 0 gwelumu .
PFX FD 0 gweluba .
PFX FD 0 gwelugu .
PFX FD 0 gwelugi .
PFX FD 0 gweluzi .
PFX FD 0 gweluki .
PFX FD 0 gwelubi .
PFX FD 0 gweluli .
PFX FD 0 gweluga .
PFX FD 0 gweluka .
PFX FD 0 gwelubu .
PFX FD 0 gwelulu .
PFX FD 0 gweluku .
PFX FD 0 gwelutu .
PFX FD 0 gwekun [^lmnb]
PFX FD l gwekund l.[^mn]
PFX FD l gwekunn l.[mn]
PFX FD w gwekump [w]
PFX FD 0 gwekumu .
PFX FD 0 gwekuba .
PFX FD 0 gwekugu .
PFX FD 0 gwekugi .
PFX FD 0 gwekuzi .
PFX FD 0 gwekuki .
PFX FD 0 gwekubi .
PFX FD 0 gwekuli .
PFX FD 0 gwekuga .
PFX FD 0 gwekuka .
PFX FD 0 gwekubu .
PFX FD 0 gwekulu .
PFX FD 0 gwekuku .
PFX FD 0 gwekutu .
PFX FD 0 gwetun [^lmnb]
PFX FD l gwetund l.[^mn]
PFX FD l gwetunn l.[mn]
PFX FD w gwetump [w]
PFX FD 0 gwetumu .
PFX FD 0 gwetuba .
PFX FD 0 gwetugu .
PFX FD 0 gwetugi .
PFX FD 0 gwetuzi .
PFX FD 0 gwetuki .
PFX FD 0 gwetubi .
PFX FD 0 gwetuli .
PFX FD 0 gwetuga .
PFX FD 0 gwetuka .
PFX FD 0 gwetubu .
PFX FD 0 gwetulu .
PFX FD 0 gwetuku .
PFX FD 0 gwetutu .
PFX FD 0 gyengu .
PFX FD 0 gyengi .
PFX FD 0 gyenzi .
PFX FD 0 gyenki .
PFX FD 0 gyenga .
PFX FD 0 gyenka .
PFX FD 0 gyenku .
PFX FD 0 gyentu .
PFX FD 0 gyemba .
PFX FD 0 gyembi .
PFX FD 0 gyembu .
PFX FD 0 gyendi .
PFX FD 0 gyendu .
PFX FD 0 gyetun [^lmnb]
PFX FD l gyetund l.[^mn]
PFX FD l gyetunn l.[mn]
PFX FD w gyetump [w]
PFX FD 0 gyetumu .
PFX FD 0 gyetuba .
PFX FD 0 gyetugu .
PFX FD 0 gyetugi .
PFX FD 0 gyetuzi .
PFX FD 0 gyetuki .
PFX FD 0 gyetubi .
PFX FD 0 gyetuli .
PFX FD 0 gyetuga .
PFX FD 0 gyetuka .
PFX FD 0 gyetubu .
PFX FD 0 gyetulu .
PFX FD 0 gyetuku .
PFX FD 0 gyetutu .
PFX FD 0 gyemun [^lmnb]
PFX FD l gyemund l.[^mn]
PFX FD l gyemunn l.[mn]
PFX FD w gyemump [w]
PFX FD 0 gyemumu .
PFX FD 0 gyemuba .
PFX FD 0 gyemugu .
PFX FD 0 gyemugi .
PFX FD 0 gyemuzi .
PFX FD 0 gyemuki .
PFX FD 0 gyemubi .
PFX FD 0 gyemuli .
PFX FD 0 gyemuga .
PFX FD 0 gyemuka .
PFX FD 0 gyemubu .
PFX FD 0 gyemulu .
PFX FD 0 gyemuku .
PFX FD 0 gyemutu .
PFX FD 0 gyeban [^lmnb]
PFX FD l gyeband l.[^mn]
PFX FD l gyebann l.[mn]
PFX FD w gyebamp [w]
PFX FD 0 gyebamu .
PFX FD 0 gyebaba .
PFX FD 0 gyebagu .
PFX FD 0 gyebagi .
PFX FD 0 gyebazi .
PFX FD 0 gyebaki .
PFX FD 0 gyebabi .
PFX FD 0 gyebali .
PFX FD 0 gyebaga .
PFX FD 0 gyebaka .
PFX FD 0 gyebabu .
PFX FD 0 gyebalu .
PFX FD 0 gyebaku .
PFX FD 0 gyebatu .
PFX FD 0 gyegun [^lmnb]
PFX FD l gyegund l.[^mn]
PFX FD l gyegunn l.[mn]
PFX FD w gyegump [w]
PFX FD 0 gyegumu .
PFX FD 0 gyeguba .
PFX FD 0 gyegugu .
PFX FD 0 gyegugi .
PFX FD 0 gyeguzi .
PFX FD 0 gyeguki .
PFX FD 0 gyegubi .
PFX FD 0 gyeguli .
PFX FD 0 gyeguga .
PFX FD 0 gyeguka .
PFX FD 0 gyegubu .
PFX FD 0 gyegulu .
PFX FD 0 gyeguku .
PFX FD 0 gyegutu .
PFX FD 0 gyegin [^lmnb]
PFX FD l gyegind l.[^mn]
PFX FD l gyeginn l.[mn]
PFX FD w gyegimp [w]
PFX FD 0 gyegimu .
PFX FD 0 gyegiba .
PFX FD 0 gyegigu .
PFX FD 0 gyegigi .
PFX FD 0 gyegizi .
PFX FD 0 gyegiki .
PFX FD 0 gyegibi .
PFX FD 0 gyegili .
PFX FD 0 gyegiga .
PFX FD 0 gyegika .
PFX FD 0 gyegibu .
PFX FD 0 gyegilu .
PFX FD 0 gyegiku .
PFX FD 0 gyegitu .
PFX FD 0 gyezin [^lmnb]
PFX FD l gyezind l.[^mn]
PFX FD l gyezinn l.[mn]
PFX FD w gyezimp [w]
PFX FD 0 gyezimu .
PFX FD 0 gyeziba .
PFX FD 0 gyezigu .
PFX FD 0 gyezigi .
PFX FD 0 gyezizi .
PFX FD 0 gyeziki .
PFX FD 0 gyezibi .
PFX FD 0 gyezili .
PFX FD 0 gyeziga .
PFX FD 0 gyezika .
PFX FD 0 gyezibu .
PFX FD 0 gyezilu .
PFX FD 0 gyeziku .
PFX FD 0 gyezitu .
PFX FD 0 gyekin [^lmnb]
PFX FD l gyekind l.[^mn]
PFX FD l gyekinn l.[mn]
PFX FD w gyekimp [w]
PFX FD 0 gyekimu .
PFX FD 0 gyekiba .
PFX FD 0 gyekigu .
PFX FD 0 gyekigi .
PFX FD 0 gyekizi .
PFX FD 0 gyekiki .
PFX FD 0 gyekibi .
PFX FD 0 gyekili .
PFX FD 0 gyekiga .
PFX FD 0 gyekika .
PFX FD 0 gyekibu .
PFX FD 0 gyekilu .
PFX FD 0 gyekiku .
PFX FD 0 gyekitu .
PFX FD 0 gyebin [^lmnb]
PFX FD l gyebind l.[^mn]
PFX FD l gyebinn l.[mn]
PFX FD w gyebimp [w]
PFX FD 0 gyebimu .
PFX FD 0 gyebiba .
PFX FD 0 gyebigu .
PFX FD 0 gyebigi .
PFX FD 0 gyebizi .
PFX FD 0 gyebiki .
PFX FD 0 gyebibi .
PFX FD 0 gyebili .
PFX FD 0 gyebiga .
PFX FD 0 gyebika .
PFX FD 0 gyebibu .
PFX FD 0 gyebilu .
PFX FD 0 gyebiku .
PFX FD 0 gyebitu .
PFX FD 0 gyelin [^lmnb]
PFX FD l gyelind l.[^mn]
PFX FD l gyelinn l.[mn]
PFX FD w gyelimp [w]
PFX FD 0 gyelimu .
PFX FD 0 gyeliba .
PFX FD 0 gyeligu .
PFX FD 0 gyeligi .
PFX FD 0 gyelizi .
PFX FD 0 gyeliki .
PFX FD 0 gyelibi .
PFX FD 0 gyelili .
PFX FD 0 gyeliga .
PFX FD 0 gyelika .
PFX FD 0 gyelibu .
PFX FD 0 gyelilu .
PFX FD 0 gyeliku .
PFX FD 0 gyelitu .
PFX FD 0 gyegan [^lmnb]
PFX FD l gyegand l.[^mn]
PFX FD l gyegann l.[mn]
PFX FD w gyegamp [w]
PFX FD 0 gyegamu .
PFX FD 0 gyegaba .
PFX FD 0 gyegagu .
PFX FD 0 gyegagi .
PFX FD 0 gyegazi .
PFX FD 0 gyegaki .
PFX FD 0 gyegabi .
PFX FD 0 gyegali .
PFX FD 0 gyegaga .
PFX FD 0 gyegaka .
PFX FD 0 gyegabu .
PFX FD 0 gyegalu .
PFX FD 0 gyegaku .
PFX FD 0 gyegatu .
PFX FD 0 gyekan [^lmnb]
PFX FD l gyekand l.[^mn]
PFX FD l gyekann l.[mn]
PFX FD w gyekamp [w]
PFX FD 0 gyekamu .
PFX FD 0 gyekaba .
PFX FD 0 gyekagu .
PFX FD 0 gyekagi .
PFX FD 0 gyekazi .
PFX FD 0 gyekaki .
PFX FD 0 gyekabi .
PFX FD 0 gyekali .
PFX FD 0 gyekaga .
PFX FD 0 gyekaka .
PFX FD 0 gyekabu .
PFX FD 0 gyekalu .
PFX FD 0 gyekaku .
PFX FD 0 gyekatu .
PFX FD 0 gyebun [^lmnb]
PFX FD l gyebund l.[^mn]
PFX FD l gyebunn l.[mn]
PFX FD w gyebump [w]
PFX FD 0 gyebumu .
PFX FD 0 gyebuba .
PFX FD 0 gyebugu .
PFX FD 0 gyebugi .
PFX FD 0 gyebuzi .
PFX FD 0 gyebuki .
PFX FD 0 gyebubi .
PFX FD 0 gyebuli .
PFX FD 0 gyebuga .
PFX FD 0 gyebuka .
PFX FD 0 gyebubu .
PFX FD 0 gyebulu .
PFX FD 0 gyebuku .
PFX FD 0 gyebutu .
PFX FD 0 gyelun [^lmnb]
PFX FD l gyelund l.[^mn]
PFX FD l gyelunn l.[mn]
PFX FD w gyelump [w]
PFX FD 0 gyelumu .
PFX FD 0 gyeluba .
PFX FD 0 gyelugu .
PFX FD 0 gyelugi .
PFX FD 0 gyeluzi .
PFX FD 0 gyeluki .
PFX FD 0 gyelubi .
PFX FD 0 gyeluli .
PFX FD 0 gyeluga .
PFX FD 0 gyeluka .
PFX FD 0 gyelubu .
PFX FD 0 gyelulu .
PFX FD 0 gyeluku .
PFX FD 0 gyelutu .
PFX FD 0 gyekun [^lmnb]
PFX FD l gyekund l.[^mn]
PFX FD l gyekunn l.[mn]
PFX FD w gyekump [w]
PFX FD 0 gyekumu .
PFX FD 0 gyekuba .
PFX FD 0 gyekugu .
PFX FD 0 gyekugi .
PFX FD 0 gyekuzi .
PFX FD 0 gyekuki .
PFX FD 0 gyekubi .
PFX FD 0 gyekuli .
PFX FD 0 gyekuga .
PFX FD 0 gyekuka .
PFX FD 0 gyekubu .
PFX FD 0 gyekulu .
PFX FD 0 gyekuku .
PFX FD 0 gyekutu .
PFX FD 0 gyetun [^lmnb]
PFX FD l gyetund l.[^mn]
PFX FD l gyetunn l.[mn]
PFX FD w gyetump [w]
PFX FD 0 gyetumu .
PFX FD 0 gyetuba .
PFX FD 0 gyetugu .
PFX FD 0 gyetugi .
PFX FD 0 gyetuzi .
PFX FD 0 gyetuki .
PFX FD 0 gyetubi .
PFX FD 0 gyetuli .
PFX FD 0 gyetuga .
PFX FD 0 gyetuka .
PFX FD 0 gyetubu .
PFX FD 0 gyetulu .
PFX FD 0 gyetuku .
PFX FD 0 gyetutu .
PFX FD 0 kyengu .
PFX FD 0 kyengi .
PFX FD 0 kyenzi .
PFX FD 0 kyenki .
PFX FD 0 kyenga .
PFX FD 0 kyenka .
PFX FD 0 kyenku .
PFX FD 0 kyentu .
PFX FD 0 kyemba .
PFX FD 0 kyembi .
PFX FD 0 kyembu .
PFX FD 0 kyendi .
PFX FD 0 kyendu .
PFX FD 0 kyetun [^lmnb]
PFX FD l kyetund l.[^mn]
PFX FD l kyetunn l.[mn]
PFX FD w kyetump [w]
PFX FD 0 kyetumu .
PFX FD 0 kyetuba .
PFX FD 0 kyetugu .
PFX FD 0 kyetugi .
PFX FD 0 kyetuzi .
PFX FD 0 kyetuki .
PFX FD 0 kyetubi .
PFX FD 0 kyetuli .
PFX FD 0 kyetuga .
PFX FD 0 kyetuka .
PFX FD 0 kyetubu .
PFX FD 0 kyetulu .
PFX FD 0 kyetuku .
PFX FD 0 kyetutu .
PFX FD 0 kyemun [^lmnb]
PFX FD l kyemund l.[^mn]
PFX FD l kyemunn l.[mn]
PFX FD w kyemump [w]
PFX FD 0 kyemumu .
PFX FD 0 kyemuba .
PFX FD 0 kyemugu .
PFX FD 0 kyemugi .
PFX FD 0 kyemuzi .
PFX FD 0 kyemuki .
PFX FD 0 kyemubi .
PFX FD 0 kyemuli .
PFX FD 0 kyemuga .
PFX FD 0 kyemuka .
PFX FD 0 kyemubu .
PFX FD 0 kyemulu .
PFX FD 0 kyemuku .
PFX FD 0 kyemutu .
PFX FD 0 kyeban [^lmnb]
PFX FD l kyeband l.[^mn]
PFX FD l kyebann l.[mn]
PFX FD w kyebamp [w]
PFX FD 0 kyebamu .
PFX FD 0 kyebaba .
PFX FD 0 kyebagu .
PFX FD 0 kyebagi .
PFX FD 0 kyebazi .
PFX FD 0 kyebaki .
PFX FD 0 kyebabi .
PFX FD 0 kyebali .
PFX FD 0 kyebaga .
PFX FD 0 kyebaka .
PFX FD 0 kyebabu .
PFX FD 0 kyebalu .
PFX FD 0 kyebaku .
PFX FD 0 kyebatu .
PFX FD 0 kyegun [^lmnb]
PFX FD l kyegund l.[^mn]
PFX FD l kyegunn l.[mn]
PFX FD w kyegump [w]
PFX FD 0 kyegumu .
PFX FD 0 kyeguba .
PFX FD 0 kyegugu .
PFX FD 0 kyegugi .
PFX FD 0 kyeguzi .
PFX FD 0 kyeguki .
PFX FD 0 kyegubi .
PFX FD 0 kyeguli .
PFX FD 0 kyeguga .
PFX FD 0 kyeguka .
PFX FD 0 kyegubu .
PFX FD 0 kyegulu .
PFX FD 0 kyeguku .
PFX FD 0 kyegutu .
PFX FD 0 kyegin [^lmnb]
PFX FD l kyegind l.[^mn]
PFX FD l kyeginn l.[mn]
PFX FD w kyegimp [w]
PFX FD 0 kyegimu .
PFX FD 0 kyegiba .
PFX FD 0 kyegigu .
PFX FD 0 kyegigi .
PFX FD 0 kyegizi .
PFX FD 0 kyegiki .
PFX FD 0 kyegibi .
PFX FD 0 kyegili .
PFX FD 0 kyegiga .
PFX FD 0 kyegika .
PFX FD 0 kyegibu .
PFX FD 0 kyegilu .
PFX FD 0 kyegiku .
PFX FD 0 kyegitu .
PFX FD 0 kyezin [^lmnb]
PFX FD l kyezind l.[^mn]
PFX FD l kyezinn l.[mn]
PFX FD w kyezimp [w]
PFX FD 0 kyezimu .
PFX FD 0 kyeziba .
PFX FD 0 kyezigu .
PFX FD 0 kyezigi .
PFX FD 0 kyezizi .
PFX FD 0 kyeziki .
PFX FD 0 kyezibi .
PFX FD 0 kyezili .
PFX FD 0 kyeziga .
PFX FD 0 kyezika .
PFX FD 0 kyezibu .
PFX FD 0 kyezilu .
PFX FD 0 kyeziku .
PFX FD 0 kyezitu .
PFX FD 0 kyekin [^lmnb]
PFX FD l kyekind l.[^mn]
PFX FD l kyekinn l.[mn]
PFX FD w kyekimp [w]
PFX FD 0 kyekimu .
PFX FD 0 kyekiba .
PFX FD 0 kyekigu .
PFX FD 0 kyekigi .
PFX FD 0 kyekizi .
PFX FD 0 kyekiki .
PFX FD 0 kyekibi .
PFX FD 0 kyekili .
PFX FD 0 kyekiga .
PFX FD 0 kyekika .
PFX FD 0 kyekibu .
PFX FD 0 kyekilu .
PFX FD 0 kyekiku .
PFX FD 0 kyekitu .
PFX FD 0 kyebin [^lmnb]
PFX FD l kyebind l.[^mn]
PFX FD l kyebinn l.[mn]
PFX FD w kyebimp [w]
PFX FD 0 kyebimu .
PFX FD 0 kyebiba .
PFX FD 0 kyebigu .
PFX FD 0 kyebigi .
PFX FD 0 kyebizi .
PFX FD 0 kyebiki .
PFX FD 0 kyebibi .
PFX FD 0 kyebili .
PFX FD 0 kyebiga .
PFX FD 0 kyebika .
PFX FD 0 kyebibu .
PFX FD 0 kyebilu .
PFX FD 0 kyebiku .
PFX FD 0 kyebitu .
PFX FD 0 kyelin [^lmnb]
PFX FD l kyelind l.[^mn]
PFX FD l kyelinn l.[mn]
PFX FD w kyelimp [w]
PFX FD 0 kyelimu .
PFX FD 0 kyeliba .
PFX FD 0 kyeligu .
PFX FD 0 kyeligi .
PFX FD 0 kyelizi .
PFX FD 0 kyeliki .
PFX FD 0 kyelibi .
PFX FD 0 kyelili .
PFX FD 0 kyeliga .
PFX FD 0 kyelika .
PFX FD 0 kyelibu .
PFX FD 0 kyelilu .
PFX FD 0 kyeliku .
PFX FD 0 kyelitu .
PFX FD 0 kyegan [^lmnb]
PFX FD l kyegand l.[^mn]
PFX FD l kyegann l.[mn]
PFX FD w kyegamp [w]
PFX FD 0 kyegamu .
PFX FD 0 kyegaba .
PFX FD 0 kyegagu .
PFX FD 0 kyegagi .
PFX FD 0 kyegazi .
PFX FD 0 kyegaki .
PFX FD 0 kyegabi .
PFX FD 0 kyegali .
PFX FD 0 kyegaga .
PFX FD 0 kyegaka .
PFX FD 0 kyegabu .
PFX FD 0 kyegalu .
PFX FD 0 kyegaku .
PFX FD 0 kyegatu .
PFX FD 0 kyekan [^lmnb]
PFX FD l kyekand l.[^mn]
PFX FD l kyekann l.[mn]
PFX FD w kyekamp [w]
PFX FD 0 kyekamu .
PFX FD 0 kyekaba .
PFX FD 0 kyekagu .
PFX FD 0 kyekagi .
PFX FD 0 kyekazi .
PFX FD 0 kyekaki .
PFX FD 0 kyekabi .
PFX FD 0 kyekali .
PFX FD 0 kyekaga .
PFX FD 0 kyekaka .
PFX FD 0 kyekabu .
PFX FD 0 kyekalu .
PFX FD 0 kyekaku .
PFX FD 0 kyekatu .
PFX FD 0 kyebun [^lmnb]
PFX FD l kyebund l.[^mn]
PFX FD l kyebunn l.[mn]
PFX FD w kyebump [w]
PFX FD 0 kyebumu .
PFX FD 0 kyebuba .
PFX FD 0 kyebugu .
PFX FD 0 kyebugi .
PFX FD 0 kyebuzi .
PFX FD 0 kyebuki .
PFX FD 0 kyebubi .
PFX FD 0 kyebuli .
PFX FD 0 kyebuga .
PFX FD 0 kyebuka .
PFX FD 0 kyebubu .
PFX FD 0 kyebulu .
PFX FD 0 kyebuku .
PFX FD 0 kyebutu .
PFX FD 0 kyelun [^lmnb]
PFX FD l kyelund l.[^mn]
PFX FD l kyelunn l.[mn]
PFX FD w kyelump [w]
PFX FD 0 kyelumu .
PFX FD 0 kyeluba .
PFX FD 0 kyelugu .
PFX FD 0 kyelugi .
PFX FD 0 kyeluzi .
PFX FD 0 kyeluki .
PFX FD 0 kyelubi .
PFX FD 0 kyeluli .
PFX FD 0 kyeluga .
PFX FD 0 kyeluka .
PFX FD 0 kyelubu .
PFX FD 0 kyelulu .
PFX FD 0 kyeluku .
PFX FD 0 kyelutu .
PFX FD 0 kyekun [^lmnb]
PFX FD l kyekund l.[^mn]
PFX FD l kyekunn l.[mn]
PFX FD w kyekump [w]
PFX FD 0 kyekumu .
PFX FD 0 kyekuba .
PFX FD 0 kyekugu .
PFX FD 0 kyekugi .
PFX FD 0 kyekuzi .
PFX FD 0 kyekuki .
PFX FD 0 kyekubi .
PFX FD 0 kyekuli .
PFX FD 0 kyekuga .
PFX FD 0 kyekuka .
PFX FD 0 kyekubu .
PFX FD 0 kyekulu .
PFX FD 0 kyekuku .
PFX FD 0 kyekutu .
PFX FD 0 kyetun [^lmnb]
PFX FD l kyetund l.[^mn]
PFX FD l kyetunn l.[mn]
PFX FD w kyetump [w]
PFX FD 0 kyetumu .
PFX FD 0 kyetuba .
PFX FD 0 kyetugu .
PFX FD 0 kyetugi .
PFX FD 0 kyetuzi .
PFX FD 0 kyetuki .
PFX FD 0 kyetubi .
PFX FD 0 kyetuli .
PFX FD 0 kyetuga .
PFX FD 0 kyetuka .
PFX FD 0 kyetubu .
PFX FD 0 kyetulu .
PFX FD 0 kyetuku .
PFX FD 0 kyetutu .
PFX FD 0 byengu .
PFX FD 0 byengi .
PFX FD 0 byenzi .
PFX FD 0 byenki .
PFX FD 0 byenga .
PFX FD 0 byenka .
PFX FD 0 byenku .
PFX FD 0 byentu .
PFX FD 0 byemba .
PFX FD 0 byembi .
PFX FD 0 byembu .
PFX FD 0 byendi .
PFX FD 0 byendu .
PFX FD 0 byetun [^lmnb]
PFX FD l byetund l.[^mn]
PFX FD l byetunn l.[mn]
PFX FD w byetump [w]
PFX FD 0 byetumu .
PFX FD 0 byetuba .
PFX FD 0 byetugu .
PFX FD 0 byetugi .
PFX FD 0 byetuzi .
PFX FD 0 byetuki .
PFX FD 0 byetubi .
PFX FD 0 byetuli .
PFX FD 0 byetuga .
PFX FD 0 byetuka .
PFX FD 0 byetubu .
PFX FD 0 byetulu .
PFX FD 0 byetuku .
PFX FD 0 byetutu .
PFX FD 0 byemun [^lmnb]
PFX FD l byemund l.[^mn]
PFX FD l byemunn l.[mn]
PFX FD w byemump [w]
PFX FD 0 byemumu .
PFX FD 0 byemuba .
PFX FD 0 byemugu .
PFX FD 0 byemugi .
PFX FD 0 byemuzi .
PFX FD 0 byemuki .
PFX FD 0 byemubi .
PFX FD 0 byemuli .
PFX FD 0 byemuga .
PFX FD 0 byemuka .
PFX FD 0 byemubu .
PFX FD 0 byemulu .
PFX FD 0 byemuku .
PFX FD 0 byemutu .
PFX FD 0 byeban [^lmnb]
PFX FD l byeband l.[^mn]
PFX FD l byebann l.[mn]
PFX FD w byebamp [w]
PFX FD 0 byebamu .
PFX FD 0 byebaba .
PFX FD 0 byebagu .
PFX FD 0 byebagi .
PFX FD 0 byebazi .
PFX FD 0 byebaki .
PFX FD 0 byebabi .
PFX FD 0 byebali .
PFX FD 0 byebaga .
PFX FD 0 byebaka .
PFX FD 0 byebabu .
PFX FD 0 byebalu .
PFX FD 0 byebaku .
PFX FD 0 byebatu .
PFX FD 0 byegun [^lmnb]
PFX FD l byegund l.[^mn]
PFX FD l byegunn l.[mn]
PFX FD w byegump [w]
PFX FD 0 byegumu .
PFX FD 0 byeguba .
PFX FD 0 byegugu .
PFX FD 0 byegugi .
PFX FD 0 byeguzi .
PFX FD 0 byeguki .
PFX FD 0 byegubi .
PFX FD 0 byeguli .
PFX FD 0 byeguga .
PFX FD 0 byeguka .
PFX FD 0 byegubu .
PFX FD 0 byegulu .
PFX FD 0 byeguku .
PFX FD 0 byegutu .
PFX FD 0 byegin [^lmnb]
PFX FD l byegind l.[^mn]
PFX FD l byeginn l.[mn]
PFX FD w byegimp [w]
PFX FD 0 byegimu .
PFX FD 0 byegiba .
PFX FD 0 byegigu .
PFX FD 0 byegigi .
PFX FD 0 byegizi .
PFX FD 0 byegiki .
PFX FD 0 byegibi .
PFX FD 0 byegili .
PFX FD 0 byegiga .
PFX FD 0 byegika .
PFX FD 0 byegibu .
PFX FD 0 byegilu .
PFX FD 0 byegiku .
PFX FD 0 byegitu .
PFX FD 0 byezin [^lmnb]
PFX FD l byezind l.[^mn]
PFX FD l byezinn l.[mn]
PFX FD w byezimp [w]
PFX FD 0 byezimu .
PFX FD 0 byeziba .
PFX FD 0 byezigu .
PFX FD 0 byezigi .
PFX FD 0 byezizi .
PFX FD 0 byeziki .
PFX FD 0 byezibi .
PFX FD 0 byezili .
PFX FD 0 byeziga .
PFX FD 0 byezika .
PFX FD 0 byezibu .
PFX FD 0 byezilu .
PFX FD 0 byeziku .
PFX FD 0 byezitu .
PFX FD 0 byekin [^lmnb]
PFX FD l byekind l.[^mn]
PFX FD l byekinn l.[mn]
PFX FD w byekimp [w]
PFX FD 0 byekimu .
PFX FD 0 byekiba .
PFX FD 0 byekigu .
PFX FD 0 byekigi .
PFX FD 0 byekizi .
PFX FD 0 byekiki .
PFX FD 0 byekibi .
PFX FD 0 byekili .
PFX FD 0 byekiga .
PFX FD 0 byekika .
PFX FD 0 byekibu .
PFX FD 0 byekilu .
PFX FD 0 byekiku .
PFX FD 0 byekitu .
PFX FD 0 byebin [^lmnb]
PFX FD l byebind l.[^mn]
PFX FD l byebinn l.[mn]
PFX FD w byebimp [w]
PFX FD 0 byebimu .
PFX FD 0 byebiba .
PFX FD 0 byebigu .
PFX FD 0 byebigi .
PFX FD 0 byebizi .
PFX FD 0 byebiki .
PFX FD 0 byebibi .
PFX FD 0 byebili .
PFX FD 0 byebiga .
PFX FD 0 byebika .
PFX FD 0 byebibu .
PFX FD 0 byebilu .
PFX FD 0 byebiku .
PFX FD 0 byebitu .
PFX FD 0 byelin [^lmnb]
PFX FD l byelind l.[^mn]
PFX FD l byelinn l.[mn]
PFX FD w byelimp [w]
PFX FD 0 byelimu .
PFX FD 0 byeliba .
PFX FD 0 byeligu .
PFX FD 0 byeligi .
PFX FD 0 byelizi .
PFX FD 0 byeliki .
PFX FD 0 byelibi .
PFX FD 0 byelili .
PFX FD 0 byeliga .
PFX FD 0 byelika .
PFX FD 0 byelibu .
PFX FD 0 byelilu .
PFX FD 0 byeliku .
PFX FD 0 byelitu .
PFX FD 0 byegan [^lmnb]
PFX FD l byegand l.[^mn]
PFX FD l byegann l.[mn]
PFX FD w byegamp [w]
PFX FD 0 byegamu .
PFX FD 0 byegaba .
PFX FD 0 byegagu .
PFX FD 0 byegagi .
PFX FD 0 byegazi .
PFX FD 0 byegaki .
PFX FD 0 byegabi .
PFX FD 0 byegali .
PFX FD 0 byegaga .
PFX FD 0 byegaka .
PFX FD 0 byegabu .
PFX FD 0 byegalu .
PFX FD 0 byegaku .
PFX FD 0 byegatu .
PFX FD 0 byekan [^lmnb]
PFX FD l byekand l.[^mn]
PFX FD l byekann l.[mn]
PFX FD w byekamp [w]
PFX FD 0 byekamu .
PFX FD 0 byekaba .
PFX FD 0 byekagu .
PFX FD 0 byekagi .
PFX FD 0 byekazi .
PFX FD 0 byekaki .
PFX FD 0 byekabi .
PFX FD 0 byekali .
PFX FD 0 byekaga .
PFX FD 0 byekaka .
PFX FD 0 byekabu .
PFX FD 0 byekalu .
PFX FD 0 byekaku .
PFX FD 0 byekatu .
PFX FD 0 byebun [^lmnb]
PFX FD l byebund l.[^mn]
PFX FD l byebunn l.[mn]
PFX FD w byebump [w]
PFX FD 0 byebumu .
PFX FD 0 byebuba .
PFX FD 0 byebugu .
PFX FD 0 byebugi .
PFX FD 0 byebuzi .
PFX FD 0 byebuki .
PFX FD 0 byebubi .
PFX FD 0 byebuli .
PFX FD 0 byebuga .
PFX FD 0 byebuka .
PFX FD 0 byebubu .
PFX FD 0 byebulu .
PFX FD 0 byebuku .
PFX FD 0 byebutu .
PFX FD 0 byelun [^lmnb]
PFX FD l byelund l.[^mn]
PFX FD l byelunn l.[mn]
PFX FD w byelump [w]
PFX FD 0 byelumu .
PFX FD 0 byeluba .
PFX FD 0 byelugu .
PFX FD 0 byelugi .
PFX FD 0 byeluzi .
PFX FD 0 byeluki .
PFX FD 0 byelubi .
PFX FD 0 byeluli .
PFX FD 0 byeluga .
PFX FD 0 byeluka .
PFX FD 0 byelubu .
PFX FD 0 byelulu .
PFX FD 0 byeluku .
PFX FD 0 byelutu .
PFX FD 0 byekun [^lmnb]
PFX FD l byekund l.[^mn]
PFX FD l byekunn l.[mn]
PFX FD w byekump [w]
PFX FD 0 byekumu .
PFX FD 0 byekuba .
PFX FD 0 byekugu .
PFX FD 0 byekugi .
PFX FD 0 byekuzi .
PFX FD 0 byekuki .
PFX FD 0 byekubi .
PFX FD 0 byekuli .
PFX FD 0 byekuga .
PFX FD 0 byekuka .
PFX FD 0 byekubu .
PFX FD 0 byekulu .
PFX FD 0 byekuku .
PFX FD 0 byekutu .
PFX FD 0 byetun [^lmnb]
PFX FD l byetund l.[^mn]
PFX FD l byetunn l.[mn]
PFX FD w byetump [w]
PFX FD 0 byetumu .
PFX FD 0 byetuba .
PFX FD 0 byetugu .
PFX FD 0 byetugi .
PFX FD 0 byetuzi .
PFX FD 0 byetuki .
PFX FD 0 byetubi .
PFX FD 0 byetuli .
PFX FD 0 byetuga .
PFX FD 0 byetuka .
PFX FD 0 byetubu .
PFX FD 0 byetulu .
PFX FD 0 byetuku .
PFX FD 0 byetutu .
PFX FD 0 lyengu .
PFX FD 0 lyengi .
PFX FD 0 lyenzi .
PFX FD 0 lyenki .
PFX FD 0 lyenga .
PFX FD 0 lyenka .
PFX FD 0 lyenku .
PFX FD 0 lyentu .
PFX FD 0 lyemba .
PFX FD 0 lyembi .
PFX FD 0 lyembu .
PFX FD 0 lyendi .
PFX FD 0 lyendu .
PFX FD 0 lyetun [^lmnb]
PFX FD l lyetund l.[^mn]
PFX FD l lyetunn l.[mn]
PFX FD w lyetump [w]
PFX FD 0 lyetumu .
PFX FD 0 lyetuba .
PFX FD 0 lyetugu .
PFX FD 0 lyetugi .
PFX FD 0 lyetuzi .
PFX FD 0 lyetuki .
PFX FD 0 lyetubi .
PFX FD 0 lyetuli .
PFX FD 0 lyetuga .
PFX FD 0 lyetuka .
PFX FD 0 lyetubu .
PFX FD 0 lyetulu .
PFX FD 0 lyetuku .
PFX FD 0 lyetutu .
PFX FD 0 lyemun [^lmnb]
PFX FD l lyemund l.[^mn]
PFX FD l lyemunn l.[mn]
PFX FD w lyemump [w]
PFX FD 0 lyemumu .
PFX FD 0 lyemuba .
PFX FD 0 lyemugu .
PFX FD 0 lyemugi .
PFX FD 0 lyemuzi .
PFX FD 0 lyemuki .
PFX FD 0 lyemubi .
PFX FD 0 lyemuli .
PFX FD 0 lyemuga .
PFX FD 0 lyemuka .
PFX FD 0 lyemubu .
PFX FD 0 lyemulu .
PFX FD 0 lyemuku .
PFX FD 0 lyemutu .
PFX FD 0 lyeban [^lmnb]
PFX FD l lyeband l.[^mn]
PFX FD l lyebann l.[mn]
PFX FD w lyebamp [w]
PFX FD 0 lyebamu .
PFX FD 0 lyebaba .
PFX FD 0 lyebagu .
PFX FD 0 lyebagi .
PFX FD 0 lyebazi .
PFX FD 0 lyebaki .
PFX FD 0 lyebabi .
PFX FD 0 lyebali .
PFX FD 0 lyebaga .
PFX FD 0 lyebaka .
PFX FD 0 lyebabu .
PFX FD 0 lyebalu .
PFX FD 0 lyebaku .
PFX FD 0 lyebatu .
PFX FD 0 lyegun [^lmnb]
PFX FD l lyegund l.[^mn]
PFX FD l lyegunn l.[mn]
PFX FD w lyegump [w]
PFX FD 0 lyegumu .
PFX FD 0 lyeguba .
PFX FD 0 lyegugu .
PFX FD 0 lyegugi .
PFX FD 0 lyeguzi .
PFX FD 0 lyeguki .
PFX FD 0 lyegubi .
PFX FD 0 lyeguli .
PFX FD 0 lyeguga .
PFX FD 0 lyeguka .
PFX FD 0 lyegubu .
PFX FD 0 lyegulu .
PFX FD 0 lyeguku .
PFX FD 0 lyegutu .
PFX FD 0 lyegin [^lmnb]
PFX FD l lyegind l.[^mn]
PFX FD l lyeginn l.[mn]
PFX FD w lyegimp [w]
PFX FD 0 lyegimu .
PFX FD 0 lyegiba .
PFX FD 0 lyegigu .
PFX FD 0 lyegigi .
PFX FD 0 lyegizi .
PFX FD 0 lyegiki .
PFX FD 0 lyegibi .
PFX FD 0 lyegili .
PFX FD 0 lyegiga .
PFX FD 0 lyegika .
PFX FD 0 lyegibu .
PFX FD 0 lyegilu .
PFX FD 0 lyegiku .
PFX FD 0 lyegitu .
PFX FD 0 lyezin [^lmnb]
PFX FD l lyezind l.[^mn]
PFX FD l lyezinn l.[mn]
PFX FD w lyezimp [w]
PFX FD 0 lyezimu .
PFX FD 0 lyeziba .
PFX FD 0 lyezigu .
PFX FD 0 lyezigi .
PFX FD 0 lyezizi .
PFX FD 0 lyeziki .
PFX FD 0 lyezibi .
PFX FD 0 lyezili .
PFX FD 0 lyeziga .
PFX FD 0 lyezika .
PFX FD 0 lyezibu .
PFX FD 0 lyezilu .
PFX FD 0 lyeziku .
PFX FD 0 lyezitu .
PFX FD 0 lyekin [^lmnb]
PFX FD l lyekind l.[^mn]
PFX FD l lyekinn l.[mn]
PFX FD w lyekimp [w]
PFX FD 0 lyekimu .
PFX FD 0 lyekiba .
PFX FD 0 lyekigu .
PFX FD 0 lyekigi .
PFX FD 0 lyekizi .
PFX FD 0 lyekiki .
PFX FD 0 lyekibi .
PFX FD 0 lyekili .
PFX FD 0 lyekiga .
PFX FD 0 lyekika .
PFX FD 0 lyekibu .
PFX FD 0 lyekilu .
PFX FD 0 lyekiku .
PFX FD 0 lyekitu .
PFX FD 0 lyebin [^lmnb]
PFX FD l lyebind l.[^mn]
PFX FD l lyebinn l.[mn]
PFX FD w lyebimp [w]
PFX FD 0 lyebimu .
PFX FD 0 lyebiba .
PFX FD 0 lyebigu .
PFX FD 0 lyebigi .
PFX FD 0 lyebizi .
PFX FD 0 lyebiki .
PFX FD 0 lyebibi .
PFX FD 0 lyebili .
PFX FD 0 lyebiga .
PFX FD 0 lyebika .
PFX FD 0 lyebibu .
PFX FD 0 lyebilu .
PFX FD 0 lyebiku .
PFX FD 0 lyebitu .
PFX FD 0 lyelin [^lmnb]
PFX FD l lyelind l.[^mn]
PFX FD l lyelinn l.[mn]
PFX FD w lyelimp [w]
PFX FD 0 lyelimu .
PFX FD 0 lyeliba .
PFX FD 0 lyeligu .
PFX FD 0 lyeligi .
PFX FD 0 lyelizi .
PFX FD 0 lyeliki .
PFX FD 0 lyelibi .
PFX FD 0 lyelili .
PFX FD 0 lyeliga .
PFX FD 0 lyelika .
PFX FD 0 lyelibu .
PFX FD 0 lyelilu .
PFX FD 0 lyeliku .
PFX FD 0 lyelitu .
PFX FD 0 lyegan [^lmnb]
PFX FD l lyegand l.[^mn]
PFX FD l lyegann l.[mn]
PFX FD w lyegamp [w]
PFX FD 0 lyegamu .
PFX FD 0 lyegaba .
PFX FD 0 lyegagu .
PFX FD 0 lyegagi .
PFX FD 0 lyegazi .
PFX FD 0 lyegaki .
PFX FD 0 lyegabi .
PFX FD 0 lyegali .
PFX FD 0 lyegaga .
PFX FD 0 lyegaka .
PFX FD 0 lyegabu .
PFX FD 0 lyegalu .
PFX FD 0 lyegaku .
PFX FD 0 lyegatu .
PFX FD 0 lyekan [^lmnb]
PFX FD l lyekand l.[^mn]
PFX FD l lyekann l.[mn]
PFX FD w lyekamp [w]
PFX FD 0 lyekamu .
PFX FD 0 lyekaba .
PFX FD 0 lyekagu .
PFX FD 0 lyekagi .
PFX FD 0 lyekazi .
PFX FD 0 lyekaki .
PFX FD 0 lyekabi .
PFX FD 0 lyekali .
PFX FD 0 lyekaga .
PFX FD 0 lyekaka .
PFX FD 0 lyekabu .
PFX FD 0 lyekalu .
PFX FD 0 lyekaku .
PFX FD 0 lyekatu .
PFX FD 0 lyebun [^lmnb]
PFX FD l lyebund l.[^mn]
PFX FD l lyebunn l.[mn]
PFX FD w lyebump [w]
PFX FD 0 lyebumu .
PFX FD 0 lyebuba .
PFX FD 0 lyebugu .
PFX FD 0 lyebugi .
PFX FD 0 lyebuzi .
PFX FD 0 lyebuki .
PFX FD 0 lyebubi .
PFX FD 0 lyebuli .
PFX FD 0 lyebuga .
PFX FD 0 lyebuka .
PFX FD 0 lyebubu .
PFX FD 0 lyebulu .
PFX FD 0 lyebuku .
PFX FD 0 lyebutu .
PFX FD 0 lyelun [^lmnb]
PFX FD l lyelund l.[^mn]
PFX FD l lyelunn l.[mn]
PFX FD w lyelump [w]
PFX FD 0 lyelumu .
PFX FD 0 lyeluba .
PFX FD 0 lyelugu .
PFX FD 0 lyelugi .
PFX FD 0 lyeluzi .
PFX FD 0 lyeluki .
PFX FD 0 lyelubi .
PFX FD 0 lyeluli .
PFX FD 0 lyeluga .
PFX FD 0 lyeluka .
PFX FD 0 lyelubu .
PFX FD 0 lyelulu .
PFX FD 0 lyeluku .
PFX FD 0 lyelutu .
PFX FD 0 lyekun [^lmnb]
PFX FD l lyekund l.[^mn]
PFX FD l lyekunn l.[mn]
PFX FD w lyekump [w]
PFX FD 0 lyekumu .
PFX FD 0 lyekuba .
PFX FD 0 lyekugu .
PFX FD 0 lyekugi .
PFX FD 0 lyekuzi .
PFX FD 0 lyekuki .
PFX FD 0 lyekubi .
PFX FD 0 lyekuli .
PFX FD 0 lyekuga .
PFX FD 0 lyekuka .
PFX FD 0 lyekubu .
PFX FD 0 lyekulu .
PFX FD 0 lyekuku .
PFX FD 0 lyekutu .
PFX FD 0 lyetun [^lmnb]
PFX FD l lyetund l.[^mn]
PFX FD l lyetunn l.[mn]
PFX FD w lyetump [w]
PFX FD 0 lyetumu .
PFX FD 0 lyetuba .
PFX FD 0 lyetugu .
PFX FD 0 lyetugi .
PFX FD 0 lyetuzi .
PFX FD 0 lyetuki .
PFX FD 0 lyetubi .
PFX FD 0 lyetuli .
PFX FD 0 lyetuga .
PFX FD 0 lyetuka .
PFX FD 0 lyetubu .
PFX FD 0 lyetulu .
PFX FD 0 lyetuku .
PFX FD 0 lyetutu .
PFX FD 0 kengu .
PFX FD 0 kengi .
PFX FD 0 kenzi .
PFX FD 0 kenki .
PFX FD 0 kenga .
PFX FD 0 kenka .
PFX FD 0 kenku .
PFX FD 0 kentu .
PFX FD 0 kemba .
PFX FD 0 kembi .
PFX FD 0 kembu .
PFX FD 0 kendi .
PFX FD 0 kendu .
PFX FD 0 ketun [^lmnb]
PFX FD l ketund l.[^mn]
PFX FD l ketunn l.[mn]
PFX FD w ketump [w]
PFX FD 0 ketumu .
PFX FD 0 ketuba .
PFX FD 0 ketugu .
PFX FD 0 ketugi .
PFX FD 0 ketuzi .
PFX FD 0 ketuki .
PFX FD 0 ketubi .
PFX FD 0 ketuli .
PFX FD 0 ketuga .
PFX FD 0 ketuka .
PFX FD 0 ketubu .
PFX FD 0 ketulu .
PFX FD 0 ketuku .
PFX FD 0 ketutu .
PFX FD 0 kemun [^lmnb]
PFX FD l kemund l.[^mn]
PFX FD l kemunn l.[mn]
PFX FD w kemump [w]
PFX FD 0 kemumu .
PFX FD 0 kemuba .
PFX FD 0 kemugu .
PFX FD 0 kemugi .
PFX FD 0 kemuzi .
PFX FD 0 kemuki .
PFX FD 0 kemubi .
PFX FD 0 kemuli .
PFX FD 0 kemuga .
PFX FD 0 kemuka .
PFX FD 0 kemubu .
PFX FD 0 kemulu .
PFX FD 0 kemuku .
PFX FD 0 kemutu .
PFX FD 0 keban [^lmnb]
PFX FD l keband l.[^mn]
PFX FD l kebann l.[mn]
PFX FD w kebamp [w]
PFX FD 0 kebamu .
PFX FD 0 kebaba .
PFX FD 0 kebagu .
PFX FD 0 kebagi .
PFX FD 0 kebazi .
PFX FD 0 kebaki .
PFX FD 0 kebabi .
PFX FD 0 kebali .
PFX FD 0 kebaga .
PFX FD 0 kebaka .
PFX FD 0 kebabu .
PFX FD 0 kebalu .
PFX FD 0 kebaku .
PFX FD 0 kebatu .
PFX FD 0 kegun [^lmnb]
PFX FD l kegund l.[^mn]
PFX FD l kegunn l.[mn]
PFX FD w kegump [w]
PFX FD 0 kegumu .
PFX FD 0 keguba .
PFX FD 0 kegugu .
PFX FD 0 kegugi .
PFX FD 0 keguzi .
PFX FD 0 keguki .
PFX FD 0 kegubi .
PFX FD 0 keguli .
PFX FD 0 keguga .
PFX FD 0 keguka .
PFX FD 0 kegubu .
PFX FD 0 kegulu .
PFX FD 0 keguku .
PFX FD 0 kegutu .
PFX FD 0 kegin [^lmnb]
PFX FD l kegind l.[^mn]
PFX FD l keginn l.[mn]
PFX FD w kegimp [w]
PFX FD 0 kegimu .
PFX FD 0 kegiba .
PFX FD 0 kegigu .
PFX FD 0 kegigi .
PFX FD 0 kegizi .
PFX FD 0 kegiki .
PFX FD 0 kegibi .
PFX FD 0 kegili .
PFX FD 0 kegiga .
PFX FD 0 kegika .
PFX FD 0 kegibu .
PFX FD 0 kegilu .
PFX FD 0 kegiku .
PFX FD 0 kegitu .
PFX FD 0 kezin [^lmnb]
PFX FD l kezind l.[^mn]
PFX FD l kezinn l.[mn]
PFX FD w kezimp [w]
PFX FD 0 kezimu .
PFX FD 0 keziba .
PFX FD 0 kezigu .
PFX FD 0 kezigi .
PFX FD 0 kezizi .
PFX FD 0 keziki .
PFX FD 0 kezibi .
PFX FD 0 kezili .
PFX FD 0 keziga .
PFX FD 0 kezika .
PFX FD 0 kezibu .
PFX FD 0 kezilu .
PFX FD 0 keziku .
PFX FD 0 kezitu .
PFX FD 0 kekin [^lmnb]
PFX FD l kekind l.[^mn]
PFX FD l kekinn l.[mn]
PFX FD w kekimp [w]
PFX FD 0 kekimu .
PFX FD 0 kekiba .
PFX FD 0 kekigu .
PFX FD 0 kekigi .
PFX FD 0 kekizi .
PFX FD 0 kekiki .
PFX FD 0 kekibi .
PFX FD 0 kekili .
PFX FD 0 kekiga .
PFX FD 0 kekika .
PFX FD 0 kekibu .
PFX FD 0 kekilu .
PFX FD 0 kekiku .
PFX FD 0 kekitu .
PFX FD 0 kebin [^lmnb]
PFX FD l kebind l.[^mn]
PFX FD l kebinn l.[mn]
PFX FD w kebimp [w]
PFX FD 0 kebimu .
PFX FD 0 kebiba .
PFX FD 0 kebigu .
PFX FD 0 kebigi .
PFX FD 0 kebizi .
PFX FD 0 kebiki .
PFX FD 0 kebibi .
PFX FD 0 kebili .
PFX FD 0 kebiga .
PFX FD 0 kebika .
PFX FD 0 kebibu .
PFX FD 0 kebilu .
PFX FD 0 kebiku .
PFX FD 0 kebitu .
PFX FD 0 kelin [^lmnb]
PFX FD l kelind l.[^mn]
PFX FD l kelinn l.[mn]
PFX FD w kelimp [w]
PFX FD 0 kelimu .
PFX FD 0 keliba .
PFX FD 0 keligu .
PFX FD 0 keligi .
PFX FD 0 kelizi .
PFX FD 0 keliki .
PFX FD 0 kelibi .
PFX FD 0 kelili .
PFX FD 0 keliga .
PFX FD 0 kelika .
PFX FD 0 kelibu .
PFX FD 0 kelilu .
PFX FD 0 keliku .
PFX FD 0 kelitu .
PFX FD 0 kegan [^lmnb]
PFX FD l kegand l.[^mn]
PFX FD l kegann l.[mn]
PFX FD w kegamp [w]
PFX FD 0 kegamu .
PFX FD 0 kegaba .
PFX FD 0 kegagu .
PFX FD 0 kegagi .
PFX FD 0 kegazi .
PFX FD 0 kegaki .
PFX FD 0 kegabi .
PFX FD 0 kegali .
PFX FD 0 kegaga .
PFX FD 0 kegaka .
PFX FD 0 kegabu .
PFX FD 0 kegalu .
PFX FD 0 kegaku .
PFX FD 0 kegatu .
PFX FD 0 kekan [^lmnb]
PFX FD l kekand l.[^mn]
PFX FD l kekann l.[mn]
PFX FD w kekamp [w]
PFX FD 0 kekamu .
PFX FD 0 kekaba .
PFX FD 0 kekagu .
PFX FD 0 kekagi .
PFX FD 0 kekazi .
PFX FD 0 kekaki .
PFX FD 0 kekabi .
PFX FD 0 kekali .
PFX FD 0 kekaga .
PFX FD 0 kekaka .
PFX FD 0 kekabu .
PFX FD 0 kekalu .
PFX FD 0 kekaku .
PFX FD 0 kekatu .
PFX FD 0 kebun [^lmnb]
PFX FD l kebund l.[^mn]
PFX FD l kebunn l.[mn]
PFX FD w kebump [w]
PFX FD 0 kebumu .
PFX FD 0 kebuba .
PFX FD 0 kebugu .
PFX FD 0 kebugi .
PFX FD 0 kebuzi .
PFX FD 0 kebuki .
PFX FD 0 kebubi .
PFX FD 0 kebuli .
PFX FD 0 kebuga .
PFX FD 0 kebuka .
PFX FD 0 kebubu .
PFX FD 0 kebulu .
PFX FD 0 kebuku .
PFX FD 0 kebutu .
PFX FD 0 kelun [^lmnb]
PFX FD l kelund l.[^mn]
PFX FD l kelunn l.[mn]
PFX FD w kelump [w]
PFX FD 0 kelumu .
PFX FD 0 keluba .
PFX FD 0 kelugu .
PFX FD 0 kelugi .
PFX FD 0 keluzi .
PFX FD 0 keluki .
PFX FD 0 kelubi .
PFX FD 0 keluli .
PFX FD 0 keluga .
PFX FD 0 keluka .
PFX FD 0 kelubu .
PFX FD 0 kelulu .
PFX FD 0 keluku .
PFX FD 0 kelutu .
PFX FD 0 kekun [^lmnb]
PFX FD l kekund l.[^mn]
PFX FD l kekunn l.[mn]
PFX FD w kekump [w]
PFX FD 0 kekumu .
PFX FD 0 kekuba .
PFX FD 0 kekugu .
PFX FD 0 kekugi .
PFX FD 0 kekuzi .
PFX FD 0 kekuki .
PFX FD 0 kekubi .
PFX FD 0 kekuli .
PFX FD 0 kekuga .
PFX FD 0 kekuka .
PFX FD 0 kekubu .
PFX FD 0 kekulu .
PFX FD 0 kekuku .
PFX FD 0 kekutu .
PFX FD 0 ketun [^lmnb]
PFX FD l ketund l.[^mn]
PFX FD l ketunn l.[mn]
PFX FD w ketump [w]
PFX FD 0 ketumu .
PFX FD 0 ketuba .
PFX FD 0 ketugu .
PFX FD 0 ketugi .
PFX FD 0 ketuzi .
PFX FD 0 ketuki .
PFX FD 0 ketubi .
PFX FD 0 ketuli .
PFX FD 0 ketuga .
PFX FD 0 ketuka .
PFX FD 0 ketubu .
PFX FD 0 ketulu .
PFX FD 0 ketuku .
PFX FD 0 ketutu ."""

rule_right_raw = """
PFX Ob Y 18
PFX Ob 0 n [^lmnb]
PFX Ob l nd l.[^mn][^u]
PFX Ob l nn l.[mn]
PFX Ob w mp [w]
PFX Ob 0 mu .
PFX Ob 0 ba .
PFX Ob 0 gu .
PFX Ob 0 gi .
PFX Ob 0 zi .
PFX Ob 0 ki .
PFX Ob 0 bi .
PFX Ob 0 li .
PFX Ob 0 ga .
PFX Ob 0 ka .
PFX Ob 0 bu .
PFX Ob 0 lu .
PFX Ob 0 ku .
PFX Ob 0 tu ."""

FLAG_DESCRIPTIONS = {
    "FD": "FD",
    "Ob": "Object markers",
}

def parse_rules(raw_text):
    rules = []
    for line in raw_text.strip().split('\n'):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        s = s.split('#', 1)[0].strip()
        parts = s.split()
        if len(parts) < 4:
            continue
        if parts[2] == 'Y':
            continue
        cond = parts[4] if len(parts) > 4 else '.'
        rules.append({'strip': parts[2], 'add': parts[3], 'cond': cond})
    return rules

def generate_block():
    lefts = parse_rules(rule_left_raw)
    rights = parse_rules(rule_right_raw)
    new_rules = []

    for left in lefts:
        for right in rights:
            if left['strip'] != '0':
                if not right['add'].startswith(left['strip']):
                    continue
                combined = left['add'] + right['add'][len(left['strip']):]
            else:
                combined = left['add'] + right['add']

            if left['cond'] != '.':
                if not re.match(left['cond'], right['add']):
                    continue

            new_rules.append({'strip': right['strip'], 'add': combined, 'cond': right['cond']})

    out_flag = "HA"
    left_desc = FLAG_DESCRIPTIONS.get("FD", "FD")
    right_desc = FLAG_DESCRIPTIONS.get("Ob", "Ob")
    comment_line = "# Cross product of {} ({}) and {} ({}) to {}".format(
        "FD", left_desc, "Ob", right_desc, out_flag
    )

    output = ["PFX {} Y {}".format(out_flag, len(new_rules))]
    for r in new_rules:
        output.append("PFX {} {} {} {}".format(out_flag, r['strip'], r['add'], r['cond']))

    return (out_flag, "\n".join([comment_line] + output) + "\n")

def main():
    if not os.path.exists(AFF_FILE):
        print("Error: {} not found.".format(AFF_FILE))
        return

    out_flag, block = generate_block()

    with open(AFF_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    first_flag_idx = None
    last_flag_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("PFX {} ".format(out_flag)):
            if first_flag_idx is None:
                first_flag_idx = i
            last_flag_idx = i

    if first_flag_idx is not None and first_flag_idx > 0:
        prev_line = lines[first_flag_idx - 1].strip()
        if prev_line.startswith("# Cross product"):
            start_idx = first_flag_idx - 1
        else:
            start_idx = first_flag_idx
    elif first_flag_idx is not None:
        start_idx = first_flag_idx
    else:
        start_idx = None

    if start_idx is not None and last_flag_idx is not None:
        # Replace existing block in-place.
        new_lines = lines[:start_idx] + [block] + lines[last_flag_idx + 1:]
    else:
        # Insert before an anchor flag if requested; otherwise append.
        insert_idx = None
        if INSERT_BEFORE_FLAG:
            anchor_prefix = "PFX {} ".format(INSERT_BEFORE_FLAG)
            for i, line in enumerate(lines):
                if line.strip().startswith(anchor_prefix):
                    insert_idx = i
                    # If the anchor PFX block is preceded by one or more cross-product
                    # comment lines, insert before those comments to keep them attached
                    # to the anchor block.
                    while insert_idx > 0 and lines[insert_idx - 1].strip().startswith("# Cross product"):
                        insert_idx -= 1
                    break

        if insert_idx is not None:
            new_lines = lines[:insert_idx] + [block] + lines[insert_idx:]
        else:
            new_lines = lines
            if new_lines and not new_lines[-1].endswith(chr(10)):
                new_lines[-1] += chr(10)
            new_lines.append(block)

    with open(AFF_FILE, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    print("{}: updated in place.".format(out_flag))

if __name__ == '__main__':
    main()
