import re
import os
from pathlib import Path

# Cross product generator: FM x Ob => GO
# Description:
# - Left block `FM`: FM
# - Right block `Ob`: Object markers
# - Output flag `GO`: Cross-product prefixes for FM x Ob

REPO_ROOT = Path(__file__).resolve().parents[1]
AFF_FILE = REPO_ROOT / "Luganda.aff"

# If set to a flag name (e.g. "HB"), the generated cross-product block will be inserted
# immediately before the first "PFX <flag>" line when the output flag block doesn't
# already exist in the .aff.
INSERT_BEFORE_FLAG = "".strip() or None

rule_left_raw = """
PFX FM Y 4082
PFX FM 0 w'onoon [^lmnb]
PFX FM l w'onoond l.[^mn][^u]
PFX FM l w'onoonn l.[mn]
PFX FM w w'onoomp [w]
PFX FM 0 w'onoomu .
PFX FM 0 w'onooba .
PFX FM 0 w'onoogu .
PFX FM 0 w'onoogi .
PFX FM 0 w'onoozi .
PFX FM 0 w'onooki .
PFX FM 0 w'onoobi .
PFX FM 0 w'onooli .
PFX FM 0 w'onooga .
PFX FM 0 w'onooka .
PFX FM 0 w'onoobu .
PFX FM 0 w'onoolu .
PFX FM 0 w'onooku .
PFX FM 0 w'onootu .
PFX FM 0 w'onaan [^lmnb]
PFX FM l w'onaand l.[^mn][^u]
PFX FM l w'onaann l.[mn]
PFX FM w w'onaamp [w]
PFX FM 0 w'onaamu .
PFX FM 0 w'onaaba .
PFX FM 0 w'onaagu .
PFX FM 0 w'onaagi .
PFX FM 0 w'onaazi .
PFX FM 0 w'onaaki .
PFX FM 0 w'onaabi .
PFX FM 0 w'onaali .
PFX FM 0 w'onaaga .
PFX FM 0 w'onaaka .
PFX FM 0 w'onaabu .
PFX FM 0 w'onaalu .
PFX FM 0 w'onaaku .
PFX FM 0 w'onaatu .
PFX FM 0 w'anaan [^lmnb]
PFX FM l w'anaand l.[^mn][^u]
PFX FM l w'anaann l.[mn]
PFX FM w w'anaamp [w]
PFX FM 0 w'anaamu .
PFX FM 0 w'anaaba .
PFX FM 0 w'anaagu .
PFX FM 0 w'anaagi .
PFX FM 0 w'anaazi .
PFX FM 0 w'anaaki .
PFX FM 0 w'anaabi .
PFX FM 0 w'anaali .
PFX FM 0 w'anaaga .
PFX FM 0 w'anaaka .
PFX FM 0 w'anaabu .
PFX FM 0 w'anaalu .
PFX FM 0 w'anaaku .
PFX FM 0 w'anaatu .
PFX FM 0 w'enaan [^lmnb]
PFX FM l w'enaand l.[^mn][^u]
PFX FM l w'enaann l.[mn]
PFX FM w w'enaamp [w]
PFX FM 0 w'enaamu .
PFX FM 0 w'enaaba .
PFX FM 0 w'enaagu .
PFX FM 0 w'enaagi .
PFX FM 0 w'enaazi .
PFX FM 0 w'enaaki .
PFX FM 0 w'enaabi .
PFX FM 0 w'enaali .
PFX FM 0 w'enaaga .
PFX FM 0 w'enaaka .
PFX FM 0 w'enaabu .
PFX FM 0 w'enaalu .
PFX FM 0 w'enaaku .
PFX FM 0 w'enaatu .
PFX FM 0 wennaaba .
PFX FM 0 wennaagu .
PFX FM 0 wennaagi .
PFX FM 0 wennaazi .
PFX FM 0 wennaaki .
PFX FM 0 wennaabi .
PFX FM 0 wennaali .
PFX FM 0 wennaaga .
PFX FM 0 wennaaka .
PFX FM 0 wennaabu .
PFX FM 0 wennaalu .
PFX FM 0 wennaaku .
PFX FM 0 wennaatu .
PFX FM 0 wennaamu .
PFX FM 0 wemunaan [^lmnb]
PFX FM l wemunaand l.[^mn][^u]
PFX FM l wemunaann l.[mn]
PFX FM w wemunaamp [w]
PFX FM 0 wemunaamu .
PFX FM 0 wemunaaba .
PFX FM 0 wemunaagu .
PFX FM 0 wemunaagi .
PFX FM 0 wemunaazi .
PFX FM 0 wemunaaki .
PFX FM 0 wemunaabi .
PFX FM 0 wemunaali .
PFX FM 0 wemunaaga .
PFX FM 0 wemunaaka .
PFX FM 0 wemunaabu .
PFX FM 0 wemunaalu .
PFX FM 0 wemunaaku .
PFX FM 0 wemunaatu .
PFX FM 0 wetunaan [^lmnb]
PFX FM l wetunaand l.[^mn][^u]
PFX FM l wetunaann l.[mn]
PFX FM w wetunaamp [w]
PFX FM 0 wetunaamu .
PFX FM 0 wetunaaba .
PFX FM 0 wetunaagu .
PFX FM 0 wetunaagi .
PFX FM 0 wetunaazi .
PFX FM 0 wetunaaki .
PFX FM 0 wetunaabi .
PFX FM 0 wetunaali .
PFX FM 0 wetunaaga .
PFX FM 0 wetunaaka .
PFX FM 0 wetunaabu .
PFX FM 0 wetunaalu .
PFX FM 0 wetunaaku .
PFX FM 0 wetunaatu .
PFX FM 0 wemunaan [^lmnb]
PFX FM l wemunaand l.[^mn][^u]
PFX FM l wemunaann l.[mn]
PFX FM w wemunaamp [w]
PFX FM 0 wemunaamu .
PFX FM 0 wemunaaba .
PFX FM 0 wemunaagu .
PFX FM 0 wemunaagi .
PFX FM 0 wemunaazi .
PFX FM 0 wemunaaki .
PFX FM 0 wemunaabi .
PFX FM 0 wemunaali .
PFX FM 0 wemunaaga .
PFX FM 0 wemunaaka .
PFX FM 0 wemunaabu .
PFX FM 0 wemunaalu .
PFX FM 0 wemunaaku .
PFX FM 0 wemunaatu .
PFX FM 0 webanaan [^lmnb]
PFX FM l webanaand l.[^mn][^u]
PFX FM l webanaann l.[mn]
PFX FM w webanaamp [w]
PFX FM 0 webanaamu .
PFX FM 0 webanaaba .
PFX FM 0 webanaagu .
PFX FM 0 webanaagi .
PFX FM 0 webanaazi .
PFX FM 0 webanaaki .
PFX FM 0 webanaabi .
PFX FM 0 webanaali .
PFX FM 0 webanaaga .
PFX FM 0 webanaaka .
PFX FM 0 webanaabu .
PFX FM 0 webanaalu .
PFX FM 0 webanaaku .
PFX FM 0 webanaatu .
PFX FM 0 wegunaan [^lmnb]
PFX FM l wegunaand l.[^mn][^u]
PFX FM l wegunaann l.[mn]
PFX FM w wegunaamp [w]
PFX FM 0 wegunaamu .
PFX FM 0 wegunaaba .
PFX FM 0 wegunaagu .
PFX FM 0 wegunaagi .
PFX FM 0 wegunaazi .
PFX FM 0 wegunaaki .
PFX FM 0 wegunaabi .
PFX FM 0 wegunaali .
PFX FM 0 wegunaaga .
PFX FM 0 wegunaaka .
PFX FM 0 wegunaabu .
PFX FM 0 wegunaalu .
PFX FM 0 wegunaaku .
PFX FM 0 wegunaatu .
PFX FM 0 weginaan [^lmnb]
PFX FM l weginaand l.[^mn][^u]
PFX FM l weginaann l.[mn]
PFX FM w weginaamp [w]
PFX FM 0 weginaamu .
PFX FM 0 weginaaba .
PFX FM 0 weginaagu .
PFX FM 0 weginaagi .
PFX FM 0 weginaazi .
PFX FM 0 weginaaki .
PFX FM 0 weginaabi .
PFX FM 0 weginaali .
PFX FM 0 weginaaga .
PFX FM 0 weginaaka .
PFX FM 0 weginaabu .
PFX FM 0 weginaalu .
PFX FM 0 weginaaku .
PFX FM 0 weginaatu .
PFX FM 0 wezinaan [^lmnb]
PFX FM l wezinaand l.[^mn][^u]
PFX FM l wezinaann l.[mn]
PFX FM w wezinaamp [w]
PFX FM 0 wezinaamu .
PFX FM 0 wezinaaba .
PFX FM 0 wezinaagu .
PFX FM 0 wezinaagi .
PFX FM 0 wezinaazi .
PFX FM 0 wezinaaki .
PFX FM 0 wezinaabi .
PFX FM 0 wezinaali .
PFX FM 0 wezinaaga .
PFX FM 0 wezinaaka .
PFX FM 0 wezinaabu .
PFX FM 0 wezinaalu .
PFX FM 0 wezinaaku .
PFX FM 0 wezinaatu .
PFX FM 0 wekinaan [^lmnb]
PFX FM l wekinaand l.[^mn][^u]
PFX FM l wekinaann l.[mn]
PFX FM w wekinaamp [w]
PFX FM 0 wekinaamu .
PFX FM 0 wekinaaba .
PFX FM 0 wekinaagu .
PFX FM 0 wekinaagi .
PFX FM 0 wekinaazi .
PFX FM 0 wekinaaki .
PFX FM 0 wekinaabi .
PFX FM 0 wekinaali .
PFX FM 0 wekinaaga .
PFX FM 0 wekinaaka .
PFX FM 0 wekinaabu .
PFX FM 0 wekinaalu .
PFX FM 0 wekinaaku .
PFX FM 0 wekinaatu .
PFX FM 0 webinaan [^lmnb]
PFX FM l webinaand l.[^mn][^u]
PFX FM l webinaann l.[mn]
PFX FM w webinaamp [w]
PFX FM 0 webinaamu .
PFX FM 0 webinaaba .
PFX FM 0 webinaagu .
PFX FM 0 webinaagi .
PFX FM 0 webinaazi .
PFX FM 0 webinaaki .
PFX FM 0 webinaabi .
PFX FM 0 webinaali .
PFX FM 0 webinaaga .
PFX FM 0 webinaaka .
PFX FM 0 webinaabu .
PFX FM 0 webinaalu .
PFX FM 0 webinaaku .
PFX FM 0 webinaatu .
PFX FM 0 welinaan [^lmnb]
PFX FM l welinaand l.[^mn][^u]
PFX FM l welinaann l.[mn]
PFX FM w welinaamp [w]
PFX FM 0 welinaamu .
PFX FM 0 welinaaba .
PFX FM 0 welinaagu .
PFX FM 0 welinaagi .
PFX FM 0 welinaazi .
PFX FM 0 welinaaki .
PFX FM 0 welinaabi .
PFX FM 0 welinaali .
PFX FM 0 welinaaga .
PFX FM 0 welinaaka .
PFX FM 0 welinaabu .
PFX FM 0 welinaalu .
PFX FM 0 welinaaku .
PFX FM 0 welinaatu .
PFX FM 0 weganaan [^lmnb]
PFX FM l weganaand l.[^mn][^u]
PFX FM l weganaann l.[mn]
PFX FM w weganaamp [w]
PFX FM 0 weganaamu .
PFX FM 0 weganaaba .
PFX FM 0 weganaagu .
PFX FM 0 weganaagi .
PFX FM 0 weganaazi .
PFX FM 0 weganaaki .
PFX FM 0 weganaabi .
PFX FM 0 weganaali .
PFX FM 0 weganaaga .
PFX FM 0 weganaaka .
PFX FM 0 weganaabu .
PFX FM 0 weganaalu .
PFX FM 0 weganaaku .
PFX FM 0 weganaatu .
PFX FM 0 wekanaan [^lmnb]
PFX FM l wekanaand l.[^mn][^u]
PFX FM l wekanaann l.[mn]
PFX FM w wekanaamp [w]
PFX FM 0 wekanaamu .
PFX FM 0 wekanaaba .
PFX FM 0 wekanaagu .
PFX FM 0 wekanaagi .
PFX FM 0 wekanaazi .
PFX FM 0 wekanaaki .
PFX FM 0 wekanaabi .
PFX FM 0 wekanaali .
PFX FM 0 wekanaaga .
PFX FM 0 wekanaaka .
PFX FM 0 wekanaabu .
PFX FM 0 wekanaalu .
PFX FM 0 wekanaaku .
PFX FM 0 wekanaatu .
PFX FM 0 webunaan [^lmnb]
PFX FM l webunaand l.[^mn][^u]
PFX FM l webunaann l.[mn]
PFX FM w webunaamp [w]
PFX FM 0 webunaamu .
PFX FM 0 webunaaba .
PFX FM 0 webunaagu .
PFX FM 0 webunaagi .
PFX FM 0 webunaazi .
PFX FM 0 webunaaki .
PFX FM 0 webunaabi .
PFX FM 0 webunaali .
PFX FM 0 webunaaga .
PFX FM 0 webunaaka .
PFX FM 0 webunaabu .
PFX FM 0 webunaalu .
PFX FM 0 webunaaku .
PFX FM 0 webunaatu .
PFX FM 0 welunaan [^lmnb]
PFX FM l welunaand l.[^mn][^u]
PFX FM l welunaann l.[mn]
PFX FM w welunaamp [w]
PFX FM 0 welunaamu .
PFX FM 0 welunaaba .
PFX FM 0 welunaagu .
PFX FM 0 welunaagi .
PFX FM 0 welunaazi .
PFX FM 0 welunaaki .
PFX FM 0 welunaabi .
PFX FM 0 welunaali .
PFX FM 0 welunaaga .
PFX FM 0 welunaaka .
PFX FM 0 welunaabu .
PFX FM 0 welunaalu .
PFX FM 0 welunaaku .
PFX FM 0 welunaatu .
PFX FM 0 wezinaan [^lmnb]
PFX FM l wezinaand l.[^mn][^u]
PFX FM l wezinaann l.[mn]
PFX FM w wezinaamp [w]
PFX FM 0 wezinaamu .
PFX FM 0 wezinaaba .
PFX FM 0 wezinaagu .
PFX FM 0 wezinaagi .
PFX FM 0 wezinaazi .
PFX FM 0 wezinaaki .
PFX FM 0 wezinaabi .
PFX FM 0 wezinaali .
PFX FM 0 wezinaaga .
PFX FM 0 wezinaaka .
PFX FM 0 wezinaabu .
PFX FM 0 wezinaalu .
PFX FM 0 wezinaaku .
PFX FM 0 wezinaatu .
PFX FM 0 wekunaan [^lmnb]
PFX FM l wekunaand l.[^mn][^u]
PFX FM l wekunaann l.[mn]
PFX FM w wekunaamp [w]
PFX FM 0 wekunaamu .
PFX FM 0 wekunaaba .
PFX FM 0 wekunaagu .
PFX FM 0 wekunaagi .
PFX FM 0 wekunaazi .
PFX FM 0 wekunaaki .
PFX FM 0 wekunaabi .
PFX FM 0 wekunaali .
PFX FM 0 wekunaaga .
PFX FM 0 wekunaaka .
PFX FM 0 wekunaabu .
PFX FM 0 wekunaalu .
PFX FM 0 wekunaaku .
PFX FM 0 wekunaatu .
PFX FM 0 weganaan [^lmnb]
PFX FM l weganaand l.[^mn][^u]
PFX FM l weganaann l.[mn]
PFX FM w weganaamp [w]
PFX FM 0 weganaamu .
PFX FM 0 weganaaba .
PFX FM 0 weganaagu .
PFX FM 0 weganaagi .
PFX FM 0 weganaazi .
PFX FM 0 weganaaki .
PFX FM 0 weganaabi .
PFX FM 0 weganaali .
PFX FM 0 weganaaga .
PFX FM 0 weganaaka .
PFX FM 0 weganaabu .
PFX FM 0 weganaalu .
PFX FM 0 weganaaku .
PFX FM 0 weganaatu .
PFX FM 0 wetunaan [^lmnb]
PFX FM l wetunaand l.[^mn][^u]
PFX FM l wetunaann l.[mn]
PFX FM w wetunaamp [w]
PFX FM 0 wetunaamu .
PFX FM 0 wetunaaba .
PFX FM 0 wetunaagu .
PFX FM 0 wetunaagi .
PFX FM 0 wetunaazi .
PFX FM 0 wetunaaki .
PFX FM 0 wetunaabi .
PFX FM 0 wetunaali .
PFX FM 0 wetunaaga .
PFX FM 0 wetunaaka .
PFX FM 0 wetunaabu .
PFX FM 0 wetunaalu .
PFX FM 0 wetunaaku .
PFX FM 0 wetunaatu .
PFX FM 0 bw'onoon [^lmnb]
PFX FM l bw'onoond l.[^mn][^u]
PFX FM l bw'onoonn l.[mn]
PFX FM w bw'onoomp [w]
PFX FM 0 bw'onoomu .
PFX FM 0 bw'onooba .
PFX FM 0 bw'onoogu .
PFX FM 0 bw'onoogi .
PFX FM 0 bw'onoozi .
PFX FM 0 bw'onooki .
PFX FM 0 bw'onoobi .
PFX FM 0 bw'onooli .
PFX FM 0 bw'onooga .
PFX FM 0 bw'onooka .
PFX FM 0 bw'onoobu .
PFX FM 0 bw'onoolu .
PFX FM 0 bw'onooku .
PFX FM 0 bw'onootu .
PFX FM 0 bw'onaan [^lmnb]
PFX FM l bw'onaand l.[^mn][^u]
PFX FM l bw'onaann l.[mn]
PFX FM w bw'onaamp [w]
PFX FM 0 bw'onaamu .
PFX FM 0 bw'onaaba .
PFX FM 0 bw'onaagu .
PFX FM 0 bw'onaagi .
PFX FM 0 bw'onaazi .
PFX FM 0 bw'onaaki .
PFX FM 0 bw'onaabi .
PFX FM 0 bw'onaali .
PFX FM 0 bw'onaaga .
PFX FM 0 bw'onaaka .
PFX FM 0 bw'onaabu .
PFX FM 0 bw'onaalu .
PFX FM 0 bw'onaaku .
PFX FM 0 bw'onaatu .
PFX FM 0 bw'anaan [^lmnb]
PFX FM l bw'anaand l.[^mn][^u]
PFX FM l bw'anaann l.[mn]
PFX FM w bw'anaamp [w]
PFX FM 0 bw'anaamu .
PFX FM 0 bw'anaaba .
PFX FM 0 bw'anaagu .
PFX FM 0 bw'anaagi .
PFX FM 0 bw'anaazi .
PFX FM 0 bw'anaaki .
PFX FM 0 bw'anaabi .
PFX FM 0 bw'anaali .
PFX FM 0 bw'anaaga .
PFX FM 0 bw'anaaka .
PFX FM 0 bw'anaabu .
PFX FM 0 bw'anaalu .
PFX FM 0 bw'anaaku .
PFX FM 0 bw'anaatu .
PFX FM 0 bw'enaan [^lmnb]
PFX FM l bw'enaand l.[^mn][^u]
PFX FM l bw'enaann l.[mn]
PFX FM w bw'enaamp [w]
PFX FM 0 bw'enaamu .
PFX FM 0 bw'enaaba .
PFX FM 0 bw'enaagu .
PFX FM 0 bw'enaagi .
PFX FM 0 bw'enaazi .
PFX FM 0 bw'enaaki .
PFX FM 0 bw'enaabi .
PFX FM 0 bw'enaali .
PFX FM 0 bw'enaaga .
PFX FM 0 bw'enaaka .
PFX FM 0 bw'enaabu .
PFX FM 0 bw'enaalu .
PFX FM 0 bw'enaaku .
PFX FM 0 bw'enaatu .
PFX FM 0 bwennaaba .
PFX FM 0 bwennaagu .
PFX FM 0 bwennaagi .
PFX FM 0 bwennaazi .
PFX FM 0 bwennaaki .
PFX FM 0 bwennaabi .
PFX FM 0 bwennaali .
PFX FM 0 bwennaaga .
PFX FM 0 bwennaaka .
PFX FM 0 bwennaabu .
PFX FM 0 bwennaalu .
PFX FM 0 bwennaaku .
PFX FM 0 bwennaatu .
PFX FM 0 bwennaamu .
PFX FM 0 bwemunaan [^lmnb]
PFX FM l bwemunaand l.[^mn][^u]
PFX FM l bwemunaann l.[mn]
PFX FM w bwemunaamp [w]
PFX FM 0 bwemunaamu .
PFX FM 0 bwemunaaba .
PFX FM 0 bwemunaagu .
PFX FM 0 bwemunaagi .
PFX FM 0 bwemunaazi .
PFX FM 0 bwemunaaki .
PFX FM 0 bwemunaabi .
PFX FM 0 bwemunaali .
PFX FM 0 bwemunaaga .
PFX FM 0 bwemunaaka .
PFX FM 0 bwemunaabu .
PFX FM 0 bwemunaalu .
PFX FM 0 bwemunaaku .
PFX FM 0 bwemunaatu .
PFX FM 0 bwetunaan [^lmnb]
PFX FM l bwetunaand l.[^mn][^u]
PFX FM l bwetunaann l.[mn]
PFX FM w bwetunaamp [w]
PFX FM 0 bwetunaamu .
PFX FM 0 bwetunaaba .
PFX FM 0 bwetunaagu .
PFX FM 0 bwetunaagi .
PFX FM 0 bwetunaazi .
PFX FM 0 bwetunaaki .
PFX FM 0 bwetunaabi .
PFX FM 0 bwetunaali .
PFX FM 0 bwetunaaga .
PFX FM 0 bwetunaaka .
PFX FM 0 bwetunaabu .
PFX FM 0 bwetunaalu .
PFX FM 0 bwetunaaku .
PFX FM 0 bwetunaatu .
PFX FM 0 bwemunaan [^lmnb]
PFX FM l bwemunaand l.[^mn][^u]
PFX FM l bwemunaann l.[mn]
PFX FM w bwemunaamp [w]
PFX FM 0 bwemunaamu .
PFX FM 0 bwemunaaba .
PFX FM 0 bwemunaagu .
PFX FM 0 bwemunaagi .
PFX FM 0 bwemunaazi .
PFX FM 0 bwemunaaki .
PFX FM 0 bwemunaabi .
PFX FM 0 bwemunaali .
PFX FM 0 bwemunaaga .
PFX FM 0 bwemunaaka .
PFX FM 0 bwemunaabu .
PFX FM 0 bwemunaalu .
PFX FM 0 bwemunaaku .
PFX FM 0 bwemunaatu .
PFX FM 0 bwebanaan [^lmnb]
PFX FM l bwebanaand l.[^mn][^u]
PFX FM l bwebanaann l.[mn]
PFX FM w bwebanaamp [w]
PFX FM 0 bwebanaamu .
PFX FM 0 bwebanaaba .
PFX FM 0 bwebanaagu .
PFX FM 0 bwebanaagi .
PFX FM 0 bwebanaazi .
PFX FM 0 bwebanaaki .
PFX FM 0 bwebanaabi .
PFX FM 0 bwebanaali .
PFX FM 0 bwebanaaga .
PFX FM 0 bwebanaaka .
PFX FM 0 bwebanaabu .
PFX FM 0 bwebanaalu .
PFX FM 0 bwebanaaku .
PFX FM 0 bwebanaatu .
PFX FM 0 bwegunaan [^lmnb]
PFX FM l bwegunaand l.[^mn][^u]
PFX FM l bwegunaann l.[mn]
PFX FM w bwegunaamp [w]
PFX FM 0 bwegunaamu .
PFX FM 0 bwegunaaba .
PFX FM 0 bwegunaagu .
PFX FM 0 bwegunaagi .
PFX FM 0 bwegunaazi .
PFX FM 0 bwegunaaki .
PFX FM 0 bwegunaabi .
PFX FM 0 bwegunaali .
PFX FM 0 bwegunaaga .
PFX FM 0 bwegunaaka .
PFX FM 0 bwegunaabu .
PFX FM 0 bwegunaalu .
PFX FM 0 bwegunaaku .
PFX FM 0 bwegunaatu .
PFX FM 0 bweginaan [^lmnb]
PFX FM l bweginaand l.[^mn][^u]
PFX FM l bweginaann l.[mn]
PFX FM w bweginaamp [w]
PFX FM 0 bweginaamu .
PFX FM 0 bweginaaba .
PFX FM 0 bweginaagu .
PFX FM 0 bweginaagi .
PFX FM 0 bweginaazi .
PFX FM 0 bweginaaki .
PFX FM 0 bweginaabi .
PFX FM 0 bweginaali .
PFX FM 0 bweginaaga .
PFX FM 0 bweginaaka .
PFX FM 0 bweginaabu .
PFX FM 0 bweginaalu .
PFX FM 0 bweginaaku .
PFX FM 0 bweginaatu .
PFX FM 0 bwezinaan [^lmnb]
PFX FM l bwezinaand l.[^mn][^u]
PFX FM l bwezinaann l.[mn]
PFX FM w bwezinaamp [w]
PFX FM 0 bwezinaamu .
PFX FM 0 bwezinaaba .
PFX FM 0 bwezinaagu .
PFX FM 0 bwezinaagi .
PFX FM 0 bwezinaazi .
PFX FM 0 bwezinaaki .
PFX FM 0 bwezinaabi .
PFX FM 0 bwezinaali .
PFX FM 0 bwezinaaga .
PFX FM 0 bwezinaaka .
PFX FM 0 bwezinaabu .
PFX FM 0 bwezinaalu .
PFX FM 0 bwezinaaku .
PFX FM 0 bwezinaatu .
PFX FM 0 bwekinaan [^lmnb]
PFX FM l bwekinaand l.[^mn][^u]
PFX FM l bwekinaann l.[mn]
PFX FM w bwekinaamp [w]
PFX FM 0 bwekinaamu .
PFX FM 0 bwekinaaba .
PFX FM 0 bwekinaagu .
PFX FM 0 bwekinaagi .
PFX FM 0 bwekinaazi .
PFX FM 0 bwekinaaki .
PFX FM 0 bwekinaabi .
PFX FM 0 bwekinaali .
PFX FM 0 bwekinaaga .
PFX FM 0 bwekinaaka .
PFX FM 0 bwekinaabu .
PFX FM 0 bwekinaalu .
PFX FM 0 bwekinaaku .
PFX FM 0 bwekinaatu .
PFX FM 0 bwebinaan [^lmnb]
PFX FM l bwebinaand l.[^mn][^u]
PFX FM l bwebinaann l.[mn]
PFX FM w bwebinaamp [w]
PFX FM 0 bwebinaamu .
PFX FM 0 bwebinaaba .
PFX FM 0 bwebinaagu .
PFX FM 0 bwebinaagi .
PFX FM 0 bwebinaazi .
PFX FM 0 bwebinaaki .
PFX FM 0 bwebinaabi .
PFX FM 0 bwebinaali .
PFX FM 0 bwebinaaga .
PFX FM 0 bwebinaaka .
PFX FM 0 bwebinaabu .
PFX FM 0 bwebinaalu .
PFX FM 0 bwebinaaku .
PFX FM 0 bwebinaatu .
PFX FM 0 bwelinaan [^lmnb]
PFX FM l bwelinaand l.[^mn][^u]
PFX FM l bwelinaann l.[mn]
PFX FM w bwelinaamp [w]
PFX FM 0 bwelinaamu .
PFX FM 0 bwelinaaba .
PFX FM 0 bwelinaagu .
PFX FM 0 bwelinaagi .
PFX FM 0 bwelinaazi .
PFX FM 0 bwelinaaki .
PFX FM 0 bwelinaabi .
PFX FM 0 bwelinaali .
PFX FM 0 bwelinaaga .
PFX FM 0 bwelinaaka .
PFX FM 0 bwelinaabu .
PFX FM 0 bwelinaalu .
PFX FM 0 bwelinaaku .
PFX FM 0 bwelinaatu .
PFX FM 0 bweganaan [^lmnb]
PFX FM l bweganaand l.[^mn][^u]
PFX FM l bweganaann l.[mn]
PFX FM w bweganaamp [w]
PFX FM 0 bweganaamu .
PFX FM 0 bweganaaba .
PFX FM 0 bweganaagu .
PFX FM 0 bweganaagi .
PFX FM 0 bweganaazi .
PFX FM 0 bweganaaki .
PFX FM 0 bweganaabi .
PFX FM 0 bweganaali .
PFX FM 0 bweganaaga .
PFX FM 0 bweganaaka .
PFX FM 0 bweganaabu .
PFX FM 0 bweganaalu .
PFX FM 0 bweganaaku .
PFX FM 0 bweganaatu .
PFX FM 0 bwekanaan [^lmnb]
PFX FM l bwekanaand l.[^mn][^u]
PFX FM l bwekanaann l.[mn]
PFX FM w bwekanaamp [w]
PFX FM 0 bwekanaamu .
PFX FM 0 bwekanaaba .
PFX FM 0 bwekanaagu .
PFX FM 0 bwekanaagi .
PFX FM 0 bwekanaazi .
PFX FM 0 bwekanaaki .
PFX FM 0 bwekanaabi .
PFX FM 0 bwekanaali .
PFX FM 0 bwekanaaga .
PFX FM 0 bwekanaaka .
PFX FM 0 bwekanaabu .
PFX FM 0 bwekanaalu .
PFX FM 0 bwekanaaku .
PFX FM 0 bwekanaatu .
PFX FM 0 bwebunaan [^lmnb]
PFX FM l bwebunaand l.[^mn][^u]
PFX FM l bwebunaann l.[mn]
PFX FM w bwebunaamp [w]
PFX FM 0 bwebunaamu .
PFX FM 0 bwebunaaba .
PFX FM 0 bwebunaagu .
PFX FM 0 bwebunaagi .
PFX FM 0 bwebunaazi .
PFX FM 0 bwebunaaki .
PFX FM 0 bwebunaabi .
PFX FM 0 bwebunaali .
PFX FM 0 bwebunaaga .
PFX FM 0 bwebunaaka .
PFX FM 0 bwebunaabu .
PFX FM 0 bwebunaalu .
PFX FM 0 bwebunaaku .
PFX FM 0 bwebunaatu .
PFX FM 0 bwelunaan [^lmnb]
PFX FM l bwelunaand l.[^mn][^u]
PFX FM l bwelunaann l.[mn]
PFX FM w bwelunaamp [w]
PFX FM 0 bwelunaamu .
PFX FM 0 bwelunaaba .
PFX FM 0 bwelunaagu .
PFX FM 0 bwelunaagi .
PFX FM 0 bwelunaazi .
PFX FM 0 bwelunaaki .
PFX FM 0 bwelunaabi .
PFX FM 0 bwelunaali .
PFX FM 0 bwelunaaga .
PFX FM 0 bwelunaaka .
PFX FM 0 bwelunaabu .
PFX FM 0 bwelunaalu .
PFX FM 0 bwelunaaku .
PFX FM 0 bwelunaatu .
PFX FM 0 bwezinaan [^lmnb]
PFX FM l bwezinaand l.[^mn][^u]
PFX FM l bwezinaann l.[mn]
PFX FM w bwezinaamp [w]
PFX FM 0 bwezinaamu .
PFX FM 0 bwezinaaba .
PFX FM 0 bwezinaagu .
PFX FM 0 bwezinaagi .
PFX FM 0 bwezinaazi .
PFX FM 0 bwezinaaki .
PFX FM 0 bwezinaabi .
PFX FM 0 bwezinaali .
PFX FM 0 bwezinaaga .
PFX FM 0 bwezinaaka .
PFX FM 0 bwezinaabu .
PFX FM 0 bwezinaalu .
PFX FM 0 bwezinaaku .
PFX FM 0 bwezinaatu .
PFX FM 0 bwekunaan [^lmnb]
PFX FM l bwekunaand l.[^mn][^u]
PFX FM l bwekunaann l.[mn]
PFX FM w bwekunaamp [w]
PFX FM 0 bwekunaamu .
PFX FM 0 bwekunaaba .
PFX FM 0 bwekunaagu .
PFX FM 0 bwekunaagi .
PFX FM 0 bwekunaazi .
PFX FM 0 bwekunaaki .
PFX FM 0 bwekunaabi .
PFX FM 0 bwekunaali .
PFX FM 0 bwekunaaga .
PFX FM 0 bwekunaaka .
PFX FM 0 bwekunaabu .
PFX FM 0 bwekunaalu .
PFX FM 0 bwekunaaku .
PFX FM 0 bwekunaatu .
PFX FM 0 bweganaan [^lmnb]
PFX FM l bweganaand l.[^mn][^u]
PFX FM l bweganaann l.[mn]
PFX FM w bweganaamp [w]
PFX FM 0 bweganaamu .
PFX FM 0 bweganaaba .
PFX FM 0 bweganaagu .
PFX FM 0 bweganaagi .
PFX FM 0 bweganaazi .
PFX FM 0 bweganaaki .
PFX FM 0 bweganaabi .
PFX FM 0 bweganaali .
PFX FM 0 bweganaaga .
PFX FM 0 bweganaaka .
PFX FM 0 bweganaabu .
PFX FM 0 bweganaalu .
PFX FM 0 bweganaaku .
PFX FM 0 bweganaatu .
PFX FM 0 bwetunaan [^lmnb]
PFX FM l bwetunaand l.[^mn][^u]
PFX FM l bwetunaann l.[mn]
PFX FM w bwetunaamp [w]
PFX FM 0 bwetunaamu .
PFX FM 0 bwetunaaba .
PFX FM 0 bwetunaagu .
PFX FM 0 bwetunaagi .
PFX FM 0 bwetunaazi .
PFX FM 0 bwetunaaki .
PFX FM 0 bwetunaabi .
PFX FM 0 bwetunaali .
PFX FM 0 bwetunaaga .
PFX FM 0 bwetunaaka .
PFX FM 0 bwetunaabu .
PFX FM 0 bwetunaalu .
PFX FM 0 bwetunaaku .
PFX FM 0 bwetunaatu .
PFX FM 0 lw'onoon [^lmnb]
PFX FM l lw'onoond l.[^mn][^u]
PFX FM l lw'onoonn l.[mn]
PFX FM w lw'onoomp [w]
PFX FM 0 lw'onoomu .
PFX FM 0 lw'onooba .
PFX FM 0 lw'onoogu .
PFX FM 0 lw'onoogi .
PFX FM 0 lw'onoozi .
PFX FM 0 lw'onooki .
PFX FM 0 lw'onoobi .
PFX FM 0 lw'onooli .
PFX FM 0 lw'onooga .
PFX FM 0 lw'onooka .
PFX FM 0 lw'onoobu .
PFX FM 0 lw'onoolu .
PFX FM 0 lw'onooku .
PFX FM 0 lw'onootu .
PFX FM 0 lw'onaan [^lmnb]
PFX FM l lw'onaand l.[^mn][^u]
PFX FM l lw'onaann l.[mn]
PFX FM w lw'onaamp [w]
PFX FM 0 lw'onaamu .
PFX FM 0 lw'onaaba .
PFX FM 0 lw'onaagu .
PFX FM 0 lw'onaagi .
PFX FM 0 lw'onaazi .
PFX FM 0 lw'onaaki .
PFX FM 0 lw'onaabi .
PFX FM 0 lw'onaali .
PFX FM 0 lw'onaaga .
PFX FM 0 lw'onaaka .
PFX FM 0 lw'onaabu .
PFX FM 0 lw'onaalu .
PFX FM 0 lw'onaaku .
PFX FM 0 lw'onaatu .
PFX FM 0 lw'anaan [^lmnb]
PFX FM l lw'anaand l.[^mn][^u]
PFX FM l lw'anaann l.[mn]
PFX FM w lw'anaamp [w]
PFX FM 0 lw'anaamu .
PFX FM 0 lw'anaaba .
PFX FM 0 lw'anaagu .
PFX FM 0 lw'anaagi .
PFX FM 0 lw'anaazi .
PFX FM 0 lw'anaaki .
PFX FM 0 lw'anaabi .
PFX FM 0 lw'anaali .
PFX FM 0 lw'anaaga .
PFX FM 0 lw'anaaka .
PFX FM 0 lw'anaabu .
PFX FM 0 lw'anaalu .
PFX FM 0 lw'anaaku .
PFX FM 0 lw'anaatu .
PFX FM 0 lw'enaan [^lmnb]
PFX FM l lw'enaand l.[^mn][^u]
PFX FM l lw'enaann l.[mn]
PFX FM w lw'enaamp [w]
PFX FM 0 lw'enaamu .
PFX FM 0 lw'enaaba .
PFX FM 0 lw'enaagu .
PFX FM 0 lw'enaagi .
PFX FM 0 lw'enaazi .
PFX FM 0 lw'enaaki .
PFX FM 0 lw'enaabi .
PFX FM 0 lw'enaali .
PFX FM 0 lw'enaaga .
PFX FM 0 lw'enaaka .
PFX FM 0 lw'enaabu .
PFX FM 0 lw'enaalu .
PFX FM 0 lw'enaaku .
PFX FM 0 lw'enaatu .
PFX FM 0 lwennaaba .
PFX FM 0 lwennaagu .
PFX FM 0 lwennaagi .
PFX FM 0 lwennaazi .
PFX FM 0 lwennaaki .
PFX FM 0 lwennaabi .
PFX FM 0 lwennaali .
PFX FM 0 lwennaaga .
PFX FM 0 lwennaaka .
PFX FM 0 lwennaabu .
PFX FM 0 lwennaalu .
PFX FM 0 lwennaaku .
PFX FM 0 lwennaatu .
PFX FM 0 lwennaamu .
PFX FM 0 lwemunaan [^lmnb]
PFX FM l lwemunaand l.[^mn][^u]
PFX FM l lwemunaann l.[mn]
PFX FM w lwemunaamp [w]
PFX FM 0 lwemunaamu .
PFX FM 0 lwemunaaba .
PFX FM 0 lwemunaagu .
PFX FM 0 lwemunaagi .
PFX FM 0 lwemunaazi .
PFX FM 0 lwemunaaki .
PFX FM 0 lwemunaabi .
PFX FM 0 lwemunaali .
PFX FM 0 lwemunaaga .
PFX FM 0 lwemunaaka .
PFX FM 0 lwemunaabu .
PFX FM 0 lwemunaalu .
PFX FM 0 lwemunaaku .
PFX FM 0 lwemunaatu .
PFX FM 0 lwetunaan [^lmnb]
PFX FM l lwetunaand l.[^mn][^u]
PFX FM l lwetunaann l.[mn]
PFX FM w lwetunaamp [w]
PFX FM 0 lwetunaamu .
PFX FM 0 lwetunaaba .
PFX FM 0 lwetunaagu .
PFX FM 0 lwetunaagi .
PFX FM 0 lwetunaazi .
PFX FM 0 lwetunaaki .
PFX FM 0 lwetunaabi .
PFX FM 0 lwetunaali .
PFX FM 0 lwetunaaga .
PFX FM 0 lwetunaaka .
PFX FM 0 lwetunaabu .
PFX FM 0 lwetunaalu .
PFX FM 0 lwetunaaku .
PFX FM 0 lwetunaatu .
PFX FM 0 lwemunaan [^lmnb]
PFX FM l lwemunaand l.[^mn][^u]
PFX FM l lwemunaann l.[mn]
PFX FM w lwemunaamp [w]
PFX FM 0 lwemunaamu .
PFX FM 0 lwemunaaba .
PFX FM 0 lwemunaagu .
PFX FM 0 lwemunaagi .
PFX FM 0 lwemunaazi .
PFX FM 0 lwemunaaki .
PFX FM 0 lwemunaabi .
PFX FM 0 lwemunaali .
PFX FM 0 lwemunaaga .
PFX FM 0 lwemunaaka .
PFX FM 0 lwemunaabu .
PFX FM 0 lwemunaalu .
PFX FM 0 lwemunaaku .
PFX FM 0 lwemunaatu .
PFX FM 0 lwebanaan [^lmnb]
PFX FM l lwebanaand l.[^mn][^u]
PFX FM l lwebanaann l.[mn]
PFX FM w lwebanaamp [w]
PFX FM 0 lwebanaamu .
PFX FM 0 lwebanaaba .
PFX FM 0 lwebanaagu .
PFX FM 0 lwebanaagi .
PFX FM 0 lwebanaazi .
PFX FM 0 lwebanaaki .
PFX FM 0 lwebanaabi .
PFX FM 0 lwebanaali .
PFX FM 0 lwebanaaga .
PFX FM 0 lwebanaaka .
PFX FM 0 lwebanaabu .
PFX FM 0 lwebanaalu .
PFX FM 0 lwebanaaku .
PFX FM 0 lwebanaatu .
PFX FM 0 lwegunaan [^lmnb]
PFX FM l lwegunaand l.[^mn][^u]
PFX FM l lwegunaann l.[mn]
PFX FM w lwegunaamp [w]
PFX FM 0 lwegunaamu .
PFX FM 0 lwegunaaba .
PFX FM 0 lwegunaagu .
PFX FM 0 lwegunaagi .
PFX FM 0 lwegunaazi .
PFX FM 0 lwegunaaki .
PFX FM 0 lwegunaabi .
PFX FM 0 lwegunaali .
PFX FM 0 lwegunaaga .
PFX FM 0 lwegunaaka .
PFX FM 0 lwegunaabu .
PFX FM 0 lwegunaalu .
PFX FM 0 lwegunaaku .
PFX FM 0 lwegunaatu .
PFX FM 0 lweginaan [^lmnb]
PFX FM l lweginaand l.[^mn][^u]
PFX FM l lweginaann l.[mn]
PFX FM w lweginaamp [w]
PFX FM 0 lweginaamu .
PFX FM 0 lweginaaba .
PFX FM 0 lweginaagu .
PFX FM 0 lweginaagi .
PFX FM 0 lweginaazi .
PFX FM 0 lweginaaki .
PFX FM 0 lweginaabi .
PFX FM 0 lweginaali .
PFX FM 0 lweginaaga .
PFX FM 0 lweginaaka .
PFX FM 0 lweginaabu .
PFX FM 0 lweginaalu .
PFX FM 0 lweginaaku .
PFX FM 0 lweginaatu .
PFX FM 0 lwezinaan [^lmnb]
PFX FM l lwezinaand l.[^mn][^u]
PFX FM l lwezinaann l.[mn]
PFX FM w lwezinaamp [w]
PFX FM 0 lwezinaamu .
PFX FM 0 lwezinaaba .
PFX FM 0 lwezinaagu .
PFX FM 0 lwezinaagi .
PFX FM 0 lwezinaazi .
PFX FM 0 lwezinaaki .
PFX FM 0 lwezinaabi .
PFX FM 0 lwezinaali .
PFX FM 0 lwezinaaga .
PFX FM 0 lwezinaaka .
PFX FM 0 lwezinaabu .
PFX FM 0 lwezinaalu .
PFX FM 0 lwezinaaku .
PFX FM 0 lwezinaatu .
PFX FM 0 lwekinaan [^lmnb]
PFX FM l lwekinaand l.[^mn][^u]
PFX FM l lwekinaann l.[mn]
PFX FM w lwekinaamp [w]
PFX FM 0 lwekinaamu .
PFX FM 0 lwekinaaba .
PFX FM 0 lwekinaagu .
PFX FM 0 lwekinaagi .
PFX FM 0 lwekinaazi .
PFX FM 0 lwekinaaki .
PFX FM 0 lwekinaabi .
PFX FM 0 lwekinaali .
PFX FM 0 lwekinaaga .
PFX FM 0 lwekinaaka .
PFX FM 0 lwekinaabu .
PFX FM 0 lwekinaalu .
PFX FM 0 lwekinaaku .
PFX FM 0 lwekinaatu .
PFX FM 0 lwebinaan [^lmnb]
PFX FM l lwebinaand l.[^mn][^u]
PFX FM l lwebinaann l.[mn]
PFX FM w lwebinaamp [w]
PFX FM 0 lwebinaamu .
PFX FM 0 lwebinaaba .
PFX FM 0 lwebinaagu .
PFX FM 0 lwebinaagi .
PFX FM 0 lwebinaazi .
PFX FM 0 lwebinaaki .
PFX FM 0 lwebinaabi .
PFX FM 0 lwebinaali .
PFX FM 0 lwebinaaga .
PFX FM 0 lwebinaaka .
PFX FM 0 lwebinaabu .
PFX FM 0 lwebinaalu .
PFX FM 0 lwebinaaku .
PFX FM 0 lwebinaatu .
PFX FM 0 lwelinaan [^lmnb]
PFX FM l lwelinaand l.[^mn][^u]
PFX FM l lwelinaann l.[mn]
PFX FM w lwelinaamp [w]
PFX FM 0 lwelinaamu .
PFX FM 0 lwelinaaba .
PFX FM 0 lwelinaagu .
PFX FM 0 lwelinaagi .
PFX FM 0 lwelinaazi .
PFX FM 0 lwelinaaki .
PFX FM 0 lwelinaabi .
PFX FM 0 lwelinaali .
PFX FM 0 lwelinaaga .
PFX FM 0 lwelinaaka .
PFX FM 0 lwelinaabu .
PFX FM 0 lwelinaalu .
PFX FM 0 lwelinaaku .
PFX FM 0 lwelinaatu .
PFX FM 0 lweganaan [^lmnb]
PFX FM l lweganaand l.[^mn][^u]
PFX FM l lweganaann l.[mn]
PFX FM w lweganaamp [w]
PFX FM 0 lweganaamu .
PFX FM 0 lweganaaba .
PFX FM 0 lweganaagu .
PFX FM 0 lweganaagi .
PFX FM 0 lweganaazi .
PFX FM 0 lweganaaki .
PFX FM 0 lweganaabi .
PFX FM 0 lweganaali .
PFX FM 0 lweganaaga .
PFX FM 0 lweganaaka .
PFX FM 0 lweganaabu .
PFX FM 0 lweganaalu .
PFX FM 0 lweganaaku .
PFX FM 0 lweganaatu .
PFX FM 0 lwekanaan [^lmnb]
PFX FM l lwekanaand l.[^mn][^u]
PFX FM l lwekanaann l.[mn]
PFX FM w lwekanaamp [w]
PFX FM 0 lwekanaamu .
PFX FM 0 lwekanaaba .
PFX FM 0 lwekanaagu .
PFX FM 0 lwekanaagi .
PFX FM 0 lwekanaazi .
PFX FM 0 lwekanaaki .
PFX FM 0 lwekanaabi .
PFX FM 0 lwekanaali .
PFX FM 0 lwekanaaga .
PFX FM 0 lwekanaaka .
PFX FM 0 lwekanaabu .
PFX FM 0 lwekanaalu .
PFX FM 0 lwekanaaku .
PFX FM 0 lwekanaatu .
PFX FM 0 lwebunaan [^lmnb]
PFX FM l lwebunaand l.[^mn][^u]
PFX FM l lwebunaann l.[mn]
PFX FM w lwebunaamp [w]
PFX FM 0 lwebunaamu .
PFX FM 0 lwebunaaba .
PFX FM 0 lwebunaagu .
PFX FM 0 lwebunaagi .
PFX FM 0 lwebunaazi .
PFX FM 0 lwebunaaki .
PFX FM 0 lwebunaabi .
PFX FM 0 lwebunaali .
PFX FM 0 lwebunaaga .
PFX FM 0 lwebunaaka .
PFX FM 0 lwebunaabu .
PFX FM 0 lwebunaalu .
PFX FM 0 lwebunaaku .
PFX FM 0 lwebunaatu .
PFX FM 0 lwelunaan [^lmnb]
PFX FM l lwelunaand l.[^mn][^u]
PFX FM l lwelunaann l.[mn]
PFX FM w lwelunaamp [w]
PFX FM 0 lwelunaamu .
PFX FM 0 lwelunaaba .
PFX FM 0 lwelunaagu .
PFX FM 0 lwelunaagi .
PFX FM 0 lwelunaazi .
PFX FM 0 lwelunaaki .
PFX FM 0 lwelunaabi .
PFX FM 0 lwelunaali .
PFX FM 0 lwelunaaga .
PFX FM 0 lwelunaaka .
PFX FM 0 lwelunaabu .
PFX FM 0 lwelunaalu .
PFX FM 0 lwelunaaku .
PFX FM 0 lwelunaatu .
PFX FM 0 lwezinaan [^lmnb]
PFX FM l lwezinaand l.[^mn][^u]
PFX FM l lwezinaann l.[mn]
PFX FM w lwezinaamp [w]
PFX FM 0 lwezinaamu .
PFX FM 0 lwezinaaba .
PFX FM 0 lwezinaagu .
PFX FM 0 lwezinaagi .
PFX FM 0 lwezinaazi .
PFX FM 0 lwezinaaki .
PFX FM 0 lwezinaabi .
PFX FM 0 lwezinaali .
PFX FM 0 lwezinaaga .
PFX FM 0 lwezinaaka .
PFX FM 0 lwezinaabu .
PFX FM 0 lwezinaalu .
PFX FM 0 lwezinaaku .
PFX FM 0 lwezinaatu .
PFX FM 0 lwekunaan [^lmnb]
PFX FM l lwekunaand l.[^mn][^u]
PFX FM l lwekunaann l.[mn]
PFX FM w lwekunaamp [w]
PFX FM 0 lwekunaamu .
PFX FM 0 lwekunaaba .
PFX FM 0 lwekunaagu .
PFX FM 0 lwekunaagi .
PFX FM 0 lwekunaazi .
PFX FM 0 lwekunaaki .
PFX FM 0 lwekunaabi .
PFX FM 0 lwekunaali .
PFX FM 0 lwekunaaga .
PFX FM 0 lwekunaaka .
PFX FM 0 lwekunaabu .
PFX FM 0 lwekunaalu .
PFX FM 0 lwekunaaku .
PFX FM 0 lwekunaatu .
PFX FM 0 lweganaan [^lmnb]
PFX FM l lweganaand l.[^mn][^u]
PFX FM l lweganaann l.[mn]
PFX FM w lweganaamp [w]
PFX FM 0 lweganaamu .
PFX FM 0 lweganaaba .
PFX FM 0 lweganaagu .
PFX FM 0 lweganaagi .
PFX FM 0 lweganaazi .
PFX FM 0 lweganaaki .
PFX FM 0 lweganaabi .
PFX FM 0 lweganaali .
PFX FM 0 lweganaaga .
PFX FM 0 lweganaaka .
PFX FM 0 lweganaabu .
PFX FM 0 lweganaalu .
PFX FM 0 lweganaaku .
PFX FM 0 lweganaatu .
PFX FM 0 lwetunaan [^lmnb]
PFX FM l lwetunaand l.[^mn][^u]
PFX FM l lwetunaann l.[mn]
PFX FM w lwetunaamp [w]
PFX FM 0 lwetunaamu .
PFX FM 0 lwetunaaba .
PFX FM 0 lwetunaagu .
PFX FM 0 lwetunaagi .
PFX FM 0 lwetunaazi .
PFX FM 0 lwetunaaki .
PFX FM 0 lwetunaabi .
PFX FM 0 lwetunaali .
PFX FM 0 lwetunaaga .
PFX FM 0 lwetunaaka .
PFX FM 0 lwetunaabu .
PFX FM 0 lwetunaalu .
PFX FM 0 lwetunaaku .
PFX FM 0 lwetunaatu .
PFX FM 0 z'onoon [^lmnb]
PFX FM l z'onoond l.[^mn][^u]
PFX FM l z'onoonn l.[mn]
PFX FM w z'onoomp [w]
PFX FM 0 z'onoomu .
PFX FM 0 z'onooba .
PFX FM 0 z'onoogu .
PFX FM 0 z'onoogi .
PFX FM 0 z'onoozi .
PFX FM 0 z'onooki .
PFX FM 0 z'onoobi .
PFX FM 0 z'onooli .
PFX FM 0 z'onooga .
PFX FM 0 z'onooka .
PFX FM 0 z'onoobu .
PFX FM 0 z'onoolu .
PFX FM 0 z'onooku .
PFX FM 0 z'onootu .
PFX FM 0 z'onaan [^lmnb]
PFX FM l z'onaand l.[^mn][^u]
PFX FM l z'onaann l.[mn]
PFX FM w z'onaamp [w]
PFX FM 0 z'onaamu .
PFX FM 0 z'onaaba .
PFX FM 0 z'onaagu .
PFX FM 0 z'onaagi .
PFX FM 0 z'onaazi .
PFX FM 0 z'onaaki .
PFX FM 0 z'onaabi .
PFX FM 0 z'onaali .
PFX FM 0 z'onaaga .
PFX FM 0 z'onaaka .
PFX FM 0 z'onaabu .
PFX FM 0 z'onaalu .
PFX FM 0 z'onaaku .
PFX FM 0 z'onaatu .
PFX FM 0 z'anaan [^lmnb]
PFX FM l z'anaand l.[^mn][^u]
PFX FM l z'anaann l.[mn]
PFX FM w z'anaamp [w]
PFX FM 0 z'anaamu .
PFX FM 0 z'anaaba .
PFX FM 0 z'anaagu .
PFX FM 0 z'anaagi .
PFX FM 0 z'anaazi .
PFX FM 0 z'anaaki .
PFX FM 0 z'anaabi .
PFX FM 0 z'anaali .
PFX FM 0 z'anaaga .
PFX FM 0 z'anaaka .
PFX FM 0 z'anaabu .
PFX FM 0 z'anaalu .
PFX FM 0 z'anaaku .
PFX FM 0 z'anaatu .
PFX FM 0 z'enaan [^lmnb]
PFX FM l z'enaand l.[^mn][^u]
PFX FM l z'enaann l.[mn]
PFX FM w z'enaamp [w]
PFX FM 0 z'enaamu .
PFX FM 0 z'enaaba .
PFX FM 0 z'enaagu .
PFX FM 0 z'enaagi .
PFX FM 0 z'enaazi .
PFX FM 0 z'enaaki .
PFX FM 0 z'enaabi .
PFX FM 0 z'enaali .
PFX FM 0 z'enaaga .
PFX FM 0 z'enaaka .
PFX FM 0 z'enaabu .
PFX FM 0 z'enaalu .
PFX FM 0 z'enaaku .
PFX FM 0 z'enaatu .
PFX FM 0 zennaaba .
PFX FM 0 zennaagu .
PFX FM 0 zennaagi .
PFX FM 0 zennaazi .
PFX FM 0 zennaaki .
PFX FM 0 zennaabi .
PFX FM 0 zennaali .
PFX FM 0 zennaaga .
PFX FM 0 zennaaka .
PFX FM 0 zennaabu .
PFX FM 0 zennaalu .
PFX FM 0 zennaaku .
PFX FM 0 zennaatu .
PFX FM 0 zennaamu .
PFX FM 0 zemunaan [^lmnb]
PFX FM l zemunaand l.[^mn][^u]
PFX FM l zemunaann l.[mn]
PFX FM w zemunaamp [w]
PFX FM 0 zemunaamu .
PFX FM 0 zemunaaba .
PFX FM 0 zemunaagu .
PFX FM 0 zemunaagi .
PFX FM 0 zemunaazi .
PFX FM 0 zemunaaki .
PFX FM 0 zemunaabi .
PFX FM 0 zemunaali .
PFX FM 0 zemunaaga .
PFX FM 0 zemunaaka .
PFX FM 0 zemunaabu .
PFX FM 0 zemunaalu .
PFX FM 0 zemunaaku .
PFX FM 0 zemunaatu .
PFX FM 0 zetunaan [^lmnb]
PFX FM l zetunaand l.[^mn][^u]
PFX FM l zetunaann l.[mn]
PFX FM w zetunaamp [w]
PFX FM 0 zetunaamu .
PFX FM 0 zetunaaba .
PFX FM 0 zetunaagu .
PFX FM 0 zetunaagi .
PFX FM 0 zetunaazi .
PFX FM 0 zetunaaki .
PFX FM 0 zetunaabi .
PFX FM 0 zetunaali .
PFX FM 0 zetunaaga .
PFX FM 0 zetunaaka .
PFX FM 0 zetunaabu .
PFX FM 0 zetunaalu .
PFX FM 0 zetunaaku .
PFX FM 0 zetunaatu .
PFX FM 0 zemunaan [^lmnb]
PFX FM l zemunaand l.[^mn][^u]
PFX FM l zemunaann l.[mn]
PFX FM w zemunaamp [w]
PFX FM 0 zemunaamu .
PFX FM 0 zemunaaba .
PFX FM 0 zemunaagu .
PFX FM 0 zemunaagi .
PFX FM 0 zemunaazi .
PFX FM 0 zemunaaki .
PFX FM 0 zemunaabi .
PFX FM 0 zemunaali .
PFX FM 0 zemunaaga .
PFX FM 0 zemunaaka .
PFX FM 0 zemunaabu .
PFX FM 0 zemunaalu .
PFX FM 0 zemunaaku .
PFX FM 0 zemunaatu .
PFX FM 0 zebanaan [^lmnb]
PFX FM l zebanaand l.[^mn][^u]
PFX FM l zebanaann l.[mn]
PFX FM w zebanaamp [w]
PFX FM 0 zebanaamu .
PFX FM 0 zebanaaba .
PFX FM 0 zebanaagu .
PFX FM 0 zebanaagi .
PFX FM 0 zebanaazi .
PFX FM 0 zebanaaki .
PFX FM 0 zebanaabi .
PFX FM 0 zebanaali .
PFX FM 0 zebanaaga .
PFX FM 0 zebanaaka .
PFX FM 0 zebanaabu .
PFX FM 0 zebanaalu .
PFX FM 0 zebanaaku .
PFX FM 0 zebanaatu .
PFX FM 0 zegunaan [^lmnb]
PFX FM l zegunaand l.[^mn][^u]
PFX FM l zegunaann l.[mn]
PFX FM w zegunaamp [w]
PFX FM 0 zegunaamu .
PFX FM 0 zegunaaba .
PFX FM 0 zegunaagu .
PFX FM 0 zegunaagi .
PFX FM 0 zegunaazi .
PFX FM 0 zegunaaki .
PFX FM 0 zegunaabi .
PFX FM 0 zegunaali .
PFX FM 0 zegunaaga .
PFX FM 0 zegunaaka .
PFX FM 0 zegunaabu .
PFX FM 0 zegunaalu .
PFX FM 0 zegunaaku .
PFX FM 0 zegunaatu .
PFX FM 0 zeginaan [^lmnb]
PFX FM l zeginaand l.[^mn][^u]
PFX FM l zeginaann l.[mn]
PFX FM w zeginaamp [w]
PFX FM 0 zeginaamu .
PFX FM 0 zeginaaba .
PFX FM 0 zeginaagu .
PFX FM 0 zeginaagi .
PFX FM 0 zeginaazi .
PFX FM 0 zeginaaki .
PFX FM 0 zeginaabi .
PFX FM 0 zeginaali .
PFX FM 0 zeginaaga .
PFX FM 0 zeginaaka .
PFX FM 0 zeginaabu .
PFX FM 0 zeginaalu .
PFX FM 0 zeginaaku .
PFX FM 0 zeginaatu .
PFX FM 0 zezinaan [^lmnb]
PFX FM l zezinaand l.[^mn][^u]
PFX FM l zezinaann l.[mn]
PFX FM w zezinaamp [w]
PFX FM 0 zezinaamu .
PFX FM 0 zezinaaba .
PFX FM 0 zezinaagu .
PFX FM 0 zezinaagi .
PFX FM 0 zezinaazi .
PFX FM 0 zezinaaki .
PFX FM 0 zezinaabi .
PFX FM 0 zezinaali .
PFX FM 0 zezinaaga .
PFX FM 0 zezinaaka .
PFX FM 0 zezinaabu .
PFX FM 0 zezinaalu .
PFX FM 0 zezinaaku .
PFX FM 0 zezinaatu .
PFX FM 0 zekinaan [^lmnb]
PFX FM l zekinaand l.[^mn][^u]
PFX FM l zekinaann l.[mn]
PFX FM w zekinaamp [w]
PFX FM 0 zekinaamu .
PFX FM 0 zekinaaba .
PFX FM 0 zekinaagu .
PFX FM 0 zekinaagi .
PFX FM 0 zekinaazi .
PFX FM 0 zekinaaki .
PFX FM 0 zekinaabi .
PFX FM 0 zekinaali .
PFX FM 0 zekinaaga .
PFX FM 0 zekinaaka .
PFX FM 0 zekinaabu .
PFX FM 0 zekinaalu .
PFX FM 0 zekinaaku .
PFX FM 0 zekinaatu .
PFX FM 0 zebinaan [^lmnb]
PFX FM l zebinaand l.[^mn][^u]
PFX FM l zebinaann l.[mn]
PFX FM w zebinaamp [w]
PFX FM 0 zebinaamu .
PFX FM 0 zebinaaba .
PFX FM 0 zebinaagu .
PFX FM 0 zebinaagi .
PFX FM 0 zebinaazi .
PFX FM 0 zebinaaki .
PFX FM 0 zebinaabi .
PFX FM 0 zebinaali .
PFX FM 0 zebinaaga .
PFX FM 0 zebinaaka .
PFX FM 0 zebinaabu .
PFX FM 0 zebinaalu .
PFX FM 0 zebinaaku .
PFX FM 0 zebinaatu .
PFX FM 0 zelinaan [^lmnb]
PFX FM l zelinaand l.[^mn][^u]
PFX FM l zelinaann l.[mn]
PFX FM w zelinaamp [w]
PFX FM 0 zelinaamu .
PFX FM 0 zelinaaba .
PFX FM 0 zelinaagu .
PFX FM 0 zelinaagi .
PFX FM 0 zelinaazi .
PFX FM 0 zelinaaki .
PFX FM 0 zelinaabi .
PFX FM 0 zelinaali .
PFX FM 0 zelinaaga .
PFX FM 0 zelinaaka .
PFX FM 0 zelinaabu .
PFX FM 0 zelinaalu .
PFX FM 0 zelinaaku .
PFX FM 0 zelinaatu .
PFX FM 0 zeganaan [^lmnb]
PFX FM l zeganaand l.[^mn][^u]
PFX FM l zeganaann l.[mn]
PFX FM w zeganaamp [w]
PFX FM 0 zeganaamu .
PFX FM 0 zeganaaba .
PFX FM 0 zeganaagu .
PFX FM 0 zeganaagi .
PFX FM 0 zeganaazi .
PFX FM 0 zeganaaki .
PFX FM 0 zeganaabi .
PFX FM 0 zeganaali .
PFX FM 0 zeganaaga .
PFX FM 0 zeganaaka .
PFX FM 0 zeganaabu .
PFX FM 0 zeganaalu .
PFX FM 0 zeganaaku .
PFX FM 0 zeganaatu .
PFX FM 0 zekanaan [^lmnb]
PFX FM l zekanaand l.[^mn][^u]
PFX FM l zekanaann l.[mn]
PFX FM w zekanaamp [w]
PFX FM 0 zekanaamu .
PFX FM 0 zekanaaba .
PFX FM 0 zekanaagu .
PFX FM 0 zekanaagi .
PFX FM 0 zekanaazi .
PFX FM 0 zekanaaki .
PFX FM 0 zekanaabi .
PFX FM 0 zekanaali .
PFX FM 0 zekanaaga .
PFX FM 0 zekanaaka .
PFX FM 0 zekanaabu .
PFX FM 0 zekanaalu .
PFX FM 0 zekanaaku .
PFX FM 0 zekanaatu .
PFX FM 0 zebunaan [^lmnb]
PFX FM l zebunaand l.[^mn][^u]
PFX FM l zebunaann l.[mn]
PFX FM w zebunaamp [w]
PFX FM 0 zebunaamu .
PFX FM 0 zebunaaba .
PFX FM 0 zebunaagu .
PFX FM 0 zebunaagi .
PFX FM 0 zebunaazi .
PFX FM 0 zebunaaki .
PFX FM 0 zebunaabi .
PFX FM 0 zebunaali .
PFX FM 0 zebunaaga .
PFX FM 0 zebunaaka .
PFX FM 0 zebunaabu .
PFX FM 0 zebunaalu .
PFX FM 0 zebunaaku .
PFX FM 0 zebunaatu .
PFX FM 0 zelunaan [^lmnb]
PFX FM l zelunaand l.[^mn][^u]
PFX FM l zelunaann l.[mn]
PFX FM w zelunaamp [w]
PFX FM 0 zelunaamu .
PFX FM 0 zelunaaba .
PFX FM 0 zelunaagu .
PFX FM 0 zelunaagi .
PFX FM 0 zelunaazi .
PFX FM 0 zelunaaki .
PFX FM 0 zelunaabi .
PFX FM 0 zelunaali .
PFX FM 0 zelunaaga .
PFX FM 0 zelunaaka .
PFX FM 0 zelunaabu .
PFX FM 0 zelunaalu .
PFX FM 0 zelunaaku .
PFX FM 0 zelunaatu .
PFX FM 0 zezinaan [^lmnb]
PFX FM l zezinaand l.[^mn][^u]
PFX FM l zezinaann l.[mn]
PFX FM w zezinaamp [w]
PFX FM 0 zezinaamu .
PFX FM 0 zezinaaba .
PFX FM 0 zezinaagu .
PFX FM 0 zezinaagi .
PFX FM 0 zezinaazi .
PFX FM 0 zezinaaki .
PFX FM 0 zezinaabi .
PFX FM 0 zezinaali .
PFX FM 0 zezinaaga .
PFX FM 0 zezinaaka .
PFX FM 0 zezinaabu .
PFX FM 0 zezinaalu .
PFX FM 0 zezinaaku .
PFX FM 0 zezinaatu .
PFX FM 0 zekunaan [^lmnb]
PFX FM l zekunaand l.[^mn][^u]
PFX FM l zekunaann l.[mn]
PFX FM w zekunaamp [w]
PFX FM 0 zekunaamu .
PFX FM 0 zekunaaba .
PFX FM 0 zekunaagu .
PFX FM 0 zekunaagi .
PFX FM 0 zekunaazi .
PFX FM 0 zekunaaki .
PFX FM 0 zekunaabi .
PFX FM 0 zekunaali .
PFX FM 0 zekunaaga .
PFX FM 0 zekunaaka .
PFX FM 0 zekunaabu .
PFX FM 0 zekunaalu .
PFX FM 0 zekunaaku .
PFX FM 0 zekunaatu .
PFX FM 0 zeganaan [^lmnb]
PFX FM l zeganaand l.[^mn][^u]
PFX FM l zeganaann l.[mn]
PFX FM w zeganaamp [w]
PFX FM 0 zeganaamu .
PFX FM 0 zeganaaba .
PFX FM 0 zeganaagu .
PFX FM 0 zeganaagi .
PFX FM 0 zeganaazi .
PFX FM 0 zeganaaki .
PFX FM 0 zeganaabi .
PFX FM 0 zeganaali .
PFX FM 0 zeganaaga .
PFX FM 0 zeganaaka .
PFX FM 0 zeganaabu .
PFX FM 0 zeganaalu .
PFX FM 0 zeganaaku .
PFX FM 0 zeganaatu .
PFX FM 0 zetunaan [^lmnb]
PFX FM l zetunaand l.[^mn][^u]
PFX FM l zetunaann l.[mn]
PFX FM w zetunaamp [w]
PFX FM 0 zetunaamu .
PFX FM 0 zetunaaba .
PFX FM 0 zetunaagu .
PFX FM 0 zetunaagi .
PFX FM 0 zetunaazi .
PFX FM 0 zetunaaki .
PFX FM 0 zetunaabi .
PFX FM 0 zetunaali .
PFX FM 0 zetunaaga .
PFX FM 0 zetunaaka .
PFX FM 0 zetunaabu .
PFX FM 0 zetunaalu .
PFX FM 0 zetunaaku .
PFX FM 0 zetunaatu .
PFX FM 0 gw'onoon [^lmnb]
PFX FM l gw'onoond l.[^mn][^u]
PFX FM l gw'onoonn l.[mn]
PFX FM w gw'onoomp [w]
PFX FM 0 gw'onoomu .
PFX FM 0 gw'onooba .
PFX FM 0 gw'onoogu .
PFX FM 0 gw'onoogi .
PFX FM 0 gw'onoozi .
PFX FM 0 gw'onooki .
PFX FM 0 gw'onoobi .
PFX FM 0 gw'onooli .
PFX FM 0 gw'onooga .
PFX FM 0 gw'onooka .
PFX FM 0 gw'onoobu .
PFX FM 0 gw'onoolu .
PFX FM 0 gw'onooku .
PFX FM 0 gw'onootu .
PFX FM 0 gw'onaan [^lmnb]
PFX FM l gw'onaand l.[^mn][^u]
PFX FM l gw'onaann l.[mn]
PFX FM w gw'onaamp [w]
PFX FM 0 gw'onaamu .
PFX FM 0 gw'onaaba .
PFX FM 0 gw'onaagu .
PFX FM 0 gw'onaagi .
PFX FM 0 gw'onaazi .
PFX FM 0 gw'onaaki .
PFX FM 0 gw'onaabi .
PFX FM 0 gw'onaali .
PFX FM 0 gw'onaaga .
PFX FM 0 gw'onaaka .
PFX FM 0 gw'onaabu .
PFX FM 0 gw'onaalu .
PFX FM 0 gw'onaaku .
PFX FM 0 gw'onaatu .
PFX FM 0 gw'anaan [^lmnb]
PFX FM l gw'anaand l.[^mn][^u]
PFX FM l gw'anaann l.[mn]
PFX FM w gw'anaamp [w]
PFX FM 0 gw'anaamu .
PFX FM 0 gw'anaaba .
PFX FM 0 gw'anaagu .
PFX FM 0 gw'anaagi .
PFX FM 0 gw'anaazi .
PFX FM 0 gw'anaaki .
PFX FM 0 gw'anaabi .
PFX FM 0 gw'anaali .
PFX FM 0 gw'anaaga .
PFX FM 0 gw'anaaka .
PFX FM 0 gw'anaabu .
PFX FM 0 gw'anaalu .
PFX FM 0 gw'anaaku .
PFX FM 0 gw'anaatu .
PFX FM 0 gw'enaan [^lmnb]
PFX FM l gw'enaand l.[^mn][^u]
PFX FM l gw'enaann l.[mn]
PFX FM w gw'enaamp [w]
PFX FM 0 gw'enaamu .
PFX FM 0 gw'enaaba .
PFX FM 0 gw'enaagu .
PFX FM 0 gw'enaagi .
PFX FM 0 gw'enaazi .
PFX FM 0 gw'enaaki .
PFX FM 0 gw'enaabi .
PFX FM 0 gw'enaali .
PFX FM 0 gw'enaaga .
PFX FM 0 gw'enaaka .
PFX FM 0 gw'enaabu .
PFX FM 0 gw'enaalu .
PFX FM 0 gw'enaaku .
PFX FM 0 gw'enaatu .
PFX FM 0 gwennaaba .
PFX FM 0 gwennaagu .
PFX FM 0 gwennaagi .
PFX FM 0 gwennaazi .
PFX FM 0 gwennaaki .
PFX FM 0 gwennaabi .
PFX FM 0 gwennaali .
PFX FM 0 gwennaaga .
PFX FM 0 gwennaaka .
PFX FM 0 gwennaabu .
PFX FM 0 gwennaalu .
PFX FM 0 gwennaaku .
PFX FM 0 gwennaatu .
PFX FM 0 gwennaamu .
PFX FM 0 gwemunaan [^lmnb]
PFX FM l gwemunaand l.[^mn][^u]
PFX FM l gwemunaann l.[mn]
PFX FM w gwemunaamp [w]
PFX FM 0 gwemunaamu .
PFX FM 0 gwemunaaba .
PFX FM 0 gwemunaagu .
PFX FM 0 gwemunaagi .
PFX FM 0 gwemunaazi .
PFX FM 0 gwemunaaki .
PFX FM 0 gwemunaabi .
PFX FM 0 gwemunaali .
PFX FM 0 gwemunaaga .
PFX FM 0 gwemunaaka .
PFX FM 0 gwemunaabu .
PFX FM 0 gwemunaalu .
PFX FM 0 gwemunaaku .
PFX FM 0 gwemunaatu .
PFX FM 0 gwetunaan [^lmnb]
PFX FM l gwetunaand l.[^mn][^u]
PFX FM l gwetunaann l.[mn]
PFX FM w gwetunaamp [w]
PFX FM 0 gwetunaamu .
PFX FM 0 gwetunaaba .
PFX FM 0 gwetunaagu .
PFX FM 0 gwetunaagi .
PFX FM 0 gwetunaazi .
PFX FM 0 gwetunaaki .
PFX FM 0 gwetunaabi .
PFX FM 0 gwetunaali .
PFX FM 0 gwetunaaga .
PFX FM 0 gwetunaaka .
PFX FM 0 gwetunaabu .
PFX FM 0 gwetunaalu .
PFX FM 0 gwetunaaku .
PFX FM 0 gwetunaatu .
PFX FM 0 gwemunaan [^lmnb]
PFX FM l gwemunaand l.[^mn][^u]
PFX FM l gwemunaann l.[mn]
PFX FM w gwemunaamp [w]
PFX FM 0 gwemunaamu .
PFX FM 0 gwemunaaba .
PFX FM 0 gwemunaagu .
PFX FM 0 gwemunaagi .
PFX FM 0 gwemunaazi .
PFX FM 0 gwemunaaki .
PFX FM 0 gwemunaabi .
PFX FM 0 gwemunaali .
PFX FM 0 gwemunaaga .
PFX FM 0 gwemunaaka .
PFX FM 0 gwemunaabu .
PFX FM 0 gwemunaalu .
PFX FM 0 gwemunaaku .
PFX FM 0 gwemunaatu .
PFX FM 0 gwebanaan [^lmnb]
PFX FM l gwebanaand l.[^mn][^u]
PFX FM l gwebanaann l.[mn]
PFX FM w gwebanaamp [w]
PFX FM 0 gwebanaamu .
PFX FM 0 gwebanaaba .
PFX FM 0 gwebanaagu .
PFX FM 0 gwebanaagi .
PFX FM 0 gwebanaazi .
PFX FM 0 gwebanaaki .
PFX FM 0 gwebanaabi .
PFX FM 0 gwebanaali .
PFX FM 0 gwebanaaga .
PFX FM 0 gwebanaaka .
PFX FM 0 gwebanaabu .
PFX FM 0 gwebanaalu .
PFX FM 0 gwebanaaku .
PFX FM 0 gwebanaatu .
PFX FM 0 gwegunaan [^lmnb]
PFX FM l gwegunaand l.[^mn][^u]
PFX FM l gwegunaann l.[mn]
PFX FM w gwegunaamp [w]
PFX FM 0 gwegunaamu .
PFX FM 0 gwegunaaba .
PFX FM 0 gwegunaagu .
PFX FM 0 gwegunaagi .
PFX FM 0 gwegunaazi .
PFX FM 0 gwegunaaki .
PFX FM 0 gwegunaabi .
PFX FM 0 gwegunaali .
PFX FM 0 gwegunaaga .
PFX FM 0 gwegunaaka .
PFX FM 0 gwegunaabu .
PFX FM 0 gwegunaalu .
PFX FM 0 gwegunaaku .
PFX FM 0 gwegunaatu .
PFX FM 0 gweginaan [^lmnb]
PFX FM l gweginaand l.[^mn][^u]
PFX FM l gweginaann l.[mn]
PFX FM w gweginaamp [w]
PFX FM 0 gweginaamu .
PFX FM 0 gweginaaba .
PFX FM 0 gweginaagu .
PFX FM 0 gweginaagi .
PFX FM 0 gweginaazi .
PFX FM 0 gweginaaki .
PFX FM 0 gweginaabi .
PFX FM 0 gweginaali .
PFX FM 0 gweginaaga .
PFX FM 0 gweginaaka .
PFX FM 0 gweginaabu .
PFX FM 0 gweginaalu .
PFX FM 0 gweginaaku .
PFX FM 0 gweginaatu .
PFX FM 0 gwezinaan [^lmnb]
PFX FM l gwezinaand l.[^mn][^u]
PFX FM l gwezinaann l.[mn]
PFX FM w gwezinaamp [w]
PFX FM 0 gwezinaamu .
PFX FM 0 gwezinaaba .
PFX FM 0 gwezinaagu .
PFX FM 0 gwezinaagi .
PFX FM 0 gwezinaazi .
PFX FM 0 gwezinaaki .
PFX FM 0 gwezinaabi .
PFX FM 0 gwezinaali .
PFX FM 0 gwezinaaga .
PFX FM 0 gwezinaaka .
PFX FM 0 gwezinaabu .
PFX FM 0 gwezinaalu .
PFX FM 0 gwezinaaku .
PFX FM 0 gwezinaatu .
PFX FM 0 gwekinaan [^lmnb]
PFX FM l gwekinaand l.[^mn][^u]
PFX FM l gwekinaann l.[mn]
PFX FM w gwekinaamp [w]
PFX FM 0 gwekinaamu .
PFX FM 0 gwekinaaba .
PFX FM 0 gwekinaagu .
PFX FM 0 gwekinaagi .
PFX FM 0 gwekinaazi .
PFX FM 0 gwekinaaki .
PFX FM 0 gwekinaabi .
PFX FM 0 gwekinaali .
PFX FM 0 gwekinaaga .
PFX FM 0 gwekinaaka .
PFX FM 0 gwekinaabu .
PFX FM 0 gwekinaalu .
PFX FM 0 gwekinaaku .
PFX FM 0 gwekinaatu .
PFX FM 0 gwebinaan [^lmnb]
PFX FM l gwebinaand l.[^mn][^u]
PFX FM l gwebinaann l.[mn]
PFX FM w gwebinaamp [w]
PFX FM 0 gwebinaamu .
PFX FM 0 gwebinaaba .
PFX FM 0 gwebinaagu .
PFX FM 0 gwebinaagi .
PFX FM 0 gwebinaazi .
PFX FM 0 gwebinaaki .
PFX FM 0 gwebinaabi .
PFX FM 0 gwebinaali .
PFX FM 0 gwebinaaga .
PFX FM 0 gwebinaaka .
PFX FM 0 gwebinaabu .
PFX FM 0 gwebinaalu .
PFX FM 0 gwebinaaku .
PFX FM 0 gwebinaatu .
PFX FM 0 gwelinaan [^lmnb]
PFX FM l gwelinaand l.[^mn][^u]
PFX FM l gwelinaann l.[mn]
PFX FM w gwelinaamp [w]
PFX FM 0 gwelinaamu .
PFX FM 0 gwelinaaba .
PFX FM 0 gwelinaagu .
PFX FM 0 gwelinaagi .
PFX FM 0 gwelinaazi .
PFX FM 0 gwelinaaki .
PFX FM 0 gwelinaabi .
PFX FM 0 gwelinaali .
PFX FM 0 gwelinaaga .
PFX FM 0 gwelinaaka .
PFX FM 0 gwelinaabu .
PFX FM 0 gwelinaalu .
PFX FM 0 gwelinaaku .
PFX FM 0 gwelinaatu .
PFX FM 0 gweganaan [^lmnb]
PFX FM l gweganaand l.[^mn][^u]
PFX FM l gweganaann l.[mn]
PFX FM w gweganaamp [w]
PFX FM 0 gweganaamu .
PFX FM 0 gweganaaba .
PFX FM 0 gweganaagu .
PFX FM 0 gweganaagi .
PFX FM 0 gweganaazi .
PFX FM 0 gweganaaki .
PFX FM 0 gweganaabi .
PFX FM 0 gweganaali .
PFX FM 0 gweganaaga .
PFX FM 0 gweganaaka .
PFX FM 0 gweganaabu .
PFX FM 0 gweganaalu .
PFX FM 0 gweganaaku .
PFX FM 0 gweganaatu .
PFX FM 0 gwekanaan [^lmnb]
PFX FM l gwekanaand l.[^mn][^u]
PFX FM l gwekanaann l.[mn]
PFX FM w gwekanaamp [w]
PFX FM 0 gwekanaamu .
PFX FM 0 gwekanaaba .
PFX FM 0 gwekanaagu .
PFX FM 0 gwekanaagi .
PFX FM 0 gwekanaazi .
PFX FM 0 gwekanaaki .
PFX FM 0 gwekanaabi .
PFX FM 0 gwekanaali .
PFX FM 0 gwekanaaga .
PFX FM 0 gwekanaaka .
PFX FM 0 gwekanaabu .
PFX FM 0 gwekanaalu .
PFX FM 0 gwekanaaku .
PFX FM 0 gwekanaatu .
PFX FM 0 gwebunaan [^lmnb]
PFX FM l gwebunaand l.[^mn][^u]
PFX FM l gwebunaann l.[mn]
PFX FM w gwebunaamp [w]
PFX FM 0 gwebunaamu .
PFX FM 0 gwebunaaba .
PFX FM 0 gwebunaagu .
PFX FM 0 gwebunaagi .
PFX FM 0 gwebunaazi .
PFX FM 0 gwebunaaki .
PFX FM 0 gwebunaabi .
PFX FM 0 gwebunaali .
PFX FM 0 gwebunaaga .
PFX FM 0 gwebunaaka .
PFX FM 0 gwebunaabu .
PFX FM 0 gwebunaalu .
PFX FM 0 gwebunaaku .
PFX FM 0 gwebunaatu .
PFX FM 0 gwelunaan [^lmnb]
PFX FM l gwelunaand l.[^mn][^u]
PFX FM l gwelunaann l.[mn]
PFX FM w gwelunaamp [w]
PFX FM 0 gwelunaamu .
PFX FM 0 gwelunaaba .
PFX FM 0 gwelunaagu .
PFX FM 0 gwelunaagi .
PFX FM 0 gwelunaazi .
PFX FM 0 gwelunaaki .
PFX FM 0 gwelunaabi .
PFX FM 0 gwelunaali .
PFX FM 0 gwelunaaga .
PFX FM 0 gwelunaaka .
PFX FM 0 gwelunaabu .
PFX FM 0 gwelunaalu .
PFX FM 0 gwelunaaku .
PFX FM 0 gwelunaatu .
PFX FM 0 gwezinaan [^lmnb]
PFX FM l gwezinaand l.[^mn][^u]
PFX FM l gwezinaann l.[mn]
PFX FM w gwezinaamp [w]
PFX FM 0 gwezinaamu .
PFX FM 0 gwezinaaba .
PFX FM 0 gwezinaagu .
PFX FM 0 gwezinaagi .
PFX FM 0 gwezinaazi .
PFX FM 0 gwezinaaki .
PFX FM 0 gwezinaabi .
PFX FM 0 gwezinaali .
PFX FM 0 gwezinaaga .
PFX FM 0 gwezinaaka .
PFX FM 0 gwezinaabu .
PFX FM 0 gwezinaalu .
PFX FM 0 gwezinaaku .
PFX FM 0 gwezinaatu .
PFX FM 0 gwekunaan [^lmnb]
PFX FM l gwekunaand l.[^mn][^u]
PFX FM l gwekunaann l.[mn]
PFX FM w gwekunaamp [w]
PFX FM 0 gwekunaamu .
PFX FM 0 gwekunaaba .
PFX FM 0 gwekunaagu .
PFX FM 0 gwekunaagi .
PFX FM 0 gwekunaazi .
PFX FM 0 gwekunaaki .
PFX FM 0 gwekunaabi .
PFX FM 0 gwekunaali .
PFX FM 0 gwekunaaga .
PFX FM 0 gwekunaaka .
PFX FM 0 gwekunaabu .
PFX FM 0 gwekunaalu .
PFX FM 0 gwekunaaku .
PFX FM 0 gwekunaatu .
PFX FM 0 gweganaan [^lmnb]
PFX FM l gweganaand l.[^mn][^u]
PFX FM l gweganaann l.[mn]
PFX FM w gweganaamp [w]
PFX FM 0 gweganaamu .
PFX FM 0 gweganaaba .
PFX FM 0 gweganaagu .
PFX FM 0 gweganaagi .
PFX FM 0 gweganaazi .
PFX FM 0 gweganaaki .
PFX FM 0 gweganaabi .
PFX FM 0 gweganaali .
PFX FM 0 gweganaaga .
PFX FM 0 gweganaaka .
PFX FM 0 gweganaabu .
PFX FM 0 gweganaalu .
PFX FM 0 gweganaaku .
PFX FM 0 gweganaatu .
PFX FM 0 gwetunaan [^lmnb]
PFX FM l gwetunaand l.[^mn][^u]
PFX FM l gwetunaann l.[mn]
PFX FM w gwetunaamp [w]
PFX FM 0 gwetunaamu .
PFX FM 0 gwetunaaba .
PFX FM 0 gwetunaagu .
PFX FM 0 gwetunaagi .
PFX FM 0 gwetunaazi .
PFX FM 0 gwetunaaki .
PFX FM 0 gwetunaabi .
PFX FM 0 gwetunaali .
PFX FM 0 gwetunaaga .
PFX FM 0 gwetunaaka .
PFX FM 0 gwetunaabu .
PFX FM 0 gwetunaalu .
PFX FM 0 gwetunaaku .
PFX FM 0 gwetunaatu .
PFX FM 0 gy'onoon [^lmnb]
PFX FM l gy'onoond l.[^mn][^u]
PFX FM l gy'onoonn l.[mn]
PFX FM w gy'onoomp [w]
PFX FM 0 gy'onoomu .
PFX FM 0 gy'onooba .
PFX FM 0 gy'onoogu .
PFX FM 0 gy'onoogi .
PFX FM 0 gy'onoozi .
PFX FM 0 gy'onooki .
PFX FM 0 gy'onoobi .
PFX FM 0 gy'onooli .
PFX FM 0 gy'onooga .
PFX FM 0 gy'onooka .
PFX FM 0 gy'onoobu .
PFX FM 0 gy'onoolu .
PFX FM 0 gy'onooku .
PFX FM 0 gy'onootu .
PFX FM 0 gy'onaan [^lmnb]
PFX FM l gy'onaand l.[^mn][^u]
PFX FM l gy'onaann l.[mn]
PFX FM w gy'onaamp [w]
PFX FM 0 gy'onaamu .
PFX FM 0 gy'onaaba .
PFX FM 0 gy'onaagu .
PFX FM 0 gy'onaagi .
PFX FM 0 gy'onaazi .
PFX FM 0 gy'onaaki .
PFX FM 0 gy'onaabi .
PFX FM 0 gy'onaali .
PFX FM 0 gy'onaaga .
PFX FM 0 gy'onaaka .
PFX FM 0 gy'onaabu .
PFX FM 0 gy'onaalu .
PFX FM 0 gy'onaaku .
PFX FM 0 gy'onaatu .
PFX FM 0 gy'anaan [^lmnb]
PFX FM l gy'anaand l.[^mn][^u]
PFX FM l gy'anaann l.[mn]
PFX FM w gy'anaamp [w]
PFX FM 0 gy'anaamu .
PFX FM 0 gy'anaaba .
PFX FM 0 gy'anaagu .
PFX FM 0 gy'anaagi .
PFX FM 0 gy'anaazi .
PFX FM 0 gy'anaaki .
PFX FM 0 gy'anaabi .
PFX FM 0 gy'anaali .
PFX FM 0 gy'anaaga .
PFX FM 0 gy'anaaka .
PFX FM 0 gy'anaabu .
PFX FM 0 gy'anaalu .
PFX FM 0 gy'anaaku .
PFX FM 0 gy'anaatu .
PFX FM 0 gy'enaan [^lmnb]
PFX FM l gy'enaand l.[^mn][^u]
PFX FM l gy'enaann l.[mn]
PFX FM w gy'enaamp [w]
PFX FM 0 gy'enaamu .
PFX FM 0 gy'enaaba .
PFX FM 0 gy'enaagu .
PFX FM 0 gy'enaagi .
PFX FM 0 gy'enaazi .
PFX FM 0 gy'enaaki .
PFX FM 0 gy'enaabi .
PFX FM 0 gy'enaali .
PFX FM 0 gy'enaaga .
PFX FM 0 gy'enaaka .
PFX FM 0 gy'enaabu .
PFX FM 0 gy'enaalu .
PFX FM 0 gy'enaaku .
PFX FM 0 gy'enaatu .
PFX FM 0 gyennaaba .
PFX FM 0 gyennaagu .
PFX FM 0 gyennaagi .
PFX FM 0 gyennaazi .
PFX FM 0 gyennaaki .
PFX FM 0 gyennaabi .
PFX FM 0 gyennaali .
PFX FM 0 gyennaaga .
PFX FM 0 gyennaaka .
PFX FM 0 gyennaabu .
PFX FM 0 gyennaalu .
PFX FM 0 gyennaaku .
PFX FM 0 gyennaatu .
PFX FM 0 gyennaamu .
PFX FM 0 gyetunaan [^lmnb]
PFX FM l gyetunaand l.[^mn][^u]
PFX FM l gyetunaann l.[mn]
PFX FM w gyetunaamp [w]
PFX FM 0 gyetunaamu .
PFX FM 0 gyetunaaba .
PFX FM 0 gyetunaagu .
PFX FM 0 gyetunaagi .
PFX FM 0 gyetunaazi .
PFX FM 0 gyetunaaki .
PFX FM 0 gyetunaabi .
PFX FM 0 gyetunaali .
PFX FM 0 gyetunaaga .
PFX FM 0 gyetunaaka .
PFX FM 0 gyetunaabu .
PFX FM 0 gyetunaalu .
PFX FM 0 gyetunaaku .
PFX FM 0 gyetunaatu .
PFX FM 0 gyemunaan [^lmnb]
PFX FM l gyemunaand l.[^mn][^u]
PFX FM l gyemunaann l.[mn]
PFX FM w gyemunaamp [w]
PFX FM 0 gyemunaamu .
PFX FM 0 gyemunaaba .
PFX FM 0 gyemunaagu .
PFX FM 0 gyemunaagi .
PFX FM 0 gyemunaazi .
PFX FM 0 gyemunaaki .
PFX FM 0 gyemunaabi .
PFX FM 0 gyemunaali .
PFX FM 0 gyemunaaga .
PFX FM 0 gyemunaaka .
PFX FM 0 gyemunaabu .
PFX FM 0 gyemunaalu .
PFX FM 0 gyemunaaku .
PFX FM 0 gyemunaatu .
PFX FM 0 gyebanaan [^lmnb]
PFX FM l gyebanaand l.[^mn][^u]
PFX FM l gyebanaann l.[mn]
PFX FM w gyebanaamp [w]
PFX FM 0 gyebanaamu .
PFX FM 0 gyebanaaba .
PFX FM 0 gyebanaagu .
PFX FM 0 gyebanaagi .
PFX FM 0 gyebanaazi .
PFX FM 0 gyebanaaki .
PFX FM 0 gyebanaabi .
PFX FM 0 gyebanaali .
PFX FM 0 gyebanaaga .
PFX FM 0 gyebanaaka .
PFX FM 0 gyebanaabu .
PFX FM 0 gyebanaalu .
PFX FM 0 gyebanaaku .
PFX FM 0 gyebanaatu .
PFX FM 0 gyegunaan [^lmnb]
PFX FM l gyegunaand l.[^mn][^u]
PFX FM l gyegunaann l.[mn]
PFX FM w gyegunaamp [w]
PFX FM 0 gyegunaamu .
PFX FM 0 gyegunaaba .
PFX FM 0 gyegunaagu .
PFX FM 0 gyegunaagi .
PFX FM 0 gyegunaazi .
PFX FM 0 gyegunaaki .
PFX FM 0 gyegunaabi .
PFX FM 0 gyegunaali .
PFX FM 0 gyegunaaga .
PFX FM 0 gyegunaaka .
PFX FM 0 gyegunaabu .
PFX FM 0 gyegunaalu .
PFX FM 0 gyegunaaku .
PFX FM 0 gyegunaatu .
PFX FM 0 gyeginaan [^lmnb]
PFX FM l gyeginaand l.[^mn][^u]
PFX FM l gyeginaann l.[mn]
PFX FM w gyeginaamp [w]
PFX FM 0 gyeginaamu .
PFX FM 0 gyeginaaba .
PFX FM 0 gyeginaagu .
PFX FM 0 gyeginaagi .
PFX FM 0 gyeginaazi .
PFX FM 0 gyeginaaki .
PFX FM 0 gyeginaabi .
PFX FM 0 gyeginaali .
PFX FM 0 gyeginaaga .
PFX FM 0 gyeginaaka .
PFX FM 0 gyeginaabu .
PFX FM 0 gyeginaalu .
PFX FM 0 gyeginaaku .
PFX FM 0 gyeginaatu .
PFX FM 0 gyezinaan [^lmnb]
PFX FM l gyezinaand l.[^mn][^u]
PFX FM l gyezinaann l.[mn]
PFX FM w gyezinaamp [w]
PFX FM 0 gyezinaamu .
PFX FM 0 gyezinaaba .
PFX FM 0 gyezinaagu .
PFX FM 0 gyezinaagi .
PFX FM 0 gyezinaazi .
PFX FM 0 gyezinaaki .
PFX FM 0 gyezinaabi .
PFX FM 0 gyezinaali .
PFX FM 0 gyezinaaga .
PFX FM 0 gyezinaaka .
PFX FM 0 gyezinaabu .
PFX FM 0 gyezinaalu .
PFX FM 0 gyezinaaku .
PFX FM 0 gyezinaatu .
PFX FM 0 gyekinaan [^lmnb]
PFX FM l gyekinaand l.[^mn][^u]
PFX FM l gyekinaann l.[mn]
PFX FM w gyekinaamp [w]
PFX FM 0 gyekinaamu .
PFX FM 0 gyekinaaba .
PFX FM 0 gyekinaagu .
PFX FM 0 gyekinaagi .
PFX FM 0 gyekinaazi .
PFX FM 0 gyekinaaki .
PFX FM 0 gyekinaabi .
PFX FM 0 gyekinaali .
PFX FM 0 gyekinaaga .
PFX FM 0 gyekinaaka .
PFX FM 0 gyekinaabu .
PFX FM 0 gyekinaalu .
PFX FM 0 gyekinaaku .
PFX FM 0 gyekinaatu .
PFX FM 0 gyebinaan [^lmnb]
PFX FM l gyebinaand l.[^mn][^u]
PFX FM l gyebinaann l.[mn]
PFX FM w gyebinaamp [w]
PFX FM 0 gyebinaamu .
PFX FM 0 gyebinaaba .
PFX FM 0 gyebinaagu .
PFX FM 0 gyebinaagi .
PFX FM 0 gyebinaazi .
PFX FM 0 gyebinaaki .
PFX FM 0 gyebinaabi .
PFX FM 0 gyebinaali .
PFX FM 0 gyebinaaga .
PFX FM 0 gyebinaaka .
PFX FM 0 gyebinaabu .
PFX FM 0 gyebinaalu .
PFX FM 0 gyebinaaku .
PFX FM 0 gyebinaatu .
PFX FM 0 gyelinaan [^lmnb]
PFX FM l gyelinaand l.[^mn][^u]
PFX FM l gyelinaann l.[mn]
PFX FM w gyelinaamp [w]
PFX FM 0 gyelinaamu .
PFX FM 0 gyelinaaba .
PFX FM 0 gyelinaagu .
PFX FM 0 gyelinaagi .
PFX FM 0 gyelinaazi .
PFX FM 0 gyelinaaki .
PFX FM 0 gyelinaabi .
PFX FM 0 gyelinaali .
PFX FM 0 gyelinaaga .
PFX FM 0 gyelinaaka .
PFX FM 0 gyelinaabu .
PFX FM 0 gyelinaalu .
PFX FM 0 gyelinaaku .
PFX FM 0 gyelinaatu .
PFX FM 0 gyeganaan [^lmnb]
PFX FM l gyeganaand l.[^mn][^u]
PFX FM l gyeganaann l.[mn]
PFX FM w gyeganaamp [w]
PFX FM 0 gyeganaamu .
PFX FM 0 gyeganaaba .
PFX FM 0 gyeganaagu .
PFX FM 0 gyeganaagi .
PFX FM 0 gyeganaazi .
PFX FM 0 gyeganaaki .
PFX FM 0 gyeganaabi .
PFX FM 0 gyeganaali .
PFX FM 0 gyeganaaga .
PFX FM 0 gyeganaaka .
PFX FM 0 gyeganaabu .
PFX FM 0 gyeganaalu .
PFX FM 0 gyeganaaku .
PFX FM 0 gyeganaatu .
PFX FM 0 gyekanaan [^lmnb]
PFX FM l gyekanaand l.[^mn][^u]
PFX FM l gyekanaann l.[mn]
PFX FM w gyekanaamp [w]
PFX FM 0 gyekanaamu .
PFX FM 0 gyekanaaba .
PFX FM 0 gyekanaagu .
PFX FM 0 gyekanaagi .
PFX FM 0 gyekanaazi .
PFX FM 0 gyekanaaki .
PFX FM 0 gyekanaabi .
PFX FM 0 gyekanaali .
PFX FM 0 gyekanaaga .
PFX FM 0 gyekanaaka .
PFX FM 0 gyekanaabu .
PFX FM 0 gyekanaalu .
PFX FM 0 gyekanaaku .
PFX FM 0 gyekanaatu .
PFX FM 0 gyebunaan [^lmnb]
PFX FM l gyebunaand l.[^mn][^u]
PFX FM l gyebunaann l.[mn]
PFX FM w gyebunaamp [w]
PFX FM 0 gyebunaamu .
PFX FM 0 gyebunaaba .
PFX FM 0 gyebunaagu .
PFX FM 0 gyebunaagi .
PFX FM 0 gyebunaazi .
PFX FM 0 gyebunaaki .
PFX FM 0 gyebunaabi .
PFX FM 0 gyebunaali .
PFX FM 0 gyebunaaga .
PFX FM 0 gyebunaaka .
PFX FM 0 gyebunaabu .
PFX FM 0 gyebunaalu .
PFX FM 0 gyebunaaku .
PFX FM 0 gyebunaatu .
PFX FM 0 gyelunaan [^lmnb]
PFX FM l gyelunaand l.[^mn][^u]
PFX FM l gyelunaann l.[mn]
PFX FM w gyelunaamp [w]
PFX FM 0 gyelunaamu .
PFX FM 0 gyelunaaba .
PFX FM 0 gyelunaagu .
PFX FM 0 gyelunaagi .
PFX FM 0 gyelunaazi .
PFX FM 0 gyelunaaki .
PFX FM 0 gyelunaabi .
PFX FM 0 gyelunaali .
PFX FM 0 gyelunaaga .
PFX FM 0 gyelunaaka .
PFX FM 0 gyelunaabu .
PFX FM 0 gyelunaalu .
PFX FM 0 gyelunaaku .
PFX FM 0 gyelunaatu .
PFX FM 0 gyezinaan [^lmnb]
PFX FM l gyezinaand l.[^mn][^u]
PFX FM l gyezinaann l.[mn]
PFX FM w gyezinaamp [w]
PFX FM 0 gyezinaamu .
PFX FM 0 gyezinaaba .
PFX FM 0 gyezinaagu .
PFX FM 0 gyezinaagi .
PFX FM 0 gyezinaazi .
PFX FM 0 gyezinaaki .
PFX FM 0 gyezinaabi .
PFX FM 0 gyezinaali .
PFX FM 0 gyezinaaga .
PFX FM 0 gyezinaaka .
PFX FM 0 gyezinaabu .
PFX FM 0 gyezinaalu .
PFX FM 0 gyezinaaku .
PFX FM 0 gyezinaatu .
PFX FM 0 gyekunaan [^lmnb]
PFX FM l gyekunaand l.[^mn][^u]
PFX FM l gyekunaann l.[mn]
PFX FM w gyekunaamp [w]
PFX FM 0 gyekunaamu .
PFX FM 0 gyekunaaba .
PFX FM 0 gyekunaagu .
PFX FM 0 gyekunaagi .
PFX FM 0 gyekunaazi .
PFX FM 0 gyekunaaki .
PFX FM 0 gyekunaabi .
PFX FM 0 gyekunaali .
PFX FM 0 gyekunaaga .
PFX FM 0 gyekunaaka .
PFX FM 0 gyekunaabu .
PFX FM 0 gyekunaalu .
PFX FM 0 gyekunaaku .
PFX FM 0 gyekunaatu .
PFX FM 0 gyeganaan [^lmnb]
PFX FM l gyeganaand l.[^mn][^u]
PFX FM l gyeganaann l.[mn]
PFX FM w gyeganaamp [w]
PFX FM 0 gyeganaamu .
PFX FM 0 gyeganaaba .
PFX FM 0 gyeganaagu .
PFX FM 0 gyeganaagi .
PFX FM 0 gyeganaazi .
PFX FM 0 gyeganaaki .
PFX FM 0 gyeganaabi .
PFX FM 0 gyeganaali .
PFX FM 0 gyeganaaga .
PFX FM 0 gyeganaaka .
PFX FM 0 gyeganaabu .
PFX FM 0 gyeganaalu .
PFX FM 0 gyeganaaku .
PFX FM 0 gyeganaatu .
PFX FM 0 gyetunaan [^lmnb]
PFX FM l gyetunaand l.[^mn][^u]
PFX FM l gyetunaann l.[mn]
PFX FM w gyetunaamp [w]
PFX FM 0 gyetunaamu .
PFX FM 0 gyetunaaba .
PFX FM 0 gyetunaagu .
PFX FM 0 gyetunaagi .
PFX FM 0 gyetunaazi .
PFX FM 0 gyetunaaki .
PFX FM 0 gyetunaabi .
PFX FM 0 gyetunaali .
PFX FM 0 gyetunaaga .
PFX FM 0 gyetunaaka .
PFX FM 0 gyetunaabu .
PFX FM 0 gyetunaalu .
PFX FM 0 gyetunaaku .
PFX FM 0 gyetunaatu .
PFX FM 0 ky'onoon [^lmnb]
PFX FM l ky'onoond l.[^mn][^u]
PFX FM l ky'onoonn l.[mn]
PFX FM w ky'onoomp [w]
PFX FM 0 ky'onoomu .
PFX FM 0 ky'onooba .
PFX FM 0 ky'onoogu .
PFX FM 0 ky'onoogi .
PFX FM 0 ky'onoozi .
PFX FM 0 ky'onooki .
PFX FM 0 ky'onoobi .
PFX FM 0 ky'onooli .
PFX FM 0 ky'onooga .
PFX FM 0 ky'onooka .
PFX FM 0 ky'onoobu .
PFX FM 0 ky'onoolu .
PFX FM 0 ky'onooku .
PFX FM 0 ky'onootu .
PFX FM 0 ky'onaan [^lmnb]
PFX FM l ky'onaand l.[^mn][^u]
PFX FM l ky'onaann l.[mn]
PFX FM w ky'onaamp [w]
PFX FM 0 ky'onaamu .
PFX FM 0 ky'onaaba .
PFX FM 0 ky'onaagu .
PFX FM 0 ky'onaagi .
PFX FM 0 ky'onaazi .
PFX FM 0 ky'onaaki .
PFX FM 0 ky'onaabi .
PFX FM 0 ky'onaali .
PFX FM 0 ky'onaaga .
PFX FM 0 ky'onaaka .
PFX FM 0 ky'onaabu .
PFX FM 0 ky'onaalu .
PFX FM 0 ky'onaaku .
PFX FM 0 ky'onaatu .
PFX FM 0 ky'anaan [^lmnb]
PFX FM l ky'anaand l.[^mn][^u]
PFX FM l ky'anaann l.[mn]
PFX FM w ky'anaamp [w]
PFX FM 0 ky'anaamu .
PFX FM 0 ky'anaaba .
PFX FM 0 ky'anaagu .
PFX FM 0 ky'anaagi .
PFX FM 0 ky'anaazi .
PFX FM 0 ky'anaaki .
PFX FM 0 ky'anaabi .
PFX FM 0 ky'anaali .
PFX FM 0 ky'anaaga .
PFX FM 0 ky'anaaka .
PFX FM 0 ky'anaabu .
PFX FM 0 ky'anaalu .
PFX FM 0 ky'anaaku .
PFX FM 0 ky'anaatu .
PFX FM 0 ky'enaan [^lmnb]
PFX FM l ky'enaand l.[^mn][^u]
PFX FM l ky'enaann l.[mn]
PFX FM w ky'enaamp [w]
PFX FM 0 ky'enaamu .
PFX FM 0 ky'enaaba .
PFX FM 0 ky'enaagu .
PFX FM 0 ky'enaagi .
PFX FM 0 ky'enaazi .
PFX FM 0 ky'enaaki .
PFX FM 0 ky'enaabi .
PFX FM 0 ky'enaali .
PFX FM 0 ky'enaaga .
PFX FM 0 ky'enaaka .
PFX FM 0 ky'enaabu .
PFX FM 0 ky'enaalu .
PFX FM 0 ky'enaaku .
PFX FM 0 ky'enaatu .
PFX FM 0 kyennaaba .
PFX FM 0 kyennaagu .
PFX FM 0 kyennaagi .
PFX FM 0 kyennaazi .
PFX FM 0 kyennaaki .
PFX FM 0 kyennaabi .
PFX FM 0 kyennaali .
PFX FM 0 kyennaaga .
PFX FM 0 kyennaaka .
PFX FM 0 kyennaabu .
PFX FM 0 kyennaalu .
PFX FM 0 kyennaaku .
PFX FM 0 kyennaatu .
PFX FM 0 kyennaamu .
PFX FM 0 kyemunaan [^lmnb]
PFX FM l kyemunaand l.[^mn][^u]
PFX FM l kyemunaann l.[mn]
PFX FM w kyemunaamp [w]
PFX FM 0 kyemunaamu .
PFX FM 0 kyemunaaba .
PFX FM 0 kyemunaagu .
PFX FM 0 kyemunaagi .
PFX FM 0 kyemunaazi .
PFX FM 0 kyemunaaki .
PFX FM 0 kyemunaabi .
PFX FM 0 kyemunaali .
PFX FM 0 kyemunaaga .
PFX FM 0 kyemunaaka .
PFX FM 0 kyemunaabu .
PFX FM 0 kyemunaalu .
PFX FM 0 kyemunaaku .
PFX FM 0 kyemunaatu .
PFX FM 0 kyetunaan [^lmnb]
PFX FM l kyetunaand l.[^mn][^u]
PFX FM l kyetunaann l.[mn]
PFX FM w kyetunaamp [w]
PFX FM 0 kyetunaamu .
PFX FM 0 kyetunaaba .
PFX FM 0 kyetunaagu .
PFX FM 0 kyetunaagi .
PFX FM 0 kyetunaazi .
PFX FM 0 kyetunaaki .
PFX FM 0 kyetunaabi .
PFX FM 0 kyetunaali .
PFX FM 0 kyetunaaga .
PFX FM 0 kyetunaaka .
PFX FM 0 kyetunaabu .
PFX FM 0 kyetunaalu .
PFX FM 0 kyetunaaku .
PFX FM 0 kyetunaatu .
PFX FM 0 kyemunaan [^lmnb]
PFX FM l kyemunaand l.[^mn][^u]
PFX FM l kyemunaann l.[mn]
PFX FM w kyemunaamp [w]
PFX FM 0 kyemunaamu .
PFX FM 0 kyemunaaba .
PFX FM 0 kyemunaagu .
PFX FM 0 kyemunaagi .
PFX FM 0 kyemunaazi .
PFX FM 0 kyemunaaki .
PFX FM 0 kyemunaabi .
PFX FM 0 kyemunaali .
PFX FM 0 kyemunaaga .
PFX FM 0 kyemunaaka .
PFX FM 0 kyemunaabu .
PFX FM 0 kyemunaalu .
PFX FM 0 kyemunaaku .
PFX FM 0 kyemunaatu .
PFX FM 0 kyebanaan [^lmnb]
PFX FM l kyebanaand l.[^mn][^u]
PFX FM l kyebanaann l.[mn]
PFX FM w kyebanaamp [w]
PFX FM 0 kyebanaamu .
PFX FM 0 kyebanaaba .
PFX FM 0 kyebanaagu .
PFX FM 0 kyebanaagi .
PFX FM 0 kyebanaazi .
PFX FM 0 kyebanaaki .
PFX FM 0 kyebanaabi .
PFX FM 0 kyebanaali .
PFX FM 0 kyebanaaga .
PFX FM 0 kyebanaaka .
PFX FM 0 kyebanaabu .
PFX FM 0 kyebanaalu .
PFX FM 0 kyebanaaku .
PFX FM 0 kyebanaatu .
PFX FM 0 kyegunaan [^lmnb]
PFX FM l kyegunaand l.[^mn][^u]
PFX FM l kyegunaann l.[mn]
PFX FM w kyegunaamp [w]
PFX FM 0 kyegunaamu .
PFX FM 0 kyegunaaba .
PFX FM 0 kyegunaagu .
PFX FM 0 kyegunaagi .
PFX FM 0 kyegunaazi .
PFX FM 0 kyegunaaki .
PFX FM 0 kyegunaabi .
PFX FM 0 kyegunaali .
PFX FM 0 kyegunaaga .
PFX FM 0 kyegunaaka .
PFX FM 0 kyegunaabu .
PFX FM 0 kyegunaalu .
PFX FM 0 kyegunaaku .
PFX FM 0 kyegunaatu .
PFX FM 0 kyeginaan [^lmnb]
PFX FM l kyeginaand l.[^mn][^u]
PFX FM l kyeginaann l.[mn]
PFX FM w kyeginaamp [w]
PFX FM 0 kyeginaamu .
PFX FM 0 kyeginaaba .
PFX FM 0 kyeginaagu .
PFX FM 0 kyeginaagi .
PFX FM 0 kyeginaazi .
PFX FM 0 kyeginaaki .
PFX FM 0 kyeginaabi .
PFX FM 0 kyeginaali .
PFX FM 0 kyeginaaga .
PFX FM 0 kyeginaaka .
PFX FM 0 kyeginaabu .
PFX FM 0 kyeginaalu .
PFX FM 0 kyeginaaku .
PFX FM 0 kyeginaatu .
PFX FM 0 kyezinaan [^lmnb]
PFX FM l kyezinaand l.[^mn][^u]
PFX FM l kyezinaann l.[mn]
PFX FM w kyezinaamp [w]
PFX FM 0 kyezinaamu .
PFX FM 0 kyezinaaba .
PFX FM 0 kyezinaagu .
PFX FM 0 kyezinaagi .
PFX FM 0 kyezinaazi .
PFX FM 0 kyezinaaki .
PFX FM 0 kyezinaabi .
PFX FM 0 kyezinaali .
PFX FM 0 kyezinaaga .
PFX FM 0 kyezinaaka .
PFX FM 0 kyezinaabu .
PFX FM 0 kyezinaalu .
PFX FM 0 kyezinaaku .
PFX FM 0 kyezinaatu .
PFX FM 0 kyekinaan [^lmnb]
PFX FM l kyekinaand l.[^mn][^u]
PFX FM l kyekinaann l.[mn]
PFX FM w kyekinaamp [w]
PFX FM 0 kyekinaamu .
PFX FM 0 kyekinaaba .
PFX FM 0 kyekinaagu .
PFX FM 0 kyekinaagi .
PFX FM 0 kyekinaazi .
PFX FM 0 kyekinaaki .
PFX FM 0 kyekinaabi .
PFX FM 0 kyekinaali .
PFX FM 0 kyekinaaga .
PFX FM 0 kyekinaaka .
PFX FM 0 kyekinaabu .
PFX FM 0 kyekinaalu .
PFX FM 0 kyekinaaku .
PFX FM 0 kyekinaatu .
PFX FM 0 kyebinaan [^lmnb]
PFX FM l kyebinaand l.[^mn][^u]
PFX FM l kyebinaann l.[mn]
PFX FM w kyebinaamp [w]
PFX FM 0 kyebinaamu .
PFX FM 0 kyebinaaba .
PFX FM 0 kyebinaagu .
PFX FM 0 kyebinaagi .
PFX FM 0 kyebinaazi .
PFX FM 0 kyebinaaki .
PFX FM 0 kyebinaabi .
PFX FM 0 kyebinaali .
PFX FM 0 kyebinaaga .
PFX FM 0 kyebinaaka .
PFX FM 0 kyebinaabu .
PFX FM 0 kyebinaalu .
PFX FM 0 kyebinaaku .
PFX FM 0 kyebinaatu .
PFX FM 0 kyelinaan [^lmnb]
PFX FM l kyelinaand l.[^mn][^u]
PFX FM l kyelinaann l.[mn]
PFX FM w kyelinaamp [w]
PFX FM 0 kyelinaamu .
PFX FM 0 kyelinaaba .
PFX FM 0 kyelinaagu .
PFX FM 0 kyelinaagi .
PFX FM 0 kyelinaazi .
PFX FM 0 kyelinaaki .
PFX FM 0 kyelinaabi .
PFX FM 0 kyelinaali .
PFX FM 0 kyelinaaga .
PFX FM 0 kyelinaaka .
PFX FM 0 kyelinaabu .
PFX FM 0 kyelinaalu .
PFX FM 0 kyelinaaku .
PFX FM 0 kyelinaatu .
PFX FM 0 kyeganaan [^lmnb]
PFX FM l kyeganaand l.[^mn][^u]
PFX FM l kyeganaann l.[mn]
PFX FM w kyeganaamp [w]
PFX FM 0 kyeganaamu .
PFX FM 0 kyeganaaba .
PFX FM 0 kyeganaagu .
PFX FM 0 kyeganaagi .
PFX FM 0 kyeganaazi .
PFX FM 0 kyeganaaki .
PFX FM 0 kyeganaabi .
PFX FM 0 kyeganaali .
PFX FM 0 kyeganaaga .
PFX FM 0 kyeganaaka .
PFX FM 0 kyeganaabu .
PFX FM 0 kyeganaalu .
PFX FM 0 kyeganaaku .
PFX FM 0 kyeganaatu .
PFX FM 0 kyekanaan [^lmnb]
PFX FM l kyekanaand l.[^mn][^u]
PFX FM l kyekanaann l.[mn]
PFX FM w kyekanaamp [w]
PFX FM 0 kyekanaamu .
PFX FM 0 kyekanaaba .
PFX FM 0 kyekanaagu .
PFX FM 0 kyekanaagi .
PFX FM 0 kyekanaazi .
PFX FM 0 kyekanaaki .
PFX FM 0 kyekanaabi .
PFX FM 0 kyekanaali .
PFX FM 0 kyekanaaga .
PFX FM 0 kyekanaaka .
PFX FM 0 kyekanaabu .
PFX FM 0 kyekanaalu .
PFX FM 0 kyekanaaku .
PFX FM 0 kyekanaatu .
PFX FM 0 kyebunaan [^lmnb]
PFX FM l kyebunaand l.[^mn][^u]
PFX FM l kyebunaann l.[mn]
PFX FM w kyebunaamp [w]
PFX FM 0 kyebunaamu .
PFX FM 0 kyebunaaba .
PFX FM 0 kyebunaagu .
PFX FM 0 kyebunaagi .
PFX FM 0 kyebunaazi .
PFX FM 0 kyebunaaki .
PFX FM 0 kyebunaabi .
PFX FM 0 kyebunaali .
PFX FM 0 kyebunaaga .
PFX FM 0 kyebunaaka .
PFX FM 0 kyebunaabu .
PFX FM 0 kyebunaalu .
PFX FM 0 kyebunaaku .
PFX FM 0 kyebunaatu .
PFX FM 0 kyelunaan [^lmnb]
PFX FM l kyelunaand l.[^mn][^u]
PFX FM l kyelunaann l.[mn]
PFX FM w kyelunaamp [w]
PFX FM 0 kyelunaamu .
PFX FM 0 kyelunaaba .
PFX FM 0 kyelunaagu .
PFX FM 0 kyelunaagi .
PFX FM 0 kyelunaazi .
PFX FM 0 kyelunaaki .
PFX FM 0 kyelunaabi .
PFX FM 0 kyelunaali .
PFX FM 0 kyelunaaga .
PFX FM 0 kyelunaaka .
PFX FM 0 kyelunaabu .
PFX FM 0 kyelunaalu .
PFX FM 0 kyelunaaku .
PFX FM 0 kyelunaatu .
PFX FM 0 kyezinaan [^lmnb]
PFX FM l kyezinaand l.[^mn][^u]
PFX FM l kyezinaann l.[mn]
PFX FM w kyezinaamp [w]
PFX FM 0 kyezinaamu .
PFX FM 0 kyezinaaba .
PFX FM 0 kyezinaagu .
PFX FM 0 kyezinaagi .
PFX FM 0 kyezinaazi .
PFX FM 0 kyezinaaki .
PFX FM 0 kyezinaabi .
PFX FM 0 kyezinaali .
PFX FM 0 kyezinaaga .
PFX FM 0 kyezinaaka .
PFX FM 0 kyezinaabu .
PFX FM 0 kyezinaalu .
PFX FM 0 kyezinaaku .
PFX FM 0 kyezinaatu .
PFX FM 0 kyekunaan [^lmnb]
PFX FM l kyekunaand l.[^mn][^u]
PFX FM l kyekunaann l.[mn]
PFX FM w kyekunaamp [w]
PFX FM 0 kyekunaamu .
PFX FM 0 kyekunaaba .
PFX FM 0 kyekunaagu .
PFX FM 0 kyekunaagi .
PFX FM 0 kyekunaazi .
PFX FM 0 kyekunaaki .
PFX FM 0 kyekunaabi .
PFX FM 0 kyekunaali .
PFX FM 0 kyekunaaga .
PFX FM 0 kyekunaaka .
PFX FM 0 kyekunaabu .
PFX FM 0 kyekunaalu .
PFX FM 0 kyekunaaku .
PFX FM 0 kyekunaatu .
PFX FM 0 kyeganaan [^lmnb]
PFX FM l kyeganaand l.[^mn][^u]
PFX FM l kyeganaann l.[mn]
PFX FM w kyeganaamp [w]
PFX FM 0 kyeganaamu .
PFX FM 0 kyeganaaba .
PFX FM 0 kyeganaagu .
PFX FM 0 kyeganaagi .
PFX FM 0 kyeganaazi .
PFX FM 0 kyeganaaki .
PFX FM 0 kyeganaabi .
PFX FM 0 kyeganaali .
PFX FM 0 kyeganaaga .
PFX FM 0 kyeganaaka .
PFX FM 0 kyeganaabu .
PFX FM 0 kyeganaalu .
PFX FM 0 kyeganaaku .
PFX FM 0 kyeganaatu .
PFX FM 0 kyetunaan [^lmnb]
PFX FM l kyetunaand l.[^mn][^u]
PFX FM l kyetunaann l.[mn]
PFX FM w kyetunaamp [w]
PFX FM 0 kyetunaamu .
PFX FM 0 kyetunaaba .
PFX FM 0 kyetunaagu .
PFX FM 0 kyetunaagi .
PFX FM 0 kyetunaazi .
PFX FM 0 kyetunaaki .
PFX FM 0 kyetunaabi .
PFX FM 0 kyetunaali .
PFX FM 0 kyetunaaga .
PFX FM 0 kyetunaaka .
PFX FM 0 kyetunaabu .
PFX FM 0 kyetunaalu .
PFX FM 0 kyetunaaku .
PFX FM 0 kyetunaatu .
PFX FM 0 by'onoon [^lmnb]
PFX FM l by'onoond l.[^mn][^u]
PFX FM l by'onoonn l.[mn]
PFX FM w by'onoomp [w]
PFX FM 0 by'onoomu .
PFX FM 0 by'onooba .
PFX FM 0 by'onoogu .
PFX FM 0 by'onoogi .
PFX FM 0 by'onoozi .
PFX FM 0 by'onooki .
PFX FM 0 by'onoobi .
PFX FM 0 by'onooli .
PFX FM 0 by'onooga .
PFX FM 0 by'onooka .
PFX FM 0 by'onoobu .
PFX FM 0 by'onoolu .
PFX FM 0 by'onooku .
PFX FM 0 by'onootu .
PFX FM 0 by'onaan [^lmnb]
PFX FM l by'onaand l.[^mn][^u]
PFX FM l by'onaann l.[mn]
PFX FM w by'onaamp [w]
PFX FM 0 by'onaamu .
PFX FM 0 by'onaaba .
PFX FM 0 by'onaagu .
PFX FM 0 by'onaagi .
PFX FM 0 by'onaazi .
PFX FM 0 by'onaaki .
PFX FM 0 by'onaabi .
PFX FM 0 by'onaali .
PFX FM 0 by'onaaga .
PFX FM 0 by'onaaka .
PFX FM 0 by'onaabu .
PFX FM 0 by'onaalu .
PFX FM 0 by'onaaku .
PFX FM 0 by'onaatu .
PFX FM 0 by'anaan [^lmnb]
PFX FM l by'anaand l.[^mn][^u]
PFX FM l by'anaann l.[mn]
PFX FM w by'anaamp [w]
PFX FM 0 by'anaamu .
PFX FM 0 by'anaaba .
PFX FM 0 by'anaagu .
PFX FM 0 by'anaagi .
PFX FM 0 by'anaazi .
PFX FM 0 by'anaaki .
PFX FM 0 by'anaabi .
PFX FM 0 by'anaali .
PFX FM 0 by'anaaga .
PFX FM 0 by'anaaka .
PFX FM 0 by'anaabu .
PFX FM 0 by'anaalu .
PFX FM 0 by'anaaku .
PFX FM 0 by'anaatu .
PFX FM 0 by'enaan [^lmnb]
PFX FM l by'enaand l.[^mn][^u]
PFX FM l by'enaann l.[mn]
PFX FM w by'enaamp [w]
PFX FM 0 by'enaamu .
PFX FM 0 by'enaaba .
PFX FM 0 by'enaagu .
PFX FM 0 by'enaagi .
PFX FM 0 by'enaazi .
PFX FM 0 by'enaaki .
PFX FM 0 by'enaabi .
PFX FM 0 by'enaali .
PFX FM 0 by'enaaga .
PFX FM 0 by'enaaka .
PFX FM 0 by'enaabu .
PFX FM 0 by'enaalu .
PFX FM 0 by'enaaku .
PFX FM 0 by'enaatu .
PFX FM 0 byennaaba .
PFX FM 0 byennaagu .
PFX FM 0 byennaagi .
PFX FM 0 byennaazi .
PFX FM 0 byennaaki .
PFX FM 0 byennaabi .
PFX FM 0 byennaali .
PFX FM 0 byennaaga .
PFX FM 0 byennaaka .
PFX FM 0 byennaabu .
PFX FM 0 byennaalu .
PFX FM 0 byennaaku .
PFX FM 0 byennaatu .
PFX FM 0 byennaamu .
PFX FM 0 byemunaan [^lmnb]
PFX FM l byemunaand l.[^mn][^u]
PFX FM l byemunaann l.[mn]
PFX FM w byemunaamp [w]
PFX FM 0 byemunaamu .
PFX FM 0 byemunaaba .
PFX FM 0 byemunaagu .
PFX FM 0 byemunaagi .
PFX FM 0 byemunaazi .
PFX FM 0 byemunaaki .
PFX FM 0 byemunaabi .
PFX FM 0 byemunaali .
PFX FM 0 byemunaaga .
PFX FM 0 byemunaaka .
PFX FM 0 byemunaabu .
PFX FM 0 byemunaalu .
PFX FM 0 byemunaaku .
PFX FM 0 byemunaatu .
PFX FM 0 byetunaan [^lmnb]
PFX FM l byetunaand l.[^mn][^u]
PFX FM l byetunaann l.[mn]
PFX FM w byetunaamp [w]
PFX FM 0 byetunaamu .
PFX FM 0 byetunaaba .
PFX FM 0 byetunaagu .
PFX FM 0 byetunaagi .
PFX FM 0 byetunaazi .
PFX FM 0 byetunaaki .
PFX FM 0 byetunaabi .
PFX FM 0 byetunaali .
PFX FM 0 byetunaaga .
PFX FM 0 byetunaaka .
PFX FM 0 byetunaabu .
PFX FM 0 byetunaalu .
PFX FM 0 byetunaaku .
PFX FM 0 byetunaatu .
PFX FM 0 byemunaan [^lmnb]
PFX FM l byemunaand l.[^mn][^u]
PFX FM l byemunaann l.[mn]
PFX FM w byemunaamp [w]
PFX FM 0 byemunaamu .
PFX FM 0 byemunaaba .
PFX FM 0 byemunaagu .
PFX FM 0 byemunaagi .
PFX FM 0 byemunaazi .
PFX FM 0 byemunaaki .
PFX FM 0 byemunaabi .
PFX FM 0 byemunaali .
PFX FM 0 byemunaaga .
PFX FM 0 byemunaaka .
PFX FM 0 byemunaabu .
PFX FM 0 byemunaalu .
PFX FM 0 byemunaaku .
PFX FM 0 byemunaatu .
PFX FM 0 byebanaan [^lmnb]
PFX FM l byebanaand l.[^mn][^u]
PFX FM l byebanaann l.[mn]
PFX FM w byebanaamp [w]
PFX FM 0 byebanaamu .
PFX FM 0 byebanaaba .
PFX FM 0 byebanaagu .
PFX FM 0 byebanaagi .
PFX FM 0 byebanaazi .
PFX FM 0 byebanaaki .
PFX FM 0 byebanaabi .
PFX FM 0 byebanaali .
PFX FM 0 byebanaaga .
PFX FM 0 byebanaaka .
PFX FM 0 byebanaabu .
PFX FM 0 byebanaalu .
PFX FM 0 byebanaaku .
PFX FM 0 byebanaatu .
PFX FM 0 byegunaan [^lmnb]
PFX FM l byegunaand l.[^mn][^u]
PFX FM l byegunaann l.[mn]
PFX FM w byegunaamp [w]
PFX FM 0 byegunaamu .
PFX FM 0 byegunaaba .
PFX FM 0 byegunaagu .
PFX FM 0 byegunaagi .
PFX FM 0 byegunaazi .
PFX FM 0 byegunaaki .
PFX FM 0 byegunaabi .
PFX FM 0 byegunaali .
PFX FM 0 byegunaaga .
PFX FM 0 byegunaaka .
PFX FM 0 byegunaabu .
PFX FM 0 byegunaalu .
PFX FM 0 byegunaaku .
PFX FM 0 byegunaatu .
PFX FM 0 byeginaan [^lmnb]
PFX FM l byeginaand l.[^mn][^u]
PFX FM l byeginaann l.[mn]
PFX FM w byeginaamp [w]
PFX FM 0 byeginaamu .
PFX FM 0 byeginaaba .
PFX FM 0 byeginaagu .
PFX FM 0 byeginaagi .
PFX FM 0 byeginaazi .
PFX FM 0 byeginaaki .
PFX FM 0 byeginaabi .
PFX FM 0 byeginaali .
PFX FM 0 byeginaaga .
PFX FM 0 byeginaaka .
PFX FM 0 byeginaabu .
PFX FM 0 byeginaalu .
PFX FM 0 byeginaaku .
PFX FM 0 byeginaatu .
PFX FM 0 byezinaan [^lmnb]
PFX FM l byezinaand l.[^mn][^u]
PFX FM l byezinaann l.[mn]
PFX FM w byezinaamp [w]
PFX FM 0 byezinaamu .
PFX FM 0 byezinaaba .
PFX FM 0 byezinaagu .
PFX FM 0 byezinaagi .
PFX FM 0 byezinaazi .
PFX FM 0 byezinaaki .
PFX FM 0 byezinaabi .
PFX FM 0 byezinaali .
PFX FM 0 byezinaaga .
PFX FM 0 byezinaaka .
PFX FM 0 byezinaabu .
PFX FM 0 byezinaalu .
PFX FM 0 byezinaaku .
PFX FM 0 byezinaatu .
PFX FM 0 byekinaan [^lmnb]
PFX FM l byekinaand l.[^mn][^u]
PFX FM l byekinaann l.[mn]
PFX FM w byekinaamp [w]
PFX FM 0 byekinaamu .
PFX FM 0 byekinaaba .
PFX FM 0 byekinaagu .
PFX FM 0 byekinaagi .
PFX FM 0 byekinaazi .
PFX FM 0 byekinaaki .
PFX FM 0 byekinaabi .
PFX FM 0 byekinaali .
PFX FM 0 byekinaaga .
PFX FM 0 byekinaaka .
PFX FM 0 byekinaabu .
PFX FM 0 byekinaalu .
PFX FM 0 byekinaaku .
PFX FM 0 byekinaatu .
PFX FM 0 byebinaan [^lmnb]
PFX FM l byebinaand l.[^mn][^u]
PFX FM l byebinaann l.[mn]
PFX FM w byebinaamp [w]
PFX FM 0 byebinaamu .
PFX FM 0 byebinaaba .
PFX FM 0 byebinaagu .
PFX FM 0 byebinaagi .
PFX FM 0 byebinaazi .
PFX FM 0 byebinaaki .
PFX FM 0 byebinaabi .
PFX FM 0 byebinaali .
PFX FM 0 byebinaaga .
PFX FM 0 byebinaaka .
PFX FM 0 byebinaabu .
PFX FM 0 byebinaalu .
PFX FM 0 byebinaaku .
PFX FM 0 byebinaatu .
PFX FM 0 byelinaan [^lmnb]
PFX FM l byelinaand l.[^mn][^u]
PFX FM l byelinaann l.[mn]
PFX FM w byelinaamp [w]
PFX FM 0 byelinaamu .
PFX FM 0 byelinaaba .
PFX FM 0 byelinaagu .
PFX FM 0 byelinaagi .
PFX FM 0 byelinaazi .
PFX FM 0 byelinaaki .
PFX FM 0 byelinaabi .
PFX FM 0 byelinaali .
PFX FM 0 byelinaaga .
PFX FM 0 byelinaaka .
PFX FM 0 byelinaabu .
PFX FM 0 byelinaalu .
PFX FM 0 byelinaaku .
PFX FM 0 byelinaatu .
PFX FM 0 byeganaan [^lmnb]
PFX FM l byeganaand l.[^mn][^u]
PFX FM l byeganaann l.[mn]
PFX FM w byeganaamp [w]
PFX FM 0 byeganaamu .
PFX FM 0 byeganaaba .
PFX FM 0 byeganaagu .
PFX FM 0 byeganaagi .
PFX FM 0 byeganaazi .
PFX FM 0 byeganaaki .
PFX FM 0 byeganaabi .
PFX FM 0 byeganaali .
PFX FM 0 byeganaaga .
PFX FM 0 byeganaaka .
PFX FM 0 byeganaabu .
PFX FM 0 byeganaalu .
PFX FM 0 byeganaaku .
PFX FM 0 byeganaatu .
PFX FM 0 byekanaan [^lmnb]
PFX FM l byekanaand l.[^mn][^u]
PFX FM l byekanaann l.[mn]
PFX FM w byekanaamp [w]
PFX FM 0 byekanaamu .
PFX FM 0 byekanaaba .
PFX FM 0 byekanaagu .
PFX FM 0 byekanaagi .
PFX FM 0 byekanaazi .
PFX FM 0 byekanaaki .
PFX FM 0 byekanaabi .
PFX FM 0 byekanaali .
PFX FM 0 byekanaaga .
PFX FM 0 byekanaaka .
PFX FM 0 byekanaabu .
PFX FM 0 byekanaalu .
PFX FM 0 byekanaaku .
PFX FM 0 byekanaatu .
PFX FM 0 byebunaan [^lmnb]
PFX FM l byebunaand l.[^mn][^u]
PFX FM l byebunaann l.[mn]
PFX FM w byebunaamp [w]
PFX FM 0 byebunaamu .
PFX FM 0 byebunaaba .
PFX FM 0 byebunaagu .
PFX FM 0 byebunaagi .
PFX FM 0 byebunaazi .
PFX FM 0 byebunaaki .
PFX FM 0 byebunaabi .
PFX FM 0 byebunaali .
PFX FM 0 byebunaaga .
PFX FM 0 byebunaaka .
PFX FM 0 byebunaabu .
PFX FM 0 byebunaalu .
PFX FM 0 byebunaaku .
PFX FM 0 byebunaatu .
PFX FM 0 byelunaan [^lmnb]
PFX FM l byelunaand l.[^mn][^u]
PFX FM l byelunaann l.[mn]
PFX FM w byelunaamp [w]
PFX FM 0 byelunaamu .
PFX FM 0 byelunaaba .
PFX FM 0 byelunaagu .
PFX FM 0 byelunaagi .
PFX FM 0 byelunaazi .
PFX FM 0 byelunaaki .
PFX FM 0 byelunaabi .
PFX FM 0 byelunaali .
PFX FM 0 byelunaaga .
PFX FM 0 byelunaaka .
PFX FM 0 byelunaabu .
PFX FM 0 byelunaalu .
PFX FM 0 byelunaaku .
PFX FM 0 byelunaatu .
PFX FM 0 byezinaan [^lmnb]
PFX FM l byezinaand l.[^mn][^u]
PFX FM l byezinaann l.[mn]
PFX FM w byezinaamp [w]
PFX FM 0 byezinaamu .
PFX FM 0 byezinaaba .
PFX FM 0 byezinaagu .
PFX FM 0 byezinaagi .
PFX FM 0 byezinaazi .
PFX FM 0 byezinaaki .
PFX FM 0 byezinaabi .
PFX FM 0 byezinaali .
PFX FM 0 byezinaaga .
PFX FM 0 byezinaaka .
PFX FM 0 byezinaabu .
PFX FM 0 byezinaalu .
PFX FM 0 byezinaaku .
PFX FM 0 byezinaatu .
PFX FM 0 byekunaan [^lmnb]
PFX FM l byekunaand l.[^mn][^u]
PFX FM l byekunaann l.[mn]
PFX FM w byekunaamp [w]
PFX FM 0 byekunaamu .
PFX FM 0 byekunaaba .
PFX FM 0 byekunaagu .
PFX FM 0 byekunaagi .
PFX FM 0 byekunaazi .
PFX FM 0 byekunaaki .
PFX FM 0 byekunaabi .
PFX FM 0 byekunaali .
PFX FM 0 byekunaaga .
PFX FM 0 byekunaaka .
PFX FM 0 byekunaabu .
PFX FM 0 byekunaalu .
PFX FM 0 byekunaaku .
PFX FM 0 byekunaatu .
PFX FM 0 byeganaan [^lmnb]
PFX FM l byeganaand l.[^mn][^u]
PFX FM l byeganaann l.[mn]
PFX FM w byeganaamp [w]
PFX FM 0 byeganaamu .
PFX FM 0 byeganaaba .
PFX FM 0 byeganaagu .
PFX FM 0 byeganaagi .
PFX FM 0 byeganaazi .
PFX FM 0 byeganaaki .
PFX FM 0 byeganaabi .
PFX FM 0 byeganaali .
PFX FM 0 byeganaaga .
PFX FM 0 byeganaaka .
PFX FM 0 byeganaabu .
PFX FM 0 byeganaalu .
PFX FM 0 byeganaaku .
PFX FM 0 byeganaatu .
PFX FM 0 byetunaan [^lmnb]
PFX FM l byetunaand l.[^mn][^u]
PFX FM l byetunaann l.[mn]
PFX FM w byetunaamp [w]
PFX FM 0 byetunaamu .
PFX FM 0 byetunaaba .
PFX FM 0 byetunaagu .
PFX FM 0 byetunaagi .
PFX FM 0 byetunaazi .
PFX FM 0 byetunaaki .
PFX FM 0 byetunaabi .
PFX FM 0 byetunaali .
PFX FM 0 byetunaaga .
PFX FM 0 byetunaaka .
PFX FM 0 byetunaabu .
PFX FM 0 byetunaalu .
PFX FM 0 byetunaaku .
PFX FM 0 byetunaatu .
PFX FM 0 ly'onoon [^lmnb]
PFX FM l ly'onoond l.[^mn][^u]
PFX FM l ly'onoonn l.[mn]
PFX FM w ly'onoomp [w]
PFX FM 0 ly'onoomu .
PFX FM 0 ly'onooba .
PFX FM 0 ly'onoogu .
PFX FM 0 ly'onoogi .
PFX FM 0 ly'onoozi .
PFX FM 0 ly'onooki .
PFX FM 0 ly'onoobi .
PFX FM 0 ly'onooli .
PFX FM 0 ly'onooga .
PFX FM 0 ly'onooka .
PFX FM 0 ly'onoobu .
PFX FM 0 ly'onoolu .
PFX FM 0 ly'onooku .
PFX FM 0 ly'onootu .
PFX FM 0 ly'onaan [^lmnb]
PFX FM l ly'onaand l.[^mn][^u]
PFX FM l ly'onaann l.[mn]
PFX FM w ly'onaamp [w]
PFX FM 0 ly'onaamu .
PFX FM 0 ly'onaaba .
PFX FM 0 ly'onaagu .
PFX FM 0 ly'onaagi .
PFX FM 0 ly'onaazi .
PFX FM 0 ly'onaaki .
PFX FM 0 ly'onaabi .
PFX FM 0 ly'onaali .
PFX FM 0 ly'onaaga .
PFX FM 0 ly'onaaka .
PFX FM 0 ly'onaabu .
PFX FM 0 ly'onaalu .
PFX FM 0 ly'onaaku .
PFX FM 0 ly'onaatu .
PFX FM 0 ly'anaan [^lmnb]
PFX FM l ly'anaand l.[^mn][^u]
PFX FM l ly'anaann l.[mn]
PFX FM w ly'anaamp [w]
PFX FM 0 ly'anaamu .
PFX FM 0 ly'anaaba .
PFX FM 0 ly'anaagu .
PFX FM 0 ly'anaagi .
PFX FM 0 ly'anaazi .
PFX FM 0 ly'anaaki .
PFX FM 0 ly'anaabi .
PFX FM 0 ly'anaali .
PFX FM 0 ly'anaaga .
PFX FM 0 ly'anaaka .
PFX FM 0 ly'anaabu .
PFX FM 0 ly'anaalu .
PFX FM 0 ly'anaaku .
PFX FM 0 ly'anaatu .
PFX FM 0 ly'enaan [^lmnb]
PFX FM l ly'enaand l.[^mn][^u]
PFX FM l ly'enaann l.[mn]
PFX FM w ly'enaamp [w]
PFX FM 0 ly'enaamu .
PFX FM 0 ly'enaaba .
PFX FM 0 ly'enaagu .
PFX FM 0 ly'enaagi .
PFX FM 0 ly'enaazi .
PFX FM 0 ly'enaaki .
PFX FM 0 ly'enaabi .
PFX FM 0 ly'enaali .
PFX FM 0 ly'enaaga .
PFX FM 0 ly'enaaka .
PFX FM 0 ly'enaabu .
PFX FM 0 ly'enaalu .
PFX FM 0 ly'enaaku .
PFX FM 0 ly'enaatu .
PFX FM 0 lyennaaba .
PFX FM 0 lyennaagu .
PFX FM 0 lyennaagi .
PFX FM 0 lyennaazi .
PFX FM 0 lyennaaki .
PFX FM 0 lyennaabi .
PFX FM 0 lyennaali .
PFX FM 0 lyennaaga .
PFX FM 0 lyennaaka .
PFX FM 0 lyennaabu .
PFX FM 0 lyennaalu .
PFX FM 0 lyennaaku .
PFX FM 0 lyennaatu .
PFX FM 0 lyennaamu .
PFX FM 0 lyemunaan [^lmnb]
PFX FM l lyemunaand l.[^mn][^u]
PFX FM l lyemunaann l.[mn]
PFX FM w lyemunaamp [w]
PFX FM 0 lyemunaamu .
PFX FM 0 lyemunaaba .
PFX FM 0 lyemunaagu .
PFX FM 0 lyemunaagi .
PFX FM 0 lyemunaazi .
PFX FM 0 lyemunaaki .
PFX FM 0 lyemunaabi .
PFX FM 0 lyemunaali .
PFX FM 0 lyemunaaga .
PFX FM 0 lyemunaaka .
PFX FM 0 lyemunaabu .
PFX FM 0 lyemunaalu .
PFX FM 0 lyemunaaku .
PFX FM 0 lyemunaatu .
PFX FM 0 lyetunaan [^lmnb]
PFX FM l lyetunaand l.[^mn][^u]
PFX FM l lyetunaann l.[mn]
PFX FM w lyetunaamp [w]
PFX FM 0 lyetunaamu .
PFX FM 0 lyetunaaba .
PFX FM 0 lyetunaagu .
PFX FM 0 lyetunaagi .
PFX FM 0 lyetunaazi .
PFX FM 0 lyetunaaki .
PFX FM 0 lyetunaabi .
PFX FM 0 lyetunaali .
PFX FM 0 lyetunaaga .
PFX FM 0 lyetunaaka .
PFX FM 0 lyetunaabu .
PFX FM 0 lyetunaalu .
PFX FM 0 lyetunaaku .
PFX FM 0 lyetunaatu .
PFX FM 0 lyemunaan [^lmnb]
PFX FM l lyemunaand l.[^mn][^u]
PFX FM l lyemunaann l.[mn]
PFX FM w lyemunaamp [w]
PFX FM 0 lyemunaamu .
PFX FM 0 lyemunaaba .
PFX FM 0 lyemunaagu .
PFX FM 0 lyemunaagi .
PFX FM 0 lyemunaazi .
PFX FM 0 lyemunaaki .
PFX FM 0 lyemunaabi .
PFX FM 0 lyemunaali .
PFX FM 0 lyemunaaga .
PFX FM 0 lyemunaaka .
PFX FM 0 lyemunaabu .
PFX FM 0 lyemunaalu .
PFX FM 0 lyemunaaku .
PFX FM 0 lyemunaatu .
PFX FM 0 lyebanaan [^lmnb]
PFX FM l lyebanaand l.[^mn][^u]
PFX FM l lyebanaann l.[mn]
PFX FM w lyebanaamp [w]
PFX FM 0 lyebanaamu .
PFX FM 0 lyebanaaba .
PFX FM 0 lyebanaagu .
PFX FM 0 lyebanaagi .
PFX FM 0 lyebanaazi .
PFX FM 0 lyebanaaki .
PFX FM 0 lyebanaabi .
PFX FM 0 lyebanaali .
PFX FM 0 lyebanaaga .
PFX FM 0 lyebanaaka .
PFX FM 0 lyebanaabu .
PFX FM 0 lyebanaalu .
PFX FM 0 lyebanaaku .
PFX FM 0 lyebanaatu .
PFX FM 0 lyegunaan [^lmnb]
PFX FM l lyegunaand l.[^mn][^u]
PFX FM l lyegunaann l.[mn]
PFX FM w lyegunaamp [w]
PFX FM 0 lyegunaamu .
PFX FM 0 lyegunaaba .
PFX FM 0 lyegunaagu .
PFX FM 0 lyegunaagi .
PFX FM 0 lyegunaazi .
PFX FM 0 lyegunaaki .
PFX FM 0 lyegunaabi .
PFX FM 0 lyegunaali .
PFX FM 0 lyegunaaga .
PFX FM 0 lyegunaaka .
PFX FM 0 lyegunaabu .
PFX FM 0 lyegunaalu .
PFX FM 0 lyegunaaku .
PFX FM 0 lyegunaatu .
PFX FM 0 lyeginaan [^lmnb]
PFX FM l lyeginaand l.[^mn][^u]
PFX FM l lyeginaann l.[mn]
PFX FM w lyeginaamp [w]
PFX FM 0 lyeginaamu .
PFX FM 0 lyeginaaba .
PFX FM 0 lyeginaagu .
PFX FM 0 lyeginaagi .
PFX FM 0 lyeginaazi .
PFX FM 0 lyeginaaki .
PFX FM 0 lyeginaabi .
PFX FM 0 lyeginaali .
PFX FM 0 lyeginaaga .
PFX FM 0 lyeginaaka .
PFX FM 0 lyeginaabu .
PFX FM 0 lyeginaalu .
PFX FM 0 lyeginaaku .
PFX FM 0 lyeginaatu .
PFX FM 0 lyezinaan [^lmnb]
PFX FM l lyezinaand l.[^mn][^u]
PFX FM l lyezinaann l.[mn]
PFX FM w lyezinaamp [w]
PFX FM 0 lyezinaamu .
PFX FM 0 lyezinaaba .
PFX FM 0 lyezinaagu .
PFX FM 0 lyezinaagi .
PFX FM 0 lyezinaazi .
PFX FM 0 lyezinaaki .
PFX FM 0 lyezinaabi .
PFX FM 0 lyezinaali .
PFX FM 0 lyezinaaga .
PFX FM 0 lyezinaaka .
PFX FM 0 lyezinaabu .
PFX FM 0 lyezinaalu .
PFX FM 0 lyezinaaku .
PFX FM 0 lyezinaatu .
PFX FM 0 lyekinaan [^lmnb]
PFX FM l lyekinaand l.[^mn][^u]
PFX FM l lyekinaann l.[mn]
PFX FM w lyekinaamp [w]
PFX FM 0 lyekinaamu .
PFX FM 0 lyekinaaba .
PFX FM 0 lyekinaagu .
PFX FM 0 lyekinaagi .
PFX FM 0 lyekinaazi .
PFX FM 0 lyekinaaki .
PFX FM 0 lyekinaabi .
PFX FM 0 lyekinaali .
PFX FM 0 lyekinaaga .
PFX FM 0 lyekinaaka .
PFX FM 0 lyekinaabu .
PFX FM 0 lyekinaalu .
PFX FM 0 lyekinaaku .
PFX FM 0 lyekinaatu .
PFX FM 0 lyebinaan [^lmnb]
PFX FM l lyebinaand l.[^mn][^u]
PFX FM l lyebinaann l.[mn]
PFX FM w lyebinaamp [w]
PFX FM 0 lyebinaamu .
PFX FM 0 lyebinaaba .
PFX FM 0 lyebinaagu .
PFX FM 0 lyebinaagi .
PFX FM 0 lyebinaazi .
PFX FM 0 lyebinaaki .
PFX FM 0 lyebinaabi .
PFX FM 0 lyebinaali .
PFX FM 0 lyebinaaga .
PFX FM 0 lyebinaaka .
PFX FM 0 lyebinaabu .
PFX FM 0 lyebinaalu .
PFX FM 0 lyebinaaku .
PFX FM 0 lyebinaatu .
PFX FM 0 lyelinaan [^lmnb]
PFX FM l lyelinaand l.[^mn][^u]
PFX FM l lyelinaann l.[mn]
PFX FM w lyelinaamp [w]
PFX FM 0 lyelinaamu .
PFX FM 0 lyelinaaba .
PFX FM 0 lyelinaagu .
PFX FM 0 lyelinaagi .
PFX FM 0 lyelinaazi .
PFX FM 0 lyelinaaki .
PFX FM 0 lyelinaabi .
PFX FM 0 lyelinaali .
PFX FM 0 lyelinaaga .
PFX FM 0 lyelinaaka .
PFX FM 0 lyelinaabu .
PFX FM 0 lyelinaalu .
PFX FM 0 lyelinaaku .
PFX FM 0 lyelinaatu .
PFX FM 0 lyeganaan [^lmnb]
PFX FM l lyeganaand l.[^mn][^u]
PFX FM l lyeganaann l.[mn]
PFX FM w lyeganaamp [w]
PFX FM 0 lyeganaamu .
PFX FM 0 lyeganaaba .
PFX FM 0 lyeganaagu .
PFX FM 0 lyeganaagi .
PFX FM 0 lyeganaazi .
PFX FM 0 lyeganaaki .
PFX FM 0 lyeganaabi .
PFX FM 0 lyeganaali .
PFX FM 0 lyeganaaga .
PFX FM 0 lyeganaaka .
PFX FM 0 lyeganaabu .
PFX FM 0 lyeganaalu .
PFX FM 0 lyeganaaku .
PFX FM 0 lyeganaatu .
PFX FM 0 lyekanaan [^lmnb]
PFX FM l lyekanaand l.[^mn][^u]
PFX FM l lyekanaann l.[mn]
PFX FM w lyekanaamp [w]
PFX FM 0 lyekanaamu .
PFX FM 0 lyekanaaba .
PFX FM 0 lyekanaagu .
PFX FM 0 lyekanaagi .
PFX FM 0 lyekanaazi .
PFX FM 0 lyekanaaki .
PFX FM 0 lyekanaabi .
PFX FM 0 lyekanaali .
PFX FM 0 lyekanaaga .
PFX FM 0 lyekanaaka .
PFX FM 0 lyekanaabu .
PFX FM 0 lyekanaalu .
PFX FM 0 lyekanaaku .
PFX FM 0 lyekanaatu .
PFX FM 0 lyebunaan [^lmnb]
PFX FM l lyebunaand l.[^mn][^u]
PFX FM l lyebunaann l.[mn]
PFX FM w lyebunaamp [w]
PFX FM 0 lyebunaamu .
PFX FM 0 lyebunaaba .
PFX FM 0 lyebunaagu .
PFX FM 0 lyebunaagi .
PFX FM 0 lyebunaazi .
PFX FM 0 lyebunaaki .
PFX FM 0 lyebunaabi .
PFX FM 0 lyebunaali .
PFX FM 0 lyebunaaga .
PFX FM 0 lyebunaaka .
PFX FM 0 lyebunaabu .
PFX FM 0 lyebunaalu .
PFX FM 0 lyebunaaku .
PFX FM 0 lyebunaatu .
PFX FM 0 lyelunaan [^lmnb]
PFX FM l lyelunaand l.[^mn][^u]
PFX FM l lyelunaann l.[mn]
PFX FM w lyelunaamp [w]
PFX FM 0 lyelunaamu .
PFX FM 0 lyelunaaba .
PFX FM 0 lyelunaagu .
PFX FM 0 lyelunaagi .
PFX FM 0 lyelunaazi .
PFX FM 0 lyelunaaki .
PFX FM 0 lyelunaabi .
PFX FM 0 lyelunaali .
PFX FM 0 lyelunaaga .
PFX FM 0 lyelunaaka .
PFX FM 0 lyelunaabu .
PFX FM 0 lyelunaalu .
PFX FM 0 lyelunaaku .
PFX FM 0 lyelunaatu .
PFX FM 0 lyezinaan [^lmnb]
PFX FM l lyezinaand l.[^mn][^u]
PFX FM l lyezinaann l.[mn]
PFX FM w lyezinaamp [w]
PFX FM 0 lyezinaamu .
PFX FM 0 lyezinaaba .
PFX FM 0 lyezinaagu .
PFX FM 0 lyezinaagi .
PFX FM 0 lyezinaazi .
PFX FM 0 lyezinaaki .
PFX FM 0 lyezinaabi .
PFX FM 0 lyezinaali .
PFX FM 0 lyezinaaga .
PFX FM 0 lyezinaaka .
PFX FM 0 lyezinaabu .
PFX FM 0 lyezinaalu .
PFX FM 0 lyezinaaku .
PFX FM 0 lyezinaatu .
PFX FM 0 lyekunaan [^lmnb]
PFX FM l lyekunaand l.[^mn][^u]
PFX FM l lyekunaann l.[mn]
PFX FM w lyekunaamp [w]
PFX FM 0 lyekunaamu .
PFX FM 0 lyekunaaba .
PFX FM 0 lyekunaagu .
PFX FM 0 lyekunaagi .
PFX FM 0 lyekunaazi .
PFX FM 0 lyekunaaki .
PFX FM 0 lyekunaabi .
PFX FM 0 lyekunaali .
PFX FM 0 lyekunaaga .
PFX FM 0 lyekunaaka .
PFX FM 0 lyekunaabu .
PFX FM 0 lyekunaalu .
PFX FM 0 lyekunaaku .
PFX FM 0 lyekunaatu .
PFX FM 0 lyeganaan [^lmnb]
PFX FM l lyeganaand l.[^mn][^u]
PFX FM l lyeganaann l.[mn]
PFX FM w lyeganaamp [w]
PFX FM 0 lyeganaamu .
PFX FM 0 lyeganaaba .
PFX FM 0 lyeganaagu .
PFX FM 0 lyeganaagi .
PFX FM 0 lyeganaazi .
PFX FM 0 lyeganaaki .
PFX FM 0 lyeganaabi .
PFX FM 0 lyeganaali .
PFX FM 0 lyeganaaga .
PFX FM 0 lyeganaaka .
PFX FM 0 lyeganaabu .
PFX FM 0 lyeganaalu .
PFX FM 0 lyeganaaku .
PFX FM 0 lyeganaatu .
PFX FM 0 lyetunaan [^lmnb]
PFX FM l lyetunaand l.[^mn][^u]
PFX FM l lyetunaann l.[mn]
PFX FM w lyetunaamp [w]
PFX FM 0 lyetunaamu .
PFX FM 0 lyetunaaba .
PFX FM 0 lyetunaagu .
PFX FM 0 lyetunaagi .
PFX FM 0 lyetunaazi .
PFX FM 0 lyetunaaki .
PFX FM 0 lyetunaabi .
PFX FM 0 lyetunaali .
PFX FM 0 lyetunaaga .
PFX FM 0 lyetunaaka .
PFX FM 0 lyetunaabu .
PFX FM 0 lyetunaalu .
PFX FM 0 lyetunaaku .
PFX FM 0 lyetunaatu .
PFX FM 0 k'onoon [^lmnb]
PFX FM l k'onoond l.[^mn][^u]
PFX FM l k'onoonn l.[mn]
PFX FM w k'onoomp [w]
PFX FM 0 k'onoomu .
PFX FM 0 k'onooba .
PFX FM 0 k'onoogu .
PFX FM 0 k'onoogi .
PFX FM 0 k'onoozi .
PFX FM 0 k'onooki .
PFX FM 0 k'onoobi .
PFX FM 0 k'onooli .
PFX FM 0 k'onooga .
PFX FM 0 k'onooka .
PFX FM 0 k'onoobu .
PFX FM 0 k'onoolu .
PFX FM 0 k'onooku .
PFX FM 0 k'onootu .
PFX FM 0 k'onaan [^lmnb]
PFX FM l k'onaand l.[^mn][^u]
PFX FM l k'onaann l.[mn]
PFX FM w k'onaamp [w]
PFX FM 0 k'onaamu .
PFX FM 0 k'onaaba .
PFX FM 0 k'onaagu .
PFX FM 0 k'onaagi .
PFX FM 0 k'onaazi .
PFX FM 0 k'onaaki .
PFX FM 0 k'onaabi .
PFX FM 0 k'onaali .
PFX FM 0 k'onaaga .
PFX FM 0 k'onaaka .
PFX FM 0 k'onaabu .
PFX FM 0 k'onaalu .
PFX FM 0 k'onaaku .
PFX FM 0 k'onaatu .
PFX FM 0 k'anaan [^lmnb]
PFX FM l k'anaand l.[^mn][^u]
PFX FM l k'anaann l.[mn]
PFX FM w k'anaamp [w]
PFX FM 0 k'anaamu .
PFX FM 0 k'anaaba .
PFX FM 0 k'anaagu .
PFX FM 0 k'anaagi .
PFX FM 0 k'anaazi .
PFX FM 0 k'anaaki .
PFX FM 0 k'anaabi .
PFX FM 0 k'anaali .
PFX FM 0 k'anaaga .
PFX FM 0 k'anaaka .
PFX FM 0 k'anaabu .
PFX FM 0 k'anaalu .
PFX FM 0 k'anaaku .
PFX FM 0 k'anaatu .
PFX FM 0 k'enaan [^lmnb]
PFX FM l k'enaand l.[^mn][^u]
PFX FM l k'enaann l.[mn]
PFX FM w k'enaamp [w]
PFX FM 0 k'enaamu .
PFX FM 0 k'enaaba .
PFX FM 0 k'enaagu .
PFX FM 0 k'enaagi .
PFX FM 0 k'enaazi .
PFX FM 0 k'enaaki .
PFX FM 0 k'enaabi .
PFX FM 0 k'enaali .
PFX FM 0 k'enaaga .
PFX FM 0 k'enaaka .
PFX FM 0 k'enaabu .
PFX FM 0 k'enaalu .
PFX FM 0 k'enaaku .
PFX FM 0 k'enaatu .
PFX FM 0 kennaaba .
PFX FM 0 kennaagu .
PFX FM 0 kennaagi .
PFX FM 0 kennaazi .
PFX FM 0 kennaaki .
PFX FM 0 kennaabi .
PFX FM 0 kennaali .
PFX FM 0 kennaaga .
PFX FM 0 kennaaka .
PFX FM 0 kennaabu .
PFX FM 0 kennaalu .
PFX FM 0 kennaaku .
PFX FM 0 kennaatu .
PFX FM 0 kennaamu .
PFX FM 0 kemunaan [^lmnb]
PFX FM l kemunaand l.[^mn][^u]
PFX FM l kemunaann l.[mn]
PFX FM w kemunaamp [w]
PFX FM 0 kemunaamu .
PFX FM 0 kemunaaba .
PFX FM 0 kemunaagu .
PFX FM 0 kemunaagi .
PFX FM 0 kemunaazi .
PFX FM 0 kemunaaki .
PFX FM 0 kemunaabi .
PFX FM 0 kemunaali .
PFX FM 0 kemunaaga .
PFX FM 0 kemunaaka .
PFX FM 0 kemunaabu .
PFX FM 0 kemunaalu .
PFX FM 0 kemunaaku .
PFX FM 0 kemunaatu .
PFX FM 0 ketunaan [^lmnb]
PFX FM l ketunaand l.[^mn][^u]
PFX FM l ketunaann l.[mn]
PFX FM w ketunaamp [w]
PFX FM 0 ketunaamu .
PFX FM 0 ketunaaba .
PFX FM 0 ketunaagu .
PFX FM 0 ketunaagi .
PFX FM 0 ketunaazi .
PFX FM 0 ketunaaki .
PFX FM 0 ketunaabi .
PFX FM 0 ketunaali .
PFX FM 0 ketunaaga .
PFX FM 0 ketunaaka .
PFX FM 0 ketunaabu .
PFX FM 0 ketunaalu .
PFX FM 0 ketunaaku .
PFX FM 0 ketunaatu .
PFX FM 0 kemunaan [^lmnb]
PFX FM l kemunaand l.[^mn][^u]
PFX FM l kemunaann l.[mn]
PFX FM w kemunaamp [w]
PFX FM 0 kemunaamu .
PFX FM 0 kemunaaba .
PFX FM 0 kemunaagu .
PFX FM 0 kemunaagi .
PFX FM 0 kemunaazi .
PFX FM 0 kemunaaki .
PFX FM 0 kemunaabi .
PFX FM 0 kemunaali .
PFX FM 0 kemunaaga .
PFX FM 0 kemunaaka .
PFX FM 0 kemunaabu .
PFX FM 0 kemunaalu .
PFX FM 0 kemunaaku .
PFX FM 0 kemunaatu .
PFX FM 0 kebanaan [^lmnb]
PFX FM l kebanaand l.[^mn][^u]
PFX FM l kebanaann l.[mn]
PFX FM w kebanaamp [w]
PFX FM 0 kebanaamu .
PFX FM 0 kebanaaba .
PFX FM 0 kebanaagu .
PFX FM 0 kebanaagi .
PFX FM 0 kebanaazi .
PFX FM 0 kebanaaki .
PFX FM 0 kebanaabi .
PFX FM 0 kebanaali .
PFX FM 0 kebanaaga .
PFX FM 0 kebanaaka .
PFX FM 0 kebanaabu .
PFX FM 0 kebanaalu .
PFX FM 0 kebanaaku .
PFX FM 0 kebanaatu .
PFX FM 0 kegunaan [^lmnb]
PFX FM l kegunaand l.[^mn][^u]
PFX FM l kegunaann l.[mn]
PFX FM w kegunaamp [w]
PFX FM 0 kegunaamu .
PFX FM 0 kegunaaba .
PFX FM 0 kegunaagu .
PFX FM 0 kegunaagi .
PFX FM 0 kegunaazi .
PFX FM 0 kegunaaki .
PFX FM 0 kegunaabi .
PFX FM 0 kegunaali .
PFX FM 0 kegunaaga .
PFX FM 0 kegunaaka .
PFX FM 0 kegunaabu .
PFX FM 0 kegunaalu .
PFX FM 0 kegunaaku .
PFX FM 0 kegunaatu .
PFX FM 0 keginaan [^lmnb]
PFX FM l keginaand l.[^mn][^u]
PFX FM l keginaann l.[mn]
PFX FM w keginaamp [w]
PFX FM 0 keginaamu .
PFX FM 0 keginaaba .
PFX FM 0 keginaagu .
PFX FM 0 keginaagi .
PFX FM 0 keginaazi .
PFX FM 0 keginaaki .
PFX FM 0 keginaabi .
PFX FM 0 keginaali .
PFX FM 0 keginaaga .
PFX FM 0 keginaaka .
PFX FM 0 keginaabu .
PFX FM 0 keginaalu .
PFX FM 0 keginaaku .
PFX FM 0 keginaatu .
PFX FM 0 kezinaan [^lmnb]
PFX FM l kezinaand l.[^mn][^u]
PFX FM l kezinaann l.[mn]
PFX FM w kezinaamp [w]
PFX FM 0 kezinaamu .
PFX FM 0 kezinaaba .
PFX FM 0 kezinaagu .
PFX FM 0 kezinaagi .
PFX FM 0 kezinaazi .
PFX FM 0 kezinaaki .
PFX FM 0 kezinaabi .
PFX FM 0 kezinaali .
PFX FM 0 kezinaaga .
PFX FM 0 kezinaaka .
PFX FM 0 kezinaabu .
PFX FM 0 kezinaalu .
PFX FM 0 kezinaaku .
PFX FM 0 kezinaatu .
PFX FM 0 kekinaan [^lmnb]
PFX FM l kekinaand l.[^mn][^u]
PFX FM l kekinaann l.[mn]
PFX FM w kekinaamp [w]
PFX FM 0 kekinaamu .
PFX FM 0 kekinaaba .
PFX FM 0 kekinaagu .
PFX FM 0 kekinaagi .
PFX FM 0 kekinaazi .
PFX FM 0 kekinaaki .
PFX FM 0 kekinaabi .
PFX FM 0 kekinaali .
PFX FM 0 kekinaaga .
PFX FM 0 kekinaaka .
PFX FM 0 kekinaabu .
PFX FM 0 kekinaalu .
PFX FM 0 kekinaaku .
PFX FM 0 kekinaatu .
PFX FM 0 kebinaan [^lmnb]
PFX FM l kebinaand l.[^mn][^u]
PFX FM l kebinaann l.[mn]
PFX FM w kebinaamp [w]
PFX FM 0 kebinaamu .
PFX FM 0 kebinaaba .
PFX FM 0 kebinaagu .
PFX FM 0 kebinaagi .
PFX FM 0 kebinaazi .
PFX FM 0 kebinaaki .
PFX FM 0 kebinaabi .
PFX FM 0 kebinaali .
PFX FM 0 kebinaaga .
PFX FM 0 kebinaaka .
PFX FM 0 kebinaabu .
PFX FM 0 kebinaalu .
PFX FM 0 kebinaaku .
PFX FM 0 kebinaatu .
PFX FM 0 kelinaan [^lmnb]
PFX FM l kelinaand l.[^mn][^u]
PFX FM l kelinaann l.[mn]
PFX FM w kelinaamp [w]
PFX FM 0 kelinaamu .
PFX FM 0 kelinaaba .
PFX FM 0 kelinaagu .
PFX FM 0 kelinaagi .
PFX FM 0 kelinaazi .
PFX FM 0 kelinaaki .
PFX FM 0 kelinaabi .
PFX FM 0 kelinaali .
PFX FM 0 kelinaaga .
PFX FM 0 kelinaaka .
PFX FM 0 kelinaabu .
PFX FM 0 kelinaalu .
PFX FM 0 kelinaaku .
PFX FM 0 kelinaatu .
PFX FM 0 keganaan [^lmnb]
PFX FM l keganaand l.[^mn][^u]
PFX FM l keganaann l.[mn]
PFX FM w keganaamp [w]
PFX FM 0 keganaamu .
PFX FM 0 keganaaba .
PFX FM 0 keganaagu .
PFX FM 0 keganaagi .
PFX FM 0 keganaazi .
PFX FM 0 keganaaki .
PFX FM 0 keganaabi .
PFX FM 0 keganaali .
PFX FM 0 keganaaga .
PFX FM 0 keganaaka .
PFX FM 0 keganaabu .
PFX FM 0 keganaalu .
PFX FM 0 keganaaku .
PFX FM 0 keganaatu .
PFX FM 0 kekanaan [^lmnb]
PFX FM l kekanaand l.[^mn][^u]
PFX FM l kekanaann l.[mn]
PFX FM w kekanaamp [w]
PFX FM 0 kekanaamu .
PFX FM 0 kekanaaba .
PFX FM 0 kekanaagu .
PFX FM 0 kekanaagi .
PFX FM 0 kekanaazi .
PFX FM 0 kekanaaki .
PFX FM 0 kekanaabi .
PFX FM 0 kekanaali .
PFX FM 0 kekanaaga .
PFX FM 0 kekanaaka .
PFX FM 0 kekanaabu .
PFX FM 0 kekanaalu .
PFX FM 0 kekanaaku .
PFX FM 0 kekanaatu .
PFX FM 0 kebunaan [^lmnb]
PFX FM l kebunaand l.[^mn][^u]
PFX FM l kebunaann l.[mn]
PFX FM w kebunaamp [w]
PFX FM 0 kebunaamu .
PFX FM 0 kebunaaba .
PFX FM 0 kebunaagu .
PFX FM 0 kebunaagi .
PFX FM 0 kebunaazi .
PFX FM 0 kebunaaki .
PFX FM 0 kebunaabi .
PFX FM 0 kebunaali .
PFX FM 0 kebunaaga .
PFX FM 0 kebunaaka .
PFX FM 0 kebunaabu .
PFX FM 0 kebunaalu .
PFX FM 0 kebunaaku .
PFX FM 0 kebunaatu .
PFX FM 0 kelunaan [^lmnb]
PFX FM l kelunaand l.[^mn][^u]
PFX FM l kelunaann l.[mn]
PFX FM w kelunaamp [w]
PFX FM 0 kelunaamu .
PFX FM 0 kelunaaba .
PFX FM 0 kelunaagu .
PFX FM 0 kelunaagi .
PFX FM 0 kelunaazi .
PFX FM 0 kelunaaki .
PFX FM 0 kelunaabi .
PFX FM 0 kelunaali .
PFX FM 0 kelunaaga .
PFX FM 0 kelunaaka .
PFX FM 0 kelunaabu .
PFX FM 0 kelunaalu .
PFX FM 0 kelunaaku .
PFX FM 0 kelunaatu .
PFX FM 0 kezinaan [^lmnb]
PFX FM l kezinaand l.[^mn][^u]
PFX FM l kezinaann l.[mn]
PFX FM w kezinaamp [w]
PFX FM 0 kezinaamu .
PFX FM 0 kezinaaba .
PFX FM 0 kezinaagu .
PFX FM 0 kezinaagi .
PFX FM 0 kezinaazi .
PFX FM 0 kezinaaki .
PFX FM 0 kezinaabi .
PFX FM 0 kezinaali .
PFX FM 0 kezinaaga .
PFX FM 0 kezinaaka .
PFX FM 0 kezinaabu .
PFX FM 0 kezinaalu .
PFX FM 0 kezinaaku .
PFX FM 0 kezinaatu .
PFX FM 0 kekunaan [^lmnb]
PFX FM l kekunaand l.[^mn][^u]
PFX FM l kekunaann l.[mn]
PFX FM w kekunaamp [w]
PFX FM 0 kekunaamu .
PFX FM 0 kekunaaba .
PFX FM 0 kekunaagu .
PFX FM 0 kekunaagi .
PFX FM 0 kekunaazi .
PFX FM 0 kekunaaki .
PFX FM 0 kekunaabi .
PFX FM 0 kekunaali .
PFX FM 0 kekunaaga .
PFX FM 0 kekunaaka .
PFX FM 0 kekunaabu .
PFX FM 0 kekunaalu .
PFX FM 0 kekunaaku .
PFX FM 0 kekunaatu .
PFX FM 0 keganaan [^lmnb]
PFX FM l keganaand l.[^mn][^u]
PFX FM l keganaann l.[mn]
PFX FM w keganaamp [w]
PFX FM 0 keganaamu .
PFX FM 0 keganaaba .
PFX FM 0 keganaagu .
PFX FM 0 keganaagi .
PFX FM 0 keganaazi .
PFX FM 0 keganaaki .
PFX FM 0 keganaabi .
PFX FM 0 keganaali .
PFX FM 0 keganaaga .
PFX FM 0 keganaaka .
PFX FM 0 keganaabu .
PFX FM 0 keganaalu .
PFX FM 0 keganaaku .
PFX FM 0 keganaatu .
PFX FM 0 ketunaan [^lmnb]
PFX FM l ketunaand l.[^mn][^u]
PFX FM l ketunaann l.[mn]
PFX FM w ketunaamp [w]
PFX FM 0 ketunaamu .
PFX FM 0 ketunaaba .
PFX FM 0 ketunaagu .
PFX FM 0 ketunaagi .
PFX FM 0 ketunaazi .
PFX FM 0 ketunaaki .
PFX FM 0 ketunaabi .
PFX FM 0 ketunaali .
PFX FM 0 ketunaaga .
PFX FM 0 ketunaaka .
PFX FM 0 ketunaabu .
PFX FM 0 ketunaalu .
PFX FM 0 ketunaaku .
PFX FM 0 ketunaatu ."""

rule_right_raw = """
PFX Ob Y 18
PFX Ob 0 n [^lmnb]
PFX Ob l nd l.[^mn][^u]
PFX Ob l nn l.[mn]
PFX Ob w mp [w]
PFX Ob 0 mu .
PFX Ob 0 ba .
PFX Ob 0 gu .
PFX Ob 0 gi .
PFX Ob 0 zi .
PFX Ob 0 ki .
PFX Ob 0 bi .
PFX Ob 0 li .
PFX Ob 0 ga .
PFX Ob 0 ka .
PFX Ob 0 bu .
PFX Ob 0 lu .
PFX Ob 0 ku .
PFX Ob 0 tu ."""

FLAG_DESCRIPTIONS = {
    "FM": "FM",
    "Ob": "Object markers",
}

def parse_rules(raw_text):
    rules = []
    for line in raw_text.strip().split('\n'):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        s = s.split('#', 1)[0].strip()
        parts = s.split()
        if len(parts) < 4:
            continue
        if parts[2] == 'Y':
            continue
        cond = parts[4] if len(parts) > 4 else '.'
        rules.append({'strip': parts[2], 'add': parts[3], 'cond': cond})
    return rules

def generate_block():
    lefts = parse_rules(rule_left_raw)
    rights = parse_rules(rule_right_raw)
    new_rules = []

    for left in lefts:
        for right in rights:
            if left['strip'] != '0':
                if not right['add'].startswith(left['strip']):
                    continue
                combined = left['add'] + right['add'][len(left['strip']):]
            else:
                combined = left['add'] + right['add']

            if left['cond'] != '.':
                if not re.match(left['cond'], right['add']):
                    continue

            new_rules.append({'strip': right['strip'], 'add': combined, 'cond': right['cond']})

    out_flag = "GO"
    left_desc = FLAG_DESCRIPTIONS.get("FM", "FM")
    right_desc = FLAG_DESCRIPTIONS.get("Ob", "Ob")
    comment_line = "# Cross product of {} ({}) and {} ({}) to {}".format(
        "FM", left_desc, "Ob", right_desc, out_flag
    )

    output = ["PFX {} Y {}".format(out_flag, len(new_rules))]
    for r in new_rules:
        output.append("PFX {} {} {} {}".format(out_flag, r['strip'], r['add'], r['cond']))

    return (out_flag, "\n".join([comment_line] + output) + "\n")

def main():
    if not os.path.exists(AFF_FILE):
        print("Error: {} not found.".format(AFF_FILE))
        return

    out_flag, block = generate_block()

    with open(AFF_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    first_flag_idx = None
    last_flag_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("PFX {} ".format(out_flag)):
            if first_flag_idx is None:
                first_flag_idx = i
            last_flag_idx = i

    if first_flag_idx is not None and first_flag_idx > 0:
        prev_line = lines[first_flag_idx - 1].strip()
        if prev_line.startswith("# Cross product"):
            start_idx = first_flag_idx - 1
        else:
            start_idx = first_flag_idx
    elif first_flag_idx is not None:
        start_idx = first_flag_idx
    else:
        start_idx = None

    if start_idx is not None and last_flag_idx is not None:
        # Replace existing block in-place.
        new_lines = lines[:start_idx] + [block] + lines[last_flag_idx + 1:]
    else:
        # Insert before an anchor flag if requested; otherwise append.
        insert_idx = None
        if INSERT_BEFORE_FLAG:
            anchor_prefix = "PFX {} ".format(INSERT_BEFORE_FLAG)
            for i, line in enumerate(lines):
                if line.strip().startswith(anchor_prefix):
                    insert_idx = i
                    # If the anchor PFX block is preceded by one or more cross-product
                    # comment lines, insert before those comments to keep them attached
                    # to the anchor block.
                    while insert_idx > 0 and lines[insert_idx - 1].strip().startswith("# Cross product"):
                        insert_idx -= 1
                    break

        if insert_idx is not None:
            new_lines = lines[:insert_idx] + [block] + lines[insert_idx:]
        else:
            new_lines = lines
            if new_lines and not new_lines[-1].endswith(chr(10)):
                new_lines[-1] += chr(10)
            new_lines.append(block)

    with open(AFF_FILE, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    print("{}: updated in place.".format(out_flag))

if __name__ == '__main__':
    main()
