import re
import os
from pathlib import Path

# Cross product generator: FV x OR => GP
# Description:
# - Left block `FV`: FV
# - Right block `OR`: Special reflexive object markers
# - Output flag `GP`: Cross-product prefixes for FV x OR

REPO_ROOT = Path(__file__).resolve().parents[1]
AFF_FILE = REPO_ROOT / "Luganda.aff"

# If set to a flag name (e.g. "HB"), the generated cross-product block will be inserted
# immediately before the first "PFX <flag>" line when the output flag block doesn't
# already exist in the .aff.
INSERT_BEFORE_FLAG = "".strip() or None

rule_left_raw = """
PFX FV Y 3380
PFX FV 0 w'otolin [^lmnb]
PFX FV l w'otolind l.[^mn][^u]
PFX FV l w'otolinn l.[mn]
PFX FV w w'otolimp [w]
PFX FV 0 w'otolimu .
PFX FV 0 w'otoliba .
PFX FV 0 w'otoligu .
PFX FV 0 w'otoligi .
PFX FV 0 w'otolizi .
PFX FV 0 w'otoliki .
PFX FV 0 w'otolibi .
PFX FV 0 w'otolili .
PFX FV 0 w'otoliga .
PFX FV 0 w'otolika .
PFX FV 0 w'otolibu .
PFX FV 0 w'otolilu .
PFX FV 0 w'otoliku .
PFX FV 0 w'otolitu .
PFX FV 0 w'atalin [^lmnb]
PFX FV l w'atalind l.[^mn][^u]
PFX FV l w'atalinn l.[mn]
PFX FV w w'atalimp [w]
PFX FV 0 w'atalimu .
PFX FV 0 w'ataliba .
PFX FV 0 w'ataligu .
PFX FV 0 w'ataligi .
PFX FV 0 w'atalizi .
PFX FV 0 w'ataliki .
PFX FV 0 w'atalibi .
PFX FV 0 w'atalili .
PFX FV 0 w'ataliga .
PFX FV 0 w'atalika .
PFX FV 0 w'atalibu .
PFX FV 0 w'atalilu .
PFX FV 0 w'ataliku .
PFX FV 0 w'atalitu .
PFX FV 0 w'etelin [^lmnb]
PFX FV l w'etelind l.[^mn][^u]
PFX FV l w'etelinn l.[mn]
PFX FV w w'etelimp [w]
PFX FV 0 w'etelimu .
PFX FV 0 w'eteliba .
PFX FV 0 w'eteligu .
PFX FV 0 w'eteligi .
PFX FV 0 w'etelizi .
PFX FV 0 w'eteliki .
PFX FV 0 w'etelibi .
PFX FV 0 w'etelili .
PFX FV 0 w'eteliga .
PFX FV 0 w'etelika .
PFX FV 0 w'etelibu .
PFX FV 0 w'etelilu .
PFX FV 0 w'eteliku .
PFX FV 0 w'etelitu .
PFX FV 0 wessiliba .
PFX FV 0 wessiligu .
PFX FV 0 wessiligi .
PFX FV 0 wessilizi .
PFX FV 0 wessiliki .
PFX FV 0 wessilibi .
PFX FV 0 wessilili .
PFX FV 0 wessiliga .
PFX FV 0 wessilika .
PFX FV 0 wessilibu .
PFX FV 0 wessililu .
PFX FV 0 wessiliku .
PFX FV 0 wessilitu .
PFX FV 0 wessilimu .
PFX FV 0 wetutalin [^lmnb]
PFX FV l wetutalind l.[^mn][^u]
PFX FV l wetutalinn l.[mn]
PFX FV w wetutalimp [w]
PFX FV 0 wetutalimu .
PFX FV 0 wetutaliba .
PFX FV 0 wetutaligu .
PFX FV 0 wetutaligi .
PFX FV 0 wetutalizi .
PFX FV 0 wetutaliki .
PFX FV 0 wetutalibi .
PFX FV 0 wetutalili .
PFX FV 0 wetutaliga .
PFX FV 0 wetutalika .
PFX FV 0 wetutalibu .
PFX FV 0 wetutalilu .
PFX FV 0 wetutaliku .
PFX FV 0 wetutalitu .
PFX FV 0 wemutalin [^lmnb]
PFX FV l wemutalind l.[^mn][^u]
PFX FV l wemutalinn l.[mn]
PFX FV w wemutalimp [w]
PFX FV 0 wemutalimu .
PFX FV 0 wemutaliba .
PFX FV 0 wemutaligu .
PFX FV 0 wemutaligi .
PFX FV 0 wemutalizi .
PFX FV 0 wemutaliki .
PFX FV 0 wemutalibi .
PFX FV 0 wemutalili .
PFX FV 0 wemutaliga .
PFX FV 0 wemutalika .
PFX FV 0 wemutalibu .
PFX FV 0 wemutalilu .
PFX FV 0 wemutaliku .
PFX FV 0 wemutalitu .
PFX FV 0 webatalin [^lmnb]
PFX FV l webatalind l.[^mn][^u]
PFX FV l webatalinn l.[mn]
PFX FV w webatalimp [w]
PFX FV 0 webatalimu .
PFX FV 0 webataliba .
PFX FV 0 webataligu .
PFX FV 0 webataligi .
PFX FV 0 webatalizi .
PFX FV 0 webataliki .
PFX FV 0 webatalibi .
PFX FV 0 webatalili .
PFX FV 0 webataliga .
PFX FV 0 webatalika .
PFX FV 0 webatalibu .
PFX FV 0 webatalilu .
PFX FV 0 webataliku .
PFX FV 0 webatalitu .
PFX FV 0 wegutalin [^lmnb]
PFX FV l wegutalind l.[^mn][^u]
PFX FV l wegutalinn l.[mn]
PFX FV w wegutalimp [w]
PFX FV 0 wegutalimu .
PFX FV 0 wegutaliba .
PFX FV 0 wegutaligu .
PFX FV 0 wegutaligi .
PFX FV 0 wegutalizi .
PFX FV 0 wegutaliki .
PFX FV 0 wegutalibi .
PFX FV 0 wegutalili .
PFX FV 0 wegutaliga .
PFX FV 0 wegutalika .
PFX FV 0 wegutalibu .
PFX FV 0 wegutalilu .
PFX FV 0 wegutaliku .
PFX FV 0 wegutalitu .
PFX FV 0 wegitalin [^lmnb]
PFX FV l wegitalind l.[^mn][^u]
PFX FV l wegitalinn l.[mn]
PFX FV w wegitalimp [w]
PFX FV 0 wegitalimu .
PFX FV 0 wegitaliba .
PFX FV 0 wegitaligu .
PFX FV 0 wegitaligi .
PFX FV 0 wegitalizi .
PFX FV 0 wegitaliki .
PFX FV 0 wegitalibi .
PFX FV 0 wegitalili .
PFX FV 0 wegitaliga .
PFX FV 0 wegitalika .
PFX FV 0 wegitalibu .
PFX FV 0 wegitalilu .
PFX FV 0 wegitaliku .
PFX FV 0 wegitalitu .
PFX FV 0 wezitalin [^lmnb]
PFX FV l wezitalind l.[^mn][^u]
PFX FV l wezitalinn l.[mn]
PFX FV w wezitalimp [w]
PFX FV 0 wezitalimu .
PFX FV 0 wezitaliba .
PFX FV 0 wezitaligu .
PFX FV 0 wezitaligi .
PFX FV 0 wezitalizi .
PFX FV 0 wezitaliki .
PFX FV 0 wezitalibi .
PFX FV 0 wezitalili .
PFX FV 0 wezitaliga .
PFX FV 0 wezitalika .
PFX FV 0 wezitalibu .
PFX FV 0 wezitalilu .
PFX FV 0 wezitaliku .
PFX FV 0 wezitalitu .
PFX FV 0 wekitalin [^lmnb]
PFX FV l wekitalind l.[^mn][^u]
PFX FV l wekitalinn l.[mn]
PFX FV w wekitalimp [w]
PFX FV 0 wekitalimu .
PFX FV 0 wekitaliba .
PFX FV 0 wekitaligu .
PFX FV 0 wekitaligi .
PFX FV 0 wekitalizi .
PFX FV 0 wekitaliki .
PFX FV 0 wekitalibi .
PFX FV 0 wekitalili .
PFX FV 0 wekitaliga .
PFX FV 0 wekitalika .
PFX FV 0 wekitalibu .
PFX FV 0 wekitalilu .
PFX FV 0 wekitaliku .
PFX FV 0 wekitalitu .
PFX FV 0 webitalin [^lmnb]
PFX FV l webitalind l.[^mn][^u]
PFX FV l webitalinn l.[mn]
PFX FV w webitalimp [w]
PFX FV 0 webitalimu .
PFX FV 0 webitaliba .
PFX FV 0 webitaligu .
PFX FV 0 webitaligi .
PFX FV 0 webitalizi .
PFX FV 0 webitaliki .
PFX FV 0 webitalibi .
PFX FV 0 webitalili .
PFX FV 0 webitaliga .
PFX FV 0 webitalika .
PFX FV 0 webitalibu .
PFX FV 0 webitalilu .
PFX FV 0 webitaliku .
PFX FV 0 webitalitu .
PFX FV 0 welitalin [^lmnb]
PFX FV l welitalind l.[^mn][^u]
PFX FV l welitalinn l.[mn]
PFX FV w welitalimp [w]
PFX FV 0 welitalimu .
PFX FV 0 welitaliba .
PFX FV 0 welitaligu .
PFX FV 0 welitaligi .
PFX FV 0 welitalizi .
PFX FV 0 welitaliki .
PFX FV 0 welitalibi .
PFX FV 0 welitalili .
PFX FV 0 welitaliga .
PFX FV 0 welitalika .
PFX FV 0 welitalibu .
PFX FV 0 welitalilu .
PFX FV 0 welitaliku .
PFX FV 0 welitalitu .
PFX FV 0 wegatalin [^lmnb]
PFX FV l wegatalind l.[^mn][^u]
PFX FV l wegatalinn l.[mn]
PFX FV w wegatalimp [w]
PFX FV 0 wegatalimu .
PFX FV 0 wegataliba .
PFX FV 0 wegataligu .
PFX FV 0 wegataligi .
PFX FV 0 wegatalizi .
PFX FV 0 wegataliki .
PFX FV 0 wegatalibi .
PFX FV 0 wegatalili .
PFX FV 0 wegataliga .
PFX FV 0 wegatalika .
PFX FV 0 wegatalibu .
PFX FV 0 wegatalilu .
PFX FV 0 wegataliku .
PFX FV 0 wegatalitu .
PFX FV 0 wekatalin [^lmnb]
PFX FV l wekatalind l.[^mn][^u]
PFX FV l wekatalinn l.[mn]
PFX FV w wekatalimp [w]
PFX FV 0 wekatalimu .
PFX FV 0 wekataliba .
PFX FV 0 wekataligu .
PFX FV 0 wekataligi .
PFX FV 0 wekatalizi .
PFX FV 0 wekataliki .
PFX FV 0 wekatalibi .
PFX FV 0 wekatalili .
PFX FV 0 wekataliga .
PFX FV 0 wekatalika .
PFX FV 0 wekatalibu .
PFX FV 0 wekatalilu .
PFX FV 0 wekataliku .
PFX FV 0 wekatalitu .
PFX FV 0 webutalin [^lmnb]
PFX FV l webutalind l.[^mn][^u]
PFX FV l webutalinn l.[mn]
PFX FV w webutalimp [w]
PFX FV 0 webutalimu .
PFX FV 0 webutaliba .
PFX FV 0 webutaligu .
PFX FV 0 webutaligi .
PFX FV 0 webutalizi .
PFX FV 0 webutaliki .
PFX FV 0 webutalibi .
PFX FV 0 webutalili .
PFX FV 0 webutaliga .
PFX FV 0 webutalika .
PFX FV 0 webutalibu .
PFX FV 0 webutalilu .
PFX FV 0 webutaliku .
PFX FV 0 webutalitu .
PFX FV 0 welutalin [^lmnb]
PFX FV l welutalind l.[^mn][^u]
PFX FV l welutalinn l.[mn]
PFX FV w welutalimp [w]
PFX FV 0 welutalimu .
PFX FV 0 welutaliba .
PFX FV 0 welutaligu .
PFX FV 0 welutaligi .
PFX FV 0 welutalizi .
PFX FV 0 welutaliki .
PFX FV 0 welutalibi .
PFX FV 0 welutalili .
PFX FV 0 welutaliga .
PFX FV 0 welutalika .
PFX FV 0 welutalibu .
PFX FV 0 welutalilu .
PFX FV 0 welutaliku .
PFX FV 0 welutalitu .
PFX FV 0 wekutalin [^lmnb]
PFX FV l wekutalind l.[^mn][^u]
PFX FV l wekutalinn l.[mn]
PFX FV w wekutalimp [w]
PFX FV 0 wekutalimu .
PFX FV 0 wekutaliba .
PFX FV 0 wekutaligu .
PFX FV 0 wekutaligi .
PFX FV 0 wekutalizi .
PFX FV 0 wekutaliki .
PFX FV 0 wekutalibi .
PFX FV 0 wekutalili .
PFX FV 0 wekutaliga .
PFX FV 0 wekutalika .
PFX FV 0 wekutalibu .
PFX FV 0 wekutalilu .
PFX FV 0 wekutaliku .
PFX FV 0 wekutalitu .
PFX FV 0 wetutalin [^lmnb]
PFX FV l wetutalind l.[^mn][^u]
PFX FV l wetutalinn l.[mn]
PFX FV w wetutalimp [w]
PFX FV 0 wetutalimu .
PFX FV 0 wetutaliba .
PFX FV 0 wetutaligu .
PFX FV 0 wetutaligi .
PFX FV 0 wetutalizi .
PFX FV 0 wetutaliki .
PFX FV 0 wetutalibi .
PFX FV 0 wetutalili .
PFX FV 0 wetutaliga .
PFX FV 0 wetutalika .
PFX FV 0 wetutalibu .
PFX FV 0 wetutalilu .
PFX FV 0 wetutaliku .
PFX FV 0 wetutalitu .
PFX FV 0 bw'otolin [^lmnb]
PFX FV l bw'otolind l.[^mn][^u]
PFX FV l bw'otolinn l.[mn]
PFX FV w bw'otolimp [w]
PFX FV 0 bw'otolimu .
PFX FV 0 bw'otoliba .
PFX FV 0 bw'otoligu .
PFX FV 0 bw'otoligi .
PFX FV 0 bw'otolizi .
PFX FV 0 bw'otoliki .
PFX FV 0 bw'otolibi .
PFX FV 0 bw'otolili .
PFX FV 0 bw'otoliga .
PFX FV 0 bw'otolika .
PFX FV 0 bw'otolibu .
PFX FV 0 bw'otolilu .
PFX FV 0 bw'otoliku .
PFX FV 0 bw'otolitu .
PFX FV 0 bw'atalin [^lmnb]
PFX FV l bw'atalind l.[^mn][^u]
PFX FV l bw'atalinn l.[mn]
PFX FV w bw'atalimp [w]
PFX FV 0 bw'atalimu .
PFX FV 0 bw'ataliba .
PFX FV 0 bw'ataligu .
PFX FV 0 bw'ataligi .
PFX FV 0 bw'atalizi .
PFX FV 0 bw'ataliki .
PFX FV 0 bw'atalibi .
PFX FV 0 bw'atalili .
PFX FV 0 bw'ataliga .
PFX FV 0 bw'atalika .
PFX FV 0 bw'atalibu .
PFX FV 0 bw'atalilu .
PFX FV 0 bw'ataliku .
PFX FV 0 bw'atalitu .
PFX FV 0 bw'etelin [^lmnb]
PFX FV l bw'etelind l.[^mn][^u]
PFX FV l bw'etelinn l.[mn]
PFX FV w bw'etelimp [w]
PFX FV 0 bw'etelimu .
PFX FV 0 bw'eteliba .
PFX FV 0 bw'eteligu .
PFX FV 0 bw'eteligi .
PFX FV 0 bw'etelizi .
PFX FV 0 bw'eteliki .
PFX FV 0 bw'etelibi .
PFX FV 0 bw'etelili .
PFX FV 0 bw'eteliga .
PFX FV 0 bw'etelika .
PFX FV 0 bw'etelibu .
PFX FV 0 bw'etelilu .
PFX FV 0 bw'eteliku .
PFX FV 0 bw'etelitu .
PFX FV 0 bwessiliba .
PFX FV 0 bwessiligu .
PFX FV 0 bwessiligi .
PFX FV 0 bwessilizi .
PFX FV 0 bwessiliki .
PFX FV 0 bwessilibi .
PFX FV 0 bwessilili .
PFX FV 0 bwessiliga .
PFX FV 0 bwessilika .
PFX FV 0 bwessilibu .
PFX FV 0 bwessililu .
PFX FV 0 bwessiliku .
PFX FV 0 bwessilitu .
PFX FV 0 bwessilimu .
PFX FV 0 bwetutalin [^lmnb]
PFX FV l bwetutalind l.[^mn][^u]
PFX FV l bwetutalinn l.[mn]
PFX FV w bwetutalimp [w]
PFX FV 0 bwetutalimu .
PFX FV 0 bwetutaliba .
PFX FV 0 bwetutaligu .
PFX FV 0 bwetutaligi .
PFX FV 0 bwetutalizi .
PFX FV 0 bwetutaliki .
PFX FV 0 bwetutalibi .
PFX FV 0 bwetutalili .
PFX FV 0 bwetutaliga .
PFX FV 0 bwetutalika .
PFX FV 0 bwetutalibu .
PFX FV 0 bwetutalilu .
PFX FV 0 bwetutaliku .
PFX FV 0 bwetutalitu .
PFX FV 0 bwemutalin [^lmnb]
PFX FV l bwemutalind l.[^mn][^u]
PFX FV l bwemutalinn l.[mn]
PFX FV w bwemutalimp [w]
PFX FV 0 bwemutalimu .
PFX FV 0 bwemutaliba .
PFX FV 0 bwemutaligu .
PFX FV 0 bwemutaligi .
PFX FV 0 bwemutalizi .
PFX FV 0 bwemutaliki .
PFX FV 0 bwemutalibi .
PFX FV 0 bwemutalili .
PFX FV 0 bwemutaliga .
PFX FV 0 bwemutalika .
PFX FV 0 bwemutalibu .
PFX FV 0 bwemutalilu .
PFX FV 0 bwemutaliku .
PFX FV 0 bwemutalitu .
PFX FV 0 bwebatalin [^lmnb]
PFX FV l bwebatalind l.[^mn][^u]
PFX FV l bwebatalinn l.[mn]
PFX FV w bwebatalimp [w]
PFX FV 0 bwebatalimu .
PFX FV 0 bwebataliba .
PFX FV 0 bwebataligu .
PFX FV 0 bwebataligi .
PFX FV 0 bwebatalizi .
PFX FV 0 bwebataliki .
PFX FV 0 bwebatalibi .
PFX FV 0 bwebatalili .
PFX FV 0 bwebataliga .
PFX FV 0 bwebatalika .
PFX FV 0 bwebatalibu .
PFX FV 0 bwebatalilu .
PFX FV 0 bwebataliku .
PFX FV 0 bwebatalitu .
PFX FV 0 bwegutalin [^lmnb]
PFX FV l bwegutalind l.[^mn][^u]
PFX FV l bwegutalinn l.[mn]
PFX FV w bwegutalimp [w]
PFX FV 0 bwegutalimu .
PFX FV 0 bwegutaliba .
PFX FV 0 bwegutaligu .
PFX FV 0 bwegutaligi .
PFX FV 0 bwegutalizi .
PFX FV 0 bwegutaliki .
PFX FV 0 bwegutalibi .
PFX FV 0 bwegutalili .
PFX FV 0 bwegutaliga .
PFX FV 0 bwegutalika .
PFX FV 0 bwegutalibu .
PFX FV 0 bwegutalilu .
PFX FV 0 bwegutaliku .
PFX FV 0 bwegutalitu .
PFX FV 0 bwegitalin [^lmnb]
PFX FV l bwegitalind l.[^mn][^u]
PFX FV l bwegitalinn l.[mn]
PFX FV w bwegitalimp [w]
PFX FV 0 bwegitalimu .
PFX FV 0 bwegitaliba .
PFX FV 0 bwegitaligu .
PFX FV 0 bwegitaligi .
PFX FV 0 bwegitalizi .
PFX FV 0 bwegitaliki .
PFX FV 0 bwegitalibi .
PFX FV 0 bwegitalili .
PFX FV 0 bwegitaliga .
PFX FV 0 bwegitalika .
PFX FV 0 bwegitalibu .
PFX FV 0 bwegitalilu .
PFX FV 0 bwegitaliku .
PFX FV 0 bwegitalitu .
PFX FV 0 bwezitalin [^lmnb]
PFX FV l bwezitalind l.[^mn][^u]
PFX FV l bwezitalinn l.[mn]
PFX FV w bwezitalimp [w]
PFX FV 0 bwezitalimu .
PFX FV 0 bwezitaliba .
PFX FV 0 bwezitaligu .
PFX FV 0 bwezitaligi .
PFX FV 0 bwezitalizi .
PFX FV 0 bwezitaliki .
PFX FV 0 bwezitalibi .
PFX FV 0 bwezitalili .
PFX FV 0 bwezitaliga .
PFX FV 0 bwezitalika .
PFX FV 0 bwezitalibu .
PFX FV 0 bwezitalilu .
PFX FV 0 bwezitaliku .
PFX FV 0 bwezitalitu .
PFX FV 0 bwekitalin [^lmnb]
PFX FV l bwekitalind l.[^mn][^u]
PFX FV l bwekitalinn l.[mn]
PFX FV w bwekitalimp [w]
PFX FV 0 bwekitalimu .
PFX FV 0 bwekitaliba .
PFX FV 0 bwekitaligu .
PFX FV 0 bwekitaligi .
PFX FV 0 bwekitalizi .
PFX FV 0 bwekitaliki .
PFX FV 0 bwekitalibi .
PFX FV 0 bwekitalili .
PFX FV 0 bwekitaliga .
PFX FV 0 bwekitalika .
PFX FV 0 bwekitalibu .
PFX FV 0 bwekitalilu .
PFX FV 0 bwekitaliku .
PFX FV 0 bwekitalitu .
PFX FV 0 bwebitalin [^lmnb]
PFX FV l bwebitalind l.[^mn][^u]
PFX FV l bwebitalinn l.[mn]
PFX FV w bwebitalimp [w]
PFX FV 0 bwebitalimu .
PFX FV 0 bwebitaliba .
PFX FV 0 bwebitaligu .
PFX FV 0 bwebitaligi .
PFX FV 0 bwebitalizi .
PFX FV 0 bwebitaliki .
PFX FV 0 bwebitalibi .
PFX FV 0 bwebitalili .
PFX FV 0 bwebitaliga .
PFX FV 0 bwebitalika .
PFX FV 0 bwebitalibu .
PFX FV 0 bwebitalilu .
PFX FV 0 bwebitaliku .
PFX FV 0 bwebitalitu .
PFX FV 0 bwelitalin [^lmnb]
PFX FV l bwelitalind l.[^mn][^u]
PFX FV l bwelitalinn l.[mn]
PFX FV w bwelitalimp [w]
PFX FV 0 bwelitalimu .
PFX FV 0 bwelitaliba .
PFX FV 0 bwelitaligu .
PFX FV 0 bwelitaligi .
PFX FV 0 bwelitalizi .
PFX FV 0 bwelitaliki .
PFX FV 0 bwelitalibi .
PFX FV 0 bwelitalili .
PFX FV 0 bwelitaliga .
PFX FV 0 bwelitalika .
PFX FV 0 bwelitalibu .
PFX FV 0 bwelitalilu .
PFX FV 0 bwelitaliku .
PFX FV 0 bwelitalitu .
PFX FV 0 bwegatalin [^lmnb]
PFX FV l bwegatalind l.[^mn][^u]
PFX FV l bwegatalinn l.[mn]
PFX FV w bwegatalimp [w]
PFX FV 0 bwegatalimu .
PFX FV 0 bwegataliba .
PFX FV 0 bwegataligu .
PFX FV 0 bwegataligi .
PFX FV 0 bwegatalizi .
PFX FV 0 bwegataliki .
PFX FV 0 bwegatalibi .
PFX FV 0 bwegatalili .
PFX FV 0 bwegataliga .
PFX FV 0 bwegatalika .
PFX FV 0 bwegatalibu .
PFX FV 0 bwegatalilu .
PFX FV 0 bwegataliku .
PFX FV 0 bwegatalitu .
PFX FV 0 bwekatalin [^lmnb]
PFX FV l bwekatalind l.[^mn][^u]
PFX FV l bwekatalinn l.[mn]
PFX FV w bwekatalimp [w]
PFX FV 0 bwekatalimu .
PFX FV 0 bwekataliba .
PFX FV 0 bwekataligu .
PFX FV 0 bwekataligi .
PFX FV 0 bwekatalizi .
PFX FV 0 bwekataliki .
PFX FV 0 bwekatalibi .
PFX FV 0 bwekatalili .
PFX FV 0 bwekataliga .
PFX FV 0 bwekatalika .
PFX FV 0 bwekatalibu .
PFX FV 0 bwekatalilu .
PFX FV 0 bwekataliku .
PFX FV 0 bwekatalitu .
PFX FV 0 bwebutalin [^lmnb]
PFX FV l bwebutalind l.[^mn][^u]
PFX FV l bwebutalinn l.[mn]
PFX FV w bwebutalimp [w]
PFX FV 0 bwebutalimu .
PFX FV 0 bwebutaliba .
PFX FV 0 bwebutaligu .
PFX FV 0 bwebutaligi .
PFX FV 0 bwebutalizi .
PFX FV 0 bwebutaliki .
PFX FV 0 bwebutalibi .
PFX FV 0 bwebutalili .
PFX FV 0 bwebutaliga .
PFX FV 0 bwebutalika .
PFX FV 0 bwebutalibu .
PFX FV 0 bwebutalilu .
PFX FV 0 bwebutaliku .
PFX FV 0 bwebutalitu .
PFX FV 0 bwelutalin [^lmnb]
PFX FV l bwelutalind l.[^mn][^u]
PFX FV l bwelutalinn l.[mn]
PFX FV w bwelutalimp [w]
PFX FV 0 bwelutalimu .
PFX FV 0 bwelutaliba .
PFX FV 0 bwelutaligu .
PFX FV 0 bwelutaligi .
PFX FV 0 bwelutalizi .
PFX FV 0 bwelutaliki .
PFX FV 0 bwelutalibi .
PFX FV 0 bwelutalili .
PFX FV 0 bwelutaliga .
PFX FV 0 bwelutalika .
PFX FV 0 bwelutalibu .
PFX FV 0 bwelutalilu .
PFX FV 0 bwelutaliku .
PFX FV 0 bwelutalitu .
PFX FV 0 bwekutalin [^lmnb]
PFX FV l bwekutalind l.[^mn][^u]
PFX FV l bwekutalinn l.[mn]
PFX FV w bwekutalimp [w]
PFX FV 0 bwekutalimu .
PFX FV 0 bwekutaliba .
PFX FV 0 bwekutaligu .
PFX FV 0 bwekutaligi .
PFX FV 0 bwekutalizi .
PFX FV 0 bwekutaliki .
PFX FV 0 bwekutalibi .
PFX FV 0 bwekutalili .
PFX FV 0 bwekutaliga .
PFX FV 0 bwekutalika .
PFX FV 0 bwekutalibu .
PFX FV 0 bwekutalilu .
PFX FV 0 bwekutaliku .
PFX FV 0 bwekutalitu .
PFX FV 0 bwetutalin [^lmnb]
PFX FV l bwetutalind l.[^mn][^u]
PFX FV l bwetutalinn l.[mn]
PFX FV w bwetutalimp [w]
PFX FV 0 bwetutalimu .
PFX FV 0 bwetutaliba .
PFX FV 0 bwetutaligu .
PFX FV 0 bwetutaligi .
PFX FV 0 bwetutalizi .
PFX FV 0 bwetutaliki .
PFX FV 0 bwetutalibi .
PFX FV 0 bwetutalili .
PFX FV 0 bwetutaliga .
PFX FV 0 bwetutalika .
PFX FV 0 bwetutalibu .
PFX FV 0 bwetutalilu .
PFX FV 0 bwetutaliku .
PFX FV 0 bwetutalitu .
PFX FV 0 lw'otolin [^lmnb]
PFX FV l lw'otolind l.[^mn][^u]
PFX FV l lw'otolinn l.[mn]
PFX FV w lw'otolimp [w]
PFX FV 0 lw'otolimu .
PFX FV 0 lw'otoliba .
PFX FV 0 lw'otoligu .
PFX FV 0 lw'otoligi .
PFX FV 0 lw'otolizi .
PFX FV 0 lw'otoliki .
PFX FV 0 lw'otolibi .
PFX FV 0 lw'otolili .
PFX FV 0 lw'otoliga .
PFX FV 0 lw'otolika .
PFX FV 0 lw'otolibu .
PFX FV 0 lw'otolilu .
PFX FV 0 lw'otoliku .
PFX FV 0 lw'otolitu .
PFX FV 0 lw'atalin [^lmnb]
PFX FV l lw'atalind l.[^mn][^u]
PFX FV l lw'atalinn l.[mn]
PFX FV w lw'atalimp [w]
PFX FV 0 lw'atalimu .
PFX FV 0 lw'ataliba .
PFX FV 0 lw'ataligu .
PFX FV 0 lw'ataligi .
PFX FV 0 lw'atalizi .
PFX FV 0 lw'ataliki .
PFX FV 0 lw'atalibi .
PFX FV 0 lw'atalili .
PFX FV 0 lw'ataliga .
PFX FV 0 lw'atalika .
PFX FV 0 lw'atalibu .
PFX FV 0 lw'atalilu .
PFX FV 0 lw'ataliku .
PFX FV 0 lw'atalitu .
PFX FV 0 lw'etelin [^lmnb]
PFX FV l lw'etelind l.[^mn][^u]
PFX FV l lw'etelinn l.[mn]
PFX FV w lw'etelimp [w]
PFX FV 0 lw'etelimu .
PFX FV 0 lw'eteliba .
PFX FV 0 lw'eteligu .
PFX FV 0 lw'eteligi .
PFX FV 0 lw'etelizi .
PFX FV 0 lw'eteliki .
PFX FV 0 lw'etelibi .
PFX FV 0 lw'etelili .
PFX FV 0 lw'eteliga .
PFX FV 0 lw'etelika .
PFX FV 0 lw'etelibu .
PFX FV 0 lw'etelilu .
PFX FV 0 lw'eteliku .
PFX FV 0 lw'etelitu .
PFX FV 0 lwessiliba .
PFX FV 0 lwessiligu .
PFX FV 0 lwessiligi .
PFX FV 0 lwessilizi .
PFX FV 0 lwessiliki .
PFX FV 0 lwessilibi .
PFX FV 0 lwessilili .
PFX FV 0 lwessiliga .
PFX FV 0 lwessilika .
PFX FV 0 lwessilibu .
PFX FV 0 lwessililu .
PFX FV 0 lwessiliku .
PFX FV 0 lwessilitu .
PFX FV 0 lwessilimu .
PFX FV 0 lwetutalin [^lmnb]
PFX FV l lwetutalind l.[^mn][^u]
PFX FV l lwetutalinn l.[mn]
PFX FV w lwetutalimp [w]
PFX FV 0 lwetutalimu .
PFX FV 0 lwetutaliba .
PFX FV 0 lwetutaligu .
PFX FV 0 lwetutaligi .
PFX FV 0 lwetutalizi .
PFX FV 0 lwetutaliki .
PFX FV 0 lwetutalibi .
PFX FV 0 lwetutalili .
PFX FV 0 lwetutaliga .
PFX FV 0 lwetutalika .
PFX FV 0 lwetutalibu .
PFX FV 0 lwetutalilu .
PFX FV 0 lwetutaliku .
PFX FV 0 lwetutalitu .
PFX FV 0 lwemutalin [^lmnb]
PFX FV l lwemutalind l.[^mn][^u]
PFX FV l lwemutalinn l.[mn]
PFX FV w lwemutalimp [w]
PFX FV 0 lwemutalimu .
PFX FV 0 lwemutaliba .
PFX FV 0 lwemutaligu .
PFX FV 0 lwemutaligi .
PFX FV 0 lwemutalizi .
PFX FV 0 lwemutaliki .
PFX FV 0 lwemutalibi .
PFX FV 0 lwemutalili .
PFX FV 0 lwemutaliga .
PFX FV 0 lwemutalika .
PFX FV 0 lwemutalibu .
PFX FV 0 lwemutalilu .
PFX FV 0 lwemutaliku .
PFX FV 0 lwemutalitu .
PFX FV 0 lwebatalin [^lmnb]
PFX FV l lwebatalind l.[^mn][^u]
PFX FV l lwebatalinn l.[mn]
PFX FV w lwebatalimp [w]
PFX FV 0 lwebatalimu .
PFX FV 0 lwebataliba .
PFX FV 0 lwebataligu .
PFX FV 0 lwebataligi .
PFX FV 0 lwebatalizi .
PFX FV 0 lwebataliki .
PFX FV 0 lwebatalibi .
PFX FV 0 lwebatalili .
PFX FV 0 lwebataliga .
PFX FV 0 lwebatalika .
PFX FV 0 lwebatalibu .
PFX FV 0 lwebatalilu .
PFX FV 0 lwebataliku .
PFX FV 0 lwebatalitu .
PFX FV 0 lwegutalin [^lmnb]
PFX FV l lwegutalind l.[^mn][^u]
PFX FV l lwegutalinn l.[mn]
PFX FV w lwegutalimp [w]
PFX FV 0 lwegutalimu .
PFX FV 0 lwegutaliba .
PFX FV 0 lwegutaligu .
PFX FV 0 lwegutaligi .
PFX FV 0 lwegutalizi .
PFX FV 0 lwegutaliki .
PFX FV 0 lwegutalibi .
PFX FV 0 lwegutalili .
PFX FV 0 lwegutaliga .
PFX FV 0 lwegutalika .
PFX FV 0 lwegutalibu .
PFX FV 0 lwegutalilu .
PFX FV 0 lwegutaliku .
PFX FV 0 lwegutalitu .
PFX FV 0 lwegitalin [^lmnb]
PFX FV l lwegitalind l.[^mn][^u]
PFX FV l lwegitalinn l.[mn]
PFX FV w lwegitalimp [w]
PFX FV 0 lwegitalimu .
PFX FV 0 lwegitaliba .
PFX FV 0 lwegitaligu .
PFX FV 0 lwegitaligi .
PFX FV 0 lwegitalizi .
PFX FV 0 lwegitaliki .
PFX FV 0 lwegitalibi .
PFX FV 0 lwegitalili .
PFX FV 0 lwegitaliga .
PFX FV 0 lwegitalika .
PFX FV 0 lwegitalibu .
PFX FV 0 lwegitalilu .
PFX FV 0 lwegitaliku .
PFX FV 0 lwegitalitu .
PFX FV 0 lwezitalin [^lmnb]
PFX FV l lwezitalind l.[^mn][^u]
PFX FV l lwezitalinn l.[mn]
PFX FV w lwezitalimp [w]
PFX FV 0 lwezitalimu .
PFX FV 0 lwezitaliba .
PFX FV 0 lwezitaligu .
PFX FV 0 lwezitaligi .
PFX FV 0 lwezitalizi .
PFX FV 0 lwezitaliki .
PFX FV 0 lwezitalibi .
PFX FV 0 lwezitalili .
PFX FV 0 lwezitaliga .
PFX FV 0 lwezitalika .
PFX FV 0 lwezitalibu .
PFX FV 0 lwezitalilu .
PFX FV 0 lwezitaliku .
PFX FV 0 lwezitalitu .
PFX FV 0 lwekitalin [^lmnb]
PFX FV l lwekitalind l.[^mn][^u]
PFX FV l lwekitalinn l.[mn]
PFX FV w lwekitalimp [w]
PFX FV 0 lwekitalimu .
PFX FV 0 lwekitaliba .
PFX FV 0 lwekitaligu .
PFX FV 0 lwekitaligi .
PFX FV 0 lwekitalizi .
PFX FV 0 lwekitaliki .
PFX FV 0 lwekitalibi .
PFX FV 0 lwekitalili .
PFX FV 0 lwekitaliga .
PFX FV 0 lwekitalika .
PFX FV 0 lwekitalibu .
PFX FV 0 lwekitalilu .
PFX FV 0 lwekitaliku .
PFX FV 0 lwekitalitu .
PFX FV 0 lwebitalin [^lmnb]
PFX FV l lwebitalind l.[^mn][^u]
PFX FV l lwebitalinn l.[mn]
PFX FV w lwebitalimp [w]
PFX FV 0 lwebitalimu .
PFX FV 0 lwebitaliba .
PFX FV 0 lwebitaligu .
PFX FV 0 lwebitaligi .
PFX FV 0 lwebitalizi .
PFX FV 0 lwebitaliki .
PFX FV 0 lwebitalibi .
PFX FV 0 lwebitalili .
PFX FV 0 lwebitaliga .
PFX FV 0 lwebitalika .
PFX FV 0 lwebitalibu .
PFX FV 0 lwebitalilu .
PFX FV 0 lwebitaliku .
PFX FV 0 lwebitalitu .
PFX FV 0 lwelitalin [^lmnb]
PFX FV l lwelitalind l.[^mn][^u]
PFX FV l lwelitalinn l.[mn]
PFX FV w lwelitalimp [w]
PFX FV 0 lwelitalimu .
PFX FV 0 lwelitaliba .
PFX FV 0 lwelitaligu .
PFX FV 0 lwelitaligi .
PFX FV 0 lwelitalizi .
PFX FV 0 lwelitaliki .
PFX FV 0 lwelitalibi .
PFX FV 0 lwelitalili .
PFX FV 0 lwelitaliga .
PFX FV 0 lwelitalika .
PFX FV 0 lwelitalibu .
PFX FV 0 lwelitalilu .
PFX FV 0 lwelitaliku .
PFX FV 0 lwelitalitu .
PFX FV 0 lwegatalin [^lmnb]
PFX FV l lwegatalind l.[^mn][^u]
PFX FV l lwegatalinn l.[mn]
PFX FV w lwegatalimp [w]
PFX FV 0 lwegatalimu .
PFX FV 0 lwegataliba .
PFX FV 0 lwegataligu .
PFX FV 0 lwegataligi .
PFX FV 0 lwegatalizi .
PFX FV 0 lwegataliki .
PFX FV 0 lwegatalibi .
PFX FV 0 lwegatalili .
PFX FV 0 lwegataliga .
PFX FV 0 lwegatalika .
PFX FV 0 lwegatalibu .
PFX FV 0 lwegatalilu .
PFX FV 0 lwegataliku .
PFX FV 0 lwegatalitu .
PFX FV 0 lwekatalin [^lmnb]
PFX FV l lwekatalind l.[^mn][^u]
PFX FV l lwekatalinn l.[mn]
PFX FV w lwekatalimp [w]
PFX FV 0 lwekatalimu .
PFX FV 0 lwekataliba .
PFX FV 0 lwekataligu .
PFX FV 0 lwekataligi .
PFX FV 0 lwekatalizi .
PFX FV 0 lwekataliki .
PFX FV 0 lwekatalibi .
PFX FV 0 lwekatalili .
PFX FV 0 lwekataliga .
PFX FV 0 lwekatalika .
PFX FV 0 lwekatalibu .
PFX FV 0 lwekatalilu .
PFX FV 0 lwekataliku .
PFX FV 0 lwekatalitu .
PFX FV 0 lwebutalin [^lmnb]
PFX FV l lwebutalind l.[^mn][^u]
PFX FV l lwebutalinn l.[mn]
PFX FV w lwebutalimp [w]
PFX FV 0 lwebutalimu .
PFX FV 0 lwebutaliba .
PFX FV 0 lwebutaligu .
PFX FV 0 lwebutaligi .
PFX FV 0 lwebutalizi .
PFX FV 0 lwebutaliki .
PFX FV 0 lwebutalibi .
PFX FV 0 lwebutalili .
PFX FV 0 lwebutaliga .
PFX FV 0 lwebutalika .
PFX FV 0 lwebutalibu .
PFX FV 0 lwebutalilu .
PFX FV 0 lwebutaliku .
PFX FV 0 lwebutalitu .
PFX FV 0 lwelutalin [^lmnb]
PFX FV l lwelutalind l.[^mn][^u]
PFX FV l lwelutalinn l.[mn]
PFX FV w lwelutalimp [w]
PFX FV 0 lwelutalimu .
PFX FV 0 lwelutaliba .
PFX FV 0 lwelutaligu .
PFX FV 0 lwelutaligi .
PFX FV 0 lwelutalizi .
PFX FV 0 lwelutaliki .
PFX FV 0 lwelutalibi .
PFX FV 0 lwelutalili .
PFX FV 0 lwelutaliga .
PFX FV 0 lwelutalika .
PFX FV 0 lwelutalibu .
PFX FV 0 lwelutalilu .
PFX FV 0 lwelutaliku .
PFX FV 0 lwelutalitu .
PFX FV 0 lwekutalin [^lmnb]
PFX FV l lwekutalind l.[^mn][^u]
PFX FV l lwekutalinn l.[mn]
PFX FV w lwekutalimp [w]
PFX FV 0 lwekutalimu .
PFX FV 0 lwekutaliba .
PFX FV 0 lwekutaligu .
PFX FV 0 lwekutaligi .
PFX FV 0 lwekutalizi .
PFX FV 0 lwekutaliki .
PFX FV 0 lwekutalibi .
PFX FV 0 lwekutalili .
PFX FV 0 lwekutaliga .
PFX FV 0 lwekutalika .
PFX FV 0 lwekutalibu .
PFX FV 0 lwekutalilu .
PFX FV 0 lwekutaliku .
PFX FV 0 lwekutalitu .
PFX FV 0 lwetutalin [^lmnb]
PFX FV l lwetutalind l.[^mn][^u]
PFX FV l lwetutalinn l.[mn]
PFX FV w lwetutalimp [w]
PFX FV 0 lwetutalimu .
PFX FV 0 lwetutaliba .
PFX FV 0 lwetutaligu .
PFX FV 0 lwetutaligi .
PFX FV 0 lwetutalizi .
PFX FV 0 lwetutaliki .
PFX FV 0 lwetutalibi .
PFX FV 0 lwetutalili .
PFX FV 0 lwetutaliga .
PFX FV 0 lwetutalika .
PFX FV 0 lwetutalibu .
PFX FV 0 lwetutalilu .
PFX FV 0 lwetutaliku .
PFX FV 0 lwetutalitu .
PFX FV 0 z'otolin [^lmnb]
PFX FV l z'otolind l.[^mn][^u]
PFX FV l z'otolinn l.[mn]
PFX FV w z'otolimp [w]
PFX FV 0 z'otolimu .
PFX FV 0 z'otoliba .
PFX FV 0 z'otoligu .
PFX FV 0 z'otoligi .
PFX FV 0 z'otolizi .
PFX FV 0 z'otoliki .
PFX FV 0 z'otolibi .
PFX FV 0 z'otolili .
PFX FV 0 z'otoliga .
PFX FV 0 z'otolika .
PFX FV 0 z'otolibu .
PFX FV 0 z'otolilu .
PFX FV 0 z'otoliku .
PFX FV 0 z'otolitu .
PFX FV 0 z'atalin [^lmnb]
PFX FV l z'atalind l.[^mn][^u]
PFX FV l z'atalinn l.[mn]
PFX FV w z'atalimp [w]
PFX FV 0 z'atalimu .
PFX FV 0 z'ataliba .
PFX FV 0 z'ataligu .
PFX FV 0 z'ataligi .
PFX FV 0 z'atalizi .
PFX FV 0 z'ataliki .
PFX FV 0 z'atalibi .
PFX FV 0 z'atalili .
PFX FV 0 z'ataliga .
PFX FV 0 z'atalika .
PFX FV 0 z'atalibu .
PFX FV 0 z'atalilu .
PFX FV 0 z'ataliku .
PFX FV 0 z'atalitu .
PFX FV 0 z'etelin [^lmnb]
PFX FV l z'etelind l.[^mn][^u]
PFX FV l z'etelinn l.[mn]
PFX FV w z'etelimp [w]
PFX FV 0 z'etelimu .
PFX FV 0 z'eteliba .
PFX FV 0 z'eteligu .
PFX FV 0 z'eteligi .
PFX FV 0 z'etelizi .
PFX FV 0 z'eteliki .
PFX FV 0 z'etelibi .
PFX FV 0 z'etelili .
PFX FV 0 z'eteliga .
PFX FV 0 z'etelika .
PFX FV 0 z'etelibu .
PFX FV 0 z'etelilu .
PFX FV 0 z'eteliku .
PFX FV 0 z'etelitu .
PFX FV 0 zessiliba .
PFX FV 0 zessiligu .
PFX FV 0 zessiligi .
PFX FV 0 zessilizi .
PFX FV 0 zessiliki .
PFX FV 0 zessilibi .
PFX FV 0 zessilili .
PFX FV 0 zessiliga .
PFX FV 0 zessilika .
PFX FV 0 zessilibu .
PFX FV 0 zessililu .
PFX FV 0 zessiliku .
PFX FV 0 zessilitu .
PFX FV 0 zessilimu .
PFX FV 0 zetutalin [^lmnb]
PFX FV l zetutalind l.[^mn][^u]
PFX FV l zetutalinn l.[mn]
PFX FV w zetutalimp [w]
PFX FV 0 zetutalimu .
PFX FV 0 zetutaliba .
PFX FV 0 zetutaligu .
PFX FV 0 zetutaligi .
PFX FV 0 zetutalizi .
PFX FV 0 zetutaliki .
PFX FV 0 zetutalibi .
PFX FV 0 zetutalili .
PFX FV 0 zetutaliga .
PFX FV 0 zetutalika .
PFX FV 0 zetutalibu .
PFX FV 0 zetutalilu .
PFX FV 0 zetutaliku .
PFX FV 0 zetutalitu .
PFX FV 0 zemutalin [^lmnb]
PFX FV l zemutalind l.[^mn][^u]
PFX FV l zemutalinn l.[mn]
PFX FV w zemutalimp [w]
PFX FV 0 zemutalimu .
PFX FV 0 zemutaliba .
PFX FV 0 zemutaligu .
PFX FV 0 zemutaligi .
PFX FV 0 zemutalizi .
PFX FV 0 zemutaliki .
PFX FV 0 zemutalibi .
PFX FV 0 zemutalili .
PFX FV 0 zemutaliga .
PFX FV 0 zemutalika .
PFX FV 0 zemutalibu .
PFX FV 0 zemutalilu .
PFX FV 0 zemutaliku .
PFX FV 0 zemutalitu .
PFX FV 0 zebatalin [^lmnb]
PFX FV l zebatalind l.[^mn][^u]
PFX FV l zebatalinn l.[mn]
PFX FV w zebatalimp [w]
PFX FV 0 zebatalimu .
PFX FV 0 zebataliba .
PFX FV 0 zebataligu .
PFX FV 0 zebataligi .
PFX FV 0 zebatalizi .
PFX FV 0 zebataliki .
PFX FV 0 zebatalibi .
PFX FV 0 zebatalili .
PFX FV 0 zebataliga .
PFX FV 0 zebatalika .
PFX FV 0 zebatalibu .
PFX FV 0 zebatalilu .
PFX FV 0 zebataliku .
PFX FV 0 zebatalitu .
PFX FV 0 zegutalin [^lmnb]
PFX FV l zegutalind l.[^mn][^u]
PFX FV l zegutalinn l.[mn]
PFX FV w zegutalimp [w]
PFX FV 0 zegutalimu .
PFX FV 0 zegutaliba .
PFX FV 0 zegutaligu .
PFX FV 0 zegutaligi .
PFX FV 0 zegutalizi .
PFX FV 0 zegutaliki .
PFX FV 0 zegutalibi .
PFX FV 0 zegutalili .
PFX FV 0 zegutaliga .
PFX FV 0 zegutalika .
PFX FV 0 zegutalibu .
PFX FV 0 zegutalilu .
PFX FV 0 zegutaliku .
PFX FV 0 zegutalitu .
PFX FV 0 zegitalin [^lmnb]
PFX FV l zegitalind l.[^mn][^u]
PFX FV l zegitalinn l.[mn]
PFX FV w zegitalimp [w]
PFX FV 0 zegitalimu .
PFX FV 0 zegitaliba .
PFX FV 0 zegitaligu .
PFX FV 0 zegitaligi .
PFX FV 0 zegitalizi .
PFX FV 0 zegitaliki .
PFX FV 0 zegitalibi .
PFX FV 0 zegitalili .
PFX FV 0 zegitaliga .
PFX FV 0 zegitalika .
PFX FV 0 zegitalibu .
PFX FV 0 zegitalilu .
PFX FV 0 zegitaliku .
PFX FV 0 zegitalitu .
PFX FV 0 zezitalin [^lmnb]
PFX FV l zezitalind l.[^mn][^u]
PFX FV l zezitalinn l.[mn]
PFX FV w zezitalimp [w]
PFX FV 0 zezitalimu .
PFX FV 0 zezitaliba .
PFX FV 0 zezitaligu .
PFX FV 0 zezitaligi .
PFX FV 0 zezitalizi .
PFX FV 0 zezitaliki .
PFX FV 0 zezitalibi .
PFX FV 0 zezitalili .
PFX FV 0 zezitaliga .
PFX FV 0 zezitalika .
PFX FV 0 zezitalibu .
PFX FV 0 zezitalilu .
PFX FV 0 zezitaliku .
PFX FV 0 zezitalitu .
PFX FV 0 zekitalin [^lmnb]
PFX FV l zekitalind l.[^mn][^u]
PFX FV l zekitalinn l.[mn]
PFX FV w zekitalimp [w]
PFX FV 0 zekitalimu .
PFX FV 0 zekitaliba .
PFX FV 0 zekitaligu .
PFX FV 0 zekitaligi .
PFX FV 0 zekitalizi .
PFX FV 0 zekitaliki .
PFX FV 0 zekitalibi .
PFX FV 0 zekitalili .
PFX FV 0 zekitaliga .
PFX FV 0 zekitalika .
PFX FV 0 zekitalibu .
PFX FV 0 zekitalilu .
PFX FV 0 zekitaliku .
PFX FV 0 zekitalitu .
PFX FV 0 zebitalin [^lmnb]
PFX FV l zebitalind l.[^mn][^u]
PFX FV l zebitalinn l.[mn]
PFX FV w zebitalimp [w]
PFX FV 0 zebitalimu .
PFX FV 0 zebitaliba .
PFX FV 0 zebitaligu .
PFX FV 0 zebitaligi .
PFX FV 0 zebitalizi .
PFX FV 0 zebitaliki .
PFX FV 0 zebitalibi .
PFX FV 0 zebitalili .
PFX FV 0 zebitaliga .
PFX FV 0 zebitalika .
PFX FV 0 zebitalibu .
PFX FV 0 zebitalilu .
PFX FV 0 zebitaliku .
PFX FV 0 zebitalitu .
PFX FV 0 zelitalin [^lmnb]
PFX FV l zelitalind l.[^mn][^u]
PFX FV l zelitalinn l.[mn]
PFX FV w zelitalimp [w]
PFX FV 0 zelitalimu .
PFX FV 0 zelitaliba .
PFX FV 0 zelitaligu .
PFX FV 0 zelitaligi .
PFX FV 0 zelitalizi .
PFX FV 0 zelitaliki .
PFX FV 0 zelitalibi .
PFX FV 0 zelitalili .
PFX FV 0 zelitaliga .
PFX FV 0 zelitalika .
PFX FV 0 zelitalibu .
PFX FV 0 zelitalilu .
PFX FV 0 zelitaliku .
PFX FV 0 zelitalitu .
PFX FV 0 zegatalin [^lmnb]
PFX FV l zegatalind l.[^mn][^u]
PFX FV l zegatalinn l.[mn]
PFX FV w zegatalimp [w]
PFX FV 0 zegatalimu .
PFX FV 0 zegataliba .
PFX FV 0 zegataligu .
PFX FV 0 zegataligi .
PFX FV 0 zegatalizi .
PFX FV 0 zegataliki .
PFX FV 0 zegatalibi .
PFX FV 0 zegatalili .
PFX FV 0 zegataliga .
PFX FV 0 zegatalika .
PFX FV 0 zegatalibu .
PFX FV 0 zegatalilu .
PFX FV 0 zegataliku .
PFX FV 0 zegatalitu .
PFX FV 0 zekatalin [^lmnb]
PFX FV l zekatalind l.[^mn][^u]
PFX FV l zekatalinn l.[mn]
PFX FV w zekatalimp [w]
PFX FV 0 zekatalimu .
PFX FV 0 zekataliba .
PFX FV 0 zekataligu .
PFX FV 0 zekataligi .
PFX FV 0 zekatalizi .
PFX FV 0 zekataliki .
PFX FV 0 zekatalibi .
PFX FV 0 zekatalili .
PFX FV 0 zekataliga .
PFX FV 0 zekatalika .
PFX FV 0 zekatalibu .
PFX FV 0 zekatalilu .
PFX FV 0 zekataliku .
PFX FV 0 zekatalitu .
PFX FV 0 zebutalin [^lmnb]
PFX FV l zebutalind l.[^mn][^u]
PFX FV l zebutalinn l.[mn]
PFX FV w zebutalimp [w]
PFX FV 0 zebutalimu .
PFX FV 0 zebutaliba .
PFX FV 0 zebutaligu .
PFX FV 0 zebutaligi .
PFX FV 0 zebutalizi .
PFX FV 0 zebutaliki .
PFX FV 0 zebutalibi .
PFX FV 0 zebutalili .
PFX FV 0 zebutaliga .
PFX FV 0 zebutalika .
PFX FV 0 zebutalibu .
PFX FV 0 zebutalilu .
PFX FV 0 zebutaliku .
PFX FV 0 zebutalitu .
PFX FV 0 zelutalin [^lmnb]
PFX FV l zelutalind l.[^mn][^u]
PFX FV l zelutalinn l.[mn]
PFX FV w zelutalimp [w]
PFX FV 0 zelutalimu .
PFX FV 0 zelutaliba .
PFX FV 0 zelutaligu .
PFX FV 0 zelutaligi .
PFX FV 0 zelutalizi .
PFX FV 0 zelutaliki .
PFX FV 0 zelutalibi .
PFX FV 0 zelutalili .
PFX FV 0 zelutaliga .
PFX FV 0 zelutalika .
PFX FV 0 zelutalibu .
PFX FV 0 zelutalilu .
PFX FV 0 zelutaliku .
PFX FV 0 zelutalitu .
PFX FV 0 zekutalin [^lmnb]
PFX FV l zekutalind l.[^mn][^u]
PFX FV l zekutalinn l.[mn]
PFX FV w zekutalimp [w]
PFX FV 0 zekutalimu .
PFX FV 0 zekutaliba .
PFX FV 0 zekutaligu .
PFX FV 0 zekutaligi .
PFX FV 0 zekutalizi .
PFX FV 0 zekutaliki .
PFX FV 0 zekutalibi .
PFX FV 0 zekutalili .
PFX FV 0 zekutaliga .
PFX FV 0 zekutalika .
PFX FV 0 zekutalibu .
PFX FV 0 zekutalilu .
PFX FV 0 zekutaliku .
PFX FV 0 zekutalitu .
PFX FV 0 zetutalin [^lmnb]
PFX FV l zetutalind l.[^mn][^u]
PFX FV l zetutalinn l.[mn]
PFX FV w zetutalimp [w]
PFX FV 0 zetutalimu .
PFX FV 0 zetutaliba .
PFX FV 0 zetutaligu .
PFX FV 0 zetutaligi .
PFX FV 0 zetutalizi .
PFX FV 0 zetutaliki .
PFX FV 0 zetutalibi .
PFX FV 0 zetutalili .
PFX FV 0 zetutaliga .
PFX FV 0 zetutalika .
PFX FV 0 zetutalibu .
PFX FV 0 zetutalilu .
PFX FV 0 zetutaliku .
PFX FV 0 zetutalitu .
PFX FV 0 gw'otolin [^lmnb]
PFX FV l gw'otolind l.[^mn][^u]
PFX FV l gw'otolinn l.[mn]
PFX FV w gw'otolimp [w]
PFX FV 0 gw'otolimu .
PFX FV 0 gw'otoliba .
PFX FV 0 gw'otoligu .
PFX FV 0 gw'otoligi .
PFX FV 0 gw'otolizi .
PFX FV 0 gw'otoliki .
PFX FV 0 gw'otolibi .
PFX FV 0 gw'otolili .
PFX FV 0 gw'otoliga .
PFX FV 0 gw'otolika .
PFX FV 0 gw'otolibu .
PFX FV 0 gw'otolilu .
PFX FV 0 gw'otoliku .
PFX FV 0 gw'otolitu .
PFX FV 0 gw'atalin [^lmnb]
PFX FV l gw'atalind l.[^mn][^u]
PFX FV l gw'atalinn l.[mn]
PFX FV w gw'atalimp [w]
PFX FV 0 gw'atalimu .
PFX FV 0 gw'ataliba .
PFX FV 0 gw'ataligu .
PFX FV 0 gw'ataligi .
PFX FV 0 gw'atalizi .
PFX FV 0 gw'ataliki .
PFX FV 0 gw'atalibi .
PFX FV 0 gw'atalili .
PFX FV 0 gw'ataliga .
PFX FV 0 gw'atalika .
PFX FV 0 gw'atalibu .
PFX FV 0 gw'atalilu .
PFX FV 0 gw'ataliku .
PFX FV 0 gw'atalitu .
PFX FV 0 gw'etelin [^lmnb]
PFX FV l gw'etelind l.[^mn][^u]
PFX FV l gw'etelinn l.[mn]
PFX FV w gw'etelimp [w]
PFX FV 0 gw'etelimu .
PFX FV 0 gw'eteliba .
PFX FV 0 gw'eteligu .
PFX FV 0 gw'eteligi .
PFX FV 0 gw'etelizi .
PFX FV 0 gw'eteliki .
PFX FV 0 gw'etelibi .
PFX FV 0 gw'etelili .
PFX FV 0 gw'eteliga .
PFX FV 0 gw'etelika .
PFX FV 0 gw'etelibu .
PFX FV 0 gw'etelilu .
PFX FV 0 gw'eteliku .
PFX FV 0 gw'etelitu .
PFX FV 0 gwessiliba .
PFX FV 0 gwessiligu .
PFX FV 0 gwessiligi .
PFX FV 0 gwessilizi .
PFX FV 0 gwessiliki .
PFX FV 0 gwessilibi .
PFX FV 0 gwessilili .
PFX FV 0 gwessiliga .
PFX FV 0 gwessilika .
PFX FV 0 gwessilibu .
PFX FV 0 gwessililu .
PFX FV 0 gwessiliku .
PFX FV 0 gwessilitu .
PFX FV 0 gwessilimu .
PFX FV 0 gwetutalin [^lmnb]
PFX FV l gwetutalind l.[^mn][^u]
PFX FV l gwetutalinn l.[mn]
PFX FV w gwetutalimp [w]
PFX FV 0 gwetutalimu .
PFX FV 0 gwetutaliba .
PFX FV 0 gwetutaligu .
PFX FV 0 gwetutaligi .
PFX FV 0 gwetutalizi .
PFX FV 0 gwetutaliki .
PFX FV 0 gwetutalibi .
PFX FV 0 gwetutalili .
PFX FV 0 gwetutaliga .
PFX FV 0 gwetutalika .
PFX FV 0 gwetutalibu .
PFX FV 0 gwetutalilu .
PFX FV 0 gwetutaliku .
PFX FV 0 gwetutalitu .
PFX FV 0 gwemutalin [^lmnb]
PFX FV l gwemutalind l.[^mn][^u]
PFX FV l gwemutalinn l.[mn]
PFX FV w gwemutalimp [w]
PFX FV 0 gwemutalimu .
PFX FV 0 gwemutaliba .
PFX FV 0 gwemutaligu .
PFX FV 0 gwemutaligi .
PFX FV 0 gwemutalizi .
PFX FV 0 gwemutaliki .
PFX FV 0 gwemutalibi .
PFX FV 0 gwemutalili .
PFX FV 0 gwemutaliga .
PFX FV 0 gwemutalika .
PFX FV 0 gwemutalibu .
PFX FV 0 gwemutalilu .
PFX FV 0 gwemutaliku .
PFX FV 0 gwemutalitu .
PFX FV 0 gwebatalin [^lmnb]
PFX FV l gwebatalind l.[^mn][^u]
PFX FV l gwebatalinn l.[mn]
PFX FV w gwebatalimp [w]
PFX FV 0 gwebatalimu .
PFX FV 0 gwebataliba .
PFX FV 0 gwebataligu .
PFX FV 0 gwebataligi .
PFX FV 0 gwebatalizi .
PFX FV 0 gwebataliki .
PFX FV 0 gwebatalibi .
PFX FV 0 gwebatalili .
PFX FV 0 gwebataliga .
PFX FV 0 gwebatalika .
PFX FV 0 gwebatalibu .
PFX FV 0 gwebatalilu .
PFX FV 0 gwebataliku .
PFX FV 0 gwebatalitu .
PFX FV 0 gwegutalin [^lmnb]
PFX FV l gwegutalind l.[^mn][^u]
PFX FV l gwegutalinn l.[mn]
PFX FV w gwegutalimp [w]
PFX FV 0 gwegutalimu .
PFX FV 0 gwegutaliba .
PFX FV 0 gwegutaligu .
PFX FV 0 gwegutaligi .
PFX FV 0 gwegutalizi .
PFX FV 0 gwegutaliki .
PFX FV 0 gwegutalibi .
PFX FV 0 gwegutalili .
PFX FV 0 gwegutaliga .
PFX FV 0 gwegutalika .
PFX FV 0 gwegutalibu .
PFX FV 0 gwegutalilu .
PFX FV 0 gwegutaliku .
PFX FV 0 gwegutalitu .
PFX FV 0 gwegitalin [^lmnb]
PFX FV l gwegitalind l.[^mn][^u]
PFX FV l gwegitalinn l.[mn]
PFX FV w gwegitalimp [w]
PFX FV 0 gwegitalimu .
PFX FV 0 gwegitaliba .
PFX FV 0 gwegitaligu .
PFX FV 0 gwegitaligi .
PFX FV 0 gwegitalizi .
PFX FV 0 gwegitaliki .
PFX FV 0 gwegitalibi .
PFX FV 0 gwegitalili .
PFX FV 0 gwegitaliga .
PFX FV 0 gwegitalika .
PFX FV 0 gwegitalibu .
PFX FV 0 gwegitalilu .
PFX FV 0 gwegitaliku .
PFX FV 0 gwegitalitu .
PFX FV 0 gwezitalin [^lmnb]
PFX FV l gwezitalind l.[^mn][^u]
PFX FV l gwezitalinn l.[mn]
PFX FV w gwezitalimp [w]
PFX FV 0 gwezitalimu .
PFX FV 0 gwezitaliba .
PFX FV 0 gwezitaligu .
PFX FV 0 gwezitaligi .
PFX FV 0 gwezitalizi .
PFX FV 0 gwezitaliki .
PFX FV 0 gwezitalibi .
PFX FV 0 gwezitalili .
PFX FV 0 gwezitaliga .
PFX FV 0 gwezitalika .
PFX FV 0 gwezitalibu .
PFX FV 0 gwezitalilu .
PFX FV 0 gwezitaliku .
PFX FV 0 gwezitalitu .
PFX FV 0 gwekitalin [^lmnb]
PFX FV l gwekitalind l.[^mn][^u]
PFX FV l gwekitalinn l.[mn]
PFX FV w gwekitalimp [w]
PFX FV 0 gwekitalimu .
PFX FV 0 gwekitaliba .
PFX FV 0 gwekitaligu .
PFX FV 0 gwekitaligi .
PFX FV 0 gwekitalizi .
PFX FV 0 gwekitaliki .
PFX FV 0 gwekitalibi .
PFX FV 0 gwekitalili .
PFX FV 0 gwekitaliga .
PFX FV 0 gwekitalika .
PFX FV 0 gwekitalibu .
PFX FV 0 gwekitalilu .
PFX FV 0 gwekitaliku .
PFX FV 0 gwekitalitu .
PFX FV 0 gwebitalin [^lmnb]
PFX FV l gwebitalind l.[^mn][^u]
PFX FV l gwebitalinn l.[mn]
PFX FV w gwebitalimp [w]
PFX FV 0 gwebitalimu .
PFX FV 0 gwebitaliba .
PFX FV 0 gwebitaligu .
PFX FV 0 gwebitaligi .
PFX FV 0 gwebitalizi .
PFX FV 0 gwebitaliki .
PFX FV 0 gwebitalibi .
PFX FV 0 gwebitalili .
PFX FV 0 gwebitaliga .
PFX FV 0 gwebitalika .
PFX FV 0 gwebitalibu .
PFX FV 0 gwebitalilu .
PFX FV 0 gwebitaliku .
PFX FV 0 gwebitalitu .
PFX FV 0 gwelitalin [^lmnb]
PFX FV l gwelitalind l.[^mn][^u]
PFX FV l gwelitalinn l.[mn]
PFX FV w gwelitalimp [w]
PFX FV 0 gwelitalimu .
PFX FV 0 gwelitaliba .
PFX FV 0 gwelitaligu .
PFX FV 0 gwelitaligi .
PFX FV 0 gwelitalizi .
PFX FV 0 gwelitaliki .
PFX FV 0 gwelitalibi .
PFX FV 0 gwelitalili .
PFX FV 0 gwelitaliga .
PFX FV 0 gwelitalika .
PFX FV 0 gwelitalibu .
PFX FV 0 gwelitalilu .
PFX FV 0 gwelitaliku .
PFX FV 0 gwelitalitu .
PFX FV 0 gwegatalin [^lmnb]
PFX FV l gwegatalind l.[^mn][^u]
PFX FV l gwegatalinn l.[mn]
PFX FV w gwegatalimp [w]
PFX FV 0 gwegatalimu .
PFX FV 0 gwegataliba .
PFX FV 0 gwegataligu .
PFX FV 0 gwegataligi .
PFX FV 0 gwegatalizi .
PFX FV 0 gwegataliki .
PFX FV 0 gwegatalibi .
PFX FV 0 gwegatalili .
PFX FV 0 gwegataliga .
PFX FV 0 gwegatalika .
PFX FV 0 gwegatalibu .
PFX FV 0 gwegatalilu .
PFX FV 0 gwegataliku .
PFX FV 0 gwegatalitu .
PFX FV 0 gwekatalin [^lmnb]
PFX FV l gwekatalind l.[^mn][^u]
PFX FV l gwekatalinn l.[mn]
PFX FV w gwekatalimp [w]
PFX FV 0 gwekatalimu .
PFX FV 0 gwekataliba .
PFX FV 0 gwekataligu .
PFX FV 0 gwekataligi .
PFX FV 0 gwekatalizi .
PFX FV 0 gwekataliki .
PFX FV 0 gwekatalibi .
PFX FV 0 gwekatalili .
PFX FV 0 gwekataliga .
PFX FV 0 gwekatalika .
PFX FV 0 gwekatalibu .
PFX FV 0 gwekatalilu .
PFX FV 0 gwekataliku .
PFX FV 0 gwekatalitu .
PFX FV 0 gwebutalin [^lmnb]
PFX FV l gwebutalind l.[^mn][^u]
PFX FV l gwebutalinn l.[mn]
PFX FV w gwebutalimp [w]
PFX FV 0 gwebutalimu .
PFX FV 0 gwebutaliba .
PFX FV 0 gwebutaligu .
PFX FV 0 gwebutaligi .
PFX FV 0 gwebutalizi .
PFX FV 0 gwebutaliki .
PFX FV 0 gwebutalibi .
PFX FV 0 gwebutalili .
PFX FV 0 gwebutaliga .
PFX FV 0 gwebutalika .
PFX FV 0 gwebutalibu .
PFX FV 0 gwebutalilu .
PFX FV 0 gwebutaliku .
PFX FV 0 gwebutalitu .
PFX FV 0 gwelutalin [^lmnb]
PFX FV l gwelutalind l.[^mn][^u]
PFX FV l gwelutalinn l.[mn]
PFX FV w gwelutalimp [w]
PFX FV 0 gwelutalimu .
PFX FV 0 gwelutaliba .
PFX FV 0 gwelutaligu .
PFX FV 0 gwelutaligi .
PFX FV 0 gwelutalizi .
PFX FV 0 gwelutaliki .
PFX FV 0 gwelutalibi .
PFX FV 0 gwelutalili .
PFX FV 0 gwelutaliga .
PFX FV 0 gwelutalika .
PFX FV 0 gwelutalibu .
PFX FV 0 gwelutalilu .
PFX FV 0 gwelutaliku .
PFX FV 0 gwelutalitu .
PFX FV 0 gwekutalin [^lmnb]
PFX FV l gwekutalind l.[^mn][^u]
PFX FV l gwekutalinn l.[mn]
PFX FV w gwekutalimp [w]
PFX FV 0 gwekutalimu .
PFX FV 0 gwekutaliba .
PFX FV 0 gwekutaligu .
PFX FV 0 gwekutaligi .
PFX FV 0 gwekutalizi .
PFX FV 0 gwekutaliki .
PFX FV 0 gwekutalibi .
PFX FV 0 gwekutalili .
PFX FV 0 gwekutaliga .
PFX FV 0 gwekutalika .
PFX FV 0 gwekutalibu .
PFX FV 0 gwekutalilu .
PFX FV 0 gwekutaliku .
PFX FV 0 gwekutalitu .
PFX FV 0 gwetutalin [^lmnb]
PFX FV l gwetutalind l.[^mn][^u]
PFX FV l gwetutalinn l.[mn]
PFX FV w gwetutalimp [w]
PFX FV 0 gwetutalimu .
PFX FV 0 gwetutaliba .
PFX FV 0 gwetutaligu .
PFX FV 0 gwetutaligi .
PFX FV 0 gwetutalizi .
PFX FV 0 gwetutaliki .
PFX FV 0 gwetutalibi .
PFX FV 0 gwetutalili .
PFX FV 0 gwetutaliga .
PFX FV 0 gwetutalika .
PFX FV 0 gwetutalibu .
PFX FV 0 gwetutalilu .
PFX FV 0 gwetutaliku .
PFX FV 0 gwetutalitu .
PFX FV 0 gy'otolin [^lmnb]
PFX FV l gy'otolind l.[^mn][^u]
PFX FV l gy'otolinn l.[mn]
PFX FV w gy'otolimp [w]
PFX FV 0 gy'otolimu .
PFX FV 0 gy'otoliba .
PFX FV 0 gy'otoligu .
PFX FV 0 gy'otoligi .
PFX FV 0 gy'otolizi .
PFX FV 0 gy'otoliki .
PFX FV 0 gy'otolibi .
PFX FV 0 gy'otolili .
PFX FV 0 gy'otoliga .
PFX FV 0 gy'otolika .
PFX FV 0 gy'otolibu .
PFX FV 0 gy'otolilu .
PFX FV 0 gy'otoliku .
PFX FV 0 gy'otolitu .
PFX FV 0 gy'atalin [^lmnb]
PFX FV l gy'atalind l.[^mn][^u]
PFX FV l gy'atalinn l.[mn]
PFX FV w gy'atalimp [w]
PFX FV 0 gy'atalimu .
PFX FV 0 gy'ataliba .
PFX FV 0 gy'ataligu .
PFX FV 0 gy'ataligi .
PFX FV 0 gy'atalizi .
PFX FV 0 gy'ataliki .
PFX FV 0 gy'atalibi .
PFX FV 0 gy'atalili .
PFX FV 0 gy'ataliga .
PFX FV 0 gy'atalika .
PFX FV 0 gy'atalibu .
PFX FV 0 gy'atalilu .
PFX FV 0 gy'ataliku .
PFX FV 0 gy'atalitu .
PFX FV 0 gy'etelin [^lmnb]
PFX FV l gy'etelind l.[^mn][^u]
PFX FV l gy'etelinn l.[mn]
PFX FV w gy'etelimp [w]
PFX FV 0 gy'etelimu .
PFX FV 0 gy'eteliba .
PFX FV 0 gy'eteligu .
PFX FV 0 gy'eteligi .
PFX FV 0 gy'etelizi .
PFX FV 0 gy'eteliki .
PFX FV 0 gy'etelibi .
PFX FV 0 gy'etelili .
PFX FV 0 gy'eteliga .
PFX FV 0 gy'etelika .
PFX FV 0 gy'etelibu .
PFX FV 0 gy'etelilu .
PFX FV 0 gy'eteliku .
PFX FV 0 gy'etelitu .
PFX FV 0 gyessiliba .
PFX FV 0 gyessiligu .
PFX FV 0 gyessiligi .
PFX FV 0 gyessilizi .
PFX FV 0 gyessiliki .
PFX FV 0 gyessilibi .
PFX FV 0 gyessilili .
PFX FV 0 gyessiliga .
PFX FV 0 gyessilika .
PFX FV 0 gyessilibu .
PFX FV 0 gyessililu .
PFX FV 0 gyessiliku .
PFX FV 0 gyessilitu .
PFX FV 0 gyessilimu .
PFX FV 0 gyetutalin [^lmnb]
PFX FV l gyetutalind l.[^mn][^u]
PFX FV l gyetutalinn l.[mn]
PFX FV w gyetutalimp [w]
PFX FV 0 gyetutalimu .
PFX FV 0 gyetutaliba .
PFX FV 0 gyetutaligu .
PFX FV 0 gyetutaligi .
PFX FV 0 gyetutalizi .
PFX FV 0 gyetutaliki .
PFX FV 0 gyetutalibi .
PFX FV 0 gyetutalili .
PFX FV 0 gyetutaliga .
PFX FV 0 gyetutalika .
PFX FV 0 gyetutalibu .
PFX FV 0 gyetutalilu .
PFX FV 0 gyetutaliku .
PFX FV 0 gyetutalitu .
PFX FV 0 gyemutalin [^lmnb]
PFX FV l gyemutalind l.[^mn][^u]
PFX FV l gyemutalinn l.[mn]
PFX FV w gyemutalimp [w]
PFX FV 0 gyemutalimu .
PFX FV 0 gyemutaliba .
PFX FV 0 gyemutaligu .
PFX FV 0 gyemutaligi .
PFX FV 0 gyemutalizi .
PFX FV 0 gyemutaliki .
PFX FV 0 gyemutalibi .
PFX FV 0 gyemutalili .
PFX FV 0 gyemutaliga .
PFX FV 0 gyemutalika .
PFX FV 0 gyemutalibu .
PFX FV 0 gyemutalilu .
PFX FV 0 gyemutaliku .
PFX FV 0 gyemutalitu .
PFX FV 0 gyebatalin [^lmnb]
PFX FV l gyebatalind l.[^mn][^u]
PFX FV l gyebatalinn l.[mn]
PFX FV w gyebatalimp [w]
PFX FV 0 gyebatalimu .
PFX FV 0 gyebataliba .
PFX FV 0 gyebataligu .
PFX FV 0 gyebataligi .
PFX FV 0 gyebatalizi .
PFX FV 0 gyebataliki .
PFX FV 0 gyebatalibi .
PFX FV 0 gyebatalili .
PFX FV 0 gyebataliga .
PFX FV 0 gyebatalika .
PFX FV 0 gyebatalibu .
PFX FV 0 gyebatalilu .
PFX FV 0 gyebataliku .
PFX FV 0 gyebatalitu .
PFX FV 0 gyegutalin [^lmnb]
PFX FV l gyegutalind l.[^mn][^u]
PFX FV l gyegutalinn l.[mn]
PFX FV w gyegutalimp [w]
PFX FV 0 gyegutalimu .
PFX FV 0 gyegutaliba .
PFX FV 0 gyegutaligu .
PFX FV 0 gyegutaligi .
PFX FV 0 gyegutalizi .
PFX FV 0 gyegutaliki .
PFX FV 0 gyegutalibi .
PFX FV 0 gyegutalili .
PFX FV 0 gyegutaliga .
PFX FV 0 gyegutalika .
PFX FV 0 gyegutalibu .
PFX FV 0 gyegutalilu .
PFX FV 0 gyegutaliku .
PFX FV 0 gyegutalitu .
PFX FV 0 gyegitalin [^lmnb]
PFX FV l gyegitalind l.[^mn][^u]
PFX FV l gyegitalinn l.[mn]
PFX FV w gyegitalimp [w]
PFX FV 0 gyegitalimu .
PFX FV 0 gyegitaliba .
PFX FV 0 gyegitaligu .
PFX FV 0 gyegitaligi .
PFX FV 0 gyegitalizi .
PFX FV 0 gyegitaliki .
PFX FV 0 gyegitalibi .
PFX FV 0 gyegitalili .
PFX FV 0 gyegitaliga .
PFX FV 0 gyegitalika .
PFX FV 0 gyegitalibu .
PFX FV 0 gyegitalilu .
PFX FV 0 gyegitaliku .
PFX FV 0 gyegitalitu .
PFX FV 0 gyezitalin [^lmnb]
PFX FV l gyezitalind l.[^mn][^u]
PFX FV l gyezitalinn l.[mn]
PFX FV w gyezitalimp [w]
PFX FV 0 gyezitalimu .
PFX FV 0 gyezitaliba .
PFX FV 0 gyezitaligu .
PFX FV 0 gyezitaligi .
PFX FV 0 gyezitalizi .
PFX FV 0 gyezitaliki .
PFX FV 0 gyezitalibi .
PFX FV 0 gyezitalili .
PFX FV 0 gyezitaliga .
PFX FV 0 gyezitalika .
PFX FV 0 gyezitalibu .
PFX FV 0 gyezitalilu .
PFX FV 0 gyezitaliku .
PFX FV 0 gyezitalitu .
PFX FV 0 gyekitalin [^lmnb]
PFX FV l gyekitalind l.[^mn][^u]
PFX FV l gyekitalinn l.[mn]
PFX FV w gyekitalimp [w]
PFX FV 0 gyekitalimu .
PFX FV 0 gyekitaliba .
PFX FV 0 gyekitaligu .
PFX FV 0 gyekitaligi .
PFX FV 0 gyekitalizi .
PFX FV 0 gyekitaliki .
PFX FV 0 gyekitalibi .
PFX FV 0 gyekitalili .
PFX FV 0 gyekitaliga .
PFX FV 0 gyekitalika .
PFX FV 0 gyekitalibu .
PFX FV 0 gyekitalilu .
PFX FV 0 gyekitaliku .
PFX FV 0 gyekitalitu .
PFX FV 0 gyebitalin [^lmnb]
PFX FV l gyebitalind l.[^mn][^u]
PFX FV l gyebitalinn l.[mn]
PFX FV w gyebitalimp [w]
PFX FV 0 gyebitalimu .
PFX FV 0 gyebitaliba .
PFX FV 0 gyebitaligu .
PFX FV 0 gyebitaligi .
PFX FV 0 gyebitalizi .
PFX FV 0 gyebitaliki .
PFX FV 0 gyebitalibi .
PFX FV 0 gyebitalili .
PFX FV 0 gyebitaliga .
PFX FV 0 gyebitalika .
PFX FV 0 gyebitalibu .
PFX FV 0 gyebitalilu .
PFX FV 0 gyebitaliku .
PFX FV 0 gyebitalitu .
PFX FV 0 gyelitalin [^lmnb]
PFX FV l gyelitalind l.[^mn][^u]
PFX FV l gyelitalinn l.[mn]
PFX FV w gyelitalimp [w]
PFX FV 0 gyelitalimu .
PFX FV 0 gyelitaliba .
PFX FV 0 gyelitaligu .
PFX FV 0 gyelitaligi .
PFX FV 0 gyelitalizi .
PFX FV 0 gyelitaliki .
PFX FV 0 gyelitalibi .
PFX FV 0 gyelitalili .
PFX FV 0 gyelitaliga .
PFX FV 0 gyelitalika .
PFX FV 0 gyelitalibu .
PFX FV 0 gyelitalilu .
PFX FV 0 gyelitaliku .
PFX FV 0 gyelitalitu .
PFX FV 0 gyegatalin [^lmnb]
PFX FV l gyegatalind l.[^mn][^u]
PFX FV l gyegatalinn l.[mn]
PFX FV w gyegatalimp [w]
PFX FV 0 gyegatalimu .
PFX FV 0 gyegataliba .
PFX FV 0 gyegataligu .
PFX FV 0 gyegataligi .
PFX FV 0 gyegatalizi .
PFX FV 0 gyegataliki .
PFX FV 0 gyegatalibi .
PFX FV 0 gyegatalili .
PFX FV 0 gyegataliga .
PFX FV 0 gyegatalika .
PFX FV 0 gyegatalibu .
PFX FV 0 gyegatalilu .
PFX FV 0 gyegataliku .
PFX FV 0 gyegatalitu .
PFX FV 0 gyekatalin [^lmnb]
PFX FV l gyekatalind l.[^mn][^u]
PFX FV l gyekatalinn l.[mn]
PFX FV w gyekatalimp [w]
PFX FV 0 gyekatalimu .
PFX FV 0 gyekataliba .
PFX FV 0 gyekataligu .
PFX FV 0 gyekataligi .
PFX FV 0 gyekatalizi .
PFX FV 0 gyekataliki .
PFX FV 0 gyekatalibi .
PFX FV 0 gyekatalili .
PFX FV 0 gyekataliga .
PFX FV 0 gyekatalika .
PFX FV 0 gyekatalibu .
PFX FV 0 gyekatalilu .
PFX FV 0 gyekataliku .
PFX FV 0 gyekatalitu .
PFX FV 0 gyebutalin [^lmnb]
PFX FV l gyebutalind l.[^mn][^u]
PFX FV l gyebutalinn l.[mn]
PFX FV w gyebutalimp [w]
PFX FV 0 gyebutalimu .
PFX FV 0 gyebutaliba .
PFX FV 0 gyebutaligu .
PFX FV 0 gyebutaligi .
PFX FV 0 gyebutalizi .
PFX FV 0 gyebutaliki .
PFX FV 0 gyebutalibi .
PFX FV 0 gyebutalili .
PFX FV 0 gyebutaliga .
PFX FV 0 gyebutalika .
PFX FV 0 gyebutalibu .
PFX FV 0 gyebutalilu .
PFX FV 0 gyebutaliku .
PFX FV 0 gyebutalitu .
PFX FV 0 gyelutalin [^lmnb]
PFX FV l gyelutalind l.[^mn][^u]
PFX FV l gyelutalinn l.[mn]
PFX FV w gyelutalimp [w]
PFX FV 0 gyelutalimu .
PFX FV 0 gyelutaliba .
PFX FV 0 gyelutaligu .
PFX FV 0 gyelutaligi .
PFX FV 0 gyelutalizi .
PFX FV 0 gyelutaliki .
PFX FV 0 gyelutalibi .
PFX FV 0 gyelutalili .
PFX FV 0 gyelutaliga .
PFX FV 0 gyelutalika .
PFX FV 0 gyelutalibu .
PFX FV 0 gyelutalilu .
PFX FV 0 gyelutaliku .
PFX FV 0 gyelutalitu .
PFX FV 0 gyekutalin [^lmnb]
PFX FV l gyekutalind l.[^mn][^u]
PFX FV l gyekutalinn l.[mn]
PFX FV w gyekutalimp [w]
PFX FV 0 gyekutalimu .
PFX FV 0 gyekutaliba .
PFX FV 0 gyekutaligu .
PFX FV 0 gyekutaligi .
PFX FV 0 gyekutalizi .
PFX FV 0 gyekutaliki .
PFX FV 0 gyekutalibi .
PFX FV 0 gyekutalili .
PFX FV 0 gyekutaliga .
PFX FV 0 gyekutalika .
PFX FV 0 gyekutalibu .
PFX FV 0 gyekutalilu .
PFX FV 0 gyekutaliku .
PFX FV 0 gyekutalitu .
PFX FV 0 gyetutalin [^lmnb]
PFX FV l gyetutalind l.[^mn][^u]
PFX FV l gyetutalinn l.[mn]
PFX FV w gyetutalimp [w]
PFX FV 0 gyetutalimu .
PFX FV 0 gyetutaliba .
PFX FV 0 gyetutaligu .
PFX FV 0 gyetutaligi .
PFX FV 0 gyetutalizi .
PFX FV 0 gyetutaliki .
PFX FV 0 gyetutalibi .
PFX FV 0 gyetutalili .
PFX FV 0 gyetutaliga .
PFX FV 0 gyetutalika .
PFX FV 0 gyetutalibu .
PFX FV 0 gyetutalilu .
PFX FV 0 gyetutaliku .
PFX FV 0 gyetutalitu .
PFX FV 0 ky'otolin [^lmnb]
PFX FV l ky'otolind l.[^mn][^u]
PFX FV l ky'otolinn l.[mn]
PFX FV w ky'otolimp [w]
PFX FV 0 ky'otolimu .
PFX FV 0 ky'otoliba .
PFX FV 0 ky'otoligu .
PFX FV 0 ky'otoligi .
PFX FV 0 ky'otolizi .
PFX FV 0 ky'otoliki .
PFX FV 0 ky'otolibi .
PFX FV 0 ky'otolili .
PFX FV 0 ky'otoliga .
PFX FV 0 ky'otolika .
PFX FV 0 ky'otolibu .
PFX FV 0 ky'otolilu .
PFX FV 0 ky'otoliku .
PFX FV 0 ky'otolitu .
PFX FV 0 ky'atalin [^lmnb]
PFX FV l ky'atalind l.[^mn][^u]
PFX FV l ky'atalinn l.[mn]
PFX FV w ky'atalimp [w]
PFX FV 0 ky'atalimu .
PFX FV 0 ky'ataliba .
PFX FV 0 ky'ataligu .
PFX FV 0 ky'ataligi .
PFX FV 0 ky'atalizi .
PFX FV 0 ky'ataliki .
PFX FV 0 ky'atalibi .
PFX FV 0 ky'atalili .
PFX FV 0 ky'ataliga .
PFX FV 0 ky'atalika .
PFX FV 0 ky'atalibu .
PFX FV 0 ky'atalilu .
PFX FV 0 ky'ataliku .
PFX FV 0 ky'atalitu .
PFX FV 0 ky'etelin [^lmnb]
PFX FV l ky'etelind l.[^mn][^u]
PFX FV l ky'etelinn l.[mn]
PFX FV w ky'etelimp [w]
PFX FV 0 ky'etelimu .
PFX FV 0 ky'eteliba .
PFX FV 0 ky'eteligu .
PFX FV 0 ky'eteligi .
PFX FV 0 ky'etelizi .
PFX FV 0 ky'eteliki .
PFX FV 0 ky'etelibi .
PFX FV 0 ky'etelili .
PFX FV 0 ky'eteliga .
PFX FV 0 ky'etelika .
PFX FV 0 ky'etelibu .
PFX FV 0 ky'etelilu .
PFX FV 0 ky'eteliku .
PFX FV 0 ky'etelitu .
PFX FV 0 kyessiliba .
PFX FV 0 kyessiligu .
PFX FV 0 kyessiligi .
PFX FV 0 kyessilizi .
PFX FV 0 kyessiliki .
PFX FV 0 kyessilibi .
PFX FV 0 kyessilili .
PFX FV 0 kyessiliga .
PFX FV 0 kyessilika .
PFX FV 0 kyessilibu .
PFX FV 0 kyessililu .
PFX FV 0 kyessiliku .
PFX FV 0 kyessilitu .
PFX FV 0 kyessilimu .
PFX FV 0 kyetutalin [^lmnb]
PFX FV l kyetutalind l.[^mn][^u]
PFX FV l kyetutalinn l.[mn]
PFX FV w kyetutalimp [w]
PFX FV 0 kyetutalimu .
PFX FV 0 kyetutaliba .
PFX FV 0 kyetutaligu .
PFX FV 0 kyetutaligi .
PFX FV 0 kyetutalizi .
PFX FV 0 kyetutaliki .
PFX FV 0 kyetutalibi .
PFX FV 0 kyetutalili .
PFX FV 0 kyetutaliga .
PFX FV 0 kyetutalika .
PFX FV 0 kyetutalibu .
PFX FV 0 kyetutalilu .
PFX FV 0 kyetutaliku .
PFX FV 0 kyetutalitu .
PFX FV 0 kyemutalin [^lmnb]
PFX FV l kyemutalind l.[^mn][^u]
PFX FV l kyemutalinn l.[mn]
PFX FV w kyemutalimp [w]
PFX FV 0 kyemutalimu .
PFX FV 0 kyemutaliba .
PFX FV 0 kyemutaligu .
PFX FV 0 kyemutaligi .
PFX FV 0 kyemutalizi .
PFX FV 0 kyemutaliki .
PFX FV 0 kyemutalibi .
PFX FV 0 kyemutalili .
PFX FV 0 kyemutaliga .
PFX FV 0 kyemutalika .
PFX FV 0 kyemutalibu .
PFX FV 0 kyemutalilu .
PFX FV 0 kyemutaliku .
PFX FV 0 kyemutalitu .
PFX FV 0 kyebatalin [^lmnb]
PFX FV l kyebatalind l.[^mn][^u]
PFX FV l kyebatalinn l.[mn]
PFX FV w kyebatalimp [w]
PFX FV 0 kyebatalimu .
PFX FV 0 kyebataliba .
PFX FV 0 kyebataligu .
PFX FV 0 kyebataligi .
PFX FV 0 kyebatalizi .
PFX FV 0 kyebataliki .
PFX FV 0 kyebatalibi .
PFX FV 0 kyebatalili .
PFX FV 0 kyebataliga .
PFX FV 0 kyebatalika .
PFX FV 0 kyebatalibu .
PFX FV 0 kyebatalilu .
PFX FV 0 kyebataliku .
PFX FV 0 kyebatalitu .
PFX FV 0 kyegutalin [^lmnb]
PFX FV l kyegutalind l.[^mn][^u]
PFX FV l kyegutalinn l.[mn]
PFX FV w kyegutalimp [w]
PFX FV 0 kyegutalimu .
PFX FV 0 kyegutaliba .
PFX FV 0 kyegutaligu .
PFX FV 0 kyegutaligi .
PFX FV 0 kyegutalizi .
PFX FV 0 kyegutaliki .
PFX FV 0 kyegutalibi .
PFX FV 0 kyegutalili .
PFX FV 0 kyegutaliga .
PFX FV 0 kyegutalika .
PFX FV 0 kyegutalibu .
PFX FV 0 kyegutalilu .
PFX FV 0 kyegutaliku .
PFX FV 0 kyegutalitu .
PFX FV 0 kyegitalin [^lmnb]
PFX FV l kyegitalind l.[^mn][^u]
PFX FV l kyegitalinn l.[mn]
PFX FV w kyegitalimp [w]
PFX FV 0 kyegitalimu .
PFX FV 0 kyegitaliba .
PFX FV 0 kyegitaligu .
PFX FV 0 kyegitaligi .
PFX FV 0 kyegitalizi .
PFX FV 0 kyegitaliki .
PFX FV 0 kyegitalibi .
PFX FV 0 kyegitalili .
PFX FV 0 kyegitaliga .
PFX FV 0 kyegitalika .
PFX FV 0 kyegitalibu .
PFX FV 0 kyegitalilu .
PFX FV 0 kyegitaliku .
PFX FV 0 kyegitalitu .
PFX FV 0 kyezitalin [^lmnb]
PFX FV l kyezitalind l.[^mn][^u]
PFX FV l kyezitalinn l.[mn]
PFX FV w kyezitalimp [w]
PFX FV 0 kyezitalimu .
PFX FV 0 kyezitaliba .
PFX FV 0 kyezitaligu .
PFX FV 0 kyezitaligi .
PFX FV 0 kyezitalizi .
PFX FV 0 kyezitaliki .
PFX FV 0 kyezitalibi .
PFX FV 0 kyezitalili .
PFX FV 0 kyezitaliga .
PFX FV 0 kyezitalika .
PFX FV 0 kyezitalibu .
PFX FV 0 kyezitalilu .
PFX FV 0 kyezitaliku .
PFX FV 0 kyezitalitu .
PFX FV 0 kyekitalin [^lmnb]
PFX FV l kyekitalind l.[^mn][^u]
PFX FV l kyekitalinn l.[mn]
PFX FV w kyekitalimp [w]
PFX FV 0 kyekitalimu .
PFX FV 0 kyekitaliba .
PFX FV 0 kyekitaligu .
PFX FV 0 kyekitaligi .
PFX FV 0 kyekitalizi .
PFX FV 0 kyekitaliki .
PFX FV 0 kyekitalibi .
PFX FV 0 kyekitalili .
PFX FV 0 kyekitaliga .
PFX FV 0 kyekitalika .
PFX FV 0 kyekitalibu .
PFX FV 0 kyekitalilu .
PFX FV 0 kyekitaliku .
PFX FV 0 kyekitalitu .
PFX FV 0 kyebitalin [^lmnb]
PFX FV l kyebitalind l.[^mn][^u]
PFX FV l kyebitalinn l.[mn]
PFX FV w kyebitalimp [w]
PFX FV 0 kyebitalimu .
PFX FV 0 kyebitaliba .
PFX FV 0 kyebitaligu .
PFX FV 0 kyebitaligi .
PFX FV 0 kyebitalizi .
PFX FV 0 kyebitaliki .
PFX FV 0 kyebitalibi .
PFX FV 0 kyebitalili .
PFX FV 0 kyebitaliga .
PFX FV 0 kyebitalika .
PFX FV 0 kyebitalibu .
PFX FV 0 kyebitalilu .
PFX FV 0 kyebitaliku .
PFX FV 0 kyebitalitu .
PFX FV 0 kyelitalin [^lmnb]
PFX FV l kyelitalind l.[^mn][^u]
PFX FV l kyelitalinn l.[mn]
PFX FV w kyelitalimp [w]
PFX FV 0 kyelitalimu .
PFX FV 0 kyelitaliba .
PFX FV 0 kyelitaligu .
PFX FV 0 kyelitaligi .
PFX FV 0 kyelitalizi .
PFX FV 0 kyelitaliki .
PFX FV 0 kyelitalibi .
PFX FV 0 kyelitalili .
PFX FV 0 kyelitaliga .
PFX FV 0 kyelitalika .
PFX FV 0 kyelitalibu .
PFX FV 0 kyelitalilu .
PFX FV 0 kyelitaliku .
PFX FV 0 kyelitalitu .
PFX FV 0 kyegatalin [^lmnb]
PFX FV l kyegatalind l.[^mn][^u]
PFX FV l kyegatalinn l.[mn]
PFX FV w kyegatalimp [w]
PFX FV 0 kyegatalimu .
PFX FV 0 kyegataliba .
PFX FV 0 kyegataligu .
PFX FV 0 kyegataligi .
PFX FV 0 kyegatalizi .
PFX FV 0 kyegataliki .
PFX FV 0 kyegatalibi .
PFX FV 0 kyegatalili .
PFX FV 0 kyegataliga .
PFX FV 0 kyegatalika .
PFX FV 0 kyegatalibu .
PFX FV 0 kyegatalilu .
PFX FV 0 kyegataliku .
PFX FV 0 kyegatalitu .
PFX FV 0 kyekatalin [^lmnb]
PFX FV l kyekatalind l.[^mn][^u]
PFX FV l kyekatalinn l.[mn]
PFX FV w kyekatalimp [w]
PFX FV 0 kyekatalimu .
PFX FV 0 kyekataliba .
PFX FV 0 kyekataligu .
PFX FV 0 kyekataligi .
PFX FV 0 kyekatalizi .
PFX FV 0 kyekataliki .
PFX FV 0 kyekatalibi .
PFX FV 0 kyekatalili .
PFX FV 0 kyekataliga .
PFX FV 0 kyekatalika .
PFX FV 0 kyekatalibu .
PFX FV 0 kyekatalilu .
PFX FV 0 kyekataliku .
PFX FV 0 kyekatalitu .
PFX FV 0 kyebutalin [^lmnb]
PFX FV l kyebutalind l.[^mn][^u]
PFX FV l kyebutalinn l.[mn]
PFX FV w kyebutalimp [w]
PFX FV 0 kyebutalimu .
PFX FV 0 kyebutaliba .
PFX FV 0 kyebutaligu .
PFX FV 0 kyebutaligi .
PFX FV 0 kyebutalizi .
PFX FV 0 kyebutaliki .
PFX FV 0 kyebutalibi .
PFX FV 0 kyebutalili .
PFX FV 0 kyebutaliga .
PFX FV 0 kyebutalika .
PFX FV 0 kyebutalibu .
PFX FV 0 kyebutalilu .
PFX FV 0 kyebutaliku .
PFX FV 0 kyebutalitu .
PFX FV 0 kyelutalin [^lmnb]
PFX FV l kyelutalind l.[^mn][^u]
PFX FV l kyelutalinn l.[mn]
PFX FV w kyelutalimp [w]
PFX FV 0 kyelutalimu .
PFX FV 0 kyelutaliba .
PFX FV 0 kyelutaligu .
PFX FV 0 kyelutaligi .
PFX FV 0 kyelutalizi .
PFX FV 0 kyelutaliki .
PFX FV 0 kyelutalibi .
PFX FV 0 kyelutalili .
PFX FV 0 kyelutaliga .
PFX FV 0 kyelutalika .
PFX FV 0 kyelutalibu .
PFX FV 0 kyelutalilu .
PFX FV 0 kyelutaliku .
PFX FV 0 kyelutalitu .
PFX FV 0 kyekutalin [^lmnb]
PFX FV l kyekutalind l.[^mn][^u]
PFX FV l kyekutalinn l.[mn]
PFX FV w kyekutalimp [w]
PFX FV 0 kyekutalimu .
PFX FV 0 kyekutaliba .
PFX FV 0 kyekutaligu .
PFX FV 0 kyekutaligi .
PFX FV 0 kyekutalizi .
PFX FV 0 kyekutaliki .
PFX FV 0 kyekutalibi .
PFX FV 0 kyekutalili .
PFX FV 0 kyekutaliga .
PFX FV 0 kyekutalika .
PFX FV 0 kyekutalibu .
PFX FV 0 kyekutalilu .
PFX FV 0 kyekutaliku .
PFX FV 0 kyekutalitu .
PFX FV 0 kyetutalin [^lmnb]
PFX FV l kyetutalind l.[^mn][^u]
PFX FV l kyetutalinn l.[mn]
PFX FV w kyetutalimp [w]
PFX FV 0 kyetutalimu .
PFX FV 0 kyetutaliba .
PFX FV 0 kyetutaligu .
PFX FV 0 kyetutaligi .
PFX FV 0 kyetutalizi .
PFX FV 0 kyetutaliki .
PFX FV 0 kyetutalibi .
PFX FV 0 kyetutalili .
PFX FV 0 kyetutaliga .
PFX FV 0 kyetutalika .
PFX FV 0 kyetutalibu .
PFX FV 0 kyetutalilu .
PFX FV 0 kyetutaliku .
PFX FV 0 kyetutalitu .
PFX FV 0 by'otolin [^lmnb]
PFX FV l by'otolind l.[^mn][^u]
PFX FV l by'otolinn l.[mn]
PFX FV w by'otolimp [w]
PFX FV 0 by'otolimu .
PFX FV 0 by'otoliba .
PFX FV 0 by'otoligu .
PFX FV 0 by'otoligi .
PFX FV 0 by'otolizi .
PFX FV 0 by'otoliki .
PFX FV 0 by'otolibi .
PFX FV 0 by'otolili .
PFX FV 0 by'otoliga .
PFX FV 0 by'otolika .
PFX FV 0 by'otolibu .
PFX FV 0 by'otolilu .
PFX FV 0 by'otoliku .
PFX FV 0 by'otolitu .
PFX FV 0 by'atalin [^lmnb]
PFX FV l by'atalind l.[^mn][^u]
PFX FV l by'atalinn l.[mn]
PFX FV w by'atalimp [w]
PFX FV 0 by'atalimu .
PFX FV 0 by'ataliba .
PFX FV 0 by'ataligu .
PFX FV 0 by'ataligi .
PFX FV 0 by'atalizi .
PFX FV 0 by'ataliki .
PFX FV 0 by'atalibi .
PFX FV 0 by'atalili .
PFX FV 0 by'ataliga .
PFX FV 0 by'atalika .
PFX FV 0 by'atalibu .
PFX FV 0 by'atalilu .
PFX FV 0 by'ataliku .
PFX FV 0 by'atalitu .
PFX FV 0 by'etelin [^lmnb]
PFX FV l by'etelind l.[^mn][^u]
PFX FV l by'etelinn l.[mn]
PFX FV w by'etelimp [w]
PFX FV 0 by'etelimu .
PFX FV 0 by'eteliba .
PFX FV 0 by'eteligu .
PFX FV 0 by'eteligi .
PFX FV 0 by'etelizi .
PFX FV 0 by'eteliki .
PFX FV 0 by'etelibi .
PFX FV 0 by'etelili .
PFX FV 0 by'eteliga .
PFX FV 0 by'etelika .
PFX FV 0 by'etelibu .
PFX FV 0 by'etelilu .
PFX FV 0 by'eteliku .
PFX FV 0 by'etelitu .
PFX FV 0 byessiliba .
PFX FV 0 byessiligu .
PFX FV 0 byessiligi .
PFX FV 0 byessilizi .
PFX FV 0 byessiliki .
PFX FV 0 byessilibi .
PFX FV 0 byessilili .
PFX FV 0 byessiliga .
PFX FV 0 byessilika .
PFX FV 0 byessilibu .
PFX FV 0 byessililu .
PFX FV 0 byessiliku .
PFX FV 0 byessilitu .
PFX FV 0 byessilimu .
PFX FV 0 byetutalin [^lmnb]
PFX FV l byetutalind l.[^mn][^u]
PFX FV l byetutalinn l.[mn]
PFX FV w byetutalimp [w]
PFX FV 0 byetutalimu .
PFX FV 0 byetutaliba .
PFX FV 0 byetutaligu .
PFX FV 0 byetutaligi .
PFX FV 0 byetutalizi .
PFX FV 0 byetutaliki .
PFX FV 0 byetutalibi .
PFX FV 0 byetutalili .
PFX FV 0 byetutaliga .
PFX FV 0 byetutalika .
PFX FV 0 byetutalibu .
PFX FV 0 byetutalilu .
PFX FV 0 byetutaliku .
PFX FV 0 byetutalitu .
PFX FV 0 byemutalin [^lmnb]
PFX FV l byemutalind l.[^mn][^u]
PFX FV l byemutalinn l.[mn]
PFX FV w byemutalimp [w]
PFX FV 0 byemutalimu .
PFX FV 0 byemutaliba .
PFX FV 0 byemutaligu .
PFX FV 0 byemutaligi .
PFX FV 0 byemutalizi .
PFX FV 0 byemutaliki .
PFX FV 0 byemutalibi .
PFX FV 0 byemutalili .
PFX FV 0 byemutaliga .
PFX FV 0 byemutalika .
PFX FV 0 byemutalibu .
PFX FV 0 byemutalilu .
PFX FV 0 byemutaliku .
PFX FV 0 byemutalitu .
PFX FV 0 byebatalin [^lmnb]
PFX FV l byebatalind l.[^mn][^u]
PFX FV l byebatalinn l.[mn]
PFX FV w byebatalimp [w]
PFX FV 0 byebatalimu .
PFX FV 0 byebataliba .
PFX FV 0 byebataligu .
PFX FV 0 byebataligi .
PFX FV 0 byebatalizi .
PFX FV 0 byebataliki .
PFX FV 0 byebatalibi .
PFX FV 0 byebatalili .
PFX FV 0 byebataliga .
PFX FV 0 byebatalika .
PFX FV 0 byebatalibu .
PFX FV 0 byebatalilu .
PFX FV 0 byebataliku .
PFX FV 0 byebatalitu .
PFX FV 0 byegutalin [^lmnb]
PFX FV l byegutalind l.[^mn][^u]
PFX FV l byegutalinn l.[mn]
PFX FV w byegutalimp [w]
PFX FV 0 byegutalimu .
PFX FV 0 byegutaliba .
PFX FV 0 byegutaligu .
PFX FV 0 byegutaligi .
PFX FV 0 byegutalizi .
PFX FV 0 byegutaliki .
PFX FV 0 byegutalibi .
PFX FV 0 byegutalili .
PFX FV 0 byegutaliga .
PFX FV 0 byegutalika .
PFX FV 0 byegutalibu .
PFX FV 0 byegutalilu .
PFX FV 0 byegutaliku .
PFX FV 0 byegutalitu .
PFX FV 0 byegitalin [^lmnb]
PFX FV l byegitalind l.[^mn][^u]
PFX FV l byegitalinn l.[mn]
PFX FV w byegitalimp [w]
PFX FV 0 byegitalimu .
PFX FV 0 byegitaliba .
PFX FV 0 byegitaligu .
PFX FV 0 byegitaligi .
PFX FV 0 byegitalizi .
PFX FV 0 byegitaliki .
PFX FV 0 byegitalibi .
PFX FV 0 byegitalili .
PFX FV 0 byegitaliga .
PFX FV 0 byegitalika .
PFX FV 0 byegitalibu .
PFX FV 0 byegitalilu .
PFX FV 0 byegitaliku .
PFX FV 0 byegitalitu .
PFX FV 0 byezitalin [^lmnb]
PFX FV l byezitalind l.[^mn][^u]
PFX FV l byezitalinn l.[mn]
PFX FV w byezitalimp [w]
PFX FV 0 byezitalimu .
PFX FV 0 byezitaliba .
PFX FV 0 byezitaligu .
PFX FV 0 byezitaligi .
PFX FV 0 byezitalizi .
PFX FV 0 byezitaliki .
PFX FV 0 byezitalibi .
PFX FV 0 byezitalili .
PFX FV 0 byezitaliga .
PFX FV 0 byezitalika .
PFX FV 0 byezitalibu .
PFX FV 0 byezitalilu .
PFX FV 0 byezitaliku .
PFX FV 0 byezitalitu .
PFX FV 0 byekitalin [^lmnb]
PFX FV l byekitalind l.[^mn][^u]
PFX FV l byekitalinn l.[mn]
PFX FV w byekitalimp [w]
PFX FV 0 byekitalimu .
PFX FV 0 byekitaliba .
PFX FV 0 byekitaligu .
PFX FV 0 byekitaligi .
PFX FV 0 byekitalizi .
PFX FV 0 byekitaliki .
PFX FV 0 byekitalibi .
PFX FV 0 byekitalili .
PFX FV 0 byekitaliga .
PFX FV 0 byekitalika .
PFX FV 0 byekitalibu .
PFX FV 0 byekitalilu .
PFX FV 0 byekitaliku .
PFX FV 0 byekitalitu .
PFX FV 0 byebitalin [^lmnb]
PFX FV l byebitalind l.[^mn][^u]
PFX FV l byebitalinn l.[mn]
PFX FV w byebitalimp [w]
PFX FV 0 byebitalimu .
PFX FV 0 byebitaliba .
PFX FV 0 byebitaligu .
PFX FV 0 byebitaligi .
PFX FV 0 byebitalizi .
PFX FV 0 byebitaliki .
PFX FV 0 byebitalibi .
PFX FV 0 byebitalili .
PFX FV 0 byebitaliga .
PFX FV 0 byebitalika .
PFX FV 0 byebitalibu .
PFX FV 0 byebitalilu .
PFX FV 0 byebitaliku .
PFX FV 0 byebitalitu .
PFX FV 0 byelitalin [^lmnb]
PFX FV l byelitalind l.[^mn][^u]
PFX FV l byelitalinn l.[mn]
PFX FV w byelitalimp [w]
PFX FV 0 byelitalimu .
PFX FV 0 byelitaliba .
PFX FV 0 byelitaligu .
PFX FV 0 byelitaligi .
PFX FV 0 byelitalizi .
PFX FV 0 byelitaliki .
PFX FV 0 byelitalibi .
PFX FV 0 byelitalili .
PFX FV 0 byelitaliga .
PFX FV 0 byelitalika .
PFX FV 0 byelitalibu .
PFX FV 0 byelitalilu .
PFX FV 0 byelitaliku .
PFX FV 0 byelitalitu .
PFX FV 0 byegatalin [^lmnb]
PFX FV l byegatalind l.[^mn][^u]
PFX FV l byegatalinn l.[mn]
PFX FV w byegatalimp [w]
PFX FV 0 byegatalimu .
PFX FV 0 byegataliba .
PFX FV 0 byegataligu .
PFX FV 0 byegataligi .
PFX FV 0 byegatalizi .
PFX FV 0 byegataliki .
PFX FV 0 byegatalibi .
PFX FV 0 byegatalili .
PFX FV 0 byegataliga .
PFX FV 0 byegatalika .
PFX FV 0 byegatalibu .
PFX FV 0 byegatalilu .
PFX FV 0 byegataliku .
PFX FV 0 byegatalitu .
PFX FV 0 byekatalin [^lmnb]
PFX FV l byekatalind l.[^mn][^u]
PFX FV l byekatalinn l.[mn]
PFX FV w byekatalimp [w]
PFX FV 0 byekatalimu .
PFX FV 0 byekataliba .
PFX FV 0 byekataligu .
PFX FV 0 byekataligi .
PFX FV 0 byekatalizi .
PFX FV 0 byekataliki .
PFX FV 0 byekatalibi .
PFX FV 0 byekatalili .
PFX FV 0 byekataliga .
PFX FV 0 byekatalika .
PFX FV 0 byekatalibu .
PFX FV 0 byekatalilu .
PFX FV 0 byekataliku .
PFX FV 0 byekatalitu .
PFX FV 0 byebutalin [^lmnb]
PFX FV l byebutalind l.[^mn][^u]
PFX FV l byebutalinn l.[mn]
PFX FV w byebutalimp [w]
PFX FV 0 byebutalimu .
PFX FV 0 byebutaliba .
PFX FV 0 byebutaligu .
PFX FV 0 byebutaligi .
PFX FV 0 byebutalizi .
PFX FV 0 byebutaliki .
PFX FV 0 byebutalibi .
PFX FV 0 byebutalili .
PFX FV 0 byebutaliga .
PFX FV 0 byebutalika .
PFX FV 0 byebutalibu .
PFX FV 0 byebutalilu .
PFX FV 0 byebutaliku .
PFX FV 0 byebutalitu .
PFX FV 0 byelutalin [^lmnb]
PFX FV l byelutalind l.[^mn][^u]
PFX FV l byelutalinn l.[mn]
PFX FV w byelutalimp [w]
PFX FV 0 byelutalimu .
PFX FV 0 byelutaliba .
PFX FV 0 byelutaligu .
PFX FV 0 byelutaligi .
PFX FV 0 byelutalizi .
PFX FV 0 byelutaliki .
PFX FV 0 byelutalibi .
PFX FV 0 byelutalili .
PFX FV 0 byelutaliga .
PFX FV 0 byelutalika .
PFX FV 0 byelutalibu .
PFX FV 0 byelutalilu .
PFX FV 0 byelutaliku .
PFX FV 0 byelutalitu .
PFX FV 0 byekutalin [^lmnb]
PFX FV l byekutalind l.[^mn][^u]
PFX FV l byekutalinn l.[mn]
PFX FV w byekutalimp [w]
PFX FV 0 byekutalimu .
PFX FV 0 byekutaliba .
PFX FV 0 byekutaligu .
PFX FV 0 byekutaligi .
PFX FV 0 byekutalizi .
PFX FV 0 byekutaliki .
PFX FV 0 byekutalibi .
PFX FV 0 byekutalili .
PFX FV 0 byekutaliga .
PFX FV 0 byekutalika .
PFX FV 0 byekutalibu .
PFX FV 0 byekutalilu .
PFX FV 0 byekutaliku .
PFX FV 0 byekutalitu .
PFX FV 0 byetutalin [^lmnb]
PFX FV l byetutalind l.[^mn][^u]
PFX FV l byetutalinn l.[mn]
PFX FV w byetutalimp [w]
PFX FV 0 byetutalimu .
PFX FV 0 byetutaliba .
PFX FV 0 byetutaligu .
PFX FV 0 byetutaligi .
PFX FV 0 byetutalizi .
PFX FV 0 byetutaliki .
PFX FV 0 byetutalibi .
PFX FV 0 byetutalili .
PFX FV 0 byetutaliga .
PFX FV 0 byetutalika .
PFX FV 0 byetutalibu .
PFX FV 0 byetutalilu .
PFX FV 0 byetutaliku .
PFX FV 0 byetutalitu .
PFX FV 0 ly'otolin [^lmnb]
PFX FV l ly'otolind l.[^mn][^u]
PFX FV l ly'otolinn l.[mn]
PFX FV w ly'otolimp [w]
PFX FV 0 ly'otolimu .
PFX FV 0 ly'otoliba .
PFX FV 0 ly'otoligu .
PFX FV 0 ly'otoligi .
PFX FV 0 ly'otolizi .
PFX FV 0 ly'otoliki .
PFX FV 0 ly'otolibi .
PFX FV 0 ly'otolili .
PFX FV 0 ly'otoliga .
PFX FV 0 ly'otolika .
PFX FV 0 ly'otolibu .
PFX FV 0 ly'otolilu .
PFX FV 0 ly'otoliku .
PFX FV 0 ly'otolitu .
PFX FV 0 ly'atalin [^lmnb]
PFX FV l ly'atalind l.[^mn][^u]
PFX FV l ly'atalinn l.[mn]
PFX FV w ly'atalimp [w]
PFX FV 0 ly'atalimu .
PFX FV 0 ly'ataliba .
PFX FV 0 ly'ataligu .
PFX FV 0 ly'ataligi .
PFX FV 0 ly'atalizi .
PFX FV 0 ly'ataliki .
PFX FV 0 ly'atalibi .
PFX FV 0 ly'atalili .
PFX FV 0 ly'ataliga .
PFX FV 0 ly'atalika .
PFX FV 0 ly'atalibu .
PFX FV 0 ly'atalilu .
PFX FV 0 ly'ataliku .
PFX FV 0 ly'atalitu .
PFX FV 0 ly'etelin [^lmnb]
PFX FV l ly'etelind l.[^mn][^u]
PFX FV l ly'etelinn l.[mn]
PFX FV w ly'etelimp [w]
PFX FV 0 ly'etelimu .
PFX FV 0 ly'eteliba .
PFX FV 0 ly'eteligu .
PFX FV 0 ly'eteligi .
PFX FV 0 ly'etelizi .
PFX FV 0 ly'eteliki .
PFX FV 0 ly'etelibi .
PFX FV 0 ly'etelili .
PFX FV 0 ly'eteliga .
PFX FV 0 ly'etelika .
PFX FV 0 ly'etelibu .
PFX FV 0 ly'etelilu .
PFX FV 0 ly'eteliku .
PFX FV 0 ly'etelitu .
PFX FV 0 lyessiliba .
PFX FV 0 lyessiligu .
PFX FV 0 lyessiligi .
PFX FV 0 lyessilizi .
PFX FV 0 lyessiliki .
PFX FV 0 lyessilibi .
PFX FV 0 lyessilili .
PFX FV 0 lyessiliga .
PFX FV 0 lyessilika .
PFX FV 0 lyessilibu .
PFX FV 0 lyessililu .
PFX FV 0 lyessiliku .
PFX FV 0 lyessilitu .
PFX FV 0 lyessilimu .
PFX FV 0 lyetutalin [^lmnb]
PFX FV l lyetutalind l.[^mn][^u]
PFX FV l lyetutalinn l.[mn]
PFX FV w lyetutalimp [w]
PFX FV 0 lyetutalimu .
PFX FV 0 lyetutaliba .
PFX FV 0 lyetutaligu .
PFX FV 0 lyetutaligi .
PFX FV 0 lyetutalizi .
PFX FV 0 lyetutaliki .
PFX FV 0 lyetutalibi .
PFX FV 0 lyetutalili .
PFX FV 0 lyetutaliga .
PFX FV 0 lyetutalika .
PFX FV 0 lyetutalibu .
PFX FV 0 lyetutalilu .
PFX FV 0 lyetutaliku .
PFX FV 0 lyetutalitu .
PFX FV 0 lyemutalin [^lmnb]
PFX FV l lyemutalind l.[^mn][^u]
PFX FV l lyemutalinn l.[mn]
PFX FV w lyemutalimp [w]
PFX FV 0 lyemutalimu .
PFX FV 0 lyemutaliba .
PFX FV 0 lyemutaligu .
PFX FV 0 lyemutaligi .
PFX FV 0 lyemutalizi .
PFX FV 0 lyemutaliki .
PFX FV 0 lyemutalibi .
PFX FV 0 lyemutalili .
PFX FV 0 lyemutaliga .
PFX FV 0 lyemutalika .
PFX FV 0 lyemutalibu .
PFX FV 0 lyemutalilu .
PFX FV 0 lyemutaliku .
PFX FV 0 lyemutalitu .
PFX FV 0 lyebatalin [^lmnb]
PFX FV l lyebatalind l.[^mn][^u]
PFX FV l lyebatalinn l.[mn]
PFX FV w lyebatalimp [w]
PFX FV 0 lyebatalimu .
PFX FV 0 lyebataliba .
PFX FV 0 lyebataligu .
PFX FV 0 lyebataligi .
PFX FV 0 lyebatalizi .
PFX FV 0 lyebataliki .
PFX FV 0 lyebatalibi .
PFX FV 0 lyebatalili .
PFX FV 0 lyebataliga .
PFX FV 0 lyebatalika .
PFX FV 0 lyebatalibu .
PFX FV 0 lyebatalilu .
PFX FV 0 lyebataliku .
PFX FV 0 lyebatalitu .
PFX FV 0 lyegutalin [^lmnb]
PFX FV l lyegutalind l.[^mn][^u]
PFX FV l lyegutalinn l.[mn]
PFX FV w lyegutalimp [w]
PFX FV 0 lyegutalimu .
PFX FV 0 lyegutaliba .
PFX FV 0 lyegutaligu .
PFX FV 0 lyegutaligi .
PFX FV 0 lyegutalizi .
PFX FV 0 lyegutaliki .
PFX FV 0 lyegutalibi .
PFX FV 0 lyegutalili .
PFX FV 0 lyegutaliga .
PFX FV 0 lyegutalika .
PFX FV 0 lyegutalibu .
PFX FV 0 lyegutalilu .
PFX FV 0 lyegutaliku .
PFX FV 0 lyegutalitu .
PFX FV 0 lyegitalin [^lmnb]
PFX FV l lyegitalind l.[^mn][^u]
PFX FV l lyegitalinn l.[mn]
PFX FV w lyegitalimp [w]
PFX FV 0 lyegitalimu .
PFX FV 0 lyegitaliba .
PFX FV 0 lyegitaligu .
PFX FV 0 lyegitaligi .
PFX FV 0 lyegitalizi .
PFX FV 0 lyegitaliki .
PFX FV 0 lyegitalibi .
PFX FV 0 lyegitalili .
PFX FV 0 lyegitaliga .
PFX FV 0 lyegitalika .
PFX FV 0 lyegitalibu .
PFX FV 0 lyegitalilu .
PFX FV 0 lyegitaliku .
PFX FV 0 lyegitalitu .
PFX FV 0 lyezitalin [^lmnb]
PFX FV l lyezitalind l.[^mn][^u]
PFX FV l lyezitalinn l.[mn]
PFX FV w lyezitalimp [w]
PFX FV 0 lyezitalimu .
PFX FV 0 lyezitaliba .
PFX FV 0 lyezitaligu .
PFX FV 0 lyezitaligi .
PFX FV 0 lyezitalizi .
PFX FV 0 lyezitaliki .
PFX FV 0 lyezitalibi .
PFX FV 0 lyezitalili .
PFX FV 0 lyezitaliga .
PFX FV 0 lyezitalika .
PFX FV 0 lyezitalibu .
PFX FV 0 lyezitalilu .
PFX FV 0 lyezitaliku .
PFX FV 0 lyezitalitu .
PFX FV 0 lyekitalin [^lmnb]
PFX FV l lyekitalind l.[^mn][^u]
PFX FV l lyekitalinn l.[mn]
PFX FV w lyekitalimp [w]
PFX FV 0 lyekitalimu .
PFX FV 0 lyekitaliba .
PFX FV 0 lyekitaligu .
PFX FV 0 lyekitaligi .
PFX FV 0 lyekitalizi .
PFX FV 0 lyekitaliki .
PFX FV 0 lyekitalibi .
PFX FV 0 lyekitalili .
PFX FV 0 lyekitaliga .
PFX FV 0 lyekitalika .
PFX FV 0 lyekitalibu .
PFX FV 0 lyekitalilu .
PFX FV 0 lyekitaliku .
PFX FV 0 lyekitalitu .
PFX FV 0 lyebitalin [^lmnb]
PFX FV l lyebitalind l.[^mn][^u]
PFX FV l lyebitalinn l.[mn]
PFX FV w lyebitalimp [w]
PFX FV 0 lyebitalimu .
PFX FV 0 lyebitaliba .
PFX FV 0 lyebitaligu .
PFX FV 0 lyebitaligi .
PFX FV 0 lyebitalizi .
PFX FV 0 lyebitaliki .
PFX FV 0 lyebitalibi .
PFX FV 0 lyebitalili .
PFX FV 0 lyebitaliga .
PFX FV 0 lyebitalika .
PFX FV 0 lyebitalibu .
PFX FV 0 lyebitalilu .
PFX FV 0 lyebitaliku .
PFX FV 0 lyebitalitu .
PFX FV 0 lyelitalin [^lmnb]
PFX FV l lyelitalind l.[^mn][^u]
PFX FV l lyelitalinn l.[mn]
PFX FV w lyelitalimp [w]
PFX FV 0 lyelitalimu .
PFX FV 0 lyelitaliba .
PFX FV 0 lyelitaligu .
PFX FV 0 lyelitaligi .
PFX FV 0 lyelitalizi .
PFX FV 0 lyelitaliki .
PFX FV 0 lyelitalibi .
PFX FV 0 lyelitalili .
PFX FV 0 lyelitaliga .
PFX FV 0 lyelitalika .
PFX FV 0 lyelitalibu .
PFX FV 0 lyelitalilu .
PFX FV 0 lyelitaliku .
PFX FV 0 lyelitalitu .
PFX FV 0 lyegatalin [^lmnb]
PFX FV l lyegatalind l.[^mn][^u]
PFX FV l lyegatalinn l.[mn]
PFX FV w lyegatalimp [w]
PFX FV 0 lyegatalimu .
PFX FV 0 lyegataliba .
PFX FV 0 lyegataligu .
PFX FV 0 lyegataligi .
PFX FV 0 lyegatalizi .
PFX FV 0 lyegataliki .
PFX FV 0 lyegatalibi .
PFX FV 0 lyegatalili .
PFX FV 0 lyegataliga .
PFX FV 0 lyegatalika .
PFX FV 0 lyegatalibu .
PFX FV 0 lyegatalilu .
PFX FV 0 lyegataliku .
PFX FV 0 lyegatalitu .
PFX FV 0 lyekatalin [^lmnb]
PFX FV l lyekatalind l.[^mn][^u]
PFX FV l lyekatalinn l.[mn]
PFX FV w lyekatalimp [w]
PFX FV 0 lyekatalimu .
PFX FV 0 lyekataliba .
PFX FV 0 lyekataligu .
PFX FV 0 lyekataligi .
PFX FV 0 lyekatalizi .
PFX FV 0 lyekataliki .
PFX FV 0 lyekatalibi .
PFX FV 0 lyekatalili .
PFX FV 0 lyekataliga .
PFX FV 0 lyekatalika .
PFX FV 0 lyekatalibu .
PFX FV 0 lyekatalilu .
PFX FV 0 lyekataliku .
PFX FV 0 lyekatalitu .
PFX FV 0 lyebutalin [^lmnb]
PFX FV l lyebutalind l.[^mn][^u]
PFX FV l lyebutalinn l.[mn]
PFX FV w lyebutalimp [w]
PFX FV 0 lyebutalimu .
PFX FV 0 lyebutaliba .
PFX FV 0 lyebutaligu .
PFX FV 0 lyebutaligi .
PFX FV 0 lyebutalizi .
PFX FV 0 lyebutaliki .
PFX FV 0 lyebutalibi .
PFX FV 0 lyebutalili .
PFX FV 0 lyebutaliga .
PFX FV 0 lyebutalika .
PFX FV 0 lyebutalibu .
PFX FV 0 lyebutalilu .
PFX FV 0 lyebutaliku .
PFX FV 0 lyebutalitu .
PFX FV 0 lyelutalin [^lmnb]
PFX FV l lyelutalind l.[^mn][^u]
PFX FV l lyelutalinn l.[mn]
PFX FV w lyelutalimp [w]
PFX FV 0 lyelutalimu .
PFX FV 0 lyelutaliba .
PFX FV 0 lyelutaligu .
PFX FV 0 lyelutaligi .
PFX FV 0 lyelutalizi .
PFX FV 0 lyelutaliki .
PFX FV 0 lyelutalibi .
PFX FV 0 lyelutalili .
PFX FV 0 lyelutaliga .
PFX FV 0 lyelutalika .
PFX FV 0 lyelutalibu .
PFX FV 0 lyelutalilu .
PFX FV 0 lyelutaliku .
PFX FV 0 lyelutalitu .
PFX FV 0 lyekutalin [^lmnb]
PFX FV l lyekutalind l.[^mn][^u]
PFX FV l lyekutalinn l.[mn]
PFX FV w lyekutalimp [w]
PFX FV 0 lyekutalimu .
PFX FV 0 lyekutaliba .
PFX FV 0 lyekutaligu .
PFX FV 0 lyekutaligi .
PFX FV 0 lyekutalizi .
PFX FV 0 lyekutaliki .
PFX FV 0 lyekutalibi .
PFX FV 0 lyekutalili .
PFX FV 0 lyekutaliga .
PFX FV 0 lyekutalika .
PFX FV 0 lyekutalibu .
PFX FV 0 lyekutalilu .
PFX FV 0 lyekutaliku .
PFX FV 0 lyekutalitu .
PFX FV 0 lyetutalin [^lmnb]
PFX FV l lyetutalind l.[^mn][^u]
PFX FV l lyetutalinn l.[mn]
PFX FV w lyetutalimp [w]
PFX FV 0 lyetutalimu .
PFX FV 0 lyetutaliba .
PFX FV 0 lyetutaligu .
PFX FV 0 lyetutaligi .
PFX FV 0 lyetutalizi .
PFX FV 0 lyetutaliki .
PFX FV 0 lyetutalibi .
PFX FV 0 lyetutalili .
PFX FV 0 lyetutaliga .
PFX FV 0 lyetutalika .
PFX FV 0 lyetutalibu .
PFX FV 0 lyetutalilu .
PFX FV 0 lyetutaliku .
PFX FV 0 lyetutalitu .
PFX FV 0 k'otolin [^lmnb]
PFX FV l k'otolind l.[^mn][^u]
PFX FV l k'otolinn l.[mn]
PFX FV w k'otolimp [w]
PFX FV 0 k'otolimu .
PFX FV 0 k'otoliba .
PFX FV 0 k'otoligu .
PFX FV 0 k'otoligi .
PFX FV 0 k'otolizi .
PFX FV 0 k'otoliki .
PFX FV 0 k'otolibi .
PFX FV 0 k'otolili .
PFX FV 0 k'otoliga .
PFX FV 0 k'otolika .
PFX FV 0 k'otolibu .
PFX FV 0 k'otolilu .
PFX FV 0 k'otoliku .
PFX FV 0 k'otolitu .
PFX FV 0 k'atalin [^lmnb]
PFX FV l k'atalind l.[^mn][^u]
PFX FV l k'atalinn l.[mn]
PFX FV w k'atalimp [w]
PFX FV 0 k'atalimu .
PFX FV 0 k'ataliba .
PFX FV 0 k'ataligu .
PFX FV 0 k'ataligi .
PFX FV 0 k'atalizi .
PFX FV 0 k'ataliki .
PFX FV 0 k'atalibi .
PFX FV 0 k'atalili .
PFX FV 0 k'ataliga .
PFX FV 0 k'atalika .
PFX FV 0 k'atalibu .
PFX FV 0 k'atalilu .
PFX FV 0 k'ataliku .
PFX FV 0 k'atalitu .
PFX FV 0 k'etelin [^lmnb]
PFX FV l k'etelind l.[^mn][^u]
PFX FV l k'etelinn l.[mn]
PFX FV w k'etelimp [w]
PFX FV 0 k'etelimu .
PFX FV 0 k'eteliba .
PFX FV 0 k'eteligu .
PFX FV 0 k'eteligi .
PFX FV 0 k'etelizi .
PFX FV 0 k'eteliki .
PFX FV 0 k'etelibi .
PFX FV 0 k'etelili .
PFX FV 0 k'eteliga .
PFX FV 0 k'etelika .
PFX FV 0 k'etelibu .
PFX FV 0 k'etelilu .
PFX FV 0 k'eteliku .
PFX FV 0 k'etelitu .
PFX FV 0 kessiliba .
PFX FV 0 kessiligu .
PFX FV 0 kessiligi .
PFX FV 0 kessilizi .
PFX FV 0 kessiliki .
PFX FV 0 kessilibi .
PFX FV 0 kessilili .
PFX FV 0 kessiliga .
PFX FV 0 kessilika .
PFX FV 0 kessilibu .
PFX FV 0 kessililu .
PFX FV 0 kessiliku .
PFX FV 0 kessilitu .
PFX FV 0 kessilimu .
PFX FV 0 ketutalin [^lmnb]
PFX FV l ketutalind l.[^mn][^u]
PFX FV l ketutalinn l.[mn]
PFX FV w ketutalimp [w]
PFX FV 0 ketutalimu .
PFX FV 0 ketutaliba .
PFX FV 0 ketutaligu .
PFX FV 0 ketutaligi .
PFX FV 0 ketutalizi .
PFX FV 0 ketutaliki .
PFX FV 0 ketutalibi .
PFX FV 0 ketutalili .
PFX FV 0 ketutaliga .
PFX FV 0 ketutalika .
PFX FV 0 ketutalibu .
PFX FV 0 ketutalilu .
PFX FV 0 ketutaliku .
PFX FV 0 ketutalitu .
PFX FV 0 kemutalin [^lmnb]
PFX FV l kemutalind l.[^mn][^u]
PFX FV l kemutalinn l.[mn]
PFX FV w kemutalimp [w]
PFX FV 0 kemutalimu .
PFX FV 0 kemutaliba .
PFX FV 0 kemutaligu .
PFX FV 0 kemutaligi .
PFX FV 0 kemutalizi .
PFX FV 0 kemutaliki .
PFX FV 0 kemutalibi .
PFX FV 0 kemutalili .
PFX FV 0 kemutaliga .
PFX FV 0 kemutalika .
PFX FV 0 kemutalibu .
PFX FV 0 kemutalilu .
PFX FV 0 kemutaliku .
PFX FV 0 kemutalitu .
PFX FV 0 kebatalin [^lmnb]
PFX FV l kebatalind l.[^mn][^u]
PFX FV l kebatalinn l.[mn]
PFX FV w kebatalimp [w]
PFX FV 0 kebatalimu .
PFX FV 0 kebataliba .
PFX FV 0 kebataligu .
PFX FV 0 kebataligi .
PFX FV 0 kebatalizi .
PFX FV 0 kebataliki .
PFX FV 0 kebatalibi .
PFX FV 0 kebatalili .
PFX FV 0 kebataliga .
PFX FV 0 kebatalika .
PFX FV 0 kebatalibu .
PFX FV 0 kebatalilu .
PFX FV 0 kebataliku .
PFX FV 0 kebatalitu .
PFX FV 0 kegutalin [^lmnb]
PFX FV l kegutalind l.[^mn][^u]
PFX FV l kegutalinn l.[mn]
PFX FV w kegutalimp [w]
PFX FV 0 kegutalimu .
PFX FV 0 kegutaliba .
PFX FV 0 kegutaligu .
PFX FV 0 kegutaligi .
PFX FV 0 kegutalizi .
PFX FV 0 kegutaliki .
PFX FV 0 kegutalibi .
PFX FV 0 kegutalili .
PFX FV 0 kegutaliga .
PFX FV 0 kegutalika .
PFX FV 0 kegutalibu .
PFX FV 0 kegutalilu .
PFX FV 0 kegutaliku .
PFX FV 0 kegutalitu .
PFX FV 0 kegitalin [^lmnb]
PFX FV l kegitalind l.[^mn][^u]
PFX FV l kegitalinn l.[mn]
PFX FV w kegitalimp [w]
PFX FV 0 kegitalimu .
PFX FV 0 kegitaliba .
PFX FV 0 kegitaligu .
PFX FV 0 kegitaligi .
PFX FV 0 kegitalizi .
PFX FV 0 kegitaliki .
PFX FV 0 kegitalibi .
PFX FV 0 kegitalili .
PFX FV 0 kegitaliga .
PFX FV 0 kegitalika .
PFX FV 0 kegitalibu .
PFX FV 0 kegitalilu .
PFX FV 0 kegitaliku .
PFX FV 0 kegitalitu .
PFX FV 0 kezitalin [^lmnb]
PFX FV l kezitalind l.[^mn][^u]
PFX FV l kezitalinn l.[mn]
PFX FV w kezitalimp [w]
PFX FV 0 kezitalimu .
PFX FV 0 kezitaliba .
PFX FV 0 kezitaligu .
PFX FV 0 kezitaligi .
PFX FV 0 kezitalizi .
PFX FV 0 kezitaliki .
PFX FV 0 kezitalibi .
PFX FV 0 kezitalili .
PFX FV 0 kezitaliga .
PFX FV 0 kezitalika .
PFX FV 0 kezitalibu .
PFX FV 0 kezitalilu .
PFX FV 0 kezitaliku .
PFX FV 0 kezitalitu .
PFX FV 0 kekitalin [^lmnb]
PFX FV l kekitalind l.[^mn][^u]
PFX FV l kekitalinn l.[mn]
PFX FV w kekitalimp [w]
PFX FV 0 kekitalimu .
PFX FV 0 kekitaliba .
PFX FV 0 kekitaligu .
PFX FV 0 kekitaligi .
PFX FV 0 kekitalizi .
PFX FV 0 kekitaliki .
PFX FV 0 kekitalibi .
PFX FV 0 kekitalili .
PFX FV 0 kekitaliga .
PFX FV 0 kekitalika .
PFX FV 0 kekitalibu .
PFX FV 0 kekitalilu .
PFX FV 0 kekitaliku .
PFX FV 0 kekitalitu .
PFX FV 0 kebitalin [^lmnb]
PFX FV l kebitalind l.[^mn][^u]
PFX FV l kebitalinn l.[mn]
PFX FV w kebitalimp [w]
PFX FV 0 kebitalimu .
PFX FV 0 kebitaliba .
PFX FV 0 kebitaligu .
PFX FV 0 kebitaligi .
PFX FV 0 kebitalizi .
PFX FV 0 kebitaliki .
PFX FV 0 kebitalibi .
PFX FV 0 kebitalili .
PFX FV 0 kebitaliga .
PFX FV 0 kebitalika .
PFX FV 0 kebitalibu .
PFX FV 0 kebitalilu .
PFX FV 0 kebitaliku .
PFX FV 0 kebitalitu .
PFX FV 0 kelitalin [^lmnb]
PFX FV l kelitalind l.[^mn][^u]
PFX FV l kelitalinn l.[mn]
PFX FV w kelitalimp [w]
PFX FV 0 kelitalimu .
PFX FV 0 kelitaliba .
PFX FV 0 kelitaligu .
PFX FV 0 kelitaligi .
PFX FV 0 kelitalizi .
PFX FV 0 kelitaliki .
PFX FV 0 kelitalibi .
PFX FV 0 kelitalili .
PFX FV 0 kelitaliga .
PFX FV 0 kelitalika .
PFX FV 0 kelitalibu .
PFX FV 0 kelitalilu .
PFX FV 0 kelitaliku .
PFX FV 0 kelitalitu .
PFX FV 0 kegatalin [^lmnb]
PFX FV l kegatalind l.[^mn][^u]
PFX FV l kegatalinn l.[mn]
PFX FV w kegatalimp [w]
PFX FV 0 kegatalimu .
PFX FV 0 kegataliba .
PFX FV 0 kegataligu .
PFX FV 0 kegataligi .
PFX FV 0 kegatalizi .
PFX FV 0 kegataliki .
PFX FV 0 kegatalibi .
PFX FV 0 kegatalili .
PFX FV 0 kegataliga .
PFX FV 0 kegatalika .
PFX FV 0 kegatalibu .
PFX FV 0 kegatalilu .
PFX FV 0 kegataliku .
PFX FV 0 kegatalitu .
PFX FV 0 kekatalin [^lmnb]
PFX FV l kekatalind l.[^mn][^u]
PFX FV l kekatalinn l.[mn]
PFX FV w kekatalimp [w]
PFX FV 0 kekatalimu .
PFX FV 0 kekataliba .
PFX FV 0 kekataligu .
PFX FV 0 kekataligi .
PFX FV 0 kekatalizi .
PFX FV 0 kekataliki .
PFX FV 0 kekatalibi .
PFX FV 0 kekatalili .
PFX FV 0 kekataliga .
PFX FV 0 kekatalika .
PFX FV 0 kekatalibu .
PFX FV 0 kekatalilu .
PFX FV 0 kekataliku .
PFX FV 0 kekatalitu .
PFX FV 0 kebutalin [^lmnb]
PFX FV l kebutalind l.[^mn][^u]
PFX FV l kebutalinn l.[mn]
PFX FV w kebutalimp [w]
PFX FV 0 kebutalimu .
PFX FV 0 kebutaliba .
PFX FV 0 kebutaligu .
PFX FV 0 kebutaligi .
PFX FV 0 kebutalizi .
PFX FV 0 kebutaliki .
PFX FV 0 kebutalibi .
PFX FV 0 kebutalili .
PFX FV 0 kebutaliga .
PFX FV 0 kebutalika .
PFX FV 0 kebutalibu .
PFX FV 0 kebutalilu .
PFX FV 0 kebutaliku .
PFX FV 0 kebutalitu .
PFX FV 0 kelutalin [^lmnb]
PFX FV l kelutalind l.[^mn][^u]
PFX FV l kelutalinn l.[mn]
PFX FV w kelutalimp [w]
PFX FV 0 kelutalimu .
PFX FV 0 kelutaliba .
PFX FV 0 kelutaligu .
PFX FV 0 kelutaligi .
PFX FV 0 kelutalizi .
PFX FV 0 kelutaliki .
PFX FV 0 kelutalibi .
PFX FV 0 kelutalili .
PFX FV 0 kelutaliga .
PFX FV 0 kelutalika .
PFX FV 0 kelutalibu .
PFX FV 0 kelutalilu .
PFX FV 0 kelutaliku .
PFX FV 0 kelutalitu .
PFX FV 0 kekutalin [^lmnb]
PFX FV l kekutalind l.[^mn][^u]
PFX FV l kekutalinn l.[mn]
PFX FV w kekutalimp [w]
PFX FV 0 kekutalimu .
PFX FV 0 kekutaliba .
PFX FV 0 kekutaligu .
PFX FV 0 kekutaligi .
PFX FV 0 kekutalizi .
PFX FV 0 kekutaliki .
PFX FV 0 kekutalibi .
PFX FV 0 kekutalili .
PFX FV 0 kekutaliga .
PFX FV 0 kekutalika .
PFX FV 0 kekutalibu .
PFX FV 0 kekutalilu .
PFX FV 0 kekutaliku .
PFX FV 0 kekutalitu .
PFX FV 0 ketutalin [^lmnb]
PFX FV l ketutalind l.[^mn][^u]
PFX FV l ketutalinn l.[mn]
PFX FV w ketutalimp [w]
PFX FV 0 ketutalimu .
PFX FV 0 ketutaliba .
PFX FV 0 ketutaligu .
PFX FV 0 ketutaligi .
PFX FV 0 ketutalizi .
PFX FV 0 ketutaliki .
PFX FV 0 ketutalibi .
PFX FV 0 ketutalili .
PFX FV 0 ketutaliga .
PFX FV 0 ketutalika .
PFX FV 0 ketutalibu .
PFX FV 0 ketutalilu .
PFX FV 0 ketutaliku .
PFX FV 0 ketutalitu ."""

rule_right_raw = """
PFX OR Y 16
PFX OR 0 mwe .
PFX OR 0 bee .
PFX OR 0 gwe .
PFX OR 0 gye .
PFX OR 0 zee .
PFX OR 0 kye .
PFX OR 0 bye .
PFX OR 0 lye .
PFX OR 0 gee .
PFX OR 0 kee .
PFX OR 0 bwe .
PFX OR 0 lwe .
PFX OR 0 zee .
PFX OR 0 kwe .
PFX OR 0 gee .
PFX OR 0 twe ."""

FLAG_DESCRIPTIONS = {
    "FV": "FV",
    "OR": "Special reflexive object markers",
}

def parse_rules(raw_text):
    rules = []
    for line in raw_text.strip().split('\n'):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        s = s.split('#', 1)[0].strip()
        parts = s.split()
        if len(parts) < 4:
            continue
        if parts[2] == 'Y':
            continue
        cond = parts[4] if len(parts) > 4 else '.'
        rules.append({'strip': parts[2], 'add': parts[3], 'cond': cond})
    return rules

def generate_block():
    lefts = parse_rules(rule_left_raw)
    rights = parse_rules(rule_right_raw)
    new_rules = []

    for left in lefts:
        for right in rights:
            if left['strip'] != '0':
                if not right['add'].startswith(left['strip']):
                    continue
                combined = left['add'] + right['add'][len(left['strip']):]
            else:
                combined = left['add'] + right['add']

            if left['cond'] != '.':
                if not re.match(left['cond'], right['add']):
                    continue

            new_rules.append({'strip': right['strip'], 'add': combined, 'cond': right['cond']})

    out_flag = "GP"
    left_desc = FLAG_DESCRIPTIONS.get("FV", "FV")
    right_desc = FLAG_DESCRIPTIONS.get("OR", "OR")
    comment_line = "# Cross product of {} ({}) and {} ({}) to {}".format(
        "FV", left_desc, "OR", right_desc, out_flag
    )

    output = ["PFX {} Y {}".format(out_flag, len(new_rules))]
    for r in new_rules:
        output.append("PFX {} {} {} {}".format(out_flag, r['strip'], r['add'], r['cond']))

    return (out_flag, "\n".join([comment_line] + output) + "\n")

def main():
    if not os.path.exists(AFF_FILE):
        print("Error: {} not found.".format(AFF_FILE))
        return

    out_flag, block = generate_block()

    with open(AFF_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    first_flag_idx = None
    last_flag_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("PFX {} ".format(out_flag)):
            if first_flag_idx is None:
                first_flag_idx = i
            last_flag_idx = i

    if first_flag_idx is not None and first_flag_idx > 0:
        prev_line = lines[first_flag_idx - 1].strip()
        if prev_line.startswith("# Cross product"):
            start_idx = first_flag_idx - 1
        else:
            start_idx = first_flag_idx
    elif first_flag_idx is not None:
        start_idx = first_flag_idx
    else:
        start_idx = None

    if start_idx is not None and last_flag_idx is not None:
        # Replace existing block in-place.
        new_lines = lines[:start_idx] + [block] + lines[last_flag_idx + 1:]
    else:
        # Insert before an anchor flag if requested; otherwise append.
        insert_idx = None
        if INSERT_BEFORE_FLAG:
            anchor_prefix = "PFX {} ".format(INSERT_BEFORE_FLAG)
            for i, line in enumerate(lines):
                if line.strip().startswith(anchor_prefix):
                    insert_idx = i
                    # If the anchor PFX block is preceded by one or more cross-product
                    # comment lines, insert before those comments to keep them attached
                    # to the anchor block.
                    while insert_idx > 0 and lines[insert_idx - 1].strip().startswith("# Cross product"):
                        insert_idx -= 1
                    break

        if insert_idx is not None:
            new_lines = lines[:insert_idx] + [block] + lines[insert_idx:]
        else:
            new_lines = lines
            if new_lines and not new_lines[-1].endswith(chr(10)):
                new_lines[-1] += chr(10)
            new_lines.append(block)

    with open(AFF_FILE, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    print("{}: updated in place.".format(out_flag))

if __name__ == '__main__':
    main()
