import re
import os
from pathlib import Path

# Cross product generator: FP x OR => GL
# Description:
# - Left block `FP`: FP
# - Right block `OR`: Special reflexive object markers
# - Output flag `GL`: Cross-product prefixes for FP x OR

REPO_ROOT = Path(__file__).resolve().parents[1]
AFF_FILE = REPO_ROOT / "Luganda.aff"

# If set to a flag name (e.g. "HB"), the generated cross-product block will be inserted
# immediately before the first "PFX <flag>" line when the output flag block doesn't
# already exist in the .aff.
INSERT_BEFORE_FLAG = "".strip() or None

rule_left_raw = """
PFX FP Y 3408
PFX FP 0 w'otoon [^lmnb]
PFX FP l w'otoond l.[^mn][^u]
PFX FP l w'otoonn l.[mn]
PFX FP w w'otoomp [w]
PFX FP 0 w'otoomu .
PFX FP 0 w'otooba .
PFX FP 0 w'otoogu .
PFX FP 0 w'otoogi .
PFX FP 0 w'otoozi .
PFX FP 0 w'otooki .
PFX FP 0 w'otoobi .
PFX FP 0 w'otooli .
PFX FP 0 w'otooga .
PFX FP 0 w'otooka .
PFX FP 0 w'otoobu .
PFX FP 0 w'otoolu .
PFX FP 0 w'otooku .
PFX FP 0 w'otootu .
PFX FP 0 w'ataan [^lmnb]
PFX FP l w'ataand l.[^mn][^u]
PFX FP l w'ataann l.[mn]
PFX FP w w'ataamp [w]
PFX FP 0 w'ataamu .
PFX FP 0 w'ataaba .
PFX FP 0 w'ataagu .
PFX FP 0 w'ataagi .
PFX FP 0 w'ataazi .
PFX FP 0 w'ataaki .
PFX FP 0 w'ataabi .
PFX FP 0 w'ataali .
PFX FP 0 w'ataaga .
PFX FP 0 w'ataaka .
PFX FP 0 w'ataabu .
PFX FP 0 w'ataalu .
PFX FP 0 w'ataaku .
PFX FP 0 w'ataatu .
PFX FP 0 w'etaan [^lmnb]
PFX FP l w'etaand l.[^mn][^u]
PFX FP l w'etaann l.[mn]
PFX FP w w'etaamp [w]
PFX FP 0 w'etaamu .
PFX FP 0 w'etaaba .
PFX FP 0 w'etaagu .
PFX FP 0 w'etaagi .
PFX FP 0 w'etaazi .
PFX FP 0 w'etaaki .
PFX FP 0 w'etaabi .
PFX FP 0 w'etaali .
PFX FP 0 w'etaaga .
PFX FP 0 w'etaaka .
PFX FP 0 w'etaabu .
PFX FP 0 w'etaalu .
PFX FP 0 w'etaaku .
PFX FP 0 w'etaatu .
PFX FP 0 wessiiba .
PFX FP 0 wessiigu .
PFX FP 0 wessiigi .
PFX FP 0 wessiizi .
PFX FP 0 wessiiki .
PFX FP 0 wessiibi .
PFX FP 0 wessiili .
PFX FP 0 wessiiga .
PFX FP 0 wessiika .
PFX FP 0 wessiibu .
PFX FP 0 wessiilu .
PFX FP 0 wessiiku .
PFX FP 0 wessiitu .
PFX FP 0 wessiimu .
PFX FP 0 wetutaan [^lmnb]
PFX FP l wetutaand l.[^mn][^u]
PFX FP l wetutaann l.[mn]
PFX FP w wetutaamp [w]
PFX FP 0 wetutaamu .
PFX FP 0 wetutaaba .
PFX FP 0 wetutaagu .
PFX FP 0 wetutaagi .
PFX FP 0 wetutaazi .
PFX FP 0 wetutaaki .
PFX FP 0 wetutaabi .
PFX FP 0 wetutaali .
PFX FP 0 wetutaaga .
PFX FP 0 wetutaaka .
PFX FP 0 wetutaabu .
PFX FP 0 wetutaalu .
PFX FP 0 wetutaaku .
PFX FP 0 wetutaatu .
PFX FP 0 wemutaan [^lmnb]
PFX FP l wemutaand l.[^mn][^u]
PFX FP l wemutaann l.[mn]
PFX FP w wemutaamp [w]
PFX FP 0 wemutaamu .
PFX FP 0 wemutaaba .
PFX FP 0 wemutaagu .
PFX FP 0 wemutaagi .
PFX FP 0 wemutaazi .
PFX FP 0 wemutaaki .
PFX FP 0 wemutaabi .
PFX FP 0 wemutaali .
PFX FP 0 wemutaaga .
PFX FP 0 wemutaaka .
PFX FP 0 wemutaabu .
PFX FP 0 wemutaalu .
PFX FP 0 wemutaaku .
PFX FP 0 wemutaatu .
PFX FP 0 webataan [^lmnb]
PFX FP l webataand l.[^mn][^u]
PFX FP l webataann l.[mn]
PFX FP w webataamp [w]
PFX FP 0 webataamu .
PFX FP 0 webataaba .
PFX FP 0 webataagu .
PFX FP 0 webataagi .
PFX FP 0 webataazi .
PFX FP 0 webataaki .
PFX FP 0 webataabi .
PFX FP 0 webataali .
PFX FP 0 webataaga .
PFX FP 0 webataaka .
PFX FP 0 webataabu .
PFX FP 0 webataalu .
PFX FP 0 webataaku .
PFX FP 0 webataatu .
PFX FP 0 wegutaan [^lmnb]
PFX FP l wegutaand l.[^mn][^u]
PFX FP l wegutaann l.[mn]
PFX FP w wegutaamp [w]
PFX FP 0 wegutaamu .
PFX FP 0 wegutaaba .
PFX FP 0 wegutaagu .
PFX FP 0 wegutaagi .
PFX FP 0 wegutaazi .
PFX FP 0 wegutaaki .
PFX FP 0 wegutaabi .
PFX FP 0 wegutaali .
PFX FP 0 wegutaaga .
PFX FP 0 wegutaaka .
PFX FP 0 wegutaabu .
PFX FP 0 wegutaalu .
PFX FP 0 wegutaaku .
PFX FP 0 wegutaatu .
PFX FP 0 wegitaan [^lmnb]
PFX FP l wegitaand l.[^mn][^u]
PFX FP l wegitaann l.[mn]
PFX FP w wegitaamp [w]
PFX FP 0 wegitaamu .
PFX FP 0 wegitaaba .
PFX FP 0 wegitaagu .
PFX FP 0 wegitaagi .
PFX FP 0 wegitaazi .
PFX FP 0 wegitaaki .
PFX FP 0 wegitaabi .
PFX FP 0 wegitaali .
PFX FP 0 wegitaaga .
PFX FP 0 wegitaaka .
PFX FP 0 wegitaabu .
PFX FP 0 wegitaalu .
PFX FP 0 wegitaaku .
PFX FP 0 wegitaatu .
PFX FP 0 wezitaan [^lmnb]
PFX FP l wezitaand l.[^mn][^u]
PFX FP l wezitaann l.[mn]
PFX FP w wezitaamp [w]
PFX FP 0 wezitaamu .
PFX FP 0 wezitaaba .
PFX FP 0 wezitaagu .
PFX FP 0 wezitaagi .
PFX FP 0 wezitaazi .
PFX FP 0 wezitaaki .
PFX FP 0 wezitaabi .
PFX FP 0 wezitaali .
PFX FP 0 wezitaaga .
PFX FP 0 wezitaaka .
PFX FP 0 wezitaabu .
PFX FP 0 wezitaalu .
PFX FP 0 wezitaaku .
PFX FP 0 wezitaatu .
PFX FP 0 wekitaan [^lmnb]
PFX FP l wekitaand l.[^mn][^u]
PFX FP l wekitaann l.[mn]
PFX FP w wekitaamp [w]
PFX FP 0 wekitaamu .
PFX FP 0 wekitaaba .
PFX FP 0 wekitaagu .
PFX FP 0 wekitaagi .
PFX FP 0 wekitaazi .
PFX FP 0 wekitaaki .
PFX FP 0 wekitaabi .
PFX FP 0 wekitaali .
PFX FP 0 wekitaaga .
PFX FP 0 wekitaaka .
PFX FP 0 wekitaabu .
PFX FP 0 wekitaalu .
PFX FP 0 wekitaaku .
PFX FP 0 wekitaatu .
PFX FP 0 webitaan [^lmnb]
PFX FP l webitaand l.[^mn][^u]
PFX FP l webitaann l.[mn]
PFX FP w webitaamp [w]
PFX FP 0 webitaamu .
PFX FP 0 webitaaba .
PFX FP 0 webitaagu .
PFX FP 0 webitaagi .
PFX FP 0 webitaazi .
PFX FP 0 webitaaki .
PFX FP 0 webitaabi .
PFX FP 0 webitaali .
PFX FP 0 webitaaga .
PFX FP 0 webitaaka .
PFX FP 0 webitaabu .
PFX FP 0 webitaalu .
PFX FP 0 webitaaku .
PFX FP 0 webitaatu .
PFX FP 0 welitaan [^lmnb]
PFX FP l welitaand l.[^mn][^u]
PFX FP l welitaann l.[mn]
PFX FP w welitaamp [w]
PFX FP 0 welitaamu .
PFX FP 0 welitaaba .
PFX FP 0 welitaagu .
PFX FP 0 welitaagi .
PFX FP 0 welitaazi .
PFX FP 0 welitaaki .
PFX FP 0 welitaabi .
PFX FP 0 welitaali .
PFX FP 0 welitaaga .
PFX FP 0 welitaaka .
PFX FP 0 welitaabu .
PFX FP 0 welitaalu .
PFX FP 0 welitaaku .
PFX FP 0 welitaatu .
PFX FP 0 wegataan [^lmnb]
PFX FP l wegataand l.[^mn][^u]
PFX FP l wegataann l.[mn]
PFX FP w wegataamp [w]
PFX FP 0 wegataamu .
PFX FP 0 wegataaba .
PFX FP 0 wegataagu .
PFX FP 0 wegataagi .
PFX FP 0 wegataazi .
PFX FP 0 wegataaki .
PFX FP 0 wegataabi .
PFX FP 0 wegataali .
PFX FP 0 wegataaga .
PFX FP 0 wegataaka .
PFX FP 0 wegataabu .
PFX FP 0 wegataalu .
PFX FP 0 wegataaku .
PFX FP 0 wegataatu .
PFX FP 0 wekataan [^lmnb]
PFX FP l wekataand l.[^mn][^u]
PFX FP l wekataann l.[mn]
PFX FP w wekataamp [w]
PFX FP 0 wekataamu .
PFX FP 0 wekataaba .
PFX FP 0 wekataagu .
PFX FP 0 wekataagi .
PFX FP 0 wekataazi .
PFX FP 0 wekataaki .
PFX FP 0 wekataabi .
PFX FP 0 wekataali .
PFX FP 0 wekataaga .
PFX FP 0 wekataaka .
PFX FP 0 wekataabu .
PFX FP 0 wekataalu .
PFX FP 0 wekataaku .
PFX FP 0 wekataatu .
PFX FP 0 webutaan [^lmnb]
PFX FP l webutaand l.[^mn][^u]
PFX FP l webutaann l.[mn]
PFX FP w webutaamp [w]
PFX FP 0 webutaamu .
PFX FP 0 webutaaba .
PFX FP 0 webutaagu .
PFX FP 0 webutaagi .
PFX FP 0 webutaazi .
PFX FP 0 webutaaki .
PFX FP 0 webutaabi .
PFX FP 0 webutaali .
PFX FP 0 webutaaga .
PFX FP 0 webutaaka .
PFX FP 0 webutaabu .
PFX FP 0 webutaalu .
PFX FP 0 webutaaku .
PFX FP 0 webutaatu .
PFX FP 0 welutaan [^lmnb]
PFX FP l welutaand l.[^mn][^u]
PFX FP l welutaann l.[mn]
PFX FP w welutaamp [w]
PFX FP 0 welutaamu .
PFX FP 0 welutaaba .
PFX FP 0 welutaagu .
PFX FP 0 welutaagi .
PFX FP 0 welutaazi .
PFX FP 0 welutaaki .
PFX FP 0 welutaabi .
PFX FP 0 welutaali .
PFX FP 0 welutaaga .
PFX FP 0 welutaaka .
PFX FP 0 welutaabu .
PFX FP 0 welutaalu .
PFX FP 0 welutaaku .
PFX FP 0 welutaatu .
PFX FP 0 wekutaan [^lmnb]
PFX FP l wekutaand l.[^mn][^u]
PFX FP l wekutaann l.[mn]
PFX FP w wekutaamp [w]
PFX FP 0 wekutaamu .
PFX FP 0 wekutaaba .
PFX FP 0 wekutaagu .
PFX FP 0 wekutaagi .
PFX FP 0 wekutaazi .
PFX FP 0 wekutaaki .
PFX FP 0 wekutaabi .
PFX FP 0 wekutaali .
PFX FP 0 wekutaaga .
PFX FP 0 wekutaaka .
PFX FP 0 wekutaabu .
PFX FP 0 wekutaalu .
PFX FP 0 wekutaaku .
PFX FP 0 wekutaatu .
PFX FP 0 wetutaan [^lmnb]
PFX FP l wetutaand l.[^mn][^u]
PFX FP l wetutaann l.[mn]
PFX FP w wetutaamp [w]
PFX FP 0 wetutaamu .
PFX FP 0 wetutaaba .
PFX FP 0 wetutaagu .
PFX FP 0 wetutaagi .
PFX FP 0 wetutaazi .
PFX FP 0 wetutaaki .
PFX FP 0 wetutaabi .
PFX FP 0 wetutaali .
PFX FP 0 wetutaaga .
PFX FP 0 wetutaaka .
PFX FP 0 wetutaabu .
PFX FP 0 wetutaalu .
PFX FP 0 wetutaaku .
PFX FP 0 wetutaatu .
PFX FP 0 bw'otoon [^lmnb]
PFX FP l bw'otoond l.[^mn][^u]
PFX FP l bw'otoonn l.[mn]
PFX FP w bw'otoomp [w]
PFX FP 0 bw'otoomu .
PFX FP 0 bw'otooba .
PFX FP 0 bw'otoogu .
PFX FP 0 bw'otoogi .
PFX FP 0 bw'otoozi .
PFX FP 0 bw'otooki .
PFX FP 0 bw'otoobi .
PFX FP 0 bw'otooli .
PFX FP 0 bw'otooga .
PFX FP 0 bw'otooka .
PFX FP 0 bw'otoobu .
PFX FP 0 bw'otoolu .
PFX FP 0 bw'otooku .
PFX FP 0 bw'otootu .
PFX FP 0 bw'ataan [^lmnb]
PFX FP l bw'ataand l.[^mn][^u]
PFX FP l bw'ataann l.[mn]
PFX FP w bw'ataamp [w]
PFX FP 0 bw'ataamu .
PFX FP 0 bw'ataaba .
PFX FP 0 bw'ataagu .
PFX FP 0 bw'ataagi .
PFX FP 0 bw'ataazi .
PFX FP 0 bw'ataaki .
PFX FP 0 bw'ataabi .
PFX FP 0 bw'ataali .
PFX FP 0 bw'ataaga .
PFX FP 0 bw'ataaka .
PFX FP 0 bw'ataabu .
PFX FP 0 bw'ataalu .
PFX FP 0 bw'ataaku .
PFX FP 0 bw'ataatu .
PFX FP 0 bw'etaan [^lmnb]
PFX FP l bw'etaand l.[^mn][^u]
PFX FP l bw'etaann l.[mn]
PFX FP w bw'etaamp [w]
PFX FP 0 bw'etaamu .
PFX FP 0 bw'etaaba .
PFX FP 0 bw'etaagu .
PFX FP 0 bw'etaagi .
PFX FP 0 bw'etaazi .
PFX FP 0 bw'etaaki .
PFX FP 0 bw'etaabi .
PFX FP 0 bw'etaali .
PFX FP 0 bw'etaaga .
PFX FP 0 bw'etaaka .
PFX FP 0 bw'etaabu .
PFX FP 0 bw'etaalu .
PFX FP 0 bw'etaaku .
PFX FP 0 bw'etaatu .
PFX FP 0 bwessiiba .
PFX FP 0 bwessiigu .
PFX FP 0 bwessiigi .
PFX FP 0 bwessiizi .
PFX FP 0 bwessiiki .
PFX FP 0 bwessiibi .
PFX FP 0 bwessiili .
PFX FP 0 bwessiiga .
PFX FP 0 bwessiika .
PFX FP 0 bwessiibu .
PFX FP 0 bwessiilu .
PFX FP 0 bwessiiku .
PFX FP 0 bwessiitu .
PFX FP 0 bwessiimu .
PFX FP 0 bwetutaan [^lmnb]
PFX FP l bwetutaand l.[^mn][^u]
PFX FP l bwetutaann l.[mn]
PFX FP w bwetutaamp [w]
PFX FP 0 bwetutaamu .
PFX FP 0 bwetutaaba .
PFX FP 0 bwetutaagu .
PFX FP 0 bwetutaagi .
PFX FP 0 bwetutaazi .
PFX FP 0 bwetutaaki .
PFX FP 0 bwetutaabi .
PFX FP 0 bwetutaali .
PFX FP 0 bwetutaaga .
PFX FP 0 bwetutaaka .
PFX FP 0 bwetutaabu .
PFX FP 0 bwetutaalu .
PFX FP 0 bwetutaaku .
PFX FP 0 bwetutaatu .
PFX FP 0 bwemutaan [^lmnb]
PFX FP l bwemutaand l.[^mn][^u]
PFX FP l bwemutaann l.[mn]
PFX FP w bwemutaamp [w]
PFX FP 0 bwemutaamu .
PFX FP 0 bwemutaaba .
PFX FP 0 bwemutaagu .
PFX FP 0 bwemutaagi .
PFX FP 0 bwemutaazi .
PFX FP 0 bwemutaaki .
PFX FP 0 bwemutaabi .
PFX FP 0 bwemutaali .
PFX FP 0 bwemutaaga .
PFX FP 0 bwemutaaka .
PFX FP 0 bwemutaabu .
PFX FP 0 bwemutaalu .
PFX FP 0 bwemutaaku .
PFX FP 0 bwemutaatu .
PFX FP 0 bwebataan [^lmnb]
PFX FP l bwebataand l.[^mn][^u]
PFX FP l bwebataann l.[mn]
PFX FP w bwebataamp [w]
PFX FP 0 bwebataamu .
PFX FP 0 bwebataaba .
PFX FP 0 bwebataagu .
PFX FP 0 bwebataagi .
PFX FP 0 bwebataazi .
PFX FP 0 bwebataaki .
PFX FP 0 bwebataabi .
PFX FP 0 bwebataali .
PFX FP 0 bwebataaga .
PFX FP 0 bwebataaka .
PFX FP 0 bwebataabu .
PFX FP 0 bwebataalu .
PFX FP 0 bwebataaku .
PFX FP 0 bwebataatu .
PFX FP 0 bwegutaan [^lmnb]
PFX FP l bwegutaand l.[^mn][^u]
PFX FP l bwegutaann l.[mn]
PFX FP w bwegutaamp [w]
PFX FP 0 bwegutaamu .
PFX FP 0 bwegutaaba .
PFX FP 0 bwegutaagu .
PFX FP 0 bwegutaagi .
PFX FP 0 bwegutaazi .
PFX FP 0 bwegutaaki .
PFX FP 0 bwegutaabi .
PFX FP 0 bwegutaali .
PFX FP 0 bwegutaaga .
PFX FP 0 bwegutaaka .
PFX FP 0 bwegutaabu .
PFX FP 0 bwegutaalu .
PFX FP 0 bwegutaaku .
PFX FP 0 bwegutaatu .
PFX FP 0 bwegitaan [^lmnb]
PFX FP l bwegitaand l.[^mn][^u]
PFX FP l bwegitaann l.[mn]
PFX FP w bwegitaamp [w]
PFX FP 0 bwegitaamu .
PFX FP 0 bwegitaaba .
PFX FP 0 bwegitaagu .
PFX FP 0 bwegitaagi .
PFX FP 0 bwegitaazi .
PFX FP 0 bwegitaaki .
PFX FP 0 bwegitaabi .
PFX FP 0 bwegitaali .
PFX FP 0 bwegitaaga .
PFX FP 0 bwegitaaka .
PFX FP 0 bwegitaabu .
PFX FP 0 bwegitaalu .
PFX FP 0 bwegitaaku .
PFX FP 0 bwegitaatu .
PFX FP 0 bwezitaan [^lmnb]
PFX FP l bwezitaand l.[^mn][^u]
PFX FP l bwezitaann l.[mn]
PFX FP w bwezitaamp [w]
PFX FP 0 bwezitaamu .
PFX FP 0 bwezitaaba .
PFX FP 0 bwezitaagu .
PFX FP 0 bwezitaagi .
PFX FP 0 bwezitaazi .
PFX FP 0 bwezitaaki .
PFX FP 0 bwezitaabi .
PFX FP 0 bwezitaali .
PFX FP 0 bwezitaaga .
PFX FP 0 bwezitaaka .
PFX FP 0 bwezitaabu .
PFX FP 0 bwezitaalu .
PFX FP 0 bwezitaaku .
PFX FP 0 bwezitaatu .
PFX FP 0 bwekitaan [^lmnb]
PFX FP l bwekitaand l.[^mn][^u]
PFX FP l bwekitaann l.[mn]
PFX FP w bwekitaamp [w]
PFX FP 0 bwekitaamu .
PFX FP 0 bwekitaaba .
PFX FP 0 bwekitaagu .
PFX FP 0 bwekitaagi .
PFX FP 0 bwekitaazi .
PFX FP 0 bwekitaaki .
PFX FP 0 bwekitaabi .
PFX FP 0 bwekitaali .
PFX FP 0 bwekitaaga .
PFX FP 0 bwekitaaka .
PFX FP 0 bwekitaabu .
PFX FP 0 bwekitaalu .
PFX FP 0 bwekitaaku .
PFX FP 0 bwekitaatu .
PFX FP 0 bwebitaan [^lmnb]
PFX FP l bwebitaand l.[^mn][^u]
PFX FP l bwebitaann l.[mn]
PFX FP w bwebitaamp [w]
PFX FP 0 bwebitaamu .
PFX FP 0 bwebitaaba .
PFX FP 0 bwebitaagu .
PFX FP 0 bwebitaagi .
PFX FP 0 bwebitaazi .
PFX FP 0 bwebitaaki .
PFX FP 0 bwebitaabi .
PFX FP 0 bwebitaali .
PFX FP 0 bwebitaaga .
PFX FP 0 bwebitaaka .
PFX FP 0 bwebitaabu .
PFX FP 0 bwebitaalu .
PFX FP 0 bwebitaaku .
PFX FP 0 bwebitaatu .
PFX FP 0 bwelitaan [^lmnb]
PFX FP l bwelitaand l.[^mn][^u]
PFX FP l bwelitaann l.[mn]
PFX FP w bwelitaamp [w]
PFX FP 0 bwelitaamu .
PFX FP 0 bwelitaaba .
PFX FP 0 bwelitaagu .
PFX FP 0 bwelitaagi .
PFX FP 0 bwelitaazi .
PFX FP 0 bwelitaaki .
PFX FP 0 bwelitaabi .
PFX FP 0 bwelitaali .
PFX FP 0 bwelitaaga .
PFX FP 0 bwelitaaka .
PFX FP 0 bwelitaabu .
PFX FP 0 bwelitaalu .
PFX FP 0 bwelitaaku .
PFX FP 0 bwelitaatu .
PFX FP 0 bwegataan [^lmnb]
PFX FP l bwegataand l.[^mn][^u]
PFX FP l bwegataann l.[mn]
PFX FP w bwegataamp [w]
PFX FP 0 bwegataamu .
PFX FP 0 bwegataaba .
PFX FP 0 bwegataagu .
PFX FP 0 bwegataagi .
PFX FP 0 bwegataazi .
PFX FP 0 bwegataaki .
PFX FP 0 bwegataabi .
PFX FP 0 bwegataali .
PFX FP 0 bwegataaga .
PFX FP 0 bwegataaka .
PFX FP 0 bwegataabu .
PFX FP 0 bwegataalu .
PFX FP 0 bwegataaku .
PFX FP 0 bwegataatu .
PFX FP 0 bwekataan [^lmnb]
PFX FP l bwekataand l.[^mn][^u]
PFX FP l bwekataann l.[mn]
PFX FP w bwekataamp [w]
PFX FP 0 bwekataamu .
PFX FP 0 bwekataaba .
PFX FP 0 bwekataagu .
PFX FP 0 bwekataagi .
PFX FP 0 bwekataazi .
PFX FP 0 bwekataaki .
PFX FP 0 bwekataabi .
PFX FP 0 bwekataali .
PFX FP 0 bwekataaga .
PFX FP 0 bwekataaka .
PFX FP 0 bwekataabu .
PFX FP 0 bwekataalu .
PFX FP 0 bwekataaku .
PFX FP 0 bwekataatu .
PFX FP 0 bwebutaan [^lmnb]
PFX FP l bwebutaand l.[^mn][^u]
PFX FP l bwebutaann l.[mn]
PFX FP w bwebutaamp [w]
PFX FP 0 bwebutaamu .
PFX FP 0 bwebutaaba .
PFX FP 0 bwebutaagu .
PFX FP 0 bwebutaagi .
PFX FP 0 bwebutaazi .
PFX FP 0 bwebutaaki .
PFX FP 0 bwebutaabi .
PFX FP 0 bwebutaali .
PFX FP 0 bwebutaaga .
PFX FP 0 bwebutaaka .
PFX FP 0 bwebutaabu .
PFX FP 0 bwebutaalu .
PFX FP 0 bwebutaaku .
PFX FP 0 bwebutaatu .
PFX FP 0 bwelutaan [^lmnb]
PFX FP l bwelutaand l.[^mn][^u]
PFX FP l bwelutaann l.[mn]
PFX FP w bwelutaamp [w]
PFX FP 0 bwelutaamu .
PFX FP 0 bwelutaaba .
PFX FP 0 bwelutaagu .
PFX FP 0 bwelutaagi .
PFX FP 0 bwelutaazi .
PFX FP 0 bwelutaaki .
PFX FP 0 bwelutaabi .
PFX FP 0 bwelutaali .
PFX FP 0 bwelutaaga .
PFX FP 0 bwelutaaka .
PFX FP 0 bwelutaabu .
PFX FP 0 bwelutaalu .
PFX FP 0 bwelutaaku .
PFX FP 0 bwelutaatu .
PFX FP 0 bwekutaan [^lmnb]
PFX FP l bwekutaand l.[^mn][^u]
PFX FP l bwekutaann l.[mn]
PFX FP w bwekutaamp [w]
PFX FP 0 bwekutaamu .
PFX FP 0 bwekutaaba .
PFX FP 0 bwekutaagu .
PFX FP 0 bwekutaagi .
PFX FP 0 bwekutaazi .
PFX FP 0 bwekutaaki .
PFX FP 0 bwekutaabi .
PFX FP 0 bwekutaali .
PFX FP 0 bwekutaaga .
PFX FP 0 bwekutaaka .
PFX FP 0 bwekutaabu .
PFX FP 0 bwekutaalu .
PFX FP 0 bwekutaaku .
PFX FP 0 bwekutaatu .
PFX FP 0 bwetutaan [^lmnb]
PFX FP l bwetutaand l.[^mn][^u]
PFX FP l bwetutaann l.[mn]
PFX FP w bwetutaamp [w]
PFX FP 0 bwetutaamu .
PFX FP 0 bwetutaaba .
PFX FP 0 bwetutaagu .
PFX FP 0 bwetutaagi .
PFX FP 0 bwetutaazi .
PFX FP 0 bwetutaaki .
PFX FP 0 bwetutaabi .
PFX FP 0 bwetutaali .
PFX FP 0 bwetutaaga .
PFX FP 0 bwetutaaka .
PFX FP 0 bwetutaabu .
PFX FP 0 bwetutaalu .
PFX FP 0 bwetutaaku .
PFX FP 0 bwetutaatu .
PFX FP 0 bwessiiba .
PFX FP 0 bwessiigu .
PFX FP 0 bwessiigi .
PFX FP 0 bwessiizi .
PFX FP 0 bwessiiki .
PFX FP 0 bwessiibi .
PFX FP 0 bwessiili .
PFX FP 0 bwessiiga .
PFX FP 0 bwessiika .
PFX FP 0 bwessiibu .
PFX FP 0 bwessiilu .
PFX FP 0 bwessiiku .
PFX FP 0 bwessiitu .
PFX FP 0 bwessiimu .
PFX FP 0 lw'otoon [^lmnb]
PFX FP l lw'otoond l.[^mn][^u]
PFX FP l lw'otoonn l.[mn]
PFX FP w lw'otoomp [w]
PFX FP 0 lw'otoomu .
PFX FP 0 lw'otooba .
PFX FP 0 lw'otoogu .
PFX FP 0 lw'otoogi .
PFX FP 0 lw'otoozi .
PFX FP 0 lw'otooki .
PFX FP 0 lw'otoobi .
PFX FP 0 lw'otooli .
PFX FP 0 lw'otooga .
PFX FP 0 lw'otooka .
PFX FP 0 lw'otoobu .
PFX FP 0 lw'otoolu .
PFX FP 0 lw'otooku .
PFX FP 0 lw'otootu .
PFX FP 0 lw'ataan [^lmnb]
PFX FP l lw'ataand l.[^mn][^u]
PFX FP l lw'ataann l.[mn]
PFX FP w lw'ataamp [w]
PFX FP 0 lw'ataamu .
PFX FP 0 lw'ataaba .
PFX FP 0 lw'ataagu .
PFX FP 0 lw'ataagi .
PFX FP 0 lw'ataazi .
PFX FP 0 lw'ataaki .
PFX FP 0 lw'ataabi .
PFX FP 0 lw'ataali .
PFX FP 0 lw'ataaga .
PFX FP 0 lw'ataaka .
PFX FP 0 lw'ataabu .
PFX FP 0 lw'ataalu .
PFX FP 0 lw'ataaku .
PFX FP 0 lw'ataatu .
PFX FP 0 lw'etaan [^lmnb]
PFX FP l lw'etaand l.[^mn][^u]
PFX FP l lw'etaann l.[mn]
PFX FP w lw'etaamp [w]
PFX FP 0 lw'etaamu .
PFX FP 0 lw'etaaba .
PFX FP 0 lw'etaagu .
PFX FP 0 lw'etaagi .
PFX FP 0 lw'etaazi .
PFX FP 0 lw'etaaki .
PFX FP 0 lw'etaabi .
PFX FP 0 lw'etaali .
PFX FP 0 lw'etaaga .
PFX FP 0 lw'etaaka .
PFX FP 0 lw'etaabu .
PFX FP 0 lw'etaalu .
PFX FP 0 lw'etaaku .
PFX FP 0 lw'etaatu .
PFX FP 0 lwessiiba .
PFX FP 0 lwessiigu .
PFX FP 0 lwessiigi .
PFX FP 0 lwessiizi .
PFX FP 0 lwessiiki .
PFX FP 0 lwessiibi .
PFX FP 0 lwessiili .
PFX FP 0 lwessiiga .
PFX FP 0 lwessiika .
PFX FP 0 lwessiibu .
PFX FP 0 lwessiilu .
PFX FP 0 lwessiiku .
PFX FP 0 lwessiitu .
PFX FP 0 lwessiimu .
PFX FP 0 lwetutaan [^lmnb]
PFX FP l lwetutaand l.[^mn][^u]
PFX FP l lwetutaann l.[mn]
PFX FP w lwetutaamp [w]
PFX FP 0 lwetutaamu .
PFX FP 0 lwetutaaba .
PFX FP 0 lwetutaagu .
PFX FP 0 lwetutaagi .
PFX FP 0 lwetutaazi .
PFX FP 0 lwetutaaki .
PFX FP 0 lwetutaabi .
PFX FP 0 lwetutaali .
PFX FP 0 lwetutaaga .
PFX FP 0 lwetutaaka .
PFX FP 0 lwetutaabu .
PFX FP 0 lwetutaalu .
PFX FP 0 lwetutaaku .
PFX FP 0 lwetutaatu .
PFX FP 0 lwemutaan [^lmnb]
PFX FP l lwemutaand l.[^mn][^u]
PFX FP l lwemutaann l.[mn]
PFX FP w lwemutaamp [w]
PFX FP 0 lwemutaamu .
PFX FP 0 lwemutaaba .
PFX FP 0 lwemutaagu .
PFX FP 0 lwemutaagi .
PFX FP 0 lwemutaazi .
PFX FP 0 lwemutaaki .
PFX FP 0 lwemutaabi .
PFX FP 0 lwemutaali .
PFX FP 0 lwemutaaga .
PFX FP 0 lwemutaaka .
PFX FP 0 lwemutaabu .
PFX FP 0 lwemutaalu .
PFX FP 0 lwemutaaku .
PFX FP 0 lwemutaatu .
PFX FP 0 lwebataan [^lmnb]
PFX FP l lwebataand l.[^mn][^u]
PFX FP l lwebataann l.[mn]
PFX FP w lwebataamp [w]
PFX FP 0 lwebataamu .
PFX FP 0 lwebataaba .
PFX FP 0 lwebataagu .
PFX FP 0 lwebataagi .
PFX FP 0 lwebataazi .
PFX FP 0 lwebataaki .
PFX FP 0 lwebataabi .
PFX FP 0 lwebataali .
PFX FP 0 lwebataaga .
PFX FP 0 lwebataaka .
PFX FP 0 lwebataabu .
PFX FP 0 lwebataalu .
PFX FP 0 lwebataaku .
PFX FP 0 lwebataatu .
PFX FP 0 lwegutaan [^lmnb]
PFX FP l lwegutaand l.[^mn][^u]
PFX FP l lwegutaann l.[mn]
PFX FP w lwegutaamp [w]
PFX FP 0 lwegutaamu .
PFX FP 0 lwegutaaba .
PFX FP 0 lwegutaagu .
PFX FP 0 lwegutaagi .
PFX FP 0 lwegutaazi .
PFX FP 0 lwegutaaki .
PFX FP 0 lwegutaabi .
PFX FP 0 lwegutaali .
PFX FP 0 lwegutaaga .
PFX FP 0 lwegutaaka .
PFX FP 0 lwegutaabu .
PFX FP 0 lwegutaalu .
PFX FP 0 lwegutaaku .
PFX FP 0 lwegutaatu .
PFX FP 0 lwegitaan [^lmnb]
PFX FP l lwegitaand l.[^mn][^u]
PFX FP l lwegitaann l.[mn]
PFX FP w lwegitaamp [w]
PFX FP 0 lwegitaamu .
PFX FP 0 lwegitaaba .
PFX FP 0 lwegitaagu .
PFX FP 0 lwegitaagi .
PFX FP 0 lwegitaazi .
PFX FP 0 lwegitaaki .
PFX FP 0 lwegitaabi .
PFX FP 0 lwegitaali .
PFX FP 0 lwegitaaga .
PFX FP 0 lwegitaaka .
PFX FP 0 lwegitaabu .
PFX FP 0 lwegitaalu .
PFX FP 0 lwegitaaku .
PFX FP 0 lwegitaatu .
PFX FP 0 lwezitaan [^lmnb]
PFX FP l lwezitaand l.[^mn][^u]
PFX FP l lwezitaann l.[mn]
PFX FP w lwezitaamp [w]
PFX FP 0 lwezitaamu .
PFX FP 0 lwezitaaba .
PFX FP 0 lwezitaagu .
PFX FP 0 lwezitaagi .
PFX FP 0 lwezitaazi .
PFX FP 0 lwezitaaki .
PFX FP 0 lwezitaabi .
PFX FP 0 lwezitaali .
PFX FP 0 lwezitaaga .
PFX FP 0 lwezitaaka .
PFX FP 0 lwezitaabu .
PFX FP 0 lwezitaalu .
PFX FP 0 lwezitaaku .
PFX FP 0 lwezitaatu .
PFX FP 0 lwekitaan [^lmnb]
PFX FP l lwekitaand l.[^mn][^u]
PFX FP l lwekitaann l.[mn]
PFX FP w lwekitaamp [w]
PFX FP 0 lwekitaamu .
PFX FP 0 lwekitaaba .
PFX FP 0 lwekitaagu .
PFX FP 0 lwekitaagi .
PFX FP 0 lwekitaazi .
PFX FP 0 lwekitaaki .
PFX FP 0 lwekitaabi .
PFX FP 0 lwekitaali .
PFX FP 0 lwekitaaga .
PFX FP 0 lwekitaaka .
PFX FP 0 lwekitaabu .
PFX FP 0 lwekitaalu .
PFX FP 0 lwekitaaku .
PFX FP 0 lwekitaatu .
PFX FP 0 lwebitaan [^lmnb]
PFX FP l lwebitaand l.[^mn][^u]
PFX FP l lwebitaann l.[mn]
PFX FP w lwebitaamp [w]
PFX FP 0 lwebitaamu .
PFX FP 0 lwebitaaba .
PFX FP 0 lwebitaagu .
PFX FP 0 lwebitaagi .
PFX FP 0 lwebitaazi .
PFX FP 0 lwebitaaki .
PFX FP 0 lwebitaabi .
PFX FP 0 lwebitaali .
PFX FP 0 lwebitaaga .
PFX FP 0 lwebitaaka .
PFX FP 0 lwebitaabu .
PFX FP 0 lwebitaalu .
PFX FP 0 lwebitaaku .
PFX FP 0 lwebitaatu .
PFX FP 0 lwelitaan [^lmnb]
PFX FP l lwelitaand l.[^mn][^u]
PFX FP l lwelitaann l.[mn]
PFX FP w lwelitaamp [w]
PFX FP 0 lwelitaamu .
PFX FP 0 lwelitaaba .
PFX FP 0 lwelitaagu .
PFX FP 0 lwelitaagi .
PFX FP 0 lwelitaazi .
PFX FP 0 lwelitaaki .
PFX FP 0 lwelitaabi .
PFX FP 0 lwelitaali .
PFX FP 0 lwelitaaga .
PFX FP 0 lwelitaaka .
PFX FP 0 lwelitaabu .
PFX FP 0 lwelitaalu .
PFX FP 0 lwelitaaku .
PFX FP 0 lwelitaatu .
PFX FP 0 lwegataan [^lmnb]
PFX FP l lwegataand l.[^mn][^u]
PFX FP l lwegataann l.[mn]
PFX FP w lwegataamp [w]
PFX FP 0 lwegataamu .
PFX FP 0 lwegataaba .
PFX FP 0 lwegataagu .
PFX FP 0 lwegataagi .
PFX FP 0 lwegataazi .
PFX FP 0 lwegataaki .
PFX FP 0 lwegataabi .
PFX FP 0 lwegataali .
PFX FP 0 lwegataaga .
PFX FP 0 lwegataaka .
PFX FP 0 lwegataabu .
PFX FP 0 lwegataalu .
PFX FP 0 lwegataaku .
PFX FP 0 lwegataatu .
PFX FP 0 lwekataan [^lmnb]
PFX FP l lwekataand l.[^mn][^u]
PFX FP l lwekataann l.[mn]
PFX FP w lwekataamp [w]
PFX FP 0 lwekataamu .
PFX FP 0 lwekataaba .
PFX FP 0 lwekataagu .
PFX FP 0 lwekataagi .
PFX FP 0 lwekataazi .
PFX FP 0 lwekataaki .
PFX FP 0 lwekataabi .
PFX FP 0 lwekataali .
PFX FP 0 lwekataaga .
PFX FP 0 lwekataaka .
PFX FP 0 lwekataabu .
PFX FP 0 lwekataalu .
PFX FP 0 lwekataaku .
PFX FP 0 lwekataatu .
PFX FP 0 lwebutaan [^lmnb]
PFX FP l lwebutaand l.[^mn][^u]
PFX FP l lwebutaann l.[mn]
PFX FP w lwebutaamp [w]
PFX FP 0 lwebutaamu .
PFX FP 0 lwebutaaba .
PFX FP 0 lwebutaagu .
PFX FP 0 lwebutaagi .
PFX FP 0 lwebutaazi .
PFX FP 0 lwebutaaki .
PFX FP 0 lwebutaabi .
PFX FP 0 lwebutaali .
PFX FP 0 lwebutaaga .
PFX FP 0 lwebutaaka .
PFX FP 0 lwebutaabu .
PFX FP 0 lwebutaalu .
PFX FP 0 lwebutaaku .
PFX FP 0 lwebutaatu .
PFX FP 0 lwelutaan [^lmnb]
PFX FP l lwelutaand l.[^mn][^u]
PFX FP l lwelutaann l.[mn]
PFX FP w lwelutaamp [w]
PFX FP 0 lwelutaamu .
PFX FP 0 lwelutaaba .
PFX FP 0 lwelutaagu .
PFX FP 0 lwelutaagi .
PFX FP 0 lwelutaazi .
PFX FP 0 lwelutaaki .
PFX FP 0 lwelutaabi .
PFX FP 0 lwelutaali .
PFX FP 0 lwelutaaga .
PFX FP 0 lwelutaaka .
PFX FP 0 lwelutaabu .
PFX FP 0 lwelutaalu .
PFX FP 0 lwelutaaku .
PFX FP 0 lwelutaatu .
PFX FP 0 lwekutaan [^lmnb]
PFX FP l lwekutaand l.[^mn][^u]
PFX FP l lwekutaann l.[mn]
PFX FP w lwekutaamp [w]
PFX FP 0 lwekutaamu .
PFX FP 0 lwekutaaba .
PFX FP 0 lwekutaagu .
PFX FP 0 lwekutaagi .
PFX FP 0 lwekutaazi .
PFX FP 0 lwekutaaki .
PFX FP 0 lwekutaabi .
PFX FP 0 lwekutaali .
PFX FP 0 lwekutaaga .
PFX FP 0 lwekutaaka .
PFX FP 0 lwekutaabu .
PFX FP 0 lwekutaalu .
PFX FP 0 lwekutaaku .
PFX FP 0 lwekutaatu .
PFX FP 0 lwetutaan [^lmnb]
PFX FP l lwetutaand l.[^mn][^u]
PFX FP l lwetutaann l.[mn]
PFX FP w lwetutaamp [w]
PFX FP 0 lwetutaamu .
PFX FP 0 lwetutaaba .
PFX FP 0 lwetutaagu .
PFX FP 0 lwetutaagi .
PFX FP 0 lwetutaazi .
PFX FP 0 lwetutaaki .
PFX FP 0 lwetutaabi .
PFX FP 0 lwetutaali .
PFX FP 0 lwetutaaga .
PFX FP 0 lwetutaaka .
PFX FP 0 lwetutaabu .
PFX FP 0 lwetutaalu .
PFX FP 0 lwetutaaku .
PFX FP 0 lwetutaatu .
PFX FP 0 lwessiiba .
PFX FP 0 lwessiigu .
PFX FP 0 lwessiigi .
PFX FP 0 lwessiizi .
PFX FP 0 lwessiiki .
PFX FP 0 lwessiibi .
PFX FP 0 lwessiili .
PFX FP 0 lwessiiga .
PFX FP 0 lwessiika .
PFX FP 0 lwessiibu .
PFX FP 0 lwessiilu .
PFX FP 0 lwessiiku .
PFX FP 0 lwessiitu .
PFX FP 0 lwessiimu .
PFX FP 0 z'otoon [^lmnb]
PFX FP l z'otoond l.[^mn][^u]
PFX FP l z'otoonn l.[mn]
PFX FP w z'otoomp [w]
PFX FP 0 z'otoomu .
PFX FP 0 z'otooba .
PFX FP 0 z'otoogu .
PFX FP 0 z'otoogi .
PFX FP 0 z'otoozi .
PFX FP 0 z'otooki .
PFX FP 0 z'otoobi .
PFX FP 0 z'otooli .
PFX FP 0 z'otooga .
PFX FP 0 z'otooka .
PFX FP 0 z'otoobu .
PFX FP 0 z'otoolu .
PFX FP 0 z'otooku .
PFX FP 0 z'otootu .
PFX FP 0 z'ataan [^lmnb]
PFX FP l z'ataand l.[^mn][^u]
PFX FP l z'ataann l.[mn]
PFX FP w z'ataamp [w]
PFX FP 0 z'ataamu .
PFX FP 0 z'ataaba .
PFX FP 0 z'ataagu .
PFX FP 0 z'ataagi .
PFX FP 0 z'ataazi .
PFX FP 0 z'ataaki .
PFX FP 0 z'ataabi .
PFX FP 0 z'ataali .
PFX FP 0 z'ataaga .
PFX FP 0 z'ataaka .
PFX FP 0 z'ataabu .
PFX FP 0 z'ataalu .
PFX FP 0 z'ataaku .
PFX FP 0 z'ataatu .
PFX FP 0 z'etaan [^lmnb]
PFX FP l z'etaand l.[^mn][^u]
PFX FP l z'etaann l.[mn]
PFX FP w z'etaamp [w]
PFX FP 0 z'etaamu .
PFX FP 0 z'etaaba .
PFX FP 0 z'etaagu .
PFX FP 0 z'etaagi .
PFX FP 0 z'etaazi .
PFX FP 0 z'etaaki .
PFX FP 0 z'etaabi .
PFX FP 0 z'etaali .
PFX FP 0 z'etaaga .
PFX FP 0 z'etaaka .
PFX FP 0 z'etaabu .
PFX FP 0 z'etaalu .
PFX FP 0 z'etaaku .
PFX FP 0 z'etaatu .
PFX FP 0 zetutaan [^lmnb]
PFX FP l zetutaand l.[^mn][^u]
PFX FP l zetutaann l.[mn]
PFX FP w zetutaamp [w]
PFX FP 0 zetutaamu .
PFX FP 0 zetutaaba .
PFX FP 0 zetutaagu .
PFX FP 0 zetutaagi .
PFX FP 0 zetutaazi .
PFX FP 0 zetutaaki .
PFX FP 0 zetutaabi .
PFX FP 0 zetutaali .
PFX FP 0 zetutaaga .
PFX FP 0 zetutaaka .
PFX FP 0 zetutaabu .
PFX FP 0 zetutaalu .
PFX FP 0 zetutaaku .
PFX FP 0 zetutaatu .
PFX FP 0 zemutaan [^lmnb]
PFX FP l zemutaand l.[^mn][^u]
PFX FP l zemutaann l.[mn]
PFX FP w zemutaamp [w]
PFX FP 0 zemutaamu .
PFX FP 0 zemutaaba .
PFX FP 0 zemutaagu .
PFX FP 0 zemutaagi .
PFX FP 0 zemutaazi .
PFX FP 0 zemutaaki .
PFX FP 0 zemutaabi .
PFX FP 0 zemutaali .
PFX FP 0 zemutaaga .
PFX FP 0 zemutaaka .
PFX FP 0 zemutaabu .
PFX FP 0 zemutaalu .
PFX FP 0 zemutaaku .
PFX FP 0 zemutaatu .
PFX FP 0 zebataan [^lmnb]
PFX FP l zebataand l.[^mn][^u]
PFX FP l zebataann l.[mn]
PFX FP w zebataamp [w]
PFX FP 0 zebataamu .
PFX FP 0 zebataaba .
PFX FP 0 zebataagu .
PFX FP 0 zebataagi .
PFX FP 0 zebataazi .
PFX FP 0 zebataaki .
PFX FP 0 zebataabi .
PFX FP 0 zebataali .
PFX FP 0 zebataaga .
PFX FP 0 zebataaka .
PFX FP 0 zebataabu .
PFX FP 0 zebataalu .
PFX FP 0 zebataaku .
PFX FP 0 zebataatu .
PFX FP 0 zegutaan [^lmnb]
PFX FP l zegutaand l.[^mn][^u]
PFX FP l zegutaann l.[mn]
PFX FP w zegutaamp [w]
PFX FP 0 zegutaamu .
PFX FP 0 zegutaaba .
PFX FP 0 zegutaagu .
PFX FP 0 zegutaagi .
PFX FP 0 zegutaazi .
PFX FP 0 zegutaaki .
PFX FP 0 zegutaabi .
PFX FP 0 zegutaali .
PFX FP 0 zegutaaga .
PFX FP 0 zegutaaka .
PFX FP 0 zegutaabu .
PFX FP 0 zegutaalu .
PFX FP 0 zegutaaku .
PFX FP 0 zegutaatu .
PFX FP 0 zegitaan [^lmnb]
PFX FP l zegitaand l.[^mn][^u]
PFX FP l zegitaann l.[mn]
PFX FP w zegitaamp [w]
PFX FP 0 zegitaamu .
PFX FP 0 zegitaaba .
PFX FP 0 zegitaagu .
PFX FP 0 zegitaagi .
PFX FP 0 zegitaazi .
PFX FP 0 zegitaaki .
PFX FP 0 zegitaabi .
PFX FP 0 zegitaali .
PFX FP 0 zegitaaga .
PFX FP 0 zegitaaka .
PFX FP 0 zegitaabu .
PFX FP 0 zegitaalu .
PFX FP 0 zegitaaku .
PFX FP 0 zegitaatu .
PFX FP 0 zezitaan [^lmnb]
PFX FP l zezitaand l.[^mn][^u]
PFX FP l zezitaann l.[mn]
PFX FP w zezitaamp [w]
PFX FP 0 zezitaamu .
PFX FP 0 zezitaaba .
PFX FP 0 zezitaagu .
PFX FP 0 zezitaagi .
PFX FP 0 zezitaazi .
PFX FP 0 zezitaaki .
PFX FP 0 zezitaabi .
PFX FP 0 zezitaali .
PFX FP 0 zezitaaga .
PFX FP 0 zezitaaka .
PFX FP 0 zezitaabu .
PFX FP 0 zezitaalu .
PFX FP 0 zezitaaku .
PFX FP 0 zezitaatu .
PFX FP 0 zekitaan [^lmnb]
PFX FP l zekitaand l.[^mn][^u]
PFX FP l zekitaann l.[mn]
PFX FP w zekitaamp [w]
PFX FP 0 zekitaamu .
PFX FP 0 zekitaaba .
PFX FP 0 zekitaagu .
PFX FP 0 zekitaagi .
PFX FP 0 zekitaazi .
PFX FP 0 zekitaaki .
PFX FP 0 zekitaabi .
PFX FP 0 zekitaali .
PFX FP 0 zekitaaga .
PFX FP 0 zekitaaka .
PFX FP 0 zekitaabu .
PFX FP 0 zekitaalu .
PFX FP 0 zekitaaku .
PFX FP 0 zekitaatu .
PFX FP 0 zebitaan [^lmnb]
PFX FP l zebitaand l.[^mn][^u]
PFX FP l zebitaann l.[mn]
PFX FP w zebitaamp [w]
PFX FP 0 zebitaamu .
PFX FP 0 zebitaaba .
PFX FP 0 zebitaagu .
PFX FP 0 zebitaagi .
PFX FP 0 zebitaazi .
PFX FP 0 zebitaaki .
PFX FP 0 zebitaabi .
PFX FP 0 zebitaali .
PFX FP 0 zebitaaga .
PFX FP 0 zebitaaka .
PFX FP 0 zebitaabu .
PFX FP 0 zebitaalu .
PFX FP 0 zebitaaku .
PFX FP 0 zebitaatu .
PFX FP 0 zelitaan [^lmnb]
PFX FP l zelitaand l.[^mn][^u]
PFX FP l zelitaann l.[mn]
PFX FP w zelitaamp [w]
PFX FP 0 zelitaamu .
PFX FP 0 zelitaaba .
PFX FP 0 zelitaagu .
PFX FP 0 zelitaagi .
PFX FP 0 zelitaazi .
PFX FP 0 zelitaaki .
PFX FP 0 zelitaabi .
PFX FP 0 zelitaali .
PFX FP 0 zelitaaga .
PFX FP 0 zelitaaka .
PFX FP 0 zelitaabu .
PFX FP 0 zelitaalu .
PFX FP 0 zelitaaku .
PFX FP 0 zelitaatu .
PFX FP 0 zegataan [^lmnb]
PFX FP l zegataand l.[^mn][^u]
PFX FP l zegataann l.[mn]
PFX FP w zegataamp [w]
PFX FP 0 zegataamu .
PFX FP 0 zegataaba .
PFX FP 0 zegataagu .
PFX FP 0 zegataagi .
PFX FP 0 zegataazi .
PFX FP 0 zegataaki .
PFX FP 0 zegataabi .
PFX FP 0 zegataali .
PFX FP 0 zegataaga .
PFX FP 0 zegataaka .
PFX FP 0 zegataabu .
PFX FP 0 zegataalu .
PFX FP 0 zegataaku .
PFX FP 0 zegataatu .
PFX FP 0 zekataan [^lmnb]
PFX FP l zekataand l.[^mn][^u]
PFX FP l zekataann l.[mn]
PFX FP w zekataamp [w]
PFX FP 0 zekataamu .
PFX FP 0 zekataaba .
PFX FP 0 zekataagu .
PFX FP 0 zekataagi .
PFX FP 0 zekataazi .
PFX FP 0 zekataaki .
PFX FP 0 zekataabi .
PFX FP 0 zekataali .
PFX FP 0 zekataaga .
PFX FP 0 zekataaka .
PFX FP 0 zekataabu .
PFX FP 0 zekataalu .
PFX FP 0 zekataaku .
PFX FP 0 zekataatu .
PFX FP 0 zebutaan [^lmnb]
PFX FP l zebutaand l.[^mn][^u]
PFX FP l zebutaann l.[mn]
PFX FP w zebutaamp [w]
PFX FP 0 zebutaamu .
PFX FP 0 zebutaaba .
PFX FP 0 zebutaagu .
PFX FP 0 zebutaagi .
PFX FP 0 zebutaazi .
PFX FP 0 zebutaaki .
PFX FP 0 zebutaabi .
PFX FP 0 zebutaali .
PFX FP 0 zebutaaga .
PFX FP 0 zebutaaka .
PFX FP 0 zebutaabu .
PFX FP 0 zebutaalu .
PFX FP 0 zebutaaku .
PFX FP 0 zebutaatu .
PFX FP 0 zelutaan [^lmnb]
PFX FP l zelutaand l.[^mn][^u]
PFX FP l zelutaann l.[mn]
PFX FP w zelutaamp [w]
PFX FP 0 zelutaamu .
PFX FP 0 zelutaaba .
PFX FP 0 zelutaagu .
PFX FP 0 zelutaagi .
PFX FP 0 zelutaazi .
PFX FP 0 zelutaaki .
PFX FP 0 zelutaabi .
PFX FP 0 zelutaali .
PFX FP 0 zelutaaga .
PFX FP 0 zelutaaka .
PFX FP 0 zelutaabu .
PFX FP 0 zelutaalu .
PFX FP 0 zelutaaku .
PFX FP 0 zelutaatu .
PFX FP 0 zekutaan [^lmnb]
PFX FP l zekutaand l.[^mn][^u]
PFX FP l zekutaann l.[mn]
PFX FP w zekutaamp [w]
PFX FP 0 zekutaamu .
PFX FP 0 zekutaaba .
PFX FP 0 zekutaagu .
PFX FP 0 zekutaagi .
PFX FP 0 zekutaazi .
PFX FP 0 zekutaaki .
PFX FP 0 zekutaabi .
PFX FP 0 zekutaali .
PFX FP 0 zekutaaga .
PFX FP 0 zekutaaka .
PFX FP 0 zekutaabu .
PFX FP 0 zekutaalu .
PFX FP 0 zekutaaku .
PFX FP 0 zekutaatu .
PFX FP 0 zetutaan [^lmnb]
PFX FP l zetutaand l.[^mn][^u]
PFX FP l zetutaann l.[mn]
PFX FP w zetutaamp [w]
PFX FP 0 zetutaamu .
PFX FP 0 zetutaaba .
PFX FP 0 zetutaagu .
PFX FP 0 zetutaagi .
PFX FP 0 zetutaazi .
PFX FP 0 zetutaaki .
PFX FP 0 zetutaabi .
PFX FP 0 zetutaali .
PFX FP 0 zetutaaga .
PFX FP 0 zetutaaka .
PFX FP 0 zetutaabu .
PFX FP 0 zetutaalu .
PFX FP 0 zetutaaku .
PFX FP 0 zetutaatu .
PFX FP 0 gw'otoon [^lmnb]
PFX FP l gw'otoond l.[^mn][^u]
PFX FP l gw'otoonn l.[mn]
PFX FP w gw'otoomp [w]
PFX FP 0 gw'otoomu .
PFX FP 0 gw'otooba .
PFX FP 0 gw'otoogu .
PFX FP 0 gw'otoogi .
PFX FP 0 gw'otoozi .
PFX FP 0 gw'otooki .
PFX FP 0 gw'otoobi .
PFX FP 0 gw'otooli .
PFX FP 0 gw'otooga .
PFX FP 0 gw'otooka .
PFX FP 0 gw'otoobu .
PFX FP 0 gw'otoolu .
PFX FP 0 gw'otooku .
PFX FP 0 gw'otootu .
PFX FP 0 gw'ataan [^lmnb]
PFX FP l gw'ataand l.[^mn][^u]
PFX FP l gw'ataann l.[mn]
PFX FP w gw'ataamp [w]
PFX FP 0 gw'ataamu .
PFX FP 0 gw'ataaba .
PFX FP 0 gw'ataagu .
PFX FP 0 gw'ataagi .
PFX FP 0 gw'ataazi .
PFX FP 0 gw'ataaki .
PFX FP 0 gw'ataabi .
PFX FP 0 gw'ataali .
PFX FP 0 gw'ataaga .
PFX FP 0 gw'ataaka .
PFX FP 0 gw'ataabu .
PFX FP 0 gw'ataalu .
PFX FP 0 gw'ataaku .
PFX FP 0 gw'ataatu .
PFX FP 0 gw'etaan [^lmnb]
PFX FP l gw'etaand l.[^mn][^u]
PFX FP l gw'etaann l.[mn]
PFX FP w gw'etaamp [w]
PFX FP 0 gw'etaamu .
PFX FP 0 gw'etaaba .
PFX FP 0 gw'etaagu .
PFX FP 0 gw'etaagi .
PFX FP 0 gw'etaazi .
PFX FP 0 gw'etaaki .
PFX FP 0 gw'etaabi .
PFX FP 0 gw'etaali .
PFX FP 0 gw'etaaga .
PFX FP 0 gw'etaaka .
PFX FP 0 gw'etaabu .
PFX FP 0 gw'etaalu .
PFX FP 0 gw'etaaku .
PFX FP 0 gw'etaatu .
PFX FP 0 gwessiiba .
PFX FP 0 gwessiigu .
PFX FP 0 gwessiigi .
PFX FP 0 gwessiizi .
PFX FP 0 gwessiiki .
PFX FP 0 gwessiibi .
PFX FP 0 gwessiili .
PFX FP 0 gwessiiga .
PFX FP 0 gwessiika .
PFX FP 0 gwessiibu .
PFX FP 0 gwessiilu .
PFX FP 0 gwessiiku .
PFX FP 0 gwessiitu .
PFX FP 0 gwessiimu .
PFX FP 0 gwetutaan [^lmnb]
PFX FP l gwetutaand l.[^mn][^u]
PFX FP l gwetutaann l.[mn]
PFX FP w gwetutaamp [w]
PFX FP 0 gwetutaamu .
PFX FP 0 gwetutaaba .
PFX FP 0 gwetutaagu .
PFX FP 0 gwetutaagi .
PFX FP 0 gwetutaazi .
PFX FP 0 gwetutaaki .
PFX FP 0 gwetutaabi .
PFX FP 0 gwetutaali .
PFX FP 0 gwetutaaga .
PFX FP 0 gwetutaaka .
PFX FP 0 gwetutaabu .
PFX FP 0 gwetutaalu .
PFX FP 0 gwetutaaku .
PFX FP 0 gwetutaatu .
PFX FP 0 gwemutaan [^lmnb]
PFX FP l gwemutaand l.[^mn][^u]
PFX FP l gwemutaann l.[mn]
PFX FP w gwemutaamp [w]
PFX FP 0 gwemutaamu .
PFX FP 0 gwemutaaba .
PFX FP 0 gwemutaagu .
PFX FP 0 gwemutaagi .
PFX FP 0 gwemutaazi .
PFX FP 0 gwemutaaki .
PFX FP 0 gwemutaabi .
PFX FP 0 gwemutaali .
PFX FP 0 gwemutaaga .
PFX FP 0 gwemutaaka .
PFX FP 0 gwemutaabu .
PFX FP 0 gwemutaalu .
PFX FP 0 gwemutaaku .
PFX FP 0 gwemutaatu .
PFX FP 0 gwebataan [^lmnb]
PFX FP l gwebataand l.[^mn][^u]
PFX FP l gwebataann l.[mn]
PFX FP w gwebataamp [w]
PFX FP 0 gwebataamu .
PFX FP 0 gwebataaba .
PFX FP 0 gwebataagu .
PFX FP 0 gwebataagi .
PFX FP 0 gwebataazi .
PFX FP 0 gwebataaki .
PFX FP 0 gwebataabi .
PFX FP 0 gwebataali .
PFX FP 0 gwebataaga .
PFX FP 0 gwebataaka .
PFX FP 0 gwebataabu .
PFX FP 0 gwebataalu .
PFX FP 0 gwebataaku .
PFX FP 0 gwebataatu .
PFX FP 0 gwegutaan [^lmnb]
PFX FP l gwegutaand l.[^mn][^u]
PFX FP l gwegutaann l.[mn]
PFX FP w gwegutaamp [w]
PFX FP 0 gwegutaamu .
PFX FP 0 gwegutaaba .
PFX FP 0 gwegutaagu .
PFX FP 0 gwegutaagi .
PFX FP 0 gwegutaazi .
PFX FP 0 gwegutaaki .
PFX FP 0 gwegutaabi .
PFX FP 0 gwegutaali .
PFX FP 0 gwegutaaga .
PFX FP 0 gwegutaaka .
PFX FP 0 gwegutaabu .
PFX FP 0 gwegutaalu .
PFX FP 0 gwegutaaku .
PFX FP 0 gwegutaatu .
PFX FP 0 gwegitaan [^lmnb]
PFX FP l gwegitaand l.[^mn][^u]
PFX FP l gwegitaann l.[mn]
PFX FP w gwegitaamp [w]
PFX FP 0 gwegitaamu .
PFX FP 0 gwegitaaba .
PFX FP 0 gwegitaagu .
PFX FP 0 gwegitaagi .
PFX FP 0 gwegitaazi .
PFX FP 0 gwegitaaki .
PFX FP 0 gwegitaabi .
PFX FP 0 gwegitaali .
PFX FP 0 gwegitaaga .
PFX FP 0 gwegitaaka .
PFX FP 0 gwegitaabu .
PFX FP 0 gwegitaalu .
PFX FP 0 gwegitaaku .
PFX FP 0 gwegitaatu .
PFX FP 0 gwezitaan [^lmnb]
PFX FP l gwezitaand l.[^mn][^u]
PFX FP l gwezitaann l.[mn]
PFX FP w gwezitaamp [w]
PFX FP 0 gwezitaamu .
PFX FP 0 gwezitaaba .
PFX FP 0 gwezitaagu .
PFX FP 0 gwezitaagi .
PFX FP 0 gwezitaazi .
PFX FP 0 gwezitaaki .
PFX FP 0 gwezitaabi .
PFX FP 0 gwezitaali .
PFX FP 0 gwezitaaga .
PFX FP 0 gwezitaaka .
PFX FP 0 gwezitaabu .
PFX FP 0 gwezitaalu .
PFX FP 0 gwezitaaku .
PFX FP 0 gwezitaatu .
PFX FP 0 gwekitaan [^lmnb]
PFX FP l gwekitaand l.[^mn][^u]
PFX FP l gwekitaann l.[mn]
PFX FP w gwekitaamp [w]
PFX FP 0 gwekitaamu .
PFX FP 0 gwekitaaba .
PFX FP 0 gwekitaagu .
PFX FP 0 gwekitaagi .
PFX FP 0 gwekitaazi .
PFX FP 0 gwekitaaki .
PFX FP 0 gwekitaabi .
PFX FP 0 gwekitaali .
PFX FP 0 gwekitaaga .
PFX FP 0 gwekitaaka .
PFX FP 0 gwekitaabu .
PFX FP 0 gwekitaalu .
PFX FP 0 gwekitaaku .
PFX FP 0 gwekitaatu .
PFX FP 0 gwebitaan [^lmnb]
PFX FP l gwebitaand l.[^mn][^u]
PFX FP l gwebitaann l.[mn]
PFX FP w gwebitaamp [w]
PFX FP 0 gwebitaamu .
PFX FP 0 gwebitaaba .
PFX FP 0 gwebitaagu .
PFX FP 0 gwebitaagi .
PFX FP 0 gwebitaazi .
PFX FP 0 gwebitaaki .
PFX FP 0 gwebitaabi .
PFX FP 0 gwebitaali .
PFX FP 0 gwebitaaga .
PFX FP 0 gwebitaaka .
PFX FP 0 gwebitaabu .
PFX FP 0 gwebitaalu .
PFX FP 0 gwebitaaku .
PFX FP 0 gwebitaatu .
PFX FP 0 gwelitaan [^lmnb]
PFX FP l gwelitaand l.[^mn][^u]
PFX FP l gwelitaann l.[mn]
PFX FP w gwelitaamp [w]
PFX FP 0 gwelitaamu .
PFX FP 0 gwelitaaba .
PFX FP 0 gwelitaagu .
PFX FP 0 gwelitaagi .
PFX FP 0 gwelitaazi .
PFX FP 0 gwelitaaki .
PFX FP 0 gwelitaabi .
PFX FP 0 gwelitaali .
PFX FP 0 gwelitaaga .
PFX FP 0 gwelitaaka .
PFX FP 0 gwelitaabu .
PFX FP 0 gwelitaalu .
PFX FP 0 gwelitaaku .
PFX FP 0 gwelitaatu .
PFX FP 0 gwegataan [^lmnb]
PFX FP l gwegataand l.[^mn][^u]
PFX FP l gwegataann l.[mn]
PFX FP w gwegataamp [w]
PFX FP 0 gwegataamu .
PFX FP 0 gwegataaba .
PFX FP 0 gwegataagu .
PFX FP 0 gwegataagi .
PFX FP 0 gwegataazi .
PFX FP 0 gwegataaki .
PFX FP 0 gwegataabi .
PFX FP 0 gwegataali .
PFX FP 0 gwegataaga .
PFX FP 0 gwegataaka .
PFX FP 0 gwegataabu .
PFX FP 0 gwegataalu .
PFX FP 0 gwegataaku .
PFX FP 0 gwegataatu .
PFX FP 0 gwekataan [^lmnb]
PFX FP l gwekataand l.[^mn][^u]
PFX FP l gwekataann l.[mn]
PFX FP w gwekataamp [w]
PFX FP 0 gwekataamu .
PFX FP 0 gwekataaba .
PFX FP 0 gwekataagu .
PFX FP 0 gwekataagi .
PFX FP 0 gwekataazi .
PFX FP 0 gwekataaki .
PFX FP 0 gwekataabi .
PFX FP 0 gwekataali .
PFX FP 0 gwekataaga .
PFX FP 0 gwekataaka .
PFX FP 0 gwekataabu .
PFX FP 0 gwekataalu .
PFX FP 0 gwekataaku .
PFX FP 0 gwekataatu .
PFX FP 0 gwebutaan [^lmnb]
PFX FP l gwebutaand l.[^mn][^u]
PFX FP l gwebutaann l.[mn]
PFX FP w gwebutaamp [w]
PFX FP 0 gwebutaamu .
PFX FP 0 gwebutaaba .
PFX FP 0 gwebutaagu .
PFX FP 0 gwebutaagi .
PFX FP 0 gwebutaazi .
PFX FP 0 gwebutaaki .
PFX FP 0 gwebutaabi .
PFX FP 0 gwebutaali .
PFX FP 0 gwebutaaga .
PFX FP 0 gwebutaaka .
PFX FP 0 gwebutaabu .
PFX FP 0 gwebutaalu .
PFX FP 0 gwebutaaku .
PFX FP 0 gwebutaatu .
PFX FP 0 gwelutaan [^lmnb]
PFX FP l gwelutaand l.[^mn][^u]
PFX FP l gwelutaann l.[mn]
PFX FP w gwelutaamp [w]
PFX FP 0 gwelutaamu .
PFX FP 0 gwelutaaba .
PFX FP 0 gwelutaagu .
PFX FP 0 gwelutaagi .
PFX FP 0 gwelutaazi .
PFX FP 0 gwelutaaki .
PFX FP 0 gwelutaabi .
PFX FP 0 gwelutaali .
PFX FP 0 gwelutaaga .
PFX FP 0 gwelutaaka .
PFX FP 0 gwelutaabu .
PFX FP 0 gwelutaalu .
PFX FP 0 gwelutaaku .
PFX FP 0 gwelutaatu .
PFX FP 0 gwekutaan [^lmnb]
PFX FP l gwekutaand l.[^mn][^u]
PFX FP l gwekutaann l.[mn]
PFX FP w gwekutaamp [w]
PFX FP 0 gwekutaamu .
PFX FP 0 gwekutaaba .
PFX FP 0 gwekutaagu .
PFX FP 0 gwekutaagi .
PFX FP 0 gwekutaazi .
PFX FP 0 gwekutaaki .
PFX FP 0 gwekutaabi .
PFX FP 0 gwekutaali .
PFX FP 0 gwekutaaga .
PFX FP 0 gwekutaaka .
PFX FP 0 gwekutaabu .
PFX FP 0 gwekutaalu .
PFX FP 0 gwekutaaku .
PFX FP 0 gwekutaatu .
PFX FP 0 gwetutaan [^lmnb]
PFX FP l gwetutaand l.[^mn][^u]
PFX FP l gwetutaann l.[mn]
PFX FP w gwetutaamp [w]
PFX FP 0 gwetutaamu .
PFX FP 0 gwetutaaba .
PFX FP 0 gwetutaagu .
PFX FP 0 gwetutaagi .
PFX FP 0 gwetutaazi .
PFX FP 0 gwetutaaki .
PFX FP 0 gwetutaabi .
PFX FP 0 gwetutaali .
PFX FP 0 gwetutaaga .
PFX FP 0 gwetutaaka .
PFX FP 0 gwetutaabu .
PFX FP 0 gwetutaalu .
PFX FP 0 gwetutaaku .
PFX FP 0 gwetutaatu .
PFX FP 0 gy'otoon [^lmnb]
PFX FP l gy'otoond l.[^mn][^u]
PFX FP l gy'otoonn l.[mn]
PFX FP w gy'otoomp [w]
PFX FP 0 gy'otoomu .
PFX FP 0 gy'otooba .
PFX FP 0 gy'otoogu .
PFX FP 0 gy'otoogi .
PFX FP 0 gy'otoozi .
PFX FP 0 gy'otooki .
PFX FP 0 gy'otoobi .
PFX FP 0 gy'otooli .
PFX FP 0 gy'otooga .
PFX FP 0 gy'otooka .
PFX FP 0 gy'otoobu .
PFX FP 0 gy'otoolu .
PFX FP 0 gy'otooku .
PFX FP 0 gy'otootu .
PFX FP 0 gy'ataan [^lmnb]
PFX FP l gy'ataand l.[^mn][^u]
PFX FP l gy'ataann l.[mn]
PFX FP w gy'ataamp [w]
PFX FP 0 gy'ataamu .
PFX FP 0 gy'ataaba .
PFX FP 0 gy'ataagu .
PFX FP 0 gy'ataagi .
PFX FP 0 gy'ataazi .
PFX FP 0 gy'ataaki .
PFX FP 0 gy'ataabi .
PFX FP 0 gy'ataali .
PFX FP 0 gy'ataaga .
PFX FP 0 gy'ataaka .
PFX FP 0 gy'ataabu .
PFX FP 0 gy'ataalu .
PFX FP 0 gy'ataaku .
PFX FP 0 gy'ataatu .
PFX FP 0 gy'etaan [^lmnb]
PFX FP l gy'etaand l.[^mn][^u]
PFX FP l gy'etaann l.[mn]
PFX FP w gy'etaamp [w]
PFX FP 0 gy'etaamu .
PFX FP 0 gy'etaaba .
PFX FP 0 gy'etaagu .
PFX FP 0 gy'etaagi .
PFX FP 0 gy'etaazi .
PFX FP 0 gy'etaaki .
PFX FP 0 gy'etaabi .
PFX FP 0 gy'etaali .
PFX FP 0 gy'etaaga .
PFX FP 0 gy'etaaka .
PFX FP 0 gy'etaabu .
PFX FP 0 gy'etaalu .
PFX FP 0 gy'etaaku .
PFX FP 0 gy'etaatu .
PFX FP 0 gyessiiba .
PFX FP 0 gyessiigu .
PFX FP 0 gyessiigi .
PFX FP 0 gyessiizi .
PFX FP 0 gyessiiki .
PFX FP 0 gyessiibi .
PFX FP 0 gyessiili .
PFX FP 0 gyessiiga .
PFX FP 0 gyessiika .
PFX FP 0 gyessiibu .
PFX FP 0 gyessiilu .
PFX FP 0 gyessiiku .
PFX FP 0 gyessiitu .
PFX FP 0 gyessiimu .
PFX FP 0 gyetutaan [^lmnb]
PFX FP l gyetutaand l.[^mn][^u]
PFX FP l gyetutaann l.[mn]
PFX FP w gyetutaamp [w]
PFX FP 0 gyetutaamu .
PFX FP 0 gyetutaaba .
PFX FP 0 gyetutaagu .
PFX FP 0 gyetutaagi .
PFX FP 0 gyetutaazi .
PFX FP 0 gyetutaaki .
PFX FP 0 gyetutaabi .
PFX FP 0 gyetutaali .
PFX FP 0 gyetutaaga .
PFX FP 0 gyetutaaka .
PFX FP 0 gyetutaabu .
PFX FP 0 gyetutaalu .
PFX FP 0 gyetutaaku .
PFX FP 0 gyetutaatu .
PFX FP 0 gyemutaan [^lmnb]
PFX FP l gyemutaand l.[^mn][^u]
PFX FP l gyemutaann l.[mn]
PFX FP w gyemutaamp [w]
PFX FP 0 gyemutaamu .
PFX FP 0 gyemutaaba .
PFX FP 0 gyemutaagu .
PFX FP 0 gyemutaagi .
PFX FP 0 gyemutaazi .
PFX FP 0 gyemutaaki .
PFX FP 0 gyemutaabi .
PFX FP 0 gyemutaali .
PFX FP 0 gyemutaaga .
PFX FP 0 gyemutaaka .
PFX FP 0 gyemutaabu .
PFX FP 0 gyemutaalu .
PFX FP 0 gyemutaaku .
PFX FP 0 gyemutaatu .
PFX FP 0 gyebataan [^lmnb]
PFX FP l gyebataand l.[^mn][^u]
PFX FP l gyebataann l.[mn]
PFX FP w gyebataamp [w]
PFX FP 0 gyebataamu .
PFX FP 0 gyebataaba .
PFX FP 0 gyebataagu .
PFX FP 0 gyebataagi .
PFX FP 0 gyebataazi .
PFX FP 0 gyebataaki .
PFX FP 0 gyebataabi .
PFX FP 0 gyebataali .
PFX FP 0 gyebataaga .
PFX FP 0 gyebataaka .
PFX FP 0 gyebataabu .
PFX FP 0 gyebataalu .
PFX FP 0 gyebataaku .
PFX FP 0 gyebataatu .
PFX FP 0 gyegutaan [^lmnb]
PFX FP l gyegutaand l.[^mn][^u]
PFX FP l gyegutaann l.[mn]
PFX FP w gyegutaamp [w]
PFX FP 0 gyegutaamu .
PFX FP 0 gyegutaaba .
PFX FP 0 gyegutaagu .
PFX FP 0 gyegutaagi .
PFX FP 0 gyegutaazi .
PFX FP 0 gyegutaaki .
PFX FP 0 gyegutaabi .
PFX FP 0 gyegutaali .
PFX FP 0 gyegutaaga .
PFX FP 0 gyegutaaka .
PFX FP 0 gyegutaabu .
PFX FP 0 gyegutaalu .
PFX FP 0 gyegutaaku .
PFX FP 0 gyegutaatu .
PFX FP 0 gyegitaan [^lmnb]
PFX FP l gyegitaand l.[^mn][^u]
PFX FP l gyegitaann l.[mn]
PFX FP w gyegitaamp [w]
PFX FP 0 gyegitaamu .
PFX FP 0 gyegitaaba .
PFX FP 0 gyegitaagu .
PFX FP 0 gyegitaagi .
PFX FP 0 gyegitaazi .
PFX FP 0 gyegitaaki .
PFX FP 0 gyegitaabi .
PFX FP 0 gyegitaali .
PFX FP 0 gyegitaaga .
PFX FP 0 gyegitaaka .
PFX FP 0 gyegitaabu .
PFX FP 0 gyegitaalu .
PFX FP 0 gyegitaaku .
PFX FP 0 gyegitaatu .
PFX FP 0 gyezitaan [^lmnb]
PFX FP l gyezitaand l.[^mn][^u]
PFX FP l gyezitaann l.[mn]
PFX FP w gyezitaamp [w]
PFX FP 0 gyezitaamu .
PFX FP 0 gyezitaaba .
PFX FP 0 gyezitaagu .
PFX FP 0 gyezitaagi .
PFX FP 0 gyezitaazi .
PFX FP 0 gyezitaaki .
PFX FP 0 gyezitaabi .
PFX FP 0 gyezitaali .
PFX FP 0 gyezitaaga .
PFX FP 0 gyezitaaka .
PFX FP 0 gyezitaabu .
PFX FP 0 gyezitaalu .
PFX FP 0 gyezitaaku .
PFX FP 0 gyezitaatu .
PFX FP 0 gyekitaan [^lmnb]
PFX FP l gyekitaand l.[^mn][^u]
PFX FP l gyekitaann l.[mn]
PFX FP w gyekitaamp [w]
PFX FP 0 gyekitaamu .
PFX FP 0 gyekitaaba .
PFX FP 0 gyekitaagu .
PFX FP 0 gyekitaagi .
PFX FP 0 gyekitaazi .
PFX FP 0 gyekitaaki .
PFX FP 0 gyekitaabi .
PFX FP 0 gyekitaali .
PFX FP 0 gyekitaaga .
PFX FP 0 gyekitaaka .
PFX FP 0 gyekitaabu .
PFX FP 0 gyekitaalu .
PFX FP 0 gyekitaaku .
PFX FP 0 gyekitaatu .
PFX FP 0 gyebitaan [^lmnb]
PFX FP l gyebitaand l.[^mn][^u]
PFX FP l gyebitaann l.[mn]
PFX FP w gyebitaamp [w]
PFX FP 0 gyebitaamu .
PFX FP 0 gyebitaaba .
PFX FP 0 gyebitaagu .
PFX FP 0 gyebitaagi .
PFX FP 0 gyebitaazi .
PFX FP 0 gyebitaaki .
PFX FP 0 gyebitaabi .
PFX FP 0 gyebitaali .
PFX FP 0 gyebitaaga .
PFX FP 0 gyebitaaka .
PFX FP 0 gyebitaabu .
PFX FP 0 gyebitaalu .
PFX FP 0 gyebitaaku .
PFX FP 0 gyebitaatu .
PFX FP 0 gyelitaan [^lmnb]
PFX FP l gyelitaand l.[^mn][^u]
PFX FP l gyelitaann l.[mn]
PFX FP w gyelitaamp [w]
PFX FP 0 gyelitaamu .
PFX FP 0 gyelitaaba .
PFX FP 0 gyelitaagu .
PFX FP 0 gyelitaagi .
PFX FP 0 gyelitaazi .
PFX FP 0 gyelitaaki .
PFX FP 0 gyelitaabi .
PFX FP 0 gyelitaali .
PFX FP 0 gyelitaaga .
PFX FP 0 gyelitaaka .
PFX FP 0 gyelitaabu .
PFX FP 0 gyelitaalu .
PFX FP 0 gyelitaaku .
PFX FP 0 gyelitaatu .
PFX FP 0 gyegataan [^lmnb]
PFX FP l gyegataand l.[^mn][^u]
PFX FP l gyegataann l.[mn]
PFX FP w gyegataamp [w]
PFX FP 0 gyegataamu .
PFX FP 0 gyegataaba .
PFX FP 0 gyegataagu .
PFX FP 0 gyegataagi .
PFX FP 0 gyegataazi .
PFX FP 0 gyegataaki .
PFX FP 0 gyegataabi .
PFX FP 0 gyegataali .
PFX FP 0 gyegataaga .
PFX FP 0 gyegataaka .
PFX FP 0 gyegataabu .
PFX FP 0 gyegataalu .
PFX FP 0 gyegataaku .
PFX FP 0 gyegataatu .
PFX FP 0 gyekataan [^lmnb]
PFX FP l gyekataand l.[^mn][^u]
PFX FP l gyekataann l.[mn]
PFX FP w gyekataamp [w]
PFX FP 0 gyekataamu .
PFX FP 0 gyekataaba .
PFX FP 0 gyekataagu .
PFX FP 0 gyekataagi .
PFX FP 0 gyekataazi .
PFX FP 0 gyekataaki .
PFX FP 0 gyekataabi .
PFX FP 0 gyekataali .
PFX FP 0 gyekataaga .
PFX FP 0 gyekataaka .
PFX FP 0 gyekataabu .
PFX FP 0 gyekataalu .
PFX FP 0 gyekataaku .
PFX FP 0 gyekataatu .
PFX FP 0 gyebutaan [^lmnb]
PFX FP l gyebutaand l.[^mn][^u]
PFX FP l gyebutaann l.[mn]
PFX FP w gyebutaamp [w]
PFX FP 0 gyebutaamu .
PFX FP 0 gyebutaaba .
PFX FP 0 gyebutaagu .
PFX FP 0 gyebutaagi .
PFX FP 0 gyebutaazi .
PFX FP 0 gyebutaaki .
PFX FP 0 gyebutaabi .
PFX FP 0 gyebutaali .
PFX FP 0 gyebutaaga .
PFX FP 0 gyebutaaka .
PFX FP 0 gyebutaabu .
PFX FP 0 gyebutaalu .
PFX FP 0 gyebutaaku .
PFX FP 0 gyebutaatu .
PFX FP 0 gyelutaan [^lmnb]
PFX FP l gyelutaand l.[^mn][^u]
PFX FP l gyelutaann l.[mn]
PFX FP w gyelutaamp [w]
PFX FP 0 gyelutaamu .
PFX FP 0 gyelutaaba .
PFX FP 0 gyelutaagu .
PFX FP 0 gyelutaagi .
PFX FP 0 gyelutaazi .
PFX FP 0 gyelutaaki .
PFX FP 0 gyelutaabi .
PFX FP 0 gyelutaali .
PFX FP 0 gyelutaaga .
PFX FP 0 gyelutaaka .
PFX FP 0 gyelutaabu .
PFX FP 0 gyelutaalu .
PFX FP 0 gyelutaaku .
PFX FP 0 gyelutaatu .
PFX FP 0 gyekutaan [^lmnb]
PFX FP l gyekutaand l.[^mn][^u]
PFX FP l gyekutaann l.[mn]
PFX FP w gyekutaamp [w]
PFX FP 0 gyekutaamu .
PFX FP 0 gyekutaaba .
PFX FP 0 gyekutaagu .
PFX FP 0 gyekutaagi .
PFX FP 0 gyekutaazi .
PFX FP 0 gyekutaaki .
PFX FP 0 gyekutaabi .
PFX FP 0 gyekutaali .
PFX FP 0 gyekutaaga .
PFX FP 0 gyekutaaka .
PFX FP 0 gyekutaabu .
PFX FP 0 gyekutaalu .
PFX FP 0 gyekutaaku .
PFX FP 0 gyekutaatu .
PFX FP 0 gyetutaan [^lmnb]
PFX FP l gyetutaand l.[^mn][^u]
PFX FP l gyetutaann l.[mn]
PFX FP w gyetutaamp [w]
PFX FP 0 gyetutaamu .
PFX FP 0 gyetutaaba .
PFX FP 0 gyetutaagu .
PFX FP 0 gyetutaagi .
PFX FP 0 gyetutaazi .
PFX FP 0 gyetutaaki .
PFX FP 0 gyetutaabi .
PFX FP 0 gyetutaali .
PFX FP 0 gyetutaaga .
PFX FP 0 gyetutaaka .
PFX FP 0 gyetutaabu .
PFX FP 0 gyetutaalu .
PFX FP 0 gyetutaaku .
PFX FP 0 gyetutaatu .
PFX FP 0 ky'otoon [^lmnb]
PFX FP l ky'otoond l.[^mn][^u]
PFX FP l ky'otoonn l.[mn]
PFX FP w ky'otoomp [w]
PFX FP 0 ky'otoomu .
PFX FP 0 ky'otooba .
PFX FP 0 ky'otoogu .
PFX FP 0 ky'otoogi .
PFX FP 0 ky'otoozi .
PFX FP 0 ky'otooki .
PFX FP 0 ky'otoobi .
PFX FP 0 ky'otooli .
PFX FP 0 ky'otooga .
PFX FP 0 ky'otooka .
PFX FP 0 ky'otoobu .
PFX FP 0 ky'otoolu .
PFX FP 0 ky'otooku .
PFX FP 0 ky'otootu .
PFX FP 0 ky'ataan [^lmnb]
PFX FP l ky'ataand l.[^mn][^u]
PFX FP l ky'ataann l.[mn]
PFX FP w ky'ataamp [w]
PFX FP 0 ky'ataamu .
PFX FP 0 ky'ataaba .
PFX FP 0 ky'ataagu .
PFX FP 0 ky'ataagi .
PFX FP 0 ky'ataazi .
PFX FP 0 ky'ataaki .
PFX FP 0 ky'ataabi .
PFX FP 0 ky'ataali .
PFX FP 0 ky'ataaga .
PFX FP 0 ky'ataaka .
PFX FP 0 ky'ataabu .
PFX FP 0 ky'ataalu .
PFX FP 0 ky'ataaku .
PFX FP 0 ky'ataatu .
PFX FP 0 ky'etaan [^lmnb]
PFX FP l ky'etaand l.[^mn][^u]
PFX FP l ky'etaann l.[mn]
PFX FP w ky'etaamp [w]
PFX FP 0 ky'etaamu .
PFX FP 0 ky'etaaba .
PFX FP 0 ky'etaagu .
PFX FP 0 ky'etaagi .
PFX FP 0 ky'etaazi .
PFX FP 0 ky'etaaki .
PFX FP 0 ky'etaabi .
PFX FP 0 ky'etaali .
PFX FP 0 ky'etaaga .
PFX FP 0 ky'etaaka .
PFX FP 0 ky'etaabu .
PFX FP 0 ky'etaalu .
PFX FP 0 ky'etaaku .
PFX FP 0 ky'etaatu .
PFX FP 0 kyessiiba .
PFX FP 0 kyessiigu .
PFX FP 0 kyessiigi .
PFX FP 0 kyessiizi .
PFX FP 0 kyessiiki .
PFX FP 0 kyessiibi .
PFX FP 0 kyessiili .
PFX FP 0 kyessiiga .
PFX FP 0 kyessiika .
PFX FP 0 kyessiibu .
PFX FP 0 kyessiilu .
PFX FP 0 kyessiiku .
PFX FP 0 kyessiitu .
PFX FP 0 kyessiimu .
PFX FP 0 kyetutaan [^lmnb]
PFX FP l kyetutaand l.[^mn][^u]
PFX FP l kyetutaann l.[mn]
PFX FP w kyetutaamp [w]
PFX FP 0 kyetutaamu .
PFX FP 0 kyetutaaba .
PFX FP 0 kyetutaagu .
PFX FP 0 kyetutaagi .
PFX FP 0 kyetutaazi .
PFX FP 0 kyetutaaki .
PFX FP 0 kyetutaabi .
PFX FP 0 kyetutaali .
PFX FP 0 kyetutaaga .
PFX FP 0 kyetutaaka .
PFX FP 0 kyetutaabu .
PFX FP 0 kyetutaalu .
PFX FP 0 kyetutaaku .
PFX FP 0 kyetutaatu .
PFX FP 0 kyemutaan [^lmnb]
PFX FP l kyemutaand l.[^mn][^u]
PFX FP l kyemutaann l.[mn]
PFX FP w kyemutaamp [w]
PFX FP 0 kyemutaamu .
PFX FP 0 kyemutaaba .
PFX FP 0 kyemutaagu .
PFX FP 0 kyemutaagi .
PFX FP 0 kyemutaazi .
PFX FP 0 kyemutaaki .
PFX FP 0 kyemutaabi .
PFX FP 0 kyemutaali .
PFX FP 0 kyemutaaga .
PFX FP 0 kyemutaaka .
PFX FP 0 kyemutaabu .
PFX FP 0 kyemutaalu .
PFX FP 0 kyemutaaku .
PFX FP 0 kyemutaatu .
PFX FP 0 kyebataan [^lmnb]
PFX FP l kyebataand l.[^mn][^u]
PFX FP l kyebataann l.[mn]
PFX FP w kyebataamp [w]
PFX FP 0 kyebataamu .
PFX FP 0 kyebataaba .
PFX FP 0 kyebataagu .
PFX FP 0 kyebataagi .
PFX FP 0 kyebataazi .
PFX FP 0 kyebataaki .
PFX FP 0 kyebataabi .
PFX FP 0 kyebataali .
PFX FP 0 kyebataaga .
PFX FP 0 kyebataaka .
PFX FP 0 kyebataabu .
PFX FP 0 kyebataalu .
PFX FP 0 kyebataaku .
PFX FP 0 kyebataatu .
PFX FP 0 kyegutaan [^lmnb]
PFX FP l kyegutaand l.[^mn][^u]
PFX FP l kyegutaann l.[mn]
PFX FP w kyegutaamp [w]
PFX FP 0 kyegutaamu .
PFX FP 0 kyegutaaba .
PFX FP 0 kyegutaagu .
PFX FP 0 kyegutaagi .
PFX FP 0 kyegutaazi .
PFX FP 0 kyegutaaki .
PFX FP 0 kyegutaabi .
PFX FP 0 kyegutaali .
PFX FP 0 kyegutaaga .
PFX FP 0 kyegutaaka .
PFX FP 0 kyegutaabu .
PFX FP 0 kyegutaalu .
PFX FP 0 kyegutaaku .
PFX FP 0 kyegutaatu .
PFX FP 0 kyegitaan [^lmnb]
PFX FP l kyegitaand l.[^mn][^u]
PFX FP l kyegitaann l.[mn]
PFX FP w kyegitaamp [w]
PFX FP 0 kyegitaamu .
PFX FP 0 kyegitaaba .
PFX FP 0 kyegitaagu .
PFX FP 0 kyegitaagi .
PFX FP 0 kyegitaazi .
PFX FP 0 kyegitaaki .
PFX FP 0 kyegitaabi .
PFX FP 0 kyegitaali .
PFX FP 0 kyegitaaga .
PFX FP 0 kyegitaaka .
PFX FP 0 kyegitaabu .
PFX FP 0 kyegitaalu .
PFX FP 0 kyegitaaku .
PFX FP 0 kyegitaatu .
PFX FP 0 kyezitaan [^lmnb]
PFX FP l kyezitaand l.[^mn][^u]
PFX FP l kyezitaann l.[mn]
PFX FP w kyezitaamp [w]
PFX FP 0 kyezitaamu .
PFX FP 0 kyezitaaba .
PFX FP 0 kyezitaagu .
PFX FP 0 kyezitaagi .
PFX FP 0 kyezitaazi .
PFX FP 0 kyezitaaki .
PFX FP 0 kyezitaabi .
PFX FP 0 kyezitaali .
PFX FP 0 kyezitaaga .
PFX FP 0 kyezitaaka .
PFX FP 0 kyezitaabu .
PFX FP 0 kyezitaalu .
PFX FP 0 kyezitaaku .
PFX FP 0 kyezitaatu .
PFX FP 0 kyekitaan [^lmnb]
PFX FP l kyekitaand l.[^mn][^u]
PFX FP l kyekitaann l.[mn]
PFX FP w kyekitaamp [w]
PFX FP 0 kyekitaamu .
PFX FP 0 kyekitaaba .
PFX FP 0 kyekitaagu .
PFX FP 0 kyekitaagi .
PFX FP 0 kyekitaazi .
PFX FP 0 kyekitaaki .
PFX FP 0 kyekitaabi .
PFX FP 0 kyekitaali .
PFX FP 0 kyekitaaga .
PFX FP 0 kyekitaaka .
PFX FP 0 kyekitaabu .
PFX FP 0 kyekitaalu .
PFX FP 0 kyekitaaku .
PFX FP 0 kyekitaatu .
PFX FP 0 kyebitaan [^lmnb]
PFX FP l kyebitaand l.[^mn][^u]
PFX FP l kyebitaann l.[mn]
PFX FP w kyebitaamp [w]
PFX FP 0 kyebitaamu .
PFX FP 0 kyebitaaba .
PFX FP 0 kyebitaagu .
PFX FP 0 kyebitaagi .
PFX FP 0 kyebitaazi .
PFX FP 0 kyebitaaki .
PFX FP 0 kyebitaabi .
PFX FP 0 kyebitaali .
PFX FP 0 kyebitaaga .
PFX FP 0 kyebitaaka .
PFX FP 0 kyebitaabu .
PFX FP 0 kyebitaalu .
PFX FP 0 kyebitaaku .
PFX FP 0 kyebitaatu .
PFX FP 0 kyelitaan [^lmnb]
PFX FP l kyelitaand l.[^mn][^u]
PFX FP l kyelitaann l.[mn]
PFX FP w kyelitaamp [w]
PFX FP 0 kyelitaamu .
PFX FP 0 kyelitaaba .
PFX FP 0 kyelitaagu .
PFX FP 0 kyelitaagi .
PFX FP 0 kyelitaazi .
PFX FP 0 kyelitaaki .
PFX FP 0 kyelitaabi .
PFX FP 0 kyelitaali .
PFX FP 0 kyelitaaga .
PFX FP 0 kyelitaaka .
PFX FP 0 kyelitaabu .
PFX FP 0 kyelitaalu .
PFX FP 0 kyelitaaku .
PFX FP 0 kyelitaatu .
PFX FP 0 kyegataan [^lmnb]
PFX FP l kyegataand l.[^mn][^u]
PFX FP l kyegataann l.[mn]
PFX FP w kyegataamp [w]
PFX FP 0 kyegataamu .
PFX FP 0 kyegataaba .
PFX FP 0 kyegataagu .
PFX FP 0 kyegataagi .
PFX FP 0 kyegataazi .
PFX FP 0 kyegataaki .
PFX FP 0 kyegataabi .
PFX FP 0 kyegataali .
PFX FP 0 kyegataaga .
PFX FP 0 kyegataaka .
PFX FP 0 kyegataabu .
PFX FP 0 kyegataalu .
PFX FP 0 kyegataaku .
PFX FP 0 kyegataatu .
PFX FP 0 kyekataan [^lmnb]
PFX FP l kyekataand l.[^mn][^u]
PFX FP l kyekataann l.[mn]
PFX FP w kyekataamp [w]
PFX FP 0 kyekataamu .
PFX FP 0 kyekataaba .
PFX FP 0 kyekataagu .
PFX FP 0 kyekataagi .
PFX FP 0 kyekataazi .
PFX FP 0 kyekataaki .
PFX FP 0 kyekataabi .
PFX FP 0 kyekataali .
PFX FP 0 kyekataaga .
PFX FP 0 kyekataaka .
PFX FP 0 kyekataabu .
PFX FP 0 kyekataalu .
PFX FP 0 kyekataaku .
PFX FP 0 kyekataatu .
PFX FP 0 kyebutaan [^lmnb]
PFX FP l kyebutaand l.[^mn][^u]
PFX FP l kyebutaann l.[mn]
PFX FP w kyebutaamp [w]
PFX FP 0 kyebutaamu .
PFX FP 0 kyebutaaba .
PFX FP 0 kyebutaagu .
PFX FP 0 kyebutaagi .
PFX FP 0 kyebutaazi .
PFX FP 0 kyebutaaki .
PFX FP 0 kyebutaabi .
PFX FP 0 kyebutaali .
PFX FP 0 kyebutaaga .
PFX FP 0 kyebutaaka .
PFX FP 0 kyebutaabu .
PFX FP 0 kyebutaalu .
PFX FP 0 kyebutaaku .
PFX FP 0 kyebutaatu .
PFX FP 0 kyelutaan [^lmnb]
PFX FP l kyelutaand l.[^mn][^u]
PFX FP l kyelutaann l.[mn]
PFX FP w kyelutaamp [w]
PFX FP 0 kyelutaamu .
PFX FP 0 kyelutaaba .
PFX FP 0 kyelutaagu .
PFX FP 0 kyelutaagi .
PFX FP 0 kyelutaazi .
PFX FP 0 kyelutaaki .
PFX FP 0 kyelutaabi .
PFX FP 0 kyelutaali .
PFX FP 0 kyelutaaga .
PFX FP 0 kyelutaaka .
PFX FP 0 kyelutaabu .
PFX FP 0 kyelutaalu .
PFX FP 0 kyelutaaku .
PFX FP 0 kyelutaatu .
PFX FP 0 kyekutaan [^lmnb]
PFX FP l kyekutaand l.[^mn][^u]
PFX FP l kyekutaann l.[mn]
PFX FP w kyekutaamp [w]
PFX FP 0 kyekutaamu .
PFX FP 0 kyekutaaba .
PFX FP 0 kyekutaagu .
PFX FP 0 kyekutaagi .
PFX FP 0 kyekutaazi .
PFX FP 0 kyekutaaki .
PFX FP 0 kyekutaabi .
PFX FP 0 kyekutaali .
PFX FP 0 kyekutaaga .
PFX FP 0 kyekutaaka .
PFX FP 0 kyekutaabu .
PFX FP 0 kyekutaalu .
PFX FP 0 kyekutaaku .
PFX FP 0 kyekutaatu .
PFX FP 0 kyetutaan [^lmnb]
PFX FP l kyetutaand l.[^mn][^u]
PFX FP l kyetutaann l.[mn]
PFX FP w kyetutaamp [w]
PFX FP 0 kyetutaamu .
PFX FP 0 kyetutaaba .
PFX FP 0 kyetutaagu .
PFX FP 0 kyetutaagi .
PFX FP 0 kyetutaazi .
PFX FP 0 kyetutaaki .
PFX FP 0 kyetutaabi .
PFX FP 0 kyetutaali .
PFX FP 0 kyetutaaga .
PFX FP 0 kyetutaaka .
PFX FP 0 kyetutaabu .
PFX FP 0 kyetutaalu .
PFX FP 0 kyetutaaku .
PFX FP 0 kyetutaatu .
PFX FP 0 by'otoon [^lmnb]
PFX FP l by'otoond l.[^mn][^u]
PFX FP l by'otoonn l.[mn]
PFX FP w by'otoomp [w]
PFX FP 0 by'otoomu .
PFX FP 0 by'otooba .
PFX FP 0 by'otoogu .
PFX FP 0 by'otoogi .
PFX FP 0 by'otoozi .
PFX FP 0 by'otooki .
PFX FP 0 by'otoobi .
PFX FP 0 by'otooli .
PFX FP 0 by'otooga .
PFX FP 0 by'otooka .
PFX FP 0 by'otoobu .
PFX FP 0 by'otoolu .
PFX FP 0 by'otooku .
PFX FP 0 by'otootu .
PFX FP 0 by'ataan [^lmnb]
PFX FP l by'ataand l.[^mn][^u]
PFX FP l by'ataann l.[mn]
PFX FP w by'ataamp [w]
PFX FP 0 by'ataamu .
PFX FP 0 by'ataaba .
PFX FP 0 by'ataagu .
PFX FP 0 by'ataagi .
PFX FP 0 by'ataazi .
PFX FP 0 by'ataaki .
PFX FP 0 by'ataabi .
PFX FP 0 by'ataali .
PFX FP 0 by'ataaga .
PFX FP 0 by'ataaka .
PFX FP 0 by'ataabu .
PFX FP 0 by'ataalu .
PFX FP 0 by'ataaku .
PFX FP 0 by'ataatu .
PFX FP 0 by'etaan [^lmnb]
PFX FP l by'etaand l.[^mn][^u]
PFX FP l by'etaann l.[mn]
PFX FP w by'etaamp [w]
PFX FP 0 by'etaamu .
PFX FP 0 by'etaaba .
PFX FP 0 by'etaagu .
PFX FP 0 by'etaagi .
PFX FP 0 by'etaazi .
PFX FP 0 by'etaaki .
PFX FP 0 by'etaabi .
PFX FP 0 by'etaali .
PFX FP 0 by'etaaga .
PFX FP 0 by'etaaka .
PFX FP 0 by'etaabu .
PFX FP 0 by'etaalu .
PFX FP 0 by'etaaku .
PFX FP 0 by'etaatu .
PFX FP 0 byessiiba .
PFX FP 0 byessiigu .
PFX FP 0 byessiigi .
PFX FP 0 byessiizi .
PFX FP 0 byessiiki .
PFX FP 0 byessiibi .
PFX FP 0 byessiili .
PFX FP 0 byessiiga .
PFX FP 0 byessiika .
PFX FP 0 byessiibu .
PFX FP 0 byessiilu .
PFX FP 0 byessiiku .
PFX FP 0 byessiitu .
PFX FP 0 byessiimu .
PFX FP 0 byetutaan [^lmnb]
PFX FP l byetutaand l.[^mn][^u]
PFX FP l byetutaann l.[mn]
PFX FP w byetutaamp [w]
PFX FP 0 byetutaamu .
PFX FP 0 byetutaaba .
PFX FP 0 byetutaagu .
PFX FP 0 byetutaagi .
PFX FP 0 byetutaazi .
PFX FP 0 byetutaaki .
PFX FP 0 byetutaabi .
PFX FP 0 byetutaali .
PFX FP 0 byetutaaga .
PFX FP 0 byetutaaka .
PFX FP 0 byetutaabu .
PFX FP 0 byetutaalu .
PFX FP 0 byetutaaku .
PFX FP 0 byetutaatu .
PFX FP 0 byemutaan [^lmnb]
PFX FP l byemutaand l.[^mn][^u]
PFX FP l byemutaann l.[mn]
PFX FP w byemutaamp [w]
PFX FP 0 byemutaamu .
PFX FP 0 byemutaaba .
PFX FP 0 byemutaagu .
PFX FP 0 byemutaagi .
PFX FP 0 byemutaazi .
PFX FP 0 byemutaaki .
PFX FP 0 byemutaabi .
PFX FP 0 byemutaali .
PFX FP 0 byemutaaga .
PFX FP 0 byemutaaka .
PFX FP 0 byemutaabu .
PFX FP 0 byemutaalu .
PFX FP 0 byemutaaku .
PFX FP 0 byemutaatu .
PFX FP 0 byebataan [^lmnb]
PFX FP l byebataand l.[^mn][^u]
PFX FP l byebataann l.[mn]
PFX FP w byebataamp [w]
PFX FP 0 byebataamu .
PFX FP 0 byebataaba .
PFX FP 0 byebataagu .
PFX FP 0 byebataagi .
PFX FP 0 byebataazi .
PFX FP 0 byebataaki .
PFX FP 0 byebataabi .
PFX FP 0 byebataali .
PFX FP 0 byebataaga .
PFX FP 0 byebataaka .
PFX FP 0 byebataabu .
PFX FP 0 byebataalu .
PFX FP 0 byebataaku .
PFX FP 0 byebataatu .
PFX FP 0 byegutaan [^lmnb]
PFX FP l byegutaand l.[^mn][^u]
PFX FP l byegutaann l.[mn]
PFX FP w byegutaamp [w]
PFX FP 0 byegutaamu .
PFX FP 0 byegutaaba .
PFX FP 0 byegutaagu .
PFX FP 0 byegutaagi .
PFX FP 0 byegutaazi .
PFX FP 0 byegutaaki .
PFX FP 0 byegutaabi .
PFX FP 0 byegutaali .
PFX FP 0 byegutaaga .
PFX FP 0 byegutaaka .
PFX FP 0 byegutaabu .
PFX FP 0 byegutaalu .
PFX FP 0 byegutaaku .
PFX FP 0 byegutaatu .
PFX FP 0 byegitaan [^lmnb]
PFX FP l byegitaand l.[^mn][^u]
PFX FP l byegitaann l.[mn]
PFX FP w byegitaamp [w]
PFX FP 0 byegitaamu .
PFX FP 0 byegitaaba .
PFX FP 0 byegitaagu .
PFX FP 0 byegitaagi .
PFX FP 0 byegitaazi .
PFX FP 0 byegitaaki .
PFX FP 0 byegitaabi .
PFX FP 0 byegitaali .
PFX FP 0 byegitaaga .
PFX FP 0 byegitaaka .
PFX FP 0 byegitaabu .
PFX FP 0 byegitaalu .
PFX FP 0 byegitaaku .
PFX FP 0 byegitaatu .
PFX FP 0 byezitaan [^lmnb]
PFX FP l byezitaand l.[^mn][^u]
PFX FP l byezitaann l.[mn]
PFX FP w byezitaamp [w]
PFX FP 0 byezitaamu .
PFX FP 0 byezitaaba .
PFX FP 0 byezitaagu .
PFX FP 0 byezitaagi .
PFX FP 0 byezitaazi .
PFX FP 0 byezitaaki .
PFX FP 0 byezitaabi .
PFX FP 0 byezitaali .
PFX FP 0 byezitaaga .
PFX FP 0 byezitaaka .
PFX FP 0 byezitaabu .
PFX FP 0 byezitaalu .
PFX FP 0 byezitaaku .
PFX FP 0 byezitaatu .
PFX FP 0 byekitaan [^lmnb]
PFX FP l byekitaand l.[^mn][^u]
PFX FP l byekitaann l.[mn]
PFX FP w byekitaamp [w]
PFX FP 0 byekitaamu .
PFX FP 0 byekitaaba .
PFX FP 0 byekitaagu .
PFX FP 0 byekitaagi .
PFX FP 0 byekitaazi .
PFX FP 0 byekitaaki .
PFX FP 0 byekitaabi .
PFX FP 0 byekitaali .
PFX FP 0 byekitaaga .
PFX FP 0 byekitaaka .
PFX FP 0 byekitaabu .
PFX FP 0 byekitaalu .
PFX FP 0 byekitaaku .
PFX FP 0 byekitaatu .
PFX FP 0 byebitaan [^lmnb]
PFX FP l byebitaand l.[^mn][^u]
PFX FP l byebitaann l.[mn]
PFX FP w byebitaamp [w]
PFX FP 0 byebitaamu .
PFX FP 0 byebitaaba .
PFX FP 0 byebitaagu .
PFX FP 0 byebitaagi .
PFX FP 0 byebitaazi .
PFX FP 0 byebitaaki .
PFX FP 0 byebitaabi .
PFX FP 0 byebitaali .
PFX FP 0 byebitaaga .
PFX FP 0 byebitaaka .
PFX FP 0 byebitaabu .
PFX FP 0 byebitaalu .
PFX FP 0 byebitaaku .
PFX FP 0 byebitaatu .
PFX FP 0 byelitaan [^lmnb]
PFX FP l byelitaand l.[^mn][^u]
PFX FP l byelitaann l.[mn]
PFX FP w byelitaamp [w]
PFX FP 0 byelitaamu .
PFX FP 0 byelitaaba .
PFX FP 0 byelitaagu .
PFX FP 0 byelitaagi .
PFX FP 0 byelitaazi .
PFX FP 0 byelitaaki .
PFX FP 0 byelitaabi .
PFX FP 0 byelitaali .
PFX FP 0 byelitaaga .
PFX FP 0 byelitaaka .
PFX FP 0 byelitaabu .
PFX FP 0 byelitaalu .
PFX FP 0 byelitaaku .
PFX FP 0 byelitaatu .
PFX FP 0 byegataan [^lmnb]
PFX FP l byegataand l.[^mn][^u]
PFX FP l byegataann l.[mn]
PFX FP w byegataamp [w]
PFX FP 0 byegataamu .
PFX FP 0 byegataaba .
PFX FP 0 byegataagu .
PFX FP 0 byegataagi .
PFX FP 0 byegataazi .
PFX FP 0 byegataaki .
PFX FP 0 byegataabi .
PFX FP 0 byegataali .
PFX FP 0 byegataaga .
PFX FP 0 byegataaka .
PFX FP 0 byegataabu .
PFX FP 0 byegataalu .
PFX FP 0 byegataaku .
PFX FP 0 byegataatu .
PFX FP 0 byekataan [^lmnb]
PFX FP l byekataand l.[^mn][^u]
PFX FP l byekataann l.[mn]
PFX FP w byekataamp [w]
PFX FP 0 byekataamu .
PFX FP 0 byekataaba .
PFX FP 0 byekataagu .
PFX FP 0 byekataagi .
PFX FP 0 byekataazi .
PFX FP 0 byekataaki .
PFX FP 0 byekataabi .
PFX FP 0 byekataali .
PFX FP 0 byekataaga .
PFX FP 0 byekataaka .
PFX FP 0 byekataabu .
PFX FP 0 byekataalu .
PFX FP 0 byekataaku .
PFX FP 0 byekataatu .
PFX FP 0 byebutaan [^lmnb]
PFX FP l byebutaand l.[^mn][^u]
PFX FP l byebutaann l.[mn]
PFX FP w byebutaamp [w]
PFX FP 0 byebutaamu .
PFX FP 0 byebutaaba .
PFX FP 0 byebutaagu .
PFX FP 0 byebutaagi .
PFX FP 0 byebutaazi .
PFX FP 0 byebutaaki .
PFX FP 0 byebutaabi .
PFX FP 0 byebutaali .
PFX FP 0 byebutaaga .
PFX FP 0 byebutaaka .
PFX FP 0 byebutaabu .
PFX FP 0 byebutaalu .
PFX FP 0 byebutaaku .
PFX FP 0 byebutaatu .
PFX FP 0 byelutaan [^lmnb]
PFX FP l byelutaand l.[^mn][^u]
PFX FP l byelutaann l.[mn]
PFX FP w byelutaamp [w]
PFX FP 0 byelutaamu .
PFX FP 0 byelutaaba .
PFX FP 0 byelutaagu .
PFX FP 0 byelutaagi .
PFX FP 0 byelutaazi .
PFX FP 0 byelutaaki .
PFX FP 0 byelutaabi .
PFX FP 0 byelutaali .
PFX FP 0 byelutaaga .
PFX FP 0 byelutaaka .
PFX FP 0 byelutaabu .
PFX FP 0 byelutaalu .
PFX FP 0 byelutaaku .
PFX FP 0 byelutaatu .
PFX FP 0 byekutaan [^lmnb]
PFX FP l byekutaand l.[^mn][^u]
PFX FP l byekutaann l.[mn]
PFX FP w byekutaamp [w]
PFX FP 0 byekutaamu .
PFX FP 0 byekutaaba .
PFX FP 0 byekutaagu .
PFX FP 0 byekutaagi .
PFX FP 0 byekutaazi .
PFX FP 0 byekutaaki .
PFX FP 0 byekutaabi .
PFX FP 0 byekutaali .
PFX FP 0 byekutaaga .
PFX FP 0 byekutaaka .
PFX FP 0 byekutaabu .
PFX FP 0 byekutaalu .
PFX FP 0 byekutaaku .
PFX FP 0 byekutaatu .
PFX FP 0 byetutaan [^lmnb]
PFX FP l byetutaand l.[^mn][^u]
PFX FP l byetutaann l.[mn]
PFX FP w byetutaamp [w]
PFX FP 0 byetutaamu .
PFX FP 0 byetutaaba .
PFX FP 0 byetutaagu .
PFX FP 0 byetutaagi .
PFX FP 0 byetutaazi .
PFX FP 0 byetutaaki .
PFX FP 0 byetutaabi .
PFX FP 0 byetutaali .
PFX FP 0 byetutaaga .
PFX FP 0 byetutaaka .
PFX FP 0 byetutaabu .
PFX FP 0 byetutaalu .
PFX FP 0 byetutaaku .
PFX FP 0 byetutaatu .
PFX FP 0 ly'otoon [^lmnb]
PFX FP l ly'otoond l.[^mn][^u]
PFX FP l ly'otoonn l.[mn]
PFX FP w ly'otoomp [w]
PFX FP 0 ly'otoomu .
PFX FP 0 ly'otooba .
PFX FP 0 ly'otoogu .
PFX FP 0 ly'otoogi .
PFX FP 0 ly'otoozi .
PFX FP 0 ly'otooki .
PFX FP 0 ly'otoobi .
PFX FP 0 ly'otooli .
PFX FP 0 ly'otooga .
PFX FP 0 ly'otooka .
PFX FP 0 ly'otoobu .
PFX FP 0 ly'otoolu .
PFX FP 0 ly'otooku .
PFX FP 0 ly'otootu .
PFX FP 0 ly'ataan [^lmnb]
PFX FP l ly'ataand l.[^mn][^u]
PFX FP l ly'ataann l.[mn]
PFX FP w ly'ataamp [w]
PFX FP 0 ly'ataamu .
PFX FP 0 ly'ataaba .
PFX FP 0 ly'ataagu .
PFX FP 0 ly'ataagi .
PFX FP 0 ly'ataazi .
PFX FP 0 ly'ataaki .
PFX FP 0 ly'ataabi .
PFX FP 0 ly'ataali .
PFX FP 0 ly'ataaga .
PFX FP 0 ly'ataaka .
PFX FP 0 ly'ataabu .
PFX FP 0 ly'ataalu .
PFX FP 0 ly'ataaku .
PFX FP 0 ly'ataatu .
PFX FP 0 ly'etaan [^lmnb]
PFX FP l ly'etaand l.[^mn][^u]
PFX FP l ly'etaann l.[mn]
PFX FP w ly'etaamp [w]
PFX FP 0 ly'etaamu .
PFX FP 0 ly'etaaba .
PFX FP 0 ly'etaagu .
PFX FP 0 ly'etaagi .
PFX FP 0 ly'etaazi .
PFX FP 0 ly'etaaki .
PFX FP 0 ly'etaabi .
PFX FP 0 ly'etaali .
PFX FP 0 ly'etaaga .
PFX FP 0 ly'etaaka .
PFX FP 0 ly'etaabu .
PFX FP 0 ly'etaalu .
PFX FP 0 ly'etaaku .
PFX FP 0 ly'etaatu .
PFX FP 0 lyessiiba .
PFX FP 0 lyessiigu .
PFX FP 0 lyessiigi .
PFX FP 0 lyessiizi .
PFX FP 0 lyessiiki .
PFX FP 0 lyessiibi .
PFX FP 0 lyessiili .
PFX FP 0 lyessiiga .
PFX FP 0 lyessiika .
PFX FP 0 lyessiibu .
PFX FP 0 lyessiilu .
PFX FP 0 lyessiiku .
PFX FP 0 lyessiitu .
PFX FP 0 lyessiimu .
PFX FP 0 lyetutaan [^lmnb]
PFX FP l lyetutaand l.[^mn][^u]
PFX FP l lyetutaann l.[mn]
PFX FP w lyetutaamp [w]
PFX FP 0 lyetutaamu .
PFX FP 0 lyetutaaba .
PFX FP 0 lyetutaagu .
PFX FP 0 lyetutaagi .
PFX FP 0 lyetutaazi .
PFX FP 0 lyetutaaki .
PFX FP 0 lyetutaabi .
PFX FP 0 lyetutaali .
PFX FP 0 lyetutaaga .
PFX FP 0 lyetutaaka .
PFX FP 0 lyetutaabu .
PFX FP 0 lyetutaalu .
PFX FP 0 lyetutaaku .
PFX FP 0 lyetutaatu .
PFX FP 0 lyemutaan [^lmnb]
PFX FP l lyemutaand l.[^mn][^u]
PFX FP l lyemutaann l.[mn]
PFX FP w lyemutaamp [w]
PFX FP 0 lyemutaamu .
PFX FP 0 lyemutaaba .
PFX FP 0 lyemutaagu .
PFX FP 0 lyemutaagi .
PFX FP 0 lyemutaazi .
PFX FP 0 lyemutaaki .
PFX FP 0 lyemutaabi .
PFX FP 0 lyemutaali .
PFX FP 0 lyemutaaga .
PFX FP 0 lyemutaaka .
PFX FP 0 lyemutaabu .
PFX FP 0 lyemutaalu .
PFX FP 0 lyemutaaku .
PFX FP 0 lyemutaatu .
PFX FP 0 lyebataan [^lmnb]
PFX FP l lyebataand l.[^mn][^u]
PFX FP l lyebataann l.[mn]
PFX FP w lyebataamp [w]
PFX FP 0 lyebataamu .
PFX FP 0 lyebataaba .
PFX FP 0 lyebataagu .
PFX FP 0 lyebataagi .
PFX FP 0 lyebataazi .
PFX FP 0 lyebataaki .
PFX FP 0 lyebataabi .
PFX FP 0 lyebataali .
PFX FP 0 lyebataaga .
PFX FP 0 lyebataaka .
PFX FP 0 lyebataabu .
PFX FP 0 lyebataalu .
PFX FP 0 lyebataaku .
PFX FP 0 lyebataatu .
PFX FP 0 lyegutaan [^lmnb]
PFX FP l lyegutaand l.[^mn][^u]
PFX FP l lyegutaann l.[mn]
PFX FP w lyegutaamp [w]
PFX FP 0 lyegutaamu .
PFX FP 0 lyegutaaba .
PFX FP 0 lyegutaagu .
PFX FP 0 lyegutaagi .
PFX FP 0 lyegutaazi .
PFX FP 0 lyegutaaki .
PFX FP 0 lyegutaabi .
PFX FP 0 lyegutaali .
PFX FP 0 lyegutaaga .
PFX FP 0 lyegutaaka .
PFX FP 0 lyegutaabu .
PFX FP 0 lyegutaalu .
PFX FP 0 lyegutaaku .
PFX FP 0 lyegutaatu .
PFX FP 0 lyegitaan [^lmnb]
PFX FP l lyegitaand l.[^mn][^u]
PFX FP l lyegitaann l.[mn]
PFX FP w lyegitaamp [w]
PFX FP 0 lyegitaamu .
PFX FP 0 lyegitaaba .
PFX FP 0 lyegitaagu .
PFX FP 0 lyegitaagi .
PFX FP 0 lyegitaazi .
PFX FP 0 lyegitaaki .
PFX FP 0 lyegitaabi .
PFX FP 0 lyegitaali .
PFX FP 0 lyegitaaga .
PFX FP 0 lyegitaaka .
PFX FP 0 lyegitaabu .
PFX FP 0 lyegitaalu .
PFX FP 0 lyegitaaku .
PFX FP 0 lyegitaatu .
PFX FP 0 lyezitaan [^lmnb]
PFX FP l lyezitaand l.[^mn][^u]
PFX FP l lyezitaann l.[mn]
PFX FP w lyezitaamp [w]
PFX FP 0 lyezitaamu .
PFX FP 0 lyezitaaba .
PFX FP 0 lyezitaagu .
PFX FP 0 lyezitaagi .
PFX FP 0 lyezitaazi .
PFX FP 0 lyezitaaki .
PFX FP 0 lyezitaabi .
PFX FP 0 lyezitaali .
PFX FP 0 lyezitaaga .
PFX FP 0 lyezitaaka .
PFX FP 0 lyezitaabu .
PFX FP 0 lyezitaalu .
PFX FP 0 lyezitaaku .
PFX FP 0 lyezitaatu .
PFX FP 0 lyekitaan [^lmnb]
PFX FP l lyekitaand l.[^mn][^u]
PFX FP l lyekitaann l.[mn]
PFX FP w lyekitaamp [w]
PFX FP 0 lyekitaamu .
PFX FP 0 lyekitaaba .
PFX FP 0 lyekitaagu .
PFX FP 0 lyekitaagi .
PFX FP 0 lyekitaazi .
PFX FP 0 lyekitaaki .
PFX FP 0 lyekitaabi .
PFX FP 0 lyekitaali .
PFX FP 0 lyekitaaga .
PFX FP 0 lyekitaaka .
PFX FP 0 lyekitaabu .
PFX FP 0 lyekitaalu .
PFX FP 0 lyekitaaku .
PFX FP 0 lyekitaatu .
PFX FP 0 lyebitaan [^lmnb]
PFX FP l lyebitaand l.[^mn][^u]
PFX FP l lyebitaann l.[mn]
PFX FP w lyebitaamp [w]
PFX FP 0 lyebitaamu .
PFX FP 0 lyebitaaba .
PFX FP 0 lyebitaagu .
PFX FP 0 lyebitaagi .
PFX FP 0 lyebitaazi .
PFX FP 0 lyebitaaki .
PFX FP 0 lyebitaabi .
PFX FP 0 lyebitaali .
PFX FP 0 lyebitaaga .
PFX FP 0 lyebitaaka .
PFX FP 0 lyebitaabu .
PFX FP 0 lyebitaalu .
PFX FP 0 lyebitaaku .
PFX FP 0 lyebitaatu .
PFX FP 0 lyelitaan [^lmnb]
PFX FP l lyelitaand l.[^mn][^u]
PFX FP l lyelitaann l.[mn]
PFX FP w lyelitaamp [w]
PFX FP 0 lyelitaamu .
PFX FP 0 lyelitaaba .
PFX FP 0 lyelitaagu .
PFX FP 0 lyelitaagi .
PFX FP 0 lyelitaazi .
PFX FP 0 lyelitaaki .
PFX FP 0 lyelitaabi .
PFX FP 0 lyelitaali .
PFX FP 0 lyelitaaga .
PFX FP 0 lyelitaaka .
PFX FP 0 lyelitaabu .
PFX FP 0 lyelitaalu .
PFX FP 0 lyelitaaku .
PFX FP 0 lyelitaatu .
PFX FP 0 lyegataan [^lmnb]
PFX FP l lyegataand l.[^mn][^u]
PFX FP l lyegataann l.[mn]
PFX FP w lyegataamp [w]
PFX FP 0 lyegataamu .
PFX FP 0 lyegataaba .
PFX FP 0 lyegataagu .
PFX FP 0 lyegataagi .
PFX FP 0 lyegataazi .
PFX FP 0 lyegataaki .
PFX FP 0 lyegataabi .
PFX FP 0 lyegataali .
PFX FP 0 lyegataaga .
PFX FP 0 lyegataaka .
PFX FP 0 lyegataabu .
PFX FP 0 lyegataalu .
PFX FP 0 lyegataaku .
PFX FP 0 lyegataatu .
PFX FP 0 lyekataan [^lmnb]
PFX FP l lyekataand l.[^mn][^u]
PFX FP l lyekataann l.[mn]
PFX FP w lyekataamp [w]
PFX FP 0 lyekataamu .
PFX FP 0 lyekataaba .
PFX FP 0 lyekataagu .
PFX FP 0 lyekataagi .
PFX FP 0 lyekataazi .
PFX FP 0 lyekataaki .
PFX FP 0 lyekataabi .
PFX FP 0 lyekataali .
PFX FP 0 lyekataaga .
PFX FP 0 lyekataaka .
PFX FP 0 lyekataabu .
PFX FP 0 lyekataalu .
PFX FP 0 lyekataaku .
PFX FP 0 lyekataatu .
PFX FP 0 lyebutaan [^lmnb]
PFX FP l lyebutaand l.[^mn][^u]
PFX FP l lyebutaann l.[mn]
PFX FP w lyebutaamp [w]
PFX FP 0 lyebutaamu .
PFX FP 0 lyebutaaba .
PFX FP 0 lyebutaagu .
PFX FP 0 lyebutaagi .
PFX FP 0 lyebutaazi .
PFX FP 0 lyebutaaki .
PFX FP 0 lyebutaabi .
PFX FP 0 lyebutaali .
PFX FP 0 lyebutaaga .
PFX FP 0 lyebutaaka .
PFX FP 0 lyebutaabu .
PFX FP 0 lyebutaalu .
PFX FP 0 lyebutaaku .
PFX FP 0 lyebutaatu .
PFX FP 0 lyelutaan [^lmnb]
PFX FP l lyelutaand l.[^mn][^u]
PFX FP l lyelutaann l.[mn]
PFX FP w lyelutaamp [w]
PFX FP 0 lyelutaamu .
PFX FP 0 lyelutaaba .
PFX FP 0 lyelutaagu .
PFX FP 0 lyelutaagi .
PFX FP 0 lyelutaazi .
PFX FP 0 lyelutaaki .
PFX FP 0 lyelutaabi .
PFX FP 0 lyelutaali .
PFX FP 0 lyelutaaga .
PFX FP 0 lyelutaaka .
PFX FP 0 lyelutaabu .
PFX FP 0 lyelutaalu .
PFX FP 0 lyelutaaku .
PFX FP 0 lyelutaatu .
PFX FP 0 lyekutaan [^lmnb]
PFX FP l lyekutaand l.[^mn][^u]
PFX FP l lyekutaann l.[mn]
PFX FP w lyekutaamp [w]
PFX FP 0 lyekutaamu .
PFX FP 0 lyekutaaba .
PFX FP 0 lyekutaagu .
PFX FP 0 lyekutaagi .
PFX FP 0 lyekutaazi .
PFX FP 0 lyekutaaki .
PFX FP 0 lyekutaabi .
PFX FP 0 lyekutaali .
PFX FP 0 lyekutaaga .
PFX FP 0 lyekutaaka .
PFX FP 0 lyekutaabu .
PFX FP 0 lyekutaalu .
PFX FP 0 lyekutaaku .
PFX FP 0 lyekutaatu .
PFX FP 0 lyetutaan [^lmnb]
PFX FP l lyetutaand l.[^mn][^u]
PFX FP l lyetutaann l.[mn]
PFX FP w lyetutaamp [w]
PFX FP 0 lyetutaamu .
PFX FP 0 lyetutaaba .
PFX FP 0 lyetutaagu .
PFX FP 0 lyetutaagi .
PFX FP 0 lyetutaazi .
PFX FP 0 lyetutaaki .
PFX FP 0 lyetutaabi .
PFX FP 0 lyetutaali .
PFX FP 0 lyetutaaga .
PFX FP 0 lyetutaaka .
PFX FP 0 lyetutaabu .
PFX FP 0 lyetutaalu .
PFX FP 0 lyetutaaku .
PFX FP 0 lyetutaatu .
PFX FP 0 k'otoon [^lmnb]
PFX FP l k'otoond l.[^mn][^u]
PFX FP l k'otoonn l.[mn]
PFX FP w k'otoomp [w]
PFX FP 0 k'otoomu .
PFX FP 0 k'otooba .
PFX FP 0 k'otoogu .
PFX FP 0 k'otoogi .
PFX FP 0 k'otoozi .
PFX FP 0 k'otooki .
PFX FP 0 k'otoobi .
PFX FP 0 k'otooli .
PFX FP 0 k'otooga .
PFX FP 0 k'otooka .
PFX FP 0 k'otoobu .
PFX FP 0 k'otoolu .
PFX FP 0 k'otooku .
PFX FP 0 k'otootu .
PFX FP 0 k'ataan [^lmnb]
PFX FP l k'ataand l.[^mn][^u]
PFX FP l k'ataann l.[mn]
PFX FP w k'ataamp [w]
PFX FP 0 k'ataamu .
PFX FP 0 k'ataaba .
PFX FP 0 k'ataagu .
PFX FP 0 k'ataagi .
PFX FP 0 k'ataazi .
PFX FP 0 k'ataaki .
PFX FP 0 k'ataabi .
PFX FP 0 k'ataali .
PFX FP 0 k'ataaga .
PFX FP 0 k'ataaka .
PFX FP 0 k'ataabu .
PFX FP 0 k'ataalu .
PFX FP 0 k'ataaku .
PFX FP 0 k'ataatu .
PFX FP 0 k'etaan [^lmnb]
PFX FP l k'etaand l.[^mn][^u]
PFX FP l k'etaann l.[mn]
PFX FP w k'etaamp [w]
PFX FP 0 k'etaamu .
PFX FP 0 k'etaaba .
PFX FP 0 k'etaagu .
PFX FP 0 k'etaagi .
PFX FP 0 k'etaazi .
PFX FP 0 k'etaaki .
PFX FP 0 k'etaabi .
PFX FP 0 k'etaali .
PFX FP 0 k'etaaga .
PFX FP 0 k'etaaka .
PFX FP 0 k'etaabu .
PFX FP 0 k'etaalu .
PFX FP 0 k'etaaku .
PFX FP 0 k'etaatu .
PFX FP 0 kessiiba .
PFX FP 0 kessiigu .
PFX FP 0 kessiigi .
PFX FP 0 kessiizi .
PFX FP 0 kessiiki .
PFX FP 0 kessiibi .
PFX FP 0 kessiili .
PFX FP 0 kessiiga .
PFX FP 0 kessiika .
PFX FP 0 kessiibu .
PFX FP 0 kessiilu .
PFX FP 0 kessiiku .
PFX FP 0 kessiitu .
PFX FP 0 kessiimu .
PFX FP 0 kessiiba .
PFX FP 0 kessiigu .
PFX FP 0 kessiigi .
PFX FP 0 kessiizi .
PFX FP 0 kessiiki .
PFX FP 0 kessiibi .
PFX FP 0 kessiili .
PFX FP 0 kessiiga .
PFX FP 0 kessiika .
PFX FP 0 kessiibu .
PFX FP 0 kessiilu .
PFX FP 0 kessiiku .
PFX FP 0 kessiitu .
PFX FP 0 kessiimu .
PFX FP 0 ketutaan [^lmnb]
PFX FP l ketutaand l.[^mn][^u]
PFX FP l ketutaann l.[mn]
PFX FP w ketutaamp [w]
PFX FP 0 ketutaamu .
PFX FP 0 ketutaaba .
PFX FP 0 ketutaagu .
PFX FP 0 ketutaagi .
PFX FP 0 ketutaazi .
PFX FP 0 ketutaaki .
PFX FP 0 ketutaabi .
PFX FP 0 ketutaali .
PFX FP 0 ketutaaga .
PFX FP 0 ketutaaka .
PFX FP 0 ketutaabu .
PFX FP 0 ketutaalu .
PFX FP 0 ketutaaku .
PFX FP 0 ketutaatu .
PFX FP 0 kemutaan [^lmnb]
PFX FP l kemutaand l.[^mn][^u]
PFX FP l kemutaann l.[mn]
PFX FP w kemutaamp [w]
PFX FP 0 kemutaamu .
PFX FP 0 kemutaaba .
PFX FP 0 kemutaagu .
PFX FP 0 kemutaagi .
PFX FP 0 kemutaazi .
PFX FP 0 kemutaaki .
PFX FP 0 kemutaabi .
PFX FP 0 kemutaali .
PFX FP 0 kemutaaga .
PFX FP 0 kemutaaka .
PFX FP 0 kemutaabu .
PFX FP 0 kemutaalu .
PFX FP 0 kemutaaku .
PFX FP 0 kemutaatu .
PFX FP 0 kebataan [^lmnb]
PFX FP l kebataand l.[^mn][^u]
PFX FP l kebataann l.[mn]
PFX FP w kebataamp [w]
PFX FP 0 kebataamu .
PFX FP 0 kebataaba .
PFX FP 0 kebataagu .
PFX FP 0 kebataagi .
PFX FP 0 kebataazi .
PFX FP 0 kebataaki .
PFX FP 0 kebataabi .
PFX FP 0 kebataali .
PFX FP 0 kebataaga .
PFX FP 0 kebataaka .
PFX FP 0 kebataabu .
PFX FP 0 kebataalu .
PFX FP 0 kebataaku .
PFX FP 0 kebataatu .
PFX FP 0 kegutaan [^lmnb]
PFX FP l kegutaand l.[^mn][^u]
PFX FP l kegutaann l.[mn]
PFX FP w kegutaamp [w]
PFX FP 0 kegutaamu .
PFX FP 0 kegutaaba .
PFX FP 0 kegutaagu .
PFX FP 0 kegutaagi .
PFX FP 0 kegutaazi .
PFX FP 0 kegutaaki .
PFX FP 0 kegutaabi .
PFX FP 0 kegutaali .
PFX FP 0 kegutaaga .
PFX FP 0 kegutaaka .
PFX FP 0 kegutaabu .
PFX FP 0 kegutaalu .
PFX FP 0 kegutaaku .
PFX FP 0 kegutaatu .
PFX FP 0 kegitaan [^lmnb]
PFX FP l kegitaand l.[^mn][^u]
PFX FP l kegitaann l.[mn]
PFX FP w kegitaamp [w]
PFX FP 0 kegitaamu .
PFX FP 0 kegitaaba .
PFX FP 0 kegitaagu .
PFX FP 0 kegitaagi .
PFX FP 0 kegitaazi .
PFX FP 0 kegitaaki .
PFX FP 0 kegitaabi .
PFX FP 0 kegitaali .
PFX FP 0 kegitaaga .
PFX FP 0 kegitaaka .
PFX FP 0 kegitaabu .
PFX FP 0 kegitaalu .
PFX FP 0 kegitaaku .
PFX FP 0 kegitaatu .
PFX FP 0 kezitaan [^lmnb]
PFX FP l kezitaand l.[^mn][^u]
PFX FP l kezitaann l.[mn]
PFX FP w kezitaamp [w]
PFX FP 0 kezitaamu .
PFX FP 0 kezitaaba .
PFX FP 0 kezitaagu .
PFX FP 0 kezitaagi .
PFX FP 0 kezitaazi .
PFX FP 0 kezitaaki .
PFX FP 0 kezitaabi .
PFX FP 0 kezitaali .
PFX FP 0 kezitaaga .
PFX FP 0 kezitaaka .
PFX FP 0 kezitaabu .
PFX FP 0 kezitaalu .
PFX FP 0 kezitaaku .
PFX FP 0 kezitaatu .
PFX FP 0 kekitaan [^lmnb]
PFX FP l kekitaand l.[^mn][^u]
PFX FP l kekitaann l.[mn]
PFX FP w kekitaamp [w]
PFX FP 0 kekitaamu .
PFX FP 0 kekitaaba .
PFX FP 0 kekitaagu .
PFX FP 0 kekitaagi .
PFX FP 0 kekitaazi .
PFX FP 0 kekitaaki .
PFX FP 0 kekitaabi .
PFX FP 0 kekitaali .
PFX FP 0 kekitaaga .
PFX FP 0 kekitaaka .
PFX FP 0 kekitaabu .
PFX FP 0 kekitaalu .
PFX FP 0 kekitaaku .
PFX FP 0 kekitaatu .
PFX FP 0 kebitaan [^lmnb]
PFX FP l kebitaand l.[^mn][^u]
PFX FP l kebitaann l.[mn]
PFX FP w kebitaamp [w]
PFX FP 0 kebitaamu .
PFX FP 0 kebitaaba .
PFX FP 0 kebitaagu .
PFX FP 0 kebitaagi .
PFX FP 0 kebitaazi .
PFX FP 0 kebitaaki .
PFX FP 0 kebitaabi .
PFX FP 0 kebitaali .
PFX FP 0 kebitaaga .
PFX FP 0 kebitaaka .
PFX FP 0 kebitaabu .
PFX FP 0 kebitaalu .
PFX FP 0 kebitaaku .
PFX FP 0 kebitaatu .
PFX FP 0 kelitaan [^lmnb]
PFX FP l kelitaand l.[^mn][^u]
PFX FP l kelitaann l.[mn]
PFX FP w kelitaamp [w]
PFX FP 0 kelitaamu .
PFX FP 0 kelitaaba .
PFX FP 0 kelitaagu .
PFX FP 0 kelitaagi .
PFX FP 0 kelitaazi .
PFX FP 0 kelitaaki .
PFX FP 0 kelitaabi .
PFX FP 0 kelitaali .
PFX FP 0 kelitaaga .
PFX FP 0 kelitaaka .
PFX FP 0 kelitaabu .
PFX FP 0 kelitaalu .
PFX FP 0 kelitaaku .
PFX FP 0 kelitaatu .
PFX FP 0 kegataan [^lmnb]
PFX FP l kegataand l.[^mn][^u]
PFX FP l kegataann l.[mn]
PFX FP w kegataamp [w]
PFX FP 0 kegataamu .
PFX FP 0 kegataaba .
PFX FP 0 kegataagu .
PFX FP 0 kegataagi .
PFX FP 0 kegataazi .
PFX FP 0 kegataaki .
PFX FP 0 kegataabi .
PFX FP 0 kegataali .
PFX FP 0 kegataaga .
PFX FP 0 kegataaka .
PFX FP 0 kegataabu .
PFX FP 0 kegataalu .
PFX FP 0 kegataaku .
PFX FP 0 kegataatu .
PFX FP 0 kekataan [^lmnb]
PFX FP l kekataand l.[^mn][^u]
PFX FP l kekataann l.[mn]
PFX FP w kekataamp [w]
PFX FP 0 kekataamu .
PFX FP 0 kekataaba .
PFX FP 0 kekataagu .
PFX FP 0 kekataagi .
PFX FP 0 kekataazi .
PFX FP 0 kekataaki .
PFX FP 0 kekataabi .
PFX FP 0 kekataali .
PFX FP 0 kekataaga .
PFX FP 0 kekataaka .
PFX FP 0 kekataabu .
PFX FP 0 kekataalu .
PFX FP 0 kekataaku .
PFX FP 0 kekataatu .
PFX FP 0 kebutaan [^lmnb]
PFX FP l kebutaand l.[^mn][^u]
PFX FP l kebutaann l.[mn]
PFX FP w kebutaamp [w]
PFX FP 0 kebutaamu .
PFX FP 0 kebutaaba .
PFX FP 0 kebutaagu .
PFX FP 0 kebutaagi .
PFX FP 0 kebutaazi .
PFX FP 0 kebutaaki .
PFX FP 0 kebutaabi .
PFX FP 0 kebutaali .
PFX FP 0 kebutaaga .
PFX FP 0 kebutaaka .
PFX FP 0 kebutaabu .
PFX FP 0 kebutaalu .
PFX FP 0 kebutaaku .
PFX FP 0 kebutaatu .
PFX FP 0 kelutaan [^lmnb]
PFX FP l kelutaand l.[^mn][^u]
PFX FP l kelutaann l.[mn]
PFX FP w kelutaamp [w]
PFX FP 0 kelutaamu .
PFX FP 0 kelutaaba .
PFX FP 0 kelutaagu .
PFX FP 0 kelutaagi .
PFX FP 0 kelutaazi .
PFX FP 0 kelutaaki .
PFX FP 0 kelutaabi .
PFX FP 0 kelutaali .
PFX FP 0 kelutaaga .
PFX FP 0 kelutaaka .
PFX FP 0 kelutaabu .
PFX FP 0 kelutaalu .
PFX FP 0 kelutaaku .
PFX FP 0 kelutaatu .
PFX FP 0 kekutaan [^lmnb]
PFX FP l kekutaand l.[^mn][^u]
PFX FP l kekutaann l.[mn]
PFX FP w kekutaamp [w]
PFX FP 0 kekutaamu .
PFX FP 0 kekutaaba .
PFX FP 0 kekutaagu .
PFX FP 0 kekutaagi .
PFX FP 0 kekutaazi .
PFX FP 0 kekutaaki .
PFX FP 0 kekutaabi .
PFX FP 0 kekutaali .
PFX FP 0 kekutaaga .
PFX FP 0 kekutaaka .
PFX FP 0 kekutaabu .
PFX FP 0 kekutaalu .
PFX FP 0 kekutaaku .
PFX FP 0 kekutaatu .
PFX FP 0 ketutaan [^lmnb]
PFX FP l ketutaand l.[^mn][^u]
PFX FP l ketutaann l.[mn]
PFX FP w ketutaamp [w]
PFX FP 0 ketutaamu .
PFX FP 0 ketutaaba .
PFX FP 0 ketutaagu .
PFX FP 0 ketutaagi .
PFX FP 0 ketutaazi .
PFX FP 0 ketutaaki .
PFX FP 0 ketutaabi .
PFX FP 0 ketutaali .
PFX FP 0 ketutaaga .
PFX FP 0 ketutaaka .
PFX FP 0 ketutaabu .
PFX FP 0 ketutaalu .
PFX FP 0 ketutaaku .
PFX FP 0 ketutaatu ."""

rule_right_raw = """
PFX OR Y 16
PFX OR 0 mwe .
PFX OR 0 bee .
PFX OR 0 gwe .
PFX OR 0 gye .
PFX OR 0 zee .
PFX OR 0 kye .
PFX OR 0 bye .
PFX OR 0 lye .
PFX OR 0 gee .
PFX OR 0 kee .
PFX OR 0 bwe .
PFX OR 0 lwe .
PFX OR 0 zee .
PFX OR 0 kwe .
PFX OR 0 gee .
PFX OR 0 twe ."""

FLAG_DESCRIPTIONS = {
    "FP": "FP",
    "OR": "Special reflexive object markers",
}

def parse_rules(raw_text):
    rules = []
    for line in raw_text.strip().split('\n'):
        s = line.strip()
        if not s or s.startswith('#'):
            continue
        s = s.split('#', 1)[0].strip()
        parts = s.split()
        if len(parts) < 4:
            continue
        if parts[2] == 'Y':
            continue
        cond = parts[4] if len(parts) > 4 else '.'
        rules.append({'strip': parts[2], 'add': parts[3], 'cond': cond})
    return rules

def generate_block():
    lefts = parse_rules(rule_left_raw)
    rights = parse_rules(rule_right_raw)
    new_rules = []

    for left in lefts:
        for right in rights:
            if left['strip'] != '0':
                if not right['add'].startswith(left['strip']):
                    continue
                combined = left['add'] + right['add'][len(left['strip']):]
            else:
                combined = left['add'] + right['add']

            if left['cond'] != '.':
                if not re.match(left['cond'], right['add']):
                    continue

            new_rules.append({'strip': right['strip'], 'add': combined, 'cond': right['cond']})

    out_flag = "GL"
    left_desc = FLAG_DESCRIPTIONS.get("FP", "FP")
    right_desc = FLAG_DESCRIPTIONS.get("OR", "OR")
    comment_line = "# Cross product of {} ({}) and {} ({}) to {}".format(
        "FP", left_desc, "OR", right_desc, out_flag
    )

    output = ["PFX {} Y {}".format(out_flag, len(new_rules))]
    for r in new_rules:
        output.append("PFX {} {} {} {}".format(out_flag, r['strip'], r['add'], r['cond']))

    return (out_flag, "\n".join([comment_line] + output) + "\n")

def main():
    if not os.path.exists(AFF_FILE):
        print("Error: {} not found.".format(AFF_FILE))
        return

    out_flag, block = generate_block()

    with open(AFF_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    first_flag_idx = None
    last_flag_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("PFX {} ".format(out_flag)):
            if first_flag_idx is None:
                first_flag_idx = i
            last_flag_idx = i

    if first_flag_idx is not None and first_flag_idx > 0:
        prev_line = lines[first_flag_idx - 1].strip()
        if prev_line.startswith("# Cross product"):
            start_idx = first_flag_idx - 1
        else:
            start_idx = first_flag_idx
    elif first_flag_idx is not None:
        start_idx = first_flag_idx
    else:
        start_idx = None

    if start_idx is not None and last_flag_idx is not None:
        # Replace existing block in-place.
        new_lines = lines[:start_idx] + [block] + lines[last_flag_idx + 1:]
    else:
        # Insert before an anchor flag if requested; otherwise append.
        insert_idx = None
        if INSERT_BEFORE_FLAG:
            anchor_prefix = "PFX {} ".format(INSERT_BEFORE_FLAG)
            for i, line in enumerate(lines):
                if line.strip().startswith(anchor_prefix):
                    insert_idx = i
                    # If the anchor PFX block is preceded by one or more cross-product
                    # comment lines, insert before those comments to keep them attached
                    # to the anchor block.
                    while insert_idx > 0 and lines[insert_idx - 1].strip().startswith("# Cross product"):
                        insert_idx -= 1
                    break

        if insert_idx is not None:
            new_lines = lines[:insert_idx] + [block] + lines[insert_idx:]
        else:
            new_lines = lines
            if new_lines and not new_lines[-1].endswith(chr(10)):
                new_lines[-1] += chr(10)
            new_lines.append(block)

    with open(AFF_FILE, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    print("{}: updated in place.".format(out_flag))

if __name__ == '__main__':
    main()
