"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Repo root (one level above this Django project folder).
REPO_ROOT = BASE_DIR.parent

# Default Hunspell sources.
HUNSPELL_AFF_PATH = REPO_ROOT / "Luganda.aff"
HUNSPELL_DIC_SOURCE_PATH = REPO_ROOT / "Luganda.dic"

# Server-side working output.
DATA_DIR = BASE_DIR / "data"
WORKING_DIR = DATA_DIR / "working"
WORKING_DIC_PATH = WORKING_DIR / "Luganda.dic"

# Warm expensive Hunspell .aff parsing caches at startup.
WARM_AFF_CACHE_ON_STARTUP = True

# Repo root (contains Luganda.aff and Luganda.dic)
REPO_DIR = BASE_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

def _env_bool(name: str, default: bool = False) -> bool:
    v = (os.environ.get(name) or "").strip().lower()
    if v == "":
        return default
    return v in {"1", "true", "yes", "y", "on"}


_render_hostname = (os.environ.get("RENDER_EXTERNAL_HOSTNAME") or "").strip()


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-1hd23+-=+q@^6+a#bz7+dve%#!o6e+h*8%ss=%g3_3pm02f8#y",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", default=not bool(_render_hostname))

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

if _render_hostname:
    ALLOWED_HOSTS.append(_render_hostname)

_extra_allowed_hosts = (os.environ.get("ALLOWED_HOSTS") or "").strip()
if _extra_allowed_hosts:
    ALLOWED_HOSTS.extend([h.strip() for h in _extra_allowed_hosts.split(",") if h.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'review',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.csrf',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

_db = dj_database_url.config(
    default=f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}",
    conn_max_age=600,
)

# Only enforce SSL settings for network databases (e.g. Postgres).
if not DEBUG and _db.get("ENGINE") != "django.db.backends.sqlite3":
    options = dict(_db.get("OPTIONS") or {})
    options.setdefault("sslmode", "require")
    _db["OPTIONS"] = options

DATABASES = {"default": _db}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

if _render_hostname:
    CSRF_TRUSTED_ORIGINS = [f"https://{_render_hostname}"]
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Hunspell source/working files
HUNSPELL_AFF_PATH = REPO_DIR / "Luganda.aff"
HUNSPELL_DIC_SOURCE_PATH = REPO_DIR / "Luganda.dic"
HUNSPELL_DIC_WORKING_PATH = REPO_DIR / "working" / "Luganda.dic"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
